local config = {
  str_help_pet_zzgl = "지원 오로리안:",
  str_help_pet_glzz = "지원 관리",
  str_help_pet_wfzz = "지원 불가",
  str_help_pet_shui = "물",
  str_help_pet_huo = "불",
  str_help_pet_sen = "숲",
  str_help_pet_lei = "번개",
  str_help_pet_xtyz = "<color=#c4c4c4>시스템 지원</color>",
  str_help_pet_hyyz = "<color=#34c5db>친구 지원</color>",
  str_help_pet_zb = "장비",
  str_help_pet_glxx = "지원 오로리안마다 매일 1회만 사용할 수 있습니다.",
  str_help_pet_sx = "갱신",
  str_help_pet_zcs = "지원 총 횟수",
  str_help_pet_zjqtzcs = "최근 7일 총 횟수",
  str_help_pet_zjmyzzjl = "최근 지원 기록이 없습니다.",
  str_help_pet_zjqtzztj = "최근 7일 지원 통계:",
  str_help_pet_wdzzgl = "나의 지원 오로리안",
  str_help_pet_ci = "<color=#efc602>{1}</color>회",
  str_help_pet_error_Fail = "실패",
  str_help_pet_error_Succ = "성공",
  str_help_pet_error_Sql = "데이터 오류",
  str_help_pet_error_DB = "데이터 오류",
  str_help_pet_error_Pet = "데이터 오류",
  str_help_pet_error_PetType = "데이터 오류",
  str_help_pet_error_ModuleLock = "기능 잠김",
  str_help_pet_weizhi = "지원 오로리안은 위치를 변경할 수 없습니다.",
  str_help_pet_xzzz = "지원 선택",
  str_help_pet_zjqtzzcs = "최근 7일 지원 횟수",
  str_help_pet_glxq = "오로리안 정보",
  str_help_pet_lglv = "장비 Lv.{1}",
  str_help_pet_wlg = "<color=#c4c4c4>장비 없음</color>",
  str_help_pet_wfhdjl = "지원 사용 시 3성 보상을 획득할 수 없습니다.",
  str_help_pet_cgkwfsyzzgl = "본 스테이지는 지원 오로리안을 사용할 수 없습니다.",
  str_help_pet_zcsx = "{1}초 후 새로고침 가능",
  str_help_pet_zzszcg = "지원 설정 성공",
  str_help_pet_syzz = "(지원 사용)",
  str_help_pet_xyjfgl = "편대 내 최소 1명의 아군 오로리안이 필요합니다.",
  str_help_pet_yczxx = "편대에 {1}(이)가 있습니다.",
  str_help_pet_default_user1 = "Mikeghb65",
  str_help_pet_default_user2 = "Dhehonj",
  str_help_pet_default_user3 = "MoonShad",
  str_help_pet_default_user4 = "sjf55206",
  str_help_pet_default_user5 = "Billroken",
  str_help_pet_default_user6 = "Miyate",
  str_help_pet_default_user7 = "Broeya030",
  str_help_pet_default_user8 = "Eathreaye",
  str_help_pet_default_user9 = "YellowBB",
  str_help_pet_default_user10 = "Chaopen",
  str_help_pet_no_filter = "미선택"
}
return config
