local L0_1, L1_1, L2_1, L3_1
L0_1 = {}
L1_1 = {}
L1_1.m_CutScenProcessKey = 1
L1_1.m_CutScenID = 11650902
L1_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_MAID_C_MASK_SUMMER"
L1_1.m_bWaitClick = false
L1_1.m_fWaitTime = 0
L1_1.m_StartBGMFileName = "CUTSCENE_HOPE"
L2_1 = {}
L2_1.m_CutScenKey_Talk = "LIFETIME_END_NKM_UNIT_MAID_C_MASK_SUMMER@2#Talk"
L2_1.m_CutScenProcessKey = 2
L2_1.m_CutScenID = 11650902
L2_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_MAID_C_MASK_SUMMER"
L2_1.m_bWaitClick = true
L2_1.m_fWaitTime = 0
L2_1.m_BGFileName = "LIFETIME"
L2_1.m_Face = "UNIT_LAUGH"
L2_1.m_CharStrID = "MASK_FLORA_SUMMER_NULL"
L2_1.m_Pos = "C"
L2_1.m_Talk_KOREA = "사람이라면 누구나 마지막은 흙을 요람 삼아 잠드는 법이죠. 주인님께서 영원한 평온을 얻으실 그날까지, 주인님의 머리맡을 지키고 있겠습니다."
L2_1.m_fTalkTime = 0.03
L2_1.m_Talk_JPN = "人間は誰しも最期は土に還ります。ご主人様が安らかな眠りにつくその日まで、ご主人様の枕元を守ります。"
L2_1.m_Talk_ENG = "Everyone goes back to dust in the end. I'll sit at your bedside until you find eternal peace, Master."
L2_1.m_Talk_TWN = "只要是人，最後都會把泥土當作搖籃睡覺。直到主人獲得永遠安息的那一天，我都會守護在主人的枕邊。"
L2_1.m_Talk_THA = "สุดท้ายทุกคนก็กลับกลายเป็นเถ้าธุลี ฉันจะนั่งอยู่ข้างเตียงของคุณจนกว่าคุณจะได้พบกับความสงบชั่วนิรันดร์ค่ะ มาสเตอร์"
L2_1.m_Talk_VTN = "Ai rồi cũng về với cát bụi. Tôi sẽ ngồi bên cạnh giường của ngài cho đến khi ngài tìm thấy sự yên bình vĩnh viễn, sếp."
L2_1.m_Talk_SCN = "人到了生命的尽头都会尘归大地。我会守在主人身边，直到您永远安眠的那一天。"
L2_1.m_Talk_DEU = "Am Ende zerfällt jeder wieder zu Staub. Ich werde an Ihrem Bett sitzen, bis Sie den ewigen Frieden gefunden haben, Meister."
L2_1.m_Talk_FRA = "À la fin, nous retournons tous à la terre. Je serai à vos côtés jusqu'à ce que vous trouviez la paix éternelle, maître."
L3_1 = {}
L3_1.m_CutScenProcessKey = 3
L3_1.m_CutScenID = 11650902
L3_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_MAID_C_MASK_SUMMER"
L3_1.m_bWaitClick = false
L3_1.m_fWaitTime = 0
L3_1.m_bFadeIn = false
L3_1.m_fFadeTime = 3
L3_1.m_bFadeWhite = true
L0_1[1] = L1_1
L0_1[2] = L2_1
L0_1[3] = L3_1
m_dicNKCCutScenTempletByID = L0_1
