local L0_1, L1_1, L2_1, L3_1, L4_1, L5_1, L6_1, L7_1, L8_1, L9_1, L10_1, L11_1, L12_1, L13_1, L14_1, L15_1, L16_1, L17_1, L18_1, L19_1, L20_1, L21_1, L22_1, L23_1, L24_1, L25_1, L26_1, L27_1, L28_1, L29_1, L30_1, L31_1, L32_1
L0_1 = {}
L1_1 = {}
L1_1.m_CutScenProcessKey = 1
L1_1.m_CutScenID = 12540001
L1_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L1_1.m_bWaitClick = false
L1_1.m_fWaitTime = 0
L2_1 = {}
L2_1.m_CutScenProcessKey = 2
L2_1.m_CutScenID = 12540001
L2_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L2_1.m_bWaitClick = false
L2_1.m_fWaitTime = 0
L2_1.m_BGFileName = "BLACK"
L2_1.m_bFadeIn = true
L2_1.m_fFadeTime = 1.5
L2_1.m_StartBGMFileName = "CUTSCENE_SILENCE"
L3_1 = {}
L3_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@3#Talk"
L3_1.m_CutScenProcessKey = 3
L3_1.m_CutScenID = 12540001
L3_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L3_1.m_bWaitClick = true
L3_1.m_fWaitTime = 0
L3_1.m_Talk_KOREA = "오랜 고민 끝에, 당신은 한 가지 중요한 사실을 깨달았다."
L3_1.m_fTalkTime = 0.03
L3_1.m_Talk_JPN = "長い間悩んだ結果、あなたは一つ大事なことに気づいた。"
L3_1.m_Talk_ENG = "After much debate, you came to the conclusion"
L3_1.m_Talk_TWN = "苦惱許久後，你意識到一個重要的事實。"
L3_1.m_Talk_THA = "หลังจากหารือถกเถียงกันอย่างหนักหน่วง คุณก็ได้ข้อสรุป"
L3_1.m_Talk_VTN = "Sau nhiều cuộc tranh luận, ngài đã đi đến kết luận,"
L3_1.m_Talk_SCN = "苦恼许久后，你意识到一件重要的事实。"
L3_1.m_Talk_DEU = "Nach langen Überlegungen bist du zum Schluss gekommen,"
L3_1.m_Talk_FRA = "Après un long moment de réflexion et de nombreuses délibérations,"
L4_1 = {}
L4_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@4#Talk"
L4_1.m_CutScenProcessKey = 4
L4_1.m_CutScenID = 12540001
L4_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L4_1.m_bWaitClick = true
L4_1.m_fWaitTime = 0
L4_1.m_Talk_KOREA = "줄곧 생각해 온 그녀야말로, 앞으로 마주할 운명에서 꼭 필요한 존재라는 것을."
L4_1.m_fTalkTime = 0.03
L4_1.m_Talk_JPN = "ずっと考えてきた彼女だからこそ、これから向き合う運命に必ず必要な存在であることを。"
L4_1.m_Talk_ENG = "that this employee, whom you'd been giving a lot of thought to, was absolutely necessary for the future ahead."
L4_1.m_Talk_TWN = "一直盤踞在腦海中的她，是你在未來必須要面對的命運中，一個不可或缺的存在。"
L4_1.m_Talk_THA = "ว่าพนักงานคนนี้ ซึ่งเป็นคนที่คุณพิจารณาอย่างละเอียดถี่ถ้วน เป็นบุคลากรที่มีความสำคัญอย่างยิ่งกับอนาคตภายภาคหน้า"
L4_1.m_Talk_VTN = "với sự suy xét kỹ càng, người nhân viên này là hoàn toàn cần thiết cho tương lai phía trước của ngài."
L4_1.m_Talk_SCN = "经过长久的思考，你明白在今后即将面对的命运中，她是必不可少的存在。"
L4_1.m_Talk_DEU = "dass diese Mitarbeiterin, über die du so viel nachgedacht hast, absolut unverzichtbar für die Zukunft des Unternehmens ist."
L4_1.m_Talk_FRA = "vous êtes arrivé à la conclusion que cette employée était un élément vital pour votre entreprise et son futur."
L5_1 = {}
L5_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@5#Talk"
L5_1.m_CutScenProcessKey = 5
L5_1.m_CutScenID = 12540001
L5_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L5_1.m_bWaitClick = true
L5_1.m_fWaitTime = 0
L5_1.m_Talk_KOREA = "그리하여 당신은 결심했다."
L5_1.m_fTalkTime = 0.03
L5_1.m_Talk_JPN = "そして、あなたは決心した。"
L5_1.m_Talk_ENG = "So, you've decided"
L5_1.m_Talk_TWN = "所以你決定了。"
L5_1.m_Talk_THA = "ดังนั้น คุณจึงตัดสินใจ"
L5_1.m_Talk_VTN = "Vậy nên ngài đã quyết định"
L5_1.m_Talk_SCN = "所以你下定决心。"
L5_1.m_Talk_DEU = "Daher hast du beschlossen,"
L5_1.m_Talk_FRA = "Vous avez donc décidé"
L6_1 = {}
L6_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@6#Talk"
L6_1.m_CutScenProcessKey = 6
L6_1.m_CutScenID = 12540001
L6_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L6_1.m_bWaitClick = true
L6_1.m_fWaitTime = 0
L6_1.m_Talk_KOREA = "이 세계에서 어떤 결말을 마주하더라도, 마지막까지 그녀와 함께하기로."
L6_1.m_fTalkTime = 0.03
L6_1.m_Talk_JPN = "この世界でどのような結末を迎えるとしても、最後まで彼女とともにいることを。"
L6_1.m_Talk_ENG = "that you'll be with her, no matter the consequences."
L6_1.m_Talk_TWN = "不管這個世界會迎來怎樣的結局，你都要和她一起走到最後。"
L6_1.m_Talk_THA = "ว่าจะอยู่เคียงข้างเธอ ไม่ว่าจะเกิดอะไรขึ้นต่อจากนี้ก็ตาม"
L6_1.m_Talk_VTN = "rằng ngài sẽ chọn cô ấy, bất chấp hậu quả ra sao."
L6_1.m_Talk_SCN = "不管这个世界会迎来怎样的结局，你都要和她一起走到最后。"
L6_1.m_Talk_DEU = "sie an dich zu binden, egal was auch geschieht."
L6_1.m_Talk_FRA = "de rester à ses côtés et la soutenir, peu importe les conséquences."
L7_1 = {}
L7_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@7#Talk"
L7_1.m_CutScenProcessKey = 7
L7_1.m_CutScenID = 12540001
L7_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L7_1.m_bWaitClick = true
L7_1.m_fWaitTime = 0
L7_1.m_Talk_KOREA = "마음의 준비를 마치고 사장실로 호출하자, 곧 도착한다는 응답이 돌아왔다."
L7_1.m_fTalkTime = 0.03
L7_1.m_Talk_JPN = "意を決して社長室へ呼び出すと、もうすぐ着くとの応答が返ってきた。"
L7_1.m_Talk_ENG = "Having decided that, you called her to your office. She said she'd be here soon."
L7_1.m_Talk_TWN = "下定決心後，你呼叫她到老闆辦公室，得到回應說她馬上就到。"
L7_1.m_Talk_THA = "เมื่อตัดสินใจเช่นนั้นแล้ว คุณจึงเชิญเธอมาที่ห้องทำงาน และเธอก็บอกว่าจะมาหาในไม่ช้า"
L7_1.m_Talk_VTN = "Sau khi quyết định, ngài đã gọi cô ấy đến văn phòng. Cô ấy cho biết mình sẽ sớm có mặt tại đây."
L7_1.m_Talk_SCN = "做好心理准备后，你将她传唤到老板办公室，得到回应说她马上就到。"
L7_1.m_Talk_DEU = "Also hast du sie in dein Büro gerufen. Sie sagte, sie wolle bald da sein."
L7_1.m_Talk_FRA = "Fort de cette décision, vous l'avez convoquée dans votre bureau. Elle ne devrait pas tarder."
L8_1 = {}
L8_1.m_CutScenProcessKey = 8
L8_1.m_CutScenID = 12540001
L8_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L8_1.m_bWaitClick = false
L8_1.m_fWaitTime = 0.4
L8_1.m_fFlashBangTime = 0.25
L8_1.m_StartFXSoundName = "FX_CUTSCEN_KNOCK_WOOD"
L9_1 = {}
L9_1.m_CutScenProcessKey = 9
L9_1.m_CutScenID = 12540001
L9_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L9_1.m_bWaitClick = false
L9_1.m_fWaitTime = 0.4
L9_1.m_fFlashBangTime = 0.25
L10_1 = {}
L10_1.m_CutScenProcessKey = 10
L10_1.m_CutScenID = 12540001
L10_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L10_1.m_bWaitClick = false
L10_1.m_fWaitTime = 1.5
L10_1.m_fFlashBangTime = 0.25
L11_1 = {}
L11_1.m_CutScenProcessKey = 11
L11_1.m_CutScenID = 12540001
L11_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L11_1.m_bWaitClick = false
L11_1.m_fWaitTime = 0
L11_1.m_bFadeIn = false
L11_1.m_fFadeTime = 2
L12_1 = {}
L12_1.m_CutScenProcessKey = 12
L12_1.m_CutScenID = 12540001
L12_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L12_1.m_bWaitClick = false
L12_1.m_fWaitTime = 1
L12_1.m_BGFileName = "LIFETIME"
L12_1.m_bFadeIn = true
L12_1.m_fFadeTime = 3
L12_1.m_StartBGMFileName = "CUTSCENE_HOPE"
L12_1.m_StartFXSoundName = "FX_CUTSCEN_DOOR_WOOD"
L12_1.m_CharStrID = "BASSOON_HARMONY_NULL_NULL"
L12_1.m_Pos = "C_D"
L13_1 = {}
L13_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@13#Talk"
L13_1.m_CutScenProcessKey = 13
L13_1.m_CutScenID = 12540001
L13_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L13_1.m_bWaitClick = true
L13_1.m_fWaitTime = 0
L13_1.m_CharStrID = "BASSOON_HARMONY_NULL_NULL"
L13_1.m_Pos = "C"
L13_1.m_Talk_KOREA = "나는 알 수 있어."
L13_1.m_fTalkTime = 0.03
L13_1.m_Talk_JPN = "私にはわかるわ。"
L13_1.m_Talk_ENG = "I can tell."
L13_1.m_Talk_TWN = "我知道。"
L13_1.m_Talk_THA = "ฉันบอกได้"
L13_1.m_Talk_VTN = "Tôi có thể biết được."
L13_1.m_Talk_SCN = "我能感觉到。"
L13_1.m_Talk_DEU = "Ich kann es sehen."
L13_1.m_Talk_FRA = "Je peux le sentir."
L14_1 = {}
L14_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@14#Talk"
L14_1.m_CutScenProcessKey = 14
L14_1.m_CutScenID = 12540001
L14_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L14_1.m_bWaitClick = true
L14_1.m_fWaitTime = 0
L14_1.m_CharStrID = "BASSOON_HARMONY_NULL_NULL"
L14_1.m_Pos = "C"
L14_1.m_Talk_KOREA = "당신도 우리와 마찬가지로 죄 많은 사람이라는 걸."
L14_1.m_fTalkTime = 0.03
L14_1.m_Talk_JPN = "あなたも私たちと同じで罪深い人だってことが。"
L14_1.m_Talk_ENG = "That you, like us, are a sinful person."
L14_1.m_Talk_TWN = "你和我們一樣也是罪孽深重的人。"
L14_1.m_Talk_THA = "ว่าคุณเป็นคนบาปเหมือนเรา"
L14_1.m_Talk_VTN = "Rằng ngài, giống như chúng tôi, là một người đầy tội lỗi."
L14_1.m_Talk_SCN = "你和我们一样，也是背负着罪恶的人。"
L14_1.m_Talk_DEU = "Dass Sie, genau wie wir, ein Mensch voller Sünden sind."
L14_1.m_Talk_FRA = "Comme nous, tu as commis de nombreux péchés."
L15_1 = {}
L15_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@15#Talk"
L15_1.m_CutScenProcessKey = 15
L15_1.m_CutScenID = 12540001
L15_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L15_1.m_bWaitClick = true
L15_1.m_fWaitTime = 0
L15_1.m_Face = "UNIT_DESPAIR"
L15_1.m_CharStrID = "BASSOON_HARMONY_NULL_NULL"
L15_1.m_Pos = "C"
L15_1.m_Talk_KOREA = "……왜 그렇게 생각하냐고?"
L15_1.m_fTalkTime = 0.03
L15_1.m_Talk_JPN = "……どうしてそう思うのかって？"
L15_1.m_Talk_ENG = "...Why do I think so?"
L15_1.m_Talk_TWN = "……我為什麼會這麼想？"
L15_1.m_Talk_THA = "...ทำไมฉันถึงคิดอย่างนั้นหรอ?"
L15_1.m_Talk_VTN = "...Tại sao tôi lại nghĩ vậy?"
L15_1.m_Talk_SCN = "……为什么这么想？"
L15_1.m_Talk_DEU = "... Warum ich so denke?"
L15_1.m_Talk_FRA = "... ce qui me fait penser ça ?"
L16_1 = {}
L16_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@16#Talk"
L16_1.m_CutScenProcessKey = 16
L16_1.m_CutScenID = 12540001
L16_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L16_1.m_bWaitClick = true
L16_1.m_fWaitTime = 0
L16_1.m_CharStrID = "BASSOON_HARMONY_NULL_NULL"
L16_1.m_Pos = "C"
L16_1.m_Talk_KOREA = "당신 주위에는 항상 비가 내리니까."
L16_1.m_fTalkTime = 0.03
L16_1.m_Talk_JPN = "あなたの周りにはいつも雨が降っているから。"
L16_1.m_Talk_ENG = "Because it is always raining around you."
L16_1.m_Talk_TWN = "因為你的周圍總是會下雨。"
L16_1.m_Talk_THA = "เพราะฝนจะตกรอบตัวคุณอยู่เสมอ"
L16_1.m_Talk_VTN = "Bởi vì xung quanh ngài luôn có mưa."
L16_1.m_Talk_SCN = "因为你周围总是会下雨。"
L16_1.m_Talk_DEU = "Weil es um Sie herum immer regnet."
L16_1.m_Talk_FRA = "La pluie. Il pleut toujours autour de toi."
L17_1 = {}
L17_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@17#Talk"
L17_1.m_CutScenProcessKey = 17
L17_1.m_CutScenID = 12540001
L17_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L17_1.m_bWaitClick = true
L17_1.m_fWaitTime = 0
L17_1.m_CharStrID = "BASSOON_HARMONY_NULL_NULL"
L17_1.m_Pos = "C"
L17_1.m_Talk_KOREA = "아주 어둡고… 차가운 물안개를 일으키는 비가."
L17_1.m_fTalkTime = 0.03
L17_1.m_Talk_JPN = "とても暗くて……冷たい霧を生む雨がね。"
L17_1.m_Talk_ENG = "Rain that... creates this gloomy, icy mist."
L17_1.m_Talk_TWN = "使周圍變暗……引起冰冷霧水的雨。"
L17_1.m_Talk_THA = "ฝนที่...ทำให้เกิดหมอกหนาทึบนี้"
L17_1.m_Talk_VTN = "Cơn mưa... tạo nên màn sương mù băng giá ảm đạm này."
L17_1.m_Talk_SCN = "极其黑暗的……带起冰冷水雾的雨。"
L17_1.m_Talk_DEU = "Regen, der ... diesen unglaublich düsteren, eisigen Nebel erzeugt."
L17_1.m_Talk_FRA = "Une pluie... accompagnée d’une brume sombre et glaciale."
L18_1 = {}
L18_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@18#Talk"
L18_1.m_CutScenProcessKey = 18
L18_1.m_CutScenID = 12540001
L18_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L18_1.m_bWaitClick = true
L18_1.m_fWaitTime = 0
L18_1.m_CharStrID = "BASSOON_HARMONY_NULL_NULL"
L18_1.m_Pos = "C"
L18_1.m_Talk_KOREA = "혼자서 많은 것을 짊어지고 있었지?"
L18_1.m_fTalkTime = 0.03
L18_1.m_Talk_JPN = "一人で多くのことを背負っていたでしょう？"
L18_1.m_Talk_ENG = "You carry a lot of burden by yourself, don't you?"
L18_1.m_Talk_TWN = "你一定獨自背負著很多東西吧？"
L18_1.m_Talk_THA = "ตัวเองแบกภาระหนักมากใช่ไหม?"
L18_1.m_Talk_VTN = "Một mình ngài đã chịu rất nhiều gánh nặng phải không?"
L18_1.m_Talk_SCN = "你一定独自肩负着很多东西吧？"
L18_1.m_Talk_DEU = "Sie tragen eine Menge Last alleine mit Ihnen herum, nicht wahr?"
L18_1.m_Talk_FRA = "Tu portes un lourd fardeau sur les épaules, n’est-ce pas ?"
L19_1 = {}
L19_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@19#Talk"
L19_1.m_CutScenProcessKey = 19
L19_1.m_CutScenID = 12540001
L19_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L19_1.m_bWaitClick = true
L19_1.m_fWaitTime = 0
L19_1.m_Face = "UNIT_IDLE"
L19_1.m_CharStrID = "BASSOON_HARMONY_NULL_NULL"
L19_1.m_Pos = "C"
L19_1.m_Talk_KOREA = "무언가를 짊어지고 있는지는 사람마다 달라."
L19_1.m_fTalkTime = 0.03
L19_1.m_Talk_JPN = "何を背負っているかは、人によって違うわ。"
L19_1.m_Talk_ENG = "What people carry differs for each person."
L19_1.m_Talk_TWN = "每個人都背負著不同的東西。"
L19_1.m_Talk_THA = "สิ่งที่ผู้คนพกติดตัวแตกต่างกันไปในแต่ละคน"
L19_1.m_Talk_VTN = "Thứ mọi người phải chịu đều khác nhau."
L19_1.m_Talk_SCN = "每个人都肩负着不同的东西。"
L19_1.m_Talk_DEU = "Die Last, die ein Mensch mit sich herumträgt, ist von Person zu Person unterschiedlich."
L19_1.m_Talk_FRA = "Chacun porte sa croix, comme on dit."
L20_1 = {}
L20_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@20#Talk"
L20_1.m_CutScenProcessKey = 20
L20_1.m_CutScenID = 12540001
L20_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L20_1.m_bWaitClick = true
L20_1.m_fWaitTime = 0
L20_1.m_CharStrID = "BASSOON_HARMONY_NULL_NULL"
L20_1.m_Pos = "C"
L20_1.m_Crash = 15
L20_1.m_Talk_KOREA = "죄책감일 수도 있고, 책임감일 수도 있고, 어떤 사람은 사명감이기도 했어."
L20_1.m_fTalkTime = 0.03
L20_1.m_Talk_JPN = "罪悪感かもしれないし、責任感かもしれない。使命感という人もいたわね。"
L20_1.m_Talk_ENG = "It could be guilt, a sense of responsibility, or for some, a sense of duty."
L20_1.m_Talk_TWN = "可能是罪惡感，可能是責任感，也有可能是使命感。"
L20_1.m_Talk_THA = "อาจเป็นความรู้สึกผิด ความรู้สึกรับผิดชอบ หรือสำหรับบางคน ความรู้สึกถึงหน้าที่"
L20_1.m_Talk_VTN = "Đó có thể là cảm giác tội lỗi, ý thức trách nhiệm hoặc đối với một số người, đó là ý thức về nhiệm vụ."
L20_1.m_Talk_SCN = "可能是罪恶感，可能是责任感，也有可能是使命感。"
L20_1.m_Talk_DEU = "Es könnte Schuld sein, es könnte ein Verantwortungsgefühl sein oder für manche könnte es auch ein Pflichtgefühl sein."
L20_1.m_Talk_FRA = "De la culpabilité, des responsabilités... et pour certains, un sens du devoir."
L21_1 = {}
L21_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@21#Talk"
L21_1.m_CutScenProcessKey = 21
L21_1.m_CutScenID = 12540001
L21_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L21_1.m_bWaitClick = true
L21_1.m_fWaitTime = 0
L21_1.m_CharStrID = "BASSOON_HARMONY_NULL_NULL"
L21_1.m_Pos = "C"
L21_1.m_Talk_KOREA = "하지만 사람은 그렇게 강인하지 않아. 내 연주를 들은 이들이 금방 참을성을 잃는 것처럼."
L21_1.m_fTalkTime = 0.03
L21_1.m_Talk_JPN = "でも、人はそう強くはないわ。私の演奏を聞いた人がすぐに耐えられなくなるように。"
L21_1.m_Talk_ENG = "But people are not as strong as they think. Much like those who lose their patience after hearing my performance."
L21_1.m_Talk_TWN = "但人類並沒有那麼堅強，所以聽到我的演奏的人都會很快就失去耐性。"
L21_1.m_Talk_THA = "แต่คนไม่ได้เข้มแข็งอย่างที่คิด เช่นเดียวกับคนที่หมดความอดทนหลังจากได้ยินการแสดงของฉัน"
L21_1.m_Talk_VTN = "Nhưng con người không mạnh mẽ như họ nghĩ. Giống như những người mất kiên nhẫn sau khi nghe tôi chơi."
L21_1.m_Talk_SCN = "但人类并没有那么坚强。所以听到我的演奏的人都会很快失去耐性。"
L21_1.m_Talk_DEU = "Aber die Menschen sind nicht so stark, wie sie vielleicht denken. Ähnlich wie diejenigen, die die Geduld verlieren, nachdem sie meine Aufführung gehört haben."
L21_1.m_Talk_FRA = "Mais les gens ne sont pas aussi forts qu'ils le pensent. Il suffit de voir comme ils perdent patience en écoutant mes performances."
L22_1 = {}
L22_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@22#Talk"
L22_1.m_CutScenProcessKey = 22
L22_1.m_CutScenID = 12540001
L22_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L22_1.m_bWaitClick = true
L22_1.m_fWaitTime = 0
L22_1.m_Face = "UNIT_DESPAIR"
L22_1.m_CharStrID = "BASSOON_HARMONY_NULL_NULL"
L22_1.m_Pos = "C"
L22_1.m_Talk_KOREA = "결국 늦든, 빠르든."
L22_1.m_fTalkTime = 0.03
L22_1.m_Talk_JPN = "結局のところ、遅かれ早かれ。"
L22_1.m_Talk_ENG = "Whether it's fast or slow."
L22_1.m_Talk_TWN = "無論早或晚，"
L22_1.m_Talk_THA = "ไม่ว่าจะเร็วหรือช้า..."
L22_1.m_Talk_VTN = "Dù nhanh hay chậm."
L22_1.m_Talk_SCN = "不管来得迟，还是来得早。"
L22_1.m_Talk_DEU = "Ob es nun schnell oder langsam ist ..."
L22_1.m_Talk_FRA = "Qu’il vienne lentement ou rapidement..."
L23_1 = {}
L23_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@23#Talk"
L23_1.m_CutScenProcessKey = 23
L23_1.m_CutScenID = 12540001
L23_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L23_1.m_bWaitClick = true
L23_1.m_fWaitTime = 0
L23_1.m_CharStrID = "BASSOON_HARMONY_NULL_NULL"
L23_1.m_Pos = "C"
L23_1.m_Talk_KOREA = "갑작스럽든, 예정되었든. 모든 것과 작별하고 싶은 시기가 오고 말아."
L23_1.m_fTalkTime = 0.03
L23_1.m_Talk_JPN = "突然であれ、予定されていたことであれ。すべてに別れを告げたくなる時がやってきてしまう。"
L23_1.m_Talk_ENG = "Sudden or expected. The time when one wants to part with everything eventually arrives."
L23_1.m_Talk_TWN = "事發突然或是早有預兆，終究會有想跟一切告別的時候來臨。"
L23_1.m_Talk_THA = "ฉับพลันหรือคาดหวัง เวลาที่ใครอยากจะจากไปกับทุกสิ่งทุกอย่างก็มาถึงในที่สุด"
L23_1.m_Talk_VTN = "Đột ngột hoặc dự kiến. Thời điểm người ta muốn rời xa mọi thứ cuối cùng cũng đến."
L23_1.m_Talk_SCN = "不管事发突然，还是早有预兆。与所有的一切道别的时间终将会到来。"
L23_1.m_Talk_DEU = "Plötzlich oder erwartet. Irgendwann kommt die Zeit, in der man sich von allem trennen möchte."
L23_1.m_Talk_FRA = "Qu’il soit soudain ou qu’on l’ait attendu... vient toujours un moment où l’on désire se séparer de tout."
L24_1 = {}
L24_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@24#Talk"
L24_1.m_CutScenProcessKey = 24
L24_1.m_CutScenID = 12540001
L24_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L24_1.m_bWaitClick = true
L24_1.m_fWaitTime = 0
L24_1.m_CharStrID = "BASSOON_HARMONY_NULL_NULL"
L24_1.m_Pos = "C"
L24_1.m_Talk_KOREA = "그러지 않으려는 사람들은…. 결국 덜어내는 방법을 배우게 돼."
L24_1.m_fTalkTime = 0.03
L24_1.m_Talk_JPN = "それを避けようとする人も……結局は楽になる方法を身につけるようになるわ。"
L24_1.m_Talk_ENG = "For those who try not to... they learn how to lessen it."
L24_1.m_Talk_TWN = "有些人不希望這種事發生…因此會學會減輕自己肩上的負擔。"
L24_1.m_Talk_THA = "สำหรับผู้ที่พยายามไม่ทำ... พวกเขาจะเรียนรู้วิธีลดมันลง"
L24_1.m_Talk_VTN = "Đối với những người cố gắng không làm vậy... họ học cách giảm bớt nó."
L24_1.m_Talk_SCN = "有些人不希望这种事发生……因此会学会减轻自己肩上的负担。"
L24_1.m_Talk_DEU = "Auch diejenigen, die versuchen, es nicht zu tun ... Irgendwann muss jeder mal lernen, loszulassen."
L24_1.m_Talk_FRA = "Ceux qui essaient de s’y refuser... apprennent simplement à le contenir."
L25_1 = {}
L25_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@25#Talk"
L25_1.m_CutScenProcessKey = 25
L25_1.m_CutScenID = 12540001
L25_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L25_1.m_bWaitClick = true
L25_1.m_fWaitTime = 0
L25_1.m_CharStrID = "BASSOON_HARMONY_NULL_NULL"
L25_1.m_Pos = "C"
L25_1.m_Talk_KOREA = "스스로 짊어진 것들에 짓눌리지 않기 위해."
L25_1.m_fTalkTime = 0.03
L25_1.m_Talk_JPN = "自分が背負っているものに押しつぶされないようにね。"
L25_1.m_Talk_ENG = "To avoid being crushed by their burden."
L25_1.m_Talk_TWN = "才不會讓那些所謂的責任把自己壓得喘不過氣。"
L25_1.m_Talk_THA = "เพื่อไม่ให้ถูกภาระทับถม"
L25_1.m_Talk_VTN = "Để tránh bị đè bẹp do gánh nặng."
L25_1.m_Talk_SCN = "为了避免被自己肩负的东西压得喘不上气。"
L25_1.m_Talk_DEU = "Um nicht von der eigenen Last erdrückt zu werden."
L25_1.m_Talk_FRA = "Pour éviter d'être écrasé par leur propre fardeau."
L26_1 = {}
L26_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@26#Talk"
L26_1.m_CutScenProcessKey = 26
L26_1.m_CutScenID = 12540001
L26_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L26_1.m_bWaitClick = true
L26_1.m_fWaitTime = 0
L26_1.m_Face = "UNIT_IDLE"
L26_1.m_CharStrID = "BASSOON_HARMONY_NULL_NULL"
L26_1.m_Pos = "C"
L26_1.m_Talk_KOREA = "그런데도 당신은…. 아직 포기하지 않았어."
L26_1.m_fTalkTime = 0.03
L26_1.m_Talk_JPN = "それなのにあなたという人は……まだ諦めていない。"
L27_1 = "And yet, you... still have not given up."
L26_1.m_Talk_ENG = L27_1
L27_1 = "但是你……依然沒有放棄。"
L26_1.m_Talk_TWN = L27_1
L27_1 = "แล้วคุณ...ก็ยังไม่ยอมแพ้"
L26_1.m_Talk_THA = L27_1
L27_1 = "Thế nhưng, ngài... vẫn chưa bỏ cuộc."
L26_1.m_Talk_VTN = L27_1
L27_1 = "而你却……依然没有放弃。"
L26_1.m_Talk_SCN = L27_1
L27_1 = "Trotzdem ... haben Sie immer noch nicht aufgegeben."
L26_1.m_Talk_DEU = L27_1
L27_1 = "Mais toi... toi, tu n’as toujours pas abandonné."
L26_1.m_Talk_FRA = L27_1
L27_1 = {}
L28_1 = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@27#Talk"
L27_1.m_CutScenKey_Talk = L28_1
L28_1 = 27
L27_1.m_CutScenProcessKey = L28_1
L27_1.m_CutScenID = 12540001
L27_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L27_1.m_bWaitClick = true
L27_1.m_fWaitTime = 0
L27_1.m_CharStrID = "BASSOON_HARMONY_NULL_NULL"
L27_1.m_Pos = "C"
L28_1 = "오히려 주변에서 다가올 수 없게, 늘 빗속에서 홀로 머물고 있지."
L27_1.m_Talk_KOREA = L28_1
L27_1.m_fTalkTime = 0.03
L28_1 = "むしろ周りを寄せ付けないように、いつも雨の中にひとり留まっているわ。"
L27_1.m_Talk_JPN = L28_1
L28_1 = "Better yet, you stay in the rain alone so no one else can come near."
L27_1.m_Talk_ENG = L28_1
L28_1 = "你反而選擇在雨中獨處，拒絕周圍的人靠近。"
L27_1.m_Talk_TWN = L28_1
L28_1 = "ยังดีกว่าคุณอยู่ท่ามกลางสายฝนคนเดียวเพื่อไม่ให้ใครเข้ามาใกล้ได้"
L27_1.m_Talk_THA = L28_1
L28_1 = "Tốt hơn hết là ngài nên trú mưa một mình để không ai khác có thể đến gần."
L27_1.m_Talk_VTN = L28_1
L28_1 = "你反而选择在雨中独处，拒绝了周围人的靠近。"
L27_1.m_Talk_SCN = L28_1
L28_1 = "Sie bleiben lieber allein im Regen, damit sich Ihnen niemand nähern kann."
L27_1.m_Talk_DEU = L28_1
L28_1 = "Pire encore, tu restes seul sous la pluie pour que personne ne t’approche."
L27_1.m_Talk_FRA = L28_1
L28_1 = {}
L29_1 = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@28#Talk"
L28_1.m_CutScenKey_Talk = L29_1
L29_1 = 28
L28_1.m_CutScenProcessKey = L29_1
L28_1.m_CutScenID = 12540001
L28_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L28_1.m_bWaitClick = true
L28_1.m_fWaitTime = 0
L29_1 = "UNIT_LAUGH"
L28_1.m_Face = L29_1
L28_1.m_CharStrID = "BASSOON_HARMONY_NULL_NULL"
L28_1.m_Pos = "C"
L29_1 = "괜찮아. 이제부터는 내가 곁에 있어 줄게."
L28_1.m_Talk_KOREA = L29_1
L28_1.m_fTalkTime = 0.03
L29_1 = "大丈夫よ。これからは私がそばに居てあげる。"
L28_1.m_Talk_JPN = L29_1
L29_1 = "It's okay. I will be by your side from now on."
L28_1.m_Talk_ENG = L29_1
L29_1 = "沒關係，從今以後，我會陪在你身邊。"
L28_1.m_Talk_TWN = L29_1
L29_1 = "ใช่ ฉันจะอยู่เคียงข้างคุณตั้งแต่นี้เป็นต้นไป"
L28_1.m_Talk_THA = L29_1
L29_1 = "Không sao đâu. Tôi sẽ ở bên cạnh ngài kể từ bây giờ."
L28_1.m_Talk_VTN = L29_1
L29_1 = "没关系的。从今以后，我会陪在你身边。"
L28_1.m_Talk_SCN = L29_1
L29_1 = "Schon okay. Ich werde von nun an Ihrer Seite sein."
L28_1.m_Talk_DEU = L29_1
L29_1 = "Mais ne t’inquiète pas. À partir de maintenant, je serai à tes côtés."
L28_1.m_Talk_FRA = L29_1
L29_1 = {}
L30_1 = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@29#Talk"
L29_1.m_CutScenKey_Talk = L30_1
L30_1 = 29
L29_1.m_CutScenProcessKey = L30_1
L29_1.m_CutScenID = 12540001
L29_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L29_1.m_bWaitClick = true
L29_1.m_fWaitTime = 0
L29_1.m_CharStrID = "BASSOON_HARMONY_NULL_NULL"
L29_1.m_Pos = "C"
L30_1 = "나는 당신의 비, 당신의 안개. 당신의 죽음."
L29_1.m_Talk_KOREA = L30_1
L29_1.m_fTalkTime = 0.03
L30_1 = "私はあなたの雨、あなたの霧。そして、あなたの死。"
L29_1.m_Talk_JPN = L30_1
L30_1 = "I will be your rain, your mist, and your death."
L29_1.m_Talk_ENG = L30_1
L30_1 = "我是你的雨、你的霧、你的死亡。"
L29_1.m_Talk_TWN = L30_1
L30_1 = "ฉันจะเป็นฝน เป็นหมอก และเป็นความตายให้กับคุณเอง"
L29_1.m_Talk_THA = L30_1
L30_1 = "Tôi sẽ là mưa, sương mù và cả cái chết của ngài."
L29_1.m_Talk_VTN = L30_1
L30_1 = "我是你的雨，你的雾，你的死亡。"
L29_1.m_Talk_SCN = L30_1
L30_1 = "Ich werde Ihr Regen, Ihr Nebel und Ihr Tod sein."
L29_1.m_Talk_DEU = L30_1
L30_1 = "Je serai ta pluie, ta brume. Ta mort."
L29_1.m_Talk_FRA = L30_1
L30_1 = {}
L31_1 = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON@30#Talk"
L30_1.m_CutScenKey_Talk = L31_1
L31_1 = 30
L30_1.m_CutScenProcessKey = L31_1
L30_1.m_CutScenID = 12540001
L30_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L30_1.m_bWaitClick = true
L30_1.m_fWaitTime = 0
L30_1.m_CharStrID = "BASSOON_HARMONY_NULL_NULL"
L30_1.m_Pos = "C"
L31_1 = "마지막 작별을 갈구할 때, 나는 당신 곁에 준비되어 있을 테니까."
L30_1.m_Talk_KOREA = L31_1
L30_1.m_fTalkTime = 0.03
L31_1 = "最後に死を切望する時、私はそばにちゃんと居るから。"
L30_1.m_Talk_JPN = L31_1
L31_1 = "For when you crave your last goodbye, I will be ready by your side."
L30_1.m_Talk_ENG = L31_1
L31_1 = "在你渴望最後的道別時，我會在你身邊做好準備。"
L30_1.m_Talk_TWN = L31_1
L31_1 = "เพราะเมื่อคุณต้องการคำอำลาครั้งสุดท้าย ฉันก็พร้อมจะอยู่เคียงข้างคุณ"
L30_1.m_Talk_THA = L31_1
L31_1 = "Vì khi ngài khao khát lời tạm biệt cuối cùng, tôi sẽ sẵn sàng ở bên cạnh ngài."
L30_1.m_Talk_VTN = L31_1
L31_1 = "在你渴望最后的道别时，我会在你身边做好准备。"
L30_1.m_Talk_SCN = L31_1
L31_1 = "Denn wenn Sie sich nach Ihrem letzten Abschied sehnen, werde ich an Ihrer Seite sein."
L30_1.m_Talk_DEU = L31_1
L31_1 = "Et quand tu voudras faire tes derniers adieux, je me tiendrai prête à tes côtés."
L30_1.m_Talk_FRA = L31_1
L31_1 = {}
L32_1 = 31
L31_1.m_CutScenProcessKey = L32_1
L31_1.m_CutScenID = 12540001
L31_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_HARMONY_C_BASSOON"
L31_1.m_bWaitClick = false
L31_1.m_fWaitTime = 0
L0_1[1] = L1_1
L0_1[2] = L2_1
L0_1[3] = L3_1
L0_1[4] = L4_1
L0_1[5] = L5_1
L0_1[6] = L6_1
L0_1[7] = L7_1
L0_1[8] = L8_1
L0_1[9] = L9_1
L0_1[10] = L10_1
L0_1[11] = L11_1
L0_1[12] = L12_1
L0_1[13] = L13_1
L0_1[14] = L14_1
L0_1[15] = L15_1
L0_1[16] = L16_1
L0_1[17] = L17_1
L0_1[18] = L18_1
L0_1[19] = L19_1
L0_1[20] = L20_1
L0_1[21] = L21_1
L0_1[22] = L22_1
L0_1[23] = L23_1
L0_1[24] = L24_1
L0_1[25] = L25_1
L0_1[26] = L26_1
L0_1[27] = L27_1
L0_1[28] = L28_1
L0_1[29] = L29_1
L0_1[30] = L30_1
L0_1[31] = L31_1
m_dicNKCCutScenTempletByID = L0_1
