local L0_1, L1_1, L2_1, L3_1, L4_1, L5_1, L6_1
L0_1 = {}
L1_1 = {}
L1_1.m_CutScenProcessKey = 1
L1_1.m_CutScenID = 12870002
L1_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_CORRUPTED_C_MIMIC"
L1_1.m_bWaitClick = false
L1_1.m_fWaitTime = 0
L1_1.m_BGFileName = "LIFETIME"
L1_1.m_StartBGMFileName = "CUTSCENE_HOPE"
L2_1 = {}
L2_1.m_CutScenKey_Talk = "LIFETIME_END_NKM_UNIT_CORRUPTED_C_MIMIC@2#Talk"
L2_1.m_CutScenProcessKey = 2
L2_1.m_CutScenID = 12870002
L2_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_CORRUPTED_C_MIMIC"
L2_1.m_bWaitClick = true
L2_1.m_fWaitTime = 0
L2_1.m_Face = "UNIT_IDLE"
L2_1.m_CharStrID = "MIMIC_CORRUPTED_NULL_NULL"
L2_1.m_Pos = "C"
L2_1.m_Talk_KOREA = "친구를 사귀는 건 멍청해. 나만큼 소중한 걸 곁에 두다니. 방해야."
L2_1.m_fTalkTime = 0.03
L2_1.m_Talk_JPN = "友達を作るなんてバカらしい。自分と同じくらい大切な存在なんて、邪魔なだけだよ。"
L2_1.m_Talk_ENG = "Making friends is dumb. Keeping something as precious as me nearby is a liability."
L2_1.m_Talk_TWN = "交朋友是愚蠢的。把像我這樣珍貴的東西留在身邊，得防著點。"
L2_1.m_Talk_SCN = "交朋友是愚蠢的。把像我这样珍贵的东西留在身边，得防着点。"
L2_1.m_Talk_DEU = "Making friends is dumb. Keeping something as precious as me nearby is a liability."
L2_1.m_Talk_FRA = "Making friends is dumb. Keeping something as precious as me nearby is a liability."
L3_1 = {}
L3_1.m_CutScenKey_Talk = "LIFETIME_END_NKM_UNIT_CORRUPTED_C_MIMIC@3#Talk"
L3_1.m_CutScenProcessKey = 3
L3_1.m_CutScenID = 12870002
L3_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_CORRUPTED_C_MIMIC"
L3_1.m_bWaitClick = true
L3_1.m_fWaitTime = 0
L3_1.m_Face = "UNIT_PRIDE"
L3_1.m_CharStrID = "MIMIC_CORRUPTED_NULL_NULL"
L3_1.m_Pos = "C"
L4_1 = {}
L5_1 = 1
L6_1 = 0.3
L4_1[1] = L5_1
L4_1[2] = L6_1
L3_1.m_Bounce = L4_1
L3_1.m_Talk_KOREA = "그래서 네 방식 맘에 들어. 그 비즈니스란 거, 나한테도 유용하거든. 키히히, 앞으로도 우린 함께야."
L3_1.m_fTalkTime = 0.03
L3_1.m_Talk_JPN = "だからあなたのやり方は好き。ビジネスってやつは私にも役立つから。キヒヒ、これからも一緒だよね？　私たち。"
L3_1.m_Talk_ENG = "That's why I like your approach. That business thing, it's useful for me as well. Keeheehee, we'll be together from here on out."
L3_1.m_Talk_TWN = "我喜歡你的做事方式。那個交易，對我也有用呢。嘻嘻嘻，之後也合作愉快囉。"
L3_1.m_Talk_SCN = "我喜欢你的做事方式。那个“生意”，对我也有用呢。嘎嘎嘎，就这么说定了。"
L3_1.m_Talk_DEU = "That's why I like your approach. That business thing, it's useful for me as well. Keeheehee, we'll be together from here on out."
L3_1.m_Talk_FRA = "That's why I like your approach. That business thing, it's useful for me as well. Keeheehee, we'll be together from here on out."
L4_1 = {}
L4_1.m_CutScenProcessKey = 4
L4_1.m_CutScenID = 12870002
L4_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_CORRUPTED_C_MIMIC"
L4_1.m_bWaitClick = false
L4_1.m_fWaitTime = 0
L4_1.m_bFadeIn = false
L4_1.m_fFadeTime = 3
L4_1.m_bFadeWhite = true
L0_1[1] = L1_1
L0_1[2] = L2_1
L0_1[3] = L3_1
L0_1[4] = L4_1
m_dicNKCCutScenTempletByID = L0_1
