local L0_1, L1_1, L2_1, L3_1, L4_1, L5_1, L6_1
L0_1 = {}
L1_1 = {}
L1_1.m_CutScenProcessKey = 1
L1_1.m_CutScenID = 4600206
L1_1.m_CutScenStrID = "NEVERLAND_ACT2_STAGE1_MID4"
L1_1.m_bWaitClick = false
L1_1.m_fWaitTime = 0
L1_1.m_StartBGMFileName = "BATTLE_SUMMER_01"
L2_1 = {}
L2_1.m_CutScenKey_Talk = "NEVERLAND_ACT2_STAGE1_MID4@2#Talk"
L2_1.m_CutScenProcessKey = 2
L2_1.m_CutScenID = 4600206
L2_1.m_CutScenStrID = "NEVERLAND_ACT2_STAGE1_MID4"
L2_1.m_bWaitClick = true
L2_1.m_fWaitTime = 0
L2_1.m_BGFileName = "CLOSE"
L2_1.m_CharStrID = "NEWCOMER_NPC_DREAM_NULL"
L2_1.m_Talk_KOREA = "갑자기 저 로봇들은 뭐야?!"
L2_1.m_fTalkTime = 0.03
L2_1.m_Talk_JPN = "いきなりあのロボットたちは何！？"
L2_1.m_Talk_ENG = "What are those robots?!"
L2_1.m_Talk_TWN = "怎麼突然冒出那些多機器人？！"
L2_1.m_Talk_THA = "หุ่นยนต์พวกนั้นมันอะไรน่ะ?!"
L2_1.m_Talk_VTN = "Mấy con robot đó là gì?!"
L2_1.m_Talk_SCN = "那些机器人怎么突然开始捣乱了？！"
L2_1.m_Talk_DEU = "Was sind das für Roboter?!"
L2_1.m_Talk_FRA = "D'où ils sortent ces robots ?"
L3_1 = {}
L3_1.m_CutScenKey_Talk = "NEVERLAND_ACT2_STAGE1_MID4@3#Talk"
L3_1.m_CutScenProcessKey = 3
L3_1.m_CutScenID = 4600206
L3_1.m_CutScenStrID = "NEVERLAND_ACT2_STAGE1_MID4"
L3_1.m_bWaitClick = true
L3_1.m_fWaitTime = 0
L3_1.m_CharStrID = "PUPPET_NPC_SUPPLEMENT_NULL"
L3_1.m_Talk_KOREA = "인공지능은 탑재되지 않은 것 같아."
L3_1.m_fTalkTime = 0.03
L3_1.m_Talk_JPN = "人工知能は搭載されてないみたい。"
L3_1.m_Talk_ENG = "I don't think they have any AI implementation."
L3_1.m_Talk_TWN = "好像沒有搭載人工智慧。"
L3_1.m_Talk_THA = "ฉันว่าพวกนั้นไม่ได้ใช้ AI นะ"
L3_1.m_Talk_VTN = "Tôi không nghĩ chúng có AI."
L3_1.m_Talk_SCN = "他们似乎，没有搭载人工智能。"
L3_1.m_Talk_DEU = "Ich glaube nicht, dass sie eine KI-Implementierung haben."
L3_1.m_Talk_FRA = "Je n'ai pas l'impression qu'ils disposent d'une intelligence artificielle."
L4_1 = {}
L4_1.m_CutScenKey_Talk = "NEVERLAND_ACT2_STAGE1_MID4@4#Talk"
L4_1.m_CutScenProcessKey = 4
L4_1.m_CutScenID = 4600206
L4_1.m_CutScenStrID = "NEVERLAND_ACT2_STAGE1_MID4"
L4_1.m_bWaitClick = true
L4_1.m_fWaitTime = 0
L4_1.m_CharStrID = "RUNNER_OZ_NULL_NULL"
L4_1.m_Talk_KOREA = "수영장에 로봇이라니… 뭔가 이상하게 돌아가는데."
L4_1.m_fTalkTime = 0.03
L4_1.m_Talk_JPN = "プールにロボットって……なんかおかしいことになってる。"
L4_1.m_Talk_ENG = "Robots in a pool...? Something doesn't feel right."
L4_1.m_Talk_TWN = "泳游池裡竟然有機器人…感覺不太對勁。"
L4_1.m_Talk_THA = "หุ่นยนต์ในสระน้ำเหรอ...? ท่าทางไม่ชอบมาพากลแฮะ"
L4_1.m_Talk_VTN = "Robot trong hồ bơi...? Trông chẳng đúng tí nào."
L4_1.m_Talk_SCN = "游泳池里居然有机器人？……总感觉有点奇怪。"
L4_1.m_Talk_DEU = "Roboter im Pool ...? Etwas scheint nicht zu stimmen."
L4_1.m_Talk_FRA = "Des robots dans une piscine... ? Ça ne me dit rien qui vaille."
L5_1 = {}
L5_1.m_CutScenProcessKey = 5
L5_1.m_CutScenID = 4600206
L5_1.m_CutScenStrID = "NEVERLAND_ACT2_STAGE1_MID4"
L5_1.m_bWaitClick = false
L5_1.m_fWaitTime = 1
L5_1.m_StartFXSoundName = "FX_CUTSCEN_BALL"
L6_1 = {}
L6_1.m_CutScenProcessKey = 6
L6_1.m_CutScenID = 4600206
L6_1.m_CutScenStrID = "NEVERLAND_ACT2_STAGE1_MID4"
L6_1.m_bWaitClick = false
L6_1.m_fWaitTime = 2
L6_1.m_StartFXSoundName = "FX_CUTSCEN_WHISTLE"
L0_1[1] = L1_1
L0_1[2] = L2_1
L0_1[3] = L3_1
L0_1[4] = L4_1
L0_1[5] = L5_1
L0_1[6] = L6_1
m_dicNKCCutScenTempletByID = L0_1
