---
--- Generated by zxr
--- Created by zxr.
--- DateTime: 2021/3/9 11:30 上午
---

---@class PVPArenaAgainstDialog
---@field Root                          	UnityEngine.RectTransform
---@field PVPTimeLineNode               	UnityEngine.RectTransform
---@field ButtonTicketText              	TMPro.TextMeshProUGUI
---@field ButtonTicket                  	UnityEngine.RectTransform
---@field ButtonHere                    	UnityEngine.RectTransform
---@field ButtonReward                  	UnityEngine.RectTransform
---@field ButtonHistory                 	UnityEngine.RectTransform
local PVPArenaAgainstDialog = Class("PVPArenaAgainstDialog")

------------ import ------------
local util         = require 'XLua.util'
local cs_coroutine = require 'XLua.cs_coroutine'
local CoWait       = CS.Engine.Lib.CoWait
local Blocker      = CS.Engine.UI.UIRaycastBlocker.Instance
local UIEventProxy = CS.Engine.UI.UIEventProxy
local KTool        = CS.Engine.Lib.KTool
---@type PVPArenaUtils
local PVPArenaUtils     = import('Game.Utils.PVPArenaUtils')
---@type PVPArenaComponent
local pvpArenaComponent = GameUtils.GetOrAddEntityCompByType(ECSComponentType.Constants.PVPArenaComponent)
------------ import ------------

------------ define ------------
local GroupItemPath = "Prefabs/PVP/PVPAgainstBlueItem.prefab"
local FinalItemPath = "Prefabs/PVP/PVPAgainstRedItem.prefab"
local PVPArenaTimeLineNodePath  = "Game.UI.PVPArena.PVPArenaTimeLineNode"

local MatchChartType = Constants.PVPArenaMatchChartType

local MatchChartPath = {
    [MatchChartType.Group] = GroupItemPath,
    [MatchChartType.Final] = FinalItemPath,
}

local MatchChartEnvPath = {
    [MatchChartType.Group] = "Game.UI.PVPArena.PVPArenaGroupMatchChart",
    [MatchChartType.Final] = "Game.UI.PVPArena.PVPArenaFinalMatchChart",
}

local ExcludeDialogs = {
    {id = Constants.UITypeIds.PVPArenaAgainstDialog}
}

------------ define ------------

function PVPArenaAgainstDialog:__init()
    self.selectMatchChartType = nil
    self.matchChartGos = {}
    -- self.matchChartLoaders = {}
end

function PVPArenaAgainstDialog:__delete()
    self.selectMatchChartType = nil
    self.matchChartGos = nil
    -- self.matchChartLoaders = nil
end

function PVPArenaAgainstDialog:Awake()
    UIEventProxy.Create(self.ButtonHere.gameObject).onPointerClick    = Bind(self, self.OnClickButtonHereAction)
    UIEventProxy.Create(self.ButtonTicket.gameObject).onPointerClick  = Bind(self, self.OnClickButtonTicketAction)
    UIEventProxy.Create(self.ButtonReward.gameObject).onPointerClick  = Bind(self, self.OnClickButtonRewardAction)
    UIEventProxy.Create(self.ButtonHistory.gameObject).onPointerClick = Bind(self, self.OnClickButtonHistoryAction)

    self.navigatorEnv = CfUtils.GetLuaScr(CS.UINavigationBarRoot.Instance.gameObject, "Game.Main.UINavigatorBar")
    self.navigatorEnv:SetCustomBackHandlerAction(Bind(self, self.OnCustomBackHandlerAction))

    local pvpArenaEntryDojo = pvpArenaComponent:GetPVPArenaEntryDojo()
    local t = {}
    local isAudience        = checkNumber(pvpArenaEntryDojo.identity) == Constants.PVPArenaIdentity.Audience
    local quizRewardGoodsId = pvpArenaComponent:GetParamsRowNum(Constants.PVPArenaParamsIds.QuizRewardGoodsId)
    table.insert(t, quizRewardGoodsId)
    local quizGoodsId
    if isAudience then
        quizGoodsId       = pvpArenaComponent:GetParamsRowNum(Constants.PVPArenaParamsIds.QuizGoodsId)
        table.insert(t, quizGoodsId)
    end
    --local pvpArenaDojo = pvpArenaComponent:GetPVPArenaDojo()
    --self.navigatorEnv:SetUpdateGoodsNumCallback(function(goodsId)
    --    local num = 0
    --    if isAudience and goodsId == quizGoodsId then
    --        num = pvpArenaDojo.quizTicketNum
    --    elseif goodsId == quizRewardGoodsId then
    --        num = GoodsUtils.GetThingNo(goodsId)
    --    end
    --    return num
    --end)
    self.navigatorEnv:UpdateHealthNodes({quizGoodsId, quizRewardGoodsId})
end

function PVPArenaAgainstDialog:OnInitialize()
    ---@type Engine.Lib.CoWait
    local coWait = CoWait.Start():Coroutine(util.cs_generator(function()

        ---@type PVPArenaEntryDojo
        local pvpArenaEntryDojo = pvpArenaComponent:GetPVPArenaEntryDojo()
        local isAudience   = checkNumber(pvpArenaEntryDojo.identity) == Constants.PVPArenaIdentity.Audience
        self.isAudience = isAudience
        self:RefreshButtonGroup(isAudience)

        self:RefreshTineLineNode()

        local argument   = self.controller.Argument
        local parameters = argument.parameters
        if parameters.groupIndex then
            self.groupIndex = parameters.groupIndex
            parameters.groupIndex = nil
        end

        local matchChartType = self:GetSelectMatchChartType()
        self:RefreshMatchChartByType(matchChartType)

        self.__EventRequestHomeSuccess          = Events.AddListener(Constants.EventNames.PVPArenaRequestHomeSuccess, Bind(self, self.OnEventRequestHomeSuccess))
    end))
    return coWait
end

function PVPArenaAgainstDialog:OnFinalize()
    local coWait = CoWait.Start():Coroutine(util.cs_generator(function()
        if self.__EventRequestHomeSuccess then
            Events.RemoveListener(Constants.EventNames.PVPArenaRequestHomeSuccess, self.__EventRequestHomeSuccess)
            self.__EventRequestHomeSuccess = nil
        end
        if not self.isBack then
            local argument   = self.controller.Argument
            local parameters = argument.parameters
            parameters.matchChartType = self.selectMatchChartType
            local gameObject = self.matchChartGos[MatchChartType.Group]
            if gameObject then
                ---@type PVPArenaGroupMatchChart
                local env = CfUtils.GetLuaScr(gameObject, MatchChartEnvPath[MatchChartType.Group])
                if not isNull(env) then
                    parameters.groupIndex = env:GetGroupIndex()
                end
            end
        end
        self.navigatorEnv:SetCustomBackHandlerAction()
        self.navigatorEnv = nil
        self:ReleaseBundle()
        self.controller = nil --删除lua层引用到的c#对象 否则不会产生c# gc回收到对象
        self:Delete()
        self = nil --lua层的gc需要
    end))
    return coWait
end

---------------------------------------------------
--- release begin --
---------------------------------------------------
function PVPArenaAgainstDialog:ReleaseBundle()
    -- for i, matchChartLoader in ipairs(self.matchChartLoaders) do
    --     if not isNull(matchChartLoader) then
    --         matchChartLoader:Release(true)
    --     end
    -- end
    -- self.matchChartLoaders = nil
end
---------------------------------------------------
--- release end --
---------------------------------------------------


---------------------------------------------------
--- ui logic begin --
---------------------------------------------------


function PVPArenaAgainstDialog:RefreshTineLineNode()
    ---@type PVPArenaTimeLineNode
    local mbEnv = CfUtils.GetLuaScr(self.PVPTimeLineNode.gameObject, PVPArenaTimeLineNodePath)
    if mbEnv == nil then return end

    mbEnv:RefreshUI()
end

function PVPArenaAgainstDialog:RefreshButtonGroup(isAudience)
    KTool.SetActive(self.ButtonTicket.gameObject, isAudience)
    if isAudience then
        local pvpArenaDojo = pvpArenaComponent:GetPVPArenaDojo()
        local quizzed       = checkTable(pvpArenaDojo.quizzed)
        --- 投过几次票
        local quizNum       = table.count(quizzed)
        --- 竞猜票数量
        local quizTicketNum = checkNumber(pvpArenaDojo.quizTicketNum)
        --- 能投多少次
        local quizMaxNum    = quizNum + quizTicketNum
        self.ButtonTicketText.text = string.format("%s/%s", quizNum, quizMaxNum)
    end
end

---RefreshMatchChartByType
---根据类型刷新对阵图
---@param matchChartType number
function PVPArenaAgainstDialog:RefreshMatchChartByType(matchChartType)
    local seasonFlag = pvpArenaComponent:GetSeasonFlag()
    KTool.SetActive(self.ButtonHere.gameObject, not self.isAudience and matchChartType == MatchChartType.Group and seasonFlag ~= Constants.PVPArenaSeasonFullStatus.Closed)

    local oldMatchChartType = self.selectMatchChartType
    if oldMatchChartType and oldMatchChartType ~= matchChartType then
        local gameObject = self.matchChartGos[oldMatchChartType]
        if gameObject then
            KTool.SetActive(gameObject, false)
            self:RemoveMatchChartAgainstStateCo(gameObject, matchChartType)
        end
    end
    self.selectMatchChartType = matchChartType
    self:LoadMatchChartByType(matchChartType)
end

---LoadMatchChartByType
---根据类型加载对阵图
---@param matchChartType number
function PVPArenaAgainstDialog:LoadMatchChartByType(matchChartType)
    local gameObject = self.matchChartGos[matchChartType]
    if gameObject then
        KTool.SetActive(gameObject, true)
        self:RefreshMatchChartEnvByType(gameObject, matchChartType)
        return
    end
    local path = MatchChartPath[matchChartType]
    Blocker:AddCondition(path)
    cs_coroutine.start(function()
        local go = GameUtils.LoadBundleAsync(path, self.Root.gameObject, nil, true)
        self.matchChartGos[matchChartType] = go
        -- self.matchChartLoaders[matchChartType] = loader
        self:RefreshMatchChartEnvByType(go, matchChartType)
        Blocker:RemoveCondition(path)
    end)
end

---RefreshMatchChartEnvByType
---根据对战图类型刷新对应的lua环境
---@param gameObject UnityEngine.GameObject
---@param matchChartType number
function PVPArenaAgainstDialog:RefreshMatchChartEnvByType(gameObject, matchChartType)
    local env = CfUtils.GetLuaScr(gameObject, MatchChartEnvPath[matchChartType])
    if isNull(env) then return end
    xTry(function()

        local argument   = self.controller.Argument
        local parameters = argument.parameters
        local isFirst    = parameters.isFirst
        local isGroup = matchChartType == MatchChartType.Group
        if not self.isAudience and isFirst and isGroup then
            env:JumpPlayerGroup()
            parameters.isFirst = false
        else
            if isGroup and self.groupIndex then
                env:SetGroupIndex(self.groupIndex)
            end
            env:RefreshUI()
        end

    end, function()
        printError("%s", debug.traceback())
    end)
end

function PVPArenaAgainstDialog:RemoveMatchChartAgainstStateCo(gameObject, matchChartType)
    local env = CfUtils.GetLuaScr(gameObject, MatchChartEnvPath[matchChartType])
    if isNull(env) then return end
    env:RemoveAgainstStateCo()
end

---------------------------------------------------
--- ui logic end --
---------------------------------------------------

---------------------------------------------------
--- get/set begin --
---------------------------------------------------

function PVPArenaAgainstDialog:GetSelectMatchChartType()
    local oldSeasonFlag = pvpArenaComponent:GetOldSeasonFlag()
    local seasonFlag    = pvpArenaComponent:GetSeasonFlag()
    local selectMatchChartType
    --- 如果是再对阵图界面刷新 的 话 要么是切换导致的刷新 要么是 刷新当前对阵图
    --- 如果切换对阵图
    if oldSeasonFlag == Constants.PVPArenaSeasonFullStatus.OffSeason and seasonFlag == Constants.PVPArenaSeasonFullStatus.Final then
        selectMatchChartType = MatchChartType.Final
    elseif self.selectMatchChartType then
        selectMatchChartType = self.selectMatchChartType
    --- 否则 使用参数
    else
        local argument      = self.controller.Argument
        local parameters    = argument.parameters
        selectMatchChartType = parameters.matchChartType
    end

    return selectMatchChartType
end
---------------------------------------------------
--- get/set end --
---------------------------------------------------

---------------------------------------------------
--- handler begin --
---------------------------------------------------

function PVPArenaAgainstDialog:OnEventRequestHomeSuccess()
    self:RefreshTineLineNode()
    local matchChartType = self:GetSelectMatchChartType()
    self:RefreshMatchChartByType(matchChartType)
end

function PVPArenaAgainstDialog:OnCustomBackHandlerAction()
    self.isBack = true

    local UIModule      = CS.Engine.UI.UIModule
    UIModule.BackDialog()
end

function PVPArenaAgainstDialog:OnClickButtonHereAction()
    --- 如果玩家进入最终赛 则提示 "您已经进入最终赛了"
    local mainPanelStatus = pvpArenaComponent:GetMainPanelStatus()
    local seasonFlag      = pvpArenaComponent:GetSeasonFlag()
    if mainPanelStatus ~= Constants.PVPArenaMainPanelStatus.WatchTheMatch and seasonFlag == Constants.PVPArenaSeasonFullStatus.Final then
        GameUtils.Toast(localize("您已经进入最终赛了"))
        return
    end

    local gameObject = self.matchChartGos[MatchChartType.Group]
    if gameObject then
        ---@type PVPArenaGroupMatchChart
        local env = CfUtils.GetLuaScr(gameObject, MatchChartEnvPath[MatchChartType.Group])
        env:JumpPlayerGroup()
    end
end

function PVPArenaAgainstDialog:OnClickButtonTicketAction()
    PVPArenaUtils.ShowQuizListDialog(ExcludeDialogs)
end

function PVPArenaAgainstDialog:OnClickButtonRewardAction()
    PVPArenaUtils.ShowRankRewardDialog(ExcludeDialogs)
end

function PVPArenaAgainstDialog:OnClickButtonHistoryAction()
    PVPArenaUtils.ShowHonorListDialog(ExcludeDialogs)
end

---------------------------------------------------
--- handler end --
---------------------------------------------------

return PVPArenaAgainstDialog