---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by win 10.
--- DateTime: 2019/5/24 16:58
---

local UIFightSoulSortView = BaseClass("UIFightSoulSortView",UIBaseView);
local base = UIBaseView
local this = UIFightSoulSortView


local function SetActive(btn,bool)
    local transform = btn.transform
    transform:GetChild(0).gameObject:SetActive(bool)
end

local function IsActive(btn)
    local transform = btn.transform
    return transform:GetChild(0).gameObject.activeInHierarchy
end



local function OnClickConfirmBtn(self)
    self.callBack(self.cloneScreenTypes,self.recordOrder.kind)
    UIManager:GetInstance():CloseWindow(UIWindowNames.UIFightSoulSort)
end

local function OnClickCancelBtn(self)

end

function this.OnClickSortBtn(self,id)
    self.recordOrder.kind = id
    for k,v in pairs(self.sort_BtnTab) do
        SetActive(v,k == id)
    end
end

local function OnClickToggle(self,key,id)
    if IsActive(self.toggle_Tab[key][id])  then
        if key == 1 then
            self.cloneScreenTypes.abiliType = 0
        elseif key == 2 then
            self.cloneScreenTypes.star = 0
        elseif key == 3 then
            self.cloneScreenTypes.rare = 0
        elseif key == 4 then
            self.cloneScreenTypes.isEquip = 0
        end
        SetActive(self.toggle_Tab[key][id],false)
        return
    end

    for k,v in pairs(self.toggle_Tab[key]) do
        if key == 1 then
            self.cloneScreenTypes.abiliType = id
        elseif key == 2 then
            self.cloneScreenTypes.star = id
        elseif key == 3 then
            self.cloneScreenTypes.rare = id
        elseif key == 4 then
            self.cloneScreenTypes.isEquip = id
        end

        SetActive(v,id == k)
    end
end

local function InitButtons(self)
    self:OnClickSortBtn(self.recordOrder.kind)  
    for k,v in table.pairsByKeys(self.toggle_Tab[1]) do
        SetActive(v,k == self.screenTypes.abiliType )
    end

    for k,v in table.pairsByKeys(self.toggle_Tab[2]) do
        SetActive(v,k == self.screenTypes.star )
    end

    for k,v in table.pairsByKeys(self.toggle_Tab[3]) do
        SetActive(v,k == self.screenTypes.rare )
    end
    
    for k,v in table.pairsByKeys(self.toggle_Tab[4]) do
        SetActive(v,k == self.screenTypes.isEquip )
    end
end

  
    
function this.OnLangCreate(self)
    local mainRoot=self.langRc:GetObject("MainRoot").transform
    LangUtil.BindText(self.langRc:GetObject("Title").transform).text = LangUtil.GetSysLang(187)
    
    LangUtil.GetSpriteLang(425, function(sprite) self.langRc:GetObject("Title1"):GetComponent("Image").sprite = sprite end) -- 排列
    LangUtil.GetSpriteLang(424, function(sprite) self.langRc:GetObject("Title2"):GetComponent("Image").sprite = sprite end) -- 属性


    LangUtil.GetSpriteLang(426, function(Sprite) self.langRc:GetObject("Confirm").transform:Find("Text"):GetComponent("Image").sprite = Sprite  end) -- 确认
    LangUtil.GetSpriteLang(507, function(Sprite) self.langRc:GetObject("Cancel").transform:Find("Text"):GetComponent("Image").sprite = Sprite  end) -- 取消

    local btnRoot1 = mainRoot:Find("SortRoot")
    LangUtil.BindText(btnRoot1:GetChild(0):Find("Text")).text = LangUtil.GetSysLang(166)
    LangUtil.BindText(btnRoot1:GetChild(1):Find("Text")).text = LangUtil.GetSysLang(167)
    LangUtil.BindText(btnRoot1:GetChild(2):Find("Text")).text = LangUtil.GetSysLang(169)
    
    local btnRoot2 = mainRoot:Find("ScreenRoot")
    -- 职业
    
    LangUtil.BindText(btnRoot2:GetChild(0):GetChild(0):Find("Text")).text = LangUtil.GetSysLang(SysLangKeys.ClassName[1])
    LangUtil.BindText(btnRoot2:GetChild(0):GetChild(1):Find("Text")).text = LangUtil.GetSysLang(SysLangKeys.ClassName[2])
    LangUtil.BindText(btnRoot2:GetChild(0):GetChild(2):Find("Text")).text = LangUtil.GetSysLang(SysLangKeys.ClassName[3])
    LangUtil.BindText(btnRoot2:GetChild(0):GetChild(3):Find("Text")).text = LangUtil.GetSysLang(SysLangKeys.ClassName[4])
    LangUtil.BindText(btnRoot2:GetChild(0):GetChild(4):Find("Text")).text = LangUtil.GetSysLang(SysLangKeys.ClassName[5])
    LangUtil.BindText(btnRoot2:GetChild(0):GetChild(5):Find("Text")).text = LangUtil.GetSysLang(SysLangKeys.ClassName[6])
    LangUtil.BindText(btnRoot2:GetChild(0):GetChild(6):Find("Text")).text = LangUtil.GetSysLang(SysLangKeys.ClassName[0])
    
    -- 星级
    LangUtil.BindText(btnRoot2:GetChild(1):GetChild(0):Find("Text")).text = string.gsub(LangUtil.GetSysLang(584),"X","1")  
    LangUtil.BindText(btnRoot2:GetChild(1):GetChild(1):Find("Text")).text = string.gsub(LangUtil.GetSysLang(584),"X","2")
    LangUtil.BindText(btnRoot2:GetChild(1):GetChild(2):Find("Text")).text = string.gsub(LangUtil.GetSysLang(584),"X","3")
    LangUtil.BindText(btnRoot2:GetChild(1):GetChild(3):Find("Text")).text = string.gsub(LangUtil.GetSysLang(584),"X","4")
    LangUtil.BindText(btnRoot2:GetChild(1):GetChild(4):Find("Text")).text = string.gsub(LangUtil.GetSysLang(584),"X","5")
    
    -- 稀有度
    LangUtil.BindText(btnRoot2:GetChild(2):GetChild(0):Find("Text")).text= RarityName[Rarity.R]
    LangUtil.BindText(btnRoot2:GetChild(2):GetChild(1):Find("Text")).text= RarityName[Rarity.SR]
    LangUtil.BindText(btnRoot2:GetChild(2):GetChild(2):Find("Text")).text= RarityName[Rarity.SSR]
    
    -- 是否已装备
    LangUtil.BindText(btnRoot2:GetChild(3):GetChild(0):Find("Text")).text=LangUtil.GetSysLang(590)
    LangUtil.BindText(btnRoot2:GetChild(3):GetChild(1):Find("Text")).text=LangUtil.GetSysLang(591)
    

end


function this.OnCreate(self)
    base.OnCreate(self);
    local close = self.rc:GetObject("CloseButton")
    self.confirmBtn = self.rc:GetObject("Confirm")
    self.cancelBtn = self.rc:GetObject("Cancel")
    

    self.sort_BtnCtrl = self.rc:GetObject("SortRoot").transform;
    self.sort_ToggleCtrl = self.rc:GetObject("ScreenRoot").transform;
    self.sort_BtnTab = {}
    
    self.toggle_Tab = {};
    self.recordScreen = {}
    for i = 0,self.sort_ToggleCtrl.childCount - 1 do
        local toggleParent = self.sort_ToggleCtrl:GetChild(i)
        self.toggle_Tab[i+1] = {}
        for j = 0,toggleParent.childCount -1 do
            local toggle = toggleParent:GetChild(j).gameObject
            self.toggle_Tab[i+1][j+1] = toggle;
            UIUtil.AddBtnEvent(toggle,function(go)
                OnClickToggle(self,i+1,j+1)
            end)
        end
    end

    for i = 0,self.sort_BtnCtrl.childCount - 1 do
        local btn = self.sort_BtnCtrl:GetChild(i).gameObject;
        self.sort_BtnTab[i + 1] = btn
        UIUtil.AddBtnEvent(btn,function(v) self:OnClickSortBtn(i+1) end)
    end

    EventTriggerListener.Get(self.rc:GetObject("EventBg")).onLuaClick = function() UIManager:GetInstance():CloseWindow(UIWindowNames.UIFightSoulSort) end
    
    UIUtil.AddBtnEvent(self.confirmBtn,function(v) OnClickConfirmBtn(self) UIManager:GetInstance():CloseWindow(UIWindowNames.UIFightSoulSort) end)
    UIUtil.AddBtnEvent(self.cancelBtn,function()UIManager:GetInstance():CloseWindow(UIWindowNames.UIFightSoulSort) end)
    UIUtil.AddBtnEvent(close,function()UIManager:GetInstance():CloseWindow(UIWindowNames.UIFightSoulSort) end)

end

function this.OnEnable(self)
    base.OnEnable(self);
    self:OnRefresh();
end

function this.OnRefresh(self)
    self.player = Game.Scene.Player
    self.recordOrder = self.model.data.recordOrder
    self.screenTypes = self.model.data.screenTypes
    self.cloneScreenTypes = table.clone(self.screenTypes)
    self.callBack = self.model.data.callBack
    InitButtons(self)
end

function this.OnAddListener(self)
    base.OnAddListener(self)
end

function this.OnRemoveListener(self)
    base.OnRemoveListener(self);
end

function this.OnDisable(self)
    base.OnDisable(self)
end

function this.OnDestroy(self)
    base.OnDestroy(self);
end

return this;

