local config = {
  ui_story_32280401_1_dialog_content = "Finalmente, o Último Celestita chega. Obrigado por me fazer esperar, agora experimente isso!",
  ui_story_32280401_2_dialog_content = "O que foi?",
  ui_story_32280401_3_dialog_content = "É uma verdadeira... Deixa pra lá. Só experimente!",
  ui_story_32280401_4_option_content = "Experimente um pouco",
  ui_story_32280401_5_dialog_content = "Tem gosto de balinha de limão, mas algo está um pouco diferente. Espere, poderia ser...",
  ui_story_32280401_6_dialog_content = "Heheh, parece que o Último Celestita tem um gosto bastante refinado. Isso não é uma simples bala de limão!",
  ui_story_32280401_7_dialog_content = "Acontece que é a obra-prima de Queen Kandi, a maior confeiteira da história de Umbraton - o <color=#FFB400>Lemon Supreme</color>!",
  ui_story_32280401_8_dialog_content = "Há algo especialmente refrescante nisso! Acho que nunca comi um doce tão bom na minha vida...",
  ui_story_32280401_9_dialog_content = "Infelizmente, não está mais disponível no mercado.",
  ui_story_32280401_10_dialog_content = "Isso é porque Queen Kandi faleceu trinta anos atrás, e ela nunca compartilhou a receita do Lemon Supreme com uma única alma.",
  ui_story_32280401_11_dialog_content = "Então isso significa...",
  ui_story_32280401_12_dialog_content = "Sim! É um consumível de uso único deixado por um poderoso guerreiro de três décadas atrás!",
  ui_story_32280401_13_dialog_content = "Não deveria ter estragado até agora?",
  ui_story_32280401_14_dialog_content = "Tem gosto de que estragou?",
  ui_story_32280401_15_dialog_content = "Não, mas... Deixa pra lá. Por que exatamente você precisa da minha ajuda de novo?",
  ui_story_32280401_16_dialog_content = "Outra ótima pergunta do Último Celestita! Justo antes de ela deixar este mundo, Queen Kandi uma vez disse—",
  ui_story_32280401_17_dialog_content = "\"Você quer a minha receita? Pode ficar com ela! Está bem <color=#FFB400>ali</color>! Deixei minha receita naquele <color=#FFB400>lugar</color>!\"",
  ui_story_32280401_18_dialog_content = "Por que parece que ela estava prestes a ser executada?",
  ui_story_32280401_19_dialog_content = "E recentemente, confirmei a localização daquele <color=#FFB400>lugar</color>! Quer vir procurá-lo comigo?",
  ui_story_32280401_20_option_content = "Vamos!",
  ui_story_32280401_21_dialog_content = "Não posso dizer que não estou interessado em aprender a receita secreta para este doce incrível.",
  ui_story_32280401_22_dialog_content = "Essa é exatamente o tipo de resposta que eu esperava de você!",
  ui_story_32280401_23_option_content = "Bom...",
  ui_story_32280401_24_dialog_content = "Realmente temos que ir em uma aventura apenas por alguns doces?",
  ui_story_32280401_25_dialog_content = "Você sabe que acabou de comer meu último Lemon Supreme, certo? Eu não vou deixar você sair assim depois disso!",
  ui_story_32280401_26_dialog_content = "Se você se recusar a vir junto, eu enviarei o Conan, o Iluminado, meu robô bomba mais poderoso, direto para o seu quarto!",
  ui_story_32280401_27_dialog_content = "Multar...",
  ui_story_32280401_28_dialog_content = "Não há tempo a perder! Vamos embora!",
  ui_story_32280401_29_dialog_content = "<color=#e8d9bb>Algum tempo depois</color>",
  ui_story_32280401_30_dialog_content = "Então é aqui que a receita secreta está escondida?",
  ui_story_32280401_31_dialog_content = "É apenas uma floresta de aparência normal. Isso é muito diferente do que eu imaginava.",
  ui_story_32280401_32_dialog_content = "Um verdadeiro guerreiro não julga o inimigo apenas pela aparência.",
  ui_story_32280401_33_dialog_content = "Muitas pessoas vieram procurar a receita de Queen Kandi, apenas para sair de mãos vazias...",
  ui_story_32280401_34_dialog_content = "Alguns deles até se transformaram em monstros durante a busca!",
  ui_story_32280401_35_dialog_content = "Isso soa um pouco ridículo, você não acha?",
  ui_story_32280401_36_dialog_content = "Bem, é isso que os rumores dizem! De qualquer forma, devemos continuar—",
  ui_story_32280401_37_dialog_content = "Ei, você também ouve um zumbido?",
  ui_story_32280401_38_dialog_content = "Urgh, eles de novo! Esses monstros gananciosos e sugadores de sangue são a ruína de toda existência!",
  ui_story_32280401_39_dialog_content = "Não se preocupe! Como um guerreiro experiente, eu apliquei uma poção poderosa para repeli-los antes de partirmos!",
  ui_story_32280401_40_dialog_content = "Mas por algum motivo, não parece estar funcionando... Na verdade, parece que ainda mais mosquitos estão chegando!",
  ui_story_32280401_41_dialog_content = "... Espere um minuto, esses não são mosquitos... São abelhas! Corra!",
  ui_story_32280401_42_dialog_content = "Caramba! Por que há tantas abelhas? E por que elas não param de nos perseguir?",
  ui_story_32280401_43_dialog_content = "Você está carregando algo que os atrai para nós?",
  ui_story_32280401_44_dialog_content = "De jeito nenhum! Só estou carregando minhas coisas de sempre!",
  ui_story_32280401_45_dialog_content = "Ah, ok... Espere, não! Não está bem!",
  ui_story_32280401_46_dialog_content = "Esse é o problema bem aí! Você sempre carrega um monte de doces nos seus bolsos, e aposto que é por isso que essas abelhas não nos deixam em paz! Se apresse e se livre disso!",
  ui_story_32280401_47_dialog_content = "Você quer que eu abandone meus doces companheiros? Nem em seus sonhos! Um verdadeiro guerreiro nunca faria algo tão hediondo!",
  ui_story_32280401_48_dialog_content = "Então apenas coma! Tudo!",
  ui_story_32280401_49_dialog_content = "Eu sei disso, então pare de me apressar...",
  ui_story_32280401_50_dialog_content = "<color=#e8d9bb>Splat!</color>",
  ui_story_32280401_51_dialog_content = "O-O que diabos acabou de me acertar no rosto?",
  ui_story_32280401_52_dialog_content = "Ahhhh! Desculpe por isso, eu apertei meu copo de geléia com muita força e ele jorrou—",
  ui_story_32280401_53_dialog_content = "<anim type=Shake><size=45><color=#e8d9bb>Zumbiiiiiiido!</color></size></anim>",
  ui_story_32280401_54_dialog_content = "<color=#e8d9bb>Com a visão completamente obscurecida por uma densa nuvem de abelhas, o som de zumbidos irritados enche seus ouvidos...</color>",
  ui_story_32280401_55_dialog_content = "<color=#e8d9bb>Várias horas depois</color>",
  ui_story_32280401_56_dialog_content = "Bem? Ainda dói?",
  ui_story_32280401_57_dialog_content = "Prefiro não falar sobre isso. Meu rosto parece que está sendo arrancado sempre que eu falo...",
  ui_story_32280401_58_dialog_content = "Bem, seu rosto inteiro está bastante inchado afinal...",
  ui_story_32280401_59_dialog_content = "Ohhh! Agora eu entendi!",
  ui_story_32280401_60_dialog_content = "Aquelas pessoas dos boatos nunca se transformaram em monstros! Elas apenas acabaram como você!",
  ui_story_32280401_61_dialog_content = "Você parece totalmente com um ornitorrinco agora!",
  ui_story_32280401_62_dialog_content = "Isso realmente não me faz sentir melhor, sabe.",
  ui_story_32280401_63_dialog_content = "Este lugar é perigoso... Veja só todos os problemas que encontramos em apenas algumas horas!",
  ui_story_32280401_64_dialog_content = "Fomos perseguidos por abelhas, nossa mochila foi roubada por um macaco e algum animal deu uma mordida na minha trança...",
  ui_story_32280401_65_dialog_content = "Tem sido um desastre atrás do outro...",
  ui_story_32280401_66_dialog_content = "Sim, mas também tem sido divertido, certo? Eu nunca estive em uma aventura com um amigo assim antes...",
  ui_story_32280401_67_dialog_content = "Fale por você mesmo. Você não é quem foi picado por um enxame de abelhas.",
  ui_story_32280401_68_dialog_content = "Mas depois de tudo que passamos, eu não me importo mesmo se a lendária receita secreta não existir...",
  ui_story_32280401_69_dialog_content = "Mesmo que o verdadeiro tesouro acabe sendo a diversão que tivemos ao longo do caminho, ou algum outro clichê sem sentido...",
  ui_story_32280401_70_dialog_content = "Ainda assim, vou continuar feliz!",
  ui_story_32280401_71_dialog_content = "Eu não sabia que você se sentia assim, Zeta...",
  ui_story_32280401_72_dialog_content = "Mas ainda assim... Eu sofri demais para sair de mãos vazias, então vamos continuar procurando!",
  ui_story_32280401_73_dialog_content = "Hahahaha! Não se preocupe, tenho certeza que a Queen Kandi não faria algo tão errado.",
  ui_story_32280401_74_dialog_content = "Sério? Porque esconder a receita dela assim me parece bastante errado.",
  ui_story_32280401_75_dialog_content = "De qualquer forma... Acho que finalmente chegamos.",
  ui_story_32280401_76_dialog_content = "De acordo com o mapa, a receita deve estar escondida naquela caverna à frente!",
  ui_story_32280401_77_dialog_content = "Sério? Acho que devemos ir dar uma olhada.",
  ui_story_32280401_78_dialog_content = "<color=#e8d9bb>Os dois entram sem hesitar por um momento e encontram um velho baú de madeira no centro da caverna.</color>",
  ui_story_32280401_79_dialog_content = "Olha, um baú de tesouro! A receita deve estar lá dentro!",
  ui_story_32280401_80_dialog_content = "Espere um segundo! Vamos garantir que não seja uma armadilha!",
  ui_story_32280401_81_dialog_content = "Sério? Depois de tudo que passamos, mal acho que precisamos ser tão cuidadosos assim!",
  ui_story_32280401_82_dialog_content = "Viu? Eu abri o baú, e nada aconteceu!",
  ui_story_32280401_83_dialog_content = "S-Sem brincadeira, hein... Ei, tem um pedaço de papel no baú! Poderia ser a receita?",
  ui_story_32280401_84_dialog_content = "\"Saudações, meu amigo caçador de tesouros! Parabéns por chegar tão longe!\"",
  ui_story_32280401_85_dialog_content = "\"No entanto, lamento informar que não há receita para ser encontrada aqui.\"",
  ui_story_32280401_86_dialog_content = "\"O segredo para criar o <color=#FFB400>Lemon Supreme</color> está na sua jornada até este lugar.\"",
  ui_story_32280401_87_dialog_content = "... Parece que você adivinhou, Zeta.",
  ui_story_32280401_88_dialog_content = "De qualquer forma, já estou mentalmente preparado para esse tipo de resultado. Vamos apenas voltar para casa... Uh, Zeta?",
  ui_story_32280401_89_dialog_content = "...",
  ui_story_32280401_90_dialog_content = "Você está brincando comigo? Que tipo de pessoa realmente levaria adiante um final tão clichê?",
  ui_story_32280401_91_dialog_content = "Urgh! Vou explodir essa caverna estúpida em escombros!",
  ui_story_32280401_92_dialog_content = "<color=#e8d9bb>Zeta chuta a caixa com raiva e puxa um de seus robôs cheios de doces.</color>",
  ui_story_32280401_93_dialog_content = "Acalme-se, Zeta!",
  ui_story_32280401_94_dialog_content = "Espero que esteja assistindo, sua rainha desonesta! Isso é o que acontece quando você mexe com uma guerreira!",
  ui_story_32280401_95_dialog_content = "Espere aí, Zeta... Dê uma olhada mais de perto! Há um fundo falso no baú!",
  ui_story_32280401_96_dialog_content = "Um fundo falso? Ei, você está certo! Se eu não tivesse chutado o baú agora, nunca teríamos notado isso!",
  ui_story_32280401_97_dialog_content = "... Isso significa que a nota que encontramos antes era apenas uma distração?",
  ui_story_32280401_98_dialog_content = "Entendi! Então é assim que Queen Kandi impede que malfeitores se apoderem de sua receita.",
  ui_story_32280401_99_dialog_content = "Isso tem que ser destino!",
  ui_story_32280401_100_dialog_content = "Há algo sob o fundo falso... É outra nota!",
  ui_story_32280401_101_dialog_content = "Tem que ser a receita real do <color=#FFB400>Lemon Supreme</color>, certo?",
  ui_story_32280401_102_dialog_content = "\"Se você está lendo isso, significa que você destruiu meu peito por pura raiva.\"",
  ui_story_32280401_103_dialog_content = "\"Dizem que a doçura é melhor apreciada quando combinada com um sabor oposto, e poucas coisas tornam as guloseimas mais doces do que o sofrimento de outra pessoa.\"",
  ui_story_32280401_104_dialog_content = "\"Por favor, saiba que sua frustração me traz uma alegria desenfreada.\"",
  ui_story_32280401_105_dialog_content = "... Zeta?",
  ui_story_32280401_106_dialog_content = "Detonar.",
  ui_story_32280401_107_dialog_content = "*tossindo* Caramba, Zeta... Você poderia ter esperado a gente sair primeiro...",
  ui_story_32280401_108_dialog_content = "Ai... Eu teria usado uma bomba mais fraca.",
  ui_story_32280401_109_dialog_content = "Atchim—estamos cobertos de poeira. Melhor nos livrar dela.",
  ui_story_32280401_110_dialog_content = "Eu também tinha grandes esperanças...",
  ui_story_32280401_111_dialog_content = "Eu me pergunto por que Queen Kandi estava tão relutante em deixar a receita do seu <color=#FFB400>Lemon Supreme</color>?",
  ui_story_32280401_112_dialog_content = "É gostoso, afinal de contas... *tosse*",
  ui_story_32280401_113_dialog_content = "Há muita poeira aqui. Vamos embora.",
  ui_story_32280401_114_dialog_content = "Hum? Por que essa poeira tem um gosto engraçado?",
  ui_story_32280401_115_dialog_content = "Hã? Isso parece apenas com sal... Espere, isso é porque É sal!",
  ui_story_32280401_116_dialog_content = "Essa caverna deve ser uma formação natural de sal ou algo assim.",
  ui_story_32280401_117_dialog_content = "Há algo familiar neste sabor salgado também... É quase como—",
  ui_story_32280401_118_dialog_content = "Gosta do sabor de uma certa bala de limão?",
  ui_story_32280401_119_dialog_content = "E-Então é isso! Eu finalmente entendi agora!",
  ui_story_32280401_120_dialog_content = "\"Dizem que a doçura é melhor apreciada quando combinada com um sabor oposto\"!",
  ui_story_32280401_121_dialog_content = "O sal desta caverna é o segredo por trás do sabor doce e refrescante do <color=#FFB400>Lemon Supreme</color>!",
  ui_story_32280401_122_dialog_content = "Então todo esse tempo, Queen Kandi—",
  ui_story_32280401_123_dialog_content = "Sim! Ela nunca escondeu a receita do <color=#FFB400>Lemon Supreme</color> para começar! Isso porque está bem aqui neste lugar!",
  ui_story_32280401_124_dialog_content = "Então qual era o sentido daquelas duas notas?",
  ui_story_32280401_125_dialog_content = "Provavelmente eram a ideia dela de uma piada. Afinal, Queen Kandi também era uma notória brincalhona.",
  ui_story_32280401_126_dialog_content = "Não consigo acreditar que ela conseguiu enganar um guerreiro como eu. Ela deve ter sido uma mulher incrível.",
  ui_story_32280401_127_option_content = "Então é só isso que precisa para mudar sua opinião, hein?",
  ui_story_32280401_128_dialog_content = "Você a chamou de \"rainha torta\" há um minuto atrás...",
  ui_story_32280401_129_dialog_content = "Ah, isso? Isso foi apenas um simples mal-entendido, considerando que a trama nesta aventura clássica ainda estava se desenvolvendo...",
  ui_story_32280401_130_option_content = "Eu realmente tenho que te dar os parabéns, Zeta!",
  ui_story_32280401_131_dialog_content = "Se você não tivesse explodido aquela caverna, nunca teríamos descoberto o mistério por trás da receita do Lemon Supreme.",
  ui_story_32280401_132_dialog_content = "Heheh, eu sou o protagonista predestinado em nossa história, afinal de contas.",
  ui_story_32280401_133_dialog_content = "Isso estava tudo destinado a funcionar para nós!",
  ui_story_32280401_134_dialog_content = "E agora que finalmente temos o ingrediente secreto em mãos, é hora de voltar para casa! Mal posso esperar para fazer o Lemon Supreme com minhas próprias mãos!",
  ui_story_32280401_135_dialog_content = "(Mesmo que meu rosto ainda esteja me matando, ver Zeta tão feliz...)",
  ui_story_32280401_136_dialog_content = "(Isso faz tudo valer a pena.)"
}
return config
