ACTIVITY_OBJ_NEW = class("activityobjnew")

require("controller.activitymodules.activityobjmodules.activity_base_obj")
require("controller.activitymodules.activityobjmodules.activity_task_obj")
require("controller.activitymodules.activityobjmodules.activity_main_obj")
require("controller.activitymodules.activityobjmodules.activity_sign_obj")
require("controller.activitymodules.activityobjmodules.activity_pt_obj")
require("controller.activitymodules.activityobjmodules.activity_bp_obj")
require("controller.activitymodules.activityobjmodules.activity_collect_obj")
require("controller.activitymodules.activityobjmodules.activity_flop_obj")
require("controller.activitymodules.activityobjmodules.activity_explore_obj")
require("controller.activitymodules.activityobjmodules.activity_question_obj")
require("controller.activitymodules.activityobjmodules.activity_wakefund_obj")
require("controller.activitymodules.activityobjmodules.activity_roulette_obj")
require("controller.activitymodules.activityobjmodules.activity_art_obj")
require("controller.activitymodules.activityobjmodules.activity_red_packet_obj")
require("controller.activitymodules.activityobjmodules.activity_coupons_obj")
require("controller.activitymodules.activityobjmodules.activity_shop_obj")
require("controller.activitymodules.activityobjmodules.activity_timesign_obj")
require("controller.activitymodules.activityobjmodules.activity_story_obj")
require("controller.activitymodules.activityobjmodules.activity_level_obj")
require("controller.activitymodules.activityobjmodules.activity_multi_pt_obj")
require("controller.activitymodules.activityobjmodules.activity_study_obj")
require("controller.activitymodules.activityobjmodules.activity_warorder_obj")
require("controller.activitymodules.activityobjmodules.activity_recruit_obj")
require("controller.activitymodules.activityobjmodules.activity_lolshare_obj")
require("controller.activitymodules.activityobjmodules.activity_manage_money_obj")
require("controller.activitymodules.activityobjmodules.activity_twist_return_obj")
require("controller.activitymodules.activityobjmodules.activity_auto_chess_obj")
require("controller.activitymodules.activityobjmodules.activity_jumptower_obj")
require("controller.activitymodules.activityobjmodules.activity_bossfight_obj")
require("controller.activitymodules.activityobjmodules.activity_rogue_explore_obj")
require("controller.activitymodules.activityobjmodules.activity_commonflop_obj")
require("controller.activitymodules.activityobjmodules.activity_airplane_obj")
require("controller.activitymodules.activityobjmodules.activity_flychess_obj")
require("controller.activitymodules.activityobjmodules.activity_bakery_obj")
require("controller.activitymodules.activityobjmodules.activity_worldboss_obj")
require("controller.activitymodules.activityobjmodules.activity_bestcombo_obj")
require("controller.activitymodules.activityobjmodules.activity_alchemy_obj")
require("controller.activitymodules.activityobjmodules.activity_springfirecracker_obj")
require("controller.activitymodules.activityobjmodules.activity_smallgame_obj")

function ACTIVITY_OBJ_NEW:ctor(arg_1_1, arg_1_2, arg_1_3, arg_1_4)
	self:init_activity_base_info(arg_1_1, arg_1_2, arg_1_3, arg_1_4)
end

return ACTIVITY_OBJ_NEW
