---
--- Generated by zhaoyuhao
--- Created by zhaoyuhao.
--- DateTime: 2021/11/25 13:55
--- Project: cat-proj
---
local UIModule     = CS.Engine.UI.UIModule
local cardConfMgr  = CardConfMgr:GetInstance()
local roleVoiceMgr = RoleVoiceMgr:GetInstance()
local CriWareUtils = GameUtils.GetCriWareUtils()

--- from: Assets/BundleResources/Prefabs/Gachapon/GachaponResult.prefab > name: GachaponResult
---@class GachaponResultNew
---@field Env                           	GachaponResultNew                       
---@field controller                    	Engine.UI.UILuaDialog                   
---@field BottomTips                    	UnityEngine.RectTransform               @ 点击关闭提示
---@field BtnShare                      	UnityEngine.UI.Button                   @ 分享按钮
---@field BtnSkip                       	UnityEngine.UI.Button                   @ 跳过按钮
---@field TxtCVContent                  	UnityEngine.RectTransform               @ 声优台词文本
---@field TxtCVName                     	UnityEngine.RectTransform               @ 声优名字文本
---@field TxtCat                        	UnityEngine.RectTransform               @ 猫装饰字
---@field RoleEngName                   	UnityEngine.RectTransform               @ 英文名字
---@field RoleName                      	UnityEngine.UI.Text                     @ 角色名字
---@field ImgFloorLine                  	UnityEngine.RectTransform               @ 品质名字线条
---@field ImgNew                        	UnityEngine.RectTransform               @ 新获得图标
---@field RareParticle3                 	UnityEngine.RectTransform               @ 品质特效-粒子3
---@field RareParticle2                 	UnityEngine.RectTransform               @ 品质特效-粒子2
---@field RareParticle1                 	UnityEngine.RectTransform               @ 品质特效-粒子1
---@field ImgRareIcon2                  	UnityEngine.RectTransform               @ 品质图标文字2
---@field ImgRareIcon                   	UnityEngine.UI.Image                    @ 品质图标文字
---@field ImgRareIconbg                 	UnityEngine.RectTransform               @ 品质图标背景
---@field RaceTypeTxt                   	UnityEngine.RectTransform               @ 阵营信息-文字
---@field RaceTypeImg                   	UnityEngine.RectTransform               @ 阵营信息-图标
---@field CareerTxt                     	UnityEngine.RectTransform               @ 卡牌职业-文字
---@field CareerImg                     	UnityEngine.UI.Image                    @ 卡牌职业-图标
---@field ElementTxt                    	UnityEngine.RectTransform               @ 卡牌属性-文字
---@field ElementImg                    	UnityEngine.UI.Image                    @ 卡牌属性-底图
---@field CardName                      	UnityEngine.UI.Text                     @ 卡牌名字-文字
---@field ScreenBlock                   	UnityEngine.RectTransform               @ 穿透屏蔽节点
---@field SsrLight                      	UnityEngine.RectTransform               @ 卡牌信息底衬
---@field frontBlock                    	UnityEngine.RectTransform               @ 黑底前景
---@field screenBtn                     	UnityEngine.UI.Button                   @ 全屏点击
local GachaponResultNew = Class("GachaponResultNew")


function GachaponResultNew:__init()
    ---@type table @ 抽卡结果数据
    self._gachaponData = nil

    ---@type boolean @ 是否显示ssr光
    self._isShowSsrLight = false

    ---@type fun():void
    self._closeCallback = nil
end


function GachaponResultNew:__delete()
    self._gachaponData   = nil
    self._isShowSsrLight = nil
    self._closeCallback  = nil
end


function GachaponResultNew:Awake()
    self.eventShareEnableCB_ = Events.AddListener(Constants.EventNames.GACHAPON_ANIM_RESULT_SHARE_ENABLE, Bind(self, self.OnShareEnableCallback_))
    self.eventCloseEnableCB_ = Events.AddListener(Constants.EventNames.GACHAPON_ANIM_RESULT_CLOSE_ENABLE, Bind(self, self.OnCloseEnableCallback_))

    SetButtonAction(self.BtnSkip, Bind(self, self.OnClickSkipButtonHandler_))
    SetButtonAction(self.screenBtn, Bind(self, self.OnClickSkipButtonHandler_))

    GameUtils.InstallShareButton(self.BtnShare, Constants.ShareType.GACHA_SSR_FRAME, 'Prefabs/Share/GachaponResultShareShowDialog.prefab')
end


function GachaponResultNew:OnInitialize()
    return CoWaitDo(function()
        local initParams     = self.controller.Argument.parameters or {}
        self._gachaponData   = checkTable(initParams.gachaponData)
        self._isShowSsrLight = checkBool(initParams.isHaveLight)
        self._closeCallback  = initParams.callback
    end)
end


function GachaponResultNew:OnFinalize()
    return CoWaitDo(function()
        Events.RemoveListener(Constants.EventNames.GACHAPON_ANIM_RESULT_SHARE_ENABLE, self.eventShareEnableCB_)
        Events.RemoveListener(Constants.EventNames.GACHAPON_ANIM_RESULT_CLOSE_ENABLE, self.eventCloseEnableCB_)
        self.controller = nil --删除lua层引⽤到的c#对象否则不会产⽣c# gc回收到对象
        self:Delete()
    end)
end


function GachaponResultNew:OnShow()
    return CoWaitDo(function()
        self:DoShowInfo_()
    end)
end


-------------------------------------------------
-- private

function GachaponResultNew:DoShowInfo_()
    CfUtils.SetActive(self.BtnSkip, false)
    CfUtils.SetActive(self.BtnShare, false)
    CfUtils.SetActive(self.screenBtn, false)
    CfUtils.SetActive(self.frontBlock, false)
    CfUtils.SetActive(self.ScreenBlock, false)
    CfUtils.SetActive(self.BottomTips, false)
    CfUtils.SetActive(self.SsrLight, self._isShowSsrLight)

    local result = checkTable(self._gachaponData)
    local cardId = checkInt(result.goodsId)
    local isNew  = isSet(result, "playerCard")
    local level  = isNew and result.playerCard.cardLevel or 1
    self:updateCardInfo_(cardId, isNew, level)
end


---@param cardId integer
---@param isNew boolean
---@param level integer
function GachaponResultNew:updateCardInfo_(cardId, isNew, level)
    CfUtils.SetActive(self.ImgNew, checkBool(isNew))

    ---@type CardVo
    local cardVo = cardConfMgr:GetCardByRefId(cardId)
    
    -- 卡牌品质
    local cardRare = checkInt(cardVo.rare)
    CfUtils.SetUISwitchText(self.TxtCat, cardRare)
    CfUtils.SetUISwitchText(self.CardName, cardRare)
    CfUtils.SetUISwitchImage(self.ImgRareIcon, cardRare)
    CfUtils.SetUISwitchImage(self.ImgRareIcon2, cardRare)
    CfUtils.SetUISwitchImage(self.ImgRareIconbg, cardRare)
    CfUtils.SetUISwitchImage(self.ImgFloorLine, cardRare)
    CfUtils.SetUISwitchParticleSystem(self.RareParticle1, cardRare)
    CfUtils.SetUISwitchParticleSystem(self.RareParticle2, cardRare)
    CfUtils.SetUISwitchParticleSystem(self.RareParticle3, cardRare)
    
    -- 卡牌名称/角色名
    local roleVo = cardConfMgr:GetRolesVo(cardVo.characterId) or {}
    CfUtils.FillText(self.RoleEngName, tostring(roleVo.englishName))
    CfUtils.FillText(self.RoleName, tostring(roleVo.name))

    local cardLevel = checkInt(level)
    local cardName  = tostring(cardVo.name)
    if cardLevel > 1 then
        CfUtils.FillText(self.CardName, localize('Lv._num_ _roleName_·_cardName_', {_num_ = cardLevel, _roleName_ = tostring(roleVo.name), _cardName_ = cardName}))
    else
        CfUtils.FillText(self.CardName, localize('_roleName_·_cardName_', {_num_ = cardLevel, _roleName_ = tostring(roleVo.name), _cardName_ = cardName}))
    end

    -- 卡牌属性
    local cardAttr = checkInt(cardVo.attributeType)
    CfUtils.SetUISwitchImage(self.ElementImg, cardAttr)
    CfUtils.FillText(self.ElementTxt, cardConfMgr:GetRoleAttributeColorVo(cardAttr).name)

    -- 卡牌职业
    local cardCareer = checkInt(cardVo.career)
    CfUtils.SetUISwitchImage(self.CareerImg, cardCareer)
    CfUtils.FillText(self.CareerTxt, cardConfMgr:GetCardCareerRowByType(cardCareer).name)

    -- 卡牌阵营
    local cardRace = checkInt(cardVo.race)
    CfUtils.FillImage(self.RaceTypeImg, CardUtils.GetCardRaceIconPath(cardRace))
    CfUtils.FillText(self.RaceTypeTxt, cardConfMgr:GetRoleRaceVoById(cardRace).name)
    
    -- 角色声优
    CfUtils.FillText(self.TxtCVName, localize('CV: _name_', {_name_ = cardVo.cv}))

    -- 播放当前卡牌的台词
    ---@type RoleVoiceVo
    local roleVoiceVo = roleVoiceMgr:PlayDrawCardVoiceByCardId(cardId, nil, cardVo.defaultSkin)
    if roleVoiceVo then
        CfUtils.FillText(self.TxtCVContent, roleVoiceVo:GetDesk())
    else
        local errorTips = string.format("卡牌<%s>未在【角色表/角色台词表】找到对应数据", tostring(cardId))
        if Config.DEBUG then
            CfUtils.FillText(self.TxtCVContent, string.format("<color=#FF66FF>%s</color>", errorTips))
        else
            printError(errorTips)
        end
    end
end


-------------------------------------------------
-- handler

function GachaponResultNew:OnShareEnableCallback_()
    Events.Broadcast(Constants.EventNames.SHARE_BUTTON_REFRESH)
    CfUtils.SetActive(self.BottomTips, true)
end


function GachaponResultNew:OnCloseEnableCallback_()
    CfUtils.SetActive(self.BottomTips, true)
end


function GachaponResultNew:OnClickSkipButtonHandler_()
    if self._isPop ~= nil and self._isPop then
        return
    end

    self._isPop = true

    if self._closeCallback ~= nil then
        self._closeCallback()
    end

    self.controller:Close()
end


return GachaponResultNew
