return {
	CURRENCY_TYPE_DIAMOND = {
		id = "CURRENCY_TYPE_DIAMOND",
		item_id = 1,
		hide_number = 0
	},
	CURRENCY_TYPE_GOLD = {
		id = "CURRENCY_TYPE_GOLD",
		item_id = 2,
		hide_number = 0
	},
	CURRENCY_TYPE_FRIENDSHIP_POINT = {
		id = "CURRENCY_TYPE_FRIENDSHIP_POINT",
		item_id = 3,
		hide_number = 0
	},
	CURRENCY_TYPE_FATIGUE = {
		id = "CURRENCY_TYPE_FATIGUE",
		item_id = 4,
		hide_number = 0
	},
	CURRENCY_TYPE_TREASURE_TICKET = {
		id = "CURRENCY_TYPE_TREASURE_TICKET",
		item_id = 5,
		hide_number = 0
	},
	CURRENCY_TYPE_CHANGE_NAME_CARD = {
		id = "CURRENCY_TYPE_CHANGE_NAME_CARD",
		item_id = 6,
		hide_number = 0
	},
	CURRENCY_TYPE_CLUB_MEDAL = {
		id = "CURRENCY_TYPE_CLUB_MEDAL",
		item_id = 7,
		hide_number = 0
	},
	CURRENCY_TYPE_CLUB_POPULARITY = {
		id = "CURRENCY_TYPE_CLUB_POPULARITY",
		item_id = 8,
		hide_number = 0
	},
	CURRENCY_TYPE_INTELLIGENCE_POINT = {
		id = "CURRENCY_TYPE_INTELLIGENCE_POINT",
		item_id = 9,
		hide_number = 0
	},
	CURRENCY_TYPE_MYSTICAL_DIAMOND = {
		id = "CURRENCY_TYPE_MYSTICAL_DIAMOND",
		item_id = 10,
		hide_number = 0
	},
	CURRENCY_TYPE_BATTLEPASS_POINT = {
		id = "CURRENCY_TYPE_BATTLEPASS_POINT",
		item_id = 11,
		hide_number = 0
	},
	CURRENCY_TYPE_USER_EXP = {
		id = "CURRENCY_TYPE_USER_EXP",
		item_id = 12,
		hide_number = 1
	},
	CURRENCY_TYPE_HERO_EXP = {
		id = "CURRENCY_TYPE_HERO_EXP",
		item_id = 13,
		hide_number = 0
	},
	CURRENCY_TYPE_BATTLEPASS_EXP = {
		id = "CURRENCY_TYPE_BATTLEPASS_EXP",
		item_id = 14,
		hide_number = 1
	},
	CURRENCY_TYPE_INFO_BADGE_LOW = {
		id = "CURRENCY_TYPE_INFO_BADGE_LOW",
		item_id = 15,
		hide_number = 0
	},
	CURRENCY_TYPE_INFO_BADGE_MID = {
		id = "CURRENCY_TYPE_INFO_BADGE_MID",
		item_id = 40901,
		hide_number = 0
	},
	CURRENCY_TYPE_INFO_BADGE_TOP = {
		id = "CURRENCY_TYPE_INFO_BADGE_TOP",
		item_id = 40902,
		hide_number = 0
	},
	CURRENCY_TYPE_RECALL_CHAPTER = {
		id = "CURRENCY_TYPE_RECALL_CHAPTER",
		item_id = 18,
		hide_number = 0
	},
	CURRENCY_TYPE_TREASURE_TICKET_EQUIP = {
		id = "CURRENCY_TYPE_TREASURE_TICKET_EQUIP",
		item_id = 19,
		hide_number = 0
	},
	CURRENCY_TYPE_FIVE_STAR_EQUIP_RESOLVE = {
		id = "CURRENCY_TYPE_FIVE_STAR_EQUIP_RESOLVE",
		item_id = 41001,
		hide_number = 0
	},
	CURRENCY_TYPE_SIX_STAR_EQUIP_RESOLVE = {
		id = "CURRENCY_TYPE_SIX_STAR_EQUIP_RESOLVE",
		item_id = 41002,
		hide_number = 0
	},
	CURRENCY_TYPE_DAILY_ACTIVITY_PT = {
		id = "CURRENCY_TYPE_DAILY_ACTIVITY_PT",
		item_id = 22,
		hide_number = 1
	},
	CURRENCY_TYPE_NEW_ACTIVITY_PT = {
		id = "CURRENCY_TYPE_NEW_ACTIVITY_PT",
		item_id = 23,
		hide_number = 1
	},
	CURRENCY_TYPE_SKIN = {
		id = "CURRENCY_TYPE_SKIN",
		item_id = 24,
		hide_number = 0
	},
	CURRENCY_TYPE_MYTHIC = {
		id = "CURRENCY_TYPE_MYTHIC",
		item_id = 25,
		hide_number = 0
	},
	CURRENCY_TYPE_MATRIX_COIN = {
		id = "CURRENCY_TYPE_MATRIX_COIN",
		item_id = 26,
		hide_number = 0
	},
	CURRENCY_TYPE_MATRIX_RING = {
		id = "CURRENCY_TYPE_MATRIX_RING",
		item_id = 27,
		hide_number = 0
	},
	CURRENCY_TYPE_MATRIX_CERTIFICATION = {
		id = "CURRENCY_TYPE_MATRIX_CERTIFICATION",
		item_id = 28,
		hide_number = 0
	},
	CURRENCY_TYPE_MATRIX_PT = {
		id = "CURRENCY_TYPE_MATRIX_PT",
		item_id = 29,
		hide_number = 0
	},
	CURRENCY_TYPE_RECHARGE_DIAMOND_IOS = {
		id = "CURRENCY_TYPE_RECHARGE_DIAMOND_IOS",
		item_id = 30,
		hide_number = 0
	},
	CURRENCY_TYPE_RECHARGE_DIAMOND_NOT_IOS = {
		id = "CURRENCY_TYPE_RECHARGE_DIAMOND_NOT_IOS",
		item_id = 31,
		hide_number = 0
	},
	CURRENCY_TYPE_RECHARGE_DIAMOND_FREE = {
		id = "CURRENCY_TYPE_RECHARGE_DIAMOND_FREE",
		item_id = 32,
		hide_number = 0
	},
	CURRENCY_TYPE_ACHIEVEMENT_POINT = {
		id = "CURRENCY_TYPE_ACHIEVEMENT_POINT",
		item_id = 33,
		hide_number = 0
	},
	CURRENCY_TYPE_MATRIX_TERMINAL_EXP = {
		id = "CURRENCY_TYPE_MATRIX_TERMINAL_EXP",
		item_id = 34,
		hide_number = 0
	},
	CURRENCY_TYPE_WEEK_ACTIVITY_PT = {
		id = "CURRENCY_TYPE_WEEK_ACTIVITY_PT",
		item_id = 35,
		hide_number = 1
	},
	CURRENCY_TYPE_DRAW = {
		id = "CURRENCY_TYPE_DRAW",
		item_id = 36,
		hide_number = 0
	},
	CURRENCY_TYPE_BOSS_CHALLENGE = {
		id = "CURRENCY_TYPE_BOSS_CHALLENGE",
		item_id = 37,
		hide_number = 0
	},
	CURRENCY_TYPE_TREASURE_TICKET_ACTIVITY = {
		id = "CURRENCY_TYPE_TREASURE_TICKET_ACTIVITY",
		item_id = 38,
		hide_number = 0
	},
	CURRENCY_TYPE_DORM_GOLD = {
		id = "CURRENCY_TYPE_DORM_GOLD",
		item_id = 39,
		hide_number = 0
	},
	CURRENCY_TYPE_CLUB_COIN_A = {
		id = "CURRENCY_TYPE_CLUB_COIN_A",
		item_id = 52001,
		hide_number = 0
	},
	CURRENCY_TYPE_CLUB_COIN_B = {
		id = "CURRENCY_TYPE_CLUB_COIN_B",
		item_id = 40,
		hide_number = 0
	},
	CURRENCY_TYPE_BOSS_CHALLENGE_S = {
		id = "CURRENCY_TYPE_BOSS_CHALLENGE_S",
		item_id = 41,
		hide_number = 0
	},
	CURRENCY_TYPE_OSIRIS_INFINITY_COIN = {
		id = "CURRENCY_TYPE_OSIRIS_INFINITY_COIN",
		item_id = 53001,
		hide_number = 0
	},
	CURRENCY_TYPE_HELLA_TALENT_TREE_COIN = {
		id = "CURRENCY_TYPE_HELLA_TALENT_TREE_COIN",
		item_id = 54001,
		hide_number = 0
	},
	CURRENCY_TYPE_HELLA_SHOP_COIN = {
		id = "CURRENCY_TYPE_HELLA_SHOP_COIN",
		item_id = 54002,
		hide_number = 0
	},
	CURRENCY_TYPE_SUMMER_FISHING_COIN = {
		id = "CURRENCY_TYPE_SUMMER_FISHING_COIN",
		item_id = 54003,
		hide_number = 0
	},
	CURRENCY_TYPE_RETURN_COIN = {
		id = "CURRENCY_TYPE_RETURN_COIN",
		item_id = 54004,
		hide_number = 0
	},
	CURRENCY_TYPE_SUMMER_SKIN_COIN = {
		id = "CURRENCY_TYPE_SUMMER_SKIN_COIN",
		item_id = 54005,
		hide_number = 0
	},
	CURRENCY_TYPE_SUMMER_PT = {
		id = "CURRENCY_TYPE_SUMMER_PT",
		item_id = 54006,
		hide_number = 0
	},
	CURRENCY_TYPE_BOSS_CHALLENGE_ADVANCE = {
		id = "CURRENCY_TYPE_BOSS_CHALLENGE_ADVANCE",
		item_id = 42,
		hide_number = 0
	},
	CURRENCY_TYPE_CHAPTERIII_PT = {
		id = "CURRENCY_TYPE_CHAPTERIII_PT",
		item_id = 53003,
		hide_number = 0
	},
	CURRENCY_TYPE_ACTIVITY_RACE = {
		id = "CURRENCY_TYPE_ACTIVITY_RACE",
		item_id = 53006,
		hide_number = 0
	},
	CURRENCY_TYPE_CHAPTERIII_DOWN_PT = {
		id = "CURRENCY_TYPE_CHAPTERIII_DOWN_PT",
		item_id = 53007,
		hide_number = 0
	},
	CURRENCY_TYPE_ACTIVITY_CLUB_BOSS_MAP_COIN = {
		id = "CURRENCY_TYPE_ACTIVITY_CLUB_BOSS_MAP_COIN",
		item_id = 53008,
		hide_number = 0
	},
	CURRENCY_TYPE_FINAL_MYTHIC = {
		id = "CURRENCY_TYPE_FINAL_MYTHIC",
		item_id = 43,
		hide_number = 0
	},
	CURRENCY_TYPE_FACTORY_INFINITY_COIN = {
		id = "CURRENCY_TYPE_FACTORY_INFINITY_COIN",
		item_id = 53010,
		hide_number = 0
	},
	CURRENCY_TYPE_FACTORY_PT = {
		id = "CURRENCY_TYPE_FACTORY_PT",
		item_id = 53011,
		hide_number = 0
	},
	CURRENCY_TYPE_FESTIVAL_MONSTER_PT = {
		id = "CURRENCY_TYPE_FESTIVAL_MONSTER_PT",
		item_id = 53012,
		hide_number = 0
	},
	CURRENCY_TYPE_EMPTYDREAM_PT = {
		id = "CURRENCY_TYPE_EMPTYDREAM_PT",
		item_id = 53013,
		hide_number = 0
	},
	CURRENCY_TYPE_PASS_SENIOR_COIN = {
		id = "CURRENCY_TYPE_PASS_SENIOR_COIN",
		item_id = 53014,
		hide_number = 0
	},
	CURRENCY_TYPE_PASS_LOWER_COIN = {
		id = "CURRENCY_TYPE_PASS_LOWER_COIN",
		item_id = 53015,
		hide_number = 0
	},
	CURRENCY_TYPE_FESTIVAL_CANTEEN_COIN = {
		id = "CURRENCY_TYPE_FESTIVAL_CANTEEN_COIN",
		item_id = 54013,
		hide_number = 0
	},
	CURRENCY_TYPE_TYR_COIN = {
		id = "CURRENCY_TYPE_TYR_COIN",
		item_id = 53016,
		hide_number = 0
	},
	CURRENCY_XUHENG_COIN = {
		id = "CURRENCY_XUHENG_COIN",
		item_id = 53017,
		hide_number = 0
	},
	CURRENCY_XUHENG_TICKET = {
		id = "CURRENCY_XUHENG_TICKET",
		item_id = 54014,
		hide_number = 0
	},
	CURRENCY_XUHENG_CULTIVATE_COIN = {
		id = "CURRENCY_XUHENG_CULTIVATE_COIN",
		item_id = 54015,
		hide_number = 0
	},
	CURRENCY_TYPE_NEW_RETURN_COIN = {
		id = "CURRENCY_TYPE_NEW_RETURN_COIN",
		item_id = 54016,
		hide_number = 0
	},
	CURRENCY_TYPE_RECALLED_COIN = {
		id = "CURRENCY_TYPE_RECALLED_COIN",
		item_id = 53021,
		hide_number = 0
	},
	CURRENCY_TYPE_DRAW_FEEDBACK_COIN = {
		id = "CURRENCY_TYPE_DRAW_FEEDBACK_COIN",
		item_id = 53022,
		hide_number = 0
	},
	CURRENCY_TYPE_UNLOCK_PROPS = {
		id = "CURRENCY_TYPE_UNLOCK_PROPS",
		item_id = 44,
		hide_number = 0
	},
	CURRENCY_TYPE_SHIFTING_EXP = {
		id = "CURRENCY_TYPE_SHIFTING_EXP",
		item_id = 45,
		hide_number = 0
	},
	CURRENCY_TYPE_WEAPON_MODULE = {
		id = "CURRENCY_TYPE_WEAPON_MODULE",
		item_id = 41601,
		hide_number = 0
	},
	CURRENCY_TYPE_POLYHEDRON_TERMINAL_EXP = {
		id = "CURRENCY_TYPE_POLYHEDRON_TERMINAL_EXP",
		item_id = 46,
		hide_number = 0
	},
	CURRENCY_XUHENG_PT_COIN = {
		id = "CURRENCY_XUHENG_PT_COIN",
		item_id = 53023,
		hide_number = 0
	},
	CURRENCY_XUHENG_PT_TICKET = {
		id = "CURRENCY_XUHENG_PT_TICKET",
		item_id = 54017,
		hide_number = 0
	},
	CURRENCY_XUHENG_LULIANG_CHAPTER_TICKET = {
		id = "CURRENCY_XUHENG_LULIANG_CHAPTER_TICKET",
		item_id = 54018,
		hide_number = 0
	},
	CURRENCY_XUHENG_CULTIVATE_COIN_A = {
		id = "CURRENCY_XUHENG_CULTIVATE_COIN_A",
		item_id = 54019,
		hide_number = 0
	},
	CURRENCY_TYPE_CHIP_COST = {
		id = "CURRENCY_TYPE_CHIP_COST",
		item_id = 47,
		hide_number = 0
	},
	CURRENCY_LINKGAME_COST = {
		id = "CURRENCY_LINKGAME_COST",
		item_id = 53207,
		hide_number = 0
	},
	CURRENCY_PUZZLE_FRAGMENT = {
		id = "CURRENCY_PUZZLE_FRAGMENT",
		item_id = 53025,
		hide_number = 0
	},
	CURRENCY_PUZZLE_COIN = {
		id = "CURRENCY_PUZZLE_COIN",
		item_id = 53026,
		hide_number = 0
	},
	CURRENCY_PUZZLE_III_COIN = {
		id = "CURRENCY_PUZZLE_III_COIN",
		item_id = 53034,
		hide_number = 0
	},
	CURRENCY_TYPE_PERIODICITY_EXPLORE_TICKER_INSTANCE = {
		id = "CURRENCY_TYPE_PERIODICITY_EXPLORE_TICKER_INSTANCE",
		item_id = 48,
		hide_number = 0
	},
	CURRENCY_TYPE_PERIODICITY_EXPLORE_TICKER_TEMPLATE_1 = {
		id = "CURRENCY_TYPE_PERIODICITY_EXPLORE_TICKER_TEMPLATE_1",
		item_id = 49,
		hide_number = 0
	},
	CURRENCY_TYPE_PERIODICITY_EXPLORE_TICKER_TEMPLATE_2 = {
		id = "CURRENCY_TYPE_PERIODICITY_EXPLORE_TICKER_TEMPLATE_2",
		item_id = 50,
		hide_number = 0
	},
	CURRENCY_TYPE_PERIODICITY_EXPLORE_TICKER_TEMPLATE_3 = {
		id = "CURRENCY_TYPE_PERIODICITY_EXPLORE_TICKER_TEMPLATE_3",
		item_id = 51,
		hide_number = 0
	},
	CURRENCY_TYPE_PERIODICITY_EXPLORE_TICKER_TEMPLATE_4 = {
		id = "CURRENCY_TYPE_PERIODICITY_EXPLORE_TICKER_TEMPLATE_4",
		item_id = 52,
		hide_number = 0
	},
	CURRENCY_TYPE_EXPLORE_EXP = {
		id = "CURRENCY_TYPE_EXPLORE_EXP",
		item_id = 53,
		hide_number = 0
	},
	CURRENCY_TYPE_EXPLORE_GOLD_1 = {
		id = "CURRENCY_TYPE_EXPLORE_GOLD_1",
		item_id = 54,
		hide_number = 0
	},
	CURRENCY_TYPE_EXPLORE_GOLD_2 = {
		id = "CURRENCY_TYPE_EXPLORE_GOLD_2",
		item_id = 55,
		hide_number = 0
	},
	CURRENCY_TYPE_EXPLORE_GOLD_3 = {
		id = "CURRENCY_TYPE_EXPLORE_GOLD_3",
		item_id = 56,
		hide_number = 0
	},
	CURRENCY_TYPE_ACTIVITY_WATER_ASSISTANCE = {
		id = "CURRENCY_TYPE_ACTIVITY_WATER_ASSISTANCE",
		item_id = 54023,
		hide_number = 0
	},
	CURRENCY_TYPE_ACTIVITY_WATER_TOKENS = {
		id = "CURRENCY_TYPE_ACTIVITY_WATER_TOKENS",
		item_id = 53027,
		hide_number = 0
	},
	CURRENCY_XUHENG_PT_COIN_2_2 = {
		id = "CURRENCY_XUHENG_PT_COIN_2_2",
		item_id = 53028,
		hide_number = 0
	},
	CURRENCY_XUHENG_PT_TICKET_2_2 = {
		id = "CURRENCY_XUHENG_PT_TICKET_2_2",
		item_id = 54024,
		hide_number = 0
	},
	CURRENCY_TYPE_FLIP_CARD_TICKET = {
		id = "CURRENCY_TYPE_FLIP_CARD_TICKET",
		item_id = 54025,
		hide_number = 0
	},
	CURRENCY_TYPE_ACTIVITY_SKADI_SEA_COIN = {
		id = "CURRENCY_TYPE_ACTIVITY_SKADI_SEA_COIN",
		item_id = 54021,
		hide_number = 0
	},
	CURRENCY_TYPE_STRONGHOLD_EXP_1 = {
		id = "CURRENCY_TYPE_STRONGHOLD_EXP_1",
		item_id = 54026,
		hide_number = 0
	},
	CURRENCY_TYPE_STRONGHOLD_EXP_2 = {
		id = "CURRENCY_TYPE_STRONGHOLD_EXP_2",
		item_id = 54027,
		hide_number = 0
	},
	CURRENCY_TYPE_STRONGHOLD_EXP_3 = {
		id = "CURRENCY_TYPE_STRONGHOLD_EXP_3",
		item_id = 54028,
		hide_number = 0
	},
	CURRENCY_TYPE_GENGCHEN_SKIN_COIN = {
		id = "CURRENCY_TYPE_GENGCHEN_SKIN_COIN",
		item_id = 53029,
		hide_number = 0
	},
	CURRENCY_TYPE_GENGCHEN_SKIN_TICKET = {
		id = "CURRENCY_TYPE_GENGCHEN_SKIN_TICKET",
		item_id = 53030,
		hide_number = 0
	},
	CURRENCY_TYPE_GENGCHEN_SCENE_TICKET = {
		id = "CURRENCY_TYPE_GENGCHEN_SCENE_TICKET",
		item_id = 53031,
		hide_number = 0
	},
	CURRENCY_PT_COIN_2_4_UP = {
		id = "CURRENCY_PT_COIN_2_4_UP",
		item_id = 53032,
		hide_number = 0
	},
	CURRENCY_PT_COIN_2_4_DOWN = {
		id = "CURRENCY_PT_COIN_2_4_DOWN",
		item_id = 53033,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_2_4_UP = {
		id = "CURRENCY_PT_TICKET_2_4_UP",
		item_id = 54030,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_2_4_DOWN = {
		id = "CURRENCY_PT_TICKET_2_4_DOWN",
		item_id = 54031,
		hide_number = 0
	},
	CURRENCY_TYPE_ACTIVITY_CLUB_BOSS_SP_MAP_COIN = {
		id = "CURRENCY_TYPE_ACTIVITY_CLUB_BOSS_SP_MAP_COIN",
		item_id = 54032,
		hide_number = 0
	},
	CURRENCY_TYPE_ACTIVITY_CLUB_BOSS_SP_MAP_COIN_B = {
		id = "CURRENCY_TYPE_ACTIVITY_CLUB_BOSS_SP_MAP_COIN_B",
		item_id = 54033,
		hide_number = 0
	},
	CURRENCY_TYPE_SKIN_RECHARGE = {
		id = "CURRENCY_TYPE_SKIN_RECHARGE",
		item_id = 57,
		hide_number = 0
	},
	CURRENCY_TYPE_ACTIVITY_KAGUTSUCHI_COIN = {
		id = "CURRENCY_TYPE_ACTIVITY_KAGUTSUCHI_COIN",
		item_id = 53078,
		hide_number = 0
	},
	CURRENCY_TYPE_ACTIVITY_KAGUTSUCHI_FATIGUE = {
		id = "CURRENCY_TYPE_ACTIVITY_KAGUTSUCHI_FATIGUE",
		item_id = 54036,
		hide_number = 0
	},
	CURRENCY_PT_COIN_2_7 = {
		id = "CURRENCY_PT_COIN_2_7",
		item_id = 53080,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_2_7 = {
		id = "CURRENCY_PT_TICKET_2_7",
		item_id = 54039,
		hide_number = 0
	},
	CURRENCY_TYPE_NEW_WARCHESS_MOVE = {
		id = "CURRENCY_TYPE_NEW_WARCHESS_MOVE",
		item_id = 53082,
		hide_number = 0
	},
	CURRENCY_PT_ROULETTE_COIN_2_6 = {
		id = "CURRENCY_PT_ROULETTE_COIN_2_6",
		item_id = 53079,
		hide_number = 0
	},
	CURRENCY_PT_ROULETTE_TICKET_2_6 = {
		id = "CURRENCY_PT_ROULETTE_TICKET_2_6",
		item_id = 54037,
		hide_number = 0
	},
	CURRENCY_TYPE_ACCURATE_EXPLORE_TICKER_INSTANCE = {
		id = "CURRENCY_TYPE_ACCURATE_EXPLORE_TICKER_INSTANCE",
		item_id = 58,
		hide_number = 0
	},
	CURRENCY_TYPE_ACCURATE_EXPLORE_TICKER_TEMPLATE_1 = {
		id = "CURRENCY_TYPE_ACCURATE_EXPLORE_TICKER_TEMPLATE_1",
		item_id = 59,
		hide_number = 0
	},
	CURRENCY_PT_COIN_2_8 = {
		id = "CURRENCY_PT_COIN_2_8",
		item_id = 53085,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_2_8 = {
		id = "CURRENCY_PT_TICKET_2_8",
		item_id = 54047,
		hide_number = 0
	},
	CURRENCY_PT_COIN_2_9 = {
		id = "CURRENCY_PT_COIN_2_9",
		item_id = 53086,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_2_9 = {
		id = "CURRENCY_PT_TICKET_2_9",
		item_id = 54048,
		hide_number = 0
	},
	CURRENCY_TYPE_ACTIVITY_CLUB_BOSS_SP_MAP_COIN_2_8 = {
		id = "CURRENCY_TYPE_ACTIVITY_CLUB_BOSS_SP_MAP_COIN_2_8",
		item_id = 54050,
		hide_number = 0
	},
	CURRENCY_TYPE_ACTIVITY_CLUB_BOSS_SP_MAP_COIN_B_2_8 = {
		id = "CURRENCY_TYPE_ACTIVITY_CLUB_BOSS_SP_MAP_COIN_B_2_8",
		item_id = 54051,
		hide_number = 0
	},
	CURRENCY_NIAN_PT_2_9 = {
		id = "CURRENCY_NIAN_PT_2_9",
		item_id = 53087,
		hide_number = 0
	},
	CURRENCY_PT_COIN_2_10 = {
		id = "CURRENCY_PT_COIN_2_10",
		item_id = 53092,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_2_10 = {
		id = "CURRENCY_PT_TICKET_2_10",
		item_id = 54052,
		hide_number = 0
	},
	CURRENCY_TYPE_NEW_WARCHESS_MOVE_2_10 = {
		id = "CURRENCY_TYPE_NEW_WARCHESS_MOVE_2_10",
		item_id = 53093,
		hide_number = 0
	},
	CURRENCY_PT_COIN_2_11 = {
		id = "CURRENCY_PT_COIN_2_11",
		item_id = 53098,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_2_11 = {
		id = "CURRENCY_PT_TICKET_2_11",
		item_id = 54056,
		hide_number = 0
	},
	CURRENCY_TYPE_CORE_COIN = {
		id = "CURRENCY_TYPE_CORE_COIN",
		item_id = 60,
		hide_number = 0
	},
	CURRENCY_HERO_CHALLENGE_COIN_1 = {
		id = "CURRENCY_HERO_CHALLENGE_COIN_1",
		item_id = 53100,
		hide_number = 0
	},
	CURRENCY_HERO_CHALLENGE_COIN_2 = {
		id = "CURRENCY_HERO_CHALLENGE_COIN_2",
		item_id = 53101,
		hide_number = 0
	},
	CURRENCY_HERO_CHALLENGE_TICKET = {
		id = "CURRENCY_HERO_CHALLENGE_TICKET",
		item_id = 54057,
		hide_number = 0
	},
	CURRENCY_PT_COIN_3_0 = {
		id = "CURRENCY_PT_COIN_3_0",
		item_id = 53103,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_3_0 = {
		id = "CURRENCY_PT_TICKET_3_0",
		item_id = 54060,
		hide_number = 0
	},
	CURRENCY_PT_COIN_3_1 = {
		id = "CURRENCY_PT_COIN_3_1",
		item_id = 53104,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_3_1 = {
		id = "CURRENCY_PT_TICKET_3_1",
		item_id = 54061,
		hide_number = 0
	},
	CURRENCY_TYPE_ACCURATE_EXPLORE_PROOF = {
		id = "CURRENCY_TYPE_ACCURATE_EXPLORE_PROOF",
		item_id = 64,
		hide_number = 0
	},
	CURRENCY_TYPE_ACTIVITY_NEW_SERVER = {
		id = "CURRENCY_TYPE_ACTIVITY_NEW_SERVER",
		item_id = 54063,
		hide_number = 0
	},
	CURRENCY_TYPE_ACCURATE_EXPLORE_TICKER_INSTANCE_NEW = {
		id = "CURRENCY_TYPE_ACCURATE_EXPLORE_TICKER_INSTANCE_NEW",
		item_id = 62,
		hide_number = 0
	},
	CURRENCY_TYPE_PERIODICITY_EXPLORE_TICKER_TEMPLATE_NEW_1 = {
		id = "CURRENCY_TYPE_PERIODICITY_EXPLORE_TICKER_TEMPLATE_NEW_1",
		item_id = 63,
		hide_number = 0
	},
	CURRENCY_TYPE_PERIODICITY_EXPLORE_TICKER_TEMPLATE_NEW_2 = {
		id = "CURRENCY_TYPE_PERIODICITY_EXPLORE_TICKER_TEMPLATE_NEW_2",
		item_id = 65,
		hide_number = 0
	},
	CURRENCY_PT_COIN_3_2 = {
		id = "CURRENCY_PT_COIN_3_2",
		item_id = 53108,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_3_2 = {
		id = "CURRENCY_PT_TICKET_3_2",
		item_id = 54067,
		hide_number = 0
	},
	CURRENCY_TYPE_GENGCHEN_SKIN_COIN_3_2 = {
		id = "CURRENCY_TYPE_GENGCHEN_SKIN_COIN_3_2",
		item_id = 53111,
		hide_number = 0
	},
	CURRENCY_TYPE_GENGCHEN_SKIN_TICKET_3_2 = {
		id = "CURRENCY_TYPE_GENGCHEN_SKIN_TICKET_3_2",
		item_id = 53109,
		hide_number = 0
	},
	CURRENCY_TYPE_GENGCHEN_SCENE_TICKET_3_2 = {
		id = "CURRENCY_TYPE_GENGCHEN_SCENE_TICKET_3_2",
		item_id = 53110,
		hide_number = 0
	},
	CURRENCY_PT_COIN_3_4 = {
		id = "CURRENCY_PT_COIN_3_4",
		item_id = 53113,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_3_4 = {
		id = "CURRENCY_PT_TICKET_3_4",
		item_id = 54070,
		hide_number = 0
	},
	CURRENCY_ACTIVITY_SIM_BUSINESS_3_5 = {
		id = "CURRENCY_ACTIVITY_SIM_BUSINESS_3_5",
		item_id = 54112,
		hide_number = 0
	},
	CURRENCY_PUZZLE_III_COIN_3_5 = {
		id = "CURRENCY_PUZZLE_III_COIN_3_5",
		item_id = 53116,
		hide_number = 0
	},
	CURRENCY_PT_COIN_3_5 = {
		id = "CURRENCY_PT_COIN_3_5",
		item_id = 53117,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_3_5 = {
		id = "CURRENCY_PT_TICKET_3_5",
		item_id = 54071,
		hide_number = 0
	},
	CURRENCY_STRATEGYMATRIX_TICKET_3_5 = {
		id = "CURRENCY_STRATEGYMATRIX_TICKET_3_5",
		item_id = 53115,
		hide_number = 0
	},
	CURRENCY_PT_COIN_3_6 = {
		id = "CURRENCY_PT_COIN_3_6",
		item_id = 53119,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_3_6 = {
		id = "CURRENCY_PT_TICKET_3_6",
		item_id = 54073,
		hide_number = 0
	},
	CURRENCY_SHOP_COIN = {
		id = "CURRENCY_SHOP_COIN",
		item_id = 53118,
		hide_number = 0
	},
	CURRENCY_CHIP = {
		id = "CURRENCY_CHIP",
		item_id = 54114,
		hide_number = 0
	},
	CURRENCY_ROGUE_TEAM_BATTLEPASS = {
		id = "CURRENCY_ROGUE_TEAM_BATTLEPASS",
		item_id = 70,
		hide_number = 0
	},
	CURRENCY_TYPE_TUOTE_SKIN_COIN = {
		id = "CURRENCY_TYPE_TUOTE_SKIN_COIN",
		item_id = 53122,
		hide_number = 0
	},
	CURRENCY_TYPE_TUOTE_SKIN_TICKET = {
		id = "CURRENCY_TYPE_TUOTE_SKIN_TICKET",
		item_id = 53120,
		hide_number = 0
	},
	CURRENCY_TYPE_TUOTE_SCENE_TICKET = {
		id = "CURRENCY_TYPE_TUOTE_SCENE_TICKET",
		item_id = 53121,
		hide_number = 0
	},
	CURRENCY_TYPE_TUOTE_SCENE_TICKET_2 = {
		id = "CURRENCY_TYPE_TUOTE_SCENE_TICKET_2",
		item_id = 53124,
		hide_number = 0
	},
	CURRENCY_PT_COIN_3_7 = {
		id = "CURRENCY_PT_COIN_3_7",
		item_id = 53125,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_3_7 = {
		id = "CURRENCY_PT_TICKET_3_7",
		item_id = 54076,
		hide_number = 0
	},
	ACTIVITY_GOD_EATER_HUB_EXP = {
		id = "ACTIVITY_GOD_EATER_HUB_EXP",
		item_id = 74,
		hide_number = 0
	},
	CURRENCY_GOD_EATER_SHOP_COIN = {
		id = "CURRENCY_GOD_EATER_SHOP_COIN",
		item_id = 75,
		hide_number = 0
	},
	CURRENCY_PT_COIN_4_2 = {
		id = "CURRENCY_PT_COIN_4_2",
		item_id = 53160,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_4_2 = {
		id = "CURRENCY_PT_TICKET_4_2",
		item_id = 54085,
		hide_number = 0
	},
	CURRENCY_PT_COIN_3_8 = {
		id = "CURRENCY_PT_COIN_3_8",
		item_id = 53128,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_3_8 = {
		id = "CURRENCY_PT_TICKET_3_8",
		item_id = 54079,
		hide_number = 0
	},
	CURRENCY_PT_COIN_3_9 = {
		id = "CURRENCY_PT_COIN_3_9",
		item_id = 53150,
		hide_number = 0
	},
	CURRENCY_SPRING_SHOP_COIN_3_10 = {
		id = "CURRENCY_SPRING_SHOP_COIN_3_10",
		item_id = 54116,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_3_9 = {
		id = "CURRENCY_PT_TICKET_3_9",
		item_id = 54080,
		hide_number = 0
	},
	CURRENCY_PT_COIN_3_10 = {
		id = "CURRENCY_PT_COIN_3_10",
		item_id = 53152,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_3_10 = {
		id = "CURRENCY_PT_TICKET_3_10",
		item_id = 54117,
		hide_number = 0
	},
	CURRENCY_TYPE_GENGCHEN_SKIN_COIN_3_10 = {
		id = "CURRENCY_TYPE_GENGCHEN_SKIN_COIN_3_10",
		item_id = 53142,
		hide_number = 0
	},
	CURRENCY_TYPE_GENGCHEN_SKIN_TICKET_3_10 = {
		id = "CURRENCY_TYPE_GENGCHEN_SKIN_TICKET_3_10",
		item_id = 53140,
		hide_number = 0
	},
	CURRENCY_PT_COIN_3_11 = {
		id = "CURRENCY_PT_COIN_3_11",
		item_id = 53153,
		hide_number = 0
	},
	CURRENCY_QUANZHOU_COIN_4_0 = {
		id = "CURRENCY_QUANZHOU_COIN_4_0",
		item_id = 77,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_3_11 = {
		id = "CURRENCY_PT_TICKET_3_11",
		item_id = 54083,
		hide_number = 0
	},
	CURRENCY_TYPE_GENGCHEN_SCENE_TICKET_3_10 = {
		id = "CURRENCY_TYPE_GENGCHEN_SCENE_TICKET_3_10",
		item_id = 53141,
		hide_number = 0
	},
	CURRENCY_SKULD_COIN_4_0 = {
		id = "CURRENCY_SKULD_COIN_4_0",
		item_id = 76,
		hide_number = 0
	},
	CURRENCY_PT_COIN_4_0 = {
		id = "CURRENCY_PT_COIN_4_0",
		item_id = 53161,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_4_0 = {
		id = "CURRENCY_PT_TICKET_4_0",
		item_id = 54118,
		hide_number = 0
	},
	CURRENCY_TYPE_FANTIAN_SKIN_COIN = {
		id = "CURRENCY_TYPE_FANTIAN_SKIN_COIN",
		item_id = 53158,
		hide_number = 0
	},
	CURRENCY_TYPE_FANTIAN_SKIN_TICKET = {
		id = "CURRENCY_TYPE_FANTIAN_SKIN_TICKET",
		item_id = 53156,
		hide_number = 0
	},
	CURRENCY_TYPE_FANTIAN_SCENE_TICKET = {
		id = "CURRENCY_TYPE_FANTIAN_SCENE_TICKET",
		item_id = 53157,
		hide_number = 0
	},
	CURRENCY_PUZZLE_III_COIN_4_1 = {
		id = "CURRENCY_PUZZLE_III_COIN_4_1",
		item_id = 53159,
		hide_number = 0
	},
	CURRENCY_PT_COIN_4_1 = {
		id = "CURRENCY_PT_COIN_4_1",
		item_id = 53163,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_4_1 = {
		id = "CURRENCY_PT_TICKET_4_1",
		item_id = 54120,
		hide_number = 0
	},
	CURRENCY_TYPE_SPECIAL_EXPLORE_TICKER_INSTANCE_NEW = {
		id = "CURRENCY_TYPE_SPECIAL_EXPLORE_TICKER_INSTANCE_NEW",
		item_id = 69,
		hide_number = 0
	},
	CURRENCY_TYPE_SPECIAL_EXPLORE_TICKER_TEMPLATE_NEW_1 = {
		id = "CURRENCY_TYPE_SPECIAL_EXPLORE_TICKER_TEMPLATE_NEW_1",
		item_id = 78,
		hide_number = 0
	},
	CURRENCY_TYPE_TUOTE_SKIN_COIN_4_03 = {
		id = "CURRENCY_TYPE_TUOTE_SKIN_COIN_4_03",
		item_id = 53183,
		hide_number = 0
	},
	CURRENCY_TYPE_TUOTE_SKIN_TICKET_4_03 = {
		id = "CURRENCY_TYPE_TUOTE_SKIN_TICKET_4_03",
		item_id = 53180,
		hide_number = 0
	},
	CURRENCY_TYPE_TUOTE_SCENE_TICKET_4_03 = {
		id = "CURRENCY_TYPE_TUOTE_SCENE_TICKET_4_03",
		item_id = 53181,
		hide_number = 0
	},
	CURRENCY_TYPE_TUOTE_SCENE_TICKET_2_4_03 = {
		id = "CURRENCY_TYPE_TUOTE_SCENE_TICKET_2_4_03",
		item_id = 53182,
		hide_number = 0
	},
	CURRENCY_PT_COIN_4_3 = {
		id = "CURRENCY_PT_COIN_4_3",
		item_id = 53184,
		hide_number = 0
	},
	CURRENCY_ASH_COIN_4_4 = {
		id = "CURRENCY_ASH_COIN_4_4",
		item_id = 79,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_4_3 = {
		id = "CURRENCY_PT_TICKET_4_3",
		item_id = 54121,
		hide_number = 0
	},
	CURRENCY_PT_COIN_4_4 = {
		id = "CURRENCY_PT_COIN_4_4",
		item_id = 53186,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_4_4 = {
		id = "CURRENCY_PT_TICKET_4_4",
		item_id = 54122,
		hide_number = 0
	},
	CURRENCY_AUTOCHESS_COIN_4_5 = {
		id = "CURRENCY_AUTOCHESS_COIN_4_5",
		item_id = 80,
		hide_number = 0
	},
	CURRENCY_TYPE_DORM_FRACTION_4_5 = {
		id = "CURRENCY_TYPE_DORM_FRACTION_4_5",
		item_id = 61,
		hide_number = 0
	},
	CURRENCY_TYPE_SKULD_SKIN_COIN = {
		id = "CURRENCY_TYPE_SKULD_SKIN_COIN",
		item_id = 53189,
		hide_number = 0
	},
	CURRENCY_TYPE_SKULD_SKIN_TICKET = {
		id = "CURRENCY_TYPE_SKULD_SKIN_TICKET",
		item_id = 53190,
		hide_number = 0
	},
	CURRENCY_TYPE_SKULD_SCENE_TICKET = {
		id = "CURRENCY_TYPE_SKULD_SCENE_TICKET",
		item_id = 53191,
		hide_number = 0
	},
	CURRENCY_PT_COIN_4_5 = {
		id = "CURRENCY_PT_COIN_4_5",
		item_id = 53192,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_4_5 = {
		id = "CURRENCY_PT_TICKET_4_5",
		item_id = 54123,
		hide_number = 0
	},
	CURRENCY_TYPE_PASS_PAID_COIN = {
		id = "CURRENCY_TYPE_PASS_PAID_COIN",
		item_id = 53193,
		hide_number = 0
	},
	CURRENCY_PUZZLE_III_COIN_4_6 = {
		id = "CURRENCY_PUZZLE_III_COIN_4_6",
		item_id = 53194,
		hide_number = 0
	},
	CURRENCY_PT_COIN_4_6 = {
		id = "CURRENCY_PT_COIN_4_6",
		item_id = 53195,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_4_6 = {
		id = "CURRENCY_PT_TICKET_4_6",
		item_id = 54124,
		hide_number = 0
	},
	CURRENCY_AUTO_CHESS_PACK_1 = {
		id = "CURRENCY_AUTO_CHESS_PACK_1",
		item_id = 82,
		hide_number = 0
	},
	CURRENCY_PT_COIN_4_7 = {
		id = "CURRENCY_PT_COIN_4_7",
		item_id = 53197,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_4_7 = {
		id = "CURRENCY_PT_TICKET_4_7",
		item_id = 54125,
		hide_number = 0
	},
	CURRENCY_TYPE_T0_DRAW_SKIN_TICKET_4_8 = {
		id = "CURRENCY_TYPE_T0_DRAW_SKIN_TICKET_4_8",
		item_id = 53198,
		hide_number = 0
	},
	CURRENCY_TYPE_T0_DRAW_SCENE_TICKET_4_8 = {
		id = "CURRENCY_TYPE_T0_DRAW_SCENE_TICKET_4_8",
		item_id = 53199,
		hide_number = 0
	},
	CURRENCY_TYPE_T0_DRAW_SKIN_COIN_4_8 = {
		id = "CURRENCY_TYPE_T0_DRAW_SKIN_COIN_4_8",
		item_id = 53200,
		hide_number = 0
	},
	CURRENCY_TYPE_WEDDING_DRAW_SKIN_TICKET_4_8 = {
		id = "CURRENCY_TYPE_WEDDING_DRAW_SKIN_TICKET_4_8",
		item_id = 53202,
		hide_number = 0
	},
	CURRENCY_TYPE_WEDDING_DRAW_SCENE_TICKET_4_8 = {
		id = "CURRENCY_TYPE_WEDDING_DRAW_SCENE_TICKET_4_8",
		item_id = 53203,
		hide_number = 0
	},
	CURRENCY_PT_COIN_4_8 = {
		id = "CURRENCY_PT_COIN_4_8",
		item_id = 53204,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_4_8 = {
		id = "CURRENCY_PT_TICKET_4_8",
		item_id = 54126,
		hide_number = 0
	},
	CURRENCY_TYPE_T0_DRAW_SKIN_TICKET_5_0 = {
		id = "CURRENCY_TYPE_T0_DRAW_SKIN_TICKET_5_0",
		item_id = 53208,
		hide_number = 0
	},
	CURRENCY_TYPE_T0_DRAW_SCENE_TICKET_5_0 = {
		id = "CURRENCY_TYPE_T0_DRAW_SCENE_TICKET_5_0",
		item_id = 53209,
		hide_number = 0
	},
	CURRENCY_TYPE_T0_DRAW_SKIN_COIN_5_0 = {
		id = "CURRENCY_TYPE_T0_DRAW_SKIN_COIN_5_0",
		item_id = 53210,
		hide_number = 0
	},
	CURRENCY_PT_COIN_5_0 = {
		id = "CURRENCY_PT_COIN_5_0",
		item_id = 53213,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_5_0 = {
		id = "CURRENCY_PT_TICKET_5_0",
		item_id = 54127,
		hide_number = 0
	},
	CURRENCY_PT_COIN_5_1 = {
		id = "CURRENCY_PT_COIN_5_1",
		item_id = 53214,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_5_1 = {
		id = "CURRENCY_PT_TICKET_5_1",
		item_id = 54128,
		hide_number = 0
	},
	CURRENCY_PUZZLE_III_COIN_5_1 = {
		id = "CURRENCY_PUZZLE_III_COIN_5_1",
		item_id = 53215,
		hide_number = 0
	},
	CURRENCY_TYPE_T0_DRAW_SKIN_TICKET_5_2 = {
		id = "CURRENCY_TYPE_T0_DRAW_SKIN_TICKET_5_2",
		item_id = 53216,
		hide_number = 0
	},
	CURRENCY_TYPE_T0_DRAW_SCENE_TICKET_5_2 = {
		id = "CURRENCY_TYPE_T0_DRAW_SCENE_TICKET_5_2",
		item_id = 53217,
		hide_number = 0
	},
	CURRENCY_TYPE_T0_DRAW_SKIN_COIN_5_2 = {
		id = "CURRENCY_TYPE_T0_DRAW_SKIN_COIN_5_2",
		item_id = 53218,
		hide_number = 0
	},
	CURRENCY_TYPE_WEDDING_DRAW_SKIN_TICKET_5_2 = {
		id = "CURRENCY_TYPE_WEDDING_DRAW_SKIN_TICKET_5_2",
		item_id = 53219,
		hide_number = 0
	},
	CURRENCY_TYPE_WEDDING_DRAW_SCENE_TICKET_5_2 = {
		id = "CURRENCY_TYPE_WEDDING_DRAW_SCENE_TICKET_5_2",
		item_id = 53220,
		hide_number = 0
	},
	CURRENCY_PT_COIN_5_2 = {
		id = "CURRENCY_PT_COIN_5_2",
		item_id = 53221,
		hide_number = 0
	},
	CURRENCY_PT_TICKET_5_2 = {
		id = "CURRENCY_PT_TICKET_5_2",
		item_id = 54129,
		hide_number = 0
	},
	all = {
		CURRENCY_TYPE_DIAMOND,
		CURRENCY_TYPE_GOLD,
		CURRENCY_TYPE_FRIENDSHIP_POINT,
		CURRENCY_TYPE_FATIGUE,
		CURRENCY_TYPE_TREASURE_TICKET,
		CURRENCY_TYPE_CHANGE_NAME_CARD,
		CURRENCY_TYPE_CLUB_MEDAL,
		CURRENCY_TYPE_CLUB_POPULARITY,
		CURRENCY_TYPE_INTELLIGENCE_POINT,
		CURRENCY_TYPE_MYSTICAL_DIAMOND,
		CURRENCY_TYPE_BATTLEPASS_POINT,
		CURRENCY_TYPE_USER_EXP,
		CURRENCY_TYPE_HERO_EXP,
		CURRENCY_TYPE_BATTLEPASS_EXP,
		CURRENCY_TYPE_INFO_BADGE_LOW,
		CURRENCY_TYPE_INFO_BADGE_MID,
		CURRENCY_TYPE_INFO_BADGE_TOP,
		CURRENCY_TYPE_RECALL_CHAPTER,
		CURRENCY_TYPE_TREASURE_TICKET_EQUIP,
		CURRENCY_TYPE_FIVE_STAR_EQUIP_RESOLVE,
		CURRENCY_TYPE_SIX_STAR_EQUIP_RESOLVE,
		CURRENCY_TYPE_DAILY_ACTIVITY_PT,
		CURRENCY_TYPE_NEW_ACTIVITY_PT,
		CURRENCY_TYPE_SKIN,
		CURRENCY_TYPE_MYTHIC,
		CURRENCY_TYPE_MATRIX_COIN,
		CURRENCY_TYPE_MATRIX_RING,
		CURRENCY_TYPE_MATRIX_CERTIFICATION,
		CURRENCY_TYPE_MATRIX_PT,
		CURRENCY_TYPE_RECHARGE_DIAMOND_IOS,
		CURRENCY_TYPE_RECHARGE_DIAMOND_NOT_IOS,
		CURRENCY_TYPE_RECHARGE_DIAMOND_FREE,
		CURRENCY_TYPE_ACHIEVEMENT_POINT,
		CURRENCY_TYPE_MATRIX_TERMINAL_EXP,
		CURRENCY_TYPE_WEEK_ACTIVITY_PT,
		CURRENCY_TYPE_DRAW,
		CURRENCY_TYPE_BOSS_CHALLENGE,
		CURRENCY_TYPE_TREASURE_TICKET_ACTIVITY,
		CURRENCY_TYPE_DORM_GOLD,
		CURRENCY_TYPE_CLUB_COIN_A,
		CURRENCY_TYPE_CLUB_COIN_B,
		CURRENCY_TYPE_BOSS_CHALLENGE_S,
		CURRENCY_TYPE_OSIRIS_INFINITY_COIN,
		CURRENCY_TYPE_HELLA_TALENT_TREE_COIN,
		CURRENCY_TYPE_HELLA_SHOP_COIN,
		CURRENCY_TYPE_SUMMER_FISHING_COIN,
		CURRENCY_TYPE_RETURN_COIN,
		CURRENCY_TYPE_SUMMER_SKIN_COIN,
		CURRENCY_TYPE_SUMMER_PT,
		CURRENCY_TYPE_BOSS_CHALLENGE_ADVANCE,
		CURRENCY_TYPE_CHAPTERIII_PT,
		CURRENCY_TYPE_ACTIVITY_RACE,
		CURRENCY_TYPE_CHAPTERIII_DOWN_PT,
		CURRENCY_TYPE_ACTIVITY_CLUB_BOSS_MAP_COIN,
		CURRENCY_TYPE_FINAL_MYTHIC,
		CURRENCY_TYPE_FACTORY_INFINITY_COIN,
		CURRENCY_TYPE_FACTORY_PT,
		CURRENCY_TYPE_FESTIVAL_MONSTER_PT,
		CURRENCY_TYPE_EMPTYDREAM_PT,
		CURRENCY_TYPE_PASS_SENIOR_COIN,
		CURRENCY_TYPE_PASS_LOWER_COIN,
		CURRENCY_TYPE_FESTIVAL_CANTEEN_COIN,
		CURRENCY_TYPE_TYR_COIN,
		CURRENCY_XUHENG_COIN,
		CURRENCY_XUHENG_TICKET,
		CURRENCY_XUHENG_CULTIVATE_COIN,
		CURRENCY_TYPE_NEW_RETURN_COIN,
		CURRENCY_TYPE_RECALLED_COIN,
		CURRENCY_TYPE_DRAW_FEEDBACK_COIN,
		CURRENCY_TYPE_UNLOCK_PROPS,
		CURRENCY_TYPE_SHIFTING_EXP,
		CURRENCY_TYPE_WEAPON_MODULE,
		CURRENCY_TYPE_POLYHEDRON_TERMINAL_EXP,
		CURRENCY_XUHENG_PT_COIN,
		CURRENCY_XUHENG_PT_TICKET,
		CURRENCY_XUHENG_LULIANG_CHAPTER_TICKET,
		CURRENCY_XUHENG_CULTIVATE_COIN_A,
		CURRENCY_TYPE_CHIP_COST,
		CURRENCY_LINKGAME_COST,
		CURRENCY_PUZZLE_FRAGMENT,
		CURRENCY_PUZZLE_COIN,
		CURRENCY_PUZZLE_III_COIN,
		CURRENCY_TYPE_PERIODICITY_EXPLORE_TICKER_INSTANCE,
		CURRENCY_TYPE_PERIODICITY_EXPLORE_TICKER_TEMPLATE_1,
		CURRENCY_TYPE_PERIODICITY_EXPLORE_TICKER_TEMPLATE_2,
		CURRENCY_TYPE_PERIODICITY_EXPLORE_TICKER_TEMPLATE_3,
		CURRENCY_TYPE_PERIODICITY_EXPLORE_TICKER_TEMPLATE_4,
		CURRENCY_TYPE_EXPLORE_EXP,
		CURRENCY_TYPE_EXPLORE_GOLD_1,
		CURRENCY_TYPE_EXPLORE_GOLD_2,
		CURRENCY_TYPE_EXPLORE_GOLD_3,
		CURRENCY_TYPE_ACTIVITY_WATER_ASSISTANCE,
		CURRENCY_TYPE_ACTIVITY_WATER_TOKENS,
		CURRENCY_XUHENG_PT_COIN_2_2,
		CURRENCY_XUHENG_PT_TICKET_2_2,
		CURRENCY_TYPE_FLIP_CARD_TICKET,
		CURRENCY_TYPE_ACTIVITY_SKADI_SEA_COIN,
		CURRENCY_TYPE_STRONGHOLD_EXP_1,
		CURRENCY_TYPE_STRONGHOLD_EXP_2,
		CURRENCY_TYPE_STRONGHOLD_EXP_3,
		CURRENCY_TYPE_GENGCHEN_SKIN_COIN,
		CURRENCY_TYPE_GENGCHEN_SKIN_TICKET,
		CURRENCY_TYPE_GENGCHEN_SCENE_TICKET,
		CURRENCY_PT_COIN_2_4_UP,
		CURRENCY_PT_COIN_2_4_DOWN,
		CURRENCY_PT_TICKET_2_4_UP,
		CURRENCY_PT_TICKET_2_4_DOWN,
		CURRENCY_TYPE_ACTIVITY_CLUB_BOSS_SP_MAP_COIN,
		CURRENCY_TYPE_ACTIVITY_CLUB_BOSS_SP_MAP_COIN_B,
		CURRENCY_TYPE_SKIN_RECHARGE,
		CURRENCY_TYPE_ACTIVITY_KAGUTSUCHI_COIN,
		CURRENCY_TYPE_ACTIVITY_KAGUTSUCHI_FATIGUE,
		CURRENCY_PT_COIN_2_7,
		CURRENCY_PT_TICKET_2_7,
		CURRENCY_TYPE_NEW_WARCHESS_MOVE,
		CURRENCY_PT_ROULETTE_COIN_2_6,
		CURRENCY_PT_ROULETTE_TICKET_2_6,
		CURRENCY_TYPE_ACCURATE_EXPLORE_TICKER_INSTANCE,
		CURRENCY_TYPE_ACCURATE_EXPLORE_TICKER_TEMPLATE_1,
		CURRENCY_PT_COIN_2_8,
		CURRENCY_PT_TICKET_2_8,
		CURRENCY_PT_COIN_2_9,
		CURRENCY_PT_TICKET_2_9,
		CURRENCY_TYPE_ACTIVITY_CLUB_BOSS_SP_MAP_COIN_2_8,
		CURRENCY_TYPE_ACTIVITY_CLUB_BOSS_SP_MAP_COIN_B_2_8,
		CURRENCY_NIAN_PT_2_9,
		CURRENCY_PT_COIN_2_10,
		CURRENCY_PT_TICKET_2_10,
		CURRENCY_TYPE_NEW_WARCHESS_MOVE_2_10,
		CURRENCY_PT_COIN_2_11,
		CURRENCY_PT_TICKET_2_11,
		CURRENCY_TYPE_CORE_COIN,
		CURRENCY_HERO_CHALLENGE_COIN_1,
		CURRENCY_HERO_CHALLENGE_COIN_2,
		CURRENCY_HERO_CHALLENGE_TICKET,
		CURRENCY_PT_COIN_3_0,
		CURRENCY_PT_TICKET_3_0,
		CURRENCY_PT_COIN_3_1,
		CURRENCY_PT_TICKET_3_1,
		CURRENCY_TYPE_ACCURATE_EXPLORE_PROOF,
		CURRENCY_TYPE_ACTIVITY_NEW_SERVER,
		CURRENCY_TYPE_ACCURATE_EXPLORE_TICKER_INSTANCE_NEW,
		CURRENCY_TYPE_PERIODICITY_EXPLORE_TICKER_TEMPLATE_NEW_1,
		CURRENCY_TYPE_PERIODICITY_EXPLORE_TICKER_TEMPLATE_NEW_2,
		CURRENCY_PT_COIN_3_2,
		CURRENCY_PT_TICKET_3_2,
		CURRENCY_TYPE_GENGCHEN_SKIN_COIN_3_2,
		CURRENCY_TYPE_GENGCHEN_SKIN_TICKET_3_2,
		CURRENCY_TYPE_GENGCHEN_SCENE_TICKET_3_2,
		CURRENCY_PT_COIN_3_4,
		CURRENCY_PT_TICKET_3_4,
		CURRENCY_ACTIVITY_SIM_BUSINESS_3_5,
		CURRENCY_PUZZLE_III_COIN_3_5,
		CURRENCY_PT_COIN_3_5,
		CURRENCY_PT_TICKET_3_5,
		CURRENCY_STRATEGYMATRIX_TICKET_3_5,
		CURRENCY_PT_COIN_3_6,
		CURRENCY_PT_TICKET_3_6,
		CURRENCY_SHOP_COIN,
		CURRENCY_CHIP,
		CURRENCY_ROGUE_TEAM_BATTLEPASS,
		CURRENCY_TYPE_TUOTE_SKIN_COIN,
		CURRENCY_TYPE_TUOTE_SKIN_TICKET,
		CURRENCY_TYPE_TUOTE_SCENE_TICKET,
		CURRENCY_TYPE_TUOTE_SCENE_TICKET_2,
		CURRENCY_PT_COIN_3_7,
		CURRENCY_PT_TICKET_3_7,
		ACTIVITY_GOD_EATER_HUB_EXP,
		CURRENCY_GOD_EATER_SHOP_COIN,
		CURRENCY_PT_COIN_4_2,
		CURRENCY_PT_TICKET_4_2,
		CURRENCY_PT_COIN_3_8,
		CURRENCY_PT_TICKET_3_8,
		CURRENCY_PT_COIN_3_9,
		CURRENCY_SPRING_SHOP_COIN_3_10,
		CURRENCY_PT_TICKET_3_9,
		CURRENCY_PT_COIN_3_10,
		CURRENCY_PT_TICKET_3_10,
		CURRENCY_TYPE_GENGCHEN_SKIN_COIN_3_10,
		CURRENCY_TYPE_GENGCHEN_SKIN_TICKET_3_10,
		CURRENCY_PT_COIN_3_11,
		CURRENCY_QUANZHOU_COIN_4_0,
		CURRENCY_PT_TICKET_3_11,
		CURRENCY_TYPE_GENGCHEN_SCENE_TICKET_3_10,
		CURRENCY_SKULD_COIN_4_0,
		CURRENCY_PT_COIN_4_0,
		CURRENCY_PT_TICKET_4_0,
		CURRENCY_TYPE_FANTIAN_SKIN_COIN,
		CURRENCY_TYPE_FANTIAN_SKIN_TICKET,
		CURRENCY_TYPE_FANTIAN_SCENE_TICKET,
		CURRENCY_PUZZLE_III_COIN_4_1,
		CURRENCY_PT_COIN_4_1,
		CURRENCY_PT_TICKET_4_1,
		CURRENCY_TYPE_SPECIAL_EXPLORE_TICKER_INSTANCE_NEW,
		CURRENCY_TYPE_SPECIAL_EXPLORE_TICKER_TEMPLATE_NEW_1,
		CURRENCY_TYPE_TUOTE_SKIN_COIN_4_03,
		CURRENCY_TYPE_TUOTE_SKIN_TICKET_4_03,
		CURRENCY_TYPE_TUOTE_SCENE_TICKET_4_03,
		CURRENCY_TYPE_TUOTE_SCENE_TICKET_2_4_03,
		CURRENCY_PT_COIN_4_3,
		CURRENCY_ASH_COIN_4_4,
		CURRENCY_PT_TICKET_4_3,
		CURRENCY_PT_COIN_4_4,
		CURRENCY_PT_TICKET_4_4,
		CURRENCY_AUTOCHESS_COIN_4_5,
		CURRENCY_TYPE_DORM_FRACTION_4_5,
		CURRENCY_TYPE_SKULD_SKIN_COIN,
		CURRENCY_TYPE_SKULD_SKIN_TICKET,
		CURRENCY_TYPE_SKULD_SCENE_TICKET,
		CURRENCY_PT_COIN_4_5,
		CURRENCY_PT_TICKET_4_5,
		CURRENCY_TYPE_PASS_PAID_COIN,
		CURRENCY_PUZZLE_III_COIN_4_6,
		CURRENCY_PT_COIN_4_6,
		CURRENCY_PT_TICKET_4_6,
		CURRENCY_AUTO_CHESS_PACK_1,
		CURRENCY_PT_COIN_4_7,
		CURRENCY_PT_TICKET_4_7,
		CURRENCY_TYPE_T0_DRAW_SKIN_TICKET_4_8,
		CURRENCY_TYPE_T0_DRAW_SCENE_TICKET_4_8,
		CURRENCY_TYPE_T0_DRAW_SKIN_COIN_4_8,
		CURRENCY_TYPE_WEDDING_DRAW_SKIN_TICKET_4_8,
		CURRENCY_TYPE_WEDDING_DRAW_SCENE_TICKET_4_8,
		CURRENCY_PT_COIN_4_8,
		CURRENCY_PT_TICKET_4_8,
		CURRENCY_TYPE_T0_DRAW_SKIN_TICKET_5_0,
		CURRENCY_TYPE_T0_DRAW_SCENE_TICKET_5_0,
		CURRENCY_TYPE_T0_DRAW_SKIN_COIN_5_0,
		CURRENCY_PT_COIN_5_0,
		CURRENCY_PT_TICKET_5_0,
		CURRENCY_PT_COIN_5_1,
		CURRENCY_PT_TICKET_5_1,
		CURRENCY_PUZZLE_III_COIN_5_1,
		CURRENCY_TYPE_T0_DRAW_SKIN_TICKET_5_2,
		CURRENCY_TYPE_T0_DRAW_SCENE_TICKET_5_2,
		CURRENCY_TYPE_T0_DRAW_SKIN_COIN_5_2,
		CURRENCY_TYPE_WEDDING_DRAW_SKIN_TICKET_5_2,
		CURRENCY_TYPE_WEDDING_DRAW_SCENE_TICKET_5_2,
		CURRENCY_PT_COIN_5_2,
		CURRENCY_PT_TICKET_5_2
	}
}
