local avg_110307Table = {
                [1] = {
                        id = 1,
                        type = 5,
                        title = "PlotSerious",
                        showCharacter = 1,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [2] = {
                        id = 2,
                        type = 4,
                        title = "scene_sea_cloudy2",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [3] = {
                        id = 3,
                        type = 10,
                        title = "Effect_UI_WuQi",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [4] = {
                        id = 4,
                        type = 1,
                        title = nil,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "？？？，海雾区域。",
                },

                [5] = {
                        id = 5,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = "Z16_生气",
                        content = "哈……哈……",
                },

                [6] = {
                        id = 6,
                        type = 1,
                        title = "弗莱彻",
                        showCharacter = 10016,
                        left = 10016,
                        center = nil,
                        right = 10019,
                        action = "弗莱彻_惊讶",
                        content = "你航行得太快了，Z16！不控制马力的话，在这种雾气中很容易走散的！",
                },

                [7] = {
                        id = 7,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = 10016,
                        center = nil,
                        right = 10019,
                        action = nil,
                        content = "不行……不行！",
                },

                [8] = {
                        id = 8,
                        type = 12,
                        title = 2,
                        showCharacter = 10019,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = 0.2,
                        content = 100,
                },

                [9] = {
                        id = 9,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = 10016,
                        center = nil,
                        right = 10019,
                        action = nil,
                        content = "好不容易等到了雾气变弱，如果不抓住机会的话——",
                },

                [10] = {
                        id = 10,
                        type = 12,
                        title = 3,
                        showCharacter = 10019,
                        left = 1,
                        center = nil,
                        right = nil,
                        action = 1.5,
                        content = 50,
                },

                [11] = {
                        id = 11,
                        type = 1,
                        title = "弗莱彻",
                        showCharacter = 10016,
                        left = nil,
                        center = 10016,
                        right = nil,
                        action = nil,
                        content = "等等，Z16，等等！",
                },

                [12] = {
                        id = 12,
                        type = 11,
                        title = "Effect_UI_WuQi",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [13] = {
                        id = 13,
                        type = 4,
                        title = "scene_black",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [14] = {
                        id = 14,
                        type = 22,
                        title = nil,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [15] = {
                        id = 15,
                        type = 4,
                        title = "scene_sea_cloudy2",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [16] = {
                        id = 16,
                        type = 10,
                        title = "Effect_UI_WuQi",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [17] = {
                        id = 17,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = "Z16_生气",
                        content = "哈……哈……",
                },

                [18] = {
                        id = 18,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "为什么……",
                },

                [19] = {
                        id = 19,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = "Z16_认真",
                        content = "明明雾气已经变弱了，明明已经全速前进了，为什么……为什么还是走不出去——",
                },

                [20] = {
                        id = 20,
                        type = 1,
                        title = "弗莱彻",
                        showCharacter = 10016,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "所——以——说——跑这么快的话，很容易走散的啊！",
                },

                [21] = {
                        id = 21,
                        type = 20,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "……",
                },

                [22] = {
                        id = 22,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "抱歉，弗莱彻，是我太着急了。",
                },

                [23] = {
                        id = 23,
                        type = 1,
                        title = "弗莱彻",
                        showCharacter = 10016,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "唉……真，真拿你没办法。",
                },

                [24] = {
                        id = 24,
                        type = 1,
                        title = "弗莱彻",
                        showCharacter = 10016,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "抓住我的手，这次可别再走丢——",
                },

                [25] = {
                        id = 25,
                        type = 16,
                        title = "boom1",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [26] = {
                        id = 26,
                        type = 6,
                        title = 30,
                        showCharacter = 1,
                        left = 1,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [27] = {
                        id = 27,
                        type = 1,
                        title = "弗莱彻？",
                        showCharacter = 10016,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "呀啊！你，你干什么——",
                },

                [28] = {
                        id = 28,
                        type = 16,
                        title = "boom1",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [29] = {
                        id = 29,
                        type = 6,
                        title = 30,
                        showCharacter = 1,
                        left = 1,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [30] = {
                        id = 30,
                        type = 1,
                        title = "弗莱彻？",
                        showCharacter = 10016,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "是我啊！你的同伴啊，你怎么——",
                },

                [31] = {
                        id = 31,
                        type = 16,
                        title = "boom1",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [32] = {
                        id = 32,
                        type = 6,
                        title = 30,
                        showCharacter = 1,
                        left = 1,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [33] = {
                        id = 33,
                        type = 1,
                        title = "弗莱彻？",
                        showCharacter = 10016,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "我知道了我知道了，我投降，我投降……",
                },

                [34] = {
                        id = 34,
                        type = 5,
                        title = "PlotNervous",
                        showCharacter = 1,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [35] = {
                        id = 35,
                        type = 1,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = "乌妮妮_生气",
                        content = "——才怪呢！区区驱逐舰的炮击，真以为能伤得了我吗！",
                },

                [36] = {
                        id = 36,
                        type = 27,
                        title = nil,
                        showCharacter = 0.01,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [37] = {
                        id = 37,
                        type = 16,
                        title = "boom2",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [38] = {
                        id = 38,
                        type = 6,
                        title = 30,
                        showCharacter = 2,
                        left = 1.5,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [39] = {
                        id = 39,
                        type = 20,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "唔！",
                },

                [40] = {
                        id = 40,
                        type = 1,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = nil,
                        content = "维……维纳斯大人都会夸我学别人说话很厉害，你到底是怎么发现的！",
                },

                [41] = {
                        id = 41,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "就算是在雾气之中，你的舰装也比弗莱彻大了整整一圈呢，看不出来才奇怪呢！",
                },

                [42] = {
                        id = 42,
                        type = 1,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = nil,
                        content = "啊是吗，真可惜。",
                },

                [43] = {
                        id = 43,
                        type = 6,
                        title = 10,
                        showCharacter = 0.5,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [44] = {
                        id = 44,
                        type = 1,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = nil,
                        content = "不过……不过，你已经被我逼入绝境的现实……并没有改变！",
                },

                [45] = {
                        id = 45,
                        type = 20,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "……",
                },

                [46] = {
                        id = 46,
                        type = 1,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = "乌妮妮_奸笑",
                        content = "真是愚蠢的小鬼……只要稍稍减弱雾气，就会自乱阵脚……",
                },

                [47] = {
                        id = 47,
                        type = 1,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = nil,
                        content = "你们这群假惺惺的家伙，……危急的时候亲密无间，互相舔舐伤口",
                },

                [48] = {
                        id = 48,
                        type = 1,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = nil,
                        content = "然而只要稍稍有一点点希望，你们就露出本性，各奔东西……",
                },

                [49] = {
                        id = 49,
                        type = 27,
                        title = nil,
                        showCharacter = 0.01,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [50] = {
                        id = 50,
                        type = 16,
                        title = "boom2",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [51] = {
                        id = 51,
                        type = 6,
                        title = 30,
                        showCharacter = 2,
                        left = 1.5,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [52] = {
                        id = 52,
                        type = 20,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "呜！",
                },

                [53] = {
                        id = 53,
                        type = 1,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = nil,
                        content = "哈哈！啊哈哈！这样才对嘛~",
                },

                [54] = {
                        id = 54,
                        type = 27,
                        title = nil,
                        showCharacter = 0.01,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [55] = {
                        id = 55,
                        type = 16,
                        title = "boom2",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [56] = {
                        id = 56,
                        type = 6,
                        title = 30,
                        showCharacter = 2,
                        left = 1.5,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [57] = {
                        id = 57,
                        type = 1,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = nil,
                        content = "再卖力闪躲呀！在……再，在多让我看看你们狼狈的样子呀！",
                },

                [58] = {
                        id = 58,
                        type = 1,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = nil,
                        content = "这段时间……吃尽了你们的苦，维纳斯大人也差点对我失望！",
                },

                [59] = {
                        id = 59,
                        type = 1,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = nil,
                        content = "我会好好地折磨你，让你好好尝尝我吃的苦头，你的同伴也是——",
                },

                [60] = {
                        id = 60,
                        type = 27,
                        title = nil,
                        showCharacter = 0.01,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [61] = {
                        id = 61,
                        type = 16,
                        title = "boom2",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [62] = {
                        id = 62,
                        type = 6,
                        title = 30,
                        showCharacter = 2,
                        left = 1.5,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [63] = {
                        id = 63,
                        type = 20,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "……",
                },

                [64] = {
                        id = 64,
                        type = 1,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = "乌妮妮_生气",
                        content = "怎么了？再多让我听听你……你的惨叫啊！",
                },

                [65] = {
                        id = 65,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = "Z16_严肃",
                        content = "……成……",
                },

                [66] = {
                        id = 66,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "成熟的大人，可不会因为这点小挫折就哭哭啼啼的。",
                },

                [67] = {
                        id = 67,
                        type = 1,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = nil,
                        content = "成熟的大人……哈！",
                },

                [68] = {
                        id = 68,
                        type = 1,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = nil,
                        content = "哪……哪有成熟的大人像，像你这样！",
                },

                [69] = {
                        id = 69,
                        type = 6,
                        title = 10,
                        showCharacter = 0.5,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [70] = {
                        id = 70,
                        type = 1,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = nil,
                        content = "伤痕累累，邋邋遢遢，还一身的臭味！",
                },

                [71] = {
                        id = 71,
                        type = 20,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = "Z16_认真",
                        content = "……",
                },

                [72] = {
                        id = 72,
                        type = 27,
                        title = nil,
                        showCharacter = 0.01,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [73] = {
                        id = 73,
                        type = 16,
                        title = "boom2",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [74] = {
                        id = 74,
                        type = 6,
                        title = 30,
                        showCharacter = 2,
                        left = 1.5,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [75] = {
                        id = 75,
                        type = 20,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "……",
                },

                [76] = {
                        id = 76,
                        type = 1,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = nil,
                        content = "怎么不说话了……无话可说了是吗！",
                },

                [77] = {
                        id = 77,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "成熟的大人……不会在必要的时候多嘴。",
                },

                [78] = {
                        id = 78,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "我刚才回答你是为了拖延时间，现在……",
                },

                [79] = {
                        id = 79,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "不需要了！",
                },

                [80] = {
                        id = 80,
                        type = 20,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = nil,
                        content = "！",
                },

                [81] = {
                        id = 81,
                        type = 16,
                        title = "splash",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [82] = {
                        id = 82,
                        type = 6,
                        title = 30,
                        showCharacter = 2,
                        left = 1,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [83] = {
                        id = 83,
                        type = 1,
                        title = "弗莱彻",
                        showCharacter = 10016,
                        left = nil,
                        center = 10016,
                        right = nil,
                        action = "弗莱彻_严肃",
                        content = "太好了！命中了！",
                },

                [84] = {
                        id = 84,
                        type = 23,
                        title = "Z16",
                        showCharacter = 10019,
                        left = 10016,
                        center = nil,
                        right = 10019,
                        action = "Z16_自信",
                        content = "弗莱彻！",
                },

                [85] = {
                        id = 85,
                        type = 23,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = nil,
                        content = "你、你们——！",
                },

                [86] = {
                        id = 86,
                        type = 23,
                        title = "弗莱彻",
                        showCharacter = 10016,
                        left = 10016,
                        center = nil,
                        right = 10019,
                        action = nil,
                        content = "这是最后的鱼雷了！要是砸不中可就真的难办了！",
                },

                [87] = {
                        id = 87,
                        type = 23,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = nil,
                        content = "为什么……",
                },

                [88] = {
                        id = 88,
                        type = 6,
                        title = 10,
                        showCharacter = 0.5,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [89] = {
                        id = 89,
                        type = 23,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = nil,
                        content = "明明……明明你们才是被欺负的一方……为什么……为什么！你们就不肯乖乖地让我欺负呢！",
                },

                [90] = {
                        id = 90,
                        type = 23,
                        title = "弗莱彻",
                        showCharacter = 10016,
                        left = 10016,
                        center = nil,
                        right = 10019,
                        action = nil,
                        content = "因为我们不傻！你这个蠢深海！",
                },

                [91] = {
                        id = 91,
                        type = 23,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = nil,
                        content = "你——！",
                },

                [92] = {
                        id = 92,
                        type = 23,
                        title = "Z16",
                        showCharacter = 10019,
                        left = 10016,
                        center = nil,
                        right = 10019,
                        action = "Z16_严肃",
                        content = "弗莱彻，指挥官他们——",
                },

                [93] = {
                        id = 93,
                        type = 12,
                        title = 1,
                        showCharacter = 10016,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = 0.2,
                        content = -100,
                },

                [94] = {
                        id = 94,
                        type = 23,
                        title = "弗莱彻",
                        showCharacter = 10016,
                        left = 10016,
                        center = nil,
                        right = 10019,
                        action = nil,
                        content = "正在往这边赶！",
                },

                [95] = {
                        id = 95,
                        type = 23,
                        title = "Z16",
                        showCharacter = 10019,
                        left = 10016,
                        center = nil,
                        right = 10019,
                        action = nil,
                        content = "这家伙不是一般的深海，就算合我们两个的力量，也未必……",
                },

                [96] = {
                        id = 96,
                        type = 23,
                        title = "弗莱彻",
                        showCharacter = 10016,
                        left = 10016,
                        center = nil,
                        right = 10019,
                        action = nil,
                        content = "但是，只要能拖住她就算胜利，不是吗？",
                },

                [97] = {
                        id = 97,
                        type = 20,
                        title = "Z16",
                        showCharacter = 10019,
                        left = 10016,
                        center = nil,
                        right = 10019,
                        action = "Z16_自信",
                        content = "嗯！",
                },

                [98] = {
                        id = 98,
                        type = 23,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = nil,
                        content = "你们……你们——",
                },

                [99] = {
                        id = 99,
                        type = 6,
                        title = 10,
                        showCharacter = 0.5,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                },

                [100] = {
                        id = 100,
                        type = 23,
                        title = "乌妮妮",
                        showCharacter = 10018,
                        left = nil,
                        center = 10018,
                        right = nil,
                        action = nil,
                        content = "别小看我！！！",
                },

}
return avg_110307Table