local avg_151001901Table = {
                [1] = {
                        id = 1,
                        type = 5,
                        title = "PlotNormal",
                        showCharacter = 1,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [2] = {
                        id = 2,
                        type = 4,
                        title = "scene_office",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [3] = {
                        id = 3,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = "Z16_默认",
                        content = "早上好，指挥官！",
                        voice = 119050,
                },

                [4] = {
                        id = 4,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "哎呀……？今天很早嘛，芙蕾德莉卡。",
                        voice = nil,
                },

                [5] = {
                        id = 5,
                        type = 12,
                        title = 1,
                        showCharacter = 10019,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = 0.2,
                        content = -100,
                        voice = nil,
                },

                [6] = {
                        id = 6,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "今天这样的日子，当然要展现健全的精气神！",
                        voice = nil,
                },

                [7] = {
                        id = 7,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "不错不错，话说你胸前那个是……“一日指挥官”——",
                        voice = nil,
                },

                [8] = {
                        id = 8,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = "Z16_笑",
                        content = "嘿嘿，这是我专门为今天做的绶带！戴上它，感觉自己真的像个指挥官了呢！",
                        voice = 119037,
                },

                [9] = {
                        id = 9,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "虽然只是短短的一天，但还请指挥官多多指导、鞭策！",
                        voice = nil,
                },

                [10] = {
                        id = 10,
                        type = 4,
                        title = "scene_black",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [11] = {
                        id = 11,
                        type = 9,
                        title = nil,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "一日指挥官制度——这是由艾塔提议试推行的一项制度。",
                        voice = nil,
                },

                [12] = {
                        id = 12,
                        type = 14,
                        title = 0.1,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [13] = {
                        id = 13,
                        type = 9,
                        title = nil,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "让在前线作战的战舰少女，",
                        voice = nil,
                },

                [14] = {
                        id = 14,
                        type = 9,
                        title = nil,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "通过体验指挥官的工作，培养站在指挥官角度思考问题的习惯，",
                        voice = nil,
                },

                [15] = {
                        id = 15,
                        type = 9,
                        title = nil,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "从而加强战斗中与指挥官的配合，以及对战场形势的正确把握。",
                        voice = nil,
                },

                [16] = {
                        id = 16,
                        type = 14,
                        title = 0.1,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [17] = {
                        id = 17,
                        type = 9,
                        title = nil,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "第一次选择的对象就是芙蕾德莉卡。",
                        voice = nil,
                },

                [18] = {
                        id = 18,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = "Z16_自信",
                        content = "多么光荣的任务……！如果能完美达成，那大家都会认可我的成熟魅力了吧！这可是好机会啊！",
                        voice = nil,
                },

                [19] = {
                        id = 19,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "（活泼可爱，而且率直又好学的她，确实是最佳人选。）",
                        voice = nil,
                },

                [20] = {
                        id = 20,
                        type = 4,
                        title = "scene_office",
                        showCharacter = 0.2,
                        left = nil,
                        center = 1,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [21] = {
                        id = 21,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = "Z16_害羞",
                        content = "……指挥官，您怎么一直盯着我笑？难道说，早上吃的面包渣还留在嘴边……！？",
                        voice = 119036,
                },

                [22] = {
                        id = 22,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "没有，我只是想起高兴的事。",
                        voice = nil,
                },

                [23] = {
                        id = 23,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "那么，今天就由不才担任芙蕾德莉卡指挥官的秘书。有什么需要请尽管吩咐。",
                        voice = nil,
                },

                [24] = {
                        id = 24,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = "Z16_笑",
                        content = "喔喔，指挥官当我的秘书，多么奢侈啊！",
                        voice = nil,
                },

                [25] = {
                        id = 25,
                        type = 12,
                        title = 1,
                        showCharacter = 10019,
                        left = nil,
                        center = 2,
                        right = nil,
                        action = 0.2,
                        content = -100,
                        voice = nil,
                },

                [26] = {
                        id = 26,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "咳咳……秘书啊，今天的首要之事为何？",
                        voice = nil,
                },

                [27] = {
                        id = 27,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "那当然是……",
                        voice = nil,
                },

                [28] = {
                        id = 28,
                        type = 16,
                        title = "putCup",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [29] = {
                        id = 29,
                        type = 14,
                        title = 1,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [30] = {
                        id = 30,
                        type = 20,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "（……好香的味道！）",
                        voice = nil,
                },

                [31] = {
                        id = 31,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "请您品尝这杯提神醒脑、香醇四溢的奶茶了。",
                        voice = nil,
                },

                [32] = {
                        id = 32,
                        type = 12,
                        title = 1,
                        showCharacter = 10019,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = 0.2,
                        content = 100,
                        voice = nil,
                },

                [33] = {
                        id = 33,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "哇啊，是焦糖奶茶，我最喜欢焦糖奶茶了！",
                        voice = 119040,
                },

                [34] = {
                        id = 34,
                        type = 5,
                        title = nil,
                        showCharacter = 1,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [35] = {
                        id = 35,
                        type = 14,
                        title = 1,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [36] = {
                        id = 36,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = "Z16_赌气",
                        content = "……等一下，指挥官，您另一只手里拿的是什么？",
                        voice = 119036,
                },

                [37] = {
                        id = 37,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "这个吗？只是普通的黑咖啡而已。",
                        voice = nil,
                },

                [38] = {
                        id = 38,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "黑咖啡……指挥官，您平时都喝黑咖啡的吗？",
                        voice = nil,
                },

                [39] = {
                        id = 39,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "嗯，是这样没错？",
                        voice = nil,
                },

                [40] = {
                        id = 40,
                        type = 12,
                        title = 1,
                        showCharacter = 10019,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = 0.2,
                        content = 100,
                        voice = nil,
                },

                [41] = {
                        id = 41,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "……那么，我也要喝黑咖啡！",
                        voice = nil,
                },

                [42] = {
                        id = 42,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "还是不要吧，黑咖啡很苦的。",
                        voice = nil,
                },

                [43] = {
                        id = 43,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "确实，书上也是这么说的……不过，如果只是青椒的程度，咬咬牙的话……",
                        voice = nil,
                },

                [44] = {
                        id = 44,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "比青椒要苦喔。",
                        voice = nil,
                },

                [45] = {
                        id = 45,
                        type = 5,
                        title = "PlotFunny",
                        showCharacter = 1,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [46] = {
                        id = 46,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = "Z16_惊讶",
                        content = "真、真的假的……",
                        voice = 119043,
                },

                [47] = {
                        id = 47,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "顺带一提，苦瓜跟它比起来，完全就是杂鱼。",
                        voice = nil,
                },

                [48] = {
                        id = 48,
                        type = 6,
                        title = 5,
                        showCharacter = 0.5,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [49] = {
                        id = 49,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = "Z16_害怕",
                        content = "连那个苦瓜也……！？糟了，完全是预料之外……",
                        voice = 119056,
                },

                [50] = {
                        id = 50,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "……正因为跨越了这份苦难，才能成为指挥官吗……",
                        voice = nil,
                },

                [51] = {
                        id = 51,
                        type = 1,
                        title = nil,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "芙蕾德莉卡站了起来，看了看胸前的绶带，这使她充满了决心。",
                        voice = nil,
                },

                [52] = {
                        id = 52,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = "Z16_生气",
                        content = "这是一场试炼！一场为了战胜过去的试炼！只有战胜了那些幼稚的过去，人才能有所成长！",
                        voice = 119038,
                },

                [53] = {
                        id = 53,
                        type = 6,
                        title = 10,
                        showCharacter = 0.5,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [54] = {
                        id = 54,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "能喝下黑咖啡的人，才有资格佩戴这神授的绶带啊！",
                        voice = nil,
                },

                [55] = {
                        id = 55,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "（这绶带不是你自制的吗？）",
                        voice = nil,
                },

                [56] = {
                        id = 56,
                        type = 12,
                        title = 1,
                        showCharacter = 10019,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = 0.2,
                        content = 100,
                        voice = nil,
                },

                [57] = {
                        id = 57,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "指挥官，我……想喝黑咖啡……！",
                        voice = nil,
                },

                [58] = {
                        id = 58,
                        type = 1,
                        title = nil,
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "拗不过芙蕾德莉卡，我只好将黑咖啡递了过去。她小心翼翼接过，轻轻啜了一口。",
                        voice = nil,
                },

                [59] = {
                        id = 59,
                        type = 6,
                        title = 10,
                        showCharacter = 0.5,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [60] = {
                        id = 60,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = "Z16_害怕",
                        content = "<size=40>啊~~~~~~</size>",
                        voice = nil,
                },

                [61] = {
                        id = 61,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "咕，成为成熟大人的路途是多么险峻啊……！",
                        voice = 119044,
                },

                [62] = {
                        id = 62,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "（哎呀呀……）",
                        voice = nil,
                },

                [63] = {
                        id = 63,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "芙蕾德莉卡，你知道吗？奶茶在16世纪的皇室贵族之间，其实是颇为流行的。",
                        voice = nil,
                },

                [64] = {
                        id = 64,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = "Z16_惊讶",
                        content = "诶？啊，嗯……？",
                        voice = 119036,
                },

                [65] = {
                        id = 65,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "也就是说，那些皇室贵族的淑女们，也是会喝奶茶的。",
                        voice = nil,
                },

                [66] = {
                        id = 66,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "是这个道理……？",
                        voice = nil,
                },

                [67] = {
                        id = 67,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "看来，你还没意识到这代表着什么啊。",
                        voice = nil,
                },

                [68] = {
                        id = 68,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "诶？{Pause=0.3}——啊。",
                        voice = nil,
                },

                [69] = {
                        id = 69,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "不错，奶茶才是优雅的代名词，成熟大人的标志啊！",
                        voice = nil,
                },

                [70] = {
                        id = 70,
                        type = 6,
                        title = 5,
                        showCharacter = 0.5,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [71] = {
                        id = 71,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "真是盲点啊——！",
                        voice = 119062,
                },

                [72] = {
                        id = 72,
                        type = 12,
                        title = 1,
                        showCharacter = 10019,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = 0.5,
                        content = -100,
                        voice = nil,
                },

                [73] = {
                        id = 73,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "的确，胡德姐姐的茶会上，也经常出现用红茶冲泡的奶茶……",
                        voice = nil,
                },

                [74] = {
                        id = 74,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "黑咖啡诚然不错，但只要有静品奶茶的风度，也能彰显成熟大人的品位与格调。",
                        voice = nil,
                },

                [75] = {
                        id = 75,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "“称霸奶茶之人就能称霸世界”。能够达成这项伟业的淑女，被世人称颂为——",
                        voice = nil,
                },

                [76] = {
                        id = 76,
                        type = 6,
                        title = 10,
                        showCharacter = 0.5,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [77] = {
                        id = 77,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "<ruby=Elegante Dame>高雅的贵妇人</ruby>！",
                        voice = nil,
                },

                [78] = {
                        id = 78,
                        type = 6,
                        title = 10,
                        showCharacter = 0.5,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [79] = {
                        id = 79,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = "Z16_害羞",
                        content = "<ruby=Mein Gott>天哪</ruby>！",
                        voice = 119056,
                },

                [80] = {
                        id = 80,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "哎呀，到巡视港区的时间了呢。怎么办？要眼睁睁放弃成为成熟大人的机会吗！",
                        voice = nil,
                },

                [81] = {
                        id = 81,
                        type = 12,
                        title = 1,
                        showCharacter = 10019,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = 0.2,
                        content = 100,
                        voice = nil,
                },

                [82] = {
                        id = 82,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "那不行！",
                        voice = nil,
                },

                [83] = {
                        id = 83,
                        type = 16,
                        title = "drinking1",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [84] = {
                        id = 84,
                        type = 12,
                        title = 2,
                        showCharacter = 10019,
                        left = nil,
                        center = 3,
                        right = nil,
                        action = nil,
                        content = 50,
                        voice = nil,
                },

                [85] = {
                        id = 85,
                        type = 1,
                        title = nil,
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "咕嘟咕嘟——",
                        voice = nil,
                },

                [86] = {
                        id = 86,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = "Z16_笑",
                        content = "<size=40>美味！</size>",
                        voice = 119041,
                },

                [87] = {
                        id = 87,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "这样一来，我的迷人气质就……",
                        voice = nil,
                },

                [88] = {
                        id = 88,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "是啊，现在的芙蕾德莉卡，比以往任何时候更加美丽动人喔。",
                        voice = nil,
                },

                [89] = {
                        id = 89,
                        type = 12,
                        title = 1,
                        showCharacter = 10019,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = 0.2,
                        content = -100,
                        voice = nil,
                },

                [90] = {
                        id = 90,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "嘿嘿！这样子去巡视港区的话，大家都会察觉到我成熟的魅力了！",
                        voice = 119070,
                },

                [91] = {
                        id = 91,
                        type = 1,
                        title = "Z16",
                        showCharacter = 10019,
                        left = nil,
                        center = 10019,
                        right = nil,
                        action = nil,
                        content = "我们快出发吧，指挥官！",
                        voice = nil,
                },

                [92] = {
                        id = 92,
                        type = 4,
                        title = "scene_coco",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [93] = {
                        id = 93,
                        type = 1,
                        title = nil,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "在那之后，芙蕾德莉卡认真尽责地完成了港区巡视，水雷训练指导，安全宣传，与居民互动等日常项目。",
                        voice = nil,
                },

                [94] = {
                        id = 94,
                        type = 1,
                        title = nil,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "“今天真是学到了很多！这都是奶茶的功劳！”这样笑着的她，想必将来能成为一个受人尊敬的大人吧。",
                        voice = nil,
                },

}
return avg_151001901Table