local avg_151003202Table = {
                [1] = {
                        id = 1,
                        type = 5,
                        title = "PlotNormal",
                        showCharacter = 1,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [2] = {
                        id = 2,
                        type = 4,
                        title = "scene_headquarters",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [3] = {
                        id = 3,
                        type = 16,
                        title = "door",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [4] = {
                        id = 4,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "唉……",
                        voice = nil,
                },

                [5] = {
                        id = 5,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "……不行，不能再叹气了。这才刚到下午，调整完大家的巡逻安排，还有巡视工作，晚上还有要签发收尾文件。",
                        voice = nil,
                },

                [6] = {
                        id = 6,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "……",
                        voice = nil,
                },

                [7] = {
                        id = 7,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "还是先喝杯咖啡提提神吧。",
                        voice = nil,
                },

                [8] = {
                        id = 8,
                        type = 16,
                        title = "coffee",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [9] = {
                        id = 9,
                        type = 14,
                        title = 2,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [10] = {
                        id = 10,
                        type = 6,
                        title = 10,
                        showCharacter = 0.5,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [11] = {
                        id = 11,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "咕嘟咕嘟——哈！很好，趁现在意识清醒，多做点事。",
                        voice = nil,
                },

                [12] = {
                        id = 12,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "嗯……先看看最近一周海上的天气数据吧。",
                        voice = nil,
                },

                [13] = {
                        id = 13,
                        type = 5,
                        title = nil,
                        showCharacter = 1,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [14] = {
                        id = 14,
                        type = 16,
                        title = "chest",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [15] = {
                        id = 15,
                        type = 14,
                        title = 1,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [16] = {
                        id = 16,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "……嗯？云层图标在眨眼睛？",
                        voice = nil,
                },

                [17] = {
                        id = 17,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "我眼花了吗？",
                        voice = nil,
                },

                [18] = {
                        id = 18,
                        type = 16,
                        title = "chest",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [19] = {
                        id = 19,
                        type = 14,
                        title = 1,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [20] = {
                        id = 20,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "气象标识怎么都变成卡通画了？再调用一下作战记录模块——",
                        voice = nil,
                },

                [21] = {
                        id = 21,
                        type = 16,
                        title = "chest",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [22] = {
                        id = 22,
                        type = 6,
                        title = 10,
                        showCharacter = 0.5,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [23] = {
                        id = 23,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "呜啊！？",
                        voice = nil,
                },

                [24] = {
                        id = 24,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "好晃眼！怎么全是彩色色块啊！？",
                        voice = nil,
                },

                [25] = {
                        id = 25,
                        type = 5,
                        title = "PlotSerious",
                        showCharacter = 1,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [26] = {
                        id = 26,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "海图……海图可别再出问题……",
                        voice = nil,
                },

                [27] = {
                        id = 27,
                        type = 6,
                        title = 10,
                        showCharacter = 0.5,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [28] = {
                        id = 28,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "全变成简笔画了啊！",
                        voice = nil,
                },

                [29] = {
                        id = 29,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "这到底怎么回事？后台程序出错了吗？",
                        voice = nil,
                },

                [30] = {
                        id = 30,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "程序还在正常运行……看来需要好好排查一下——",
                        voice = nil,
                },

                [31] = {
                        id = 31,
                        type = 4,
                        title = "scene_black",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [32] = {
                        id = 32,
                        type = 4,
                        title = "scene_headquarters",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [33] = {
                        id = 33,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "……不行，报错信息实在太多了。",
                        voice = nil,
                },

                [34] = {
                        id = 34,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "数据没有丢失，但内部系统全被替换更新……比起BUG，更像是外部骇客入侵的结果……还是说，系统被外部人员监控后台了？",
                        voice = nil,
                },

                [35] = {
                        id = 35,
                        type = 16,
                        title = "beep",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [36] = {
                        id = 36,
                        type = 14,
                        title = 1,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [37] = {
                        id = 37,
                        type = 13,
                        title = "克利俄",
                        showCharacter = 20000,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = "idle_talk",
                        content = "有什么事吗，指挥官？",
                        voice = nil,
                },

                [38] = {
                        id = 38,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "克利俄，麻烦立刻到作战中心来！这里出问题了！",
                        voice = nil,
                },

                [39] = {
                        id = 39,
                        type = 13,
                        title = "克利俄",
                        showCharacter = 20000,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = "amazed_talk",
                        content = "……嗯？",
                        voice = 200001,
                },

                [40] = {
                        id = 40,
                        type = 4,
                        title = "scene_black",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [41] = {
                        id = 41,
                        type = 4,
                        title = "scene_headquarters",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [42] = {
                        id = 42,
                        type = 1,
                        title = "克利俄",
                        showCharacter = 20000,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = "克利俄_默认",
                        content = "——排查完毕。",
                        voice = nil,
                },

                [43] = {
                        id = 43,
                        type = 5,
                        title = nil,
                        showCharacter = 1,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [44] = {
                        id = 44,
                        type = 1,
                        title = "克利俄",
                        showCharacter = 20000,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = nil,
                        content = "指挥官请放心，系统没有被外部骇入、植入病毒或远程监控等迹象，应该是内部人员乱操作导致根源代码出了问题。",
                        voice = nil,
                },

                [45] = {
                        id = 45,
                        type = 1,
                        title = "克利俄",
                        showCharacter = 20000,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = nil,
                        content = "修复难度并不大，只是需要多花一点时间。",
                        voice = 200004,
                },

                [46] = {
                        id = 46,
                        type = 5,
                        title = "PlotNormal",
                        showCharacter = 1,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [47] = {
                        id = 47,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = nil,
                        content = "虚惊一场啊……那就拜托你了，克利俄。",
                        voice = nil,
                },

                [48] = {
                        id = 48,
                        type = 1,
                        title = "克利俄",
                        showCharacter = 20000,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = "克利俄_闭眼",
                        content = "嗯，我会争取在三个小时后的演习巡视工作开展前修复完成。",
                        voice = nil,
                },

                [49] = {
                        id = 49,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = nil,
                        content = "……",
                        voice = nil,
                },

                [50] = {
                        id = 50,
                        type = 1,
                        title = "克利俄",
                        showCharacter = 20000,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = nil,
                        content = "另外还有——",
                        voice = nil,
                },

                [51] = {
                        id = 51,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = nil,
                        content = "……还有其他工作吗？",
                        voice = nil,
                },

                [52] = {
                        id = 52,
                        type = 1,
                        title = "克利俄",
                        showCharacter = 20000,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = "克利俄_悲伤",
                        content = "……您不要紧张。只是有些事情想要向您汇报。",
                        voice = 200020,
                },

                [53] = {
                        id = 53,
                        type = 1,
                        title = "克利俄",
                        showCharacter = 20000,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = nil,
                        content = "根据指挥官刚才的描述，您没有调整系统就出现了这么多问题，这情况和我、艾塔遇到的事有些相似。",
                        voice = nil,
                },

                [54] = {
                        id = 54,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = nil,
                        content = "发生什么事了？",
                        voice = nil,
                },

                [55] = {
                        id = 55,
                        type = 1,
                        title = "克利俄",
                        showCharacter = 20000,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = "克利俄_惊讶",
                        content = "艾塔说，昨天她刚在指挥室整理过文件，但是今早发现顺序全被打乱了。",
                        voice = nil,
                },

                [56] = {
                        id = 56,
                        type = 1,
                        title = "克利俄",
                        showCharacter = 20000,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = nil,
                        content = "而我这边，我看到您的日程安排——从上午批阅文件到下午调整巡逻安排和巡视演习，再到晚上签发文件，近一周满满当当的工作全被改成了“休息”。",
                        voice = nil,
                },

                [57] = {
                        id = 57,
                        type = 1,
                        title = "克利俄",
                        showCharacter = 20000,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = nil,
                        content = "我们原本以为是您被工作逼得想要逃出港区度假才会这样做——",
                        voice = nil,
                },

                [58] = {
                        id = 58,
                        type = 6,
                        title = 10,
                        showCharacter = 0.5,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [59] = {
                        id = 59,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = nil,
                        content = "（……可以的话我真的想享受那么长的假期啊！）",
                        voice = nil,
                },

                [60] = {
                        id = 60,
                        type = 1,
                        title = "克利俄",
                        showCharacter = 20000,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = nil,
                        content = "这些都是跟您工作相关的事，现在看来，应该是别人做的？",
                        voice = 200002,
                },

                [61] = {
                        id = 61,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = nil,
                        content = "咳，确实是这样。我平时都会好好按艾塔的整理顺序排列文件，也不会乱动日程表。",
                        voice = nil,
                },

                [62] = {
                        id = 62,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = nil,
                        content = "不过这到底是谁做的呢……看来有必要调查一下。",
                        voice = nil,
                },

                [63] = {
                        id = 63,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = nil,
                        content = "克利俄，我先出去一会儿，这里就交给你了。",
                        voice = nil,
                },

                [64] = {
                        id = 64,
                        type = 1,
                        title = "克利俄",
                        showCharacter = 20000,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = "克利俄_闭眼",
                        content = "……好的。",
                        voice = nil,
                },

                [65] = {
                        id = 65,
                        type = 1,
                        title = "克利俄",
                        showCharacter = 20000,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = nil,
                        content = "不过特别提醒您一句还是请优先休息，您的皮质醇水平已经连续数小时处于高位，不趁这个空档休息可能会加剧疲劳累积。",
                        voice = 200018,
                },

                [66] = {
                        id = 66,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 20000,
                        right = nil,
                        action = nil,
                        content = "呃，我争取……",
                        voice = nil,
                },

                [67] = {
                        id = 67,
                        type = 16,
                        title = "door",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [68] = {
                        id = 68,
                        type = 4,
                        title = "scene_corridor",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [69] = {
                        id = 69,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "……被克利俄一提醒，感觉疲劳又涌上来了。",
                        voice = nil,
                },

                [70] = {
                        id = 70,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "总之先要去一趟指挥室调取出入记录……",
                        voice = nil,
                },

                [71] = {
                        id = 71,
                        type = 5,
                        title = nil,
                        showCharacter = 1,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [72] = {
                        id = 72,
                        type = 6,
                        title = 5,
                        showCharacter = 0.5,
                        left = 1,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [73] = {
                        id = 73,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "好累……腿快没力气了，真不想走路。",
                        voice = nil,
                },

                [74] = {
                        id = 74,
                        type = 16,
                        title = "recovery",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [75] = {
                        id = 75,
                        type = 1,
                        title = "？？？",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "那我来帮您吧！沙哇哇~嘿！",
                        voice = 132057,
                },

                [76] = {
                        id = 76,
                        type = 5,
                        title = "PlotFunny",
                        showCharacter = 1,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [77] = {
                        id = 77,
                        type = 6,
                        title = 10,
                        showCharacter = 0.5,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [78] = {
                        id = 78,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "这声音是——哇啊！？",
                        voice = nil,
                },

                [79] = {
                        id = 79,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "怎么回事！？我怎么飘起来了——",
                        voice = nil,
                },

                [80] = {
                        id = 80,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "脚底下好像有什么东西，可恶，甩不开！？",
                        voice = nil,
                },

                [81] = {
                        id = 81,
                        type = 1,
                        title = "萤火虫的声音",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "哈哈！指挥官~飞起来是不是快多啦？",
                        voice = 132043,
                },

                [82] = {
                        id = 82,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "果然是你吗，萤火虫！",
                        voice = nil,
                },

                [83] = {
                        id = 83,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "速度太快了，先停、停一下！",
                        voice = nil,
                },

                [84] = {
                        id = 84,
                        type = 1,
                        title = "萤火虫的声音",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "诶？那好吧——魔法解除！",
                        voice = nil,
                },

                [85] = {
                        id = 85,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "！？",
                        voice = nil,
                },

                [86] = {
                        id = 86,
                        type = 16,
                        title = "crash",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [87] = {
                        id = 87,
                        type = 6,
                        title = 20,
                        showCharacter = 1,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [88] = {
                        id = 88,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "疼疼疼……",
                        voice = nil,
                },

                [89] = {
                        id = 89,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = "萤火虫_害怕2",
                        content = "呜啊……指挥官您没事吧！？",
                        voice = 132052,
                },

                [90] = {
                        id = 90,
                        type = 12,
                        title = 4,
                        showCharacter = 10032,
                        left = nil,
                        center = nil,
                        right = -500,
                        action = 0.5,
                        content = 1.6,
                        voice = nil,
                },

                [91] = {
                        id = 91,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "来，小萤扶您起来。",
                        voice = nil,
                },

                [92] = {
                        id = 92,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = "萤火虫_收手悲伤2",
                        content = "对不起哦……刚才没有指挥好使魔，害您受伤了……",
                        voice = nil,
                },

                [93] = {
                        id = 93,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "（原来刚才脚底下那个是使魔在推着我飞吗！？）",
                        voice = nil,
                },

                [94] = {
                        id = 94,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "小萤这就给您治疗一下。",
                        voice = nil,
                },

                [95] = {
                        id = 95,
                        type = 12,
                        title = 2,
                        showCharacter = 10032,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = 0.2,
                        content = 100,
                        voice = nil,
                },

                [96] = {
                        id = 96,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "呼~呼~疼痛疼痛都飞走了！",
                        voice = nil,
                },

                [97] = {
                        id = 97,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "噗……这算什么治疗方式？",
                        voice = nil,
                },

                [98] = {
                        id = 98,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "放心吧，我只是摔了一跤，没受重伤。",
                        voice = nil,
                },

                [99] = {
                        id = 99,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = "萤火虫_害羞2",
                        content = "那、那就好……",
                        voice = nil,
                },

                [100] = {
                        id = 100,
                        type = 12,
                        title = 0,
                        showCharacter = 10032,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = 0.5,
                        content = nil,
                        voice = nil,
                },

                [101] = {
                        id = 101,
                        type = 14,
                        title = 1,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [102] = {
                        id = 102,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "不过你为什么会在这里？",
                        voice = nil,
                },

                [103] = {
                        id = 103,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "当然是为了等您忙完工作，给您提供别的方便呀。",
                        voice = nil,
                },

                [104] = {
                        id = 104,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = "萤火虫_笑",
                        content = "没想到指挥官这么快出来了！嘿嘿~果然是因为小萤的“超级简单易懂魔法化系统”用起来很方便，一下子就把工作处理完了吧？",
                        voice = 132049,
                },

                [105] = {
                        id = 105,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "接下来您是打算去巡视演习吗？小萤要很隆重地告诉您——不用去啦！我已经把您的日程表都调整成“休息”咯。",
                        voice = nil,
                },

                [106] = {
                        id = 106,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "……发现始作俑者了。",
                        voice = nil,
                },

                [107] = {
                        id = 107,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "姑且问一下，小萤，你今早有动过指挥室的文件吗？",
                        voice = nil,
                },

                [108] = {
                        id = 108,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = "萤火虫_自豪",
                        content = "您发现啦！没错，正是勤劳的小萤为您整理了文——{Pause=0.2}哎{Action=萤火虫_害怕2}呀！为什么要敲小萤脑袋！？",
                        voice = nil,
                },

                [109] = {
                        id = 109,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "这是给添乱的“坏孩子”的小小教训。",
                        voice = nil,
                },

                [110] = {
                        id = 110,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "坏孩子……？",
                        voice = 132033,
                },

                [111] = {
                        id = 111,
                        type = 5,
                        title = nil,
                        showCharacter = 1,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [112] = {
                        id = 112,
                        type = 4,
                        title = "scene_black",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [113] = {
                        id = 113,
                        type = 22,
                        title = nil,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [114] = {
                        id = 114,
                        type = 5,
                        title = "PlotLyrical",
                        showCharacter = 1,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [115] = {
                        id = 115,
                        type = 4,
                        title = "scene_corridor",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [116] = {
                        id = 116,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = "萤火虫_收手悲伤2",
                        content = "原来是这样……",
                        voice = 132039,
                },

                [117] = {
                        id = 117,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "小萤本来觉得，把文件整理好、把系统调整得简单易懂、帮指挥官多放几天假，就能帮您减轻负担了，结果却添了这么多麻烦……",
                        voice = nil,
                },

                [118] = {
                        id = 118,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "既然你是出于好心，我就不多追究了，不要太自责。",
                        voice = nil,
                },

                [119] = {
                        id = 119,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "只是我不明白，你为什么突然要自告奋勇来帮忙？",
                        voice = nil,
                },

                [120] = {
                        id = 120,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "那是因为……",
                        voice = nil,
                },

                [121] = {
                        id = 121,
                        type = 12,
                        title = 2,
                        showCharacter = 10032,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = 0.2,
                        content = 100,
                        voice = nil,
                },

                [122] = {
                        id = 122,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "（偷瞄）",
                        voice = nil,
                },

                [123] = {
                        id = 123,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "？",
                        voice = nil,
                },

                [124] = {
                        id = 124,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "指挥官……难道您忘记之前在魔法之家许的愿望了？",
                        voice = nil,
                },

                [125] = {
                        id = 125,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "……啊。",
                        voice = nil,
                },

                [126] = {
                        id = 126,
                        type = 15,
                        title = 129,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [127] = {
                        id = 127,
                        type = 10,
                        title = "Effect_UI_FanHuangTeXiao_2",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [128] = {
                        id = 128,
                        type = 4,
                        title = "scene_activityroom2",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [129] = {
                        id = 129,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "愿望吗……",
                        voice = nil,
                },

                [130] = {
                        id = 130,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "我倒没有特别的想法，大概也就希望工作能轻松一些吧。",
                        voice = nil,
                },

                [131] = {
                        id = 131,
                        type = 15,
                        title = 135,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [132] = {
                        id = 132,
                        type = 11,
                        title = "Effect_UI_FanHuangTeXiao_2",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [133] = {
                        id = 133,
                        type = 4,
                        title = "scene_corridor",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [134] = {
                        id = 134,
                        type = 22,
                        title = nil,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [135] = {
                        id = 135,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "原来是因为那句话……",
                        voice = nil,
                },

                [136] = {
                        id = 136,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "（当时只是随口一说，没想到她认真记在心里了。）",
                        voice = nil,
                },

                [137] = {
                        id = 137,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "……",
                        voice = nil,
                },

                [138] = {
                        id = 138,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = "萤火虫_悲伤3",
                        content = "结果完全没帮上您……反而给您和大家增加了更多工作，小萤好惭愧……",
                        voice = 132039,
                },

                [139] = {
                        id = 139,
                        type = 12,
                        title = 4,
                        showCharacter = 10032,
                        left = nil,
                        center = nil,
                        right = -500,
                        action = 0.5,
                        content = 1.6,
                        voice = nil,
                },

                [140] = {
                        id = 140,
                        type = 14,
                        title = 1,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [141] = {
                        id = 141,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "指、指挥官……？",
                        voice = nil,
                },

                [142] = {
                        id = 142,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "谢谢你，小萤。",
                        voice = nil,
                },

                [143] = {
                        id = 143,
                        type = 12,
                        title = 2,
                        showCharacter = 10032,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = 0.2,
                        content = 100,
                        voice = nil,
                },

                [144] = {
                        id = 144,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = "萤火虫_收手悲伤2",
                        content = "唔，明明添了麻烦，这都要被道谢的话，小萤会无地自容的……",
                        voice = 132042,
                },

                [145] = {
                        id = 145,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "不是因为这些事……",
                        voice = nil,
                },

                [146] = {
                        id = 146,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "我是在感谢小萤这么重视我的想法。虽然没有帮上忙，但你的心意让我很感动哦。",
                        voice = nil,
                },

                [147] = {
                        id = 147,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "呜……小萤会好好反省的，我实在很想减轻您的负担……",
                        voice = nil,
                },

                [148] = {
                        id = 148,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "我知道。",
                        voice = nil,
                },

                [149] = {
                        id = 149,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "……",
                        voice = nil,
                },

                [150] = {
                        id = 150,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "……",
                        voice = nil,
                },

                [151] = {
                        id = 151,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = "萤火虫_害羞",
                        content = "（小声）不、不过小萤要说……您抱得好紧哦？",
                        voice = nil,
                },

                [152] = {
                        id = 152,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "啊，太紧了吗……",
                        voice = nil,
                },

                [153] = {
                        id = 153,
                        type = 12,
                        title = 0,
                        showCharacter = 10032,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = 0.5,
                        content = nil,
                        voice = nil,
                },

                [154] = {
                        id = 154,
                        type = 14,
                        title = 1,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [155] = {
                        id = 155,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "总之你想帮忙可以随时跟我说。",
                        voice = nil,
                },

                [156] = {
                        id = 156,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "我平时处理的信息比较繁琐，只有我们两个一起梳理解决才能事半功倍。",
                        voice = nil,
                },

                [157] = {
                        id = 157,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = "萤火虫_闭眼",
                        content = "……嗯！小萤知道了！",
                        voice = 132035,
                },

                [158] = {
                        id = 158,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "小萤想要弥补自己今天做错的事，怎么才能帮到您呢……？",
                        voice = nil,
                },

                [159] = {
                        id = 159,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "可以到指挥室来和我一起整理文件，不过要等晚上了，我现在有点累，想多休息一下。",
                        voice = nil,
                },

                [160] = {
                        id = 160,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = "萤火虫_笑",
                        content = "那小萤帮您按摩吧！捏捏肩膀捶捶腿很治愈的~",
                        voice = 132057,
                },

                [161] = {
                        id = 161,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "这点子不错，那就去休息室吧！",
                        voice = nil,
                },

                [162] = {
                        id = 162,
                        type = 1,
                        title = "萤火虫",
                        showCharacter = 10032,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "需要让使魔帮您飞过去吗！这次我一定会控制好速度的！",
                        voice = nil,
                },

                [163] = {
                        id = 163,
                        type = 6,
                        title = 10,
                        showCharacter = 0.5,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [164] = {
                        id = 164,
                        type = 1,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10032,
                        right = nil,
                        action = nil,
                        content = "这就不要了！？",
                        voice = nil,
                },

                [165] = {
                        id = 165,
                        type = 1,
                        title = nil,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "所幸，那天的怪事风波在萤火虫的弥补下很快平息了。",
                        voice = nil,
                },

                [166] = {
                        id = 166,
                        type = 1,
                        title = nil,
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = "或许魔法之家的小主人今后大概还会用她笨拙却真诚的方式，一点点帮助需要帮助的人吧。",
                        voice = nil,
                },

}
return avg_151003202Table