---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by
--- DateTime: 2019/11/13 11:10
---
local Buff_5007 = BaseClass("Buff_5007",Buff)
local base = Buff

local function __init(self)
    self.once_state = 0
    self.hit=false
end

local function OnAtkStart(self)
    if self.once_state == 1 then
        self.once_state = 2
    end
end

local function OnOccur(self)
    base.OnOccur(self)
    self.__tcc.AtkBuff["bf_1007"] ={}
    self.__tcc.AtkBuff["bf_1007"].id=1007
    self.__tcc.AtkBuff["bf_1007"].turn=2
    self.once_state = 1
end

local function OnRemoved(self)
    self.__tcc.AtkBuff["bf_1007"]=nil
    base.OnRemoved(self)
end

local function OnAtkEnd(self)
    if not self.hit then return end
    if self.once_state == 2 then
        OnRemoved(self)
    end
end
local function OnHit(self)
    base.OnHit(self)
    self.hit=true
end

Buff_5007.__init = __init
Buff_5007.OnAtkStart = OnAtkStart
Buff_5007.OnOccur = OnOccur
Buff_5007.OnRemoved = OnRemoved
Buff_5007.OnAtkEnd = OnAtkEnd
Buff_5007.OnHit=OnHit

return Buff_5007