<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>common</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <TargetFramework>net45</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Google.Protobuf">
      <HintPath>../../../../../../../tmp/ag_decompile_1t3uzm9t/ref/Google.Protobuf.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>../../../../../../../tmp/ag_decompile_1t3uzm9t/ref/UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="NLog">
      <HintPath>../../../../../../../tmp/ag_decompile_1t3uzm9t/ref/NLog.dll</HintPath>
    </Reference>
    <Reference Include="litjson">
      <HintPath>../../../../../../../tmp/ag_decompile_1t3uzm9t/ref/litjson.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>