<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Unity.InputSystem</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>Download/DLL/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>Download/DLL/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.XRModule" />
    <Reference Include="UnityEngine.UI">
      <HintPath>Download/DLL/UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule" />
    <Reference Include="UnityEngine.PhysicsModule" />
    <Reference Include="UnityEngine.Physics2DModule" />
    <Reference Include="UnityEngine.InputModule" />
    <Reference Include="UnityEngine.JSONSerializeModule" />
    <Reference Include="UnityEngine.VRModule" />
    <Reference Include="UnityEngine.UIElementsModule" />
  </ItemGroup>
</Project>