---
--- Generated by fantang
--- Created by fantang.
--- DateTime: 2020/7/9 13:34
---

------------ import ------------
local KTool = CS.Engine.Lib.KTool
local UISwitchImage = CS.Game.Native.Common.UISwitchImage
------------ import ------------

------------ define ------------
local PanelShowType = {
    None = 0,
    Animate = 1,    -- 动画展示
    Direct = 2,     -- 直接展示
    SweepAnimate = 3,   -- 在扫荡界面里面使用的时候播的动画
}
-- container 动画
local TaskAnimate =         "UIBattleEndLevelDailyTaskGo"
local TaskAnimateComplete = "UIBattleEndLevelDailyTaskCompleteGo"
local TaskDefault =         "UIBattleEndLevelDailyTaskGoDefault"
local TaskDefaultComplete = "UIBattleEndLevelDailyTaskCompleteGoDefault"

local TaskSweepComplete = "FightTeamEndLevel_TaskCellNode_Complete"
------------ define -------------

--- from: Assets/BundleResources/Prefabs/UIBattling/BattleEnd/UIBattleEndLevel.prefab
---@class BattleEndTaskNode
---@field Env                           	BattleEndTaskNode                                     
---@field controller                    	Engine.Modules.LuaBehaviour | Engine.UI.UILuaDialog
---@field LB_Slider                     	Engine.Modules.LuaBehaviour             
---@field Txt_taskType                  	UnityEngine.UI.Text                     
---@field Txt_progressNum               	TMPro.TextMeshProUGUI                   
---@field Txt_taskName                  	UnityEngine.UI.Text                     
---@field Animation_Container           	UnityEngine.Animation                   

local BattleEndTaskNode = Class("BattleEndTaskNode")

------------------------------------------------Lifecycle
function BattleEndTaskNode:Awake()
    self:CleanProperty()
    self.LB_Slider:Init()
    self.LT_Slider = self.LB_Slider.Env
    self.LT_Slider:SetProgress(0)
end

function BattleEndTaskNode:OnDestroy()
    self:CleanProperty()
    self.controller = nil
end
------------------------------------------------Lifecycle

function BattleEndTaskNode:CleanProperty()
    self.LT_Slider = nil
    self.complete = nil
end

------------------------------------------------Function

--- func desc
---@param taskId any
---@param taskProgressInfo table { oldProgress = 1, newProgress = 2, }
---@param showType any
function BattleEndTaskNode:ShowTaskNode(taskId, taskProgressInfo, showType)

    self.complete = false
    taskId = checkInt(taskId)
    if taskId < 10000 then
        -- 主线任务
        local vo = CfUtils.GetCfVo(AutoIds.IdSetting252, "MainTaskQuestVo", taskId)
        -- print("[任务] 主线", taskId, vo)
        if isNull(vo) then
            return 
        end
        local taskTargetProgress = vo.taskContenNum
        self.complete = taskProgressInfo.newProgress >= taskTargetProgress
        self.Txt_taskName.text = vo.taskTitle
        self.Txt_progressNum.text = string.format("<size=30><color=#545454>%d</color></size>/%d", taskProgressInfo.newProgress, taskTargetProgress)
        self.Txt_taskType.text = localize("主线任务")
        self.LT_Slider:SetProgress(taskProgressInfo.newProgress / taskTargetProgress)
    elseif 10000 < taskId and taskId < 19999 then
        -- 日常任务
        local vo = CfUtils.GetCfVo(AutoIds.IdSetting254, "DailyTaskVo", taskId)
        -- print("[任务] 日常", taskId, vo)
        if isNull(vo) then
            return 
        end
        local taskTargetProgress = vo.taskContent
        self.complete = taskProgressInfo.newProgress >= taskTargetProgress
        self.Txt_taskName.text = vo.taskTitle
        self.Txt_progressNum.text = string.format("<size=30><color=#545454>%d</color></size>/%d", taskProgressInfo.newProgress, taskTargetProgress)
        self.Txt_taskType.text = localize("日常任务")
        self.LT_Slider:SetProgress(taskProgressInfo.newProgress / taskTargetProgress)
    elseif 100000 < taskId and taskId < 699999 then
        -- 区域任务
        local vo = CfUtils.GetCfVo(AutoIds.IdSetting4090, "RegionTaskVo", taskId)
        -- print("[任务] 区域", taskId, vo)
        if isNull(vo) then
            return 
        end
        local taskTargetProgress = vo.taskContenNum
        self.complete = taskProgressInfo.newProgress >= taskTargetProgress
        self.Txt_taskName.text = vo.name
        self.Txt_progressNum.text = string.format("<size=30><color=#545454>%d</color></size>/%d", taskProgressInfo.newProgress, taskTargetProgress)
        self.Txt_taskType.text = localize("区域任务")
        self.LT_Slider:SetProgress(taskProgressInfo.newProgress / taskTargetProgress)
    end

    if showType == PanelShowType.Animate then
        self.Animation_Container:Play(self.complete and TaskAnimateComplete or TaskAnimate)
    elseif showType == PanelShowType.Direct then
        self.Animation_Container:Play(self.complete and TaskDefaultComplete or TaskDefault)
    elseif showType == PanelShowType.SweepAnimate then
        local canvasGroup = self.controller:GetComponent(typeof(CS.UnityEngine.CanvasGroup))
        if not isNull(canvasGroup) then
            canvasGroup.alpha = 1   -- 不知道是什么东西会把这个alpha改成0，这里强制打开一下
        end
        if self.complete then
            self.Animation_Container:Play(TaskSweepComplete)
            local transform = self.Animation_Container.transform
            local activePointNode = transform:Find("ActivePointNode")
            if activePointNode then
                KTool.SetActive(activePointNode, true)
            end
            local RT_slider = transform:Find("Slider/Fill")
            local SImg_Fill = RT_slider:GetComponent(typeof(UISwitchImage))
            SImg_Fill.Status = 2
            -- local titleText = transform:Find("TitleText")

        end
    end
end

function BattleEndTaskNode:StopAnimateShowTaskNode()
    
end

function BattleEndTaskNode:ReshowTaskNode()
    self.Animation_Container:Play(self.complete and TaskDefaultComplete or TaskDefault)
end

function BattleEndTaskNode:TaskNodeAnimateCompleted()
    return not self.Animation_Container:IsPlaying(self.complete and TaskAnimateComplete or TaskAnimate)
end
------------------------------------------------Function

return BattleEndTaskNode
