---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gaole.
--- DateTime: 2020-09-11 18:02:11
---
local CoWait = CS.Engine.Lib.CoWait
local util = require 'XLua.util'
local cs_coroutine = import('XLua.cs_coroutine')
local KCookie = CS.Engine.Lib.KCookie
local UIModule = CS.Engine.UI.UIModule
local ActionUtils = import('Game.UI.FightReady.UIMainChapter.ActionUtils')
local CountDownTime = 2592000 --30 * 86400 30天的秒数
local CDTimerModule = CS.Engine.Modules.CDTimerModule
local ActionComponent = GameUtils.GetOrAddEntityCompByType(ECSComponentType.Constants.ActionComponent)
local UINavigationBarRoot = CS.UINavigationBarRoot
local KTool = CS.Engine.Lib.KTool
---@type RegionQuestMgr
local RegionQuestMgr = import('Game.UI.FightReady.UIMainChapter.RegionQuestMgr')
local playerComp = GameUtils.GetOrAddEntityCompByType(ECSComponentType.Constants.PlayerComponent)
local Yielders = CS.Engine.Lib.Yielders
local URPBaseCamera = CS.Game.Native.URP.URPBaseCamera
local UIEffectCapturedImage = CS.UGUI.Effects.UIEffectCapturedImage
local Animation = CS.UnityEngine.Animation
local TimeCoroutine = import('Game.Behaviours.TimeCoroutine')
local XLuaUtils = CS.Engine.Lib.XLuaUtils
local AnnihilationUtils = import('Game.UI.FightReady.UIMainChapter.AnnihilationUtils')
local UIEventProxy = CS.Engine.UI.UIEventProxy
---@type CriWareUtils
local CriWareUtils =  import('Game.Entry.CriWareUtilsFix')

--房间状态
local HouseState = {
    None = 0,   --无操作 只有自己
    InviteWaiting = 1,   --等待中 已发起邀请
    InviteSuc = 2,   --邀请成功
    ReadySuc = 3,   ---准备成功
}
local MatchPanelLuaPath = "Game.UI.FightReady.UIMainChapter.UIActionAnnihilation.UIActionPointMapBossMatch"
local RecruitBtnAnimation = "ActionTeamDestoryDialog_ImgSymbolActivation"

--- from: Assets/BundleResources/Prefabs/Action/ActionTeamDestoryDialog.prefab > name: ActionTeamDestoryDialog
---@class UIActionTeamDestoryDialog
---@field Env                           	UIActionTeamDestoryDialog               
---@field controller                    	Engine.UI.UILuaDialog                   
---@field RT_ConsumePop                 	UnityEngine.RectTransform               
---@field Txt_RemainTimes               	TMPro.TextMeshProUGUI                   
---@field TxtRecruitTime                	CustomText                              
---@field TxtRecruit                    	CustomText                              
---@field BtnCancelResruit              	UnityEngine.RectTransform               
---@field Txt_RecommandPower            	TMPro.TextMeshProUGUI                   
---@field TextNumber                    	UnityEngine.RectTransform               
---@field UIFX_LadderCompetionMatchDialog	UnityEngine.RectTransform               
---@field Underway                      	UnityEngine.RectTransform               
---@field MatchDisplay                  	UnityEngine.RectTransform               
---@field Complete                      	UnityEngine.RectTransform               
---@field FontStyleButton               	UnityEngine.RectTransform               
---@field ActionTeamDestoryMatchDialog  	UnityEngine.RectTransform               
---@field ClickClose                    	UnityEngine.RectTransform               
---@field BtnSearch                     	UnityEngine.RectTransform               
---@field BtnMatch                      	UnityEngine.RectTransform               
---@field SecondMenu                    	UnityEngine.RectTransform               
---@field TxtNum2                       	UnityEngine.RectTransform               
---@field ImgLoad2                      	UnityEngine.UI.Image                    
---@field TxtNum                        	UnityEngine.RectTransform               
---@field ImgLoad                       	UnityEngine.UI.Image                    
---@field LoadingGroup2                 	UnityEngine.RectTransform               
---@field LoadingGroup                  	UnityEngine.RectTransform               
---@field Before                        	UnityEngine.RectTransform               
---@field BtnChat                       	UnityEngine.RectTransform               
---@field BossRoleGroup                 	UnityEngine.RectTransform               
---@field ImgBgBoss                     	UnityEngine.RectTransform               
---@field After                         	UnityEngine.RectTransform               
---@field InvateGroup                   	UnityEngine.RectTransform               
---@field InvateInfo                    	UnityEngine.RectTransform               
---@field TxtStart                      	UnityEngine.RectTransform               
---@field TxtTime2                      	UnityEngine.RectTransform               
---@field LeftPanel                     	UnityEngine.RectTransform               
---@field RightPanel                    	UnityEngine.RectTransform               
---@field StartGroup                    	UnityEngine.RectTransform               
---@field TitleGroup                    	UnityEngine.RectTransform               
---@field RightGroup                    	UnityEngine.RectTransform               
---@field LeftGroup                     	UnityEngine.RectTransform               
---@field BtnStart                      	UnityEngine.RectTransform               
---@field TxtTitle                      	UnityEngine.RectTransform               
---@field WaitingGroup                  	UnityEngine.RectTransform               
---@field PlayerGroup2                  	UnityEngine.RectTransform               
---@field PlayerGroup                   	UnityEngine.RectTransform               
---@field Container                     	UnityEngine.RectTransform               
---@field Root                          	UnityEngine.RectTransform               
local UIActionTeamDestoryDialog = Class("UIActionTeamDestoryDialog")

function UIActionTeamDestoryDialog:__init()
    self.activityType = 0
    self.activityContetnId = 0
    self.activityUuid = 0
    self._curQuestId = 0    --关卡id
    self._bossTypeId = 0    --boss;类型

    self._countDown = 0     --倒计时
    self._timeDown = nil     --

    self._matchingTime = 60
    self._isClearScene = true
    self._enterBattle = false
    self.co_showRecruitTime = nil   -- 招募计时
    self.tc_RecruitProtect = nil    -- 招募按钮保护计时器
    self.teamRoomUITypeId = nil
end

function UIActionTeamDestoryDialog:__delete()
    self.activityType = 0
    self.activityContetnId = 0
    self.activityUuid = 0
    self._curQuestId = 0
    self._timeDown = nil
    self._bossTypeId = 0    --关卡id
    self._countDown = 0     --倒计时

    self._matchingTime = 60
    self._isClearScene = true
    self._enterBattle = false
    self.co_showRecruitTime = nil   -- 招募计时
    self.tc_RecruitProtect = nil    -- 招募按钮保护计时器
    self.teamRoomUITypeId = nil
end

function UIActionTeamDestoryDialog:Awake()
    local scr = CfUtils.GetLuaScr(self.BtnChat, "Game.OverseaChat.OverseaChatButtonNode")
    if isNotNull(scr) then
        scr:InitRedPoint()
    end
    local chatTrans = self.BtnChat.transform.parent:Find("Button")
    if chatTrans then
        SetButtonAction(chatTrans.gameObject, function()
            ---聊天功能
            UIModule.OpenDialog(UIArgs(Constants.UITypeIds.OverseaChatMainDialog))
        end)
    end
    self.EventRegionTeamInviteResult = Events.AddListener(Constants.EventNames.RegionTeamInviteResult, Bind(self, self.OnRegionTeamInviteResult))
    self.EventRegionTeamReadey = Events.AddListener(Constants.EventNames.RegionTeamReadey, Bind(self, self.OnRegionTeamReadey))
    self.EventRegionTeamQuite = Events.AddListener(Constants.EventNames.RegionTeamQuite, Bind(self, self.OnRegionTeamQuite))
    self.EventRegionTeamSet = Events.AddListener(Constants.EventNames.RefeshTeamMember, Bind(self, self.FillDialog))
    self.EventRegionTeamKickout = Events.AddListener(Constants.EventNames.RegionTeamKickout, Bind(self, self.OnRegionTeamKickout))
    self.EventRegionRecruitResult = Events.AddListener(Constants.EventNames.RegionRecruitResult, Bind(self, self.OnRegionRecruitResult))
    self.EventReconnectRefreshDisplay = Events.AddListener(Constants.EventNames.TeamRoomReconnectRefreshDisplay, Bind(self, self.FillDialog))
    self.EventUpdateResources = Events.AddListener(Constants.EventNames.DreamAdventuresHomeDataUpdate, Bind(self, self.UpdateResources))

    self.EventRegionLoadBegin = Events.AddListener(Constants.EventNames.RegionLoadBegin, Bind(self, self.OnLoadBegin))
    self.EventRegionLoading = Events.AddListener(Constants.EventNames.RegionLoading, Bind(self, self.OnLoading))
    
    self.EventExecuteBackHome = Events.AddListener(Constants.EventNames.ExecuteBackHome, Bind(self, self.OnExecuteBackHome))

    self.EventOnAppQuit = Events.AddListener(Constants.EventNames.ONAPPQUIT, Bind(self, self.OnAppQuit))

    SetButtonAction(self.BtnSearch, Bind(self,self.OnBtnPeopleInvate))
    SetButtonAction(self.TitleGroup, function()
        self._isClearScene =false
        UIModule.OpenDialog({ id = Constants.UITypeIds.UIBossDetailDialog, parameters = { levelId = self._curQuestId } }, {
            {id = self.teamRoomUITypeId }
        })
    end)
    -- self.LT_MatchPanel = GetLuaBehaviour(self.ActionTeamDestoryMatchDialog.gameObject, MatchPanelLuaPath).Env

    -- 招募按钮
    self.Go_BtnRecruit = self.BtnMatch.transform:Find("Root/Area").gameObject
    SetButtonAction(self.Go_BtnRecruit, Bind(self, self.OnBtnRecruit))
    self.anim_BtnRecruit = self.BtnMatch.transform:Find("Root"):GetComponent(typeof(Animation))

    -- 招募按钮保护时间的计时器
    ---@type TimeCoroutine
    self.tc_RecruitProtect = TimeCoroutine(2)

    -- 根节点动画
    self.anim_Container = self.Root.transform:Find("Container"):GetComponent(typeof(Animation))

    -- 消耗体力按钮
    if isNotNull(self.RT_UseHP) then
        local usehp = RegionQuestMgr:GetInstance():GetUseHP()
        KTool.SetActive(self.RT_UseHPContent, usehp == 1)
        KTool.SetActive(self.RT_TextUnopened, usehp == 0)
        KTool.SetActive(self.RT_TextOpen, usehp == 1)
        
        UIEventProxy.Create(self.RT_UseHP.gameObject).onPointerClick = function()
            local useHP = 1 - RegionQuestMgr:GetInstance():GetUseHP()
            RegionQuestMgr:GetInstance():SetUseHP(useHP)
            KTool.SetActive(self.RT_UseHPContent, useHP == 1)
            KTool.SetActive(self.RT_TextUnopened, useHP == 0)
            KTool.SetActive(self.RT_TextOpen, useHP == 1)
            self:FillRewardTimesAndConsumeInfo()
        end
    end

    -- 麦克风初始默认关闭
    self.STxt_BtnOpenState.Status = 2
end

function UIActionTeamDestoryDialog:OnInitialize()
    local coWait = CoWait.Start():Coroutine(util.cs_generator(function()
        local canvas = KTool.GetComponent(UINavigationBarRoot.Instance.gameObject, typeof(CS.UnityEngine.Canvas))
        canvas.enabled = true
    
        local t = RegionQuestMgr:GetInstance():GetHouseInfo()
        if not t then
            return
        end
        self.activityType = checkNumber(t.activityType)
        self.activityContetnId = checkNumber(t.activityContentId)
        self.activityUuid = checkNumber(t.activityUuid)
        self.activityPrefabId = checkNumber(t.activityPrefabId)
        self._curQuestId = checkNumber(t.questId)
        self._bossTypeId = checkNumber(t.bossTypeId)

        if self._curQuestId <= 0 or self._bossTypeId < 0 then
            return
        end
        self.comp = AnnihilationUtils.GetComponent(self.activityPrefabId)
        
        self.teamRoomUITypeId = self.comp:GetTeamUITypeId()

        -- 加载场景和角色模型
        coroutine.yield(RegionQuestMgr:GetInstance():EntryRegionTeamScene())
        RegionQuestMgr:GetInstance():SetSceneActive(true)
        GameUtils.HidePreviousDialogs(self.controller)
        KCookie.Set(Constants.UICacheDataKeys.OVERSEA_ANNIHILATION_KEY, 1)
        -- 绘制界面
        self:FillDialog()
        
        -- 进入聊天房间
        local useVoiceRoom = self.comp:UseVoiceRoom()
        RegionQuestMgr:GetInstance().useVoiceRoom = useVoiceRoom
        if useVoiceRoom then
            local t = RegionQuestMgr:GetInstance():GetHouseInfo()
            local social = AppService:GetInstance():GetSocialLine()
            social:EnterVoiceRoom(t.roomId)
        end
    end))
    return coWait
end

function UIActionTeamDestoryDialog:OnShow()
    ---@type Engine.Lib.CoWait
    local coWait = CoWait.Start():Coroutine(util.cs_generator(function()
        CfUtils.SetTopRightProjection(0)
        CfUtils.SetUICameraProjection(true, 26)    -- 设置UI相机的透视模式和fov
        self:OnRegionTeamQuite()

        local cam = RegionQuestMgr:GetInstance():GetCurrentSceneCam()
        if not isNull(cam) then 
            local urpBase = cam:GetComponent(typeof(URPBaseCamera))
            urpBase:CopyCamera() 
        end

        local imOwner = RegionQuestMgr:GetInstance():GetIsHouseOwn()
        if imOwner then
            -- 开房时记录最后进入的Boss和关卡
            GameUtils.SaveInt(string.format("AnnihilationLastBoss_%s_%d_%d", GameUtils.GetPlayerId(), self.activityPrefabId, self.activityContetnId), self._bossTypeId)
            GameUtils.SaveInt(string.format("AnnihilationLastBossQuest_%s_%d_%d_%d", GameUtils.GetPlayerId(), self.activityPrefabId, self.activityContetnId, self._bossTypeId), self._curQuestId)
        end
    end))
    return coWait
end

-- function UIActionTeamDestoryDialog:OnHide()
--     ---@type Engine.Lib.CoWait
--     local coWait = CoWait.Start():Coroutine(util.cs_generator(function()
--         -- self:OnCaptureAction()
--         if self._isClearScene then
--             if not self._enterBattle then   -- 如果是进入战斗，就不要发送退出房间的消息
--                 RegionQuestMgr:GetInstance():QuitReq()
--                 print("[歼灭战] mgr quit req OnHide")
--             end
--             RegionQuestMgr:GetInstance():Clear()
--             print("[歼灭战] OnHide")
--         end
--     end))
--     return coWait
-- end

function UIActionTeamDestoryDialog:HandleBackAction()
    CfUtils.StartCoroutineWithBlocker(function()
        xTry(function()
            -- cs_coroutine.yield_return(Yielders.GetWaitForSeconds(0.1))
            self._isClearScene = true
            local social = AppService:GetInstance():GetSocialLine()
            social:ExitTeamRoom()
            if self.comp:UseVoiceRoom() then
                social:ExitVoiceRoom()
            end
            cs_coroutine.yield_return(self:OnCaptureAction())
            RegionQuestMgr:GetInstance():QuitReq()
            print("[歼灭战] mgr quit req HandleBackAction")
            RegionQuestMgr:GetInstance():QuitRegionTeamScene()
        end)
    end)
end

function UIActionTeamDestoryDialog:OnFocus(focus)
    if focus then
        CfUtils.RefreshTopGoods(self.comp:GetResources())
        -- 刷新消耗道具提示
        self:FillRewardTimesAndConsumeInfo()
    end
end

function UIActionTeamDestoryDialog:OnFinalize()
    local coWait = CoWait.Start():Coroutine(util.cs_generator(function()
        if self._co ~= nil then
            cs_coroutine.stop(self._co)
            self._co = nil
        end
        self:StopShowRecruitTime()
        self.tc_RecruitProtect:Stop()
        Events.RemoveListener(Constants.EventNames.RegionTeamInviteResult, self.EventRegionTeamInviteResult)
        Events.RemoveListener(Constants.EventNames.RegionTeamReadey, self.EventRegionTeamReadey)
        Events.RemoveListener(Constants.EventNames.RegionTeamQuite, self.EventRegionTeamQuite)
        Events.RemoveListener(Constants.EventNames.RefeshTeamMember, self.EventRegionTeamSet)

        Events.RemoveListener(Constants.EventNames.RegionLoadBegin, self.EventRegionLoadBegin)
        Events.RemoveListener(Constants.EventNames.RegionLoading, self.EventRegionLoading)

        Events.RemoveListener(Constants.EventNames.RegionTeamMatch, self.EventRegionTeamMatch)
        
        Events.RemoveListener(Constants.EventNames.ExecuteBackHome, self.EventExecuteBackHome)
        Events.RemoveListener(Constants.EventNames.RegionRecruitResult, self.EventRegionRecruitResult)
        Events.RemoveListener(Constants.EventNames.ONAPPQUIT, self.EventOnAppQuit)
        Events.RemoveListener(Constants.EventNames.TeamRoomReconnectRefreshDisplay, self.EventReconnectRefreshDisplay)
        Events.RemoveListener(Constants.EventNames.DreamAdventuresHomeDataUpdate, self.EventUpdateResources)

        GameUtils.RemoveRedPointCallBack(Constants.RedPointConst.OverseaChat)
        if not isNull(self._timeDown) then
            CDTimerModule.GetInstance():RemoveCD(self._timeDown)
            self._timeDown = nil
        end
        CfUtils.SetTopCommonCb()

        --if self._isClearScene and not self._enterBattle then    -- 进入战斗的时候不用打开主界面，否则退出战斗的时候也会自动打开主界面，导致出bug
        --    Events.Broadcast(Constants.EventNames.UIMainHomeSceneFocusShowEventName, true)
        --end
        GameUtils.ShowPreviousDialogs(self.controller)
        self.controller = nil --删除lua层引用到的c#对象 否则不会产生c# gc回收到对象
        self:Delete()
        self = nil --lua层的gc需要
    end))
    return coWait
end

function UIActionTeamDestoryDialog:OnCaptureAction()
    if self._isClearScene then
        -- capture screen
        local effectBg = self.controller.gameObject:GetComponent(typeof(UIEffectCapturedImage))
        if effectBg then
            effectBg:Capture()
        end
        cs_coroutine.yield_return(Yielders.EndOfFrame)
        cs_coroutine.yield_return(RegionQuestMgr:GetInstance():Clear())
    end
end

function UIActionTeamDestoryDialog:InitData()
end

function UIActionTeamDestoryDialog:FillDialog()
    self:FillQuestInfo()
    self:FillHouseOwnerInfo()
    self:FillHouseMemberInfo()
    self:FillBtnStartInfo()
    self:FillBtnRecruit()
    self:FillRewardTimesAndConsumeInfo()
    self:FillMicInfo()
    self:FillRewardTimesFilter()
    self:FillRealtimeReward()
end

--- 实时匹配奖励
function UIActionTeamDestoryDialog:FillRealtimeReward()
    if isNull(self.GoodGroup) then
        return
    end

    local vo = RewardConfMgr:GetInstance():GetQuestRewardVo(self._curQuestId)
    if isNull(vo) then
        return
    end

    local rewardIdList = vo.playerRewardItem
    local rewardNumList = vo.playerRewardNum

    local rewards = parse_rewards(rewardIdList, rewardNumList, ";")

    if table.count(rewards) <= 0 then
        KTool.SetActive(self.GoodGroup, false)
        return
    end

    print("[实时奖励]", table.dump(rewards))
    
    local luaPath = "Game.UI.FightReady.UIMainChapter.ActionTeamDestoryDialog.UIActionTeamDestroyRealtimeReward"
    ---@type UIActionTeamDestroyRealtimeReward
    local lt = CfUtils.GetLuaScr(self.GoodGroup.gameObject, luaPath)
    lt:Refresh(rewards)

    local activeState = false
    local desc = ""
    local state = RegionQuestMgr:GetInstance():GetHouseState()
    if state == HouseState.None or state == HouseState.InviteWaiting then
        -- 没人
        activeState = false
        desc = localize("邀请在线好友一起时激活")
    elseif state == HouseState.InviteSuc or state == HouseState.ReadySuc then
        -- 有人
        local isRobot = RegionQuestMgr:GetInstance():IsOtherRobot()
        if isRobot == 1 then
            -- 机器人
            activeState = false
            desc = localize("邀请在线好友一起时激活")
        else
            -- 真人
            local rewardTimes = checkNumber(self.comp.remainCreateRewardTimes)  -- 剩余奖励次数
            if rewardTimes > 0 then
                -- 有剩余次数
                activeState = true
            else
                -- 没有剩余次数了
                activeState = false
                desc = localize("今日奖励次数已用完")
            end
        end
    end
    lt:SetActive(activeState)
    lt:OnInActiveClicked(function()
        GameUtils.Toast(desc)
    end)
end

--- 多倍消耗的列表
function UIActionTeamDestoryDialog:FillRewardTimesFilter()
    if isNull(self.AlignNode) then
        return
    end
    local rewardTimes = checkNumber(self.comp.remainCreateRewardTimes)  -- 剩余奖励次数
    if rewardTimes <= 0 then
        KTool.SetActive(self.AlignNode, false)
        return
    end
    ---@type CommonFilter
    local lt = CfUtils.GetLuaScr(self.AlignNode.gameObject, "Game.UI.Common.CommonFilter")
    if isNotNull(lt) then
        KTool.SetActive(self.AlignNode, true)

        local vo = QuestConfMgr:GetInstance():GetQuestVoById(self._curQuestId)
        if isNull(vo) then
            printError("id %s 找不到关卡信息", self._curQuestId)
            return
        end
        local costItem = vo.costItem
        local costNum = (vo.costNum + vo.costNumLose)

        ---@type GoodsVo
        local goodsVo = GoodsConfMgr:GetInstance():GetGoodsVoById(costItem)
        if isNull(goodsVo) then
            printError("id %s 找不到道具信息", costItem)
            return
        end
        -- 构造列表数据
        local filterData = {}
        for i = 1, rewardTimes, 1 do
            local data = {
                imgPath = goodsVo.photoPath,
                text1 = localize("_num_倍", {_num_ = i}),
                text2 = tostring(costNum * i)
            }
            table.insert(filterData, data)
        end
        lt:SetOnValueChanged(function(index)
            RegionQuestMgr:GetInstance():SetConsumeTimes(index)
        end)
        local times = RegionQuestMgr:GetInstance():GetConsumeTimes()
        lt:RefreshPanel(filterData, times)
    end
end

function UIActionTeamDestoryDialog:FillMicInfo()
    local useVoice = false  -- self.comp:UseVoiceRoom()
    KTool.SetActive(self.CommonVoiceChatBtn.transform.parent, useVoice)
    if useVoice then
        local lb = GetLuaBehaviour(self.CommonVoiceChatBtn.gameObject, "Game.Behaviours.CommonMicBtn")
        lb.Env:SetPlayerId(checkNumber(GameUtils.GetPlayerId()))
        lb.Env:SetCallbackOnBtnStageChanged(function(state)
            self.STxt_BtnOpenState.Status = state and 1 or 2
        end)
    end
end

function UIActionTeamDestoryDialog:FillRewardTimesAndConsumeInfo()
    if self.activityType == 0 then
        -- 剩余奖励次数
        local rewardTimes = checkNumber(self.comp.remainCreateRewardTimes)
        self.Txt_RemainTimes.text = tostring(rewardTimes)
        
        -- 奖励次数清零以后，不显示消耗道具提示
        KTool.SetActive(self.RT_ConsumePop, rewardTimes > 0)
    else
        local useHP = RegionQuestMgr:GetInstance():GetUseHP()
        KTool.SetActive(self.RT_ConsumePop, useHP == 1)
    end
    
    -- 刷新消耗道具提示
    local vo = QuestConfMgr:GetInstance():GetQuestVoById(self._curQuestId)
    CfUtils.FillCommonBtnConsumePopNode(self.RT_ConsumePop, vo.costItem, (vo.costNum + vo.costNumLose))
end

--- 绘制关卡信息
function UIActionTeamDestoryDialog:FillQuestInfo()
    -- 关卡名
    local typeVo = self.comp:GetTypeVo(self._bossTypeId)
    if not typeVo then
        return
    end
    CfUtils.FillText(self.TxtTitle, typeVo.name)
    
    -- 推荐战力
    local vo = QuestConfMgr:GetInstance():GetQuestVoById(self._curQuestId)
    if not vo then
       return
    end
    local recommendPower = vo.proposalLevel
    CfUtils.FillText(self.Txt_RecommandPower, recommendPower)
    CfUtils.SetColor(self.Txt_RecommandPower, self:IsOverRecommendPower() and Color.white or XLuaUtils.HexToColor("#ff6363"))
end

--- 绘制房主信息
function UIActionTeamDestoryDialog:FillHouseOwnerInfo()
    -- 看房主是不是我自己
    local imOwner = RegionQuestMgr:GetInstance():GetIsHouseOwn()

    local scr = CfUtils.GetLuaScr(self.PlayerGroup2, "Game.UI.FightReady.UIMainChapter.ActionTeamDestoryDialog.UIActionTeamDestoryNode")
    if scr then
        local data = RegionQuestMgr:GetInstance():GetHouseOwnerInfo()
        scr:Refresh(data, imOwner, true, function()
            -- 点击编队按钮回调
            if self._isBegin then
                return
            end

            RegionQuestMgr:GetInstance():SetSceneActive(false)
            self._isClearScene = false
            UIModule.OpenDialog({ id = Constants.UITypeIds.UIFightTeamChoose, parameters = { levelId = self._curQuestId, isOwn = imOwner and 1 or 0} }, {
                { id = self.teamRoomUITypeId },
            })
        end, function()
            local isMyself = imOwner
            if not isMyself then
                if data.playerInfo.playerId > 0 then
                    -- 直接进入 他人的 个人信息界面2D版 
                    self._isClearScene = false
                    GameUtils.ShowPlayerInfo( data.playerInfo.playerId, {{ id = self.teamRoomUITypeId}} )
                end
            end
        end, self.comp:UseVoiceRoom())
        -- 房主默认显示准备完成
        scr:FillReadyInfo(1)
    end
end

--- 绘制队员的信息
function UIActionTeamDestoryDialog:FillHouseMemberInfo()
    CfUtils.SetActive(self.InvateInfo, false)
    CfUtils.SetActive(self.WaitingGroup, false)
    CfUtils.SetActive(self.PlayerGroup, false)

    local state = RegionQuestMgr:GetInstance():GetHouseState()
    if state == HouseState.None or state == HouseState.InviteWaiting then
        CfUtils.SetActive(self.InvateInfo, true)
    --elseif state == HouseState.InviteWaiting then
    --    CfUtils.SetActive(self.WaitingGroup, true)
    elseif state == HouseState.InviteSuc or state == HouseState.ReadySuc then
        self:FillHouseMember()
        CfUtils.SetActive(self.PlayerGroup, true)
    end
end

--- 绘制队员
function UIActionTeamDestoryDialog:FillHouseMember()
    -- 看房客是不是我自己
    local imMember = not RegionQuestMgr:GetInstance():GetIsHouseOwn()

    local scr = CfUtils.GetLuaScr(self.PlayerGroup, "Game.UI.FightReady.UIMainChapter.ActionTeamDestoryDialog.UIActionTeamDestoryNode")
    if scr then
        local data = RegionQuestMgr:GetInstance():GetHouseMemberInfo()
        scr:Refresh(data, imMember, false, function()
            -- 点击编队按钮回调，查看别人的编队
            self._isClearScene = false

            UIModule.OpenDialog({ id = Constants.UITypeIds.UIFightTeamChoose, parameters = { levelId = self._curQuestId, isOwn = imMember and 1 or 0 } }, {
                { id = self.teamRoomUITypeId },
            })
        end, function()
            local isMyself = imMember
            if not isMyself then
                if data.playerInfo.playerId > 0 then
                    -- 直接进入 他人的 个人信息界面2D版 
                    self._isClearScene = false
                    GameUtils.ShowPlayerInfo( data.playerInfo.playerId, {{ id = self.teamRoomUITypeId}} )
                end
            end
        end, self.comp:UseVoiceRoom())
        -- 绘制准备状态
        local info = RegionQuestMgr:GetInstance():GetHouseMemberInfo()
        scr:FillReadyInfo(checkNumber(info.readyState))
    end
end

-- 点击准备按钮回调
function UIActionTeamDestoryDialog:OnBtnReady()
    -- 点击准备按钮回调
    if self._isBegin then
        return
    end

    local data = RegionQuestMgr:GetInstance():GetOwnInfo()
    local t = {
        ready = ((checkNumber(data.readyState) == 0) and 1 or 0)
    }
    -- 请求更新准备状态
    RegionQuestMgr:GetInstance():ReadyReq(t)
end

--- 服务器下发准备状态
function UIActionTeamDestoryDialog:OnRegionTeamReadey()
    self:FillReadyInfo()
    self:FillBtnStartInfo()
end

function UIActionTeamDestoryDialog:FillReadyInfo()
    local scr = CfUtils.GetLuaScr(self.PlayerGroup, "Game.UI.FightReady.UIMainChapter.ActionTeamDestoryDialog.UIActionTeamDestoryNode")
    if scr then
        local data = RegionQuestMgr:GetInstance():GetHouseMemberInfo()
        scr:FillReadyInfo(data.readyState)
        CfUtils.SetActive(self.LeftGroup, checkNumber(data.readyState) == 1)
    end
end

--开始按钮
function UIActionTeamDestoryDialog:FillBtnStartInfo()
    local comp = AnnihilationUtils.GetComponent(self.activityPrefabId)
    local animPrefix = comp:GetTeamRoomDialogAnimationPrefix()

    local isHouseOwn = RegionQuestMgr:GetInstance():GetIsHouseOwn()
    if isHouseOwn then
        CfUtils.FillText(self.TxtStart, localize("开始"))  
        CfUtils.PlayAnimation(self.StartGroup, animPrefix .. "_StartGroup_Ready")
        SetButtonAction(self.BtnStart, Bind(self,self.OnBtnStart))
    else
        local houseMemberState = RegionQuestMgr:GetInstance():GetHouseMemberInfo()
        local readyState = checkNumber(houseMemberState.readyState)
        if readyState == 0 then
            CfUtils.FillText(self.TxtStart, localize("准备"))
            CfUtils.PlayAnimation(self.StartGroup, animPrefix .. "_StartGroup_Ready")
            SetButtonAction(self.BtnStart, Bind(self, self.OnBtnReady))
        elseif readyState == 1 then
            CfUtils.FillText(self.TxtStart, localize("取消准备"))
            CfUtils.PlayAnimation(self.StartGroup, animPrefix .. "_StartGroup_Ready")
            SetButtonAction(self.BtnStart, Bind(self, self.OnBtnReady))
        end
    end
end

--- 房客收到需要退出房间的消息
function UIActionTeamDestoryDialog:OnRegionTeamQuite()
    local kickoutState = RegionQuestMgr:GetInstance():GetOwnKickOutState()
    if kickoutState > 0 then
        local str = ""
        if kickoutState == 1 then
            str = localize("被踢出房间")
        elseif kickoutState == 2 then
            str = localize("房间已解散")
        elseif kickoutState == 3 then
            str = localize("发生网络波动，请重新加入房间")
        end
        -- 如果聊天界面开着，先关闭聊天界面
        local chatDialog = GameUtils.GetDialog(Constants.UITypeIds.OverseaChatMainDialog)
        if isNotNull(chatDialog) then
            UIModule.CloseDialog(chatDialog)
        end
        GameUtils.SecondConfirm(str, function()
            GameUtils.ShowBlackOverlay(nil, function()
                self._isClearScene = false
                local social = AppService:GetInstance():GetSocialLine()
                social:ExitTeamRoom()
                if self.comp:UseVoiceRoom() then
                    social:ExitVoiceRoom()
                end
                cs_coroutine.yield_return(self:OnCaptureAction())
                RegionQuestMgr:GetInstance():QuitReq()
                RegionQuestMgr:GetInstance():QuitRegionTeamScene()
            end)
        end, function()
            GameUtils.ShowBlackOverlay(nil, function()
                self._isClearScene = false
                local social = AppService:GetInstance():GetSocialLine()
                social:ExitTeamRoom()
                if self.comp:UseVoiceRoom() then
                    social:ExitVoiceRoom()
                end
                cs_coroutine.yield_return(self:OnCaptureAction())
                RegionQuestMgr:GetInstance():QuitReq()
                RegionQuestMgr:GetInstance():QuitRegionTeamScene()
            end)
        end)
    end
end

--- 当收到踢人消息时
function UIActionTeamDestoryDialog:OnRegionTeamKickout()
    self:FillHouseMemberInfo()
    self:FillQuestInfo()   -- 更新总战力的颜色
    self:FillRealtimeReward()
end

--@region 匹配
--匹配
function UIActionTeamDestoryDialog:OnBtnMatching()
    RegionQuestMgr:GetInstance():StartHouseMatchingReq()
end 

--取消匹配
function UIActionTeamDestoryDialog:OnBtnCancelMatching()
    RegionQuestMgr:GetInstance():CancelHouseMatchingReq()
    self:OnMatchingEnd(false)
end

--s收到加入匹配结果
function UIActionTeamDestoryDialog:OnRegionTeamMatch(body)
    --成功, 可以开始匹配了
    if checkNumber(body.result) == 0 then
        self._matchingTime = ActionUtils.GetDefaultCountDown()
        CfUtils.FillText(self.TextNumber, self._matchingTime)

        CfUtils.SetActive(self.ActionTeamDestoryMatchDialog, true)
        CfUtils.SetActive(self.Root, false)
        self._isBeginMatching = true
        self.LT_MatchPanel:StartCountDown(self._matchingTime, function()
            self:OnBtnCancelMatching()
        end)

        -- CfUtils.PlayAnimator(self.ActionTeamDestoryMatchDialog.transform:Find("Root"), "Match")
    else
        CfUtils.SetActive(self.ActionTeamDestoryMatchDialog, false)
        CfUtils.SetActive(self.Root, true)
        self._isBeginMatching = false
        GameUtils.Toast(localize("加入匹配失败"))
    end
end

function UIActionTeamDestoryDialog:OnMatchingEnd(isSuc, cb)
    if isSuc then
        self._isBeginMatching = false
        self.LT_MatchPanel:PlayComplete(function()
            CfUtils.SetActive(self.Root, true)
            CfUtils.SetActive(self.ActionTeamDestoryMatchDialog, false)
            CfUtils.PlayAnimation(self.Root, "ActionTeamDestoryDialog_InvateGroupBack")
            if cb then
                cb()
            end
        end)
    else
        CfUtils.SetActive(self.ActionTeamDestoryMatchDialog, false)
        CfUtils.SetActive(self.Root, true)
        self._isBeginMatching = false
    end
end
--@endregion

function UIActionTeamDestoryDialog:OnExecuteBackHome()
    local social = AppService:GetInstance():GetSocialLine()
    social:ExitTeamRoom()
    if self.comp:UseVoiceRoom() then
        social:ExitVoiceRoom()
    end
end

--- 点击邀请按钮
function UIActionTeamDestoryDialog:OnBtnPeopleInvate()
    if self._isBegin then
        return
    end

    self._isClearScene = false 

    -- 检查是否有好友
    RegionQuestMgr:GetInstance():OverseaRegionalBossInvitePanelReq(2, function(data)
        local hasFriends = #checkTable(data.data) > 0
        local index = hasFriends and 1 or 3 -- 有好友显示好友，没好友显示AI机器人
        UIModule.OpenDialog({ id = Constants.UITypeIds.UIActionTeamInvitePopupDialog, parameters = {selectIndex = index, comp = self.comp}}, {
            {id = self.teamRoomUITypeId }
        })
    end)
end

--- 有邀请结果来了 刷新伙伴信息
function UIActionTeamDestoryDialog:OnRegionTeamInviteResult(data)
    if self._isBeginMatching then
        self:OnMatchingEnd(true, function()
            self:FillHouseMemberInfo()
            self:FillQuestInfo()
            self:FillRealtimeReward()
        end)
    else
        self:FillHouseMemberInfo()
        self:FillQuestInfo()
        self:FillRealtimeReward()

        if isNotNull(data) then
            CriWareUtils.PlaySe(UISheets.UI_Menu.path, UISheets.UI_Menu.ui_anzhuang)
        end
    end
end

--- 点击开始按钮(只有房主能点击开始)
function UIActionTeamDestoryDialog:OnBtnStart()
    if self._isBegin then
        return
    end

    --不是自己的房间
    local isHouseOwn = RegionQuestMgr:GetInstance():GetIsHouseOwn()
    if not isHouseOwn then
        return
    end

    local state = RegionQuestMgr:GetInstance():GetHouseState()
    -- 单人开始
    if state == HouseState.None
    or state == HouseState.InviteWaiting then
        if not RegionQuestMgr:GetInstance():IsTeamSet(true) then
            GameUtils.Toast(localize("编队为空"))
            return
        end
        
        GameUtils.SecondConfirm(localize("是否单人进入战斗？"), 
        function()
            RegionQuestMgr:GetInstance():StartBattleReq()
        end,
        nil,
        self:IsOverRecommendPower() and "" or localize("当前战斗力未达到推荐战力"))
    -- 双人开始
    elseif state == HouseState.ReadySuc
    or state == HouseState.InviteSuc then
        if not RegionQuestMgr:GetInstance():IsTeamSet(true) then
            GameUtils.Toast(localize("编队为空"))
            return
        end
        RegionQuestMgr:GetInstance():StartBattleReq()
    -- -- 有人没准备
    -- elseif state == HouseState.InviteSuc then
    --     -- 队友没准备
    --     GameUtils.Toast(localize("请等待队友准备完成"))
    end
end

--- 判断队伍战力是否超过推荐战力
function UIActionTeamDestoryDialog:IsOverRecommendPower()
    local vo = QuestConfMgr:GetInstance():GetQuestVoById(self._curQuestId)
    if not vo then
        return false
    end
    local recommendPower = vo.proposalLevel

    local myPower = RegionQuestMgr:GetInstance():GetOwnInfo().mainTeamSet.totalCombatVal

    local otherPower = 0
    local otherInfo = RegionQuestMgr:GetInstance():GetOtherInfo()
    if otherInfo and otherInfo.mainTeamSet and otherInfo.mainTeamSet.totalCombatVal then
        otherPower = checkNumber(otherInfo.mainTeamSet.totalCombatVal) 
    end

    return (checkNumber(myPower) + otherPower) >= checkNumber(recommendPower)
end

--- 绘制招募按钮
function UIActionTeamDestoryDialog:FillBtnRecruit()
    local state = RegionQuestMgr:GetInstance():GetRecruitState()
    self:SetRecruitBtnState(state, false)
end

function UIActionTeamDestoryDialog:SetRecruitBtnState(state, showTrail)
    if state == 0 then
        self.TxtRecruit.text = localize("公开招募")
        KTool.SetActive(self.BtnCancelResruit, false)
        KTool.SetActive(self.TxtRecruitTime, false)
    elseif state == 1 then
        self.TxtRecruit.text = localize("取消招募")
        KTool.SetActive(self.BtnCancelResruit, true)
        KTool.SetActive(self.TxtRecruitTime, true)
        self:StartShowRecruitTime()
    end
    -- 动效
    self:EffectOnRecruitBtnStateChanged(state, showTrail)
end

function UIActionTeamDestoryDialog:StartShowRecruitTime()
    if isNotNull(self.co_showRecruitTime) then
        return
    end
    -- 开始计时
    local time = RegionQuestMgr:GetInstance():GetRecruitTime()
    self.TxtRecruitTime.text = localize("等待中_num_s", {_num_ = time})

    self.co_showRecruitTime = cs_coroutine.start(function()
        while true do
            cs_coroutine.yield_return(Yielders.GetWaitForSeconds(1))
            local time = RegionQuestMgr:GetInstance():GetRecruitTime()
            self.TxtRecruitTime.text = localize("等待中_num_s", {_num_ = time})
        end
        self.co_showRecruitTime = nil
    end)
end

function UIActionTeamDestoryDialog:StopShowRecruitTime()
    if isNotNull(self.co_showRecruitTime) then
        cs_coroutine.stop(self.co_showRecruitTime)
        self.co_showRecruitTime = nil
    end
end

--- 请求修改招募状态
function UIActionTeamDestoryDialog:OnBtnRecruit()
    local state = RegionQuestMgr:GetInstance():GetRecruitState()
    if state == 0 then
        -- 开启招募需要判断保护时间
        if self.tc_RecruitProtect:IsRunning() then
            local time = self.tc_RecruitProtect:GetTime()
            GameUtils.Toast(localize("招募按钮冷却中 _num_秒", {_num_ = 3 - time}))
            return
        end
    end
    
    if state == 1 then
        self.tc_RecruitProtect:Stop()
        self.tc_RecruitProtect:Start(3)
    end

    RegionQuestMgr:GetInstance():RecruitReq()

end

--- 收到招募状态变化事件
---@param newState number
function UIActionTeamDestoryDialog:OnRegionRecruitResult(newState)
    self:SetRecruitBtnState(newState, true)
end

--- 招募按钮特效
---@param state any
function UIActionTeamDestoryDialog:EffectOnRecruitBtnStateChanged(state, showTrail)
    if state == 0 then
        self.anim_BtnRecruit:Stop()
        -- 关闭循环特效
        local loopEffect = self.anim_BtnRecruit.transform:Find("UIFX_LoopGlow")
        KTool.SetActive(loopEffect, false)
        -- 拖尾特效位置还原
        local trailEffect = loopEffect:Find("UIFX_Number_BoomMove")
        trailEffect.localPosition = Vector3.zero
        -- 关闭爆炸特效
        if isNotNull(self.anim_Container) then
            self.anim_Container:Stop()
            self.anim_Container:Play("ActionTeamDestoryDialog_OverseaChatBtnGlowDefault")
        end
    elseif state == 1 then
        self.anim_BtnRecruit:Play(RecruitBtnAnimation)
        -- 拖尾
        local trailEffect = self.anim_BtnRecruit.transform:Find("UIFX_LoopGlow/UIFX_Number_BoomMove")
        KTool.SetActive(trailEffect, showTrail)
        if showTrail then
            -- 移动拖尾特效
            local chatIcon = self.BtnChat:Find("Button/ImgChat")
            if isNotNull(chatIcon) then
                trailEffect:DOMove(chatIcon.position, 0.38, false):OnComplete(function()
                    -- 播放爆炸特效
                    if isNotNull(self.anim_Container) then
                        self.anim_Container:Play("ActionTeamDestoryDialog_OverseaChatBtnGlow")
                    end
                    -- 隐藏拖尾特效
                    KTool.SetActive(trailEffect, false)
                end)
            end
        end
    end
end

function UIActionTeamDestoryDialog:OnLoadBegin()
    self._isBegin = true
    local state = RegionQuestMgr:GetInstance():GetHouseState()
    --单人开始
    if state == HouseState.None then
        CfUtils.SetActive(self.LeftPanel, false)
    --双人开始
    elseif state == HouseState.ReadySuc then
        CfUtils.SetActive(self.LeftPanel, false)
    end
    CfUtils.SetActive(self.Before, false)
    CfUtils.SetActive(self.After, true)

    CfUtils.SetActive(self.TitleGroup, false)
    CfUtils.SetActive(self.BtnChat, false)
    CfUtils.SetActive(self.LeftGroup, false)
    CfUtils.SetActive(self.RightGroup, false)
    CfUtils.SetActive(self.TxtTime2, false)
    CfUtils.SetActive(self.LoadingGroup, true)
    CfUtils.SetActive(self.LoadingGroup2, true)
    local scr = CfUtils.GetLuaScr(self.PlayerGroup2, "Game.UI.FightReady.UIMainChapter.ActionTeamDestoryDialog.UIActionTeamDestoryNode")
    if scr then
        scr:FillLoad()
    end

    local scr = CfUtils.GetLuaScr(self.PlayerGroup, "Game.UI.FightReady.UIMainChapter.ActionTeamDestoryDialog.UIActionTeamDestoryNode")
    if scr then
        scr:FillLoad()
    end

    if not isNull(self._timeDown) then
        CDTimerModule.GetInstance():RemoveCD(self._timeDown)
        self._timeDown = nil
    end
end

function UIActionTeamDestoryDialog:OnLoading(data)
    data = checkTable(data)
    if checkNumber(data.type) == 1 then   --自己
        self.ImgLoad2.fillAmount = checkNumber(data.num)
        CfUtils.FillText(self.TxtNum2, data.num)
    else
        self.ImgLoad.fillAmount = checkNumber(data.num)
        CfUtils.FillText(self.TxtNum, data.num)
    end
end

function UIActionTeamDestoryDialog:SetStateEnterBattle(state)
    self._enterBattle = state
end

function UIActionTeamDestoryDialog:OnAppQuit()
    RegionQuestMgr:GetInstance():QuitReq()
end

function UIActionTeamDestoryDialog:UpdateResources()
    if isNotNull(self.comp) then
        CfUtils.RefreshTopGoods(self.comp:GetResources())
    end
end

return UIActionTeamDestoryDialog
