return {
  unitList = {
    {
      Rotate = -90.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = false,
      Camp = 4,
      UnitID = 20103001,
      InitPos = "M1",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_10459_0",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = -90.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = false,
      Camp = 4,
      UnitID = 20103001,
      InitPos = "M2",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_10459_1",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = -90.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = false,
      Camp = 4,
      UnitID = 20103001,
      InitPos = "M3",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_10459_2",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = -90.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = false,
      Camp = 4,
      UnitID = 20103001,
      InitPos = "M4",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_10459_3",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 0
    }
  },
  Name = "",
  Id = 10459,
  Type = 0
}
