return {
  unitList = {
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20101501,
      InitPos = "M1",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_21012102_0",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20101501,
      InitPos = "M2",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_21012102_1",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20101501,
      InitPos = "M3",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_21012102_2",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20101401,
      InitPos = "M4",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_21012102_3",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20101401,
      InitPos = "M5",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_21012102_4",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20101401,
      InitPos = "M6",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_21012102_5",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 0
    }
  },
  Name = "",
  Id = 21012102,
  Type = 0
}
