return {
  unitList = {
    {
      Rotate = 180.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = false,
      Camp = 4,
      UnitID = 2010120100,
      InitPos = "M3",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_21231_0",
      AutoLevel = 2,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 180.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = false,
      Camp = 4,
      UnitID = 20102901,
      InitPos = "M1",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_21231_1",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 180.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = false,
      Camp = 4,
      UnitID = 20102901,
      InitPos = "M2",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_21231_2",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 0
    }
  },
  Name = "",
  Id = 21231,
  Type = 0
}
