return {
  unitList = {
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20104401,
      InitPos = "M1",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_600543_0",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20103701,
      InitPos = "M2",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_600543_1",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20104301,
      InitPos = "M3",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_600543_2",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20103701,
      InitPos = "M4",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_600543_3",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20103701,
      InitPos = "M5",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_600543_4",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20104401,
      InitPos = "M6",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_600543_5",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20304602,
      InitPos = "E2",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_600543_6",
      AutoLevel = 2,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20104104,
      InitPos = "E3",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_600543_7",
      AutoLevel = 2,
      Delay = 0.0,
      MagicId = 0
    }
  },
  Name = "",
  Id = 600543,
  Type = 0
}
