return {
  unitList = {
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20103001,
      InitPos = "M5",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_601602_0",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 5000001
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20103001,
      InitPos = "M7",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_601602_1",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 5000001
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20103001,
      InitPos = "M11",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_601602_2",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 5000001
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20103001,
      InitPos = "M12",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_601602_3",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 5000001
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20102806,
      InitPos = "center",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_601602_4",
      AutoLevel = 2,
      Delay = 0.0,
      MagicId = 5000002
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20103001,
      InitPos = "M6",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_601602_5",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 5000001
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20103001,
      InitPos = "M8",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_601602_6",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 5000001
    }
  },
  Name = "",
  Id = 601602,
  Type = 0
}
