return {
  unitList = {
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = false,
      Camp = 2,
      UnitID = 3001040,
      InitPos = "npc1",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_6020301_0",
      AutoLevel = 0,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = false,
      Camp = 2,
      UnitID = 3001048,
      InitPos = "npc2",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_6020301_1",
      AutoLevel = 0,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = false,
      Camp = 2,
      UnitID = 3001049,
      InitPos = "npc3",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_6020301_2",
      AutoLevel = 0,
      Delay = 0.0,
      MagicId = 0
    }
  },
  Name = "",
  Id = 6020301,
  Type = 0
}
