return {
  unitList = {
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20103701,
      InitPos = "M1",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_7030603_0",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 5000001
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20104105,
      InitPos = "M5",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_7030603_1",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 5000002
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20103701,
      InitPos = "M3",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_7030603_2",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 5000001
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20103701,
      InitPos = "M4",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_7030603_3",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 5000001
    }
  },
  Name = "",
  Id = 7030603,
  Type = 0
}
