return {
  [1001001] = {
    {
      Id = 1001001,
      Lv = 1,
      attack = 5,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.38,
      hp = 88.82,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001001,
      Lv = 2,
      attack = 5.63,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.8,
      hp = 99.92,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001001,
      Lv = 3,
      attack = 6.25,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.23,
      hp = 111.02,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001001,
      Lv = 4,
      attack = 7.5,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.07,
      hp = 133.23,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001001,
      Lv = 5,
      attack = 8.75,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.92,
      hp = 155.43,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001001,
      Lv = 6,
      attack = 10,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.76,
      hp = 177.63,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001002] = {
    {
      Id = 1001002,
      Lv = 1,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001002,
      Lv = 2,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001002,
      Lv = 3,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001002,
      Lv = 4,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001002,
      Lv = 5,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001002,
      Lv = 6,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001003] = {
    {
      Id = 1001003,
      Lv = 1,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001003,
      Lv = 2,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001003,
      Lv = 3,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001003,
      Lv = 4,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001003,
      Lv = 5,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001003,
      Lv = 6,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001004] = {
    {
      Id = 1001004,
      Lv = 1,
      attack = 6.64,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.32,
      hp = 88.03,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001004,
      Lv = 2,
      attack = 7.46,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.74,
      hp = 99.03,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001004,
      Lv = 3,
      attack = 8.29,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.15,
      hp = 110.03,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001004,
      Lv = 4,
      attack = 9.95,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.99,
      hp = 132.04,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001004,
      Lv = 5,
      attack = 11.61,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.82,
      hp = 154.05,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001004,
      Lv = 6,
      attack = 13.27,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.65,
      hp = 176.05,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001005] = {
    {
      Id = 1001005,
      Lv = 1,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001005,
      Lv = 2,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001005,
      Lv = 3,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001005,
      Lv = 4,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001005,
      Lv = 5,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001005,
      Lv = 6,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001006] = {
    {
      Id = 1001006,
      Lv = 1,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001006,
      Lv = 2,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001006,
      Lv = 3,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001006,
      Lv = 4,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001006,
      Lv = 5,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001006,
      Lv = 6,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001007] = {
    {
      Id = 1001007,
      Lv = 1,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001007,
      Lv = 2,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001007,
      Lv = 3,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001007,
      Lv = 4,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001007,
      Lv = 5,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001007,
      Lv = 6,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001008] = {
    {
      Id = 1001008,
      Lv = 1,
      attack = 9.63,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.36,
      hp = 88.38,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001008,
      Lv = 2,
      attack = 10.83,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.78,
      hp = 99.43,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001008,
      Lv = 3,
      attack = 12.03,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.2,
      hp = 110.47,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001008,
      Lv = 4,
      attack = 14.44,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.04,
      hp = 132.57,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001008,
      Lv = 5,
      attack = 16.84,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.88,
      hp = 154.66,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001008,
      Lv = 6,
      attack = 19.25,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.72,
      hp = 176.75,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001009] = {
    {
      Id = 1001009,
      Lv = 1,
      attack = 9.73,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.32,
      hp = 89.35,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001009,
      Lv = 2,
      attack = 10.95,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.74,
      hp = 100.51,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001009,
      Lv = 3,
      attack = 12.16,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.15,
      hp = 111.68,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001009,
      Lv = 4,
      attack = 14.6,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.99,
      hp = 134.02,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001009,
      Lv = 5,
      attack = 17.03,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.82,
      hp = 156.35,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001009,
      Lv = 6,
      attack = 19.46,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.65,
      hp = 178.69,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001010] = {
    {
      Id = 1001010,
      Lv = 1,
      attack = 4.99,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.39,
      hp = 92.34,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001010,
      Lv = 2,
      attack = 5.62,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.81,
      hp = 103.88,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001010,
      Lv = 3,
      attack = 6.24,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.23,
      hp = 115.42,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001010,
      Lv = 4,
      attack = 7.49,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.08,
      hp = 138.5,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001010,
      Lv = 5,
      attack = 8.74,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.92,
      hp = 161.59,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001010,
      Lv = 6,
      attack = 9.99,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.77,
      hp = 184.67,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001011] = {
    {
      Id = 1001011,
      Lv = 1,
      attack = 3.49,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.37,
      hp = 87.5,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001011,
      Lv = 2,
      attack = 3.92,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.8,
      hp = 98.44,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001011,
      Lv = 3,
      attack = 4.36,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.22,
      hp = 109.37,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001011,
      Lv = 4,
      attack = 5.23,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.06,
      hp = 131.25,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001011,
      Lv = 5,
      attack = 6.1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.9,
      hp = 153.12,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001011,
      Lv = 6,
      attack = 6.97,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.75,
      hp = 175,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001012] = {
    {
      Id = 1001012,
      Lv = 1,
      attack = 9.99,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.23,
      hp = 87.15,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001012,
      Lv = 2,
      attack = 11.24,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.64,
      hp = 98.04,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001012,
      Lv = 3,
      attack = 12.49,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.04,
      hp = 108.93,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001012,
      Lv = 4,
      attack = 14.99,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.85,
      hp = 130.72,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001012,
      Lv = 5,
      attack = 17.48,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.66,
      hp = 152.51,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001012,
      Lv = 6,
      attack = 19.98,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.47,
      hp = 174.29,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001013] = {
    {
      Id = 1001013,
      Lv = 1,
      attack = 5,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.38,
      hp = 86.18,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001013,
      Lv = 2,
      attack = 5.62,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.81,
      hp = 96.95,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001013,
      Lv = 3,
      attack = 6.25,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.23,
      hp = 107.72,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001013,
      Lv = 4,
      attack = 7.49,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.08,
      hp = 129.27,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001013,
      Lv = 5,
      attack = 8.74,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.92,
      hp = 150.81,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001013,
      Lv = 6,
      attack = 9.99,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.77,
      hp = 172.36,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001014] = {
    {
      Id = 1001014,
      Lv = 1,
      attack = 6.07,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.29,
      hp = 86.97,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001014,
      Lv = 2,
      attack = 6.83,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.7,
      hp = 97.84,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001014,
      Lv = 3,
      attack = 7.59,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.12,
      hp = 108.71,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001014,
      Lv = 4,
      attack = 9.1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.94,
      hp = 130.46,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001014,
      Lv = 5,
      attack = 10.62,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.76,
      hp = 152.2,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001014,
      Lv = 6,
      attack = 12.14,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.59,
      hp = 173.94,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001015] = {
    {
      Id = 1001015,
      Lv = 1,
      attack = 6.56,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.36,
      hp = 90.22,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001015,
      Lv = 2,
      attack = 7.38,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.78,
      hp = 101.5,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001015,
      Lv = 3,
      attack = 8.2,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.2,
      hp = 112.78,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001015,
      Lv = 4,
      attack = 9.83,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.05,
      hp = 135.34,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001015,
      Lv = 5,
      attack = 11.47,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.89,
      hp = 157.89,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001015,
      Lv = 6,
      attack = 13.11,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.73,
      hp = 180.45,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001016] = {
    {
      Id = 1001016,
      Lv = 1,
      attack = 6.03,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.31,
      hp = 88.55,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001016,
      Lv = 2,
      attack = 6.79,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.73,
      hp = 99.62,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001016,
      Lv = 3,
      attack = 7.54,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.14,
      hp = 110.69,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001016,
      Lv = 4,
      attack = 9.05,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.97,
      hp = 132.83,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001016,
      Lv = 5,
      attack = 10.56,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.8,
      hp = 154.97,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001016,
      Lv = 6,
      attack = 12.07,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.63,
      hp = 177.11,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001017] = {
    {
      Id = 1001017,
      Lv = 1,
      attack = 6.02,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.32,
      hp = 87.41,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001017,
      Lv = 2,
      attack = 6.77,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.74,
      hp = 98.34,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001017,
      Lv = 3,
      attack = 7.53,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.15,
      hp = 109.26,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001017,
      Lv = 4,
      attack = 9.03,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.98,
      hp = 131.12,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001017,
      Lv = 5,
      attack = 10.54,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.81,
      hp = 152.97,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001017,
      Lv = 6,
      attack = 12.04,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.64,
      hp = 174.82,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001018] = {
    {
      Id = 1001018,
      Lv = 1,
      attack = 3.49,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.37,
      hp = 87.59,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001018,
      Lv = 2,
      attack = 3.93,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.79,
      hp = 98.53,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001018,
      Lv = 3,
      attack = 4.36,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.21,
      hp = 109.48,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001018,
      Lv = 4,
      attack = 5.23,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.06,
      hp = 131.38,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001018,
      Lv = 5,
      attack = 6.11,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.9,
      hp = 153.28,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001018,
      Lv = 6,
      attack = 6.98,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.74,
      hp = 175.17,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001019] = {
    {
      Id = 1001019,
      Lv = 1,
      attack = 5.03,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.36,
      hp = 93.21,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001019,
      Lv = 2,
      attack = 5.66,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.78,
      hp = 104.87,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001019,
      Lv = 3,
      attack = 6.29,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.2,
      hp = 116.52,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001019,
      Lv = 4,
      attack = 7.55,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.04,
      hp = 139.82,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001019,
      Lv = 5,
      attack = 8.81,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.88,
      hp = 163.12,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001019,
      Lv = 6,
      attack = 10.06,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.72,
      hp = 186.43,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001020] = {
    {
      Id = 1001020,
      Lv = 1,
      attack = 6.55,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.37,
      hp = 88.64,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001020,
      Lv = 2,
      attack = 7.37,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.79,
      hp = 99.72,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001020,
      Lv = 3,
      attack = 8.19,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.21,
      hp = 110.8,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001020,
      Lv = 4,
      attack = 9.82,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.05,
      hp = 132.96,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001020,
      Lv = 5,
      attack = 11.46,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.89,
      hp = 155.12,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001020,
      Lv = 6,
      attack = 13.1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.73,
      hp = 177.28,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001021] = {
    {
      Id = 1001021,
      Lv = 1,
      attack = 5.01,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.38,
      hp = 87.06,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001021,
      Lv = 2,
      attack = 5.63,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.8,
      hp = 97.94,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001021,
      Lv = 3,
      attack = 6.26,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.22,
      hp = 108.82,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001021,
      Lv = 4,
      attack = 7.51,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.07,
      hp = 130.59,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001021,
      Lv = 5,
      attack = 8.76,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.91,
      hp = 152.35,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001021,
      Lv = 6,
      attack = 10.01,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.75,
      hp = 174.12,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001022] = {
    {
      Id = 1001022,
      Lv = 1,
      attack = 9.96,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.24,
      hp = 88.91,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001022,
      Lv = 2,
      attack = 11.21,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.65,
      hp = 100.02,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001022,
      Lv = 3,
      attack = 12.45,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.05,
      hp = 111.13,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001022,
      Lv = 4,
      attack = 14.94,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.86,
      hp = 133.36,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001022,
      Lv = 5,
      attack = 17.43,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.67,
      hp = 155.58,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001022,
      Lv = 6,
      attack = 19.92,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.49,
      hp = 177.81,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001023] = {
    {
      Id = 1001023,
      Lv = 1,
      attack = 6.19,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.23,
      hp = 88.99,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001023,
      Lv = 2,
      attack = 6.96,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.63,
      hp = 100.12,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001023,
      Lv = 3,
      attack = 7.74,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.03,
      hp = 111.24,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001023,
      Lv = 4,
      attack = 9.28,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.84,
      hp = 133.49,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001023,
      Lv = 5,
      attack = 10.83,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.65,
      hp = 155.74,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001023,
      Lv = 6,
      attack = 12.38,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.45,
      hp = 177.99,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001024] = {
    {
      Id = 1001024,
      Lv = 1,
      attack = 10.02,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.22,
      hp = 87.76,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001024,
      Lv = 2,
      attack = 11.27,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.63,
      hp = 98.73,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001024,
      Lv = 3,
      attack = 12.52,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.03,
      hp = 109.7,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001024,
      Lv = 4,
      attack = 15.03,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.83,
      hp = 131.64,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001024,
      Lv = 5,
      attack = 17.54,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.64,
      hp = 153.58,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001024,
      Lv = 6,
      attack = 20.04,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.44,
      hp = 175.52,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001025] = {
    {
      Id = 1001025,
      Lv = 1,
      attack = 6.59,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.54,
      hp = 95.33,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001025,
      Lv = 2,
      attack = 7.05,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.78,
      hp = 101.88,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001025,
      Lv = 3,
      attack = 7.83,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.21,
      hp = 113.2,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001025,
      Lv = 4,
      attack = 9.39,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.05,
      hp = 135.84,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001025,
      Lv = 5,
      attack = 10.96,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.89,
      hp = 158.48,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001025,
      Lv = 6,
      attack = 12.53,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.73,
      hp = 181.13,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001026] = {
    {
      Id = 1001026,
      Lv = 1,
      attack = 10.72,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.64,
      hp = 92.95,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001026,
      Lv = 2,
      attack = 11.45,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.89,
      hp = 99.34,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001026,
      Lv = 3,
      attack = 12.72,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.32,
      hp = 110.37,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001026,
      Lv = 4,
      attack = 15.27,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.18,
      hp = 132.45,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001026,
      Lv = 5,
      attack = 17.81,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.05,
      hp = 154.52,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001026,
      Lv = 6,
      attack = 20.36,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.91,
      hp = 176.6,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001027] = {
    {
      Id = 1001027,
      Lv = 1,
      attack = 6.43,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.8,
      hp = 91.52,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001027,
      Lv = 2,
      attack = 6.88,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.06,
      hp = 97.81,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001027,
      Lv = 3,
      attack = 7.64,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.51,
      hp = 108.68,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001027,
      Lv = 4,
      attack = 9.17,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.42,
      hp = 130.41,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001027,
      Lv = 5,
      attack = 10.7,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.32,
      hp = 152.15,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001027,
      Lv = 6,
      attack = 12.23,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 7.22,
      hp = 173.88,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001028] = {
    {
      Id = 1001028,
      Lv = 1,
      attack = 6.09,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.84,
      hp = 99.33,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001028,
      Lv = 2,
      attack = 6.5,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.1,
      hp = 106.16,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001028,
      Lv = 3,
      attack = 7.23,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.56,
      hp = 117.96,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001028,
      Lv = 4,
      attack = 8.67,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.47,
      hp = 141.55,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001028,
      Lv = 5,
      attack = 10.12,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.38,
      hp = 165.14,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001028,
      Lv = 6,
      attack = 11.56,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 7.29,
      hp = 188.73,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001029] = {
    {
      Id = 1001029,
      Lv = 1,
      attack = 3.62,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.8,
      hp = 100.1,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001029,
      Lv = 2,
      attack = 3.87,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.06,
      hp = 106.98,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001029,
      Lv = 3,
      attack = 4.3,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.51,
      hp = 118.86,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001029,
      Lv = 4,
      attack = 5.15,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.42,
      hp = 142.64,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001029,
      Lv = 5,
      attack = 6.01,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.32,
      hp = 166.41,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001029,
      Lv = 6,
      attack = 6.87,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 7.22,
      hp = 190.18,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001030] = {
    {
      Id = 1001030,
      Lv = 1,
      attack = 5,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.38,
      hp = 88.82,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001030,
      Lv = 2,
      attack = 5.63,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 3.8,
      hp = 99.92,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001030,
      Lv = 3,
      attack = 6.25,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 4.23,
      hp = 111.02,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001030,
      Lv = 4,
      attack = 7.5,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.07,
      hp = 133.23,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001030,
      Lv = 5,
      attack = 8.75,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 5.92,
      hp = 155.43,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001030,
      Lv = 6,
      attack = 10,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 6.76,
      hp = 177.63,
      penetrate = 0,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  },
  [1001099] = {
    {
      Id = 1001099,
      Lv = 1,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001099,
      Lv = 2,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001099,
      Lv = 3,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001099,
      Lv = 4,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001099,
      Lv = 5,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    },
    {
      Id = 1001099,
      Lv = 6,
      attack = 1,
      crit_atk_per = 0,
      crit_def_per = 0,
      crit_dmg_atk_per = 0,
      crit_dmg_def_per = 0,
      defense = 1,
      hp = 1,
      penetrate = 1,
      team_skill_energy = 0,
      team_skill_energy_max = 0
    }
  }
}
