local config = {
  str_n32_multiline_dialogue_desc = "Roadside Glimpse",
  str_n32_multiline_petfile_reward_title = "Reward for Unlocking All Past Events",
  str_n32_multiline_dialogue_reward_title = "Encounter Rewards",
  str_n32_multiline_dialogue_reward_obtained = "Received",
  str_n32_multiline_dialogue_enter_btn = "View",
  str_n32_multiline_dialogue_skip_btn = "Leave",
  str_n32_multiline_dialogue_skip_popup = "Leave this encounter?",
  str_n32_multiline_dialogue_cancel_btn = "Leave",
  str_n32_multiline_dialogue_reply_title = "I choose to...",
  str_n32_multiline_story_review = "Past Events",
  str_n32_multiline_know = "Okay.",
  str_n32_multiline_branch_tips = [[
{1}, slow down!
My crystal ball is telling me that we passed by <color=#f16a4b>{2}</color> place(s) that are worth checking out... I wonder what's there?
Should we go back and find out?]],
  str_n32_multiline_day = "{1}d",
  str_n32_multiline_hour = "{1}h",
  str_n32_multiline_minus = "{1} min",
  str_n32_multiline_less_one_minus = "<1 min",
  str_n32_multiline_activity_remain_time = "Event Ends In: {1}",
  str_n32_multiline_unlock_pet_title = "Unlocked Past Events",
  str_n32_multiline_lock_pet_title = "Missing Past Events",
  str_n32_multiline_1_name = "Mansion Garden",
  str_n32_multiline_2_name = "Mansion Hall",
  str_n32_multiline_3_name = "Center Square",
  str_n32_multiline_4_name = "Square Environs",
  str_n32_multiline_5_name = "Mansion Garden",
  str_n32_multiline_6_name = "Mansion Hall",
  str_n32_multiline_7_name = "Square Environs",
  str_n32_multiline_8_name = "Center Square",
  str_n32_multiline_9_name = "Mansion Study",
  str_n32_multiline_10_name = "Uptown Streets",
  str_n32_multiline_11_name = "Mansion Garden",
  str_n32_multiline_12_name = "Uptown Streets",
  str_n32_multiline_13_name = "Square Environs",
  str_n32_multiline_14_name = "Mansion Study",
  str_n32_multiline_15_name = "Mansion Hall",
  str_n32_multiline_16_name = "Broken Void",
  str_n32_multiline_17_name = "Outside the Gates",
  str_n32_multiline_18_name = "Montague",
  str_n32_multiline_19_name = "Red-Haired Girl",
  str_n32_multiline_20_name = "Miss Roshee",
  str_n32_multiline_21_name = "Letter Stationery",
  str_n32_multiline_22_name = "It's Not You",
  str_n32_multiline_23_name = "House Montague",
  str_n32_multiline_24_name = "Prophecy",
  str_n32_multiline_1_name_desc = "Joshua transforms into a monster and attacks you. Jakine hastily launches a spell to teleport everyone out of the Crystal of Eternal Memory, and when you come to your senses...",
  str_n32_multiline_2_name_desc = "—",
  str_n32_multiline_3_name_desc = "You split up to take two separate paths, according to the plan, and wait for the Dark Angel to appear. However, things are hardly ever that simple now, are they?",
  str_n32_multiline_4_name_desc = "A pitch-black dragon and the eerie rebel army... A good show is about to begin.",
  str_n32_multiline_5_name_desc = "Time flows backward again, the old memories and new obstacles await your arrival.",
  str_n32_multiline_6_name_desc = "Your party meets with Lady Joshua again, but the story takes an unexpected turn without you around.",
  str_n32_multiline_7_name_desc = "As Schwartz takes on the Dark Angel in a one-on-one battle, the rebellion is set to begin, and the dragon is ready to take flight, this time...",
  str_n32_multiline_8_name_desc = "This time, Mia survives. Would anyone else be so lucky?",
  str_n32_multiline_9_name_desc = "—",
  str_n32_multiline_10_name_desc = "Tragedy still finds a way to strike, but you don't have time to stop and rest.",
  str_n32_multiline_11_name_desc = "The plan for the last journey back in time has been made. Now, a race against time begins.",
  str_n32_multiline_12_name_desc = "You locate the Dark Angel, but appeasing her may be harder than expected...",
  str_n32_multiline_13_name_desc = "The flapping of a butterfly's wings can trigger a hurricane. Soon, all of your pieces will be aligned.",
  str_n32_multiline_14_name_desc = "—",
  str_n32_multiline_15_name_desc = "Only the White Queen remains on the board, and she's staking it all on one last desperate move.",
  str_n32_multiline_16_name_desc = "—",
  str_n32_multiline_17_name_desc = "Invited into the grand hall of Schwartz Mansion, you hear someone talking on the other side of a door.",
  str_n32_multiline_18_name_desc = "As you prepare to leave Schwartz Mansion, you find a pile of burnt letters in the middle of a grassy area in the back garden...",
  str_n32_multiline_19_name_desc = "On a small road leading to Schwartz Mansion, a red-haired girl suddenly blocks Sharona's path.",
  str_n32_multiline_20_name_desc = "Hiding near the center square, you inadvertently overhear a conversation between two old friends.",
  str_n32_multiline_21_name_desc = "On a street in Uptown, two seemingly unrelated people are talking about something warranting your attention...",
  str_n32_multiline_22_name_desc = "On a small road leading to Schwartz Mansion, a tall tower collapses with a crash...",
  str_n32_multiline_23_name_desc = "Amid the chaos, you discover two nobles trapped on the spot.",
  str_n32_multiline_24_name_desc = "On a small road leading to Schwartz Mansion, a tall tower has collapsed...",
  str_n32_multiline_1_name_desc_long = "Jakine has failed. You cannot leave the Crystal of Eternal Memory, but successfully trace time back to before the parade began. Joshua, who has become a monster known as the Dark Angel, attacks you once again. After fighting her off, you try to leave, despite your mounting hopelessness, but still make no progress. At this moment, another Joshua appears.",
  str_n32_multiline_2_name_desc_long = "Joshua explains the whole story to you. It turns out that Joshua never died, but had confined herself and the uncontrollable personality that splintered off from her seed to the Crystal of Eternal Memory. In order to save Joshua and leave this place, you make a plan to suppress the Dark Angel.",
  str_n32_multiline_3_name_desc_long = "You split up into two groups according to the plan. Mia arrives at the stands, while the others successfully lure the Dark Angel out. Things seem to be going perfectly when the rebellion begins early for unknown reasons. Strange enemies and a stranger-looking dragon attack the stands, plunging your plan into chaos.",
  str_n32_multiline_4_name_desc_long = "You defeat the Dark Angel, but the situation around you plummets deeper into despair by the second. Rebel forces, a flying dragon, and a rising mania continuously spreads throughout the crowd, even transforming Joshua's face into an unrecognizable picture of ferocity. Your companions are devoured by the maw of corruption, one after another, and just as you sink into despair, Jakine casts the time travel spell once again...",
  str_n32_multiline_5_name_desc_long = "Time flows backward, and everyone in the garden is once again engaged in battle with the Dark Angel. Only you are still being pursued by the guards with their eerie expressions... What is really going on here? As you hide, clinging to dear life, you become lost in contemplation.",
  str_n32_multiline_6_name_desc_long = "Similar to the first time you traveled back in time, everyone meets Joshua again, but this time, it seems that Schwartz and Joshua are at odds. For this reason, Caleb is left standing by Jakine's side, and Schwartz faces the Dark Angel alone.",
  str_n32_multiline_7_name_desc_long = "In the ensuing one-on-one battle, Schwartz and the Dark Angel are evenly matched, but the Dark Angel suddenly speaks with Joshua's voice, condemning Schwartz's irresponsible behavior toward his family. At the same time, the rebellion begins, and you realize you must seize the opportunity to regroup with the others. However, it is at this moment that you witness the Dark Angel stopping the dragon from attacking the stands.",
  str_n32_multiline_8_name_desc_long = "This time, Mia survives. However, young Carleen is affected due to an injury, and chooses to take her own life to protect her family. Mia's spirit is about to break down under the situation, at such moment, the dying Dark Angel takes Mia into her arms and holds her tightly. It is at this moment that Schwartz becomes convinced that the Dark Angel is in fact his wife.",
  str_n32_multiline_9_name_desc_long = "In the mansion, Joshua explains the truth to Caleb. It turns out that Joshua is an assassin of Schwartz's opposing faction, and not Caleb's biological sister. She tries to persuade Caleb to help her eliminate the others, and although Caleb doesn't doubt Joshua's identity, he is unwilling to assist her and is ultimately killed by Joshua.",
  str_n32_multiline_10_name_desc_long = "You and Mia arrive at the mansion to find the residence in utter chaos, and with the help of Ms. Rot, you manage to escape with Jakine. You roughly clarify the truth of the matter by organizing the intelligence obtained through the two-time travel excursions—this journey back in time will be your last opportunity.",
  str_n32_multiline_11_name_desc_long = "You evade your pursuers as planned, and come before Joshua as scheduled. A new game of chess is about to begin.",
  str_n32_multiline_12_name_desc_long = "You try to placate the Dark Angel by singing the song she sang to Mia. This reminds the Dark Angel of her past, where the assassination attempt failed and she was won over by the young Schwartz... Her memories are vivid, making it even more difficult for her to forgive Schwartz.",
  str_n32_multiline_13_name_desc_long = "Schwartz does not get to see the Dark Angel but encounters the soldiers chasing you. You guide everyone to the stands before the dragon attacks and manage to fight it off. Mia has also consoled the Dark Angel, while Ms. Rot stays with Joshua, and things take a dramatic change for the better.",
  str_n32_multiline_14_name_desc_long = "The truth may be difficult to accept, but to continue moving forward, we must learn to face it all. Caleb, Schwartz, the Dark Angel, Mia, and Ms. Rot... As the final battle approaches, everyone has their own truths firmly engraved in their hearts.",
  str_n32_multiline_15_name_desc_long = "You fight a decisive battle against the White Demon and push her to the brink of defeat. The White Demon intends to drag you into the grave with her, while the Dark Angel chooses to face the White Demon alone after reconciling with her family. The two divided selves finally meet again.",
  str_n32_multiline_16_name_desc_long = "You successfully leave the Crystal of Eternal Memory after saving Joshua. However, Joshua seems to have lost all of her memories and chooses to embark on a new journey alone. When it is difficult to face the present, people often choose to immerse themselves in the past as a means of escape. Only when people regain the courage to live can we move toward a new future.",
  str_n32_multiline_17_name_desc_long = "—",
  str_n32_multiline_18_name_desc_long = "—",
  str_n32_multiline_19_name_desc_long = "—",
  str_n32_multiline_20_name_desc_long = "—",
  str_n32_multiline_21_name_desc_long = "—",
  str_n32_multiline_22_name_desc_long = "—",
  str_n32_multiline_23_name_desc_long = "—",
  str_n32_multiline_24_name_desc_long = "—",
  str_n32_multiline_doc_lock = "Let's venture forward boldly. Maybe we'll have some unexpected encounters along the way.",
  str_n32_multiline_doc_role_1 = "Ms. Blanc",
  str_n32_multiline_doc_role_2 = "Joshua",
  str_n32_multiline_doc_role_3 = "Sharona",
  str_n32_multiline_doc_role_4 = "Otto",
  str_n32_multiline_doc_roledesc_1 = "The former Captain of the Nightwatch, whose age is a mystery.\nShe was injured and retreated during the Battle of Umbraton in Morning Calendar Year 1988 after being besieged by the Darkover, and later became an elegant tour guide.\nTo this day, legends of her former identity—Ms. Rot, a bringer of death and destruction—still linger in the hushed corners of Lumopolis...",
  str_n32_multiline_doc_roledesc_2 = [[
The daughter of a renowned scholar and the "late wife" of the City Lord. Back then, under immense pressure, she fell in love with and married Schwartz. However, her father did not get to see her wedding day, as he died in a fire.
In Morning Calendar 1992, it was officially announced that Joshua had passed away due to illness.]],
  str_n32_multiline_doc_roledesc_3 = "Born in Lumopolis, she was informed at a young age that her parents had both passed away and was taken into the care of the elders of the Kartima family. In Morning Calendar 1988, the Kartima family became wanted by Lumopolis for instigating a coup, and Sharona luckily managed to escape from the city. She later joined the coalition forces to take part in a counterattack against the Darkover, and eventually became Illumina Legion Commander.",
  str_n32_multiline_doc_roledesc_4 = "Born into the powerful Troy family, whose main sphere of influence is the Elder Council. After the previous City Lord was murdered, rumors began to point the finger at the Troy family, but these rumors quickly dissipated. He had planned to train his niece as his successor, however, she was later officially registered as deceased.",
  str_n32_multiline_doc_name_1 = "Ms. Blanc's Background",
  str_n32_multiline_doc_name_2 = "Letter to the Montagues",
  str_n32_multiline_doc_name_3 = "The Red-Haired Girl's Tale",
  str_n32_multiline_doc_name_4 = "Roshee Returns to the Righteous Path",
  str_n32_multiline_doc_name_5 = "The Burning Letter",
  str_n32_multiline_doc_name_6 = "The Red-Haired Girl and the Elder",
  str_n32_multiline_doc_name_7 = "House Montague",
  str_n32_multiline_doc_name_8 = "Maiden of Prophecy",
  str_n32_multiline_doc_tips_1 = "Past Events   Ms. Blanc's Background   Unlocked",
  str_n32_multiline_doc_tips_2 = "Past Events   Letter to the Montagues   Unlocked",
  str_n32_multiline_doc_tips_3 = "Past Events   The Red-haired Girl's Tale   Unlocked",
  str_n32_multiline_doc_tips_4 = "Past Events   Roshee Returns to the Righteous Path   Unlocked",
  str_n32_multiline_doc_tips_5 = "Past Events   The Burning Letter   Unlocked",
  str_n32_multiline_doc_tips_6 = "Past Events   The Red-haired Girl and the Elder   Unlocked",
  str_n32_multiline_doc_tips_7 = "Past Events   House Montague   Unlocked",
  str_n32_multiline_doc_tips_8 = "Past Events   Maiden of Prophecy   Unlocked",
  str_n32_multiline_doc_desc_1 = "Ms. Blanc is a distant relative of Lady Joshua, however, the two of them are not related by blood. Ms. Blanc showed astonishing talent from a young age, but suffered the frustration of having nowhere to put her ability to good use. Faced with the mixed blessing of having a gifted child, her parents had no choice but to place her in the hands of Caleb, but it was after this that she unexpectedly met Lady Joshua. The two of them hit it off, establishing a strong rapport and engaging in animated conversation from their first meeting. As a result, Joshua taught Ms. Blanc for many years.",
  str_n32_multiline_doc_desc_2 = "In a pile of burnt letters lies hidden a letter for the Child of the Montagues, penned by Caleb's father. In the letter, Caleb's father seems to have made a resolution of sorts, offering sincere wishes to the recipient.",
  str_n32_multiline_doc_desc_3 = "A mother with Dragonkin awakened had given birth to two daughters. Her heritage made her lose control and she was put to death by her family. To protect her dragon about to hatch, the older daughter chose to wander until settling in Umbraton. The younger daughter grew up not knowing her mother was killed by her tribe.",
  str_n32_multiline_doc_desc_4 = "Although Otto has no children of his own, he has always treated his niece Roshee, who later became one of the Four Angels, Michael, as if she were his own daughter. When she was younger, Roshee used to enjoy wandering the alleys and streets, catching thieves and other assorted villains, but under Otto's guidance, she gradually turned her mind to greater things. In Morning Calendar Year 1988, Roshee suddenly ran away from home without the slightest warning.",
  str_n32_multiline_doc_desc_5 = "The reason Otto's niece, Roshee, ran away from home was that she received a note listing all the evidence indicating that her uncle Otto was the one who placed Eclipsites in Lumopolis a year prior and instigated the uprising. Roshee couldn't accept this to be true, yet she knew it was something her uncle was capable of. Therefore, Roshee left a letter for her friend Sharona, and she decided to stay away from her family and join the expeditionary force...",
  str_n32_multiline_doc_desc_6 = "The red-haired girl brought down a tall tower in which an elder of the Kartima family was imprisoned for going against Mime. To the surprise of the red-haired girl, the elder said the same thing her mother had said, \"You are not the one who will save the Kartima family.\" The red-haired girl knew that the elder had been waiting for her sister Sharona, but she felt that such things no longer mattered to her.",
  str_n32_multiline_doc_desc_7 = "Pyrrhus, Gautier... Montague. These are the names of the houses that rebelled against the Schwartz family—names that were eventually lost to time. Hatred blinded the survivors, making them the ideal pawns for would-be conspirators.",
  str_n32_multiline_doc_desc_8 = "Sharona ran into the elder beside the collapsed tower. The elder told her that, according to the prophecy, Sharona was the only one who could save the Kartima family. He wished for Sharona to inherit the Azure Flame sword passed down from generation to generation by the elders of the Kartima family, and to ultimately bear the burden of securing the future glory of their bloodline.",
  str_n32_multiline_doc_lockdesc_1 = "When <color=#ffe062>Cracking</color>, listen to what the guard is saying at the entrance of the <color=#ffe062>hall of Schwartz Mansion</color>.",
  str_n32_multiline_doc_lockdesc_2 = "When <color=#ffe062>Cracking</color>, pay attention to what's under your feet on your way to the <color=#ffe062>central square</color>...",
  str_n32_multiline_doc_lockdesc_3 = "When <color=#ffe062>Cracking</color>, someone seems to be blocking your way when you're leaving the <color=#ffe062>central square</color>...",
  str_n32_multiline_doc_lockdesc_4 = "When things start <color=#ffe062>Bursting</color>, you seem to be able to hear some sounds when hiding around the <color=#ffe062>central square</color>...",
  str_n32_multiline_doc_lockdesc_5 = "When things start <color=#ffe062>Bursting</color>, look out for familiar figures when walking along the paths around the <color=#ffe062>central square</color>.",
  str_n32_multiline_doc_lockdesc_6 = "When things start <color=#ffe062>Bursting</color>, pay attention to the shapes of buildings when leaving the <color=#ffe062>central square</color>.",
  str_n32_multiline_doc_lockdesc_7 = "When things start <color=#ffe062>Collapsing</color>, point out an escape route to two nobles at the <color=#ffe062>central square</color>.",
  str_n32_multiline_doc_lockdesc_8 = "When things start <color=#ffe062>Collapsing</color>, pay attention to the collapsing tower when leaving the <color=#ffe062>central square</color>.",
  str_n32_multiline_doc_unlock_1 = "Do Ms. Blanc and Lady Joshua share such a history?!",
  str_n32_multiline_doc_unlock_2 = "How could Caleb's father have written such a letter?!",
  str_n32_multiline_doc_unlock_3 = "Is the red-haired girl's story really just a tale?",
  str_n32_multiline_doc_unlock_4 = "It seems Otto also has his unexpected weaknesses...",
  str_n32_multiline_doc_unlock_5 = "Did the niece run away from home because of what Otto did?",
  str_n32_multiline_doc_unlock_6 = "The red-haired girl is actually Sharona's biological sister, Leona?!",
  str_n32_multiline_doc_unlock_7 = "Those names now lost to time... Don't they seem familiar?",
  str_n32_multiline_doc_unlock_8 = "Sharona finally met the person who had been waiting for her...",
  str_n32_multiline_lock_tips1 = "I don't have any clues yet.",
  str_n32_multiline_lock_tips2 = "Go and search the location indicated.",
  str_n32_multiline_desc_1 = "The past has been reset. The crystal awaits your decision.",
  str_n32_multiline_desc_2 = "Keep going back and forth until you recover the truth in the destruction.",
  str_n32_multiline_desc_3 = "Find out where light and darkness end when making your final choice.",
  str_n32_multiline_desc_pass = "Embark on a journey. We'll always remember the ode sung at the city in the sky.",
  str_n32_multiline_name_1 = "Cracking",
  str_n32_multiline_name_2 = "Bursting",
  str_n32_multiline_name_3 = "Collapsing",
  str_n32_multiline_main_forlder_pass = "Current reset has ended.",
  str_n32_multiline_main_folder_unpass = "Time is being reset.",
  str_n32_multiline_branch_folder_pass = "All encounters experienced.",
  str_n32_multiline_branch_folder_unpass_normal = "There are still encounters you've <color=#fea62d>missed</color>.",
  str_n32_multiline_branch_folder_unpass_format = "You missed <color=#fea62d>{1}</color> encounter(s).",
  str_n32_multiline_dialogue_chat_title_1 = "Outside the Gates",
  str_n32_multiline_dialogue_chat_title_2 = "Montague",
  str_n32_multiline_dialogue_chat_title_3 = "Red-Haired Girl",
  str_n32_multiline_dialogue_chat_title_4 = "Miss Roshee",
  str_n32_multiline_dialogue_chat_title_5 = "Letter Stationery",
  str_n32_multiline_dialogue_chat_title_6 = "It's Not You",
  str_n32_multiline_dialogue_chat_title_7 = "House Montague",
  str_n32_multiline_dialogue_chat_title_8 = "Prophecy",
  str_n32_multiline_dialogue_chat_indesc_1 = "Outside the hall of the Schwartz mansion, a maid and a soldier are chatting.",
  str_n32_multiline_dialogue_chat_indesc_2 = "On the lush green grass, a pile of charred black paper particularly stands out.",
  str_n32_multiline_dialogue_chat_indesc_3 = "The red-haired girl stands before Sharona and speaks of some very strange things...",
  str_n32_multiline_dialogue_chat_indesc_4 = "On a quiet path, two noble-looking gentlemen are chatting.",
  str_n32_multiline_dialogue_chat_indesc_5 = "What is the connection between the red-haired girl and Duke Troy?",
  str_n32_multiline_dialogue_chat_indesc_6 = "Under the collapsed tower, the girl's red hair cannot escape the eye.",
  str_n32_multiline_dialogue_chat_indesc_7 = "Two panicked nobles attempt to understand the chaos unfolding before them.",
  str_n32_multiline_dialogue_chat_indesc_8 = "Under the collapsed tower, a girl dressed in knightly attire appears.",
  str_n32_multiline_dialogue_bigplace_1 = "Schwartz Mansion",
  str_n32_multiline_dialogue_bigplace_2 = "Schwartz Mansion",
  str_n32_multiline_dialogue_bigplace_3 = "Center Square",
  str_n32_multiline_dialogue_bigplace_4 = "Center Square",
  str_n32_multiline_dialogue_bigplace_5 = "Uptown Streets",
  str_n32_multiline_dialogue_bigplace_6 = "Kartima Mansion",
  str_n32_multiline_dialogue_bigplace_7 = "Center Square",
  str_n32_multiline_dialogue_bigplace_8 = "Kartima Mansion",
  str_n32_multiline_dialogue_bigplace_9 = "Uptown Streets",
  str_n32_multiline_dialogue_smallplace_1 = "Outside the Hall",
  str_n32_multiline_dialogue_smallplace_2 = "Garden",
  str_n32_multiline_dialogue_smallplace_3 = "Peripheral Pathway",
  str_n32_multiline_dialogue_smallplace_4 = "Peripheral Pathway",
  str_n32_multiline_dialogue_smallplace_5 = "Somewhere",
  str_n32_multiline_dialogue_smallplace_6 = "The Tower",
  str_n32_multiline_dialogue_smallplace_7 = "Entrance",
  str_n32_multiline_dialogue_smallplace_8 = "The Tower",
  str_n32_multiline_dialogue_smallplace_9 = "Near the Kartima Mansion",
  str_n32_multiline_main_intro_title = "<color=#68251b><size=55>The Divergence Gameplay Info</size></color>",
  str_n32_multiline_main_intro_head_1 = "<color=#623d33><size=34>Enter the world of the Crystal of Eternal Memory</size></color>",
  str_n32_multiline_main_intro_body_1 = "<color=#ac7655><size=28>With Jakine's help, you can go back in time and space to explore the old Lumopolis. With each attempt, you'll get closer and closer to the truth.</size></color>",
  str_n32_multiline_main_intro_head_2 = "<color=#623d33><size=34>Don't miss out on the encounters along the way</size></color>",
  str_n32_multiline_main_intro_body_2 = "<color=#ac7655><size=28>During your tense journeys, you will experience tough battles and meet different people. When you listen to their conversations, you may be able to find out past events that very few people know about and make some unexpected gains.</size></color>",
  str_n32_multiline_main_intro_head_3 = "<color=#623d33><size=34>Past Events Collection</size></color>",
  str_n32_multiline_main_intro_body_3 = "<color=#ac7655><size=28>The past events you collect during your journey will be sorted in Dossiers, where you can browse or view them at any time to find clues of other past events that you are missing.</size></color>",
  str_n32_multiline_map_intro_title = "<color=#68251b><size=55>The Divergence Gameplay Info</size></color>",
  str_n32_multiline_map_intro_head_1 = "<color=#623d33><size=34>The End of Time Travel</size></color>",
  str_n32_multiline_map_intro_body_1 = "<color=#ac7655><size=28>Although you'll travel to Lumopolis each time, you'll have different battles and encounters in each new journey, so please take each battle seriously and cherish every encounter.</size></color>",
  str_n32_multiline_map_intro_head_2 = "<color=#623d33><size=34>Journey Encounters</size></color>",
  str_n32_multiline_map_intro_body_2 = "<color=#ac7655><size=28>Cherish each encounter on your journey to record a past event that few know about. Past events will be collected in Dossiers, and you can claim a reward after collecting all past events.</size></color>"
}
return config
