---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gaole.
--- DateTime: 2020-11-07 15:46:48
---
local CoWait = CS.Engine.Lib.CoWait
local util = require 'XLua.util'
local cs_coroutine = import('XLua.cs_coroutine')
local WaitForSeconds = CS.UnityEngine.WaitForSeconds

local Text = CS.UnityEngine.UI.Text
local Image = CS.UnityEngine.UI.Image
local ImageAlterable = CS.Engine.UI.ImageAlterable
local Button = CS.UnityEngine.UI.Button
local Animator = CS.UnityEngine.Animator

local KTool = CS.Engine.Lib.KTool
local UIModule = CS.Engine.UI.UIModule
local phoneComp = GameUtils.GetOrAddEntityCompByType(ECSComponentType.Constants.PhoneComponent)

---@class UIFeelingFavorabilityRewardCellNode
local UIFeelingFavorabilityRewardCellNode = Class("UIFeelingFavorabilityRewardCellNode")
function UIFeelingFavorabilityRewardCellNode:__init() 
    self._curId = nil
    self._curCatId = nil
    self._index = nil
    self._isRedundant = false   --是否是多余的空位
    self._itemLoader = nil
    self._cb = nil
end

function UIFeelingFavorabilityRewardCellNode:__delete()
    self._curId = nil
    self._curCatId = nil
    self._index = nil
    self._isRedundant = false
    self._itemLoader = nil
    self._cb = nil
end

function UIFeelingFavorabilityRewardCellNode:Awake()
    SetButtonAction(self.FontStyleButton, Bind(self, self.OnSelectCat))
end

function UIFeelingFavorabilityRewardCellNode:Start()
end

function UIFeelingFavorabilityRewardCellNode:Refresh(id, catId, index, isRedundant, cb)
    self._curId = checkNumber(id)
    self._index = checkNumber(index)
    self._curCatId = checkNumber(catId)
    self._cb = cb

    if isRedundant then
        self._isRedundant = true
        self:RefreshRedundant()
    else
        self._isRedundant = false
        self:RefreshNormal()
    end 

    KTool.SetActive(self.Txtquestion, self._isRedundant)
    KTool.SetActive(self.Normal, not self._isRedundant)
    KTool.SetActive(self.Root, true)
end

--正常的
function UIFeelingFavorabilityRewardCellNode:RefreshNormal()
    local vo = PhoneUtils.GetLikabilityRewardVo(self._curId)
    if vo then
        CfUtils.FillText(self.Text, localize("亲密度达到<size=46><color=#ffffff> _num_ </color></size>级解锁", {_num_ = vo.rankId}))
        
        if not self._itemLoader then
            self._itemLoader = CS.Engine.Modules.ResourceModule.LoadBundleSync("Prefabs/Common/GoodNode.prefab", nil, true)
        end
        if self._itemLoader.IsSuccess then
            local go = self.Normal.transform:Find("receiveGroup/GoodNode")
            if not go then 
                go = CfUtils.InstantiateGo(self._itemLoader.ResultObject, self.ImgIcon)
                go.name = "item"
            end
            if go then
                CfUtils.RefeshGoodGo(go, vo.itemId, nil, 0.7)
            end
        end
    end

    local isCanDraw = PhoneUtils.IsCanDrawRewardById(self._curId)
    local isDraw = PhoneUtils.IsDrawRewardById(self._curId)
    --CfUtils.SetScale(self.FontStyleButton, Vector3(0.8, 0.8, 0.8))
    KTool.SetActive(self.FontStyleButton, not isDraw)
    KTool.SetActive(self.ImgGet, isDraw)
    --如果没领取
    if not isDraw then
        --如果可领取
        if isCanDraw then
            self.FontStyleButton:ResetFontStyle("B13")
            KTool.SetActive(self.FontStyleButton.transform:Find("Text"), true)
        else
            self.FontStyleButton:ResetFontStyle("B9")
            KTool.SetActive(self.FontStyleButton.transform:Find("Text"), false)
        end
    end
end

--多余的
function UIFeelingFavorabilityRewardCellNode:RefreshRedundant()
    CfUtils.FillText(self.Txtexpect, localize("敬请期待"))
end

function UIFeelingFavorabilityRewardCellNode:OnSelectCat()
    local isCanDraw = PhoneUtils.IsCanDrawRewardById(self._curId)
    local isDraw = PhoneUtils.IsDrawRewardById(self._curId)
    if not isDraw then
        --如果可领取
        if isCanDraw then
            phoneComp:PhoneDrawFavorabilityRewardReq(self._curCatId, self._curId, function()
                if self._cb then
                    self._cb()
                end
                --KTool.SetActive(self.ImgGet, true)
                --KTool.SetActive(self.FontStyleButton, false)
            end)
        else
            GameUtils.Toast(localize("未满足领取条件"))
        end
    else
        GameUtils.Toast(localize("当前奖励已领取"))
    end
end

function UIFeelingFavorabilityRewardCellNode:OnDestroy()
    if not isNull(self._itemLoader) then
        self._itemLoader:Release()
        self._itemLoader = nil
    end
    self.controller = nil--luabehaviour 中CSharp对象
    self:Delete()
    self = nil
end

return UIFeelingFavorabilityRewardCellNode
