---
--- Generated by zxr
--- Created by zxr.
--- DateTime: 2023/3/13 20:18 ---

------------ import ------------
local BTNode = import("Frame.AI.BehaviorTree.BTNode")
------------ import ------------

------------ define ------------

------------ define ------------

---@class BTSelectorNode
local BTSelectorNode = Class("BTSelectorNode", BTNode)

function BTSelectorNode:__init(...)
    BTNode.__init(self, ...)
    self._lastRunningNode = nil
end

function BTSelectorNode:__delete()

end

function BTSelectorNode:OnUpdate(agent, blackboard)
    local runningStatus = BTNode.BTStatus.FINISHED
    local previousNode = self._lastRunningNode
    self._lastRunningNode = nil
    
    local count = BTNode.GetChildCount(self)
    for i = 1, count do
        ---@type BTNode
        local child   = BTNode.GetNode(self, i)
        runningStatus = child:OnUpdate(agent, blackboard)
        if runningStatus ~= BTNode.BTStatus.FAILED then
            self._lastRunningNode = child 
            break
        end
    end

    if previousNode ~= nil and self._lastRunningNode ~= previousNode then
        previousNode:Reset(agent, blackboard)
    end
    
    return runningStatus
end

function BTSelectorNode:OnReset(agent, blackboard)
    if self._lastRunningNode ~= nil then
        self._lastRunningNode:Reset(agent, blackboard)
    end
    self._lastRunningNode = nil
end

return BTSelectorNode
 