-- chunkname: @C:/GitLab-Runner/builds/sTUwNpCg/0/aqmobile/aqmobile-client/UnityProj/Assets/Scripts/Lua/logic/proto/EternalDragonExtension_pb.lua

local protobuf = require("protobuf.protobuf")

module("logic.proto.EternalDragonExtension_pb", package.seeall)

local tb = {}

PM_ETERNALDRAGONINFOREQ_MSG = protobuf.Descriptor()
tb.PM_ETERNALDRAGONINFOREQ_ACTIVITYID_FIELD = protobuf.FieldDescriptor()
PM_ETERNALDRAGONINFORES_MSG = protobuf.Descriptor()
tb.PM_ETERNALDRAGONINFORES_ACTIVITYID_FIELD = protobuf.FieldDescriptor()
tb.PM_ETERNALDRAGONINFORES_SCORE_FIELD = protobuf.FieldDescriptor()
tb.PM_ETERNALDRAGONINFORES_WATERTIMES_FIELD = protobuf.FieldDescriptor()
tb.PM_ETERNALDRAGONINFORES_GAMETIMES_FIELD = protobuf.FieldDescriptor()
tb.PM_ETERNALDRAGONINFORES_GAINPRIZEIDS_FIELD = protobuf.FieldDescriptor()
PM_ETERNALDRAGONWATERREQ_MSG = protobuf.Descriptor()
tb.PM_ETERNALDRAGONWATERREQ_ACTIVITYID_FIELD = protobuf.FieldDescriptor()
PM_ETERNALDRAGONWATERRES_MSG = protobuf.Descriptor()
tb.PM_ETERNALDRAGONWATERRES_ACTIVITYID_FIELD = protobuf.FieldDescriptor()
tb.PM_ETERNALDRAGONWATERRES_SCORE_FIELD = protobuf.FieldDescriptor()
tb.PM_ETERNALDRAGONWATERRES_CHANGESETID_FIELD = protobuf.FieldDescriptor()
PM_ETERNALDRAGONSTARTGAMEREQ_MSG = protobuf.Descriptor()
tb.PM_ETERNALDRAGONSTARTGAMEREQ_ACTIVITYID_FIELD = protobuf.FieldDescriptor()
tb.PM_ETERNALDRAGONSTARTGAMEREQ_CLIENTKEY_FIELD = protobuf.FieldDescriptor()
PM_ETERNALDRAGONSTARTGAMERES_MSG = protobuf.Descriptor()
tb.PM_ETERNALDRAGONSTARTGAMERES_SERVERKEY_FIELD = protobuf.FieldDescriptor()
PM_ETERNALDRAGONENDGAMEREQ_MSG = protobuf.Descriptor()
tb.PM_ETERNALDRAGONENDGAMEREQ_ACTIVITYID_FIELD = protobuf.FieldDescriptor()
tb.PM_ETERNALDRAGONENDGAMEREQ_ISPASS_FIELD = protobuf.FieldDescriptor()
tb.PM_ETERNALDRAGONENDGAMEREQ_ENCRYPTEDKEY_FIELD = protobuf.FieldDescriptor()
PM_ETERNALDRAGONENDGAMERES_MSG = protobuf.Descriptor()
tb.PM_ETERNALDRAGONENDGAMERES_CHANGESETID_FIELD = protobuf.FieldDescriptor()
PM_ETERNALDRAGONCUTTINGREQ_MSG = protobuf.Descriptor()
tb.PM_ETERNALDRAGONCUTTINGREQ_ACTIVITYID_FIELD = protobuf.FieldDescriptor()
PM_ETERNALDRAGONCUTTINGRES_MSG = protobuf.Descriptor()
tb.PM_ETERNALDRAGONCUTTINGRES_ACTIVITYID_FIELD = protobuf.FieldDescriptor()
tb.PM_ETERNALDRAGONCUTTINGRES_SCORE_FIELD = protobuf.FieldDescriptor()
tb.PM_ETERNALDRAGONCUTTINGRES_CHANGESETID_FIELD = protobuf.FieldDescriptor()
PM_ETERNALDRAGONGAINPRIZEREQ_MSG = protobuf.Descriptor()
tb.PM_ETERNALDRAGONGAINPRIZEREQ_ACTIVITYID_FIELD = protobuf.FieldDescriptor()
tb.PM_ETERNALDRAGONGAINPRIZEREQ_PRIZEID_FIELD = protobuf.FieldDescriptor()
PM_ETERNALDRAGONGAINPRIZERES_MSG = protobuf.Descriptor()
tb.PM_ETERNALDRAGONGAINPRIZERES_CHANGESETID_FIELD = protobuf.FieldDescriptor()
tb.PM_ETERNALDRAGONINFOREQ_ACTIVITYID_FIELD.name = "activityId"
tb.PM_ETERNALDRAGONINFOREQ_ACTIVITYID_FIELD.full_name = ".PM_EternalDragonInfoReq.activityId"
tb.PM_ETERNALDRAGONINFOREQ_ACTIVITYID_FIELD.number = 1
tb.PM_ETERNALDRAGONINFOREQ_ACTIVITYID_FIELD.index = 0
tb.PM_ETERNALDRAGONINFOREQ_ACTIVITYID_FIELD.label = 2
tb.PM_ETERNALDRAGONINFOREQ_ACTIVITYID_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONINFOREQ_ACTIVITYID_FIELD.default_value = 0
tb.PM_ETERNALDRAGONINFOREQ_ACTIVITYID_FIELD.type = 5
tb.PM_ETERNALDRAGONINFOREQ_ACTIVITYID_FIELD.cpp_type = 1
PM_ETERNALDRAGONINFOREQ_MSG.name = "PM_EternalDragonInfoReq"
PM_ETERNALDRAGONINFOREQ_MSG.full_name = ".PM_EternalDragonInfoReq"
PM_ETERNALDRAGONINFOREQ_MSG.nested_types = {}
PM_ETERNALDRAGONINFOREQ_MSG.enum_types = {}
PM_ETERNALDRAGONINFOREQ_MSG.fields = {
	tb.PM_ETERNALDRAGONINFOREQ_ACTIVITYID_FIELD
}
PM_ETERNALDRAGONINFOREQ_MSG.is_extendable = false
PM_ETERNALDRAGONINFOREQ_MSG.extensions = {}
tb.PM_ETERNALDRAGONINFORES_ACTIVITYID_FIELD.name = "activityId"
tb.PM_ETERNALDRAGONINFORES_ACTIVITYID_FIELD.full_name = ".PM_EternalDragonInfoRes.activityId"
tb.PM_ETERNALDRAGONINFORES_ACTIVITYID_FIELD.number = 1
tb.PM_ETERNALDRAGONINFORES_ACTIVITYID_FIELD.index = 0
tb.PM_ETERNALDRAGONINFORES_ACTIVITYID_FIELD.label = 2
tb.PM_ETERNALDRAGONINFORES_ACTIVITYID_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONINFORES_ACTIVITYID_FIELD.default_value = 0
tb.PM_ETERNALDRAGONINFORES_ACTIVITYID_FIELD.type = 5
tb.PM_ETERNALDRAGONINFORES_ACTIVITYID_FIELD.cpp_type = 1
tb.PM_ETERNALDRAGONINFORES_SCORE_FIELD.name = "score"
tb.PM_ETERNALDRAGONINFORES_SCORE_FIELD.full_name = ".PM_EternalDragonInfoRes.score"
tb.PM_ETERNALDRAGONINFORES_SCORE_FIELD.number = 2
tb.PM_ETERNALDRAGONINFORES_SCORE_FIELD.index = 1
tb.PM_ETERNALDRAGONINFORES_SCORE_FIELD.label = 2
tb.PM_ETERNALDRAGONINFORES_SCORE_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONINFORES_SCORE_FIELD.default_value = 0
tb.PM_ETERNALDRAGONINFORES_SCORE_FIELD.type = 5
tb.PM_ETERNALDRAGONINFORES_SCORE_FIELD.cpp_type = 1
tb.PM_ETERNALDRAGONINFORES_WATERTIMES_FIELD.name = "waterTimes"
tb.PM_ETERNALDRAGONINFORES_WATERTIMES_FIELD.full_name = ".PM_EternalDragonInfoRes.waterTimes"
tb.PM_ETERNALDRAGONINFORES_WATERTIMES_FIELD.number = 3
tb.PM_ETERNALDRAGONINFORES_WATERTIMES_FIELD.index = 2
tb.PM_ETERNALDRAGONINFORES_WATERTIMES_FIELD.label = 2
tb.PM_ETERNALDRAGONINFORES_WATERTIMES_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONINFORES_WATERTIMES_FIELD.default_value = 0
tb.PM_ETERNALDRAGONINFORES_WATERTIMES_FIELD.type = 5
tb.PM_ETERNALDRAGONINFORES_WATERTIMES_FIELD.cpp_type = 1
tb.PM_ETERNALDRAGONINFORES_GAMETIMES_FIELD.name = "gameTimes"
tb.PM_ETERNALDRAGONINFORES_GAMETIMES_FIELD.full_name = ".PM_EternalDragonInfoRes.gameTimes"
tb.PM_ETERNALDRAGONINFORES_GAMETIMES_FIELD.number = 4
tb.PM_ETERNALDRAGONINFORES_GAMETIMES_FIELD.index = 3
tb.PM_ETERNALDRAGONINFORES_GAMETIMES_FIELD.label = 2
tb.PM_ETERNALDRAGONINFORES_GAMETIMES_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONINFORES_GAMETIMES_FIELD.default_value = 0
tb.PM_ETERNALDRAGONINFORES_GAMETIMES_FIELD.type = 5
tb.PM_ETERNALDRAGONINFORES_GAMETIMES_FIELD.cpp_type = 1
tb.PM_ETERNALDRAGONINFORES_GAINPRIZEIDS_FIELD.name = "gainPrizeIds"
tb.PM_ETERNALDRAGONINFORES_GAINPRIZEIDS_FIELD.full_name = ".PM_EternalDragonInfoRes.gainPrizeIds"
tb.PM_ETERNALDRAGONINFORES_GAINPRIZEIDS_FIELD.number = 5
tb.PM_ETERNALDRAGONINFORES_GAINPRIZEIDS_FIELD.index = 4
tb.PM_ETERNALDRAGONINFORES_GAINPRIZEIDS_FIELD.label = 3
tb.PM_ETERNALDRAGONINFORES_GAINPRIZEIDS_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONINFORES_GAINPRIZEIDS_FIELD.default_value = {}
tb.PM_ETERNALDRAGONINFORES_GAINPRIZEIDS_FIELD.type = 5
tb.PM_ETERNALDRAGONINFORES_GAINPRIZEIDS_FIELD.cpp_type = 1
PM_ETERNALDRAGONINFORES_MSG.name = "PM_EternalDragonInfoRes"
PM_ETERNALDRAGONINFORES_MSG.full_name = ".PM_EternalDragonInfoRes"
PM_ETERNALDRAGONINFORES_MSG.nested_types = {}
PM_ETERNALDRAGONINFORES_MSG.enum_types = {}
PM_ETERNALDRAGONINFORES_MSG.fields = {
	tb.PM_ETERNALDRAGONINFORES_ACTIVITYID_FIELD,
	tb.PM_ETERNALDRAGONINFORES_SCORE_FIELD,
	tb.PM_ETERNALDRAGONINFORES_WATERTIMES_FIELD,
	tb.PM_ETERNALDRAGONINFORES_GAMETIMES_FIELD,
	tb.PM_ETERNALDRAGONINFORES_GAINPRIZEIDS_FIELD
}
PM_ETERNALDRAGONINFORES_MSG.is_extendable = false
PM_ETERNALDRAGONINFORES_MSG.extensions = {}
tb.PM_ETERNALDRAGONWATERREQ_ACTIVITYID_FIELD.name = "activityId"
tb.PM_ETERNALDRAGONWATERREQ_ACTIVITYID_FIELD.full_name = ".PM_EternalDragonWaterReq.activityId"
tb.PM_ETERNALDRAGONWATERREQ_ACTIVITYID_FIELD.number = 1
tb.PM_ETERNALDRAGONWATERREQ_ACTIVITYID_FIELD.index = 0
tb.PM_ETERNALDRAGONWATERREQ_ACTIVITYID_FIELD.label = 2
tb.PM_ETERNALDRAGONWATERREQ_ACTIVITYID_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONWATERREQ_ACTIVITYID_FIELD.default_value = 0
tb.PM_ETERNALDRAGONWATERREQ_ACTIVITYID_FIELD.type = 5
tb.PM_ETERNALDRAGONWATERREQ_ACTIVITYID_FIELD.cpp_type = 1
PM_ETERNALDRAGONWATERREQ_MSG.name = "PM_EternalDragonWaterReq"
PM_ETERNALDRAGONWATERREQ_MSG.full_name = ".PM_EternalDragonWaterReq"
PM_ETERNALDRAGONWATERREQ_MSG.nested_types = {}
PM_ETERNALDRAGONWATERREQ_MSG.enum_types = {}
PM_ETERNALDRAGONWATERREQ_MSG.fields = {
	tb.PM_ETERNALDRAGONWATERREQ_ACTIVITYID_FIELD
}
PM_ETERNALDRAGONWATERREQ_MSG.is_extendable = false
PM_ETERNALDRAGONWATERREQ_MSG.extensions = {}
tb.PM_ETERNALDRAGONWATERRES_ACTIVITYID_FIELD.name = "activityId"
tb.PM_ETERNALDRAGONWATERRES_ACTIVITYID_FIELD.full_name = ".PM_EternalDragonWaterRes.activityId"
tb.PM_ETERNALDRAGONWATERRES_ACTIVITYID_FIELD.number = 1
tb.PM_ETERNALDRAGONWATERRES_ACTIVITYID_FIELD.index = 0
tb.PM_ETERNALDRAGONWATERRES_ACTIVITYID_FIELD.label = 2
tb.PM_ETERNALDRAGONWATERRES_ACTIVITYID_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONWATERRES_ACTIVITYID_FIELD.default_value = 0
tb.PM_ETERNALDRAGONWATERRES_ACTIVITYID_FIELD.type = 5
tb.PM_ETERNALDRAGONWATERRES_ACTIVITYID_FIELD.cpp_type = 1
tb.PM_ETERNALDRAGONWATERRES_SCORE_FIELD.name = "score"
tb.PM_ETERNALDRAGONWATERRES_SCORE_FIELD.full_name = ".PM_EternalDragonWaterRes.score"
tb.PM_ETERNALDRAGONWATERRES_SCORE_FIELD.number = 2
tb.PM_ETERNALDRAGONWATERRES_SCORE_FIELD.index = 1
tb.PM_ETERNALDRAGONWATERRES_SCORE_FIELD.label = 2
tb.PM_ETERNALDRAGONWATERRES_SCORE_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONWATERRES_SCORE_FIELD.default_value = 0
tb.PM_ETERNALDRAGONWATERRES_SCORE_FIELD.type = 5
tb.PM_ETERNALDRAGONWATERRES_SCORE_FIELD.cpp_type = 1
tb.PM_ETERNALDRAGONWATERRES_CHANGESETID_FIELD.name = "changeSetId"
tb.PM_ETERNALDRAGONWATERRES_CHANGESETID_FIELD.full_name = ".PM_EternalDragonWaterRes.changeSetId"
tb.PM_ETERNALDRAGONWATERRES_CHANGESETID_FIELD.number = 3
tb.PM_ETERNALDRAGONWATERRES_CHANGESETID_FIELD.index = 2
tb.PM_ETERNALDRAGONWATERRES_CHANGESETID_FIELD.label = 2
tb.PM_ETERNALDRAGONWATERRES_CHANGESETID_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONWATERRES_CHANGESETID_FIELD.default_value = 0
tb.PM_ETERNALDRAGONWATERRES_CHANGESETID_FIELD.type = 5
tb.PM_ETERNALDRAGONWATERRES_CHANGESETID_FIELD.cpp_type = 1
PM_ETERNALDRAGONWATERRES_MSG.name = "PM_EternalDragonWaterRes"
PM_ETERNALDRAGONWATERRES_MSG.full_name = ".PM_EternalDragonWaterRes"
PM_ETERNALDRAGONWATERRES_MSG.nested_types = {}
PM_ETERNALDRAGONWATERRES_MSG.enum_types = {}
PM_ETERNALDRAGONWATERRES_MSG.fields = {
	tb.PM_ETERNALDRAGONWATERRES_ACTIVITYID_FIELD,
	tb.PM_ETERNALDRAGONWATERRES_SCORE_FIELD,
	tb.PM_ETERNALDRAGONWATERRES_CHANGESETID_FIELD
}
PM_ETERNALDRAGONWATERRES_MSG.is_extendable = false
PM_ETERNALDRAGONWATERRES_MSG.extensions = {}
tb.PM_ETERNALDRAGONSTARTGAMEREQ_ACTIVITYID_FIELD.name = "activityId"
tb.PM_ETERNALDRAGONSTARTGAMEREQ_ACTIVITYID_FIELD.full_name = ".PM_EternalDragonStartGameReq.activityId"
tb.PM_ETERNALDRAGONSTARTGAMEREQ_ACTIVITYID_FIELD.number = 1
tb.PM_ETERNALDRAGONSTARTGAMEREQ_ACTIVITYID_FIELD.index = 0
tb.PM_ETERNALDRAGONSTARTGAMEREQ_ACTIVITYID_FIELD.label = 2
tb.PM_ETERNALDRAGONSTARTGAMEREQ_ACTIVITYID_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONSTARTGAMEREQ_ACTIVITYID_FIELD.default_value = 0
tb.PM_ETERNALDRAGONSTARTGAMEREQ_ACTIVITYID_FIELD.type = 5
tb.PM_ETERNALDRAGONSTARTGAMEREQ_ACTIVITYID_FIELD.cpp_type = 1
tb.PM_ETERNALDRAGONSTARTGAMEREQ_CLIENTKEY_FIELD.name = "clientKey"
tb.PM_ETERNALDRAGONSTARTGAMEREQ_CLIENTKEY_FIELD.full_name = ".PM_EternalDragonStartGameReq.clientKey"
tb.PM_ETERNALDRAGONSTARTGAMEREQ_CLIENTKEY_FIELD.number = 2
tb.PM_ETERNALDRAGONSTARTGAMEREQ_CLIENTKEY_FIELD.index = 1
tb.PM_ETERNALDRAGONSTARTGAMEREQ_CLIENTKEY_FIELD.label = 2
tb.PM_ETERNALDRAGONSTARTGAMEREQ_CLIENTKEY_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONSTARTGAMEREQ_CLIENTKEY_FIELD.default_value = 0
tb.PM_ETERNALDRAGONSTARTGAMEREQ_CLIENTKEY_FIELD.type = 5
tb.PM_ETERNALDRAGONSTARTGAMEREQ_CLIENTKEY_FIELD.cpp_type = 1
PM_ETERNALDRAGONSTARTGAMEREQ_MSG.name = "PM_EternalDragonStartGameReq"
PM_ETERNALDRAGONSTARTGAMEREQ_MSG.full_name = ".PM_EternalDragonStartGameReq"
PM_ETERNALDRAGONSTARTGAMEREQ_MSG.nested_types = {}
PM_ETERNALDRAGONSTARTGAMEREQ_MSG.enum_types = {}
PM_ETERNALDRAGONSTARTGAMEREQ_MSG.fields = {
	tb.PM_ETERNALDRAGONSTARTGAMEREQ_ACTIVITYID_FIELD,
	tb.PM_ETERNALDRAGONSTARTGAMEREQ_CLIENTKEY_FIELD
}
PM_ETERNALDRAGONSTARTGAMEREQ_MSG.is_extendable = false
PM_ETERNALDRAGONSTARTGAMEREQ_MSG.extensions = {}
tb.PM_ETERNALDRAGONSTARTGAMERES_SERVERKEY_FIELD.name = "serverKey"
tb.PM_ETERNALDRAGONSTARTGAMERES_SERVERKEY_FIELD.full_name = ".PM_EternalDragonStartGameRes.serverKey"
tb.PM_ETERNALDRAGONSTARTGAMERES_SERVERKEY_FIELD.number = 1
tb.PM_ETERNALDRAGONSTARTGAMERES_SERVERKEY_FIELD.index = 0
tb.PM_ETERNALDRAGONSTARTGAMERES_SERVERKEY_FIELD.label = 2
tb.PM_ETERNALDRAGONSTARTGAMERES_SERVERKEY_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONSTARTGAMERES_SERVERKEY_FIELD.default_value = 0
tb.PM_ETERNALDRAGONSTARTGAMERES_SERVERKEY_FIELD.type = 5
tb.PM_ETERNALDRAGONSTARTGAMERES_SERVERKEY_FIELD.cpp_type = 1
PM_ETERNALDRAGONSTARTGAMERES_MSG.name = "PM_EternalDragonStartGameRes"
PM_ETERNALDRAGONSTARTGAMERES_MSG.full_name = ".PM_EternalDragonStartGameRes"
PM_ETERNALDRAGONSTARTGAMERES_MSG.nested_types = {}
PM_ETERNALDRAGONSTARTGAMERES_MSG.enum_types = {}
PM_ETERNALDRAGONSTARTGAMERES_MSG.fields = {
	tb.PM_ETERNALDRAGONSTARTGAMERES_SERVERKEY_FIELD
}
PM_ETERNALDRAGONSTARTGAMERES_MSG.is_extendable = false
PM_ETERNALDRAGONSTARTGAMERES_MSG.extensions = {}
tb.PM_ETERNALDRAGONENDGAMEREQ_ACTIVITYID_FIELD.name = "activityId"
tb.PM_ETERNALDRAGONENDGAMEREQ_ACTIVITYID_FIELD.full_name = ".PM_EternalDragonEndGameReq.activityId"
tb.PM_ETERNALDRAGONENDGAMEREQ_ACTIVITYID_FIELD.number = 1
tb.PM_ETERNALDRAGONENDGAMEREQ_ACTIVITYID_FIELD.index = 0
tb.PM_ETERNALDRAGONENDGAMEREQ_ACTIVITYID_FIELD.label = 2
tb.PM_ETERNALDRAGONENDGAMEREQ_ACTIVITYID_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONENDGAMEREQ_ACTIVITYID_FIELD.default_value = 0
tb.PM_ETERNALDRAGONENDGAMEREQ_ACTIVITYID_FIELD.type = 5
tb.PM_ETERNALDRAGONENDGAMEREQ_ACTIVITYID_FIELD.cpp_type = 1
tb.PM_ETERNALDRAGONENDGAMEREQ_ISPASS_FIELD.name = "isPass"
tb.PM_ETERNALDRAGONENDGAMEREQ_ISPASS_FIELD.full_name = ".PM_EternalDragonEndGameReq.isPass"
tb.PM_ETERNALDRAGONENDGAMEREQ_ISPASS_FIELD.number = 2
tb.PM_ETERNALDRAGONENDGAMEREQ_ISPASS_FIELD.index = 1
tb.PM_ETERNALDRAGONENDGAMEREQ_ISPASS_FIELD.label = 2
tb.PM_ETERNALDRAGONENDGAMEREQ_ISPASS_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONENDGAMEREQ_ISPASS_FIELD.default_value = false
tb.PM_ETERNALDRAGONENDGAMEREQ_ISPASS_FIELD.type = 8
tb.PM_ETERNALDRAGONENDGAMEREQ_ISPASS_FIELD.cpp_type = 7
tb.PM_ETERNALDRAGONENDGAMEREQ_ENCRYPTEDKEY_FIELD.name = "encryptedKey"
tb.PM_ETERNALDRAGONENDGAMEREQ_ENCRYPTEDKEY_FIELD.full_name = ".PM_EternalDragonEndGameReq.encryptedKey"
tb.PM_ETERNALDRAGONENDGAMEREQ_ENCRYPTEDKEY_FIELD.number = 3
tb.PM_ETERNALDRAGONENDGAMEREQ_ENCRYPTEDKEY_FIELD.index = 2
tb.PM_ETERNALDRAGONENDGAMEREQ_ENCRYPTEDKEY_FIELD.label = 2
tb.PM_ETERNALDRAGONENDGAMEREQ_ENCRYPTEDKEY_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONENDGAMEREQ_ENCRYPTEDKEY_FIELD.default_value = 0
tb.PM_ETERNALDRAGONENDGAMEREQ_ENCRYPTEDKEY_FIELD.type = 3
tb.PM_ETERNALDRAGONENDGAMEREQ_ENCRYPTEDKEY_FIELD.cpp_type = 2
PM_ETERNALDRAGONENDGAMEREQ_MSG.name = "PM_EternalDragonEndGameReq"
PM_ETERNALDRAGONENDGAMEREQ_MSG.full_name = ".PM_EternalDragonEndGameReq"
PM_ETERNALDRAGONENDGAMEREQ_MSG.nested_types = {}
PM_ETERNALDRAGONENDGAMEREQ_MSG.enum_types = {}
PM_ETERNALDRAGONENDGAMEREQ_MSG.fields = {
	tb.PM_ETERNALDRAGONENDGAMEREQ_ACTIVITYID_FIELD,
	tb.PM_ETERNALDRAGONENDGAMEREQ_ISPASS_FIELD,
	tb.PM_ETERNALDRAGONENDGAMEREQ_ENCRYPTEDKEY_FIELD
}
PM_ETERNALDRAGONENDGAMEREQ_MSG.is_extendable = false
PM_ETERNALDRAGONENDGAMEREQ_MSG.extensions = {}
tb.PM_ETERNALDRAGONENDGAMERES_CHANGESETID_FIELD.name = "changeSetId"
tb.PM_ETERNALDRAGONENDGAMERES_CHANGESETID_FIELD.full_name = ".PM_EternalDragonEndGameRes.changeSetId"
tb.PM_ETERNALDRAGONENDGAMERES_CHANGESETID_FIELD.number = 1
tb.PM_ETERNALDRAGONENDGAMERES_CHANGESETID_FIELD.index = 0
tb.PM_ETERNALDRAGONENDGAMERES_CHANGESETID_FIELD.label = 1
tb.PM_ETERNALDRAGONENDGAMERES_CHANGESETID_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONENDGAMERES_CHANGESETID_FIELD.default_value = 0
tb.PM_ETERNALDRAGONENDGAMERES_CHANGESETID_FIELD.type = 5
tb.PM_ETERNALDRAGONENDGAMERES_CHANGESETID_FIELD.cpp_type = 1
PM_ETERNALDRAGONENDGAMERES_MSG.name = "PM_EternalDragonEndGameRes"
PM_ETERNALDRAGONENDGAMERES_MSG.full_name = ".PM_EternalDragonEndGameRes"
PM_ETERNALDRAGONENDGAMERES_MSG.nested_types = {}
PM_ETERNALDRAGONENDGAMERES_MSG.enum_types = {}
PM_ETERNALDRAGONENDGAMERES_MSG.fields = {
	tb.PM_ETERNALDRAGONENDGAMERES_CHANGESETID_FIELD
}
PM_ETERNALDRAGONENDGAMERES_MSG.is_extendable = false
PM_ETERNALDRAGONENDGAMERES_MSG.extensions = {}
tb.PM_ETERNALDRAGONCUTTINGREQ_ACTIVITYID_FIELD.name = "activityId"
tb.PM_ETERNALDRAGONCUTTINGREQ_ACTIVITYID_FIELD.full_name = ".PM_EternalDragonCuttingReq.activityId"
tb.PM_ETERNALDRAGONCUTTINGREQ_ACTIVITYID_FIELD.number = 1
tb.PM_ETERNALDRAGONCUTTINGREQ_ACTIVITYID_FIELD.index = 0
tb.PM_ETERNALDRAGONCUTTINGREQ_ACTIVITYID_FIELD.label = 2
tb.PM_ETERNALDRAGONCUTTINGREQ_ACTIVITYID_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONCUTTINGREQ_ACTIVITYID_FIELD.default_value = 0
tb.PM_ETERNALDRAGONCUTTINGREQ_ACTIVITYID_FIELD.type = 5
tb.PM_ETERNALDRAGONCUTTINGREQ_ACTIVITYID_FIELD.cpp_type = 1
PM_ETERNALDRAGONCUTTINGREQ_MSG.name = "PM_EternalDragonCuttingReq"
PM_ETERNALDRAGONCUTTINGREQ_MSG.full_name = ".PM_EternalDragonCuttingReq"
PM_ETERNALDRAGONCUTTINGREQ_MSG.nested_types = {}
PM_ETERNALDRAGONCUTTINGREQ_MSG.enum_types = {}
PM_ETERNALDRAGONCUTTINGREQ_MSG.fields = {
	tb.PM_ETERNALDRAGONCUTTINGREQ_ACTIVITYID_FIELD
}
PM_ETERNALDRAGONCUTTINGREQ_MSG.is_extendable = false
PM_ETERNALDRAGONCUTTINGREQ_MSG.extensions = {}
tb.PM_ETERNALDRAGONCUTTINGRES_ACTIVITYID_FIELD.name = "activityId"
tb.PM_ETERNALDRAGONCUTTINGRES_ACTIVITYID_FIELD.full_name = ".PM_EternalDragonCuttingRes.activityId"
tb.PM_ETERNALDRAGONCUTTINGRES_ACTIVITYID_FIELD.number = 1
tb.PM_ETERNALDRAGONCUTTINGRES_ACTIVITYID_FIELD.index = 0
tb.PM_ETERNALDRAGONCUTTINGRES_ACTIVITYID_FIELD.label = 2
tb.PM_ETERNALDRAGONCUTTINGRES_ACTIVITYID_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONCUTTINGRES_ACTIVITYID_FIELD.default_value = 0
tb.PM_ETERNALDRAGONCUTTINGRES_ACTIVITYID_FIELD.type = 5
tb.PM_ETERNALDRAGONCUTTINGRES_ACTIVITYID_FIELD.cpp_type = 1
tb.PM_ETERNALDRAGONCUTTINGRES_SCORE_FIELD.name = "score"
tb.PM_ETERNALDRAGONCUTTINGRES_SCORE_FIELD.full_name = ".PM_EternalDragonCuttingRes.score"
tb.PM_ETERNALDRAGONCUTTINGRES_SCORE_FIELD.number = 2
tb.PM_ETERNALDRAGONCUTTINGRES_SCORE_FIELD.index = 1
tb.PM_ETERNALDRAGONCUTTINGRES_SCORE_FIELD.label = 2
tb.PM_ETERNALDRAGONCUTTINGRES_SCORE_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONCUTTINGRES_SCORE_FIELD.default_value = 0
tb.PM_ETERNALDRAGONCUTTINGRES_SCORE_FIELD.type = 5
tb.PM_ETERNALDRAGONCUTTINGRES_SCORE_FIELD.cpp_type = 1
tb.PM_ETERNALDRAGONCUTTINGRES_CHANGESETID_FIELD.name = "changeSetId"
tb.PM_ETERNALDRAGONCUTTINGRES_CHANGESETID_FIELD.full_name = ".PM_EternalDragonCuttingRes.changeSetId"
tb.PM_ETERNALDRAGONCUTTINGRES_CHANGESETID_FIELD.number = 3
tb.PM_ETERNALDRAGONCUTTINGRES_CHANGESETID_FIELD.index = 2
tb.PM_ETERNALDRAGONCUTTINGRES_CHANGESETID_FIELD.label = 2
tb.PM_ETERNALDRAGONCUTTINGRES_CHANGESETID_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONCUTTINGRES_CHANGESETID_FIELD.default_value = 0
tb.PM_ETERNALDRAGONCUTTINGRES_CHANGESETID_FIELD.type = 5
tb.PM_ETERNALDRAGONCUTTINGRES_CHANGESETID_FIELD.cpp_type = 1
PM_ETERNALDRAGONCUTTINGRES_MSG.name = "PM_EternalDragonCuttingRes"
PM_ETERNALDRAGONCUTTINGRES_MSG.full_name = ".PM_EternalDragonCuttingRes"
PM_ETERNALDRAGONCUTTINGRES_MSG.nested_types = {}
PM_ETERNALDRAGONCUTTINGRES_MSG.enum_types = {}
PM_ETERNALDRAGONCUTTINGRES_MSG.fields = {
	tb.PM_ETERNALDRAGONCUTTINGRES_ACTIVITYID_FIELD,
	tb.PM_ETERNALDRAGONCUTTINGRES_SCORE_FIELD,
	tb.PM_ETERNALDRAGONCUTTINGRES_CHANGESETID_FIELD
}
PM_ETERNALDRAGONCUTTINGRES_MSG.is_extendable = false
PM_ETERNALDRAGONCUTTINGRES_MSG.extensions = {}
tb.PM_ETERNALDRAGONGAINPRIZEREQ_ACTIVITYID_FIELD.name = "activityId"
tb.PM_ETERNALDRAGONGAINPRIZEREQ_ACTIVITYID_FIELD.full_name = ".PM_EternalDragonGainPrizeReq.activityId"
tb.PM_ETERNALDRAGONGAINPRIZEREQ_ACTIVITYID_FIELD.number = 1
tb.PM_ETERNALDRAGONGAINPRIZEREQ_ACTIVITYID_FIELD.index = 0
tb.PM_ETERNALDRAGONGAINPRIZEREQ_ACTIVITYID_FIELD.label = 2
tb.PM_ETERNALDRAGONGAINPRIZEREQ_ACTIVITYID_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONGAINPRIZEREQ_ACTIVITYID_FIELD.default_value = 0
tb.PM_ETERNALDRAGONGAINPRIZEREQ_ACTIVITYID_FIELD.type = 5
tb.PM_ETERNALDRAGONGAINPRIZEREQ_ACTIVITYID_FIELD.cpp_type = 1
tb.PM_ETERNALDRAGONGAINPRIZEREQ_PRIZEID_FIELD.name = "prizeId"
tb.PM_ETERNALDRAGONGAINPRIZEREQ_PRIZEID_FIELD.full_name = ".PM_EternalDragonGainPrizeReq.prizeId"
tb.PM_ETERNALDRAGONGAINPRIZEREQ_PRIZEID_FIELD.number = 2
tb.PM_ETERNALDRAGONGAINPRIZEREQ_PRIZEID_FIELD.index = 1
tb.PM_ETERNALDRAGONGAINPRIZEREQ_PRIZEID_FIELD.label = 2
tb.PM_ETERNALDRAGONGAINPRIZEREQ_PRIZEID_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONGAINPRIZEREQ_PRIZEID_FIELD.default_value = 0
tb.PM_ETERNALDRAGONGAINPRIZEREQ_PRIZEID_FIELD.type = 5
tb.PM_ETERNALDRAGONGAINPRIZEREQ_PRIZEID_FIELD.cpp_type = 1
PM_ETERNALDRAGONGAINPRIZEREQ_MSG.name = "PM_EternalDragonGainPrizeReq"
PM_ETERNALDRAGONGAINPRIZEREQ_MSG.full_name = ".PM_EternalDragonGainPrizeReq"
PM_ETERNALDRAGONGAINPRIZEREQ_MSG.nested_types = {}
PM_ETERNALDRAGONGAINPRIZEREQ_MSG.enum_types = {}
PM_ETERNALDRAGONGAINPRIZEREQ_MSG.fields = {
	tb.PM_ETERNALDRAGONGAINPRIZEREQ_ACTIVITYID_FIELD,
	tb.PM_ETERNALDRAGONGAINPRIZEREQ_PRIZEID_FIELD
}
PM_ETERNALDRAGONGAINPRIZEREQ_MSG.is_extendable = false
PM_ETERNALDRAGONGAINPRIZEREQ_MSG.extensions = {}
tb.PM_ETERNALDRAGONGAINPRIZERES_CHANGESETID_FIELD.name = "changeSetId"
tb.PM_ETERNALDRAGONGAINPRIZERES_CHANGESETID_FIELD.full_name = ".PM_EternalDragonGainPrizeRes.changeSetId"
tb.PM_ETERNALDRAGONGAINPRIZERES_CHANGESETID_FIELD.number = 1
tb.PM_ETERNALDRAGONGAINPRIZERES_CHANGESETID_FIELD.index = 0
tb.PM_ETERNALDRAGONGAINPRIZERES_CHANGESETID_FIELD.label = 2
tb.PM_ETERNALDRAGONGAINPRIZERES_CHANGESETID_FIELD.has_default_value = false
tb.PM_ETERNALDRAGONGAINPRIZERES_CHANGESETID_FIELD.default_value = 0
tb.PM_ETERNALDRAGONGAINPRIZERES_CHANGESETID_FIELD.type = 5
tb.PM_ETERNALDRAGONGAINPRIZERES_CHANGESETID_FIELD.cpp_type = 1
PM_ETERNALDRAGONGAINPRIZERES_MSG.name = "PM_EternalDragonGainPrizeRes"
PM_ETERNALDRAGONGAINPRIZERES_MSG.full_name = ".PM_EternalDragonGainPrizeRes"
PM_ETERNALDRAGONGAINPRIZERES_MSG.nested_types = {}
PM_ETERNALDRAGONGAINPRIZERES_MSG.enum_types = {}
PM_ETERNALDRAGONGAINPRIZERES_MSG.fields = {
	tb.PM_ETERNALDRAGONGAINPRIZERES_CHANGESETID_FIELD
}
PM_ETERNALDRAGONGAINPRIZERES_MSG.is_extendable = false
PM_ETERNALDRAGONGAINPRIZERES_MSG.extensions = {}
PM_EternalDragonCuttingReq = protobuf.Message(PM_ETERNALDRAGONCUTTINGREQ_MSG)
PM_EternalDragonCuttingRes = protobuf.Message(PM_ETERNALDRAGONCUTTINGRES_MSG)
PM_EternalDragonEndGameReq = protobuf.Message(PM_ETERNALDRAGONENDGAMEREQ_MSG)
PM_EternalDragonEndGameRes = protobuf.Message(PM_ETERNALDRAGONENDGAMERES_MSG)
PM_EternalDragonGainPrizeReq = protobuf.Message(PM_ETERNALDRAGONGAINPRIZEREQ_MSG)
PM_EternalDragonGainPrizeRes = protobuf.Message(PM_ETERNALDRAGONGAINPRIZERES_MSG)
PM_EternalDragonInfoReq = protobuf.Message(PM_ETERNALDRAGONINFOREQ_MSG)
PM_EternalDragonInfoRes = protobuf.Message(PM_ETERNALDRAGONINFORES_MSG)
PM_EternalDragonStartGameReq = protobuf.Message(PM_ETERNALDRAGONSTARTGAMEREQ_MSG)
PM_EternalDragonStartGameRes = protobuf.Message(PM_ETERNALDRAGONSTARTGAMERES_MSG)
PM_EternalDragonWaterReq = protobuf.Message(PM_ETERNALDRAGONWATERREQ_MSG)
PM_EternalDragonWaterRes = protobuf.Message(PM_ETERNALDRAGONWATERRES_MSG)

return _G["logic.proto.EternalDragonExtension_pb"]
