-- chunkname: @C:/GitLab-Runner/builds/sTUwNpCg/0/aqmobile/aqmobile-client/UnityProj/Assets/Scripts/Lua/logic/proto/GodDiShiTianExtension_pb.lua

local protobuf = require("protobuf.protobuf")
local FORMATIONEXTENSION_PB = require("logic.proto.FormationExtension_pb")

module("logic.proto.GodDiShiTianExtension_pb", package.seeall)

local tb = {}

PM_DSTSTAGEDETAIL_MSG = protobuf.Descriptor()
tb.PM_DSTSTAGEDETAIL_STAGEID_FIELD = protobuf.FieldDescriptor()
tb.PM_DSTSTAGEDETAIL_SCORE_FIELD = protobuf.FieldDescriptor()
tb.PM_DSTSTAGEDETAIL_STATE_FIELD = protobuf.FieldDescriptor()
PM_DSTSTAGESUM_MSG = protobuf.Descriptor()
tb.PM_DSTSTAGESUM_STAGETYPE_FIELD = protobuf.FieldDescriptor()
tb.PM_DSTSTAGESUM_TOTALSCORE_FIELD = protobuf.FieldDescriptor()
tb.PM_DSTSTAGESUM_STAGEINFO_FIELD = protobuf.FieldDescriptor()
PM_DSTSTAGECONDITION_MSG = protobuf.Descriptor()
tb.PM_DSTSTAGECONDITION_CONDITIONID_FIELD = protobuf.FieldDescriptor()
tb.PM_DSTSTAGECONDITION_PARAM_FIELD = protobuf.FieldDescriptor()
tb.PM_DSTSTAGECONDITION_SCORE_FIELD = protobuf.FieldDescriptor()
PM_GODDISHITIANGETINFOREQ_MSG = protobuf.Descriptor()
PM_GODDISHITIANGETINFORES_MSG = protobuf.Descriptor()
tb.PM_GODDISHITIANGETINFORES_PASS_FIELD = protobuf.FieldDescriptor()
tb.PM_GODDISHITIANGETINFORES_STAGEINFO_FIELD = protobuf.FieldDescriptor()
tb.PM_GODDISHITIANGETINFORES_SIMPLEFORM_FIELD = protobuf.FieldDescriptor()
PM_GODDISHITIANCHALLENGEREQ_MSG = protobuf.Descriptor()
tb.PM_GODDISHITIANCHALLENGEREQ_STAGEID_FIELD = protobuf.FieldDescriptor()
tb.PM_GODDISHITIANCHALLENGEREQ_SIMPLEFORM_FIELD = protobuf.FieldDescriptor()
PM_GODDISHITIANCHALLENGERES_MSG = protobuf.Descriptor()
PM_GODDISHITIANSETSCOREREQ_MSG = protobuf.Descriptor()
tb.PM_GODDISHITIANSETSCOREREQ_STAGEID_FIELD = protobuf.FieldDescriptor()
PM_GODDISHITIANSETSCORERES_MSG = protobuf.Descriptor()
tb.PM_GODDISHITIANSETSCORERES_STAGEID_FIELD = protobuf.FieldDescriptor()
tb.PM_GODDISHITIANSETSCORERES_SCORE_FIELD = protobuf.FieldDescriptor()
PM_GODDISHITIANQUICKPASSREQ_MSG = protobuf.Descriptor()
PM_GODDISHITIANQUICKPASSRES_MSG = protobuf.Descriptor()
tb.PM_GODDISHITIANQUICKPASSRES_PASS_FIELD = protobuf.FieldDescriptor()
tb.PM_GODDISHITIANQUICKPASSRES_CHANGESETID_FIELD = protobuf.FieldDescriptor()
PM_GODDISHITIANSTAGEOVERRES_MSG = protobuf.Descriptor()
tb.PM_GODDISHITIANSTAGEOVERRES_STAGEID_FIELD = protobuf.FieldDescriptor()
tb.PM_GODDISHITIANSTAGEOVERRES_SCORE_FIELD = protobuf.FieldDescriptor()
tb.PM_GODDISHITIANSTAGEOVERRES_CONDITION_FIELD = protobuf.FieldDescriptor()
tb.PM_GODDISHITIANSTAGEOVERRES_PASS_FIELD = protobuf.FieldDescriptor()
tb.PM_GODDISHITIANSTAGEOVERRES_TOTALSCORE_FIELD = protobuf.FieldDescriptor()
tb.PM_GODDISHITIANSTAGEOVERRES_WIN_FIELD = protobuf.FieldDescriptor()
tb.PM_DSTSTAGEDETAIL_STAGEID_FIELD.name = "stageId"
tb.PM_DSTSTAGEDETAIL_STAGEID_FIELD.full_name = ".PM_DSTStageDetail.stageId"
tb.PM_DSTSTAGEDETAIL_STAGEID_FIELD.number = 1
tb.PM_DSTSTAGEDETAIL_STAGEID_FIELD.index = 0
tb.PM_DSTSTAGEDETAIL_STAGEID_FIELD.label = 2
tb.PM_DSTSTAGEDETAIL_STAGEID_FIELD.has_default_value = false
tb.PM_DSTSTAGEDETAIL_STAGEID_FIELD.default_value = 0
tb.PM_DSTSTAGEDETAIL_STAGEID_FIELD.type = 5
tb.PM_DSTSTAGEDETAIL_STAGEID_FIELD.cpp_type = 1
tb.PM_DSTSTAGEDETAIL_SCORE_FIELD.name = "score"
tb.PM_DSTSTAGEDETAIL_SCORE_FIELD.full_name = ".PM_DSTStageDetail.score"
tb.PM_DSTSTAGEDETAIL_SCORE_FIELD.number = 2
tb.PM_DSTSTAGEDETAIL_SCORE_FIELD.index = 1
tb.PM_DSTSTAGEDETAIL_SCORE_FIELD.label = 2
tb.PM_DSTSTAGEDETAIL_SCORE_FIELD.has_default_value = false
tb.PM_DSTSTAGEDETAIL_SCORE_FIELD.default_value = 0
tb.PM_DSTSTAGEDETAIL_SCORE_FIELD.type = 5
tb.PM_DSTSTAGEDETAIL_SCORE_FIELD.cpp_type = 1
tb.PM_DSTSTAGEDETAIL_STATE_FIELD.name = "state"
tb.PM_DSTSTAGEDETAIL_STATE_FIELD.full_name = ".PM_DSTStageDetail.state"
tb.PM_DSTSTAGEDETAIL_STATE_FIELD.number = 3
tb.PM_DSTSTAGEDETAIL_STATE_FIELD.index = 2
tb.PM_DSTSTAGEDETAIL_STATE_FIELD.label = 2
tb.PM_DSTSTAGEDETAIL_STATE_FIELD.has_default_value = false
tb.PM_DSTSTAGEDETAIL_STATE_FIELD.default_value = 0
tb.PM_DSTSTAGEDETAIL_STATE_FIELD.type = 5
tb.PM_DSTSTAGEDETAIL_STATE_FIELD.cpp_type = 1
PM_DSTSTAGEDETAIL_MSG.name = "PM_DSTStageDetail"
PM_DSTSTAGEDETAIL_MSG.full_name = ".PM_DSTStageDetail"
PM_DSTSTAGEDETAIL_MSG.nested_types = {}
PM_DSTSTAGEDETAIL_MSG.enum_types = {}
PM_DSTSTAGEDETAIL_MSG.fields = {
	tb.PM_DSTSTAGEDETAIL_STAGEID_FIELD,
	tb.PM_DSTSTAGEDETAIL_SCORE_FIELD,
	tb.PM_DSTSTAGEDETAIL_STATE_FIELD
}
PM_DSTSTAGEDETAIL_MSG.is_extendable = false
PM_DSTSTAGEDETAIL_MSG.extensions = {}
tb.PM_DSTSTAGESUM_STAGETYPE_FIELD.name = "stageType"
tb.PM_DSTSTAGESUM_STAGETYPE_FIELD.full_name = ".PM_DSTStageSum.stageType"
tb.PM_DSTSTAGESUM_STAGETYPE_FIELD.number = 1
tb.PM_DSTSTAGESUM_STAGETYPE_FIELD.index = 0
tb.PM_DSTSTAGESUM_STAGETYPE_FIELD.label = 2
tb.PM_DSTSTAGESUM_STAGETYPE_FIELD.has_default_value = false
tb.PM_DSTSTAGESUM_STAGETYPE_FIELD.default_value = 0
tb.PM_DSTSTAGESUM_STAGETYPE_FIELD.type = 5
tb.PM_DSTSTAGESUM_STAGETYPE_FIELD.cpp_type = 1
tb.PM_DSTSTAGESUM_TOTALSCORE_FIELD.name = "totalScore"
tb.PM_DSTSTAGESUM_TOTALSCORE_FIELD.full_name = ".PM_DSTStageSum.totalScore"
tb.PM_DSTSTAGESUM_TOTALSCORE_FIELD.number = 2
tb.PM_DSTSTAGESUM_TOTALSCORE_FIELD.index = 1
tb.PM_DSTSTAGESUM_TOTALSCORE_FIELD.label = 2
tb.PM_DSTSTAGESUM_TOTALSCORE_FIELD.has_default_value = false
tb.PM_DSTSTAGESUM_TOTALSCORE_FIELD.default_value = 0
tb.PM_DSTSTAGESUM_TOTALSCORE_FIELD.type = 5
tb.PM_DSTSTAGESUM_TOTALSCORE_FIELD.cpp_type = 1
tb.PM_DSTSTAGESUM_STAGEINFO_FIELD.name = "stageInfo"
tb.PM_DSTSTAGESUM_STAGEINFO_FIELD.full_name = ".PM_DSTStageSum.stageInfo"
tb.PM_DSTSTAGESUM_STAGEINFO_FIELD.number = 3
tb.PM_DSTSTAGESUM_STAGEINFO_FIELD.index = 2
tb.PM_DSTSTAGESUM_STAGEINFO_FIELD.label = 3
tb.PM_DSTSTAGESUM_STAGEINFO_FIELD.has_default_value = false
tb.PM_DSTSTAGESUM_STAGEINFO_FIELD.default_value = {}
tb.PM_DSTSTAGESUM_STAGEINFO_FIELD.message_type = PM_DSTSTAGEDETAIL_MSG
tb.PM_DSTSTAGESUM_STAGEINFO_FIELD.type = 11
tb.PM_DSTSTAGESUM_STAGEINFO_FIELD.cpp_type = 10
PM_DSTSTAGESUM_MSG.name = "PM_DSTStageSum"
PM_DSTSTAGESUM_MSG.full_name = ".PM_DSTStageSum"
PM_DSTSTAGESUM_MSG.nested_types = {}
PM_DSTSTAGESUM_MSG.enum_types = {}
PM_DSTSTAGESUM_MSG.fields = {
	tb.PM_DSTSTAGESUM_STAGETYPE_FIELD,
	tb.PM_DSTSTAGESUM_TOTALSCORE_FIELD,
	tb.PM_DSTSTAGESUM_STAGEINFO_FIELD
}
PM_DSTSTAGESUM_MSG.is_extendable = false
PM_DSTSTAGESUM_MSG.extensions = {}
tb.PM_DSTSTAGECONDITION_CONDITIONID_FIELD.name = "conditionId"
tb.PM_DSTSTAGECONDITION_CONDITIONID_FIELD.full_name = ".PM_DSTStageCondition.conditionId"
tb.PM_DSTSTAGECONDITION_CONDITIONID_FIELD.number = 1
tb.PM_DSTSTAGECONDITION_CONDITIONID_FIELD.index = 0
tb.PM_DSTSTAGECONDITION_CONDITIONID_FIELD.label = 2
tb.PM_DSTSTAGECONDITION_CONDITIONID_FIELD.has_default_value = false
tb.PM_DSTSTAGECONDITION_CONDITIONID_FIELD.default_value = 0
tb.PM_DSTSTAGECONDITION_CONDITIONID_FIELD.type = 5
tb.PM_DSTSTAGECONDITION_CONDITIONID_FIELD.cpp_type = 1
tb.PM_DSTSTAGECONDITION_PARAM_FIELD.name = "param"
tb.PM_DSTSTAGECONDITION_PARAM_FIELD.full_name = ".PM_DSTStageCondition.param"
tb.PM_DSTSTAGECONDITION_PARAM_FIELD.number = 2
tb.PM_DSTSTAGECONDITION_PARAM_FIELD.index = 1
tb.PM_DSTSTAGECONDITION_PARAM_FIELD.label = 3
tb.PM_DSTSTAGECONDITION_PARAM_FIELD.has_default_value = false
tb.PM_DSTSTAGECONDITION_PARAM_FIELD.default_value = {}
tb.PM_DSTSTAGECONDITION_PARAM_FIELD.type = 9
tb.PM_DSTSTAGECONDITION_PARAM_FIELD.cpp_type = 9
tb.PM_DSTSTAGECONDITION_SCORE_FIELD.name = "score"
tb.PM_DSTSTAGECONDITION_SCORE_FIELD.full_name = ".PM_DSTStageCondition.score"
tb.PM_DSTSTAGECONDITION_SCORE_FIELD.number = 3
tb.PM_DSTSTAGECONDITION_SCORE_FIELD.index = 2
tb.PM_DSTSTAGECONDITION_SCORE_FIELD.label = 2
tb.PM_DSTSTAGECONDITION_SCORE_FIELD.has_default_value = false
tb.PM_DSTSTAGECONDITION_SCORE_FIELD.default_value = 0
tb.PM_DSTSTAGECONDITION_SCORE_FIELD.type = 5
tb.PM_DSTSTAGECONDITION_SCORE_FIELD.cpp_type = 1
PM_DSTSTAGECONDITION_MSG.name = "PM_DSTStageCondition"
PM_DSTSTAGECONDITION_MSG.full_name = ".PM_DSTStageCondition"
PM_DSTSTAGECONDITION_MSG.nested_types = {}
PM_DSTSTAGECONDITION_MSG.enum_types = {}
PM_DSTSTAGECONDITION_MSG.fields = {
	tb.PM_DSTSTAGECONDITION_CONDITIONID_FIELD,
	tb.PM_DSTSTAGECONDITION_PARAM_FIELD,
	tb.PM_DSTSTAGECONDITION_SCORE_FIELD
}
PM_DSTSTAGECONDITION_MSG.is_extendable = false
PM_DSTSTAGECONDITION_MSG.extensions = {}
PM_GODDISHITIANGETINFOREQ_MSG.name = "PM_GodDiShiTianGetInfoReq"
PM_GODDISHITIANGETINFOREQ_MSG.full_name = ".PM_GodDiShiTianGetInfoReq"
PM_GODDISHITIANGETINFOREQ_MSG.nested_types = {}
PM_GODDISHITIANGETINFOREQ_MSG.enum_types = {}
PM_GODDISHITIANGETINFOREQ_MSG.fields = {}
PM_GODDISHITIANGETINFOREQ_MSG.is_extendable = false
PM_GODDISHITIANGETINFOREQ_MSG.extensions = {}
tb.PM_GODDISHITIANGETINFORES_PASS_FIELD.name = "pass"
tb.PM_GODDISHITIANGETINFORES_PASS_FIELD.full_name = ".PM_GodDiShiTianGetInfoRes.pass"
tb.PM_GODDISHITIANGETINFORES_PASS_FIELD.number = 1
tb.PM_GODDISHITIANGETINFORES_PASS_FIELD.index = 0
tb.PM_GODDISHITIANGETINFORES_PASS_FIELD.label = 2
tb.PM_GODDISHITIANGETINFORES_PASS_FIELD.has_default_value = false
tb.PM_GODDISHITIANGETINFORES_PASS_FIELD.default_value = false
tb.PM_GODDISHITIANGETINFORES_PASS_FIELD.type = 8
tb.PM_GODDISHITIANGETINFORES_PASS_FIELD.cpp_type = 7
tb.PM_GODDISHITIANGETINFORES_STAGEINFO_FIELD.name = "stageInfo"
tb.PM_GODDISHITIANGETINFORES_STAGEINFO_FIELD.full_name = ".PM_GodDiShiTianGetInfoRes.stageInfo"
tb.PM_GODDISHITIANGETINFORES_STAGEINFO_FIELD.number = 2
tb.PM_GODDISHITIANGETINFORES_STAGEINFO_FIELD.index = 1
tb.PM_GODDISHITIANGETINFORES_STAGEINFO_FIELD.label = 3
tb.PM_GODDISHITIANGETINFORES_STAGEINFO_FIELD.has_default_value = false
tb.PM_GODDISHITIANGETINFORES_STAGEINFO_FIELD.default_value = {}
tb.PM_GODDISHITIANGETINFORES_STAGEINFO_FIELD.message_type = PM_DSTSTAGESUM_MSG
tb.PM_GODDISHITIANGETINFORES_STAGEINFO_FIELD.type = 11
tb.PM_GODDISHITIANGETINFORES_STAGEINFO_FIELD.cpp_type = 10
tb.PM_GODDISHITIANGETINFORES_SIMPLEFORM_FIELD.name = "simpleForm"
tb.PM_GODDISHITIANGETINFORES_SIMPLEFORM_FIELD.full_name = ".PM_GodDiShiTianGetInfoRes.simpleForm"
tb.PM_GODDISHITIANGETINFORES_SIMPLEFORM_FIELD.number = 3
tb.PM_GODDISHITIANGETINFORES_SIMPLEFORM_FIELD.index = 2
tb.PM_GODDISHITIANGETINFORES_SIMPLEFORM_FIELD.label = 2
tb.PM_GODDISHITIANGETINFORES_SIMPLEFORM_FIELD.has_default_value = false
tb.PM_GODDISHITIANGETINFORES_SIMPLEFORM_FIELD.default_value = nil
tb.PM_GODDISHITIANGETINFORES_SIMPLEFORM_FIELD.message_type = FORMATIONEXTENSION_PB.PM_SIMPLEFORM_MSG
tb.PM_GODDISHITIANGETINFORES_SIMPLEFORM_FIELD.type = 11
tb.PM_GODDISHITIANGETINFORES_SIMPLEFORM_FIELD.cpp_type = 10
PM_GODDISHITIANGETINFORES_MSG.name = "PM_GodDiShiTianGetInfoRes"
PM_GODDISHITIANGETINFORES_MSG.full_name = ".PM_GodDiShiTianGetInfoRes"
PM_GODDISHITIANGETINFORES_MSG.nested_types = {}
PM_GODDISHITIANGETINFORES_MSG.enum_types = {}
PM_GODDISHITIANGETINFORES_MSG.fields = {
	tb.PM_GODDISHITIANGETINFORES_PASS_FIELD,
	tb.PM_GODDISHITIANGETINFORES_STAGEINFO_FIELD,
	tb.PM_GODDISHITIANGETINFORES_SIMPLEFORM_FIELD
}
PM_GODDISHITIANGETINFORES_MSG.is_extendable = false
PM_GODDISHITIANGETINFORES_MSG.extensions = {}
tb.PM_GODDISHITIANCHALLENGEREQ_STAGEID_FIELD.name = "stageId"
tb.PM_GODDISHITIANCHALLENGEREQ_STAGEID_FIELD.full_name = ".PM_GodDiShiTianChallengeReq.stageId"
tb.PM_GODDISHITIANCHALLENGEREQ_STAGEID_FIELD.number = 1
tb.PM_GODDISHITIANCHALLENGEREQ_STAGEID_FIELD.index = 0
tb.PM_GODDISHITIANCHALLENGEREQ_STAGEID_FIELD.label = 2
tb.PM_GODDISHITIANCHALLENGEREQ_STAGEID_FIELD.has_default_value = false
tb.PM_GODDISHITIANCHALLENGEREQ_STAGEID_FIELD.default_value = 0
tb.PM_GODDISHITIANCHALLENGEREQ_STAGEID_FIELD.type = 5
tb.PM_GODDISHITIANCHALLENGEREQ_STAGEID_FIELD.cpp_type = 1
tb.PM_GODDISHITIANCHALLENGEREQ_SIMPLEFORM_FIELD.name = "simpleForm"
tb.PM_GODDISHITIANCHALLENGEREQ_SIMPLEFORM_FIELD.full_name = ".PM_GodDiShiTianChallengeReq.simpleForm"
tb.PM_GODDISHITIANCHALLENGEREQ_SIMPLEFORM_FIELD.number = 2
tb.PM_GODDISHITIANCHALLENGEREQ_SIMPLEFORM_FIELD.index = 1
tb.PM_GODDISHITIANCHALLENGEREQ_SIMPLEFORM_FIELD.label = 2
tb.PM_GODDISHITIANCHALLENGEREQ_SIMPLEFORM_FIELD.has_default_value = false
tb.PM_GODDISHITIANCHALLENGEREQ_SIMPLEFORM_FIELD.default_value = nil
tb.PM_GODDISHITIANCHALLENGEREQ_SIMPLEFORM_FIELD.message_type = FORMATIONEXTENSION_PB.PM_SIMPLEFORM_MSG
tb.PM_GODDISHITIANCHALLENGEREQ_SIMPLEFORM_FIELD.type = 11
tb.PM_GODDISHITIANCHALLENGEREQ_SIMPLEFORM_FIELD.cpp_type = 10
PM_GODDISHITIANCHALLENGEREQ_MSG.name = "PM_GodDiShiTianChallengeReq"
PM_GODDISHITIANCHALLENGEREQ_MSG.full_name = ".PM_GodDiShiTianChallengeReq"
PM_GODDISHITIANCHALLENGEREQ_MSG.nested_types = {}
PM_GODDISHITIANCHALLENGEREQ_MSG.enum_types = {}
PM_GODDISHITIANCHALLENGEREQ_MSG.fields = {
	tb.PM_GODDISHITIANCHALLENGEREQ_STAGEID_FIELD,
	tb.PM_GODDISHITIANCHALLENGEREQ_SIMPLEFORM_FIELD
}
PM_GODDISHITIANCHALLENGEREQ_MSG.is_extendable = false
PM_GODDISHITIANCHALLENGEREQ_MSG.extensions = {}
PM_GODDISHITIANCHALLENGERES_MSG.name = "PM_GodDiShiTianChallengeRes"
PM_GODDISHITIANCHALLENGERES_MSG.full_name = ".PM_GodDiShiTianChallengeRes"
PM_GODDISHITIANCHALLENGERES_MSG.nested_types = {}
PM_GODDISHITIANCHALLENGERES_MSG.enum_types = {}
PM_GODDISHITIANCHALLENGERES_MSG.fields = {}
PM_GODDISHITIANCHALLENGERES_MSG.is_extendable = false
PM_GODDISHITIANCHALLENGERES_MSG.extensions = {}
tb.PM_GODDISHITIANSETSCOREREQ_STAGEID_FIELD.name = "stageId"
tb.PM_GODDISHITIANSETSCOREREQ_STAGEID_FIELD.full_name = ".PM_GodDiShiTianSetScoreReq.stageId"
tb.PM_GODDISHITIANSETSCOREREQ_STAGEID_FIELD.number = 1
tb.PM_GODDISHITIANSETSCOREREQ_STAGEID_FIELD.index = 0
tb.PM_GODDISHITIANSETSCOREREQ_STAGEID_FIELD.label = 2
tb.PM_GODDISHITIANSETSCOREREQ_STAGEID_FIELD.has_default_value = false
tb.PM_GODDISHITIANSETSCOREREQ_STAGEID_FIELD.default_value = 0
tb.PM_GODDISHITIANSETSCOREREQ_STAGEID_FIELD.type = 5
tb.PM_GODDISHITIANSETSCOREREQ_STAGEID_FIELD.cpp_type = 1
PM_GODDISHITIANSETSCOREREQ_MSG.name = "PM_GodDiShiTianSetScoreReq"
PM_GODDISHITIANSETSCOREREQ_MSG.full_name = ".PM_GodDiShiTianSetScoreReq"
PM_GODDISHITIANSETSCOREREQ_MSG.nested_types = {}
PM_GODDISHITIANSETSCOREREQ_MSG.enum_types = {}
PM_GODDISHITIANSETSCOREREQ_MSG.fields = {
	tb.PM_GODDISHITIANSETSCOREREQ_STAGEID_FIELD
}
PM_GODDISHITIANSETSCOREREQ_MSG.is_extendable = false
PM_GODDISHITIANSETSCOREREQ_MSG.extensions = {}
tb.PM_GODDISHITIANSETSCORERES_STAGEID_FIELD.name = "stageId"
tb.PM_GODDISHITIANSETSCORERES_STAGEID_FIELD.full_name = ".PM_GodDiShiTianSetScoreRes.stageId"
tb.PM_GODDISHITIANSETSCORERES_STAGEID_FIELD.number = 1
tb.PM_GODDISHITIANSETSCORERES_STAGEID_FIELD.index = 0
tb.PM_GODDISHITIANSETSCORERES_STAGEID_FIELD.label = 2
tb.PM_GODDISHITIANSETSCORERES_STAGEID_FIELD.has_default_value = false
tb.PM_GODDISHITIANSETSCORERES_STAGEID_FIELD.default_value = 0
tb.PM_GODDISHITIANSETSCORERES_STAGEID_FIELD.type = 5
tb.PM_GODDISHITIANSETSCORERES_STAGEID_FIELD.cpp_type = 1
tb.PM_GODDISHITIANSETSCORERES_SCORE_FIELD.name = "score"
tb.PM_GODDISHITIANSETSCORERES_SCORE_FIELD.full_name = ".PM_GodDiShiTianSetScoreRes.score"
tb.PM_GODDISHITIANSETSCORERES_SCORE_FIELD.number = 2
tb.PM_GODDISHITIANSETSCORERES_SCORE_FIELD.index = 1
tb.PM_GODDISHITIANSETSCORERES_SCORE_FIELD.label = 2
tb.PM_GODDISHITIANSETSCORERES_SCORE_FIELD.has_default_value = false
tb.PM_GODDISHITIANSETSCORERES_SCORE_FIELD.default_value = 0
tb.PM_GODDISHITIANSETSCORERES_SCORE_FIELD.type = 5
tb.PM_GODDISHITIANSETSCORERES_SCORE_FIELD.cpp_type = 1
PM_GODDISHITIANSETSCORERES_MSG.name = "PM_GodDiShiTianSetScoreRes"
PM_GODDISHITIANSETSCORERES_MSG.full_name = ".PM_GodDiShiTianSetScoreRes"
PM_GODDISHITIANSETSCORERES_MSG.nested_types = {}
PM_GODDISHITIANSETSCORERES_MSG.enum_types = {}
PM_GODDISHITIANSETSCORERES_MSG.fields = {
	tb.PM_GODDISHITIANSETSCORERES_STAGEID_FIELD,
	tb.PM_GODDISHITIANSETSCORERES_SCORE_FIELD
}
PM_GODDISHITIANSETSCORERES_MSG.is_extendable = false
PM_GODDISHITIANSETSCORERES_MSG.extensions = {}
PM_GODDISHITIANQUICKPASSREQ_MSG.name = "PM_GodDiShiTianQuickPassReq"
PM_GODDISHITIANQUICKPASSREQ_MSG.full_name = ".PM_GodDiShiTianQuickPassReq"
PM_GODDISHITIANQUICKPASSREQ_MSG.nested_types = {}
PM_GODDISHITIANQUICKPASSREQ_MSG.enum_types = {}
PM_GODDISHITIANQUICKPASSREQ_MSG.fields = {}
PM_GODDISHITIANQUICKPASSREQ_MSG.is_extendable = false
PM_GODDISHITIANQUICKPASSREQ_MSG.extensions = {}
tb.PM_GODDISHITIANQUICKPASSRES_PASS_FIELD.name = "pass"
tb.PM_GODDISHITIANQUICKPASSRES_PASS_FIELD.full_name = ".PM_GodDiShiTianQuickPassRes.pass"
tb.PM_GODDISHITIANQUICKPASSRES_PASS_FIELD.number = 1
tb.PM_GODDISHITIANQUICKPASSRES_PASS_FIELD.index = 0
tb.PM_GODDISHITIANQUICKPASSRES_PASS_FIELD.label = 2
tb.PM_GODDISHITIANQUICKPASSRES_PASS_FIELD.has_default_value = false
tb.PM_GODDISHITIANQUICKPASSRES_PASS_FIELD.default_value = false
tb.PM_GODDISHITIANQUICKPASSRES_PASS_FIELD.type = 8
tb.PM_GODDISHITIANQUICKPASSRES_PASS_FIELD.cpp_type = 7
tb.PM_GODDISHITIANQUICKPASSRES_CHANGESETID_FIELD.name = "changeSetId"
tb.PM_GODDISHITIANQUICKPASSRES_CHANGESETID_FIELD.full_name = ".PM_GodDiShiTianQuickPassRes.changeSetId"
tb.PM_GODDISHITIANQUICKPASSRES_CHANGESETID_FIELD.number = 2
tb.PM_GODDISHITIANQUICKPASSRES_CHANGESETID_FIELD.index = 1
tb.PM_GODDISHITIANQUICKPASSRES_CHANGESETID_FIELD.label = 1
tb.PM_GODDISHITIANQUICKPASSRES_CHANGESETID_FIELD.has_default_value = false
tb.PM_GODDISHITIANQUICKPASSRES_CHANGESETID_FIELD.default_value = 0
tb.PM_GODDISHITIANQUICKPASSRES_CHANGESETID_FIELD.type = 5
tb.PM_GODDISHITIANQUICKPASSRES_CHANGESETID_FIELD.cpp_type = 1
PM_GODDISHITIANQUICKPASSRES_MSG.name = "PM_GodDiShiTianQuickPassRes"
PM_GODDISHITIANQUICKPASSRES_MSG.full_name = ".PM_GodDiShiTianQuickPassRes"
PM_GODDISHITIANQUICKPASSRES_MSG.nested_types = {}
PM_GODDISHITIANQUICKPASSRES_MSG.enum_types = {}
PM_GODDISHITIANQUICKPASSRES_MSG.fields = {
	tb.PM_GODDISHITIANQUICKPASSRES_PASS_FIELD,
	tb.PM_GODDISHITIANQUICKPASSRES_CHANGESETID_FIELD
}
PM_GODDISHITIANQUICKPASSRES_MSG.is_extendable = false
PM_GODDISHITIANQUICKPASSRES_MSG.extensions = {}
tb.PM_GODDISHITIANSTAGEOVERRES_STAGEID_FIELD.name = "stageId"
tb.PM_GODDISHITIANSTAGEOVERRES_STAGEID_FIELD.full_name = ".PM_GodDiShiTianStageOverRes.stageId"
tb.PM_GODDISHITIANSTAGEOVERRES_STAGEID_FIELD.number = 1
tb.PM_GODDISHITIANSTAGEOVERRES_STAGEID_FIELD.index = 0
tb.PM_GODDISHITIANSTAGEOVERRES_STAGEID_FIELD.label = 2
tb.PM_GODDISHITIANSTAGEOVERRES_STAGEID_FIELD.has_default_value = false
tb.PM_GODDISHITIANSTAGEOVERRES_STAGEID_FIELD.default_value = 0
tb.PM_GODDISHITIANSTAGEOVERRES_STAGEID_FIELD.type = 5
tb.PM_GODDISHITIANSTAGEOVERRES_STAGEID_FIELD.cpp_type = 1
tb.PM_GODDISHITIANSTAGEOVERRES_SCORE_FIELD.name = "score"
tb.PM_GODDISHITIANSTAGEOVERRES_SCORE_FIELD.full_name = ".PM_GodDiShiTianStageOverRes.score"
tb.PM_GODDISHITIANSTAGEOVERRES_SCORE_FIELD.number = 2
tb.PM_GODDISHITIANSTAGEOVERRES_SCORE_FIELD.index = 1
tb.PM_GODDISHITIANSTAGEOVERRES_SCORE_FIELD.label = 2
tb.PM_GODDISHITIANSTAGEOVERRES_SCORE_FIELD.has_default_value = false
tb.PM_GODDISHITIANSTAGEOVERRES_SCORE_FIELD.default_value = 0
tb.PM_GODDISHITIANSTAGEOVERRES_SCORE_FIELD.type = 5
tb.PM_GODDISHITIANSTAGEOVERRES_SCORE_FIELD.cpp_type = 1
tb.PM_GODDISHITIANSTAGEOVERRES_CONDITION_FIELD.name = "condition"
tb.PM_GODDISHITIANSTAGEOVERRES_CONDITION_FIELD.full_name = ".PM_GodDiShiTianStageOverRes.condition"
tb.PM_GODDISHITIANSTAGEOVERRES_CONDITION_FIELD.number = 3
tb.PM_GODDISHITIANSTAGEOVERRES_CONDITION_FIELD.index = 2
tb.PM_GODDISHITIANSTAGEOVERRES_CONDITION_FIELD.label = 3
tb.PM_GODDISHITIANSTAGEOVERRES_CONDITION_FIELD.has_default_value = false
tb.PM_GODDISHITIANSTAGEOVERRES_CONDITION_FIELD.default_value = {}
tb.PM_GODDISHITIANSTAGEOVERRES_CONDITION_FIELD.message_type = PM_DSTSTAGECONDITION_MSG
tb.PM_GODDISHITIANSTAGEOVERRES_CONDITION_FIELD.type = 11
tb.PM_GODDISHITIANSTAGEOVERRES_CONDITION_FIELD.cpp_type = 10
tb.PM_GODDISHITIANSTAGEOVERRES_PASS_FIELD.name = "pass"
tb.PM_GODDISHITIANSTAGEOVERRES_PASS_FIELD.full_name = ".PM_GodDiShiTianStageOverRes.pass"
tb.PM_GODDISHITIANSTAGEOVERRES_PASS_FIELD.number = 4
tb.PM_GODDISHITIANSTAGEOVERRES_PASS_FIELD.index = 3
tb.PM_GODDISHITIANSTAGEOVERRES_PASS_FIELD.label = 1
tb.PM_GODDISHITIANSTAGEOVERRES_PASS_FIELD.has_default_value = false
tb.PM_GODDISHITIANSTAGEOVERRES_PASS_FIELD.default_value = false
tb.PM_GODDISHITIANSTAGEOVERRES_PASS_FIELD.type = 8
tb.PM_GODDISHITIANSTAGEOVERRES_PASS_FIELD.cpp_type = 7
tb.PM_GODDISHITIANSTAGEOVERRES_TOTALSCORE_FIELD.name = "totalScore"
tb.PM_GODDISHITIANSTAGEOVERRES_TOTALSCORE_FIELD.full_name = ".PM_GodDiShiTianStageOverRes.totalScore"
tb.PM_GODDISHITIANSTAGEOVERRES_TOTALSCORE_FIELD.number = 5
tb.PM_GODDISHITIANSTAGEOVERRES_TOTALSCORE_FIELD.index = 4
tb.PM_GODDISHITIANSTAGEOVERRES_TOTALSCORE_FIELD.label = 2
tb.PM_GODDISHITIANSTAGEOVERRES_TOTALSCORE_FIELD.has_default_value = false
tb.PM_GODDISHITIANSTAGEOVERRES_TOTALSCORE_FIELD.default_value = 0
tb.PM_GODDISHITIANSTAGEOVERRES_TOTALSCORE_FIELD.type = 5
tb.PM_GODDISHITIANSTAGEOVERRES_TOTALSCORE_FIELD.cpp_type = 1
tb.PM_GODDISHITIANSTAGEOVERRES_WIN_FIELD.name = "win"
tb.PM_GODDISHITIANSTAGEOVERRES_WIN_FIELD.full_name = ".PM_GodDiShiTianStageOverRes.win"
tb.PM_GODDISHITIANSTAGEOVERRES_WIN_FIELD.number = 6
tb.PM_GODDISHITIANSTAGEOVERRES_WIN_FIELD.index = 5
tb.PM_GODDISHITIANSTAGEOVERRES_WIN_FIELD.label = 2
tb.PM_GODDISHITIANSTAGEOVERRES_WIN_FIELD.has_default_value = false
tb.PM_GODDISHITIANSTAGEOVERRES_WIN_FIELD.default_value = false
tb.PM_GODDISHITIANSTAGEOVERRES_WIN_FIELD.type = 8
tb.PM_GODDISHITIANSTAGEOVERRES_WIN_FIELD.cpp_type = 7
PM_GODDISHITIANSTAGEOVERRES_MSG.name = "PM_GodDiShiTianStageOverRes"
PM_GODDISHITIANSTAGEOVERRES_MSG.full_name = ".PM_GodDiShiTianStageOverRes"
PM_GODDISHITIANSTAGEOVERRES_MSG.nested_types = {}
PM_GODDISHITIANSTAGEOVERRES_MSG.enum_types = {}
PM_GODDISHITIANSTAGEOVERRES_MSG.fields = {
	tb.PM_GODDISHITIANSTAGEOVERRES_STAGEID_FIELD,
	tb.PM_GODDISHITIANSTAGEOVERRES_SCORE_FIELD,
	tb.PM_GODDISHITIANSTAGEOVERRES_CONDITION_FIELD,
	tb.PM_GODDISHITIANSTAGEOVERRES_PASS_FIELD,
	tb.PM_GODDISHITIANSTAGEOVERRES_TOTALSCORE_FIELD,
	tb.PM_GODDISHITIANSTAGEOVERRES_WIN_FIELD
}
PM_GODDISHITIANSTAGEOVERRES_MSG.is_extendable = false
PM_GODDISHITIANSTAGEOVERRES_MSG.extensions = {}
PM_DSTStageCondition = protobuf.Message(PM_DSTSTAGECONDITION_MSG)
PM_DSTStageDetail = protobuf.Message(PM_DSTSTAGEDETAIL_MSG)
PM_DSTStageSum = protobuf.Message(PM_DSTSTAGESUM_MSG)
PM_GodDiShiTianChallengeReq = protobuf.Message(PM_GODDISHITIANCHALLENGEREQ_MSG)
PM_GodDiShiTianChallengeRes = protobuf.Message(PM_GODDISHITIANCHALLENGERES_MSG)
PM_GodDiShiTianGetInfoReq = protobuf.Message(PM_GODDISHITIANGETINFOREQ_MSG)
PM_GodDiShiTianGetInfoRes = protobuf.Message(PM_GODDISHITIANGETINFORES_MSG)
PM_GodDiShiTianQuickPassReq = protobuf.Message(PM_GODDISHITIANQUICKPASSREQ_MSG)
PM_GodDiShiTianQuickPassRes = protobuf.Message(PM_GODDISHITIANQUICKPASSRES_MSG)
PM_GodDiShiTianSetScoreReq = protobuf.Message(PM_GODDISHITIANSETSCOREREQ_MSG)
PM_GodDiShiTianSetScoreRes = protobuf.Message(PM_GODDISHITIANSETSCORERES_MSG)
PM_GodDiShiTianStageOverRes = protobuf.Message(PM_GODDISHITIANSTAGEOVERRES_MSG)

return _G["logic.proto.GodDiShiTianExtension_pb"]
