-- chunkname: @C:/GitLab-Runner/builds/sTUwNpCg/0/aqmobile/aqmobile-client/UnityProj/Assets/Scripts/Lua/logic/proto/NeverLandExtension_pb.lua

local protobuf = require("protobuf.protobuf")
local FORMATIONEXTENSION_PB = require("logic.proto.FormationExtension_pb")
local COMMONRANKEXTENSION_PB = require("logic.proto.CommonRankExtension_pb")

module("logic.proto.NeverLandExtension_pb", package.seeall)

local tb = {}

PM_NEVERLANDINFOREQ_MSG = protobuf.Descriptor()
tb.PM_NEVERLANDINFOREQ_ACTIVITYID_FIELD = protobuf.FieldDescriptor()
PM_NEVERLANDINFORES_MSG = protobuf.Descriptor()
tb.PM_NEVERLANDINFORES_BUFFINFOS_FIELD = protobuf.FieldDescriptor()
tb.PM_NEVERLANDINFORES_ATTACKSCORE_FIELD = protobuf.FieldDescriptor()
tb.PM_NEVERLANDINFORES_DEFENSESCORE_FIELD = protobuf.FieldDescriptor()
PM_NEVERLANDBUFFINFO_MSG = protobuf.Descriptor()
tb.PM_NEVERLANDBUFFINFO_BUFFID_FIELD = protobuf.FieldDescriptor()
tb.PM_NEVERLANDBUFFINFO_LV_FIELD = protobuf.FieldDescriptor()
PM_NEVERLANDCHALLENGEREQ_MSG = protobuf.Descriptor()
tb.PM_NEVERLANDCHALLENGEREQ_ACTIVITYID_FIELD = protobuf.FieldDescriptor()
tb.PM_NEVERLANDCHALLENGEREQ_MODE_FIELD = protobuf.FieldDescriptor()
tb.PM_NEVERLANDCHALLENGEREQ_FORM_FIELD = protobuf.FieldDescriptor()
PM_NEVERLANDNOTIFYCHALLENGERESULTRES_MSG = protobuf.Descriptor()
tb.PM_NEVERLANDNOTIFYCHALLENGERESULTRES_SCORE_FIELD = protobuf.FieldDescriptor()
PM_NEVERLANDCHALLENGERES_MSG = protobuf.Descriptor()
PM_NEVERLANDUPGRADEBUFFLVREQ_MSG = protobuf.Descriptor()
tb.PM_NEVERLANDUPGRADEBUFFLVREQ_ACTIVITYID_FIELD = protobuf.FieldDescriptor()
tb.PM_NEVERLANDUPGRADEBUFFLVREQ_BUFFID_FIELD = protobuf.FieldDescriptor()
PM_NEVERLANDUPGRADEBUFFLVRES_MSG = protobuf.Descriptor()
PM_NEVERLANDGETRANKREQ_MSG = protobuf.Descriptor()
tb.PM_NEVERLANDGETRANKREQ_ACTIVITYID_FIELD = protobuf.FieldDescriptor()
tb.PM_NEVERLANDGETRANKREQ_MODE_FIELD = protobuf.FieldDescriptor()
PM_NEVERLANDGETRANKRES_MSG = protobuf.Descriptor()
tb.PM_NEVERLANDGETRANKRES_RANKINFOS_FIELD = protobuf.FieldDescriptor()
tb.PM_NEVERLANDGETRANKRES_MYRANK_FIELD = protobuf.FieldDescriptor()
tb.PM_NEVERLANDINFOREQ_ACTIVITYID_FIELD.name = "activityId"
tb.PM_NEVERLANDINFOREQ_ACTIVITYID_FIELD.full_name = ".PM_NeverLandInfoReq.activityId"
tb.PM_NEVERLANDINFOREQ_ACTIVITYID_FIELD.number = 1
tb.PM_NEVERLANDINFOREQ_ACTIVITYID_FIELD.index = 0
tb.PM_NEVERLANDINFOREQ_ACTIVITYID_FIELD.label = 2
tb.PM_NEVERLANDINFOREQ_ACTIVITYID_FIELD.has_default_value = false
tb.PM_NEVERLANDINFOREQ_ACTIVITYID_FIELD.default_value = 0
tb.PM_NEVERLANDINFOREQ_ACTIVITYID_FIELD.type = 5
tb.PM_NEVERLANDINFOREQ_ACTIVITYID_FIELD.cpp_type = 1
PM_NEVERLANDINFOREQ_MSG.name = "PM_NeverLandInfoReq"
PM_NEVERLANDINFOREQ_MSG.full_name = ".PM_NeverLandInfoReq"
PM_NEVERLANDINFOREQ_MSG.nested_types = {}
PM_NEVERLANDINFOREQ_MSG.enum_types = {}
PM_NEVERLANDINFOREQ_MSG.fields = {
	tb.PM_NEVERLANDINFOREQ_ACTIVITYID_FIELD
}
PM_NEVERLANDINFOREQ_MSG.is_extendable = false
PM_NEVERLANDINFOREQ_MSG.extensions = {}
tb.PM_NEVERLANDINFORES_BUFFINFOS_FIELD.name = "buffInfos"
tb.PM_NEVERLANDINFORES_BUFFINFOS_FIELD.full_name = ".PM_NeverLandInfoRes.buffInfos"
tb.PM_NEVERLANDINFORES_BUFFINFOS_FIELD.number = 1
tb.PM_NEVERLANDINFORES_BUFFINFOS_FIELD.index = 0
tb.PM_NEVERLANDINFORES_BUFFINFOS_FIELD.label = 3
tb.PM_NEVERLANDINFORES_BUFFINFOS_FIELD.has_default_value = false
tb.PM_NEVERLANDINFORES_BUFFINFOS_FIELD.default_value = {}
tb.PM_NEVERLANDINFORES_BUFFINFOS_FIELD.message_type = PM_NEVERLANDBUFFINFO_MSG
tb.PM_NEVERLANDINFORES_BUFFINFOS_FIELD.type = 11
tb.PM_NEVERLANDINFORES_BUFFINFOS_FIELD.cpp_type = 10
tb.PM_NEVERLANDINFORES_ATTACKSCORE_FIELD.name = "attackScore"
tb.PM_NEVERLANDINFORES_ATTACKSCORE_FIELD.full_name = ".PM_NeverLandInfoRes.attackScore"
tb.PM_NEVERLANDINFORES_ATTACKSCORE_FIELD.number = 2
tb.PM_NEVERLANDINFORES_ATTACKSCORE_FIELD.index = 1
tb.PM_NEVERLANDINFORES_ATTACKSCORE_FIELD.label = 2
tb.PM_NEVERLANDINFORES_ATTACKSCORE_FIELD.has_default_value = false
tb.PM_NEVERLANDINFORES_ATTACKSCORE_FIELD.default_value = 0
tb.PM_NEVERLANDINFORES_ATTACKSCORE_FIELD.type = 5
tb.PM_NEVERLANDINFORES_ATTACKSCORE_FIELD.cpp_type = 1
tb.PM_NEVERLANDINFORES_DEFENSESCORE_FIELD.name = "defenseScore"
tb.PM_NEVERLANDINFORES_DEFENSESCORE_FIELD.full_name = ".PM_NeverLandInfoRes.defenseScore"
tb.PM_NEVERLANDINFORES_DEFENSESCORE_FIELD.number = 3
tb.PM_NEVERLANDINFORES_DEFENSESCORE_FIELD.index = 2
tb.PM_NEVERLANDINFORES_DEFENSESCORE_FIELD.label = 2
tb.PM_NEVERLANDINFORES_DEFENSESCORE_FIELD.has_default_value = false
tb.PM_NEVERLANDINFORES_DEFENSESCORE_FIELD.default_value = 0
tb.PM_NEVERLANDINFORES_DEFENSESCORE_FIELD.type = 5
tb.PM_NEVERLANDINFORES_DEFENSESCORE_FIELD.cpp_type = 1
PM_NEVERLANDINFORES_MSG.name = "PM_NeverLandInfoRes"
PM_NEVERLANDINFORES_MSG.full_name = ".PM_NeverLandInfoRes"
PM_NEVERLANDINFORES_MSG.nested_types = {}
PM_NEVERLANDINFORES_MSG.enum_types = {}
PM_NEVERLANDINFORES_MSG.fields = {
	tb.PM_NEVERLANDINFORES_BUFFINFOS_FIELD,
	tb.PM_NEVERLANDINFORES_ATTACKSCORE_FIELD,
	tb.PM_NEVERLANDINFORES_DEFENSESCORE_FIELD
}
PM_NEVERLANDINFORES_MSG.is_extendable = false
PM_NEVERLANDINFORES_MSG.extensions = {}
tb.PM_NEVERLANDBUFFINFO_BUFFID_FIELD.name = "buffId"
tb.PM_NEVERLANDBUFFINFO_BUFFID_FIELD.full_name = ".PM_NeverLandBuffInfo.buffId"
tb.PM_NEVERLANDBUFFINFO_BUFFID_FIELD.number = 1
tb.PM_NEVERLANDBUFFINFO_BUFFID_FIELD.index = 0
tb.PM_NEVERLANDBUFFINFO_BUFFID_FIELD.label = 2
tb.PM_NEVERLANDBUFFINFO_BUFFID_FIELD.has_default_value = false
tb.PM_NEVERLANDBUFFINFO_BUFFID_FIELD.default_value = 0
tb.PM_NEVERLANDBUFFINFO_BUFFID_FIELD.type = 5
tb.PM_NEVERLANDBUFFINFO_BUFFID_FIELD.cpp_type = 1
tb.PM_NEVERLANDBUFFINFO_LV_FIELD.name = "lv"
tb.PM_NEVERLANDBUFFINFO_LV_FIELD.full_name = ".PM_NeverLandBuffInfo.lv"
tb.PM_NEVERLANDBUFFINFO_LV_FIELD.number = 2
tb.PM_NEVERLANDBUFFINFO_LV_FIELD.index = 1
tb.PM_NEVERLANDBUFFINFO_LV_FIELD.label = 2
tb.PM_NEVERLANDBUFFINFO_LV_FIELD.has_default_value = false
tb.PM_NEVERLANDBUFFINFO_LV_FIELD.default_value = 0
tb.PM_NEVERLANDBUFFINFO_LV_FIELD.type = 5
tb.PM_NEVERLANDBUFFINFO_LV_FIELD.cpp_type = 1
PM_NEVERLANDBUFFINFO_MSG.name = "PM_NeverLandBuffInfo"
PM_NEVERLANDBUFFINFO_MSG.full_name = ".PM_NeverLandBuffInfo"
PM_NEVERLANDBUFFINFO_MSG.nested_types = {}
PM_NEVERLANDBUFFINFO_MSG.enum_types = {}
PM_NEVERLANDBUFFINFO_MSG.fields = {
	tb.PM_NEVERLANDBUFFINFO_BUFFID_FIELD,
	tb.PM_NEVERLANDBUFFINFO_LV_FIELD
}
PM_NEVERLANDBUFFINFO_MSG.is_extendable = false
PM_NEVERLANDBUFFINFO_MSG.extensions = {}
tb.PM_NEVERLANDCHALLENGEREQ_ACTIVITYID_FIELD.name = "activityId"
tb.PM_NEVERLANDCHALLENGEREQ_ACTIVITYID_FIELD.full_name = ".PM_NeverLandChallengeReq.activityId"
tb.PM_NEVERLANDCHALLENGEREQ_ACTIVITYID_FIELD.number = 1
tb.PM_NEVERLANDCHALLENGEREQ_ACTIVITYID_FIELD.index = 0
tb.PM_NEVERLANDCHALLENGEREQ_ACTIVITYID_FIELD.label = 2
tb.PM_NEVERLANDCHALLENGEREQ_ACTIVITYID_FIELD.has_default_value = false
tb.PM_NEVERLANDCHALLENGEREQ_ACTIVITYID_FIELD.default_value = 0
tb.PM_NEVERLANDCHALLENGEREQ_ACTIVITYID_FIELD.type = 5
tb.PM_NEVERLANDCHALLENGEREQ_ACTIVITYID_FIELD.cpp_type = 1
tb.PM_NEVERLANDCHALLENGEREQ_MODE_FIELD.name = "mode"
tb.PM_NEVERLANDCHALLENGEREQ_MODE_FIELD.full_name = ".PM_NeverLandChallengeReq.mode"
tb.PM_NEVERLANDCHALLENGEREQ_MODE_FIELD.number = 2
tb.PM_NEVERLANDCHALLENGEREQ_MODE_FIELD.index = 1
tb.PM_NEVERLANDCHALLENGEREQ_MODE_FIELD.label = 2
tb.PM_NEVERLANDCHALLENGEREQ_MODE_FIELD.has_default_value = false
tb.PM_NEVERLANDCHALLENGEREQ_MODE_FIELD.default_value = ""
tb.PM_NEVERLANDCHALLENGEREQ_MODE_FIELD.type = 9
tb.PM_NEVERLANDCHALLENGEREQ_MODE_FIELD.cpp_type = 9
tb.PM_NEVERLANDCHALLENGEREQ_FORM_FIELD.name = "form"
tb.PM_NEVERLANDCHALLENGEREQ_FORM_FIELD.full_name = ".PM_NeverLandChallengeReq.form"
tb.PM_NEVERLANDCHALLENGEREQ_FORM_FIELD.number = 3
tb.PM_NEVERLANDCHALLENGEREQ_FORM_FIELD.index = 2
tb.PM_NEVERLANDCHALLENGEREQ_FORM_FIELD.label = 2
tb.PM_NEVERLANDCHALLENGEREQ_FORM_FIELD.has_default_value = false
tb.PM_NEVERLANDCHALLENGEREQ_FORM_FIELD.default_value = nil
tb.PM_NEVERLANDCHALLENGEREQ_FORM_FIELD.message_type = FORMATIONEXTENSION_PB.PM_SIMPLEFORM_MSG
tb.PM_NEVERLANDCHALLENGEREQ_FORM_FIELD.type = 11
tb.PM_NEVERLANDCHALLENGEREQ_FORM_FIELD.cpp_type = 10
PM_NEVERLANDCHALLENGEREQ_MSG.name = "PM_NeverLandChallengeReq"
PM_NEVERLANDCHALLENGEREQ_MSG.full_name = ".PM_NeverLandChallengeReq"
PM_NEVERLANDCHALLENGEREQ_MSG.nested_types = {}
PM_NEVERLANDCHALLENGEREQ_MSG.enum_types = {}
PM_NEVERLANDCHALLENGEREQ_MSG.fields = {
	tb.PM_NEVERLANDCHALLENGEREQ_ACTIVITYID_FIELD,
	tb.PM_NEVERLANDCHALLENGEREQ_MODE_FIELD,
	tb.PM_NEVERLANDCHALLENGEREQ_FORM_FIELD
}
PM_NEVERLANDCHALLENGEREQ_MSG.is_extendable = false
PM_NEVERLANDCHALLENGEREQ_MSG.extensions = {}
tb.PM_NEVERLANDNOTIFYCHALLENGERESULTRES_SCORE_FIELD.name = "score"
tb.PM_NEVERLANDNOTIFYCHALLENGERESULTRES_SCORE_FIELD.full_name = ".PM_NeverLandNotifyChallengeResultRes.score"
tb.PM_NEVERLANDNOTIFYCHALLENGERESULTRES_SCORE_FIELD.number = 1
tb.PM_NEVERLANDNOTIFYCHALLENGERESULTRES_SCORE_FIELD.index = 0
tb.PM_NEVERLANDNOTIFYCHALLENGERESULTRES_SCORE_FIELD.label = 2
tb.PM_NEVERLANDNOTIFYCHALLENGERESULTRES_SCORE_FIELD.has_default_value = false
tb.PM_NEVERLANDNOTIFYCHALLENGERESULTRES_SCORE_FIELD.default_value = 0
tb.PM_NEVERLANDNOTIFYCHALLENGERESULTRES_SCORE_FIELD.type = 5
tb.PM_NEVERLANDNOTIFYCHALLENGERESULTRES_SCORE_FIELD.cpp_type = 1
PM_NEVERLANDNOTIFYCHALLENGERESULTRES_MSG.name = "PM_NeverLandNotifyChallengeResultRes"
PM_NEVERLANDNOTIFYCHALLENGERESULTRES_MSG.full_name = ".PM_NeverLandNotifyChallengeResultRes"
PM_NEVERLANDNOTIFYCHALLENGERESULTRES_MSG.nested_types = {}
PM_NEVERLANDNOTIFYCHALLENGERESULTRES_MSG.enum_types = {}
PM_NEVERLANDNOTIFYCHALLENGERESULTRES_MSG.fields = {
	tb.PM_NEVERLANDNOTIFYCHALLENGERESULTRES_SCORE_FIELD
}
PM_NEVERLANDNOTIFYCHALLENGERESULTRES_MSG.is_extendable = false
PM_NEVERLANDNOTIFYCHALLENGERESULTRES_MSG.extensions = {}
PM_NEVERLANDCHALLENGERES_MSG.name = "PM_NeverLandChallengeRes"
PM_NEVERLANDCHALLENGERES_MSG.full_name = ".PM_NeverLandChallengeRes"
PM_NEVERLANDCHALLENGERES_MSG.nested_types = {}
PM_NEVERLANDCHALLENGERES_MSG.enum_types = {}
PM_NEVERLANDCHALLENGERES_MSG.fields = {}
PM_NEVERLANDCHALLENGERES_MSG.is_extendable = false
PM_NEVERLANDCHALLENGERES_MSG.extensions = {}
tb.PM_NEVERLANDUPGRADEBUFFLVREQ_ACTIVITYID_FIELD.name = "activityId"
tb.PM_NEVERLANDUPGRADEBUFFLVREQ_ACTIVITYID_FIELD.full_name = ".PM_NeverLandUpgradeBuffLvReq.activityId"
tb.PM_NEVERLANDUPGRADEBUFFLVREQ_ACTIVITYID_FIELD.number = 1
tb.PM_NEVERLANDUPGRADEBUFFLVREQ_ACTIVITYID_FIELD.index = 0
tb.PM_NEVERLANDUPGRADEBUFFLVREQ_ACTIVITYID_FIELD.label = 2
tb.PM_NEVERLANDUPGRADEBUFFLVREQ_ACTIVITYID_FIELD.has_default_value = false
tb.PM_NEVERLANDUPGRADEBUFFLVREQ_ACTIVITYID_FIELD.default_value = 0
tb.PM_NEVERLANDUPGRADEBUFFLVREQ_ACTIVITYID_FIELD.type = 5
tb.PM_NEVERLANDUPGRADEBUFFLVREQ_ACTIVITYID_FIELD.cpp_type = 1
tb.PM_NEVERLANDUPGRADEBUFFLVREQ_BUFFID_FIELD.name = "buffId"
tb.PM_NEVERLANDUPGRADEBUFFLVREQ_BUFFID_FIELD.full_name = ".PM_NeverLandUpgradeBuffLvReq.buffId"
tb.PM_NEVERLANDUPGRADEBUFFLVREQ_BUFFID_FIELD.number = 2
tb.PM_NEVERLANDUPGRADEBUFFLVREQ_BUFFID_FIELD.index = 1
tb.PM_NEVERLANDUPGRADEBUFFLVREQ_BUFFID_FIELD.label = 2
tb.PM_NEVERLANDUPGRADEBUFFLVREQ_BUFFID_FIELD.has_default_value = false
tb.PM_NEVERLANDUPGRADEBUFFLVREQ_BUFFID_FIELD.default_value = 0
tb.PM_NEVERLANDUPGRADEBUFFLVREQ_BUFFID_FIELD.type = 5
tb.PM_NEVERLANDUPGRADEBUFFLVREQ_BUFFID_FIELD.cpp_type = 1
PM_NEVERLANDUPGRADEBUFFLVREQ_MSG.name = "PM_NeverLandUpgradeBuffLvReq"
PM_NEVERLANDUPGRADEBUFFLVREQ_MSG.full_name = ".PM_NeverLandUpgradeBuffLvReq"
PM_NEVERLANDUPGRADEBUFFLVREQ_MSG.nested_types = {}
PM_NEVERLANDUPGRADEBUFFLVREQ_MSG.enum_types = {}
PM_NEVERLANDUPGRADEBUFFLVREQ_MSG.fields = {
	tb.PM_NEVERLANDUPGRADEBUFFLVREQ_ACTIVITYID_FIELD,
	tb.PM_NEVERLANDUPGRADEBUFFLVREQ_BUFFID_FIELD
}
PM_NEVERLANDUPGRADEBUFFLVREQ_MSG.is_extendable = false
PM_NEVERLANDUPGRADEBUFFLVREQ_MSG.extensions = {}
PM_NEVERLANDUPGRADEBUFFLVRES_MSG.name = "PM_NeverLandUpgradeBuffLvRes"
PM_NEVERLANDUPGRADEBUFFLVRES_MSG.full_name = ".PM_NeverLandUpgradeBuffLvRes"
PM_NEVERLANDUPGRADEBUFFLVRES_MSG.nested_types = {}
PM_NEVERLANDUPGRADEBUFFLVRES_MSG.enum_types = {}
PM_NEVERLANDUPGRADEBUFFLVRES_MSG.fields = {}
PM_NEVERLANDUPGRADEBUFFLVRES_MSG.is_extendable = false
PM_NEVERLANDUPGRADEBUFFLVRES_MSG.extensions = {}
tb.PM_NEVERLANDGETRANKREQ_ACTIVITYID_FIELD.name = "activityId"
tb.PM_NEVERLANDGETRANKREQ_ACTIVITYID_FIELD.full_name = ".PM_NeverLandGetRankReq.activityId"
tb.PM_NEVERLANDGETRANKREQ_ACTIVITYID_FIELD.number = 1
tb.PM_NEVERLANDGETRANKREQ_ACTIVITYID_FIELD.index = 0
tb.PM_NEVERLANDGETRANKREQ_ACTIVITYID_FIELD.label = 2
tb.PM_NEVERLANDGETRANKREQ_ACTIVITYID_FIELD.has_default_value = false
tb.PM_NEVERLANDGETRANKREQ_ACTIVITYID_FIELD.default_value = 0
tb.PM_NEVERLANDGETRANKREQ_ACTIVITYID_FIELD.type = 5
tb.PM_NEVERLANDGETRANKREQ_ACTIVITYID_FIELD.cpp_type = 1
tb.PM_NEVERLANDGETRANKREQ_MODE_FIELD.name = "mode"
tb.PM_NEVERLANDGETRANKREQ_MODE_FIELD.full_name = ".PM_NeverLandGetRankReq.mode"
tb.PM_NEVERLANDGETRANKREQ_MODE_FIELD.number = 2
tb.PM_NEVERLANDGETRANKREQ_MODE_FIELD.index = 1
tb.PM_NEVERLANDGETRANKREQ_MODE_FIELD.label = 2
tb.PM_NEVERLANDGETRANKREQ_MODE_FIELD.has_default_value = false
tb.PM_NEVERLANDGETRANKREQ_MODE_FIELD.default_value = ""
tb.PM_NEVERLANDGETRANKREQ_MODE_FIELD.type = 9
tb.PM_NEVERLANDGETRANKREQ_MODE_FIELD.cpp_type = 9
PM_NEVERLANDGETRANKREQ_MSG.name = "PM_NeverLandGetRankReq"
PM_NEVERLANDGETRANKREQ_MSG.full_name = ".PM_NeverLandGetRankReq"
PM_NEVERLANDGETRANKREQ_MSG.nested_types = {}
PM_NEVERLANDGETRANKREQ_MSG.enum_types = {}
PM_NEVERLANDGETRANKREQ_MSG.fields = {
	tb.PM_NEVERLANDGETRANKREQ_ACTIVITYID_FIELD,
	tb.PM_NEVERLANDGETRANKREQ_MODE_FIELD
}
PM_NEVERLANDGETRANKREQ_MSG.is_extendable = false
PM_NEVERLANDGETRANKREQ_MSG.extensions = {}
tb.PM_NEVERLANDGETRANKRES_RANKINFOS_FIELD.name = "rankInfos"
tb.PM_NEVERLANDGETRANKRES_RANKINFOS_FIELD.full_name = ".PM_NeverLandGetRankRes.rankInfos"
tb.PM_NEVERLANDGETRANKRES_RANKINFOS_FIELD.number = 1
tb.PM_NEVERLANDGETRANKRES_RANKINFOS_FIELD.index = 0
tb.PM_NEVERLANDGETRANKRES_RANKINFOS_FIELD.label = 3
tb.PM_NEVERLANDGETRANKRES_RANKINFOS_FIELD.has_default_value = false
tb.PM_NEVERLANDGETRANKRES_RANKINFOS_FIELD.default_value = {}
tb.PM_NEVERLANDGETRANKRES_RANKINFOS_FIELD.message_type = COMMONRANKEXTENSION_PB.PM_COMMONRANKINFO_MSG
tb.PM_NEVERLANDGETRANKRES_RANKINFOS_FIELD.type = 11
tb.PM_NEVERLANDGETRANKRES_RANKINFOS_FIELD.cpp_type = 10
tb.PM_NEVERLANDGETRANKRES_MYRANK_FIELD.name = "myRank"
tb.PM_NEVERLANDGETRANKRES_MYRANK_FIELD.full_name = ".PM_NeverLandGetRankRes.myRank"
tb.PM_NEVERLANDGETRANKRES_MYRANK_FIELD.number = 2
tb.PM_NEVERLANDGETRANKRES_MYRANK_FIELD.index = 1
tb.PM_NEVERLANDGETRANKRES_MYRANK_FIELD.label = 2
tb.PM_NEVERLANDGETRANKRES_MYRANK_FIELD.has_default_value = false
tb.PM_NEVERLANDGETRANKRES_MYRANK_FIELD.default_value = 0
tb.PM_NEVERLANDGETRANKRES_MYRANK_FIELD.type = 5
tb.PM_NEVERLANDGETRANKRES_MYRANK_FIELD.cpp_type = 1
PM_NEVERLANDGETRANKRES_MSG.name = "PM_NeverLandGetRankRes"
PM_NEVERLANDGETRANKRES_MSG.full_name = ".PM_NeverLandGetRankRes"
PM_NEVERLANDGETRANKRES_MSG.nested_types = {}
PM_NEVERLANDGETRANKRES_MSG.enum_types = {}
PM_NEVERLANDGETRANKRES_MSG.fields = {
	tb.PM_NEVERLANDGETRANKRES_RANKINFOS_FIELD,
	tb.PM_NEVERLANDGETRANKRES_MYRANK_FIELD
}
PM_NEVERLANDGETRANKRES_MSG.is_extendable = false
PM_NEVERLANDGETRANKRES_MSG.extensions = {}
PM_NeverLandBuffInfo = protobuf.Message(PM_NEVERLANDBUFFINFO_MSG)
PM_NeverLandChallengeReq = protobuf.Message(PM_NEVERLANDCHALLENGEREQ_MSG)
PM_NeverLandChallengeRes = protobuf.Message(PM_NEVERLANDCHALLENGERES_MSG)
PM_NeverLandGetRankReq = protobuf.Message(PM_NEVERLANDGETRANKREQ_MSG)
PM_NeverLandGetRankRes = protobuf.Message(PM_NEVERLANDGETRANKRES_MSG)
PM_NeverLandInfoReq = protobuf.Message(PM_NEVERLANDINFOREQ_MSG)
PM_NeverLandInfoRes = protobuf.Message(PM_NEVERLANDINFORES_MSG)
PM_NeverLandNotifyChallengeResultRes = protobuf.Message(PM_NEVERLANDNOTIFYCHALLENGERESULTRES_MSG)
PM_NeverLandUpgradeBuffLvReq = protobuf.Message(PM_NEVERLANDUPGRADEBUFFLVREQ_MSG)
PM_NeverLandUpgradeBuffLvRes = protobuf.Message(PM_NEVERLANDUPGRADEBUFFLVRES_MSG)

return _G["logic.proto.NeverLandExtension_pb"]
