-- chunkname: @C:/GitLab-Runner/builds/sTUwNpCg/0/aqmobile/aqmobile-client/UnityProj/Assets/Scripts/Lua/logic/proto/ShenJiChallengeExtension_pb.lua

local protobuf = require("protobuf.protobuf")
local FORMATIONEXTENSION_PB = require("logic.proto.FormationExtension_pb")

module("logic.proto.ShenJiChallengeExtension_pb", package.seeall)

local tb = {}

PM_SHENJICLGBOSSSTAGE_MSG = protobuf.Descriptor()
tb.PM_SHENJICLGBOSSSTAGE_BOSSID_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICLGBOSSSTAGE_LOCKPETIDS_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICLGBOSSSTAGE_BOSSCURHP_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICLGBOSSSTAGE_CHALLENGETIMES_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICLGBOSSSTAGE_TODAYPASSBOSS_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICLGBOSSSTAGE_GAINPRIZEIDS_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICLGBOSSSTAGE_BOSSTOTALHP_FIELD = protobuf.FieldDescriptor()
PM_SHENJICLGSELECTSTAGE_MSG = protobuf.Descriptor()
tb.PM_SHENJICLGSELECTSTAGE_OPTIONALSTAGEIDS_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICLGSELECTSTAGE_BUFFVALUE_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICLGSELECTSTAGE_TODAYCHALLENGETIMES_FIELD = protobuf.FieldDescriptor()
PM_SHENJICHALLENGEGETINFOREQ_MSG = protobuf.Descriptor()
tb.PM_SHENJICHALLENGEGETINFOREQ_ACTID_FIELD = protobuf.FieldDescriptor()
PM_SHENJICHALLENGEGETINFORES_MSG = protobuf.Descriptor()
tb.PM_SHENJICHALLENGEGETINFORES_ACTID_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICHALLENGEGETINFORES_BOSSINFO_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICHALLENGEGETINFORES_SELECTSTAGEINFO_FIELD = protobuf.FieldDescriptor()
PM_SHENJICHALLENGESELECTCLGREQ_MSG = protobuf.Descriptor()
tb.PM_SHENJICHALLENGESELECTCLGREQ_ACTID_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICHALLENGESELECTCLGREQ_STAGEID_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICHALLENGESELECTCLGREQ_FORM_FIELD = protobuf.FieldDescriptor()
PM_SHENJICHALLENGESELECTCLGRES_MSG = protobuf.Descriptor()
PM_SHENJICHALLENGEBOSSCLGREQ_MSG = protobuf.Descriptor()
tb.PM_SHENJICHALLENGEBOSSCLGREQ_ACTID_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICHALLENGEBOSSCLGREQ_BOSSID_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICHALLENGEBOSSCLGREQ_FORM_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICHALLENGEBOSSCLGREQ_ISEMULATE_FIELD = protobuf.FieldDescriptor()
PM_SHENJICHALLENGEBOSSCLGRES_MSG = protobuf.Descriptor()
PM_SHENJICHALLENGERESETBOSSSTAGEREQ_MSG = protobuf.Descriptor()
tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_ACTID_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_BOSSID_FIELD = protobuf.FieldDescriptor()
PM_SHENJICHALLENGERESETBOSSSTAGERES_MSG = protobuf.Descriptor()
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_ACTID_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSID_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSINFO_FIELD = protobuf.FieldDescriptor()
PM_SHENJICHALLENGEGAINPRIZEREQ_MSG = protobuf.Descriptor()
tb.PM_SHENJICHALLENGEGAINPRIZEREQ_ACTID_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICHALLENGEGAINPRIZEREQ_BOSSID_FIELD = protobuf.FieldDescriptor()
PM_SHENJICHALLENGEGAINPRIZERES_MSG = protobuf.Descriptor()
tb.PM_SHENJICHALLENGEGAINPRIZERES_ACTID_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICHALLENGEGAINPRIZERES_BOSSID_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICHALLENGEGAINPRIZERES_CHANGESETID_FIELD = protobuf.FieldDescriptor()
PM_KINGJICHALLENGENOTIFYSELECTCLGRES_MSG = protobuf.Descriptor()
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ACTID_FIELD = protobuf.FieldDescriptor()
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEID_FIELD = protobuf.FieldDescriptor()
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ISWIN_FIELD = protobuf.FieldDescriptor()
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEINFO_FIELD = protobuf.FieldDescriptor()
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_CHANGEBUFFVALUE_FIELD = protobuf.FieldDescriptor()
PM_KINGJICHALLENGENOTIFYBOSSCLGRES_MSG = protobuf.Descriptor()
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ACTID_FIELD = protobuf.FieldDescriptor()
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSID_FIELD = protobuf.FieldDescriptor()
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISEMULATE_FIELD = protobuf.FieldDescriptor()
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISWIN_FIELD = protobuf.FieldDescriptor()
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_OUTPUTDAMAGE_FIELD = protobuf.FieldDescriptor()
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_PETIDS_FIELD = protobuf.FieldDescriptor()
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSINFO_FIELD = protobuf.FieldDescriptor()
tb.PM_SHENJICLGBOSSSTAGE_BOSSID_FIELD.name = "bossId"
tb.PM_SHENJICLGBOSSSTAGE_BOSSID_FIELD.full_name = ".PM_ShenJiClgBossStage.bossId"
tb.PM_SHENJICLGBOSSSTAGE_BOSSID_FIELD.number = 1
tb.PM_SHENJICLGBOSSSTAGE_BOSSID_FIELD.index = 0
tb.PM_SHENJICLGBOSSSTAGE_BOSSID_FIELD.label = 2
tb.PM_SHENJICLGBOSSSTAGE_BOSSID_FIELD.has_default_value = false
tb.PM_SHENJICLGBOSSSTAGE_BOSSID_FIELD.default_value = 0
tb.PM_SHENJICLGBOSSSTAGE_BOSSID_FIELD.type = 5
tb.PM_SHENJICLGBOSSSTAGE_BOSSID_FIELD.cpp_type = 1
tb.PM_SHENJICLGBOSSSTAGE_LOCKPETIDS_FIELD.name = "lockPetIds"
tb.PM_SHENJICLGBOSSSTAGE_LOCKPETIDS_FIELD.full_name = ".PM_ShenJiClgBossStage.lockPetIds"
tb.PM_SHENJICLGBOSSSTAGE_LOCKPETIDS_FIELD.number = 2
tb.PM_SHENJICLGBOSSSTAGE_LOCKPETIDS_FIELD.index = 1
tb.PM_SHENJICLGBOSSSTAGE_LOCKPETIDS_FIELD.label = 3
tb.PM_SHENJICLGBOSSSTAGE_LOCKPETIDS_FIELD.has_default_value = false
tb.PM_SHENJICLGBOSSSTAGE_LOCKPETIDS_FIELD.default_value = {}
tb.PM_SHENJICLGBOSSSTAGE_LOCKPETIDS_FIELD.type = 5
tb.PM_SHENJICLGBOSSSTAGE_LOCKPETIDS_FIELD.cpp_type = 1
tb.PM_SHENJICLGBOSSSTAGE_BOSSCURHP_FIELD.name = "bossCurHp"
tb.PM_SHENJICLGBOSSSTAGE_BOSSCURHP_FIELD.full_name = ".PM_ShenJiClgBossStage.bossCurHp"
tb.PM_SHENJICLGBOSSSTAGE_BOSSCURHP_FIELD.number = 3
tb.PM_SHENJICLGBOSSSTAGE_BOSSCURHP_FIELD.index = 2
tb.PM_SHENJICLGBOSSSTAGE_BOSSCURHP_FIELD.label = 2
tb.PM_SHENJICLGBOSSSTAGE_BOSSCURHP_FIELD.has_default_value = false
tb.PM_SHENJICLGBOSSSTAGE_BOSSCURHP_FIELD.default_value = 0
tb.PM_SHENJICLGBOSSSTAGE_BOSSCURHP_FIELD.type = 3
tb.PM_SHENJICLGBOSSSTAGE_BOSSCURHP_FIELD.cpp_type = 2
tb.PM_SHENJICLGBOSSSTAGE_CHALLENGETIMES_FIELD.name = "challengeTimes"
tb.PM_SHENJICLGBOSSSTAGE_CHALLENGETIMES_FIELD.full_name = ".PM_ShenJiClgBossStage.challengeTimes"
tb.PM_SHENJICLGBOSSSTAGE_CHALLENGETIMES_FIELD.number = 4
tb.PM_SHENJICLGBOSSSTAGE_CHALLENGETIMES_FIELD.index = 3
tb.PM_SHENJICLGBOSSSTAGE_CHALLENGETIMES_FIELD.label = 2
tb.PM_SHENJICLGBOSSSTAGE_CHALLENGETIMES_FIELD.has_default_value = false
tb.PM_SHENJICLGBOSSSTAGE_CHALLENGETIMES_FIELD.default_value = 0
tb.PM_SHENJICLGBOSSSTAGE_CHALLENGETIMES_FIELD.type = 5
tb.PM_SHENJICLGBOSSSTAGE_CHALLENGETIMES_FIELD.cpp_type = 1
tb.PM_SHENJICLGBOSSSTAGE_TODAYPASSBOSS_FIELD.name = "todayPassBoss"
tb.PM_SHENJICLGBOSSSTAGE_TODAYPASSBOSS_FIELD.full_name = ".PM_ShenJiClgBossStage.todayPassBoss"
tb.PM_SHENJICLGBOSSSTAGE_TODAYPASSBOSS_FIELD.number = 5
tb.PM_SHENJICLGBOSSSTAGE_TODAYPASSBOSS_FIELD.index = 4
tb.PM_SHENJICLGBOSSSTAGE_TODAYPASSBOSS_FIELD.label = 2
tb.PM_SHENJICLGBOSSSTAGE_TODAYPASSBOSS_FIELD.has_default_value = false
tb.PM_SHENJICLGBOSSSTAGE_TODAYPASSBOSS_FIELD.default_value = false
tb.PM_SHENJICLGBOSSSTAGE_TODAYPASSBOSS_FIELD.type = 8
tb.PM_SHENJICLGBOSSSTAGE_TODAYPASSBOSS_FIELD.cpp_type = 7
tb.PM_SHENJICLGBOSSSTAGE_GAINPRIZEIDS_FIELD.name = "gainPrizeIds"
tb.PM_SHENJICLGBOSSSTAGE_GAINPRIZEIDS_FIELD.full_name = ".PM_ShenJiClgBossStage.gainPrizeIds"
tb.PM_SHENJICLGBOSSSTAGE_GAINPRIZEIDS_FIELD.number = 6
tb.PM_SHENJICLGBOSSSTAGE_GAINPRIZEIDS_FIELD.index = 5
tb.PM_SHENJICLGBOSSSTAGE_GAINPRIZEIDS_FIELD.label = 3
tb.PM_SHENJICLGBOSSSTAGE_GAINPRIZEIDS_FIELD.has_default_value = false
tb.PM_SHENJICLGBOSSSTAGE_GAINPRIZEIDS_FIELD.default_value = {}
tb.PM_SHENJICLGBOSSSTAGE_GAINPRIZEIDS_FIELD.type = 5
tb.PM_SHENJICLGBOSSSTAGE_GAINPRIZEIDS_FIELD.cpp_type = 1
tb.PM_SHENJICLGBOSSSTAGE_BOSSTOTALHP_FIELD.name = "bossTotalHp"
tb.PM_SHENJICLGBOSSSTAGE_BOSSTOTALHP_FIELD.full_name = ".PM_ShenJiClgBossStage.bossTotalHp"
tb.PM_SHENJICLGBOSSSTAGE_BOSSTOTALHP_FIELD.number = 7
tb.PM_SHENJICLGBOSSSTAGE_BOSSTOTALHP_FIELD.index = 6
tb.PM_SHENJICLGBOSSSTAGE_BOSSTOTALHP_FIELD.label = 2
tb.PM_SHENJICLGBOSSSTAGE_BOSSTOTALHP_FIELD.has_default_value = false
tb.PM_SHENJICLGBOSSSTAGE_BOSSTOTALHP_FIELD.default_value = 0
tb.PM_SHENJICLGBOSSSTAGE_BOSSTOTALHP_FIELD.type = 3
tb.PM_SHENJICLGBOSSSTAGE_BOSSTOTALHP_FIELD.cpp_type = 2
PM_SHENJICLGBOSSSTAGE_MSG.name = "PM_ShenJiClgBossStage"
PM_SHENJICLGBOSSSTAGE_MSG.full_name = ".PM_ShenJiClgBossStage"
PM_SHENJICLGBOSSSTAGE_MSG.nested_types = {}
PM_SHENJICLGBOSSSTAGE_MSG.enum_types = {}
PM_SHENJICLGBOSSSTAGE_MSG.fields = {
	tb.PM_SHENJICLGBOSSSTAGE_BOSSID_FIELD,
	tb.PM_SHENJICLGBOSSSTAGE_LOCKPETIDS_FIELD,
	tb.PM_SHENJICLGBOSSSTAGE_BOSSCURHP_FIELD,
	tb.PM_SHENJICLGBOSSSTAGE_CHALLENGETIMES_FIELD,
	tb.PM_SHENJICLGBOSSSTAGE_TODAYPASSBOSS_FIELD,
	tb.PM_SHENJICLGBOSSSTAGE_GAINPRIZEIDS_FIELD,
	tb.PM_SHENJICLGBOSSSTAGE_BOSSTOTALHP_FIELD
}
PM_SHENJICLGBOSSSTAGE_MSG.is_extendable = false
PM_SHENJICLGBOSSSTAGE_MSG.extensions = {}
tb.PM_SHENJICLGSELECTSTAGE_OPTIONALSTAGEIDS_FIELD.name = "optionalStageIds"
tb.PM_SHENJICLGSELECTSTAGE_OPTIONALSTAGEIDS_FIELD.full_name = ".PM_ShenJiClgSelectStage.optionalStageIds"
tb.PM_SHENJICLGSELECTSTAGE_OPTIONALSTAGEIDS_FIELD.number = 1
tb.PM_SHENJICLGSELECTSTAGE_OPTIONALSTAGEIDS_FIELD.index = 0
tb.PM_SHENJICLGSELECTSTAGE_OPTIONALSTAGEIDS_FIELD.label = 3
tb.PM_SHENJICLGSELECTSTAGE_OPTIONALSTAGEIDS_FIELD.has_default_value = false
tb.PM_SHENJICLGSELECTSTAGE_OPTIONALSTAGEIDS_FIELD.default_value = {}
tb.PM_SHENJICLGSELECTSTAGE_OPTIONALSTAGEIDS_FIELD.type = 5
tb.PM_SHENJICLGSELECTSTAGE_OPTIONALSTAGEIDS_FIELD.cpp_type = 1
tb.PM_SHENJICLGSELECTSTAGE_BUFFVALUE_FIELD.name = "buffValue"
tb.PM_SHENJICLGSELECTSTAGE_BUFFVALUE_FIELD.full_name = ".PM_ShenJiClgSelectStage.buffValue"
tb.PM_SHENJICLGSELECTSTAGE_BUFFVALUE_FIELD.number = 2
tb.PM_SHENJICLGSELECTSTAGE_BUFFVALUE_FIELD.index = 1
tb.PM_SHENJICLGSELECTSTAGE_BUFFVALUE_FIELD.label = 2
tb.PM_SHENJICLGSELECTSTAGE_BUFFVALUE_FIELD.has_default_value = false
tb.PM_SHENJICLGSELECTSTAGE_BUFFVALUE_FIELD.default_value = 0
tb.PM_SHENJICLGSELECTSTAGE_BUFFVALUE_FIELD.type = 5
tb.PM_SHENJICLGSELECTSTAGE_BUFFVALUE_FIELD.cpp_type = 1
tb.PM_SHENJICLGSELECTSTAGE_TODAYCHALLENGETIMES_FIELD.name = "todayChallengeTimes"
tb.PM_SHENJICLGSELECTSTAGE_TODAYCHALLENGETIMES_FIELD.full_name = ".PM_ShenJiClgSelectStage.todayChallengeTimes"
tb.PM_SHENJICLGSELECTSTAGE_TODAYCHALLENGETIMES_FIELD.number = 4
tb.PM_SHENJICLGSELECTSTAGE_TODAYCHALLENGETIMES_FIELD.index = 2
tb.PM_SHENJICLGSELECTSTAGE_TODAYCHALLENGETIMES_FIELD.label = 2
tb.PM_SHENJICLGSELECTSTAGE_TODAYCHALLENGETIMES_FIELD.has_default_value = false
tb.PM_SHENJICLGSELECTSTAGE_TODAYCHALLENGETIMES_FIELD.default_value = 0
tb.PM_SHENJICLGSELECTSTAGE_TODAYCHALLENGETIMES_FIELD.type = 5
tb.PM_SHENJICLGSELECTSTAGE_TODAYCHALLENGETIMES_FIELD.cpp_type = 1
PM_SHENJICLGSELECTSTAGE_MSG.name = "PM_ShenJiClgSelectStage"
PM_SHENJICLGSELECTSTAGE_MSG.full_name = ".PM_ShenJiClgSelectStage"
PM_SHENJICLGSELECTSTAGE_MSG.nested_types = {}
PM_SHENJICLGSELECTSTAGE_MSG.enum_types = {}
PM_SHENJICLGSELECTSTAGE_MSG.fields = {
	tb.PM_SHENJICLGSELECTSTAGE_OPTIONALSTAGEIDS_FIELD,
	tb.PM_SHENJICLGSELECTSTAGE_BUFFVALUE_FIELD,
	tb.PM_SHENJICLGSELECTSTAGE_TODAYCHALLENGETIMES_FIELD
}
PM_SHENJICLGSELECTSTAGE_MSG.is_extendable = false
PM_SHENJICLGSELECTSTAGE_MSG.extensions = {}
tb.PM_SHENJICHALLENGEGETINFOREQ_ACTID_FIELD.name = "actId"
tb.PM_SHENJICHALLENGEGETINFOREQ_ACTID_FIELD.full_name = ".PM_ShenJiChallengeGetInfoReq.actId"
tb.PM_SHENJICHALLENGEGETINFOREQ_ACTID_FIELD.number = 1
tb.PM_SHENJICHALLENGEGETINFOREQ_ACTID_FIELD.index = 0
tb.PM_SHENJICHALLENGEGETINFOREQ_ACTID_FIELD.label = 2
tb.PM_SHENJICHALLENGEGETINFOREQ_ACTID_FIELD.has_default_value = false
tb.PM_SHENJICHALLENGEGETINFOREQ_ACTID_FIELD.default_value = 0
tb.PM_SHENJICHALLENGEGETINFOREQ_ACTID_FIELD.type = 5
tb.PM_SHENJICHALLENGEGETINFOREQ_ACTID_FIELD.cpp_type = 1
PM_SHENJICHALLENGEGETINFOREQ_MSG.name = "PM_ShenJiChallengeGetInfoReq"
PM_SHENJICHALLENGEGETINFOREQ_MSG.full_name = ".PM_ShenJiChallengeGetInfoReq"
PM_SHENJICHALLENGEGETINFOREQ_MSG.nested_types = {}
PM_SHENJICHALLENGEGETINFOREQ_MSG.enum_types = {}
PM_SHENJICHALLENGEGETINFOREQ_MSG.fields = {
	tb.PM_SHENJICHALLENGEGETINFOREQ_ACTID_FIELD
}
PM_SHENJICHALLENGEGETINFOREQ_MSG.is_extendable = false
PM_SHENJICHALLENGEGETINFOREQ_MSG.extensions = {}
tb.PM_SHENJICHALLENGEGETINFORES_ACTID_FIELD.name = "actId"
tb.PM_SHENJICHALLENGEGETINFORES_ACTID_FIELD.full_name = ".PM_ShenJiChallengeGetInfoRes.actId"
tb.PM_SHENJICHALLENGEGETINFORES_ACTID_FIELD.number = 1
tb.PM_SHENJICHALLENGEGETINFORES_ACTID_FIELD.index = 0
tb.PM_SHENJICHALLENGEGETINFORES_ACTID_FIELD.label = 2
tb.PM_SHENJICHALLENGEGETINFORES_ACTID_FIELD.has_default_value = false
tb.PM_SHENJICHALLENGEGETINFORES_ACTID_FIELD.default_value = 0
tb.PM_SHENJICHALLENGEGETINFORES_ACTID_FIELD.type = 5
tb.PM_SHENJICHALLENGEGETINFORES_ACTID_FIELD.cpp_type = 1
tb.PM_SHENJICHALLENGEGETINFORES_BOSSINFO_FIELD.name = "bossInfo"
tb.PM_SHENJICHALLENGEGETINFORES_BOSSINFO_FIELD.full_name = ".PM_ShenJiChallengeGetInfoRes.bossInfo"
tb.PM_SHENJICHALLENGEGETINFORES_BOSSINFO_FIELD.number = 2
tb.PM_SHENJICHALLENGEGETINFORES_BOSSINFO_FIELD.index = 1
tb.PM_SHENJICHALLENGEGETINFORES_BOSSINFO_FIELD.label = 2
tb.PM_SHENJICHALLENGEGETINFORES_BOSSINFO_FIELD.has_default_value = false
tb.PM_SHENJICHALLENGEGETINFORES_BOSSINFO_FIELD.default_value = nil
tb.PM_SHENJICHALLENGEGETINFORES_BOSSINFO_FIELD.message_type = PM_SHENJICLGBOSSSTAGE_MSG
tb.PM_SHENJICHALLENGEGETINFORES_BOSSINFO_FIELD.type = 11
tb.PM_SHENJICHALLENGEGETINFORES_BOSSINFO_FIELD.cpp_type = 10
tb.PM_SHENJICHALLENGEGETINFORES_SELECTSTAGEINFO_FIELD.name = "selectStageInfo"
tb.PM_SHENJICHALLENGEGETINFORES_SELECTSTAGEINFO_FIELD.full_name = ".PM_ShenJiChallengeGetInfoRes.selectStageInfo"
tb.PM_SHENJICHALLENGEGETINFORES_SELECTSTAGEINFO_FIELD.number = 3
tb.PM_SHENJICHALLENGEGETINFORES_SELECTSTAGEINFO_FIELD.index = 2
tb.PM_SHENJICHALLENGEGETINFORES_SELECTSTAGEINFO_FIELD.label = 2
tb.PM_SHENJICHALLENGEGETINFORES_SELECTSTAGEINFO_FIELD.has_default_value = false
tb.PM_SHENJICHALLENGEGETINFORES_SELECTSTAGEINFO_FIELD.default_value = nil
tb.PM_SHENJICHALLENGEGETINFORES_SELECTSTAGEINFO_FIELD.message_type = PM_SHENJICLGSELECTSTAGE_MSG
tb.PM_SHENJICHALLENGEGETINFORES_SELECTSTAGEINFO_FIELD.type = 11
tb.PM_SHENJICHALLENGEGETINFORES_SELECTSTAGEINFO_FIELD.cpp_type = 10
PM_SHENJICHALLENGEGETINFORES_MSG.name = "PM_ShenJiChallengeGetInfoRes"
PM_SHENJICHALLENGEGETINFORES_MSG.full_name = ".PM_ShenJiChallengeGetInfoRes"
PM_SHENJICHALLENGEGETINFORES_MSG.nested_types = {}
PM_SHENJICHALLENGEGETINFORES_MSG.enum_types = {}
PM_SHENJICHALLENGEGETINFORES_MSG.fields = {
	tb.PM_SHENJICHALLENGEGETINFORES_ACTID_FIELD,
	tb.PM_SHENJICHALLENGEGETINFORES_BOSSINFO_FIELD,
	tb.PM_SHENJICHALLENGEGETINFORES_SELECTSTAGEINFO_FIELD
}
PM_SHENJICHALLENGEGETINFORES_MSG.is_extendable = false
PM_SHENJICHALLENGEGETINFORES_MSG.extensions = {}
tb.PM_SHENJICHALLENGESELECTCLGREQ_ACTID_FIELD.name = "actId"
tb.PM_SHENJICHALLENGESELECTCLGREQ_ACTID_FIELD.full_name = ".PM_ShenJiChallengeSelectClgReq.actId"
tb.PM_SHENJICHALLENGESELECTCLGREQ_ACTID_FIELD.number = 1
tb.PM_SHENJICHALLENGESELECTCLGREQ_ACTID_FIELD.index = 0
tb.PM_SHENJICHALLENGESELECTCLGREQ_ACTID_FIELD.label = 2
tb.PM_SHENJICHALLENGESELECTCLGREQ_ACTID_FIELD.has_default_value = false
tb.PM_SHENJICHALLENGESELECTCLGREQ_ACTID_FIELD.default_value = 0
tb.PM_SHENJICHALLENGESELECTCLGREQ_ACTID_FIELD.type = 5
tb.PM_SHENJICHALLENGESELECTCLGREQ_ACTID_FIELD.cpp_type = 1
tb.PM_SHENJICHALLENGESELECTCLGREQ_STAGEID_FIELD.name = "stageId"
tb.PM_SHENJICHALLENGESELECTCLGREQ_STAGEID_FIELD.full_name = ".PM_ShenJiChallengeSelectClgReq.stageId"
tb.PM_SHENJICHALLENGESELECTCLGREQ_STAGEID_FIELD.number = 2
tb.PM_SHENJICHALLENGESELECTCLGREQ_STAGEID_FIELD.index = 1
tb.PM_SHENJICHALLENGESELECTCLGREQ_STAGEID_FIELD.label = 2
tb.PM_SHENJICHALLENGESELECTCLGREQ_STAGEID_FIELD.has_default_value = false
tb.PM_SHENJICHALLENGESELECTCLGREQ_STAGEID_FIELD.default_value = 0
tb.PM_SHENJICHALLENGESELECTCLGREQ_STAGEID_FIELD.type = 5
tb.PM_SHENJICHALLENGESELECTCLGREQ_STAGEID_FIELD.cpp_type = 1
tb.PM_SHENJICHALLENGESELECTCLGREQ_FORM_FIELD.name = "form"
tb.PM_SHENJICHALLENGESELECTCLGREQ_FORM_FIELD.full_name = ".PM_ShenJiChallengeSelectClgReq.form"
tb.PM_SHENJICHALLENGESELECTCLGREQ_FORM_FIELD.number = 3
tb.PM_SHENJICHALLENGESELECTCLGREQ_FORM_FIELD.index = 2
tb.PM_SHENJICHALLENGESELECTCLGREQ_FORM_FIELD.label = 2
tb.PM_SHENJICHALLENGESELECTCLGREQ_FORM_FIELD.has_default_value = false
tb.PM_SHENJICHALLENGESELECTCLGREQ_FORM_FIELD.default_value = nil
tb.PM_SHENJICHALLENGESELECTCLGREQ_FORM_FIELD.message_type = FORMATIONEXTENSION_PB.PM_SIMPLEFORM_MSG
tb.PM_SHENJICHALLENGESELECTCLGREQ_FORM_FIELD.type = 11
tb.PM_SHENJICHALLENGESELECTCLGREQ_FORM_FIELD.cpp_type = 10
PM_SHENJICHALLENGESELECTCLGREQ_MSG.name = "PM_ShenJiChallengeSelectClgReq"
PM_SHENJICHALLENGESELECTCLGREQ_MSG.full_name = ".PM_ShenJiChallengeSelectClgReq"
PM_SHENJICHALLENGESELECTCLGREQ_MSG.nested_types = {}
PM_SHENJICHALLENGESELECTCLGREQ_MSG.enum_types = {}
PM_SHENJICHALLENGESELECTCLGREQ_MSG.fields = {
	tb.PM_SHENJICHALLENGESELECTCLGREQ_ACTID_FIELD,
	tb.PM_SHENJICHALLENGESELECTCLGREQ_STAGEID_FIELD,
	tb.PM_SHENJICHALLENGESELECTCLGREQ_FORM_FIELD
}
PM_SHENJICHALLENGESELECTCLGREQ_MSG.is_extendable = false
PM_SHENJICHALLENGESELECTCLGREQ_MSG.extensions = {}
PM_SHENJICHALLENGESELECTCLGRES_MSG.name = "PM_ShenJiChallengeSelectClgRes"
PM_SHENJICHALLENGESELECTCLGRES_MSG.full_name = ".PM_ShenJiChallengeSelectClgRes"
PM_SHENJICHALLENGESELECTCLGRES_MSG.nested_types = {}
PM_SHENJICHALLENGESELECTCLGRES_MSG.enum_types = {}
PM_SHENJICHALLENGESELECTCLGRES_MSG.fields = {}
PM_SHENJICHALLENGESELECTCLGRES_MSG.is_extendable = false
PM_SHENJICHALLENGESELECTCLGRES_MSG.extensions = {}
tb.PM_SHENJICHALLENGEBOSSCLGREQ_ACTID_FIELD.name = "actId"
tb.PM_SHENJICHALLENGEBOSSCLGREQ_ACTID_FIELD.full_name = ".PM_ShenJiChallengeBossClgReq.actId"
tb.PM_SHENJICHALLENGEBOSSCLGREQ_ACTID_FIELD.number = 1
tb.PM_SHENJICHALLENGEBOSSCLGREQ_ACTID_FIELD.index = 0
tb.PM_SHENJICHALLENGEBOSSCLGREQ_ACTID_FIELD.label = 2
tb.PM_SHENJICHALLENGEBOSSCLGREQ_ACTID_FIELD.has_default_value = false
tb.PM_SHENJICHALLENGEBOSSCLGREQ_ACTID_FIELD.default_value = 0
tb.PM_SHENJICHALLENGEBOSSCLGREQ_ACTID_FIELD.type = 5
tb.PM_SHENJICHALLENGEBOSSCLGREQ_ACTID_FIELD.cpp_type = 1
tb.PM_SHENJICHALLENGEBOSSCLGREQ_BOSSID_FIELD.name = "bossId"
tb.PM_SHENJICHALLENGEBOSSCLGREQ_BOSSID_FIELD.full_name = ".PM_ShenJiChallengeBossClgReq.bossId"
tb.PM_SHENJICHALLENGEBOSSCLGREQ_BOSSID_FIELD.number = 2
tb.PM_SHENJICHALLENGEBOSSCLGREQ_BOSSID_FIELD.index = 1
tb.PM_SHENJICHALLENGEBOSSCLGREQ_BOSSID_FIELD.label = 2
tb.PM_SHENJICHALLENGEBOSSCLGREQ_BOSSID_FIELD.has_default_value = false
tb.PM_SHENJICHALLENGEBOSSCLGREQ_BOSSID_FIELD.default_value = 0
tb.PM_SHENJICHALLENGEBOSSCLGREQ_BOSSID_FIELD.type = 5
tb.PM_SHENJICHALLENGEBOSSCLGREQ_BOSSID_FIELD.cpp_type = 1
tb.PM_SHENJICHALLENGEBOSSCLGREQ_FORM_FIELD.name = "form"
tb.PM_SHENJICHALLENGEBOSSCLGREQ_FORM_FIELD.full_name = ".PM_ShenJiChallengeBossClgReq.form"
tb.PM_SHENJICHALLENGEBOSSCLGREQ_FORM_FIELD.number = 3
tb.PM_SHENJICHALLENGEBOSSCLGREQ_FORM_FIELD.index = 2
tb.PM_SHENJICHALLENGEBOSSCLGREQ_FORM_FIELD.label = 2
tb.PM_SHENJICHALLENGEBOSSCLGREQ_FORM_FIELD.has_default_value = false
tb.PM_SHENJICHALLENGEBOSSCLGREQ_FORM_FIELD.default_value = nil
tb.PM_SHENJICHALLENGEBOSSCLGREQ_FORM_FIELD.message_type = FORMATIONEXTENSION_PB.PM_SIMPLEFORM_MSG
tb.PM_SHENJICHALLENGEBOSSCLGREQ_FORM_FIELD.type = 11
tb.PM_SHENJICHALLENGEBOSSCLGREQ_FORM_FIELD.cpp_type = 10
tb.PM_SHENJICHALLENGEBOSSCLGREQ_ISEMULATE_FIELD.name = "isEmulate"
tb.PM_SHENJICHALLENGEBOSSCLGREQ_ISEMULATE_FIELD.full_name = ".PM_ShenJiChallengeBossClgReq.isEmulate"
tb.PM_SHENJICHALLENGEBOSSCLGREQ_ISEMULATE_FIELD.number = 4
tb.PM_SHENJICHALLENGEBOSSCLGREQ_ISEMULATE_FIELD.index = 3
tb.PM_SHENJICHALLENGEBOSSCLGREQ_ISEMULATE_FIELD.label = 2
tb.PM_SHENJICHALLENGEBOSSCLGREQ_ISEMULATE_FIELD.has_default_value = false
tb.PM_SHENJICHALLENGEBOSSCLGREQ_ISEMULATE_FIELD.default_value = false
tb.PM_SHENJICHALLENGEBOSSCLGREQ_ISEMULATE_FIELD.type = 8
tb.PM_SHENJICHALLENGEBOSSCLGREQ_ISEMULATE_FIELD.cpp_type = 7
PM_SHENJICHALLENGEBOSSCLGREQ_MSG.name = "PM_ShenJiChallengeBossClgReq"
PM_SHENJICHALLENGEBOSSCLGREQ_MSG.full_name = ".PM_ShenJiChallengeBossClgReq"
PM_SHENJICHALLENGEBOSSCLGREQ_MSG.nested_types = {}
PM_SHENJICHALLENGEBOSSCLGREQ_MSG.enum_types = {}
PM_SHENJICHALLENGEBOSSCLGREQ_MSG.fields = {
	tb.PM_SHENJICHALLENGEBOSSCLGREQ_ACTID_FIELD,
	tb.PM_SHENJICHALLENGEBOSSCLGREQ_BOSSID_FIELD,
	tb.PM_SHENJICHALLENGEBOSSCLGREQ_FORM_FIELD,
	tb.PM_SHENJICHALLENGEBOSSCLGREQ_ISEMULATE_FIELD
}
PM_SHENJICHALLENGEBOSSCLGREQ_MSG.is_extendable = false
PM_SHENJICHALLENGEBOSSCLGREQ_MSG.extensions = {}
PM_SHENJICHALLENGEBOSSCLGRES_MSG.name = "PM_ShenJiChallengeBossClgRes"
PM_SHENJICHALLENGEBOSSCLGRES_MSG.full_name = ".PM_ShenJiChallengeBossClgRes"
PM_SHENJICHALLENGEBOSSCLGRES_MSG.nested_types = {}
PM_SHENJICHALLENGEBOSSCLGRES_MSG.enum_types = {}
PM_SHENJICHALLENGEBOSSCLGRES_MSG.fields = {}
PM_SHENJICHALLENGEBOSSCLGRES_MSG.is_extendable = false
PM_SHENJICHALLENGEBOSSCLGRES_MSG.extensions = {}
tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_ACTID_FIELD.name = "actId"
tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_ACTID_FIELD.full_name = ".PM_ShenJiChallengeResetBossStageReq.actId"
tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_ACTID_FIELD.number = 1
tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_ACTID_FIELD.index = 0
tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_ACTID_FIELD.label = 2
tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_ACTID_FIELD.has_default_value = false
tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_ACTID_FIELD.default_value = 0
tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_ACTID_FIELD.type = 5
tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_ACTID_FIELD.cpp_type = 1
tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_BOSSID_FIELD.name = "bossId"
tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_BOSSID_FIELD.full_name = ".PM_ShenJiChallengeResetBossStageReq.bossId"
tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_BOSSID_FIELD.number = 2
tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_BOSSID_FIELD.index = 1
tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_BOSSID_FIELD.label = 2
tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_BOSSID_FIELD.has_default_value = false
tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_BOSSID_FIELD.default_value = 0
tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_BOSSID_FIELD.type = 5
tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_BOSSID_FIELD.cpp_type = 1
PM_SHENJICHALLENGERESETBOSSSTAGEREQ_MSG.name = "PM_ShenJiChallengeResetBossStageReq"
PM_SHENJICHALLENGERESETBOSSSTAGEREQ_MSG.full_name = ".PM_ShenJiChallengeResetBossStageReq"
PM_SHENJICHALLENGERESETBOSSSTAGEREQ_MSG.nested_types = {}
PM_SHENJICHALLENGERESETBOSSSTAGEREQ_MSG.enum_types = {}
PM_SHENJICHALLENGERESETBOSSSTAGEREQ_MSG.fields = {
	tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_ACTID_FIELD,
	tb.PM_SHENJICHALLENGERESETBOSSSTAGEREQ_BOSSID_FIELD
}
PM_SHENJICHALLENGERESETBOSSSTAGEREQ_MSG.is_extendable = false
PM_SHENJICHALLENGERESETBOSSSTAGEREQ_MSG.extensions = {}
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_ACTID_FIELD.name = "actId"
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_ACTID_FIELD.full_name = ".PM_ShenJiChallengeResetBossStageRes.actId"
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_ACTID_FIELD.number = 1
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_ACTID_FIELD.index = 0
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_ACTID_FIELD.label = 2
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_ACTID_FIELD.has_default_value = false
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_ACTID_FIELD.default_value = 0
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_ACTID_FIELD.type = 5
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_ACTID_FIELD.cpp_type = 1
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSID_FIELD.name = "bossId"
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSID_FIELD.full_name = ".PM_ShenJiChallengeResetBossStageRes.bossId"
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSID_FIELD.number = 2
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSID_FIELD.index = 1
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSID_FIELD.label = 2
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSID_FIELD.has_default_value = false
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSID_FIELD.default_value = 0
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSID_FIELD.type = 5
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSID_FIELD.cpp_type = 1
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSINFO_FIELD.name = "bossInfo"
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSINFO_FIELD.full_name = ".PM_ShenJiChallengeResetBossStageRes.bossInfo"
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSINFO_FIELD.number = 3
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSINFO_FIELD.index = 2
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSINFO_FIELD.label = 2
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSINFO_FIELD.has_default_value = false
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSINFO_FIELD.default_value = nil
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSINFO_FIELD.message_type = PM_SHENJICLGBOSSSTAGE_MSG
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSINFO_FIELD.type = 11
tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSINFO_FIELD.cpp_type = 10
PM_SHENJICHALLENGERESETBOSSSTAGERES_MSG.name = "PM_ShenJiChallengeResetBossStageRes"
PM_SHENJICHALLENGERESETBOSSSTAGERES_MSG.full_name = ".PM_ShenJiChallengeResetBossStageRes"
PM_SHENJICHALLENGERESETBOSSSTAGERES_MSG.nested_types = {}
PM_SHENJICHALLENGERESETBOSSSTAGERES_MSG.enum_types = {}
PM_SHENJICHALLENGERESETBOSSSTAGERES_MSG.fields = {
	tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_ACTID_FIELD,
	tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSID_FIELD,
	tb.PM_SHENJICHALLENGERESETBOSSSTAGERES_BOSSINFO_FIELD
}
PM_SHENJICHALLENGERESETBOSSSTAGERES_MSG.is_extendable = false
PM_SHENJICHALLENGERESETBOSSSTAGERES_MSG.extensions = {}
tb.PM_SHENJICHALLENGEGAINPRIZEREQ_ACTID_FIELD.name = "actId"
tb.PM_SHENJICHALLENGEGAINPRIZEREQ_ACTID_FIELD.full_name = ".PM_ShenJiChallengeGainPrizeReq.actId"
tb.PM_SHENJICHALLENGEGAINPRIZEREQ_ACTID_FIELD.number = 1
tb.PM_SHENJICHALLENGEGAINPRIZEREQ_ACTID_FIELD.index = 0
tb.PM_SHENJICHALLENGEGAINPRIZEREQ_ACTID_FIELD.label = 2
tb.PM_SHENJICHALLENGEGAINPRIZEREQ_ACTID_FIELD.has_default_value = false
tb.PM_SHENJICHALLENGEGAINPRIZEREQ_ACTID_FIELD.default_value = 0
tb.PM_SHENJICHALLENGEGAINPRIZEREQ_ACTID_FIELD.type = 5
tb.PM_SHENJICHALLENGEGAINPRIZEREQ_ACTID_FIELD.cpp_type = 1
tb.PM_SHENJICHALLENGEGAINPRIZEREQ_BOSSID_FIELD.name = "bossId"
tb.PM_SHENJICHALLENGEGAINPRIZEREQ_BOSSID_FIELD.full_name = ".PM_ShenJiChallengeGainPrizeReq.bossId"
tb.PM_SHENJICHALLENGEGAINPRIZEREQ_BOSSID_FIELD.number = 2
tb.PM_SHENJICHALLENGEGAINPRIZEREQ_BOSSID_FIELD.index = 1
tb.PM_SHENJICHALLENGEGAINPRIZEREQ_BOSSID_FIELD.label = 2
tb.PM_SHENJICHALLENGEGAINPRIZEREQ_BOSSID_FIELD.has_default_value = false
tb.PM_SHENJICHALLENGEGAINPRIZEREQ_BOSSID_FIELD.default_value = 0
tb.PM_SHENJICHALLENGEGAINPRIZEREQ_BOSSID_FIELD.type = 5
tb.PM_SHENJICHALLENGEGAINPRIZEREQ_BOSSID_FIELD.cpp_type = 1
PM_SHENJICHALLENGEGAINPRIZEREQ_MSG.name = "PM_ShenJiChallengeGainPrizeReq"
PM_SHENJICHALLENGEGAINPRIZEREQ_MSG.full_name = ".PM_ShenJiChallengeGainPrizeReq"
PM_SHENJICHALLENGEGAINPRIZEREQ_MSG.nested_types = {}
PM_SHENJICHALLENGEGAINPRIZEREQ_MSG.enum_types = {}
PM_SHENJICHALLENGEGAINPRIZEREQ_MSG.fields = {
	tb.PM_SHENJICHALLENGEGAINPRIZEREQ_ACTID_FIELD,
	tb.PM_SHENJICHALLENGEGAINPRIZEREQ_BOSSID_FIELD
}
PM_SHENJICHALLENGEGAINPRIZEREQ_MSG.is_extendable = false
PM_SHENJICHALLENGEGAINPRIZEREQ_MSG.extensions = {}
tb.PM_SHENJICHALLENGEGAINPRIZERES_ACTID_FIELD.name = "actId"
tb.PM_SHENJICHALLENGEGAINPRIZERES_ACTID_FIELD.full_name = ".PM_ShenJiChallengeGainPrizeRes.actId"
tb.PM_SHENJICHALLENGEGAINPRIZERES_ACTID_FIELD.number = 1
tb.PM_SHENJICHALLENGEGAINPRIZERES_ACTID_FIELD.index = 0
tb.PM_SHENJICHALLENGEGAINPRIZERES_ACTID_FIELD.label = 2
tb.PM_SHENJICHALLENGEGAINPRIZERES_ACTID_FIELD.has_default_value = false
tb.PM_SHENJICHALLENGEGAINPRIZERES_ACTID_FIELD.default_value = 0
tb.PM_SHENJICHALLENGEGAINPRIZERES_ACTID_FIELD.type = 5
tb.PM_SHENJICHALLENGEGAINPRIZERES_ACTID_FIELD.cpp_type = 1
tb.PM_SHENJICHALLENGEGAINPRIZERES_BOSSID_FIELD.name = "bossId"
tb.PM_SHENJICHALLENGEGAINPRIZERES_BOSSID_FIELD.full_name = ".PM_ShenJiChallengeGainPrizeRes.bossId"
tb.PM_SHENJICHALLENGEGAINPRIZERES_BOSSID_FIELD.number = 2
tb.PM_SHENJICHALLENGEGAINPRIZERES_BOSSID_FIELD.index = 1
tb.PM_SHENJICHALLENGEGAINPRIZERES_BOSSID_FIELD.label = 2
tb.PM_SHENJICHALLENGEGAINPRIZERES_BOSSID_FIELD.has_default_value = false
tb.PM_SHENJICHALLENGEGAINPRIZERES_BOSSID_FIELD.default_value = 0
tb.PM_SHENJICHALLENGEGAINPRIZERES_BOSSID_FIELD.type = 5
tb.PM_SHENJICHALLENGEGAINPRIZERES_BOSSID_FIELD.cpp_type = 1
tb.PM_SHENJICHALLENGEGAINPRIZERES_CHANGESETID_FIELD.name = "changeSetId"
tb.PM_SHENJICHALLENGEGAINPRIZERES_CHANGESETID_FIELD.full_name = ".PM_ShenJiChallengeGainPrizeRes.changeSetId"
tb.PM_SHENJICHALLENGEGAINPRIZERES_CHANGESETID_FIELD.number = 3
tb.PM_SHENJICHALLENGEGAINPRIZERES_CHANGESETID_FIELD.index = 2
tb.PM_SHENJICHALLENGEGAINPRIZERES_CHANGESETID_FIELD.label = 2
tb.PM_SHENJICHALLENGEGAINPRIZERES_CHANGESETID_FIELD.has_default_value = false
tb.PM_SHENJICHALLENGEGAINPRIZERES_CHANGESETID_FIELD.default_value = 0
tb.PM_SHENJICHALLENGEGAINPRIZERES_CHANGESETID_FIELD.type = 5
tb.PM_SHENJICHALLENGEGAINPRIZERES_CHANGESETID_FIELD.cpp_type = 1
PM_SHENJICHALLENGEGAINPRIZERES_MSG.name = "PM_ShenJiChallengeGainPrizeRes"
PM_SHENJICHALLENGEGAINPRIZERES_MSG.full_name = ".PM_ShenJiChallengeGainPrizeRes"
PM_SHENJICHALLENGEGAINPRIZERES_MSG.nested_types = {}
PM_SHENJICHALLENGEGAINPRIZERES_MSG.enum_types = {}
PM_SHENJICHALLENGEGAINPRIZERES_MSG.fields = {
	tb.PM_SHENJICHALLENGEGAINPRIZERES_ACTID_FIELD,
	tb.PM_SHENJICHALLENGEGAINPRIZERES_BOSSID_FIELD,
	tb.PM_SHENJICHALLENGEGAINPRIZERES_CHANGESETID_FIELD
}
PM_SHENJICHALLENGEGAINPRIZERES_MSG.is_extendable = false
PM_SHENJICHALLENGEGAINPRIZERES_MSG.extensions = {}
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ACTID_FIELD.name = "actId"
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ACTID_FIELD.full_name = ".PM_KingJiChallengeNotifySelectClgRes.actId"
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ACTID_FIELD.number = 1
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ACTID_FIELD.index = 0
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ACTID_FIELD.label = 2
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ACTID_FIELD.has_default_value = false
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ACTID_FIELD.default_value = 0
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ACTID_FIELD.type = 5
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ACTID_FIELD.cpp_type = 1
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEID_FIELD.name = "stageId"
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEID_FIELD.full_name = ".PM_KingJiChallengeNotifySelectClgRes.stageId"
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEID_FIELD.number = 2
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEID_FIELD.index = 1
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEID_FIELD.label = 2
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEID_FIELD.has_default_value = false
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEID_FIELD.default_value = 0
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEID_FIELD.type = 5
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEID_FIELD.cpp_type = 1
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ISWIN_FIELD.name = "isWin"
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ISWIN_FIELD.full_name = ".PM_KingJiChallengeNotifySelectClgRes.isWin"
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ISWIN_FIELD.number = 3
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ISWIN_FIELD.index = 2
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ISWIN_FIELD.label = 2
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ISWIN_FIELD.has_default_value = false
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ISWIN_FIELD.default_value = false
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ISWIN_FIELD.type = 8
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ISWIN_FIELD.cpp_type = 7
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEINFO_FIELD.name = "stageInfo"
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEINFO_FIELD.full_name = ".PM_KingJiChallengeNotifySelectClgRes.stageInfo"
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEINFO_FIELD.number = 4
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEINFO_FIELD.index = 3
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEINFO_FIELD.label = 2
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEINFO_FIELD.has_default_value = false
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEINFO_FIELD.default_value = nil
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEINFO_FIELD.message_type = PM_SHENJICLGSELECTSTAGE_MSG
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEINFO_FIELD.type = 11
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEINFO_FIELD.cpp_type = 10
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_CHANGEBUFFVALUE_FIELD.name = "changeBuffValue"
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_CHANGEBUFFVALUE_FIELD.full_name = ".PM_KingJiChallengeNotifySelectClgRes.changeBuffValue"
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_CHANGEBUFFVALUE_FIELD.number = 5
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_CHANGEBUFFVALUE_FIELD.index = 4
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_CHANGEBUFFVALUE_FIELD.label = 1
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_CHANGEBUFFVALUE_FIELD.has_default_value = false
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_CHANGEBUFFVALUE_FIELD.default_value = 0
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_CHANGEBUFFVALUE_FIELD.type = 5
tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_CHANGEBUFFVALUE_FIELD.cpp_type = 1
PM_KINGJICHALLENGENOTIFYSELECTCLGRES_MSG.name = "PM_KingJiChallengeNotifySelectClgRes"
PM_KINGJICHALLENGENOTIFYSELECTCLGRES_MSG.full_name = ".PM_KingJiChallengeNotifySelectClgRes"
PM_KINGJICHALLENGENOTIFYSELECTCLGRES_MSG.nested_types = {}
PM_KINGJICHALLENGENOTIFYSELECTCLGRES_MSG.enum_types = {}
PM_KINGJICHALLENGENOTIFYSELECTCLGRES_MSG.fields = {
	tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ACTID_FIELD,
	tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEID_FIELD,
	tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_ISWIN_FIELD,
	tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_STAGEINFO_FIELD,
	tb.PM_KINGJICHALLENGENOTIFYSELECTCLGRES_CHANGEBUFFVALUE_FIELD
}
PM_KINGJICHALLENGENOTIFYSELECTCLGRES_MSG.is_extendable = false
PM_KINGJICHALLENGENOTIFYSELECTCLGRES_MSG.extensions = {}
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ACTID_FIELD.name = "actId"
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ACTID_FIELD.full_name = ".PM_KingJiChallengeNotifyBossClgRes.actId"
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ACTID_FIELD.number = 1
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ACTID_FIELD.index = 0
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ACTID_FIELD.label = 2
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ACTID_FIELD.has_default_value = false
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ACTID_FIELD.default_value = 0
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ACTID_FIELD.type = 5
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ACTID_FIELD.cpp_type = 1
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSID_FIELD.name = "bossId"
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSID_FIELD.full_name = ".PM_KingJiChallengeNotifyBossClgRes.bossId"
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSID_FIELD.number = 2
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSID_FIELD.index = 1
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSID_FIELD.label = 2
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSID_FIELD.has_default_value = false
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSID_FIELD.default_value = 0
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSID_FIELD.type = 5
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSID_FIELD.cpp_type = 1
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISEMULATE_FIELD.name = "isEmulate"
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISEMULATE_FIELD.full_name = ".PM_KingJiChallengeNotifyBossClgRes.isEmulate"
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISEMULATE_FIELD.number = 3
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISEMULATE_FIELD.index = 2
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISEMULATE_FIELD.label = 2
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISEMULATE_FIELD.has_default_value = false
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISEMULATE_FIELD.default_value = false
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISEMULATE_FIELD.type = 8
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISEMULATE_FIELD.cpp_type = 7
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISWIN_FIELD.name = "isWin"
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISWIN_FIELD.full_name = ".PM_KingJiChallengeNotifyBossClgRes.isWin"
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISWIN_FIELD.number = 4
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISWIN_FIELD.index = 3
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISWIN_FIELD.label = 2
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISWIN_FIELD.has_default_value = false
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISWIN_FIELD.default_value = false
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISWIN_FIELD.type = 8
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISWIN_FIELD.cpp_type = 7
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_OUTPUTDAMAGE_FIELD.name = "outputDamage"
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_OUTPUTDAMAGE_FIELD.full_name = ".PM_KingJiChallengeNotifyBossClgRes.outputDamage"
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_OUTPUTDAMAGE_FIELD.number = 5
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_OUTPUTDAMAGE_FIELD.index = 4
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_OUTPUTDAMAGE_FIELD.label = 2
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_OUTPUTDAMAGE_FIELD.has_default_value = false
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_OUTPUTDAMAGE_FIELD.default_value = 0
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_OUTPUTDAMAGE_FIELD.type = 3
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_OUTPUTDAMAGE_FIELD.cpp_type = 2
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_PETIDS_FIELD.name = "petIds"
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_PETIDS_FIELD.full_name = ".PM_KingJiChallengeNotifyBossClgRes.petIds"
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_PETIDS_FIELD.number = 6
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_PETIDS_FIELD.index = 5
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_PETIDS_FIELD.label = 3
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_PETIDS_FIELD.has_default_value = false
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_PETIDS_FIELD.default_value = {}
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_PETIDS_FIELD.type = 5
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_PETIDS_FIELD.cpp_type = 1
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSINFO_FIELD.name = "bossInfo"
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSINFO_FIELD.full_name = ".PM_KingJiChallengeNotifyBossClgRes.bossInfo"
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSINFO_FIELD.number = 7
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSINFO_FIELD.index = 6
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSINFO_FIELD.label = 1
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSINFO_FIELD.has_default_value = false
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSINFO_FIELD.default_value = nil
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSINFO_FIELD.message_type = PM_SHENJICLGBOSSSTAGE_MSG
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSINFO_FIELD.type = 11
tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSINFO_FIELD.cpp_type = 10
PM_KINGJICHALLENGENOTIFYBOSSCLGRES_MSG.name = "PM_KingJiChallengeNotifyBossClgRes"
PM_KINGJICHALLENGENOTIFYBOSSCLGRES_MSG.full_name = ".PM_KingJiChallengeNotifyBossClgRes"
PM_KINGJICHALLENGENOTIFYBOSSCLGRES_MSG.nested_types = {}
PM_KINGJICHALLENGENOTIFYBOSSCLGRES_MSG.enum_types = {}
PM_KINGJICHALLENGENOTIFYBOSSCLGRES_MSG.fields = {
	tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ACTID_FIELD,
	tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSID_FIELD,
	tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISEMULATE_FIELD,
	tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_ISWIN_FIELD,
	tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_OUTPUTDAMAGE_FIELD,
	tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_PETIDS_FIELD,
	tb.PM_KINGJICHALLENGENOTIFYBOSSCLGRES_BOSSINFO_FIELD
}
PM_KINGJICHALLENGENOTIFYBOSSCLGRES_MSG.is_extendable = false
PM_KINGJICHALLENGENOTIFYBOSSCLGRES_MSG.extensions = {}
PM_KingJiChallengeNotifyBossClgRes = protobuf.Message(PM_KINGJICHALLENGENOTIFYBOSSCLGRES_MSG)
PM_KingJiChallengeNotifySelectClgRes = protobuf.Message(PM_KINGJICHALLENGENOTIFYSELECTCLGRES_MSG)
PM_ShenJiChallengeBossClgReq = protobuf.Message(PM_SHENJICHALLENGEBOSSCLGREQ_MSG)
PM_ShenJiChallengeBossClgRes = protobuf.Message(PM_SHENJICHALLENGEBOSSCLGRES_MSG)
PM_ShenJiChallengeGainPrizeReq = protobuf.Message(PM_SHENJICHALLENGEGAINPRIZEREQ_MSG)
PM_ShenJiChallengeGainPrizeRes = protobuf.Message(PM_SHENJICHALLENGEGAINPRIZERES_MSG)
PM_ShenJiChallengeGetInfoReq = protobuf.Message(PM_SHENJICHALLENGEGETINFOREQ_MSG)
PM_ShenJiChallengeGetInfoRes = protobuf.Message(PM_SHENJICHALLENGEGETINFORES_MSG)
PM_ShenJiChallengeResetBossStageReq = protobuf.Message(PM_SHENJICHALLENGERESETBOSSSTAGEREQ_MSG)
PM_ShenJiChallengeResetBossStageRes = protobuf.Message(PM_SHENJICHALLENGERESETBOSSSTAGERES_MSG)
PM_ShenJiChallengeSelectClgReq = protobuf.Message(PM_SHENJICHALLENGESELECTCLGREQ_MSG)
PM_ShenJiChallengeSelectClgRes = protobuf.Message(PM_SHENJICHALLENGESELECTCLGRES_MSG)
PM_ShenJiClgBossStage = protobuf.Message(PM_SHENJICLGBOSSSTAGE_MSG)
PM_ShenJiClgSelectStage = protobuf.Message(PM_SHENJICLGSELECTSTAGE_MSG)

return _G["logic.proto.ShenJiChallengeExtension_pb"]
