namespace ProjectA.Data;

table CardData {
  card_id:int;
  card_base_id:int;
  rare:int;
  show_img:string;
  card_mid_pic_icon:string;
  card_small_pic_icon:string;
  big_img:string;
  card_show_prefab:string;
  job:string;
  name:string;
  full_name:string;
  job_des:string;
  job_video:string;
  name_pic:string;
  name_position:string;
  passive_skill_length:int;
  mp_initial_value:int;
  mp_limit_value:int;
  ap:int;
  ap_normal_recover:int;
  ap_fast_recover:int;
  base_relation_exp:int;
  hp:int;
  attack:int;
  defense:int;
  crit_value:int;
  block_value:int;
  dodge_value:int;
  crit_rate:int;
  critical_damage:int;
  block_rate:int;
  block_damage:int;
  dodge_rate:int;
  hitup_max:int;
  walk_speed:int;
  moving_speed:int;
  rotate_speed:int;
  model_id:int;
  icon_id:string;
  bg_color:int;
  food_ui_offset:int;
  defence_type:int;
  defence_rate:int;
  text:string;
  stable_intensity:int;
  weight:int;
  height:int;
  range:int;
  hate:int;
  hate_ratio:int;
  blood_lv1:int;
  blood_lv2:int;
  blood_lv3:int;
  hit_color1:int;
  hit_color2:int;
  element_length:int;
  occupation_length:int;
  radar_length:int;
  sight_tracing:string;
  offset:int;
  scale:int;
  gain_id_length:int;
  special_id:int;
  skill_name_id:string;
  skill_name_color_length:int;
  skill_name_stroke_color_length:int;
  dodge_point:int;
  dodge_worked_ap_recover:int;
  ai_player_on_damage_rate:int;
  last_attack_timeline_length:int;
  energy_id:int;
  energy_buff_id_length:int;
  energy_prefab:string;
  feature_timeline:string;
  clothes_change_voice:int;
  advance_id:int;
  advance_value:int;
  dodge_success_se:string;
  lottery_voice:int;
  support_type:int;
  axis_x_intro:int;
  axis_yintro:int;
  proficient_x_intro:int;
  proficient_yintro:int;
  pronunciation:string;
  weapen_rotation:int;
  max_adv_voice:int;
  is_illustrated_book:bool;
  coin_type_num_length:int;
  coin_type_num_full_length:int;
  version_id:int;
  behaviortree:int;
}

table CardTable {
  datas:[CardData];
}

root_type CardTable;
