<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>P08.ToLua</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <TargetFramework>net40</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Debugger">
      <HintPath>../../../../../../../tmp/ag_decompile_1t3uzm9t/ref/Debugger.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>../../../../../../../tmp/ag_decompile_1t3uzm9t/ref/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>../../../../../../../tmp/ag_decompile_1t3uzm9t/ref/UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>../../../../../../../tmp/ag_decompile_1t3uzm9t/ref/UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="CString">
      <HintPath>../../../../../../../tmp/ag_decompile_1t3uzm9t/ref/CString.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>../../../../../../../tmp/ag_decompile_1t3uzm9t/ref/UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>../../../../../../../tmp/ag_decompile_1t3uzm9t/ref/UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="P08.Base">
      <HintPath>../../../../../../../tmp/ag_decompile_1t3uzm9t/ref/P08.Base.dll</HintPath>
    </Reference>
    <Reference Include="spine-unity">
      <HintPath>../../../../../../../tmp/ag_decompile_1t3uzm9t/ref/spine-unity.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>../../../../../../../tmp/ag_decompile_1t3uzm9t/ref/UnityEngine.VideoModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.DirectorModule">
      <HintPath>../../../../../../../tmp/ag_decompile_1t3uzm9t/ref/UnityEngine.DirectorModule.dll</HintPath>
    </Reference>
    <Reference Include="P08.3rd">
      <HintPath>../../../../../../../tmp/ag_decompile_1t3uzm9t/ref/P08.3rd.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>../../../../../../../tmp/ag_decompile_1t3uzm9t/ref/UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>../../../../../../../tmp/ag_decompile_1t3uzm9t/ref/UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>../../../../../../../tmp/ag_decompile_1t3uzm9t/ref/System.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>