---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yajieli.
--- DateTime: 2019-08-14 17:58

---@type ECSComponent
local ECSComponent = import("Frame.ECS.ECSComponent")

---@class PlayerComponent
local PlayerComponent = Class("PlayerComponent", ECSComponent)

---@type PlayerDojo
local PlayerDojo = import("Game.Dojo.PlayerDojo")

---@type CardStarGiftDojo
local CardStarGiftDojo = import("Game.UI.LimitedTimeSale.CardStarGiftDojo")

local UIModule = CS.Engine.UI.UIModule
local kTool = CS.Engine.Lib.KTool

---@type PlayerInfoUtils
local PlayerInfoUtils = import('Game.UI.Player.PlayerInfoUtils')

local CountDownTime = 2592000 --30 * 86400 30天的秒数


function PlayerComponent:__init()
    ECSComponent.__init(self)
    self.name = "PlayerComponent"
    ---@type PlayerDojo
    self.playerDojo = PlayerDojo.New()

    ---@type CardStarGiftDojo
    self._cardStarGiftsDojo = CardStarGiftDojo.New()

    self.__rewardsDialogInfo = {}
    self.__functionUnlockDialogDataInfo = {}

    ---@type Engine.Modules.CDTimerModule @ @ 玩家头像、头像框、徽章，倒计时map（key：道具id，value：计时器）
    self.playerHeadUpdateTimer_ = CfUtils.CDTimerAppend(1, CountDownTime, false, true, Bind(self, self.OnPlayerHeadTimerUpdateHandler_))

    self.progressInfo = {}
    self.randomTime = 0
    self.isStartedTcp = false

    ---@type GlobalTalentMgr
    GlobalTalentMgr = import('Game.GlobalTalent.GlobalTalentMgr')
end

function PlayerComponent:__delete()
    self.isStartedTcp = false
    self:StopRewardsSpecialDialogCo()
    self.randomTime = nil
    self.name = nil
    self.playerDojo = nil
    self._cardStarGiftsDojo = nil

    --新加战队信息
    self.fightcards = nil

    self.progressInfo = nil
    self.__rewardsDialogInfo = nil
    self.__functionUnlockDialogDataInfo = nil

    if isNotNull(self.playerHeadUpdateTimer_) then
        CfUtils.CDTimerRemove(self.playerHeadUpdateTimer_)
        self.playerHeadUpdateTimer_ = nil
    end

    if GlobalTalentMgr then
        GlobalTalentMgr:GetInstance():Delete()
        GlobalTalentMgr = nil
    end
end

---@param dojo CardStarGiftDojo
function PlayerComponent:SetCardStarGiftDojo(dojo)
    self._cardStarGiftsDojo = dojo
end

---@return CardStarGiftDojo
function PlayerComponent:GetCardStarGiftDojo()
    return self._cardStarGiftsDojo
end

function PlayerComponent:RemoveCardStarGiftDojoTimer()
    self._cardStarGiftsDojo:RemoveTimer()
end

---IsOpenByLevel
---色彩等级是否解锁
---@param openLevel number
function PlayerComponent:IsOpenByLevel(openLevel)
    return checkNumber(self.playerDojo.level) >= checkNumber(openLevel)
end

function PlayerComponent:__ShowWaterMark()
    local trans = UIModule.RootCanvas.transform.parent.transform
    local wmGo = trans:Find("UIWaterMark")
    if not wmGo then
        local loader = CS.Engine.Modules.ResourceModule.LoadBundleSync('Prefabs/UIWaterMark.prefab', nil, true)
        if loader and loader.IsSuccess then
            wmGo = loader:Instantiate(trans, false)
            wmGo.name = "UIWaterMark"
            kTool.SetActive(wmGo, true)
            wmGo.gameObject:GetComponent(typeof(CS.UnityEngine.Canvas)).renderMode = CS.UnityEngine.RenderMode.ScreenSpaceOverlay
            local t = wmGo:GetComponent(typeof(CS.UnityEngine.RectTransform))
            t.anchorMin = Vector2.zero
            t.anchorMax = Vector2.one
            t.offsetMin = Vector2.zero
            t.offsetMax = Vector2.zero
            t.localPosition = Vector3.zero
            t.localRotation = Quaternion.identity
            t.localScale = Vector3.one
            wmGo.layer = trans.gameObject.layer
        end
        loader:Release()
    else
        kTool.SetActive(wmGo, true)
    end

    if wmGo then
        ---@type UIWaterMark
        local wmGoEnv = CfUtils.GetLuaScr(wmGo, "Game.Main.UIWaterMark")
        if wmGoEnv then
            wmGoEnv:SetPlayerId(self.playerDojo.playerId)
        end
    end
end

---LoadPlayer
---更新角色数据
---@param json_str string
function PlayerComponent:LoadPlayer(json_str)
    self.randomTime = os.time()
    local data = json_str
    if type(json_str) == "string" then
        data = table.deserialize(json_str)
    end
    self.playerDojo:Fill(data)
    if self.playerDojo.playerId then
        self:__ShowWaterMark()
    end
    local isSet = isSet
    --背包的初始化数据
    if isSet(data, "backpack") then
        ---@type BackpackComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.BackpackComponent)
        comp:Initial(data.backpack, data.backpackExtend, data.backpackLocked)
    end

    if next(self.playerDojo.selectedAlbumMap) == nil then
        self.playerDojo.selectedAlbumMap[PlayerInfoUtils.GetDefaultMusicId()] = true
    end

    --卡牌的初始化数据
    if isSet(data, "cards") then
        ---@type ECSEntity
        local entity = self.entity
        if entity:IsCompExistsByName(ECSComponentType.Constants.CardComponent) then
            entity:RemoveComp(ECSComponentType.Constants.CardComponent)
        end
        ---@type CardComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.CardComponent)
        comp:Initial(data.cards)

        if next(self.playerDojo.revealTeam) == nil then
            local refId = CfUtils.GetCfVo(AutoIds.IdSetting950, "PersonalInfoVo", Constants.PersonalInfoVoId.CardDrawingId).num
            local cardId = comp:GetIdByCardId(refId)
            table.insert(self.playerDojo.revealTeam, cardId)
        end

        if Config.DEBUG then
            if self.playerDojo.signboardId == 0 then
                local card = table.takeFirst(comp:GetAllCardTable())
                self.playerDojo.signboardId = card.id
            end
        end
    end

    --卡牌皮肤的初始化数据
    if isSet(data, "cardSkins") then
        ---@type ECSEntity
        local entity = self.entity
        if entity:IsCompExistsByName(ECSComponentType.Constants.CardSkinComponent) then
            entity:RemoveComp(ECSComponentType.Constants.CardSkinComponent)
        end
        ---@type CardSkinComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.CardSkinComponent)
        comp:Initial(data.cardSkins, checkNumber(data.skinLevelUpTimes))
    end

    ----中型PT活动初始化数据  改到活动里了
    --if isSet(data, "activityPlotQuest") then
    --    ---@type MediumPTActivityComponent
    --    local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.MediumPTActivityComponent)
    --    comp:InitCheckInData(data.activityPlotQuest)
    --end

    --装备的初始化数据
    if isSet(data, "equipments") then
        ---@type ECSEntity
        local entity = self.entity
        if entity:IsCompExistsByName(ECSComponentType.Constants.EquipmentComponent) then
            entity:RemoveComp(ECSComponentType.Constants.EquipmentComponent)
        end
        ---@type EquipmentComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.EquipmentComponent)
        comp:Initial(data.equipments)
        -- comp:InitialDiySuits(data.equipmentDiySuits)
    end

    --战前的信息(章节和关卡信息) 
    --add by thl 2019.12.11
    if isSet(data, "newQuestId") then
        ---@type QuestComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.QuestComponent)
        comp:Initial(data.newQuestId, data.mainTaskInfo, data.sideStory, data.chapterReward)
    end

    --困难主线(章节和关卡信息)
    if isSet(data, "difficultNewQuestId") then
        ---@type QuestComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.QuestComponent)
        comp:InitialHardQuest(data.difficultNewQuestId, data.difficultNewQuestPassedTimes)
    end

    --编队信息(弃用)
    --if isSet(data, "copyTeam") then
    --    ---@type TeamComponent
    --    local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.TeamComponent)
    --    comp:Initial(data.copyTeam)
    --end

    --编队信息
    if isSet(data, "teams") then
        ---@type TeamComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.TeamComponent)
        comp:Initial(data.teams, data.copyTeam)
    end

    if isSet(data, "tips") then
        ---@type RedPointMgrComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.RedPointMgrComponent)
        if isNotNull(data.tips) and checkInt(data.tips.unFreeHp) > 0 then
            data.tips.unFreeHp = -1 
        end
        comp:Initial(data.tips)
        ---@type QuestComponent
        local questComponent = self.entity:GetOrAddComp(ECSComponentType.Constants.QuestComponent)
        if questComponent then
            questComponent:UnlockFishPlaceState()
        end
        if isSet(data, "hasDrawVip") then
            GameUtils.SetRedPointNum(Constants.RedPointConst.VipFund, (checkNumber(data.showVip) == 1 and checkNumber(data.hasDrawVip) == 0) and 1 or 0)
            GameUtils.InvokeRedPointCallBack(Constants.RedPointConst.VipFund)
        end
    end

    ---可使用道具
    if isSet(data, "items") then
        ---@type UsableGoodComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.UsableGoodComponent)
        comp:Initial(data.items)
    end

    ---委托列表
    if isSet(data, "consignInfo") then
        ---@type TeamComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.TeamComponent)
        comp:InitialEntrustData(data.consignInfo)
    end

    ---高级装备副本当前关卡信息
    if isSet(data, "equipmentQuestId") and isSet(data, "equipmentQuestPassedId") then
        ---@type EquipQuestComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.EquipQuestComponent)
        comp:InitialCurSeniorQusetInfo(data.equipmentQuestId, data.equipmentQuestPassedId)
    end

    ---角色信息
    if isSet(data, "cats") then
        ---@type PhoneComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.PhoneComponent)
        comp:Initial(data.cats)
    end
    if isNull(data.catList) then
        data.catList = {}
    end
    if isNull(data.cafeCatConvertBackpack) then
        data.cafeCatConvertBackpack = {}
    end

    if isSet(data, "catBalls") and isSet(data, "catBallConvertBackpack") then
        ---@type CatEggComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.CatEggComponent)
        -- -- print("data.catList", table.toString(data.catList))
        -- ---@type CatBallVo[]
        -- local vos = CfUtils.GetCf(AutoIds.IdSetting6033, "CatBallVo", true)
        -- print("vos", table.toString(vos))
        -- for index, value in ipairs(vos) do
        --     table.insert(data.catList, {
        --         id = value.roleId,
        --         catId = value.roleId,
        --         star = math.random(value.starMin, value.starMax),
        --     })
        -- end

        comp:InitialDojo(data.catBalls)
        comp:SetConvertBackpack(data.catBallConvertBackpack)
    end

    ---话题信息
    if isSet(data, "phoneTopics") then
        ---@type PhoneComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.PhoneComponent)
        comp:InitialTalkContent(data.phoneTopics)
    end

    if isSet(data, "guideId") then
        ---@type GuideComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.GuideComponent)
        comp:Initial(checkNumber(data.guideId), checkTable(data.specialGuide), data.receivedGuideRewards)
    end

    if isSet(data, "monthCard") then
        ---@type StoreComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.StoreComponent)
        comp:InitialMonthCardInfo(data.monthCard)
    end
    if isSet(data, "privilegeCards") then
        self:InitPrivilegeCards(data.privilegeCards)

    end
    --世界boss
    if isSet(data, "worldBossInfo") then
        ---@type WorldBossComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.WorldBossComponent)
        comp:InitialBossInfo(data.worldBossInfo)
    end

    --竹林副本占位
    if isSet(data, "ptActivityInfo") then
        ---@type BambooQuestComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.BambooQuestComponent)
        comp:Initial(data.ptActivityInfo)
    end

    if isSet(data, "prologues") then
        ---@type ProloguesQuestComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.ProloguesQuestComponent)
        comp:Fill(data.prologues)
    end

    if isSet(data, "makeCallInfo") then
        --printInfo("makeCallInfo===>>"..table.dump(data.makeCallInfo))
        ---@type ForgingComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.ForgingComponent)
        comp:InitialCheckInDojo(data.makeCallInfo)
    end

    if isSet(data, "cookingInfo") then
        ---@type CookingComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.CookingComponent)
        comp:Initial(data.cookingInfo, data.favorabilityUnlockCooking)
    end

    if isSet(data, "festivalSignInInfo") then
        ---@type FeatureSignComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.FeatureSignComponent)
        comp:InitFestivalSignInInfo(data.festivalSignInInfo)
    end

    if isSet(data, "battleCooking") then
        ---@type CookingComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.CookingComponent)
        comp:InitialBattleCookingData(data.battleCooking)
    end

    if isSet(data, "battleCookingSwitch") then
        ---@type CookingComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.CookingComponent)
        comp:InitialActiveBattleFood(data.battleCookingSwitch)
    end

    if isSet(data, "triggerChest") then
        ---@type TriggerGiftComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.TriggerGiftComponent)
        --local testData = {
        --    {
        --        id = 101,
        --        type = 2,
        --        activatedNum = 11,
        --        expirationTime = 10,
        --        rewards = { { id = 300002, num = 1}, }, 
        --    },
        --    {
        --        id = 102,
        --        type = 2,
        --        activatedNum = 11,
        --        expirationTime = 20,
        --        rewards = { { id = 300002, num = 1},}
        --    },
        --}
        ---FillGiftData
        ---填充礼包数据, giftReq 和 CheckIn
        ---@param data table
        --data.id --礼包id
        --data.type --类型
        --data.activatedNum --解锁条件(List)
        --data.expirationTime --礼包剩余时间
        --data.rewards --奖励道具(List)
        --data.consume --消耗道具(List)
        --comp:FillGiftData(testData)
        comp:FillGiftData(data.triggerChest)
    end
    if isSet(data, "cardCollection") then
        --判断数据是否为空
        if next(data.cardCollection) ~= nil then
            ---@type GatherActivityComponent
            local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.GatherActivityComponent)
            comp:FillData(data.cardCollection)
        end
    end

    if isSet(data, "isTriggerChestTips") then
        local isTrigger = checkInt(data.isTriggerChestTips)
        if isTrigger > 0 then
            ---@type TriggerGiftComponent
            local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.TriggerGiftComponent)
            --comp:SetBoolNeedTrigger(true)
            comp:TriggerGiftReq()
        end
    end

    if isSet(data, "scrollImages") then
        ---@type ScrollEntryComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.ScrollEntryComponent)
        comp:Initial(data.scrollImages)
    end

    if isSet(data, "advertise") then
        ---@type AdvertiseEntryComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.AdvertiseEntryComponent)
        comp:Initial(data.advertise)
    end

    if isSet(data, 'channelProductIds') then
        local sdkService = import('Game.Entry.SDKService')
        sdkService:GetInstance():LoadProducts(data.channelProductIds)
    end

    if isSet(data, 'visitPermission') then
        local maidCoffeeComponent = GameUtils.GetOrAddEntityCompByType(ECSComponentType.Constants.MaidCoffeeComponent)
        maidCoffeeComponent:UpdateVisitPermission(checkNumber(data.visitPermission))
    end

    ---@type MaidCoffeePlayerComponent
    local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.MaidCoffeePlayerComponent)
    comp:Initialize(data)

    if isSet(data, "cafePushInfo") then
        AppService:GetInstance():StartManageTip(data.cafePushInfo, true)
    end

    if isSet(data, "mainViewProcessInfo") then
        self:UpdateProgressInfo(data.mainViewProcessInfo)
    end

    if isSet(data, "unfinishedPVPBattle") then
        ---@type ActionComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.ActionComponent)
        comp:SetUnfinishedPVPBattleData(data.unfinishedPVPBattle)
    end
    if isSet(data, "overseaRegionMapInfo") then
        ---@type ActionComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.ActionComponent)
        comp:InitHomeData(data.overseaRegionMapInfo)
    end

    if isSet(data, "callActivity") then
        local gachaponUtils = import('Game.Gachapon.GachaponUtils')
        local gachaponComp  = gachaponUtils.GetGachaponComp()
        gachaponComp:UpdateHomeActivityDatas(data.callActivity)
    end

    if isSet(data, "callConsumeInfo") then
        local gachaponUtils = import('Game.Gachapon.GachaponUtils')
        local gachaponComp  = gachaponUtils.GetGachaponComp()
        gachaponComp:UpdateConsumeDatas(data.callConsumeInfo)
    end

    if isSet(data, "clubData") then
        local clubComp = ClubUtils.GetClubComp()
        if checkInt(data.clubData.clubId) > 0 then
            clubComp:InitialClubData(data.clubData)
            clubComp:SetApplyListRedPoint(tostring(data.clubData.applyTips) == '0')
        end
        local joinLeftSeconds = checkInt(data.clubData.quitClubTtl)
        if joinLeftSeconds > 0 then
            clubComp:SetQuitTimestamp(os.time() + joinLeftSeconds)
        end
    end

    -- 爬塔 更新主塔关卡id
    if isSet(data, "overseaClimbingTowerId") then
        local towerQuestComponent = self.entity:GetOrAddComp(ECSComponentType.Constants.TowerQuestComponent)
        towerQuestComponent:UpdateMainTowerQuestId(data.overseaClimbingTowerId)
    end

    if isSet(data, "investAddition") then
        local DailyInvestMgr = import('Game.UI.ResidentEvent.DailyInvestMgr')
        DailyInvestMgr:GetInstance():SavePropertyData(data.investAddition)
    end

    if isSet(data, "hotspotCollectionCloseCountdown") then
        ---@type HotPointCollectionComponent
        local comp = self.entity:GetOrAddComp(ECSComponentType.Constants.HotPointCollectionComponent)
        comp:Initial(data.hotspotCollectionCloseCountdown, data.hotspotCollectionActivityUuid)
    end

    -- 爬塔 更新主塔关卡id
    if isSet(data, "skinCall") then
        ---@type ActivityCardSkinComponent
        local ActivityCardSkinComponent = self.entity:GetOrAddComp(ECSComponentType.Constants.ActivityCardSkinComponent)
        ActivityCardSkinComponent:Initial(data.skinCall)
    end

    if isSet(data, "whiteLevelGift") then
        ---@type WhiteLevelGiftComponent
        local whiteLevelGiftComponent = self.entity:GetOrAddComp(ECSComponentType.Constants.WhiteLevelGiftComponent)
        whiteLevelGiftComponent:InitLevelGift(data.whiteLevelGift, self.playerDojo.level, data.whiteLevelGiftTodayReceived)
    end
    if isSet(data, "dailySignIn") then
        self:CheckPlayerSignInBox()
    end

    ---@type IllustratedHandbookComponent
    local illustratedHandbookComp = self.entity:GetOrAddComp(ECSComponentType.Constants.IllustratedHandbookComponent)
    -- 养成全局属性解锁（新号该字段不返回，所以不加判断直接调用）
    illustratedHandbookComp:InitialAdditionInfo(data.developAdditionInfo)  -- Ps：一定要写在 初始完 cards 之后，因为该方法里会立刻取值判断
    -- 海外图鉴：卡牌、皮肤、猫种、猫球收集（新号该字段不返回，所以不加判断直接调用）
    illustratedHandbookComp:InitialCollectionInfo()  -- Ps：一定要写在 初始完 cards 和 cardSkins 和 catBalls 之后，因为该方法里会立刻取值
    -- 海外图鉴：百科收集
    illustratedHandbookComp:InitialKeywordEncyInfo()  -- Ps：一定要写在 newQuestId 之后，因为该方法里会立刻取值
    -- 海外图鉴：区域收集
    illustratedHandbookComp:InitialRegionMapInfo()  -- Ps：一定要写在 初试完 overseaRegionMapInfo 之后，因为该方法里会立刻取值判断

    if not self.isStartedTcp then
        self.isStartedTcp = true
        ---开启tcp服务
        AppService:GetInstance():StartTCP(true)
        ---新的逻辑下需要加载两个图集
        CS.Engine.Modules.SpriteAtlasLoader.LoadAtlas('uiatlas/common2/common2.spriteatlas', nil, true)
        CS.Engine.Modules.SpriteAtlasLoader.LoadAtlas('uiatlas/CommonTransition/commontransition.spriteatlas', nil, true)
        ---TODO 记得要在可切账号的时候手动再释放一次
        CS.Engine.Modules.SpriteAtlasLoader.LoadAtlas('uiatlas/chapterui/chapterui.spriteatlas', nil, true)
    end

    if isSet(data, "talentData") then
        ---@type HomelandTalentComponent
        local component = self.entity:GetOrAddComp(ECSComponentType.Constants.HomelandTalentComponent)
        component:InitTalentData(data.talentData)
    end

    -- 更新推送按钮的开关状态
    if isSet(data, "pushSettings") then
        self:UpdatePushSetting(data.pushSettings)
    end
    --- 特权卡
    if isSet(data, "overseaPrivilegeCard") then
        local isHave = self:IsPrivilegeCard()
        if isHave then
            local isOpen =  CfUtils.IsOpneByFunctionId(10004)
            if isOpen  then
                local day = checkInt(CfUtils.GetLocalData("AdvertisementReward",0))
                if day < checkInt(self:GetPlayerDojo():GetServerTime()) then
                    GameUtils.SetRedPointNum(Constants.RedPointConst.AdvertisementReward , 1)
                end
            end
            self:RegGlobalTalentPrivilegeCard()
        end
    end

    if isSet(data,"krDiamond") then
        ---@type StoreUtils
        local StoreUtils = import('Game.UI.Store.StoreUtils')
        ---@type OverseaStoreComponent
        local overseaStoreComponent =  StoreUtils.GetOverseaStoreComp()
        overseaStoreComponent:SetPrimaryCurrencyData(data.krDiamond)
    end

    local isOpened = GameUtils.IsSwitchedBySystemTogId(Constants.SystemToggleIds.Id6003)
    local isUnlock = GameUtils.IsUnlockedBySystemTogId(Constants.SystemToggleIds.Id6003)
    if isOpened and isUnlock then
        -- 信息录入
        ---@type HomelandCheckInComponent
        local comp = GameUtils.GetOrAddEntityCompByType(ECSComponentType.Constants.HomelandCheckInComponent)
        comp:InitCheckInData(checkTable(data.collectionCheckin), checkNumber(data.collectionCheckinNum))
    end
end
function PlayerComponent:CheckPlayerSignInBox()
    local playerDojo = self:GetPlayerDojo()
    local dailySignIn = playerDojo.dailySignIn
    local treasureDays = checkInt(dailySignIn.treasureDays)
    local treasureDrawIds = dailySignIn.treasureDrawIds
    local treasureRewards = dailySignIn.treasureRewards
    local isCanDraw = false
    for k, v in pairs(treasureRewards) do
        if treasureDays >= checkInt(v.times) then
            local isHaveDraw = false 
            for index , id  in pairs(treasureDrawIds) do
                if checkInt(id) == checkInt(v.id) then
                    isHaveDraw = true 
                    break
                end
            end
            if not isHaveDraw then
                isCanDraw = true   
                break  
            end            
        end
    end
    if isCanDraw then
        GameUtils.SetRedPointNum(Constants.RedPointConst.PlayerSignIn , 1)
        GameUtils.InvokeRedPointCallBack(Constants.RedPointConst.PlayerSignIn)
    else 
        GameUtils.SetRedPointNum(Constants.RedPointConst.PlayerSignIn , 0)
        GameUtils.InvokeRedPointCallBack(Constants.RedPointConst.PlayerSignIn)
    end
end
function PlayerComponent:InitPrivilegeCards(privilegeCards)
    local currentTime = os.time()
    for i, v in pairs(privilegeCards) do
        v.lastTime = currentTime
    end
    self.playerDojo.privilegeCards = privilegeCards
end
function PlayerComponent:GetPrivilegeCardById(id)
    id = checkInt(id)
    local privilegeCard = {}
    for i, v in pairs(self:GetPlayerDojo().privilegeCards) do
        if id == v.privilegeCardId then
            privilegeCard = v
            break
        end
    end
    return privilegeCard
end
function PlayerComponent:GetPrivilegeCardSecondsById(id)
    local privilegeCard = self:GetPrivilegeCardById(id)
    if privilegeCard.lastTime then
        local remainSeconds = privilegeCard.remainSeconds - (os.time() - privilegeCard.lastTime)
        if remainSeconds < 0 then
            return 0
        else
            return remainSeconds
        end
    end
    return privilegeCard.remainSeconds or 0
end

function PlayerComponent:GetPrivilegeCards()
    return self:GetPlayerDojo().privilegeCards
end

---UpdateGoodsNo
---
---@param id number
---@param addV number
function PlayerComponent:UpdateGoodsNo(id, addV)
    local checkNumber = checkNumber
    id = checkNumber(id)
    if id == Constants.Currency.GoldId then
        self.playerDojo.gold = checkNumber(self.playerDojo.gold) + checkNumber(addV)
    elseif id == Constants.Currency.PayDiamondId then
        self.playerDojo.diamond = checkNumber(self.playerDojo.diamond) + checkNumber(addV)
    elseif id == Constants.Currency.FreeDiamondId then
        self.playerDojo.freeDiamond = checkNumber(self.playerDojo.freeDiamond) + checkNumber(addV)
    elseif id == Constants.Currency.HpId then
        self.playerDojo.hp = checkNumber(self.playerDojo.hp) + checkNumber(addV)
        AppService:GetInstance():UpdateRecoveryValue(self.playerDojo.hp)
    elseif id == Constants.Currency.LadderTicket then
        self.playerDojo.ladderTicketNums = checkNumber(self.playerDojo.ladderTicketNums) + checkNumber(addV)
    elseif id == Constants.Currency.LadderCoin then
        self.playerDojo.ladderCoin = checkNumber(self.playerDojo.ladderCoin) + checkNumber(addV)
    elseif id == Constants.Currency.WorldBossCoin then
        self.playerDojo.worldBossCoin = checkNumber(self.playerDojo.worldBossCoin) + checkNumber(addV)
    elseif id == Constants.Currency.LadderStruggleCurrency then
        self.playerDojo.asyncCoin = checkNumber(self.playerDojo.asyncCoin) + checkNumber(addV)
    elseif id == Constants.Currency.LadderStruggleTicket then
        self.playerDojo.asyncRecoverTicket = checkNumber(self.playerDojo.asyncRecoverTicket) + checkNumber(addV)
    elseif id == Constants.Currency.LadderStruggleSingleCurrency then
        self.playerDojo.asyncCoin = checkNumber(self.playerDojo.asyncCoin) + checkNumber(addV)
    elseif id == Constants.Currency.LadderStruggleSingleTicket then
        self.playerDojo.asyncSingleRecoverTicket = checkNumber(self.playerDojo.asyncSingleRecoverTicket) + checkNumber(addV)
    elseif id == Constants.Currency.CartCatTicket then
        self.playerDojo.catCarCoin = checkNumber(self.playerDojo.catCarCoin) + checkNumber(addV)
    elseif id == Constants.Currency.CumulativeScore then
        --self.playerDojo.payCumulative = checkNumber(self.playerDojo.payCumulative) + checkNumber(addV)
        ---充值积分特殊处理，只在充值的时候更新，其他道具领取时不做任何处理
        self.playerDojo.payCumulative = checkNumber(self.playerDojo.payCumulative)
    elseif id == Constants.Currency.TipCoin then
        self.playerDojo.tipCoin = checkNumber(self.playerDojo.tipCoin) + checkNumber(addV)
    elseif id == Constants.Currency.ClubCoin then
        self.playerDojo.clubCoin = checkNumber(self.playerDojo.clubCoin) + checkNumber(addV)
    elseif id == Constants.Currency.CatBallTicket then
        self.playerDojo.catBallTicket = checkNumber(self.playerDojo.catBallTicket) + checkNumber(addV)
    elseif id == Constants.Currency.TowerTicket then
        self.playerDojo.towerTicket = checkNumber(self.playerDojo.towerTicket) + checkNumber(addV)
    elseif id == Constants.Currency.ClubFeedCatSkinCoin then
        self.playerDojo.clubFeedCatSkinCoin = checkNumber(self.playerDojo.clubFeedCatSkinCoin) + checkNumber(addV)
    elseif id == Constants.Currency.LightDarkCoin then
        self.playerDojo.lightDarkCoin = checkNumber(self.playerDojo.lightDarkCoin) + checkNumber(addV)
    elseif id == Constants.Currency.BattleCardGameCoin then
        self.playerDojo.stardustCoin = checkNumber(self.playerDojo.stardustCoin) + checkNumber(addV)
    elseif id == Constants.Currency.StoreSkinTicket then
        self.playerDojo.skinTicket = checkNumber(self.playerDojo.skinTicket) + checkNumber(addV)
    else
        if isSet(self.playerDojo.currency, tostring(id)) then
            local num = checkNumber(self.playerDojo.currency[tostring(id)])
            self.playerDojo.currency[tostring(id)] = num + checkNumber(addV)
        end
    end
    Events.Broadcast(Constants.EventNames.EveryThingChangeEventName, checkNumber(id))
end

function PlayerComponent:ShowExpChangeTips(data)
    --data["oldLevel"] = 2
    --data["nowExp"] = 48
    --data["oldExp"] = 32
    --data["nowLevel"] = 3
    --print("expData------>>"..table.dump(data))
    if checkNumber(data.nowExp) > checkNumber(data.oldExp) then
        local ResourceModule = CS.Engine.Modules.ResourceModule
        local UIModule = CS.Engine.UI.UIModule
        local loader = ResourceModule.LoadBundleSync("Prefabs/Common/CommonExperienceUpgradeTips.prefab", nil, true)
        if loader.IsSuccess then
            local parent = UIModule.RootCanvas.transform
            local go = loader:Instantiate(parent.transform, false)
            loader:Release()
            if not isNull(go) and not isNull(parent) then
                local env = CfUtils.GetLuaScr(go, "Game.UI.Common.CommonExperienceUpgradeTips")
                env:FreshBaseUI(data)
            end
        else
            loader:Release(true)
        end
    end

end
-- AF
function PlayerComponent:AFUploadLevel(oneLevel)
    local uploadLevels = { 1, 5, 10 ,22, 30 , 42 , 45 , 60 ,75}
    oneLevel = checkInt(oneLevel)
    for i, level in pairs(uploadLevels) do
        if checkInt(level) == oneLevel then
            xRecord.af_internal(string.format("level_%s", oneLevel), { playerId = tostring(self.playerDojo.playerId) })
            break
        end
    end
end
---UpdateMainExp
---更新主角经验
---@param lv number 主角等级
---@param exp number 主角经验
---@param hp number 主角体力
---@param isShowTip boolean nil 默认为true
function PlayerComponent:UpdatePlayerLvMainExp(lv, exp, hp, isShowTip)
    ---处理升级事件的逻辑,是否提示已升级等
    local oldLevel = checkInt(self.playerDojo.level)
    local newLevel = checkInt(lv)
    self.expBefore = DeepCopy(self.playerDojo.mainExp)
    self.playerDojo.mainExp = checkInt(exp)
    isShowTip = isNull(isShowTip) or isShowTip
    if isShowTip then
        self:ShowExpChangeTips({
            oldLevel = oldLevel,
            nowLevel = newLevel,
            oldExp = checkNumber(self.expBefore),
            nowExp = self.playerDojo.mainExp
        })
    end
    hp = tonumber(hp)
    if (not isNull(hp)) and hp >= 0 then
        self.playerDojo.hp = checkNumber(hp)
        AppService:GetInstance():UpdateRecoveryValue(self.playerDojo.hp)
    end
    if oldLevel >= 0 and (newLevel > oldLevel) then
        self.playerDojo.level = newLevel
        ---@type WhiteLevelGiftComponent
        local whiteLevelGiftComponent = GameUtils.GetEntityCompByType(ECSComponentType.Constants.WhiteLevelGiftComponent)
        if whiteLevelGiftComponent then
            whiteLevelGiftComponent:SetPlayerLevel(newLevel)
        end
        self:AFUploadLevel(newLevel)
        xRecord.setUserPlayer({ playerLevel = tostring(newLevel) })
        --- 玩家升级打点记录
        ---
        ---已升级
        local expInfo = CardConfMgr:GetInstance():GetPlayerExpByLevelId(newLevel, oldLevel)
        self.playerDojo.hpLimit = checkInt(expInfo.hpMax) + checkNumber(GameUtils.GetPrivilegeCardAddNumByRefId(1, "ApMax"))
        if #expInfo.rewards > 0 then
            local rewards = {}
            for _, reward in pairs(expInfo.rewards) do
                if checkNumber(reward.goodsId) ~= Constants.Currency.HpId then
                    table.insert(rewards, reward)
                end
            end
            if #rewards > 0 then
                ---新的逻辑，服务器只返回最新的hp值，如果奖励中配这个值也不再添加
                GoodsUtils.DrawRewards(rewards)
            end
        end
        ----体力上限值的恢复值也要修改下
        AppService:GetInstance():UpdateRecoveryValueMax(self.playerDojo.hpLimit)
        ---插入升级弹窗数据
        self:InsertUpgradeDialogData(oldLevel, newLevel)
        ---修正卡牌等级
        ---@type CardComponent
        local cardComp = GameUtils.GetEntityCompByType(ECSComponentType.Constants.CardComponent)
        cardComp:FixCardLevel(oldLevel, newLevel)

        x_record_event(string.format('LEVEL_UP_%d', checkInt(newLevel)))
        --玩家升级
        local SDKService = import('Game.Entry.SDKService')
        SDKService:UpgradedRole()
        return true
    end
    return false
end

--获取更新主角经验之前的主角经验
function PlayerComponent:GetExpBefore()
    if isNull(self.expBefore) then
        --没用设置的话就返回当前的
        return self.playerDojo.mainExp
    end
    return self.expBefore
end

---GetGoodNo
---获取物品数量, 此处只用来内部获只给 GoodsUtils.GetThingNo 调用的
---@param goodsId number
function PlayerComponent:GetGoodNo(goodsId)
    goodsId = checkNumber(goodsId)
    if goodsId == Constants.Currency.GoldId then
        return checkNumber(self.playerDojo.gold)
    elseif goodsId == Constants.Currency.PayDiamondId then
        return checkNumber(self.playerDojo.diamond)
    elseif goodsId == Constants.Currency.FreeDiamondId then
        return checkNumber(self.playerDojo.freeDiamond)
    elseif goodsId == Constants.Currency.HpId then
        return checkNumber(self.playerDojo.hp)
    elseif goodsId == Constants.Currency.LadderTicket then
        return checkNumber(self.playerDojo.ladderTicketNums)
    elseif goodsId == Constants.Currency.LadderCoin then
        return checkNumber(self.playerDojo.ladderCoin)
    elseif goodsId == Constants.Currency.WorldBossCoin then
        return checkNumber(self.playerDojo.worldBossCoin)
    elseif goodsId == Constants.Currency.LadderStruggleCurrency then
        return checkNumber(self.playerDojo.asyncCoin)
    elseif goodsId == Constants.Currency.LadderStruggleTicket then
        return checkNumber(self.playerDojo.asyncRecoverTicket)
    elseif goodsId == Constants.Currency.LadderStruggleSingleCurrency then
        return checkNumber(self.playerDojo.asyncCoin)
    elseif goodsId == Constants.Currency.LadderStruggleSingleTicket then
        return checkNumber(self.playerDojo.asyncSingleRecoverTicket)
    elseif goodsId == Constants.Currency.CartCatTicket then
        return checkNumber(self.playerDojo.catCarCoin)
    elseif goodsId == Constants.Currency.CumulativeScore then
        return checkNumber(self.playerDojo.payCumulative)
    elseif goodsId == Constants.Currency.TipCoin then
        return checkNumber(self.playerDojo.tipCoin)
    elseif goodsId == Constants.Currency.ClubCoin then
        return checkNumber(self.playerDojo.clubCoin)
    elseif goodsId == Constants.Currency.CatBallTicket then
        return checkNumber(self.playerDojo.catBallTicket)
    elseif goodsId == Constants.Currency.TowerTicket then
        return checkNumber(self.playerDojo.towerTicket)
    elseif goodsId == Constants.Currency.ClubFeedCatSkinCoin then
        return checkNumber(self.playerDojo.clubFeedCatSkinCoin)
    elseif goodsId == Constants.Currency.LightDarkCoin then
        return checkNumber(self.playerDojo.lightDarkCoin)
    elseif goodsId == Constants.Currency.BattleCardGameCoin then
        return checkNumber(self.playerDojo.stardustCoin)
    elseif goodsId == Constants.Currency.StoreSkinTicket then
        return checkNumber(self.playerDojo.skinTicket)
    else
        local num = 0
        if isSet(self.playerDojo.currency, tostring(goodsId)) then
            num = checkNumber(self.playerDojo.currency[tostring(goodsId)])
        end
        return num
    end
end

---更新头像头像框贴纸道具的信息
---@param rewards table @ 服务端返回的rewards其中的一项
function PlayerComponent:UpdateAvatarFramePasterGoods(reward)
    if type(reward) ~= 'table' then
        return
    end
    local headAvatarVo = PlayerInfoUtils.GetHeadAvatarVo(reward.goodsId)
    if headAvatarVo == nil then
        return
    end
    local type = headAvatarVo.kind--区分是头像头像框还是贴纸
    if isNull(self.playerDojo.playerOtherInfo[tostring(type)]) then
        self.playerDojo.playerOtherInfo[tostring(type)] = {}
    end
    if reward.convertGoods == nil or next(reward.convertGoods) == nil then
        self.playerDojo.playerOtherInfo[tostring(type)][tostring(reward.goodsId)] = reward
        PlayerInfoUtils.UpdateAvatarNewStateById(reward.goodsId, true)
    end
end

---更新CD信息
---@param rewards table 服务端返回的rewards其中的一项
function PlayerComponent:UpdateCDGoods(reward)
    if not self:GetPlayerDojo():CheckAlbumIsUnlocked(reward.goodsId) then
        -- 更新数据储存
        self.playerDojo.ownedAlbumDt[checkInt(reward.goodsId)] = 0
        PlayerInfoUtils.UpdateCDNewStateById(reward.goodsId, true)
    end
end

---@return PlayerDojo
function PlayerComponent:GetPlayerDojo()
    return self.playerDojo
end

---插入卡牌展示弹窗数据
---@param cardDisplayDialogInfo table[] 卡牌展示弹窗数据
function PlayerComponent:InsertCardDisplayDialogData(cardDisplayDialogInfo)
    local excludeIdMap = {
        [Constants.UITypeIds.GachaponEntry] = true,
        [Constants.UITypeIds.GachaponResultViewNew] = true,
        [Constants.UITypeIds.GachaponResultViewSpecial] = true,
    }

    if GameUtils.CheckIsShowDialogByIdMap(excludeIdMap) then
        return
    end

    if next(cardDisplayDialogInfo) then
        self.__rewardsDialogInfo[Constants.RewardDialogType.CardDisplay] = {
            id = Constants.UITypeIds.CommonCardDisplayDialog,
            parameters = {
                cardInfo = cardDisplayDialogInfo,
            }
        }
    end
end

---InsertUpgradeDialogData
---插入升级弹窗数据
---@param oldLevel number 旧等级
---@param newLevel number 新等级
function PlayerComponent:InsertUpgradeDialogData(oldLevel, newLevel)
    self.__rewardsDialogInfo[Constants.RewardDialogType.PlayerUpgrade] = {
        id = Constants.UITypeIds.UICultivatePlayerUpgradeDialog,
        parameters = {
            params = {
                oldLevel = oldLevel,
                newLevel = newLevel,
            },
            uiType = 1,
        }
    }
end

function PlayerComponent:GetRewardsDialogInfos()
    return self.__rewardsDialogInfo
end

---GetSignboardCardId
---获取到看板娘的资源id
function PlayerComponent:GetSignboardCardVo()
    ---@type CardComponent
    local cardComponent = GameUtils.GetEntityCompByType(ECSComponentType.Constants.CardComponent)
    local cardDojo = cardComponent:GetCardById(self.playerDojo.signboardId)
    ---@type CardVo
    local cardVo = CardConfMgr:GetInstance():GetCardBySkinRefId(cardDojo.cardSkin)
    return cardVo
end

---GetSignboardId
---获取到看板娘的id
function PlayerComponent:GetSignboardId()
    return self:GetPlayerDojo().signboardId
end

function PlayerComponent:GetSignboardCardDojo()
    local playerCardId = self:GetSignboardId()
    ---@type CardComponent
    local cardComponent = GameUtils.GetEntityCompByType(ECSComponentType.Constants.CardComponent)
    ---@type CardDojo
    local cardDojo = cardComponent:GetCardById(playerCardId)
    return cardDojo
end

---ShowRewardsSpecialDialog
---显示奖励指定弹窗
function PlayerComponent:ShowRewardsSpecialDialog(callBack, autoClose)
    self:StopRewardsSpecialDialogCo(true)
    if next(self.__rewardsDialogInfo) == nil then
        return
    end
    local blocker = CS.Engine.UI.UIRaycastBlocker.Instance
    blocker:AddCondition("ShowRewardsSpecialDialog")

    local cs_coroutine = require 'XLua.cs_coroutine'
    local CheckIsShowDialogByIdMap = GameUtils.CheckIsShowDialogByIdMap
    self.RewardDialogCo = cs_coroutine.start(function()
        blocker:RemoveCondition("ShowRewardsSpecialDialog")
        local values = table.values(Constants.RewardDialogType)
        table.sort(values)

        local yield_return = cs_coroutine.yield_return
        for i, dialogType in ipairs(values) do
            local dialogData = self.__rewardsDialogInfo[dialogType]

            if dialogData and next(dialogData) then
                if autoClose then
                    dialogData.parameters.autoClose = true
                end
                yield_return(UIModule.OpenDialog(dialogData))
                --- 如果该界面没关闭的话 则等待它关闭
                while CheckIsShowDialogByIdMap({ [dialogData.id] = true }) do
                    yield_return()
                end
            end
        end

        self:ShowFunctionUnlockDialog(Constants.CommonUnlockType.PassQuest)

        --- 清理缓存
        self.__rewardsDialogInfo = {}
        self.RewardDialogCo = nil
        if callBack then
            callBack()
        end
    end)

    return self.RewardDialogCo
end
function PlayerComponent:StopRewardsSpecialDialogCo(isDisableClear)
    if self.RewardDialogCo then
        local cs_coroutine = require 'XLua.cs_coroutine'
        cs_coroutine.stop(self.RewardDialogCo)
        self.RewardDialogCo = nil
        if not isDisableClear then
            self.__rewardsDialogInfo = {}
        end
    end
end

function PlayerComponent:ClearRewardsDialogInfoByType(type)
    self.__rewardsDialogInfo[type] = nil
end

function PlayerComponent:StopMainChapterExtraDialog()
    if self.mainChapterExtraDialogCo then
        local cs_coroutine = require 'XLua.cs_coroutine'
        cs_coroutine.stop(self.mainChapterExtraDialogCo)
        self.mainChapterExtraDialogCo = nil
    end
end

function PlayerComponent:ShowMainChapterExtraDialog(unlockType)
    self:StopMainChapterExtraDialog()
    if next(self.__functionUnlockDialogDataInfo) == nil or not self.isShowTeamRatingDialog then
        return
    end
    local blocker = CS.Engine.UI.UIRaycastBlocker.Instance
    blocker:AddCondition("ShowMainChapterExtraDialog")

    local UIModule = CS.Engine.UI.UIModule
    local Yielders = CS.Engine.Lib.Yielders
    local sce = 0.3
    local cs_coroutine = require 'XLua.cs_coroutine'
    local CheckIsShowDialogByIdMap = GameUtils.CheckIsShowDialogByIdMap
    self.mainChapterExtraDialogCo = cs_coroutine.start(function()
        cs_coroutine.yield_return(Yielders.GetWaitForSeconds(sce))
        blocker:RemoveCondition("ShowMainChapterExtraDialog")
        local co = self:ShowFunctionUnlockDialog(unlockType)
        if co then
            cs_coroutine.yield_return(co)
            --- 如果该界面没关闭的话 则等待它关闭
            while CheckIsShowDialogByIdMap({ [Constants.UITypeIds.UICultivatePlayerUpgradeDialog] = true }) do
                cs_coroutine.yield_return(Yielders.GetWaitForSeconds(sce))
            end
        end
        if self.isShowTeamRatingDialog then
            cs_coroutine.yield_return(UIModule.OpenDialog({ id = Constants.UITypeIds.UICultivateLevelUpFinishDialog, parameters = { levelUpType = Constants.UICultivateLevelUpFinishType.TeamRating } }))
        end
        self.isShowTeamRatingDialog = nil
        self.mainChapterExtraDialogCo = nil
    end)

    return self.mainChapterExtraDialogCo
end

function PlayerComponent:InsertFunctionUnlockDialogData(parameters)
    local unlockType = parameters.unlockType
    local systemToggleIds = SystemToggleMgr:GetInstance():GetSystemToggleIds(unlockType, parameters.refId)
    if systemToggleIds == nil then
        return
    end

    self.__functionUnlockDialogDataInfo[unlockType] = {
        id = Constants.UITypeIds.CommonFunctionUnlockDialog,
        parameters = {
            params = parameters,
        }
    }
end

function PlayerComponent:ShowFunctionUnlockDialog(unlockType)
    if unlockType == nil then
        return
    end
    local oneDialogDataInfo = self.__functionUnlockDialogDataInfo[unlockType]
    if oneDialogDataInfo == nil or next(oneDialogDataInfo) == nil then
        return
    end
    self.__functionUnlockDialogDataInfo[unlockType] = {}
    local UIModule = CS.Engine.UI.UIModule
    return UIModule.OpenDialog(oneDialogDataInfo)
end

function PlayerComponent:GetAvatarNewInfoMap()
    if not self.avatarNewStateMap then
        local data = CfUtils.GetLocalData("playerAvatarNewStateMap")
        if data == "0" then
            self.avatarNewStateMap = {}
        else
            self.avatarNewStateMap = table.deserialize(data)
        end
    end
    return self.avatarNewStateMap
end

function PlayerComponent:GetCDNewStateInfo()
    if not self.cdNewStateMap then
        local data = CfUtils.GetLocalData("playerCDNewStateMap")
        if data == "0" then
            self.cdNewStateMap = {}
        else
            self.cdNewStateMap = table.deserialize(data)
        end
    end
    return self.cdNewStateMap
end

function PlayerComponent:GetRandomMusic(isForce, paramId)
    isForce = checkBool(isForce)
    local selectedCdList = self.playerDojo:GetSelectedAlbumList()
    local musicId = 5400001
    local randomCDId = PlayerInfoUtils.GetDefaultMusicId()
    local isNeedRandom = false
    if checkNumber(self._musicId) == 0 then
        ---未随机过，进行一次随机结果
        isNeedRandom = true
    elseif os.time() - checkNumber(self.randomTime) >= 5 * 60 then
        self.randomTime = os.time()
        ---10分钟
        isNeedRandom = true
    end
    if isNeedRandom then
        if #selectedCdList > 0 then
            local randomIndex = math.random(1, #selectedCdList)
            randomCDId = selectedCdList[randomIndex]
            print('==>>', table.dump(selectedCdList, false, 2))
        end
        local musicVo = CfUtils.GetCfVo(AutoIds.IdSetting899, "MusicPlayerVo", randomCDId)
        if musicVo ~= nil then
            musicId = checkNumber(musicVo.id)
        else
            musicId = randomCDId
        end
        self.randomTime = os.time()
        self._musicId = musicId
    end
    if isForce and paramId then
        self._musicId = checkNumber(paramId)
        self.randomTime = os.time()
    end
    return self._musicId
end

---GetCurrentMusicId
---获取当前播放的音乐id
---@return number
function PlayerComponent:GetCurrentMusicId()
    return checkNumber(self._musicId)
end

function PlayerComponent:SetCurrentMusicId(id)
    self._musicId = checkNumber(id)
end

local ProgressKeyToId = {
    ["cafeMenuEmpty"] = 3001,
    ["cafeCatBall"] = 3013,
    ["cafeCatCar"] = 3004,
    ["climbTower"] = 2015,
}
---更新主界面解锁进度通知
---UpdateProgressInfo
---@param data table 服务器数据   只会发送需要更新的倒计时的key-value
function PlayerComponent:UpdateProgressInfo(data)
    if isNull(self.progressInfo) then
        self.progressInfo = {}
    end
    for i, v in pairs(data) do
        local id = ProgressKeyToId[i]
        if id then
            if checkNumber(v) > 0 then
                self.progressInfo[id] = checkNumber(v) + os.time()
            else
                self.progressInfo[id] = checkNumber(v)
            end
            if id == Constants.SystemToggleIds.Id2015 then
                self:UpdateTowerRewPoint(id)
            end
        end
    end
end

function PlayerComponent:UpdateTowerRewPoint(id)
    local redPointNum = -1
    local info = self.progressInfo[id]
    local isUnLock = GameUtils.IsUnlockedBySystemTogId(Constants.SystemToggleIds.Id2015)
    if isUnLock then
        local vo = CfUtils.GetCfVo(AutoIds.IdSetting6055, "CommonModuleTipsVo", id)
        local row = GoodsConfMgr:GetInstance():GetJumpModuleRow(vo.openType)
        local jumpID = checkInt(row:Get("ID"))
        ---@type OverseaTowerUtils
        local OverseaTowerUtils = import('Game.UI.FightReady.OverseaTower.OverseaTowerUtils')
        local isJumpUnLock = OverseaTowerUtils.IsFunctionUnlock(jumpID, true)
        if isJumpUnLock then
            if info <= 0 and (info - os.time()) <= 0 then
                redPointNum = 0
            else
                redPointNum = info - os.time()
            end
        end
    end
    GameUtils.UpdateServerRedPointData({unQuestTower = redPointNum})
end

function PlayerComponent:GetProgressInfoById(id)
    if self.progressInfo[id] then
        return self.progressInfo[id]
    end
    return nil
end

function PlayerComponent:UpdateProgressRewardInfo(data)
    local rewardData = {}
    for i, v in pairs(data) do
        local id = ProgressKeyToId[i]
        if id then
            rewardData[id] = v
        end
    end
    return rewardData
end
---只要有大于0的  说明是在进行中
function PlayerComponent:IsInProcess()
    for i, v in pairs(self.progressInfo) do
        if v > 0 and (v - os.time()) > 0 then
            return true
        end
    end
    return false
end
---只要有一个小于等于0  都有红点
function PlayerComponent:IsHaveRedPoint()
    for i, v in pairs(self.progressInfo) do
        local isUnLock = GameUtils.IsUnlockedBySystemTogId(i)
        if isUnLock then
            if i == Constants.SystemToggleIds.Id2015 then
                local vo = CfUtils.GetCfVo(AutoIds.IdSetting6055, "CommonModuleTipsVo", i)
                local row = GoodsConfMgr:GetInstance():GetJumpModuleRow(vo.openType)
                local isJumpUnLock = GoodsConfMgr:GetInstance():CheckIsCanJump(row, false)
                if isJumpUnLock then
                    if v <= 0 and (v - os.time()) <= 0 then
                        return true
                    end
                end
            else
                if v <= 0 and (v - os.time()) <= 0 then
                    return true
                end
            end
        end
    end
    return false
end

function PlayerComponent:IsPrivilegeCard()
    return GameUtils.IsHavePrivilegeCard(1)
end
-- 常驻付费签到是否解锁
function PlayerComponent:IsOpenPaidCheckin()
    if type(self:GetPlayerDojo().paidCheckin) == "table" then
        local paidCheckin = self:GetPlayerDojo().paidCheckin
        if table.count(paidCheckin) > 0 then
            if paidCheckin.checkinTime < os.time() then
                return false
            end
            return true
        end
    end
    return false
end

function PlayerComponent:RegGlobalTalentPrivilegeCard()
    ---@type PlayerDojo
    local playerDojo =  self:GetPlayerDojo()
    playerDojo:RegGlobalTalentPrivilegeCard()
   
end

---IsOpenOnlineRewards
---是否开启在线奖励
function PlayerComponent:IsOpenOnlineRewards()
    ---@type PlayerDojo
    local playerDojo  = self:GetPlayerDojo()
    local checkNumber = checkNumber
    local unlockStatus = checkNumber(playerDojo.onlineTaskInfo.unlockStatus)
    if unlockStatus == 0 then
        return false
    end
    local taskList = checkTable(playerDojo.onlineTaskInfo.taskList)
    local allDraw  = true
    local count    = 0
    for i, v in pairs(taskList) do
        if (checkNumber(v.type) == 1 and checkNumber(v.status) ~= 2) or (checkNumber(v.type) == 2 and checkNumber(v.status) <= 1) then
            ---未领取存在的情况下
            allDraw = false
        end
        count = 1
    end
    return unlockStatus == 1 and count > 0 and (not allDraw)
end

function PlayerComponent:IsOpenPlayerEntryWelfare()
    local isOpen = false 
    local playerDojo =  self:GetPlayerDojo()
    if isSet(playerDojo.entryWelfareInfo, "status") then
        local status = checkNumber(playerDojo.entryWelfareInfo.status)
        if status == 1 then
            isOpen = true
        end     
    end 
    return isOpen 
end

function PlayerComponent:IsPopPlayerEntryWelfare()
    local isOpen = false 
    local playerDojo =  self:GetPlayerDojo()
    if isSet(playerDojo.entryWelfareInfo, "status") then
        local status = checkNumber(playerDojo.entryWelfareInfo.status)
        if status == 1 then
            local totalDrawNum = checkInt(playerDojo.entryWelfareInfo.totalDrawNum ) 
            local rewards = playerDojo.entryWelfareInfo.rewards or {}
            local count = #rewards
            if count > 0 and totalDrawNum == count then
                return false
            end
            return true
        end     
    end 
    return isOpen 
end
--- 更新推送状态数据
---@param pushSettings any
function PlayerComponent:UpdatePushSetting(pushSettings)
    -- 旧状态
    local oldBtnStateList = {}
    local json = GameUtils.LoadString("SettingPushBtnStateList")
    if not string.isEmpty(json) then
        oldBtnStateList = table.deserialize(json)
    end

    -- 保存服务器下发的新状态
    local settings = pushSettings
    local json = table.serialize(settings)
    GameUtils.SaveString("SettingPushBtnStateList", json)
    -- print("[推送] 服务器下发推送状态", json)

    -- 新状态
    local newBtnStateList = {}
    if not string.isEmpty(json) then
        newBtnStateList = table.deserialize(json)
    end

    -- 推送总开关是否变化
    local mainId = "main"
    ---@type SDKService
    local SDKService = import('Game.Entry.SDKService')
    local sdkService = SDKService:GetInstance()
    ---@type TpnsSdk
    local TpnsSdk =  sdkService:GetThirdSDK("TpnsSdk")
    if isNotNull(TpnsSdk) then
        if newBtnStateList[mainId] == 0 then
            print("[推送] 更新推送SDK状态 close")
            TpnsSdk:CloseNotice()
        end
    end
end

--- 玩家头像、头像框、徽章，倒计时事件
function PlayerComponent:OnPlayerHeadTimerUpdateHandler_(count, id, elapsed)
    for kind, headDataMap in pairs(self.playerDojo.playerOtherInfo) do
        for headId, headData in pairs(headDataMap) do
            -- 是否有期限的
            if checkInt(headData.expirationTime) > 0 then
                -- 更新剩余秒数
                headData.leftSeconds = headData.expirationTime - GameUtils.GetServerTime()
                -- 处理到期的
                if headData.leftSeconds <= 0 then
                    -- 删除身上的数据
                    headDataMap[headId] = nil
                    -- 如果是正在使用中的头像、头像框，则恢复默认
                    local goodsId  = checkInt(headId)
                    local headKind = checkInt(kind)
                    local nowPhoto = self.playerDojo.playerAvatar
                    local nowFrame = self.playerDojo.playerAvatarFrame
                    if headKind == Constants.PlayerAvatarItemType.Avatar then
                        if checkInt(self.playerDojo.playerAvatar) == goodsId then
                            -- 还原初始头像
                            self.playerDojo.playerAvatar = PlayerInfoUtils.GetDefaultAvatarId(self.playerDojo.gender)
                            GameUtils.Request(Interfaces.Player2DSetAvatarAndFrame, {avatar = self.playerDojo.playerAvatar, avatarFrame = nowFrame}, function(request, response)
                            end)
                        end
                    elseif headKind == Constants.PlayerAvatarItemType.AvatarFrame then
                        if checkInt(self.playerDojo.playerAvatarFrame) == goodsId then
                            -- 还原初始头像框
                            self.playerDojo.playerAvatarFrame = PlayerInfoUtils.GetDefaultAvatarFrameId()
                            GameUtils.Request(Interfaces.Player2DSetAvatarAndFrame, {avatar = nowPhoto, avatarFrame = self.playerDojo.playerAvatarFrame}, function(request, response)
                            end)
                        end
                    elseif headKind == Constants.PlayerAvatarItemType.Paster then
                        -- 删掉徽章
                        self.playerDojo.medals[tostring(goodsId)] = nil
                    end
                    Events.Broadcast(Constants.EventNames.PlayerHeadDateExpired, {goodsId = goodsId, headKind = headKind})
                end
            end
        end
    end
    if Events.HasListener(Constants.EventNames.PlayerHeadLeftTimeCountdown) then
        Events.Broadcast(Constants.EventNames.PlayerHeadLeftTimeCountdown)
    end
    xTry(function()
        ---在线奖励倒计时的逻辑
        local unlockStatus = checkNumber(self.playerDojo.onlineTaskInfo.unlockStatus)
        local taskList = checkTable(self.playerDojo.onlineTaskInfo.taskList)
        if unlockStatus == 1 and #taskList > 0 then
            for i, v in pairs(taskList) do
                v.progress = checkNumber(v.progress) + elapsed
            end
        end
    end)
end


return PlayerComponent
