local config = {
  str_n25_idol_y_start_new_game = "เส้นทางของผู้ผลิต",
  str_n25_idol_y_load_archiving = "รีวิวเวที",
  str_n25_idol_y_collection = "รางวัล",
  str_n25_idol_y_intro_title = "ข้อมูลการเล่นเกมกิจกรรมไอดอล",
  str_n25_idol_y_break_title = "ดำเนินการต่อกับการเดินทางครั้งก่อนของคุณหรือไม่",
  str_n25_idol_y_break_new_game = "เริ่มเกมใหม่",
  str_n25_idol_y_break_continue_game = "ไปต่อ",
  str_n25_idol_y_break_new_game_second_confirm = "เริ่มเกมใหม่?",
  str_n25_idol_y_break2_title = "การโหลดจากไฟล์บันทึกจะลบข้อมูลการเดินทางปัจจุบันของคุณ",
  str_n25_idol_y_break2_cancel = "ยกเลิก",
  str_n25_idol_y_break2_load_archiving = "โหลดไฟล์บันทึก",
  str_n25_idol_y_loading_title = "รีสตาร์ทสเตจ",
  str_n25_idol_y_loading_loadbtn = "โหลด",
  str_n25_idol_y_loading_week = "สัปดาห์ {1} ของการฝึกอบรม",
  str_n25_idol_y_loading_emptyen = "ว่างเปล่า",
  str_n25_idol_y_loading_empty = "ไม่มีบันทึกไฟล์",
  str_n25_idol_y_loading_fans = "แฟน ๆ",
  str_n25_idol_y_sumup_title1 = "ยังจำโรงฝึกนี้ได้ไหม?",
  str_n25_idol_y_sumup_title2 = "ยังจำการทำงานหนักทั้งหมดของคุณได้หรือไม่?",
  str_n25_idol_y_sumup_skip = "ข้าม >>",
  str_n25_idol_y_sumup_train1 = "นี่คือที่\nคุณเริ่มเป็นโปรดิวเซอร์\nและช่วยในการฝึกฝนของโกลดี้\nคุณดูแลการฝึกอบรมของเธอ\nและการเปิดตัวที่ประสบความสำเร็จของเธอ\nตลอดไปจนจบการศึกษา\nนอกจากนี้,\nคุณรู้จักชาวออโรเรียนหลายคน\nในช่วงเวลาที่คุณอยู่ที่นี่\nและได้พบกับพวกเขา <color=#6d50c3><size=43>{1}</size></color> ครั้ง.",
  str_n25_idol_y_sumup_train2 = "ด้วยความช่วยเหลือของคุณ\nโกลดี้สามารถเอาชนะได้\nผลรวมของ <color=#6d50c3><size=43>{1}</size></color> แฟน ๆ !\nตอนนี้เธอเป็นไอดอลที่มีชื่อเสียงใน Astra!\nเธอเก่ง <color=#6d50c3><size=43>{2}</size></color>,\nและ <color=#6d50c3><size=30>{3}</size></color>.\nผู้ผลิตที่มีความสามารถ\nช่วยให้ไอดอลของพวกเขาเปล่งประกาย",
  str_n25_idol_y_sumup_out_music = "การร้องเพลงที่ไพเราะจับหัวใจของแฟน ๆ ทุกคน",
  str_n25_idol_y_sumup_out_dance = "การเต้นที่สปิริตที่กระตุ้นแฟน ๆ นับไม่ถ้วน",
  str_n25_idol_y_sumup_out_perform = "ไม่มีความท้าทายใดยากเกินกว่าที่เธอจะเอาชนะได้\nซึ่งทำให้แฟนๆ เรียกเธอว่าราชินีแห่งไอดอล",
  str_n25_idol_y_cg_fans = "แฟนทั้งหมด",
  str_n25_idol_y_coll_achiev = "ความสำเร็จ",
  str_n25_idol_y_coll_ending = "สิ้นสุด\nบรรลุ",
  str_n25_idol_y_coll_memory = "สิ่งที่ต้องทำ",
  str_n25_idol_y_coll_receive = "รับ",
  str_n25_idol_y_coll_received = "รับแล้ว",
  str_n25_idol_y_coll_locked = "ล็อกอยู่",
  str_n25_idol_y_coll_unlock_ending = "ปลดล็อกตอนจบเพื่อดู",
  str_n25_idol_y_coll_unlock_event = "รายการสิ่งที่ต้องทำยังไม่เสร็จ",
  str_n25_idol_y_coll_unlock_achiev = "ยังไม่ได้ปลดล็อค",
  str_n25_idol_y_coll_unlock_ending_title = "???",
  str_n25_idol_y_coll_unlock_ending_desc = "ปลดล็อกตอนจบเพื่อดู",
  str_n25_idol_y_music = "เสียงร้อง",
  str_n25_idol_y_dance = "เต้น",
  str_n25_idol_y_perform = "ผลงาน",
  str_n25_idol_y_login_i = "ข้อมูลอีเวนต์",
  str_n25_idol_y_end_duration = "กิจกรรมสิ้นสุดใน {1} ง {2} ชม.",
  str_n25_idol_y_end_desc_title = "ความทรงจำบนเวที",
  str_n25_idol_y_end_full_view = "ดูรายละเอียด",
  str_n25_idol_y_end_title_a = "เพื่อนที่ไว้ใจได้",
  str_n25_idol_y_end_title_b = "วิคเปิดตัว!",
  str_n25_idol_y_end_title_n = "ผู้ผลิตฝึกงาน",
  str_n25_idol_y_end_desc_a = "เพื่อช่วยให้คุณเป็นผู้ผลิตที่ดีที่สุดเท่าที่คุณจะทำได้\nVice และ Carleen เสียสละเวลาและความพยายามอย่างมาก\nโดยปกติแล้ว จบการศึกษาจากเวิร์กชอปหลักสูตร Crash Course ของผู้ผลิต\nสมควรได้รับการเฉลิมฉลองสุดพิเศษ!",
  str_n25_idol_y_end_desc_b = "สิ่งที่เขาต้องการทำคือการนอนหลับ เล่นกับสัตว์มหัศจรรย์ของเขา\nและใช้ชีวิตอย่างอิสระและงดงาม...\nแต่ทุกคนต้องการ Nightium หากต้องการอยู่รอดใน Astra และ Vic ก็ไม่มีข้อยกเว้น!\nเพื่ออำนวยความสุขความสบายแก่สรรพสัตว์ทั้งปวง\nวิคไม่มีทางเลือกอื่นนอกจากการเป็น...ไอดอลระดับโลก!",
  str_n25_idol_y_end_desc_n = "หลังจากทำงานหนักมาหลายสัปดาห์และวันอันยาวนาน\nคุณและโกลดีจัดคอนเสิร์ตทั้งสามของเธอได้สำเร็จ!\nในขณะที่ได้รับเสียงปรบมือกึกก้องจากแฟนๆ ที่น่ารักของเธอ\nGoldie เชิญคุณขึ้นเวทีเพื่อร่วมเฉลิมฉลอง\nทำได้ดีมากสำหรับโปรดิวเซอร์รายใหม่ล่าสุดของ Astra!",
  str_n25_idol_y_login_intro_title = "ข้อมูลการเล่นเกม - Starlit Agency",
  str_n25_idol_y_login_intro_head_1 = "เส้นทางของผู้ผลิต",
  str_n25_idol_y_login_intro_head_2 = "รีวิวเวที",
  str_n25_idol_y_login_intro_head_3 = "รางวัล",
  str_n25_idol_y_login_intro_body_1 = "แตะเส้นทางของผู้ผลิตเพื่อเริ่มต้นเส้นทางการฝึกอบรมของโกลดี้กับเธอ!\nช่วยเธอฝึกจนเสร็จ จัดอีเวนต์ไอดอลต่างๆ และสร้างแฟนคลับให้ได้มากที่สุด! ช่วยเธอค้นหาสุดยอดไอดอลบนเวทีคอนเสิร์ต!",
  str_n25_idol_y_login_intro_body_2 = "ใน Stage Review คุณสามารถดูฟังก์ชันบันทึกอัตโนมัติของเกมและเล่นต่อได้",
  str_n25_idol_y_login_intro_body_3 = "ใน Accolades คุณสามารถดูรางวัลพิเศษและตอนจบที่ปลดล็อกได้ รวมถึงงาน To-Do List ที่ทำเสร็จแล้ว\nรับรางวัลรายการโดยปลดล็อกความสำเร็จต่างๆ",
  str_n25_idol_y_act_next_week = "สิ้นสุดกิจกรรม",
  str_n25_idol_y_act_goto = "เป็นเจ้าภาพจัดงาน",
  str_n25_idol_y_act_not = "ทักษะไม่เพียงพอ",
  str_n25_idol_y_act_finish = "เป็นเจ้าภาพ",
  str_n25_idol_y_act_pre_add_fans = "จำนวนแฟน ๆ ที่คาดการณ์ไว้",
  str_n25_idol_y_act_title1 = "กิจกรรมไอดอลประจำสัปดาห์นี้",
  str_n25_idol_y_act_title2 = "Starlit Agency: อีเวนต์ไอดอลที่แนะนำ",
  str_n25_idol_y_act_title3 = "มีอีเวนต์ไอดอลรอดำเนินการในสัปดาห์นี้! ลองดูสิ!",
  str_n25_idol_y_act_result_title = "งานไอดอล",
  str_n25_idol_y_act_result_succ = "ความสำเร็จของกิจกรรม",
  str_n25_idol_y_act_result_fans = "แฟน ๆ เพิ่มขึ้น",
  str_n25_idol_y_concert_type1 = "คอนเสิร์ตเปิดตัว",
  str_n25_idol_y_concert_type2 = "คอนเสิร์ตประเมิน",
  str_n25_idol_y_concert_type3 = "คอนเสิร์ตรับปริญญา",
  str_n25_idol_y_concert_goto = "ไปคอนเสิร์ต",
  str_n25_idol_y_concert_target_fans = "จำนวนแฟนเป้าหมาย",
  str_n25_idol_y_concert_week_1 = "สัปดาห์ที่ 1",
  str_n25_idol_y_concert_week_2 = "สัปดาห์ที่ 2",
  str_n25_idol_y_concert_week_3 = "สัปดาห์ที่ 3",
  str_n25_idol_y_concert_week_4 = "สัปดาห์ที่ 4",
  str_n25_idol_y_concert_week_5 = "สัปดาห์ที่ 5",
  str_n25_idol_y_concert_week_6 = "สัปดาห์ที่ 6",
  str_n25_idol_y_concert_Monday = "วันจันทร์",
  str_n25_idol_y_concert_Tuesday = "วันอังคาร",
  str_n25_idol_y_concert_Wednesday = "วันพุธ",
  str_n25_idol_y_concert_Thursday = "วันพฤหัสบดี",
  str_n25_idol_y_concert_Friday = "วันศุกร์",
  str_n25_idol_y_concert_Saturday = "วันเสาร์",
  str_n25_idol_y_concert_Sunday = "วันอาทิตย์",
  str_n25_idol_y_concert_less_time_title = "เวลาจนถึงคอนเสิร์ต",
  str_n25_idol_y_concert_less_time_title2 = "คงเหลือ",
  str_n25_idol_y_concert_less_time = "วัน",
  str_n25_idol_y_ap_event_main_title = "สิ่งที่ต้องทำ",
  str_n25_idol_y_concert_succ_title = "ความสำเร็จของคอนเสิร์ต!",
  str_n25_idol_y_concert_fail_title = "คอนเสิร์ตล้มเหลว!",
  str_n25_idol_y_act_not_toast = "ทักษะไอดอลไม่เพียงพอที่จะจัดงานนี้",
  str_n25_idol_y_concert_succ_desc_0 = "ขอบคุณทุกการทำงานอย่างหนักของคุณ\nคอนเสิร์ตประสบความสำเร็จ\nแฟนบอลแน่นสนาม!",
  str_n25_idol_y_concert_succ_desc_1 = "ขอบคุณความช่วยเหลือของเนวิเกเตอร์\nคอนเสิร์ตเปิดตัวของ Goldie ไม่มีปัญหา!\nNavigator เริ่มดูเหมือนผู้ผลิตตัวจริงแล้ว!",
  str_n25_idol_y_concert_succ_desc_2 = "Goldie สามารถผ่านการประเมินคอนเสิร์ต\nและได้รับการสนับสนุนจากแฟน ๆ นับไม่ถ้วนในกระบวนการนี้\nเธอเริ่มสร้างชื่อให้ตัวเองใน Astra แล้วจริงๆ!",
  str_n25_idol_y_concert_succ_desc_3 = "คอนเสิร์ตรับปริญญาประสบความสำเร็จอย่างมาก\nทุกที่นั่งเต็มไปด้วยเสียงคำรามของแฟนๆ!\nทุกที่ที่คุณหันไป แฟนๆ ของเธอตะโกนคำขวัญที่พวกเขาชื่นชอบ: \"ไม่ว่าโกลดี้ไปที่ไหน โกลดิล็อกส์จะตามไป!\"",
  str_n25_idol_y_concert_fail_desc_0 = "เนื่องจากมีพัดลมไม่เพียงพอต่อความต้องการ\nคอนเสิร์ตนี้ถูกยกเลิก...",
  str_n25_idol_y_concert_fail_desc_1 = "Navigator ไม่สามารถช่วย Goldie จัดคอนเสิร์ตเปิดตัวที่ประสบความสำเร็จได้\nดูเหมือนว่าคุณยังมีหนทางในการเป็นโปรดิวเซอร์...\nแต่ไม่ต้องกังวล! มีครั้งต่อไปเสมอ!",
  str_n25_idol_y_concert_fail_desc_2 = "คุณไม่สามารถช่วยให้ Goldie ผ่านการประเมินคอนเสิร์ต...\nฝึกฝนให้หนัก แล้วทำให้ดีขึ้นในครั้งหน้า!\nมีแฟน ๆ เพียงพออยู่เคียงข้างคุณ คุณจะประสบความสำเร็จในเวลาอันสั้น!",
  str_n25_idol_y_achievement_name_1 = "เพื่อนที่ไว้ใจได้",
  str_n25_idol_y_achievement_name_2 = "วิคเปิดตัว!",
  str_n25_idol_y_achievement_name_3 = "ผู้ผลิตฝึกงาน",
  str_n25_idol_y_achievement_name_4 = "ทุกนาที ทุกวินาที",
  str_n25_idol_y_achievement_name_5 = "คู่ต่อสู้ที่เป็นมิตร",
  str_n25_idol_y_achievement_name_6 = "ผู้ผลิตที่ดีที่สุด",
  str_n25_idol_y_achievement_name_7 = "รายการพราว",
  str_n25_idol_y_achievement_name_8 = "โปรดปรานโดยโชคชะตา",
  str_n25_idol_y_achievement_name_9 = "ช่วงเวลาที่ดวงดาวส่องสว่างที่สุด",
  str_n25_idol_y_achievement_script_1 = "พวกเขาจะสนับสนุนคุณเสมอ!",
  str_n25_idol_y_achievement_script_2 = "บางทีเขาควรจะเป็นไอดอล?",
  str_n25_idol_y_achievement_script_3 = "โปรดิวเซอร์ ฉันไว้ใจคุณ!",
  str_n25_idol_y_achievement_script_4 = "แค่พูดออกมา ฉันจะช่วยเท่าที่ทำได้!",
  str_n25_idol_y_achievement_script_5 = "เหนื่อยจัง...อยากนอนแล้ว...",
  str_n25_idol_y_achievement_script_6 = "คุณและฉันสร้างทีมที่สมบูรณ์แบบ!",
  str_n25_idol_y_achievement_script_7 = "คอนเสิร์ตเปิดตัว? ไม่มีปัญหา!",
  str_n25_idol_y_achievement_script_8 = "การพิจารณาคดี? นำมาเลย!",
  str_n25_idol_y_achievement_script_9 = "การสำเร็จการศึกษา? ฟังดูเหมือนเป็นการเริ่มต้นใหม่สำหรับฉัน!",
  str_n25_idol_y_achievement_con_1 = "ปลดล็อกตอนจบ: เพื่อนที่ไว้ใจได้",
  str_n25_idol_y_achievement_con_2 = "ปลดล็อกตอนจบ: เปิดตัววิก!",
  str_n25_idol_y_achievement_con_3 = "ปลดล็อกตอนจบ: The Intern Producer",
  str_n25_idol_y_achievement_con_4 = "ทำงานใด ๆ จากรายการสิ่งที่ต้องทำของ Vice ให้สำเร็จ",
  str_n25_idol_y_achievement_con_5 = "ทำงานใดๆ จากรายการสิ่งที่ต้องทำของ Vic ให้สำเร็จ",
  str_n25_idol_y_achievement_con_6 = "ทำงานใดๆ จากรายการสิ่งที่ต้องทำของโกลดี้ให้สำเร็จ",
  str_n25_idol_y_achievement_con_7 = "จัดคอนเสิร์ตเปิดตัวที่ประสบความสำเร็จ",
  str_n25_idol_y_achievement_con_8 = "ผ่านการประเมินคอนเสิร์ต",
  str_n25_idol_y_achievement_con_9 = "จัดคอนเสิร์ตจบการศึกษาที่ประสบความสำเร็จ",
  str_n25_idol_y_arrange_title_1 = "เวิร์กช็อปหลักสูตรความผิดพลาดของผู้ผลิต",
  str_n25_idol_y_arrange_title_2 = "เวลาน้ำชายามบ่าย",
  str_n25_idol_y_arrange_title_3 = "โปรดิวเซอร์? ไม่ใช่ คาเลสไทต์!",
  str_n25_idol_y_arrange_title_4 = "การป้องกันปาปารัซซี่",
  str_n25_idol_y_arrange_title_5 = "ไอดอลในการวิ่ง",
  str_n25_idol_y_arrange_title_6 = "สลับเทรนเนอร์!",
  str_n25_idol_y_arrange_title_7 = "ไม่โดดเดี่ยวอีกต่อไป",
  str_n25_idol_y_arrange_title_8 = "การพักผ่อนคือกุญแจสำคัญ",
  str_n25_idol_y_arrange_title_9 = "อนาคตที่มีความหวัง",
  str_n25_idol_y_arrange_title_10 = "เหงาสุดติ่ง!",
  str_n25_idol_y_arrange_title_11 = "ประธานสภานักเรียนเยี่ยมชม",
  str_n25_idol_y_arrange_title_12 = "ความลับของการเต้นรำคางุระ",
  str_n25_idol_y_arrange_title_13 = "การมาถึงของเลดี้",
  str_n25_idol_y_arrange_title_14 = "จ้องกล้อง!",
  str_n25_idol_y_arrange_title_15 = "ยินดีต้อนรับการต่อสู้",
  str_n25_idol_y_lesson_1 = "เทคนิคการร้องเพลงประสานเสียง",
  str_n25_idol_y_lesson_2 = "คู่มือการร้องเพลงของ Rediesel Rocker",
  str_n25_idol_y_lesson_3 = "การฝึกอบรมพิเศษ: ศิลปะพื้นบ้าน Courier",
  str_n25_idol_y_lesson_4 = "ศิลปะบัลเลต์ ชั้นประถมศึกษาปีที่ 10",
  str_n25_idol_y_lesson_5 = "การฝึกพิเศษ: ศิลปะการต่อสู้",
  str_n25_idol_y_lesson_6 = "Illumina Broadcast No. 6: การเพาะกาย",
  str_n25_idol_y_lesson_7 = "ประติมากรรมน้ำแข็งและสถาปัตยกรรมปราสาท",
  str_n25_idol_y_lesson_8 = "การฝึกอบรมตนเองสำหรับอัจฉริยะ",
  str_n25_idol_y_lesson_9 = "ครัวแปลกประหลาดของ Roy",
  str_n25_idol_y_lesson_1_desc = "แสดง \"300 ข้อของคืนสีขาว\" แสงจันทราส่องหน้าเมือง...เป็นไฉน?",
  str_n25_idol_y_lesson_2_desc = "รับบท \"เจ้าหญิงอันดับ 1 แห่ง Rediesel\" ซินซาซาบซึ้งกับการแสดงจนร้องไห้...",
  str_n25_idol_y_lesson_3_desc = "แสดงเพลง \"The Courier's Song\" ฉันพนันได้เลยว่าการร้องเพลงนี้จะทำให้การคลอดของพวกเขาเร็วขึ้นมาก!",
  str_n25_idol_y_lesson_4_desc = "แสดงการเต้นบัลเลต์ เต้นด้วยนิ้วเท้าทำให้ฉันดูสูงขึ้นมาก!",
  str_n25_idol_y_lesson_5_desc = "ทำการสาธิตการยิง... แต่นั่นเกี่ยวข้องกับการเต้นจริง ๆ เหรอ?",
  str_n25_idol_y_lesson_6_desc = "ดำเนินการ Illumina Broadcast Calisthenics No. 6 ซึ่งเป็นกิจวัตรการออกกำลังกาย หนึ่งสองสามสี่! ยืดตัวลงต่ำแล้วแตะปลายเท้า!",
  str_n25_idol_y_lesson_7_desc = "สร้างประติมากรรมน้ำแข็งเป็นรูปปราสาท หิมะด้านบนทำจากน้ำตาลไอซิ่ง ดังนั้นมันจึงเริ่มละลายทันที!",
  str_n25_idol_y_lesson_8_desc = "เรียนรู้เทคนิคการแสดงต่างๆ มากมายจาก Charon เขาว่าอัจฉริยะทุกคนเหงา!",
  str_n25_idol_y_lesson_9_desc = "ทำขนมอร่อยๆ มากมายตั้งแต่เริ่มต้น... แต่ Zeta กินส่วนใหญ่ในขณะที่เราไม่ได้มองหา!",
  str_n25_idol_y_lesson_2_learn = "ต้นแบบ \"เจ้าหญิงอันดับ 1 แห่ง Rediesel\"",
  str_n25_idol_y_lesson_3_learn = "มาสเตอร์ \"The Courier's Song\"",
  str_n25_idol_y_lesson_5_learn = "ศิลปะการต่อสู้ที่เชี่ยวชาญ",
  str_n25_idol_y_lesson_6_learn = "Mastered Illumina Broadcast Calisthenics หมายเลข 6",
  str_n25_idol_y_lesson_8_learn = "เชี่ยวชาญการแสดง 108 ทักษะ",
  str_n25_idol_y_lesson_9_learn = "ฝึกฝนเทคนิคการทำอาหารของ Roy",
  str_n25_idol_y_activity_title_1 = "ปล่อยเพลงใหม่",
  str_n25_idol_y_activity_title_2 = "ปล่อยอัลบั้มรูป",
  str_n25_idol_y_activity_title_3 = "ติดดาวในละคร",
  str_n25_idol_y_activity_title_4 = "บันทึกรายการวิทยุ",
  str_n25_idol_y_activity_title_5 = "แฟนมีต",
  str_n25_idol_y_activity_title_6 = "ยิงโฆษณาสปอนเซอร์",
  str_n25_idol_y_activity_desc_1 = "<color=#6d50c3>เปิดตัวเพลงกล่อมนกฮูกลูทูมิ</color>\nฮู้ ฮู้ ♪ ดูเหมือนว่าชาวออโรเรียนจำนวนมากจะฟังเพลงนี้ก่อนนอนเพื่อให้นอนหลับสบายขึ้น",
  str_n25_idol_y_activity_desc_2 = "<color=#6d50c3>เปิดตัว \"รักชั่วฟ้าดินสลาย\"</color>\nรักบนฟ้า เฝ้ามองคุณเสมอ ♪ เนวิเกเตอร์น้ำตาไหลทันทีที่ได้ยิน!",
  str_n25_idol_y_activity_desc_3 = "<color=#6d50c3>เปิดตัว \"Chef's Sonata\"</color>\nพวกเขาใช้เครื่องครัวแทนเครื่องดนตรีในการบันทึกเพลงนี้ ดูเหมือนว่าพวกเขาจะผสมเสียง Eclipsite เล็กน้อย!",
  str_n25_idol_y_activity_desc_4 = "<color=#6d50c3>อัลบั้มภาพที่วางจำหน่าย: Fluff and Stuff!</color>\nการทำงานร่วมกันระหว่าง Goldie และ Novio กับกระต่ายของเขา กระต่ายช่างน่ารักเหลือเกิน! ใครจะไม่อยากเล่นกับสัตว์เล็ก ๆ เหล่านั้นทุกวัน?",
  str_n25_idol_y_activity_desc_5 = "<color=#6d50c3>อัลบั้มภาพที่วางจำหน่าย: Bunny Pyjamas</color>\nอัลบั้มนี้เต็มไปด้วยรูปภาพของโกลดี้ในชุดนอนกระต่ายตัวโปรดของเธอ! แม้แต่ผู้บัญชาการของ Illumina ก็ยังชอบใส่มัน!",
  str_n25_idol_y_activity_desc_6 = "<color=#6d50c3>อัลบั้มภาพเปิดตัว: Train Hard, Idol!</color>\nอัลบั้มนี้ประกอบด้วยรูปภาพที่ถ่ายของโกลดี้ระหว่างการฝึก ทุกนาทีบนเวทีต้องใช้เวลาฝึกฝนหลายปี! ไอดอลตัวจริงไม่เคยหยุดฝึกฝน!",
  str_n25_idol_y_activity_desc_7 = "<color=#6d50c3>แสดงใน: \"นักสืบกอลเมส\"</color>\nภาพยนตร์ฮิตที่นำแสดงโดยลิลิกาในบทลิลิอาร์ตี้ ผู้บงการวายร้าย และโกลดี้ในบทนักสืบกอลเมส การประลองครั้งสุดท้ายใน Umbraton นั้นน่าตื่นเต้นเป็นพิเศษ!",
  str_n25_idol_y_activity_desc_8 = "<color=#6d50c3>แสดงใน: \"Phantom of the Theatre\"</color>\nการเปิดตัว \"Phantom of the Theatre\" ประสบความสำเร็จอย่างมาก! ทุกอย่างเป็นไปด้วยดี... ยกเว้นท่อนที่โกลดี้ทำแก้วแตกพร้อมกับร้องเพลงเสียงแหลมของเธอ เดาว่าการฝึกฝนทั้งหมดนั้นได้ผลตอบแทนแล้ว!",
  str_n25_idol_y_activity_desc_9 = "<color=#6d50c3>แสดงใน: \"ห้าพันเมตรต่อวินาที\"</color>\nการแปลความหมายของ \"ห้าพันเมตรต่อวินาที\" นี้ขายหมดแล้ว! คุณสามารถเปลี่ยนเวทีให้กลายเป็นรถไฟได้ และ Charon เองก็รับบทเป็นวาทยกร!",
  str_n25_idol_y_activity_desc_10 = "<color=#6d50c3>รายการวิทยุที่บันทึกไว้: Idol Legends of Umbraton</color>\nโกลดีเล่นเป็นนักแสดงนำหญิงในรายการวิทยุ Idol Legends of Umbraton ผู้เขียนเรื่องราวไม่ประสงค์จะออกนาม แต่พวกเขาบอกว่าเป็นผู้จัดการใน Umbraton Guild",
  str_n25_idol_y_activity_desc_11 = "<color=#6d50c3>รายการวิทยุที่บันทึกไว้: Ada และ Colossus</color>\nแสดงในการผลิต Ada และ Colossus สำหรับสถานีวิทยุท้องถิ่น แม้จะสั้นแต่เรื่องราวก็ยังกินใจ นอกจากนี้เด็ก ๆ ทุกคนชอบมันมาก!",
  str_n25_idol_y_activity_desc_12 = "<color=#6d50c3>รายการวิทยุที่บันทึกไว้: รายงานการจราจรเมืองกันนอน</color>\nแขกรับเชิญในรายงานการจราจรปกติของ Gannon City ระบบขนส่งใต้ดินของเมืองนี้ซับซ้อนจริงๆ!",
  str_n25_idol_y_activity_desc_13 = "<color=#6d50c3>จัดงานแฟนมีตติ้ง: Umbraton</color>\nสายที่จะจับมือกับดาราที่รักของพวกเขาวิ่งไปตามริมฝั่งแม่น้ำทองคำ!",
  str_n25_idol_y_activity_desc_14 = "<color=#6d50c3>จัดงานแฟนมีตติ้ง: Rediesel Desert</color>\nเป็นเรื่องน่าประหลาดใจที่เห็นทุกคนใน Rediesel Wrench ต่อแถวอย่างเป็นระเบียบสำหรับงานนี้! ทุกอย่างเป็นไปได้ด้วยดีจนกระทั่งบาร์บาราขอให้ไอดอลเผชิญหน้า",
  str_n25_idol_y_activity_desc_15 = "<color=#6d50c3>จัดงานแฟนมีตติ้ง: Illumina</color>\nตอนนี้ทุกคนใน Illumina สนใจไอดอลมาก! ในงานมีผู้คนมากมาย... เห็นได้ชัดว่าแม้แต่จอมพลก็ปรากฏตัวปลอมตัวเพื่อตรวจสอบสิ่งต่างๆ!",
  str_n25_idol_y_activity_desc_16 = "<color=#6d50c3>ถ่ายภาพเสร็จ: Rediesel Delights</color>\nหลังจากถ่ายภาพโปรโมทร้าน Rediesel Delights ร้านขายขนมท้องถิ่น ร้านของ Jomu ก็แน่นขนัดมาหลายวัน!",
  str_n25_idol_y_activity_desc_17 = "<color=#6d50c3>ถ่ายรูปเสร็จ: Connolly's Cafe</color>\nผู้คนจำนวนมากอยากลองกาแฟของ Connolly หลังจากโพสต์รูปภาพโปรโมตของเรา! อันที่จริง เธอกำลังพิจารณาจ้างบาริสต้าพาร์ทไทม์...",
  str_n25_idol_y_activity_desc_18 = "<color=#6d50c3>ถ่ายภาพเสร็จสมบูรณ์: ดินแดนทางเหนือ</color>\nหลังจากถ่ายภาพเพื่อส่งเสริมการท่องเที่ยวในภาคเหนือแล้ว นักท่องเที่ยวจำนวนมากเดินทางขึ้นไปที่นั่นเพื่อปั้นตุ๊กตาหิมะและเพลิดเพลินกับสถานที่ท่องเที่ยว!",
  str_n25_idol_y_activity_forwho_1 = "<color=#6d50c3>เปิดตัวเพลงกล่อมนกฮูกลูทูมิ</color>",
  str_n25_idol_y_activity_forwho_2 = "<color=#6d50c3>เปิดตัว \"รักชั่วฟ้าดินสลาย\"</color>",
  str_n25_idol_y_activity_forwho_3 = "<color=#6d50c3>เปิดตัว \"Chef's Sonata\"</color>",
  str_n25_idol_y_activity_forwho_4 = "<color=#6d50c3>อัลบั้มภาพที่วางจำหน่าย: Fluff and Stuff!</color>",
  str_n25_idol_y_activity_forwho_5 = "<color=#6d50c3>อัลบั้มภาพที่วางจำหน่าย: Bunny Pyjamas</color>",
  str_n25_idol_y_activity_forwho_6 = "<color=#6d50c3>อัลบั้มภาพเปิดตัว: Train Hard, Idol!</color>",
  str_n25_idol_y_activity_forwho_7 = "<color=#6d50c3>แสดงใน: \"นักสืบกอลเมส\"</color>",
  str_n25_idol_y_activity_forwho_8 = "<color=#6d50c3>แสดงใน: \"Phantom of the Theatre\"</color>",
  str_n25_idol_y_activity_forwho_9 = "<color=#6d50c3>แสดงใน: \"ห้าพันเมตรต่อวินาที\"</color>",
  str_n25_idol_y_activity_forwho_10 = "<color=#6d50c3>รายการวิทยุที่บันทึกไว้: Idol Legends of Umbraton</color>",
  str_n25_idol_y_activity_forwho_11 = "<color=#6d50c3>รายการวิทยุที่บันทึกไว้: Ada และ Colossus</color>",
  str_n25_idol_y_activity_forwho_12 = "<color=#6d50c3>รายการวิทยุที่บันทึกไว้: รายงานการจราจรเมืองกันนอน</color>",
  str_n25_idol_y_activity_forwho_13 = "<color=#6d50c3>จัดงานแฟนมีตติ้งใน: Umbraton</color>",
  str_n25_idol_y_activity_forwho_14 = "<color=#6d50c3>จัดงานแฟนมีตติ้งใน: Rediesel Desert</color>",
  str_n25_idol_y_activity_forwho_15 = "<color=#6d50c3>จัดงานแฟนมีตติ้งใน: Illumina</color>",
  str_n25_idol_y_activity_forwho_16 = "<color=#6d50c3>เสร็จสิ้นการถ่ายภาพสำหรับ: Rediesel Delights</color>",
  str_n25_idol_y_activity_forwho_17 = "<color=#6d50c3>เสร็จสิ้นการถ่ายภาพสำหรับ: Connolly's Cafe</color>",
  str_n25_idol_y_activity_forwho_18 = "<color=#6d50c3>เสร็จสิ้นการถ่ายภาพสำหรับ: Northland</color>",
  str_n25_idol_y_activity_desc_short_1 = "ฮู้ ฮู้ ♪ ดูเหมือนว่าชาวออโรเรียนจำนวนมากจะฟังเพลงนี้ก่อนนอนเพื่อให้นอนหลับสบายขึ้น",
  str_n25_idol_y_activity_desc_short_2 = "รักเหนือฟ้า เฝ้ามองเธอเสมอ ♪ เนวิเกเตอร์น้ำตาไหลทันทีที่ได้ยิน!",
  str_n25_idol_y_activity_desc_short_3 = "พวกเขาใช้เครื่องครัวแทนเครื่องดนตรีในการบันทึกเพลงนี้ ดูเหมือนว่าพวกเขาจะผสมเสียง Eclipsite เล็กน้อย!",
  str_n25_idol_y_activity_desc_short_4 = "การทำงานร่วมกันระหว่าง Goldie และ Novio กับกระต่ายของเขา กระต่ายช่างน่ารักเหลือเกิน! ใครจะไม่อยากเล่นกับสัตว์เล็ก ๆ น้อย ๆ เหล่านั้นทุกวัน?",
  str_n25_idol_y_activity_desc_short_5 = "อัลบั้มนี้เต็มไปด้วยรูปภาพของโกลดี้ในชุดนอนกระต่ายตัวโปรดของเธอ! แม้แต่ผู้บัญชาการของ Illumina ก็ยังชอบใส่มัน!",
  str_n25_idol_y_activity_desc_short_6 = "อัลบั้มนี้ประกอบด้วยรูปภาพที่ถ่ายของโกลดี้ระหว่างการฝึก ทุกนาทีบนเวทีต้องใช้เวลาฝึกฝนหลายปี! ไอดอลตัวจริงไม่เคยหยุดฝึกฝน!",
  str_n25_idol_y_activity_desc_short_7 = "ภาพยนตร์ฮิตที่นำแสดงโดยลิลิกาในบทลิลิอาร์ตี้ ผู้บงการวายร้าย และโกลดี้ในบทนักสืบกอลเมส การประลองครั้งสุดท้ายใน Umbraton เป็นฉากที่น่าตื่นเต้นเป็นพิเศษ!",
  str_n25_idol_y_activity_desc_short_8 = "การเปิดตัว \"Phantom of the Theatre\" ประสบความสำเร็จอย่างมาก! ทุกอย่างเป็นไปด้วยดี... ยกเว้นท่อนที่โกลดี้ทำแก้วแตกพร้อมกับร้องเพลงเสียงแหลมของเธอ เดาว่าการฝึกฝนทั้งหมดนั้นได้ผลตอบแทนแล้ว!",
  str_n25_idol_y_activity_desc_short_9 = "การแปลความหมายของ \"ห้าพันเมตรต่อวินาที\" นี้ขายหมดแล้ว! เวทีถูกสร้างเป็นรถไฟ และ Charon เองก็รับบทเป็นวาทยกร!",
  str_n25_idol_y_activity_desc_short_10 = "โกลดีเล่นเป็นนักแสดงนำหญิงในรายการวิทยุ Idol Legends of Umbraton ผู้เขียนเรื่องราวไม่ประสงค์จะออกนาม แต่พวกเขาบอกว่าเป็นผู้จัดการใน Umbraton Guild",
  str_n25_idol_y_activity_desc_short_11 = "แสดงในการผลิต \"Ada and the Colossus\" สำหรับสถานีวิทยุท้องถิ่น แม้จะสั้นแต่เรื่องราวก็ยังกินใจ นอกจากนี้เด็ก ๆ ทุกคนชอบมันมาก!",
  str_n25_idol_y_activity_desc_short_12 = "Goldie เป็นแขกรับเชิญพิเศษในรายงานการจราจรปกติของ Gannon City ระบบขนส่งใต้ดินของเมืองนี้ซับซ้อนจริงๆ!",
  str_n25_idol_y_activity_desc_short_13 = "สายที่จะจับมือกับดาราที่รักของพวกเขาวิ่งไปตามริมฝั่งแม่น้ำทองคำ!",
  str_n25_idol_y_activity_desc_short_14 = "เป็นเรื่องน่าประหลาดใจที่เห็นทุกคนใน Rediesel Wrench ต่อแถวอย่างเป็นระเบียบสำหรับงานนี้! ทุกอย่างเป็นไปได้ด้วยดีจนกระทั่งบาร์บาราขอให้ไอดอลเผชิญหน้า",
  str_n25_idol_y_activity_desc_short_15 = "ตอนนี้ทุกคนใน Illumina สนใจไอดอลมาก! ในงานมีผู้คนมากมาย... เห็นได้ชัดว่าแม้แต่จอมพลก็ปรากฏตัวปลอมตัวเพื่อตรวจสอบสิ่งต่างๆ!",
  str_n25_idol_y_activity_desc_short_16 = "หลังจากถ่ายภาพโปรโมทร้านขายขนมในท้องถิ่นที่ชื่อว่า Rediesel Delights ผู้คนก็มารวมตัวกันที่ร้านของ Jomu มาหลายวันแล้ว!",
  str_n25_idol_y_activity_desc_short_17 = "ผู้คนจำนวนมากอยากลองกาแฟของ Connolly หลังจากโพสต์รูปภาพโปรโมตของเรา! อันที่จริง เธอกำลังพิจารณาจ้างบาริสต้าพาร์ทไทม์...",
  str_n25_idol_y_activity_desc_short_18 = "หลังจากถ่ายภาพเพื่อส่งเสริมการท่องเที่ยวในนอร์ธแลนด์แล้ว นักท่องเที่ยวจำนวนมากเดินทางขึ้นไปที่นั่นเพื่อสร้างตุ๊กตาหิมะและเพลิดเพลินไปกับสถานที่ท่องเที่ยว!",
  str_n25_idol_y_trun_closed_14 = "คอนเสิร์ตเปิดตัวประสบความสำเร็จ! The Navigator ยังคงก้าวหน้าอย่างมั่นคงบนเส้นทางสู่การเป็นผู้ผลิต\nแต่เมื่อคอนเสิร์ตเดบิวต์ใกล้จะจบลง ความท้าทายต่อไปก็ใกล้เข้ามามากขึ้น: คอนเสิร์ตประเมินผล!\nอนาคตมีไว้สำหรับพวกเขาอย่างไร? กลับมาและฝึกฝนไอดอลของคุณต่อไปเพื่อค้นหา!",
  str_n25_idol_y_trun_closed_28 = "การประกวดประเมินผลประสบความสำเร็จ! Goldie, Vice, Carleen และ Navigator ใช้เวลาสักครู่เพื่อฉลองชัยชนะที่ได้มาอย่างยากลำบาก\nสิ่งที่เหลืออยู่ตอนนี้คือความท้าทายสุดท้าย... Graduation Concert!\nอนาคตมีไว้สำหรับพวกเขาอย่างไร? กลับมาและฝึกฝนไอดอลของคุณต่อไปเพื่อค้นหา!",
  str_n25_idol_y_arrange_desc_1 = "<color=#4c4c4c>รอง</color> ต้องการพบคุณ.",
  str_n25_idol_y_arrange_desc_2 = "<color=#4c4c4c>รอง</color> ต้องการพบคุณ.",
  str_n25_idol_y_arrange_desc_3 = "<color=#4c4c4c>รอง</color> ต้องการพบคุณ.",
  str_n25_idol_y_arrange_desc_4 = "<color=#4c4c4c>วิก</color> ต้องการพบคุณ.",
  str_n25_idol_y_arrange_desc_5 = "<color=#4c4c4c>วิก</color> ต้องการพบคุณ.",
  str_n25_idol_y_arrange_desc_6 = "<color=#4c4c4c>วิก</color> ต้องการพบคุณ.",
  str_n25_idol_y_arrange_desc_7 = "<color=#4c4c4c>โกลดี้</color> ต้องการพบคุณ.",
  str_n25_idol_y_arrange_desc_8 = "<color=#4c4c4c>โกลดี้</color> ต้องการพบคุณ.",
  str_n25_idol_y_arrange_desc_9 = "<color=#4c4c4c>โกลดี้</color> ต้องการพบคุณ.",
  str_n25_idol_y_arrange_desc_10 = "<color=#4c4c4c>ชารอน</color> ต้องการพบคุณ.",
  str_n25_idol_y_arrange_desc_11 = "<color=#4c4c4c>ฟลอรีน</color> ต้องการพบคุณ.",
  str_n25_idol_y_arrange_desc_12 = "<color=#4c4c4c>รินเนะ</color> ต้องการพบคุณ.",
  str_n25_idol_y_arrange_desc_13 = "<color=#4c4c4c>นีน่า</color> ต้องการพบคุณ.",
  str_n25_idol_y_arrange_desc_14 = "<color=#4c4c4c>ลิลิก้า</color> ต้องการพบคุณ.",
  str_n25_idol_y_arrange_desc_15 = "<color=#4c4c4c>เฟลอร์</color> ต้องการพบคุณ.",
  str_n25_idol_y_concert_fail_gap_fans = "แฟนๆ จำเป็นต้องไปให้ถึงเป้าหมาย",
  str_n25_idol_y_story_cant_click_tips = "ปลดล็อกเมื่อทำงานใดๆจากรายการสิ่งที่ต้องทำของ {1} เสร็จสิ้น.",
  str_n25_idol_y_concert_item_current_fans = "แฟนปัจจุบัน:",
  str_n25_idol_y_not_open_next_day_tips_1 = "คอนเสิร์ตเปิดตัวประสบความสำเร็จ! The Navigator ยังคงก้าวหน้าอย่างมั่นคงบนเส้นทางสู่การเป็นผู้ผลิต\nแต่เมื่อคอนเสิร์ตเปิดตัวใกล้จะจบลง ความท้าทายต่อไปก็ยิ่งใกล้เข้ามา: คอนเสิร์ตประเมินผล!\nอนาคตมีไว้สำหรับพวกเขาอย่างไร? กลับมาและฝึกฝนไอดอลของคุณต่อไปเพื่อค้นหา!",
  str_n25_idol_y_not_open_next_day_tips_2 = "การประกวดประเมินผลประสบความสำเร็จ! Goldie, Vice, Carleen และ Navigator ใช้เวลาสักครู่เพื่อเฉลิมฉลองชัยชนะที่ได้มาอย่างยากลำบาก\nสิ่งที่เหลืออยู่ตอนนี้คือความท้าทายสุดท้าย... Graduation Concert!\nอนาคตมีไว้สำหรับพวกเขาอย่างไร? กลับมาและฝึกฝนไอดอลของคุณต่อไปเพื่อค้นหา!",
  str_n25_idol_y_act_open_next_not_tips = "คุณยังมีงาน Idol Event ที่คุณยังทำไม่เสร็จ!",
  str_n25_idol_y_next_page = "งานอื่นๆที่ต้องทำ",
  str_n25_idol_game_tip_music_title = "ทักษะการร้อง",
  str_n25_idol_game_tip_music_desc = "ทักษะการร้องของไอดอลสามารถปรับปรุงได้ผ่าน Idol Training",
  str_n25_idol_game_tip_dance_title = "ทักษะการเต้น",
  str_n25_idol_game_tip_dance_desc = "ทักษะการเต้นของไอดอลสามารถปรับปรุงได้ผ่าน Idol Training",
  str_n25_idol_game_tip_perform_title = "ทักษะการปฏิบัติงาน",
  str_n25_idol_game_tip_perform_desc = "ทักษะการแสดงของไอดอลสามารถปรับปรุงได้ผ่าน Idol Training",
  str_n25_idol_game_tip_fans_title = "<color=#6d50c3>แฟนปัจจุบัน</color>",
  str_n25_idol_game_tip_fans_desc = "จำนวนแฟน ๆ ในปัจจุบันของ Goldie เพิ่มแฟน ๆ ด้วยการจัดกิจกรรมไอดอล",
  str_n25_idol_game_training_title = "ไอดอลเทรนนิ่ง",
  str_n25_idol_game_act_title = "เหตุการณ์ไอดอล",
  str_n25_idol_game_training_class_music = "ห้องร้องเพลง",
  str_n25_idol_game_training_class_dance = "ห้องเต้นรำ",
  str_n25_idol_game_training_class_perform = "หอประชุม",
  str_n25_idol_game_training_class_start = "เริ่มการฝึกอบรม",
  str_n25_idol_game_training_class_process = "กำลังดำเนินการฝึกอบรม",
  str_n25_idol_game_training_class_succ = "การฝึกอบรมเสร็จสิ้น",
  str_n25_idol_game_intro_title = "ข้อมูลการเล่นเกม - Starlit Agency",
  str_n25_idol_game_intro_head_1 = "ไอดอลเทรนนิ่ง",
  str_n25_idol_game_intro_head_2 = "เหตุการณ์ไอดอล",
  str_n25_idol_game_intro_head_3 = "คอนเสิร์ต",
  str_n25_idol_game_intro_body_1 = "ในฐานะโปรดิวเซอร์ คุณสามารถช่วย Goldie พัฒนาในฐานะไอดอลได้โดยเลือกโปรแกรมการฝึกที่เหมาะสมในอินเทอร์เฟซ Idol Training\nในระหว่างการฝึก คุณอาจพบกับช่วงเวลาแห่งแรงบันดาลใจฉับพลัน ซึ่งสามารถเพิ่มความก้าวหน้าของโกลดี้ได้อย่างมาก!\nนอกจากนี้ Aurorians ที่แตกต่างกันจะปรากฏในห้องโถงฝึกอบรมต่างๆ ตามรายการสิ่งที่ต้องทำของคุณ พูดคุยกับพวกเขาและดูว่ามีอะไรให้บ้าง!\nบางครั้งปาปารัซซี่จะปรากฏตัวระหว่างการฝึกซ้อมของคุณ อย่าลืมเมินเขาอย่างใจเย็นและสุภาพ!",
  str_n25_idol_game_intro_body_2 = "จัดกิจกรรมไอดอลเพื่อรับแฟน ๆ มากขึ้น\nIdol Events มีความต้องการทักษะที่แตกต่างกัน ดังนั้นฝึกฝนต่อไปเพื่อเพิ่มระดับทักษะของคุณ!",
  str_n25_idol_game_intro_body_3 = "คอนเสิร์ตเป็นวิธีที่ดีที่สุดในการแสดงทักษะของไอดอล!\nหากต้องการจัดคอนเสิร์ตให้ประสบความสำเร็จ คุณต้องมีแฟนเพลงมากพอก่อนที่จะจัดคอนเสิร์ต มิฉะนั้น คอนเสิร์ตจะล้มเหลว!\nจัดกิจกรรมไอดอลให้มากขึ้นเพื่อเพิ่มฐานแฟนคลับของคุณ!",
  str_n25_idol_game_puppy_btn = "กลับไปที่การฝึกอบรม",
  str_n25_idol_game_puppy_question_name = "ปาปารัซซี่",
  str_n25_idol_game_puppy_result_title = "ผลลัพธ์",
  str_n25_idol_game_puppy_question_1 = "สวัสดี ฉันเป็นนักข่าวของ Daily Drivel จริงหรือไม่ที่รายงานความสูงของโกลดีที่ 5'6'' เป็นเรื่องโกหก?",
  str_n25_idol_game_puppy_question_cond_1_1 = "ไม่แน่นอน! วัดด้วยตัวคุณเองถ้าคุณไม่เชื่อฉัน!",
  str_n25_idol_game_puppy_question_cond_1_2 = "โกลดี้สูง 5'6'' จริงๆ!",
  str_n25_idol_game_puppy_question_cond_1_3 = "อย่างน้อยเธอก็สูงกว่าวิค",
  str_n25_idol_game_puppy_result_1_1 = "คุณเอาตลับเมตรวัดความสูงของโกลดี้... 5'6'' ไม่มากและไม่น้อย!",
  str_n25_idol_game_puppy_result_1_2 = "นักข่าวรับคำตอบที่ไม่น่าเชื่อของคุณและจากไป\nวันต่อมา เขาเขียนถึงการที่คุณไม่มีหลักฐาน\nแฟนๆ ของ Goldie บางคนเริ่มสงสัยในตัวเธอ",
  str_n25_idol_game_puppy_result_1_3 = "นักข่าวลงบทความเปรียบเทียบความสูงของโกลดี้กับวิก\nในนั้น Vic สูงกว่าเธออย่างชัดเจน\nนักข่าวอ้างว่าคุณพยายามเยาะเย้ยวิค\nแฟนๆ ของ Goldie บางคนเริ่มสงสัยในตัวเธอ",
  str_n25_idol_game_puppy_question_2 = "สวัสดี ฉันเป็นนักข่าวของ Daily Drivel เพลงใหม่ล่าสุดของ Goldie ถูกลอกเลียนแบบมาจากเพลงของ Umbraton Boys จริงหรือ?",
  str_n25_idol_game_puppy_question_cond_2_1 = "ข่าวลือเหล่านั้นไม่มีมูลความจริงเลย เราสามารถจ้างผู้เชี่ยวชาญเพื่อจัดการเรื่องนี้ได้",
  str_n25_idol_game_puppy_question_cond_2_2 = "ไม่คิดว่าเพลงจะเหมือนกันเลย...",
  str_n25_idol_game_puppy_question_cond_2_3 = "Umbraton Boys คุณกำลังพูดถึงอะไร ฉันไม่เคยได้ยินเกี่ยวกับพวกเขา!",
  str_n25_idol_game_puppy_result_2_1 = "คุณจ้างผู้เชี่ยวชาญด้านดนตรี Umbraton ที่มีชื่อเสียงเพื่อเสนอข้อมูลเชิงลึกเกี่ยวกับเรื่องนี้\nหลังจากวิเคราะห์อย่างถี่ถ้วน...\nทั้งสองเพลงแสดงให้เห็นว่าไม่มีความคล้ายคลึงกันเลย",
  str_n25_idol_game_puppy_result_2_2 = "นักข่าวกล่าวหาว่าคุณพูดด้วยอคติส่วนตัว\nแฟนๆ ของ Goldie บางคนเริ่มสงสัยในตัวเธอ",
  str_n25_idol_game_puppy_result_2_3 = "นักข่าวกล่าวหาว่าคุณล้อเลียน Umbraton Boys\nแฟนๆ ของ Goldie บางคนเริ่มสงสัยในตัวเธอ",
  str_n25_idol_game_puppy_question_3 = "สวัสดี ฉันเป็นนักข่าวของ Daily Drivel มีข่าวลือแพร่สะพัดว่าโกลดี้สวมวิกในที่สาธารณะ และในความเป็นจริงแล้วเธอหัวโล้น ต้องการแสดงความคิดเห็นเกี่ยวกับเรื่องนี้หรือไม่?",
  str_n25_idol_game_puppy_question_cond_3_1 = "ขอให้แพทย์ตั้งค่าบันทึกตรง!",
  str_n25_idol_game_puppy_question_cond_3_2 = "นี่คือการเลือกปฏิบัติต่อคนหัวล้าน!",
  str_n25_idol_game_puppy_question_cond_3_3 = "เรื่องตลก... ทำไมฉันต้องบอกอะไรคุณด้วย?",
  str_n25_idol_game_puppy_result_3_1 = "คุณขอให้แพทย์ประเมินสุขภาพหนังศีรษะและเส้นผมของโกลดี\nแพทย์ยืนยันกับสาธารณชนว่าผมของ Goldie นั้นสมบูรณ์จริงและมีสุขภาพดี",
  str_n25_idol_game_puppy_result_3_2 = "คำตอบของคุณทำให้นักข่าวสงสัยมากขึ้นเท่านั้น\nแฟนๆ ของ Goldie หลายคนเริ่มกังวลเกี่ยวกับสุขภาพหนังศีรษะของเธอ\nแฟนๆ ของ Goldie บางคนเริ่มสงสัยในตัวเธอ",
  str_n25_idol_game_puppy_result_3_3 = "นักข่าวกล่าวหาว่าคุณและโกลดี้หยิ่งผยอง\nแฟนๆ ของ Goldie บางคนเริ่มสงสัยในตัวเธอ",
  str_n25_idol_game_puppy_question_4 = "สวัสดี ฉันเป็นนักข่าวของ Daily Drivel คำพูดบนท้องถนนคือโกลดี้ร้องเพลงไม่ได้จริง ๆ และการแสดงทั้งหมดของเธอก็ลิปซิงค์ นี่เป็นเรื่องจริงหรือไม่?",
  str_n25_idol_game_puppy_question_cond_4_1 = "ทำไมคุณไม่ฟัง Goldie ร้องเพลงด้วยตัวคุณเองล่ะ?",
  str_n25_idol_game_puppy_question_cond_4_2 = "เราไม่สามารถแม้แต่จะจ้างนักพากย์มืออาชีพแบบนั้นได้",
  str_n25_idol_game_puppy_question_cond_4_3 = "อะไรกัน ข่าวลือไร้ยางอายพวกนี้อีกแล้วเหรอ?",
  str_n25_idol_game_puppy_result_4_1 = "คุณขอให้โกลดี้ร้องเพลง \"For Your Ears Only\" ให้นักข่าวฟัง",
  str_n25_idol_game_puppy_result_4_2 = "นักข่าวกล่าวหาว่าคุณเลี่ยงคำถาม\nเขาเขียนบทความเกี่ยวกับคำตอบที่คลุมเครือของคุณ\nแฟนๆ ของ Goldie บางคนเริ่มสงสัยในตัวเธอ",
  str_n25_idol_game_puppy_result_4_3 = "นักข่าวกล่าวหาคุณใส่ร้ายเพื่อนร่วมวงการ\nและคุณไม่มีหลักฐานที่ชัดเจน\nแฟนๆ ของ Goldie บางคนเริ่มสงสัยในตัวเธอ",
  str_n25_idol_game_puppy_question_5 = "สวัสดี ฉันเป็นนักข่าวของ Daily Drivel จริงหรือไม่ที่โกลดี้แอบเก็บ Eclipsite ไว้เป็นสัตว์เลี้ยง?",
  str_n25_idol_game_puppy_question_cond_5_1 = "ดูเหมือนจะเป็นการเข้าใจผิด สัตว์เลี้ยงตัวเดียวของโกลดี้คือลูกสุนัขของเธอ",
  str_n25_idol_game_puppy_question_cond_5_2 = "หากเป็นเรื่องจริง โกลดี้อาจกลืนไมโครโฟนของเธอลงไปด้วย!",
  str_n25_idol_game_puppy_question_cond_5_3 = "ได้โปรด นั่นคือสิ่งที่ดีที่สุดที่คุณจะคิดขึ้นมาได้หรือเปล่า",
  str_n25_idol_game_puppy_result_5_1 = "คุณเรียก Marshmallow\nที่กระดอนอย่างมีความสุขและเอาชนะนักข่าวทันที",
  str_n25_idol_game_puppy_result_5_2 = "เพราะนักข่าวไม่สามารถหาคำตอบได้ว่า\nเขาตัดสินใจกระจายข่าวลือใหม่: โกลดี้ชอบกินของแปลกๆ\nแฟนๆ ของ Goldie บางคนเริ่มสงสัยในตัวเธอ",
  str_n25_idol_game_puppy_result_5_3 = "นักข่าวกล่าวหาคุณใส่ร้ายเพื่อนร่วมวงการ\nและคุณไม่มีหลักฐานที่ชัดเจน\nแฟนๆ ของ Goldie บางคนเริ่มสงสัยในตัวเธอ",
  str_n25_idol_game_puppy_question_cond_disable = "นักข่าวคิดว่าคำตอบของคุณคลุมเครือเกินไป\nแปลว่าข่าวลือต้องเป็นความจริง\nแฟนๆ ของ Goldie บางคนเริ่มสงสัยในตัวเธอ",
  str_n25_idol_game_spine_talk_name = "โกลดี้",
  str_n25_idol_game_spine_talk_1_1 = "มาทำให้เต็มที่กันเถอะโปรดิวเซอร์!",
  str_n25_idol_game_spine_talk_1_2 = "กับ PlayerName ในฐานะโปรดิวเซอร์ ในที่สุดฉันก็สามารถมีสมาธิกับการฝึกได้!",
  str_n25_idol_game_spine_talk_1_3 = "วันนี้เราจะทำการฝึกอบรมแบบไหน?",
  str_n25_idol_game_spine_talk_2_1 = "ฉันหวังว่าคอนเสิร์ตประเมินผลจะผ่านไปด้วยดีเช่นกัน!",
  str_n25_idol_game_spine_talk_2_2 = "ลา ลา ลา ลา ลา! ฉันควรจะไปให้สูงกว่านี้ในโน้ตตัวสุดท้าย... ! ย-คุณกำลังฟังอยู่เหรอ?!",
  str_n25_idol_game_spine_talk_2_3 = "คุณก้าวหน้าไปมากแล้ว! ที่ฉันสามารถยืนยันได้!",
  str_n25_idol_game_spine_talk_3_1 = "ฉันจะฝากแผนการฝึกซ้อมของวันนี้ไว้ให้คุณ PlayerName!",
  str_n25_idol_game_spine_talk_3_2 = "การเรียนจบไม่ใช่จุดจบ แต่เป็นการเริ่มต้นใหม่! ดังนั้นมาทำให้ดีที่สุดเพื่อจัดคอนเสิร์ตจบการศึกษาที่ยิ่งใหญ่ที่สุดเท่าที่เคยมีมา!",
  str_n25_idol_game_spine_talk_3_3 = "สวัสดี! โฮ! ไปกันเถอะ! ...ฮะ? โอ้ ฉันแค่เชียร์คุณ!",
  str_n25_idol_game_spine_talk_concert_1_1 = "คอนเสิร์ตกำลังจะเริ่มขึ้นแล้ว! รู้สึกประหม่า?",
  str_n25_idol_game_spine_talk_concert_1_2 = "ผ่อนคลาย! เมื่อมีคุณอยู่เคียงข้าง ฉันมั่นใจว่าคอนเสิร์ตจะดำเนินไปอย่างราบรื่น!",
  str_n25_idol_game_spine_talk_concert_1_3 = "อยากเลี้ยง Marshmallow ไหม? ไม่มีอะไรทำให้ประสาทสงบลงได้เท่ากับการได้คลอเคลียกับสัตว์น่ารักขนปุกปุย!",
  str_n25_idol_game_spine_talk_concert_2_1 = "โปรดิวเซอร์ของฉันและฉันพร้อมที่สุดสำหรับคอนเสิร์ตประเมิน! ลงมือทำกันเถอะ!",
  str_n25_idol_game_spine_talk_concert_2_2 = "คุณดูไม่ประหม่าแม้แต่น้อยอีกต่อไป PlayerName! นั่นแสดงว่าคุณมาไกลแล้ว รู้ไหม!",
  str_n25_idol_game_spine_talk_concert_2_3 = "ปิ่นปักผมชี้ลง! นั่นหมายถึงสิ่งดีๆ กำลังจะเกิดขึ้น!",
  str_n25_idol_game_spine_talk_concert_3_1 = "ในที่สุดเราก็มาถึงคอนเสิร์ตจบการศึกษา... ฉันไม่มีทางทำสิ่งนี้สำเร็จได้หากไม่ได้รับความช่วยเหลือจากคุณ PlayerName!",
  str_n25_idol_game_spine_talk_concert_3_2 = "ฉันคิดว่าฉันได้ยินเสียงฝูงชนเรียกให้ฉันขึ้นไปบนเวที! ได้ยินคนมากมายเรียกชื่อฉัน... ฉันไม่สามารถอธิบายได้ว่ามันทำให้ฉันมีความสุขแค่ไหน!",
  str_n25_idol_game_spine_talk_concert_3_3 = "นี่จะเป็นคอนเสิร์ตที่ยิ่งใหญ่ที่สุดของฉัน และฉันเป็นหนี้บุญคุณทั้งหมด PlayerName! ถึงเวลาแล้วที่โปรดิวเซอร์ของฉันจะกลับมานั่งดูฉันเปล่งประกาย!"
}
return config
