---
--- Generated by jialei
--- Created by jialei.
---

------------ import ------------
local KTool = CS.Engine.Lib.KTool
local CardConfMgr = CardConfMgr
local UIBattlingCtrlMgr = import("Game.UI.UIBattling.UIBattlingCtrlMgr")
------------ import ------------

---@class UIBattlingTipsPanel
---@field SkillTagCell                  	UnityEngine.RectTransform
---@field SkillTagList                  	UnityEngine.RectTransform
---@field TxtSkillLv                    	Game.Native.Common.UISwitchImage
---@field SkillCharactorImg             	Engine.UI.ImageAlterable
---@field SkillDesTxt                   	UnityEngine.UI.Text
---@field SkillTypeIcon                 	Engine.UI.RawImageAlterable
---@field SkillNameTxt                  	UnityEngine.UI.Text
local UIBattlingTipsPanel = Class("UIBattlingTipsPanel")

function UIBattlingTipsPanel:__init()
    self:CleanField()
end

function UIBattlingTipsPanel:__delete()
    self:CleanField()
    self.controller = nil
    self = nil
end

function UIBattlingTipsPanel:CleanField()
    self.strSkillName = nil
    self.strSkillLv = nil
    self.strSkillDes = nil
    self.pathSkillCardCharactorImg = nil
    self.tagCells = nil
end

function UIBattlingTipsPanel:Awake()
end

function UIBattlingTipsPanel:OnDestroy()
    self.controller = nil
    --luabehaviour 中CSharp对象
    self:Delete()
    self = nil
end

---SetPanelInfo
---设置 Tips 面板 信息
---@param data SkillDataVo @ UIBattlingSkillPoolPanel.SkillDataVo
function UIBattlingTipsPanel:SetPanelInfo(data)
    xTry(function()
        local roleView = BattleViewMgr:FindRoleView(data.roleId)
        
        local skillVo = UIBattlingTools.GetSkillCardInfoByTwoParam(data.skillId, data.star)
        ----- 技能名
        self.SkillNameTxt.text = skillVo.skillName
        ----- 技能描述
        local rare = 1
        if roleView.isSkillCat then
            rare = roleView.rare
        else
            local cardVo = CardConfMgr:GetCardByRefId(roleView.typeId)
            rare = cardVo.rare
        end
        local skillType = skillVo.skillType
        local strSkillDesc = UIBattlingTools.GetSkillDescInBattle(data.skillId, data.star, rare, true)
        local damageDesc = UIBattlingTools.GetSkillDamageTypeDescInBattle(data.skillId, data.star)
        local skillDesc = string.len(damageDesc) > 0 and strSkillDesc .. "\n" .. damageDesc or strSkillDesc
        self.SkillDesTxt.text = skillDesc
        --- 星级
        if self.TxtSkillLv then
            self.TxtSkillLv.Status = checkInt(data.star) 
            self.TxtSkillLv:Reset()
        end
        ----- 技能类型
        local skillData = UIBattlingTools.GetSkillCardInfoByTwoParam(data.skillId)
        local showLabel = skillData.showLabel
        local skillLabel = UICommonUtils:GetSkillShowLabelWithStar(showLabel, data.star)
        local isAoe =  checkBool(checkNumber(skillData.isAoe) > 0)
        local condition = skillLabel >= 1 and skillLabel <= 4 and isAoe
        local path = condition and UIBattlingTools.GetEnemySkillTypeAOEIconPath(skillLabel) 
                or UIBattlingTools.GetEnemySkillTypeIconPath(skillLabel)
        UIBattlingCtrlMgr:GetInstance():SetImgByDynamicAtlas(self.SkillTypeIcon, path)
        local imgPath = data.imgPath
        if isNull(imgPath) then
            local skinId = roleView.skinId
            local skinVo = CardConfMgr:GetInstance():GetCardSkinBySkinId(skinId)
            imgPath = skinVo.cardHeadList
        end
        self.SkillCharactorImg:LoadSprite(imgPath)
        self:SetSkillTag(data)

        CoStart(function()
            CoYield()
            local tfSkillInfoBg = self.controller.transform:Find("Container/SkillInfoBg")
            local rt = tfSkillInfoBg.gameObject:GetComponent(typeof(CS.UnityEngine.RectTransform))
            rt.anchoredPosition = Vector2.New(-400, 0)
            rt.anchorMin = Vector2.one
            rt.anchorMax = Vector2.one
            rt.pivot = Vector2.New(0.5, 1)
        end)
    end)
end

------------ TagCell ------------

function UIBattlingTipsPanel:SetSkillTag(data)
    local skillCardId = data.skillId
    local skillCardVO = UIBattlingTools.GetSkillCardInfoByTwoParam(skillCardId)
    --- 技能 Tags 列表
    self:CleanTagCells()
    
    ---@type CardProgressionSkillUtils
    local CardProgressionSkillUtils     = import("Game.CardProgression.CardProgressionSkillUtils")
    local skillTags = CardProgressionSkillUtils.GetSkillTags(skillCardVO.abstractLabel, data.star)

    KTool.SetActive(self.SkillTagList.gameObject, skillTags and #skillTags > 0)
    local limitValueShow = 4
    for i, labelId in ipairs(skillTags) do
        if i <= limitValueShow then
            local descTag = CfUtils.GetCfData(AutoIds.IdSetting284, labelId, "desc", Constants.DataType.LocalString)
            local goCell = self:InitTagCell()
            self:SetTagCellInfo(goCell, descTag)
        end
    end
end

function UIBattlingTipsPanel:SetTagCellInfo(go, desc)
    local txtDesc = go.transform:Find("Text_SkillTag").gameObject:GetComponent(typeof(CS.UnityEngine.UI.Text))
    txtDesc.text = desc
end

function UIBattlingTipsPanel:InitTagCell()
    if isNull(self.tagCells) then self.tagCells = {} end
    local go = KTool.Instantiate(self.SkillTagList.gameObject, self.SkillTagCell.gameObject)
    KTool.SetActive(go, true)
    table.insert(self.tagCells, go)
    return go
end

function UIBattlingTipsPanel:CleanTagCells()
    if isNull(self.tagCells) then return end
    for i = #self.tagCells, 1, -1 do
        KTool.SafeDelete(self.tagCells[i].gameObject)
    end
    self.tagCells = nil
end



------------ TagCell ------------

return UIBattlingTipsPanel
