---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuguoqing.
--- DateTime: 2020/4/7 18:53
--- 主线章节选择——Item

------------ import ------------
local UIModule = CS.Engine.UI.UIModule
---@type ActionUtils
local ActionUtils = import('Game.UI.FightReady.UIMainChapter.ActionUtils')
local CountDownTime = 2592000 --30 * 86400 30天的秒数
local CDTimerModule = CS.Engine.Modules.CDTimerModule
local KTool = CS.Engine.Lib.KTool
---@type RedPointMgrComponent
local redPointCom = GameUtils.GetEntityCompByType(ECSComponentType.Constants.RedPointMgrComponent)
---@type IllustratedHandbookComponent
local illustratedHandbookComp = GameUtils.GetEntityCompByType(ECSComponentType.Constants.IllustratedHandbookComponent)
------------ import ------------

--- from: Assets/BundleResources/Prefabs/Action/ActionPrimaryMapDialog.prefab
---@class UIActionPrimaryMapNode
---@field Env                           	UIActionPrimaryMapNode                  
---@field controller                    	Engine.Modules.LuaBehaviour             
---@field ImgIcon2                      	UnityEngine.RectTransform               
---@field ImgIcon1                      	UnityEngine.RectTransform               
---@field AnimRoot                      	UnityEngine.RectTransform               
---@field HudNode                       	UnityEngine.RectTransform               
---@field TxtDescription2               	UnityEngine.RectTransform               @ 废弃了
---@field TxtName2                      	UnityEngine.RectTransform               
---@field ImgLv5                        	UnityEngine.RectTransform               @ 废弃了
---@field ImgLv4                        	UnityEngine.RectTransform               @ 废弃了
---@field ImgLv3                        	UnityEngine.RectTransform               @ 废弃了
---@field ImgLv2                        	UnityEngine.RectTransform               @ 废弃了
---@field ImgLv1                        	UnityEngine.RectTransform               @ 废弃了
---@field TxtTime                       	UnityEngine.RectTransform               
---@field TxtState                      	UnityEngine.RectTransform               @ 废弃了
---@field ImgMonsterHead                	UnityEngine.RectTransform               @ 废弃了
---@field TxtName                       	UnityEngine.RectTransform               
---@field TxtNumber                     	UnityEngine.RectTransform               @ 废弃了
---@field Close                         	UnityEngine.RectTransform               
---@field Open                          	UnityEngine.RectTransform               
---@field Root                          	UnityEngine.RectTransform               
local UIActionPrimaryMapNode = Class("UIActionPrimaryMapNode")
function UIActionPrimaryMapNode:__init()
    self._data = nil
    self._cb = nil
    self._timeDown = nil
    self.isIntroMode = false
end

function UIActionPrimaryMapNode:__delete()
    self._data = nil
    self._cb = nil
    self._timeDown = nil
    self.isIntroMode = nil
end

function UIActionPrimaryMapNode:Awake()
end

function UIActionPrimaryMapNode:Start()
    self.EventEVENT_VIP_ORDER_TIME_TICK = Events.AddListener(Constants.EventNames.EVENT_VIP_ORDER_TIME_TICK, Bind(self, self.OnSaleoutTimeChange))
    SetButtonAction(self.Root, Bind(self, self.OnBtnClick))
end

function UIActionPrimaryMapNode:Refresh(data, cb)
    if not data then
        return
    end

    if not isNull(self._timeDown) then
        CDTimerModule.GetInstance():RemoveCD(self._timeDown)
        self._timeDown = nil
    end
    self._cb = cb

    self._data = data

    self:FillSelf()
end

function UIActionPrimaryMapNode:IsRegionalTaskUnlocked()
    local t = ActionUtils.GetAllRegionSecondMapPointId(self._data.id)
    local taskPointVo
    for k, id in pairs(t) do
        local vo = ActionUtils.GetRegionSecondaryMapVo(checkNumber(id))
        if checkNumber(vo.type) == Constants.RegionSecondMapPointType.Task then
            taskPointVo = vo
        end
    end
    if isNull(taskPointVo) then
        print("二级区域地图表没找到任务点位")
        return
    end
    local vo = taskPointVo
    local isUnlock = GameUtils.IsUnlockedSingle(checkString(vo.unlockType), checkString(vo.unlockNum), checkString(vo.unlockId))
    return isUnlock, vo
end

function UIActionPrimaryMapNode:FillSelf()    
    local isUnlock, err = ActionUtils.IsUnlockRegionalPoint(self._data.id)
    CfUtils.SetActive(self.Open, isUnlock)
    CfUtils.SetActive(self.Close, not isUnlock)
    CfUtils.SetActive(self.HudNode, isUnlock)
    if isUnlock then
        local LvGroup = self.Open.transform:Find("LvGroup")
        if self.isIntroMode then
            CfUtils.FillText(self.TxtName, self._data.lable.." "..self._data.name)
            KTool.SetActive(LvGroup.gameObject, false)
        else
            local isUnlockTask = self:IsRegionalTaskUnlocked()
            KTool.SetActive(LvGroup.gameObject, isUnlockTask)
            if isUnlockTask then
                CfUtils.FillText(self.TxtName, self._data.lable.." "..self._data.name)
                local likabilityLevel = ActionUtils.GetRegionalPointLikabilityLevel(self._data.id)
                CfUtils.FillText(LvGroup:Find("TxtNumberShadow"), likabilityLevel)
                CfUtils.FillText(LvGroup:Find("TxtNumber"), likabilityLevel)

                ---实时pvp的处理
                local DestroyGroup = self.Open.transform:Find("DestroyGroup")
                if ActionUtils.IsRegionPointHaveLadderPvp(self._data.id) then
                    local isOpen = ActionUtils.IsLadderPvpUnlocked()
                    CfUtils.SetActive(DestroyGroup, isOpen)
                    if isOpen then
                        ---@type PlayerComponent
                        local playerComponent = GameUtils.GetOrAddEntityCompByType(ECSComponentType.Constants.PlayerComponent)
                        local serverTime = playerComponent.playerDojo:GetServerTime()
                        local isInLadderOpenTime, ladderEndTime = AppService:GetInstance():IsInLadderOpenTime(serverTime)
                        if isInLadderOpenTime then
                            ---设置滚动条的相关逻辑
                            ---@type UIActionPromptUpItemNode
                            local upItemNode = AddLuaBehaviour(DestroyGroup.gameObject, 'Game.UI.FightReady.UIMainChapter.UIActionPromptUpItemNode')
                            if upItemNode then
                                if isNull(upItemNode.Env) then
                                    upItemNode:Init()
                                end
                                if upItemNode.Env then

                                    upItemNode.Env.MaskText = DestroyGroup:Find("MaskState")
                                    upItemNode.Env.TxtDesc = DestroyGroup:Find("MaskState/TxtTime")
                                    upItemNode.Env:AddListener()
                                    upItemNode.Env:Refresh(localize('天梯竞技场进行中...距离结束: _time_', { _time_ = second_toHHMMSS(checkNumber(ladderEndTime) - serverTime) }))
                                end
                            end
                        else
                            CfUtils.SetActive(DestroyGroup, false)
                        end
                    end
                else
                    CfUtils.SetActive(DestroyGroup, false)
                end
            else
                ---未解锁区域任务时
                CfUtils.FillText(self.TxtName, self._data.lable.." "..self._data.name)
            end
        end
    else
        CfUtils.FillText(self.TxtName2, self._data.lable.."."..self._data.name)
        CfUtils.FillText(self.TxtDescription2, err)
    end

    if self.isIntroMode then
        if isUnlock then
            local encyDojo = illustratedHandbookComp:GetRegionMapEncyDojoMap()[tostring(self._data.id)]
            self:SwitchNewMark(encyDojo.isNewMark)
        end
        return
    end

    local isShow = checkNumber(self._data.regionSpecShow) == 1 and isUnlock
    --CfUtils.SetActive(self.HudNode, isShow)

    --if isShow then
        --local t = CfUtils.Split(self._data.infoCoordinate)
        --self.HudNode.anchoredPosition = Vector3(t[1], t[2], t[3])
        --CfUtils.FillImage(self.ImgIcon1, self._data.mapIcon)
        --CfUtils.FillImage(self.ImgIcon2, self._data.mapIcon)
    --end

    local lv, exp = ActionUtils.GetRegionalPointLikabilityLevel(self._data.id)
    CfUtils.FillText(self.Open.transform:Find("LvGroup/TxtNumber/TxtLevel"), "Lv."..lv)

    local isMax = ActionUtils.IsMaxLikabilityLevel(self._data.id)
    CfUtils.SetActive(self.Open.transform:Find("LvGroup/TxtNumberMax"), isMax)
    CfUtils.SetActive(self.Open.transform:Find("LvGroup/TxtNumberMaxShadow"), isMax)
    CfUtils.SetActive(self.Open.transform:Find("LvGroup/TxtNumber"), not isMax)
    CfUtils.SetActive(self.Open.transform:Find("LvGroup/TxtNumberShadow"), not isMax)

    if isMax then
    else
        local num1, num2 = ActionUtils.GetTaskNumBuyHomeData(self._data.id, lv)
        CfUtils.FillText(self.Open.transform:Find("LvGroup/TxtNumber"), num1.."/"..num2)
        CfUtils.FillText(self.Open.transform:Find("LvGroup/TxtNumberShadow"), num1.."/"..num2)
    end

    local redGo = GameUtils.GetRedPointGo(self.TxtName)
    GameUtils.BindRedPoint(Constants.RedPointConst["MaidCoffeeAreaMap"..self._data.id], redGo ,true,nil,function(node)
        local isCanDraw = ActionUtils.IsHasTaskCanDraw(self._data.id) or ActionUtils.IsShowMapRedpoint(self._data.id)
        if isCanDraw then
            CfUtils.SetActive(redGo, isCanDraw)
        else
            local data = ActionUtils.GetFishPointVo(self._data.id)
            local isShow
            if not isNull(data) then
                local num = redPointCom:GetNodeNum(Constants.RedPointConst["PhoneFishCollection"..data.content])
                isShow = (num > 0)
                CfUtils.SetActive(redGo, isShow)
            end
        end
    end)

    if not ActionUtils.IsHasTaskCanDraw(self._data.id) then
        if not isShow then
            self:SwitchNewMark(ActionUtils.IsShowMapRedpoint(self._data.id))
        end
    end
end

function UIActionPrimaryMapNode:SwitchNewMark(isShowNew)
    local imgNew = self.TxtName.transform:Find("ImgNew")
    CfUtils.SetActive(imgNew, checkBool(isShowNew))
end

--歼灭战信息
function UIActionPrimaryMapNode:FillAnnihilationInfo()
    local data = ActionUtils.GetAnnihilationInfo(self._data.id)
    if not data then
        return
    end

    local vo = ActionUtils.GetRegionAnnihilationTypeVo(data.bossTypeId)
    CfUtils.FillImage(self.ImgMonsterHead, vo.bossPortrait2)
    CfUtils.FillText(self.TxtState, localize("歼灭战发生中"))
    CfUtils.FillText(self.TxtTime, CfUtils.GetTimeHMS(data.remainTime))

    self._timeDown = CDTimerModule.GetInstance():AddCD(1, function(count, id)
        local data = ActionUtils.GetAnnihilationInfo(self._data.id)
        if checkNumber(data.remainTime) <= 0 then
            CfUtils.SetActive(self.Open.transform:Find("DestroyGroup"), false)
            if not isNull(self._timeDown) then
                CDTimerModule.GetInstance():RemoveCD(self._timeDown)
                self._timeDown = nil
            end
            return
        end
        CfUtils.FillText(self.TxtTime, CfUtils.GetTimeHMS(data.remainTime))
    end, CountDownTime, false, true)
end

function UIActionPrimaryMapNode:RefreshSaleout()
    self._isSaleout = true
    if not isNull(self._timeDown) then
        CDTimerModule.GetInstance():RemoveCD(self._timeDown)
        self._timeDown = nil
    end

    ---@type MaidCoffeePlayerComponent
    local maidCoffeePlayerComponent = GameUtils.GetEntityCompByType(ECSComponentType.Constants.MaidCoffeePlayerComponent)
    local time = 0
    if checkNumber(maidCoffeePlayerComponent.vipOrderId) > 0 then
        local refreshTime = checkNumber(maidCoffeePlayerComponent.vipOrderRefreshTime)
        if refreshTime > 0 then
            time = refreshTime
        end
    end
    self:FillSaleoutTime(time)
end

function UIActionPrimaryMapNode:FillSaleoutTime(time)
    if time > 0 then
        CfUtils.FillText(self.TxtTime, second_toHHMMSS(time))
    else
        CfUtils.FillText(self.TxtTime, "")
    end
end

function UIActionPrimaryMapNode:OnSaleoutTimeChange(time, id)
    if not self._isSaleout then
        return
    end 
    self:FillSaleoutTime(time)
end

function UIActionPrimaryMapNode:OnBtnClick()
    if not isNull(self._cb) then
        self._cb()
    end
end

function UIActionPrimaryMapNode:OnDestroy()
    if not isNull(self._timeDown) then
        CDTimerModule.GetInstance():RemoveCD(self._timeDown)
        self._timeDown = nil
    end
    Events.RemoveListener(Constants.EventNames.EVENT_VIP_ORDER_TIME_TICK, self.EventEVENT_VIP_ORDER_TIME_TICK)
    if not isNull(self._data) then
        GameUtils.RemoveRedPointCallBack(Constants.RedPointConst["MaidCoffeeAreaMap"..self._data.id])
    end

    self.controller = nil--luabehaviour 中CSharp对象
    self:Delete()
    self = nil
end

return UIActionPrimaryMapNode