---
--- Generated by
--- Created by boss.
--- DateTime: 2022/11/7 10:36
---

local UIModule = CS.Engine.UI.UIModule
---@type ActivityUtils
local ActivityUtils = import("Game.Activity.ActivityUtils")
--- from: Assets/BundleResources/Prefabs/Activity/ActivityFestiveBazaarDialog12003301.prefab > name: ActivityFestiveBazaarDialog12003301
---@class ChristmasEStoreEntry
---@field Env                            ChristmasEStoreEntry
---@field controller                        Engine.Modules.LuaBehaviour
---@field TextTime2                        UnityEngine.UI.Text                        @ 0
---@field BtnGroup                        UnityEngine.RectTransform                @ 1
---@field Text                            UnityEngine.RectTransform                @ 2
---@field StateGroup                        UnityEngine.RectTransform                @ 3
---@field TxtTime                        UnityEngine.RectTransform                @ 4
---@field TitleItem                        UnityEngine.RectTransform                @ 5
---@field Root                            UnityEngine.RectTransform                @ 6
---@field ImgTitle                        UnityEngine.RectTransform                @ 7
local ChristmasEStoreEntry = Class('ChristmasEStoreEntry')

local cs_coroutine = require('XLua.cs_coroutine')
local Yielders = CS.Engine.Lib.Yielders
function ChristmasEStoreEntry:__init()
    ---@type ActivityDojo
    self.activityDojo_ = nil
end

function ChristmasEStoreEntry:__delete()
    self.activityDojo_ = nil
end

function ChristmasEStoreEntry:Awake()
    SetButtonAction(self.BtnGroup, Bind(self, self.OnClickEntryButtonHandler_))
end

function ChristmasEStoreEntry:OnDestroy()
    self.controller = nil -- luaBehaviour 中 CSharp 对象
    self:Delete()
end

---@param actDojo ActivityDojo
function ChristmasEStoreEntry:Refresh(actDojo)
    if not actDojo then
        return
    end
    self.activityDojo_ = actDojo
    self:UpdateView_()
end

function ChristmasEStoreEntry:UpdateView_()
    CfUtils.SetActive(self.Root, false)
    -- update time
    CfUtils.FillText(self.TxtTime, ActivityUtils.ConventActivityDurationTime(self.activityDojo_.startTime, self.activityDojo_.endTime))

    -- update descr
    CfUtils.FillText(self.Text, self.activityDojo_.detail)
    local t = checkTable(self.activityDojo_.unlock)
    if table.count(t) > 0 then
        local vo = t[1]
        local isUnlock = GameUtils.IsUnlockedSingle(vo.targetType, vo.targetNum, vo.targetId)
        CfUtils.SetActive(self.TextTime2.transform.parent, isUnlock)
        if isUnlock then
            CfUtils.FillText(self.TextTime2, ActivityUtils.ConventLeftTimeText(self.activityDojo_.endTime))
        end
        --local entryLockGroupTrans = self.BtnEntry.transform.parent:Find("EntryLockGroup")
        --if entryLockGroupTrans then
        --    CfUtils.SetActive(entryLockGroupTrans, not isUnlock)
        --    local err = GameUtils.GetUnlockDescr(vo.targetType, vo.targetNum, vo.targetId)
        --    SetButtonAction(entryLockGroupTrans:Find("BtnEntryLock"), function()
        --        GameUtils.Toast(localize('_name_解锁', {_name_ = tostring(err)}))
        --    end)
        --    CfUtils.FillText(entryLockGroupTrans:Find("UnlockCondition/Text"),  localize('_name_解锁', {_name_ = tostring(err)}))
        --end
        --CfUtils.SetActive(self.BtnGroup, isUnlock)
    end
    CfUtils.SetActive(self.Root, true)
    local titleImgUrl = checkString(self.activityDojo_.titleImage)
    if string.len(titleImgUrl) > 0 then
        CfUtils.FillWebRawImage(self.ImgTitle, titleImgUrl)
    end
end

function ChristmasEStoreEntry:OnClickEntryButtonHandler_()
    if self.activityDojo_ then
        local t = checkTable(self.activityDojo_.unlock)
        if table.count(t) > 0 then
            local vo = t[1]
            local isUnlock = GameUtils.IsUnlockedSingle(vo.targetType, vo.targetNum, vo.targetId)
            if not isUnlock then
                local err = GameUtils.GetUnlockDescr(vo.targetType, vo.targetNum, vo.targetId)
                GameUtils.Toast(err)
                return
            end
        end
        if GameUtils.GetServerTime() >= checkNumber(self.activityDojo_.endTime) then
            GameUtils.Toast(localize("活动已结束"))
            return
        end
        CfUtils.DialogOpen(Constants.UITypeIds.UIActivityCommonShopDialog, {
            activityUuid = self.activityDojo_.id,
            mallBgImage = string.isEmpty(self.activityDojo_.mallBgImage) and 'Arts/Textures/UIBg/draw_celebration_shop_bg.png' or CfUtils.GetImageFullPath(self.activityDojo_.mallBgImage),
            topGoods = { self.activityDojo_.currency }
        }, {
            UIArgs(Constants.UITypeIds.UIActivityMainDialog)
        })
    else
        GameUtils.Toast(localize("活动不存在"))
    end
end
return ChristmasEStoreEntry
