---
--- Generated by shentayibu
--- Created by shentayibu.
--- DateTime: 2023/10/26 17:55
---

--region import
local util = require 'XLua.util'
local cs_coroutine = require 'XLua.cs_coroutine'
local CriWareUtils = import('Game.Entry.CriWareUtilsFix')
---@type ActivityNightCatMgr
local ActivityNightCatMgr = import('Game.Activity.NightCat.ActivityNightCatMgr'):GetInstance()
--endregion import

--region define
local KTool = CS.Engine.Lib.KTool
local CoWait = CS.Engine.Lib.CoWait
local Animator = CS.UnityEngine.Animator
local UIModule = CS.Engine.UI.UIModule
local Yielders = CS.Engine.Lib.Yielders
local WaitForSeconds = CS.UnityEngine.WaitForSeconds
local Debug = CS.UnityEngine.Debug
local UIRaycastBlocker = CS.Engine.UI.UIRaycastBlocker.Instance
local CDTimerModule = CS.Engine.Modules.CDTimerModule
--endregion define


--- Behavior生命周期：__init -> Awake -> Start -> OnDestroy -> __delete


--- from: Assets/BundleResources/Prefabs/NightCatInstance/NightCatInstanceMainDialog.prefab > name: RewardNode
---@class ActivityNightCatRewardNodeBehaviour
---@field Env                           	ActivityNightCatRewardNodeBehaviour     
---@field controller                    	Engine.Modules.LuaBehaviour             
---@field BtnWordNode                   	UnityEngine.RectTransform               
---@field CardInfor                     	UnityEngine.RectTransform               
---@field StatusHasReceived             	UnityEngine.RectTransform               
---@field StatusCanReceive              	UnityEngine.RectTransform               
---@field StatusNotAchieve              	UnityEngine.RectTransform               
local ActivityNightCatRewardNodeBehaviour = Class('ActivityNightCatRewardNodeBehaviour')

--region lifecycle

function ActivityNightCatRewardNodeBehaviour:__init()
    self.events = {}
    self.config = {
        status = {
            NotAchieve = 1,     --- 未获取
            CanReceive = 2,     --- 可领取
            HasReceive = 3      --- 已经领取
        }
    }
end

function ActivityNightCatRewardNodeBehaviour:__delete()
    self.events = nil
end

function ActivityNightCatRewardNodeBehaviour:Awake()

    SetButtonAction(self.BtnWordNode, Bind(self, self.OnClickBtnWordNodeHandler))
end

function ActivityNightCatRewardNodeBehaviour:Start()

end

function ActivityNightCatRewardNodeBehaviour:OnDestroy()
    for k, v in pairs(self.events) do
        Events.RemoveListener(k, v)
    end

    self.controller = nil --删除lua层引⽤到的c#对象否则不会产⽣c# gc回收到对象
    self:Delete()
    self = nil --lua层的gc需要
end
--endregion lifecycle

--region init
--endregion init

--region handler
function ActivityNightCatRewardNodeBehaviour:OnClickBtnWordNodeHandler()
    if self._status == self.config.status.HasReceive then
        GameUtils.ShowCommonTipsBoardRewardPreview(self.BtnWordNode, ActivityNightCatMgr:GetClearRewards(), localize('奖励预览:'), true, true)
    elseif self._status == self.config.status.NotAchieve then
        GameUtils.ShowCommonTipsBoardRewardPreview(self.BtnWordNode, ActivityNightCatMgr:GetClearRewards(), localize('奖励预览:'), false, true)
    else
        -- 领取奖励
        ActivityNightCatMgr:DrawRewardsReq(function()
            self:ReloadData()
        end)
    end
end
--endregion handler

--region public
function ActivityNightCatRewardNodeBehaviour:Refresh()

    self:ReloadData()
end
--endregion public

--region private
function ActivityNightCatRewardNodeBehaviour:ReloadData()

    local rewards = ActivityNightCatMgr:GetNightCatHomeDojo().activityConf.rewards
    --table.insert(rewards, {
    --    goodsId = 8610501,
    --    num = 1
    --})
    self.cardRewards = {}
    self.goodsRewards = {}
    for i, reward in ipairs(rewards) do
        local goodsId = reward.goodsId
        local type = GoodsUtils.GetIdType(goodsId)
        if type == Constants.IDType.RoleCardCustomize then
            table.insert(self.cardRewards, reward)
        else
            table.insert(self.goodsRewards, reward)
        end
    end

    --- 奖励的领取状态 0 未领取、1 已经领取
    self._drawStatus = ActivityNightCatMgr:GetClearanceRewardsState()
    --- 奖励是否已经解锁
    self._isUnlock = ActivityNightCatMgr:JudgeClearRewardUnlock()

    --self._drawStatus = 1
    if self._drawStatus == 1 then
        self._status = self.config.status.HasReceive
        goto loadDataEnd
        return
    end

    if self._isUnlock then
        self._status = self.config.status.CanReceive
    else
        self._status = self.config.status.NotAchieve
    end

    ::loadDataEnd::
    self:RefreshUI()
end

--endregion private

--region helper
function ActivityNightCatRewardNodeBehaviour:RefreshBtnWordNode()
    KTool.SetActive(self.StatusNotAchieve, self._status == self.config.status.NotAchieve)
    KTool.SetActive(self.StatusCanReceive, self._status == self.config.status.CanReceive)
    KTool.SetActive(self.StatusHasReceived, self._status == self.config.status.HasReceive)
    if self._status == self.config.status.NotAchieve then
        local animation = self.StatusNotAchieve:GetComponent(typeof(CS.UnityEngine.Animation))
        if isNotNull(animation) then
            animation:PlayQueued("NightCatInstanceMainDialogReward1Open", CS.UnityEngine.QueueMode.CompleteOthers)
            animation:PlayQueued('NightCatInstanceMainDialogReward1Idle', CS.UnityEngine.QueueMode.CompleteOthers)
        end
    elseif self._status == self.config.status.CanReceive then
        local animation = self.StatusCanReceive:GetComponent(typeof(CS.UnityEngine.Animation))
        if isNotNull(animation) then
            animation:PlayQueued('NightCatInstanceMainDialogReward2Open', CS.UnityEngine.QueueMode.CompleteOthers)
            animation:PlayQueued('NightCatInstanceMainDialogReward2Loop', CS.UnityEngine.QueueMode.CompleteOthers)
        end
    elseif self._status == self.config.status.HasReceive then
        local animation = self.StatusHasReceived:GetComponent(typeof(CS.UnityEngine.Animation))
        if isNotNull(animation) then
            animation:PlayQueued('NightCatInstanceMainDialogReward1Open', CS.UnityEngine.QueueMode.CompleteOthers)
            animation:PlayQueued('NightCatInstanceMainDialogReward1Idle', CS.UnityEngine.QueueMode.CompleteOthers)
        end
    end
end

function ActivityNightCatRewardNodeBehaviour:RefreshCardInfo()
    local count = table.count(self.cardRewards)
    if count <= 0 then
        CfUtils.SetActive(self.CardInfor, false)
        return
    end

    ---@type ActivityNightCatCardInfoBehaviour
    local scr = CfUtils.GetLuaScr(self.CardInfor, "Game.Activity.NightCat.MainDialog.ActivityNightCatCardInfoBehaviour")
    scr:Refresh(self._status, self.cardRewards)
end

function ActivityNightCatRewardNodeBehaviour:RefreshUI()
    self:RefreshBtnWordNode()
    self:RefreshCardInfo()
end
--endregion helper

return ActivityNightCatRewardNodeBehaviour
