local avg_110108Table = {
                [1] = {
                        id = 1,
                        type = 5,
                        title = "PlotAction",
                        showCharacter = 1,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [2] = {
                        id = 2,
                        type = 4,
                        title = "scene_sea_day",
                        showCharacter = nil,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [3] = {
                        id = 3,
                        type = 1,
                        title = "基德",
                        showCharacter = 10002,
                        left = nil,
                        center = 10002,
                        right = nil,
                        action = "基德_星星笑",
                        content = "哼，易如反掌。",
                        voice = 102037,
                },

                [4] = {
                        id = 4,
                        type = 1,
                        title = "吕佐夫",
                        showCharacter = 10003,
                        left = 10003,
                        center = nil,
                        right = 10002,
                        action = "吕佐夫_笑",
                        content = "嗯嗯！基德也很努力了，好孩子好孩子~",
                        voice = nil,
                },

                [5] = {
                        id = 5,
                        type = 12,
                        title = 2,
                        showCharacter = 10002,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = 0.2,
                        content = 100,
                        voice = nil,
                },

                [6] = {
                        id = 6,
                        type = 1,
                        title = "基德",
                        showCharacter = 10002,
                        left = 10003,
                        center = nil,
                        right = 10002,
                        action = "基德_耸肩悲伤",
                        content = "等等，你干什么副官——咕！别、别摸基德大人的头！",
                        voice = 102043,
                },

                [7] = {
                        id = 7,
                        type = 1,
                        titleCensored = "瑾",
                        title = "明石",
                        showCharacter = 10004,
                        left = 10004,
                        center = nil,
                        right = 10002,
                        action = "明石_默认",
                        content = "怎么样？基德，还要继续比试吗？",
                        voice = 104039,
                },

                [8] = {
                        id = 8,
                        type = 1,
                        title = "基德",
                        showCharacter = 10002,
                        left = 10004,
                        center = nil,
                        right = 10002,
                        action = nil,
                        content = "还想比？就凭你们的能耐，要不是深海打搅，我早就——",
                        voice = nil,
                },

                [9] = {
                        id = 9,
                        type = 20,
                        title = "基德",
                        showCharacter = 10002,
                        left = 10004,
                        center = nil,
                        right = 10002,
                        action = nil,
                        content = "……",
                        voice = nil,
                },

                [10] = {
                        id = 10,
                        type = 20,
                        title = "基德",
                        showCharacter = 10002,
                        left = 10004,
                        center = nil,
                        right = 10002,
                        action = nil,
                        content = "（仔细一看，她们拿到的标志物，也并没有比我少太多……）",
                        voice = nil,
                },

                [11] = {
                        id = 11,
                        type = 20,
                        title = "基德",
                        showCharacter = 10002,
                        left = 10004,
                        center = nil,
                        right = 10002,
                        action = nil,
                        content = "（这还是我拜托吕佐夫拖延她们，外加遇到了深海捣乱的结果，要是，从一开始就全力比试的话……）",
                        voice = nil,
                },

                [12] = {
                        id = 12,
                        type = 1,
                        title = "基德",
                        showCharacter = 10002,
                        left = 10004,
                        center = nil,
                        right = 10002,
                        action = "基德_默认",
                        content = "这次，就算平手好了。",
                        voice = 102050,
                },

                [13] = {
                        id = 13,
                        type = 13,
                        title = "我",
                        showCharacter = nil,
                        left = 10004,
                        center = nil,
                        right = 10002,
                        action = nil,
                        content = "平手吗……",
                        voice = nil,
                },

                [14] = {
                        id = 14,
                        type = 1,
                        title = "基德",
                        showCharacter = 10002,
                        left = 10004,
                        center = nil,
                        right = 10002,
                        action = nil,
                        content = "虽然和我比还是差一些，不过，我认可你的实力了，指挥官。",
                        voice = nil,
                },

                [15] = {
                        id = 15,
                        type = 1,
                        title = "基德",
                        showCharacter = 10002,
                        left = 10004,
                        center = nil,
                        right = 10002,
                        action = "基德_笑",
                        content = "走了！吕佐夫，等我找到了“金银岛”的宝藏，我会邀你一起进行探险的，指挥官船长。",
                        voice = nil,
                },

                [16] = {
                        id = 16,
                        type = 1,
                        title = "吕佐夫",
                        showCharacter = 10003,
                        left = 10003,
                        center = nil,
                        right = 10002,
                        action = "吕佐夫_斜眼",
                        content = "嗯……基德？",
                        voice = 103061,
                },

                [17] = {
                        id = 17,
                        type = 1,
                        title = "基德",
                        showCharacter = 10002,
                        left = 10003,
                        center = nil,
                        right = 10002,
                        action = nil,
                        content = "嗯？干什么？",
                        voice = nil,
                },

                [18] = {
                        id = 18,
                        type = 1,
                        title = "吕佐夫",
                        showCharacter = 10003,
                        left = 10003,
                        center = nil,
                        right = 10002,
                        action = nil,
                        content = "我啊，会和指挥官他们一起回避风港去。",
                        voice = nil,
                },

                [19] = {
                        id = 19,
                        type = 1,
                        title = "基德",
                        showCharacter = 10002,
                        left = 10003,
                        center = nil,
                        right = 10002,
                        action = "基德_悲伤",
                        content = "啊？你在说什么傻话？我们不是说好了一起——",
                        voice = 102033,
                },

                [20] = {
                        id = 20,
                        type = 1,
                        title = "吕佐夫",
                        showCharacter = 10003,
                        left = 10003,
                        center = nil,
                        right = 10002,
                        action = nil,
                        content = "对不起，基德，但是，我觉得……",
                        voice = nil,
                },

                [21] = {
                        id = 21,
                        type = 1,
                        title = "吕佐夫",
                        showCharacter = 10003,
                        left = 10003,
                        center = nil,
                        right = 10002,
                        action = nil,
                        content = "我们不能再继续这样了。",
                        voice = nil,
                },

                [22] = {
                        id = 22,
                        type = 1,
                        title = "基德",
                        showCharacter = 10002,
                        left = 10003,
                        center = nil,
                        right = 10002,
                        action = nil,
                        content = "继续这样？“这样”是什么意思？",
                        voice = nil,
                },

                [23] = {
                        id = 23,
                        type = 1,
                        title = "吕佐夫",
                        showCharacter = 10003,
                        left = 10003,
                        center = nil,
                        right = 10002,
                        action = nil,
                        content = "我们是军人，必须履行军人的义务。",
                        voice = nil,
                },

                [24] = {
                        id = 24,
                        type = 12,
                        title = 1,
                        showCharacter = 10002,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = 0.07,
                        content = 100,
                        voice = nil,
                },

                [25] = {
                        id = 25,
                        type = 1,
                        title = "基德",
                        showCharacter = 10002,
                        left = 10003,
                        center = nil,
                        right = 10002,
                        action = nil,
                        content = "我……有没有履行军人的义务，你难道不清楚吗？",
                        voice = nil,
                },

                [26] = {
                        id = 26,
                        type = 1,
                        title = "吕佐夫",
                        showCharacter = 10003,
                        left = 10003,
                        center = nil,
                        right = 10002,
                        action = nil,
                        content = "是这样，无论是和你一起战斗，还是一起寻宝都很开心，但是……",
                        voice = 103060,
                },

                [27] = {
                        id = 27,
                        type = 20,
                        title = "基德",
                        showCharacter = 10002,
                        left = 10003,
                        center = nil,
                        right = 10002,
                        action = nil,
                        content = "……",
                        voice = nil,
                },

                [28] = {
                        id = 28,
                        type = 12,
                        title = 2,
                        showCharacter = 10002,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = 0.2,
                        content = 100,
                        voice = nil,
                },

                [29] = {
                        id = 29,
                        type = 1,
                        title = "基德",
                        showCharacter = 10002,
                        left = 10003,
                        center = nil,
                        right = 10002,
                        action = "基德_闭眼",
                        content = "唔唔唔……我知道了！其实你是根本不相信我能找到“金银岛”，所以才这样说对吧！",
                        voice = 102056,
                },

                [30] = {
                        id = 30,
                        type = 1,
                        title = "吕佐夫",
                        showCharacter = 10003,
                        left = 10003,
                        center = nil,
                        right = 10002,
                        action = "吕佐夫_害怕",
                        content = "诶？这个……",
                        voice = 103058,
                },

                [31] = {
                        id = 31,
                        type = 6,
                        title = nil,
                        showCharacter = 0.5,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [32] = {
                        id = 32,
                        type = 17,
                        title = nil,
                        showCharacter = 1,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [33] = {
                        id = 33,
                        type = 1,
                        title = "基德",
                        showCharacter = 10002,
                        left = 10003,
                        center = nil,
                        right = 10002,
                        action = nil,
                        content = "<size=37>哼！我才不需要你！</size>",
                        voice = nil,
                },

                [34] = {
                        id = 34,
                        type = 1,
                        title = "基德",
                        showCharacter = 10002,
                        left = 10003,
                        center = nil,
                        right = 10002,
                        action = "基德_生气",
                        content = "你被开除了，副官！等我找到宝藏之后，就算你哭着求我我也不会分你一份的。",
                        voice = nil,
                },

                [35] = {
                        id = 35,
                        type = 12,
                        title = 4,
                        showCharacter = 10002,
                        left = 1,
                        center = 10000,
                        right = nil,
                        action = 1,
                        content = nil,
                        voice = nil,
                },

                [36] = {
                        id = 36,
                        type = 13,
                        title = "我",
                        showCharacter = nil,
                        left = nil,
                        center = 10003,
                        right = nil,
                        action = nil,
                        content = "等等——基德！",
                        voice = nil,
                },

                [37] = {
                        id = 37,
                        type = 1,
                        title = "重庆",
                        showCharacter = 10006,
                        left = 10006,
                        center = 10003,
                        right = nil,
                        action = "重庆_悲伤",
                        content = "啊，跑远了……",
                        voice = 106058,
                },

                [38] = {
                        id = 38,
                        type = 18,
                        title = nil,
                        showCharacter = 1,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = nil,
                        voice = nil,
                },

                [39] = {
                        id = 39,
                        type = 1,
                        titleCensored = "瑾",
                        title = "明石",
                        showCharacter = 10004,
                        left = 10006,
                        center = 10003,
                        right = 10004,
                        action = "明石_闭眼",
                        content = "这群驱逐舰……跑又跑不过，追又追不上……",
                        voice = nil,
                },

                [40] = {
                        id = 40,
                        type = 20,
                        title = "吕佐夫",
                        showCharacter = 10003,
                        left = 10006,
                        center = 10003,
                        right = 10004,
                        action = "吕佐夫_斜眼",
                        content = "……",
                        voice = nil,
                },

                [41] = {
                        id = 41,
                        type = 1,
                        titleCensored = "瑾",
                        title = "明石",
                        showCharacter = 10004,
                        left = 10006,
                        center = 10003,
                        right = 10004,
                        action = "明石_默认",
                        content = "别担心，那孩子肯定也明白是非，给她点时间让她冷静下，我们再去找她吧。",
                        voice = nil,
                },

                [42] = {
                        id = 42,
                        type = 1,
                        title = "吕佐夫",
                        showCharacter = 10003,
                        left = 10006,
                        center = 10003,
                        right = 10004,
                        action = nil,
                        content = "……嗯。",
                        voice = nil,
                },

                [43] = {
                        id = 43,
                        type = 1,
                        title = "吕佐夫",
                        showCharacter = 10003,
                        left = 10006,
                        center = 10003,
                        right = 10004,
                        action = "吕佐夫_默认",
                        content = "那，指挥官。",
                        voice = 103042,
                },

                [44] = {
                        id = 44,
                        type = 1,
                        title = "吕佐夫",
                        showCharacter = 10003,
                        left = 10006,
                        center = 10003,
                        right = 10004,
                        action = nil,
                        content = "战列巡洋舰吕佐夫，正式归队了。",
                        voice = nil,
                },

                [45] = {
                        id = 45,
                        type = 13,
                        title = "我",
                        showCharacter = nil,
                        left = 10006,
                        center = 10003,
                        right = 10004,
                        action = nil,
                        content = "欢迎，吕佐夫，忙活了一天，赶快回基地修整吧。",
                        voice = nil,
                },

                [46] = {
                        id = 46,
                        type = 12,
                        title = 1,
                        showCharacter = 10003,
                        left = nil,
                        center = nil,
                        right = nil,
                        action = nil,
                        content = -100,
                        voice = nil,
                },

                [47] = {
                        id = 47,
                        type = 1,
                        title = "吕佐夫",
                        showCharacter = 10003,
                        left = 10006,
                        center = 10003,
                        right = 10004,
                        action = nil,
                        content = "是。",
                        voice = nil,
                },

}
return avg_110108Table