<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>GameFramework</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>Download/DLL/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>Download/DLL/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="UniTask">
      <HintPath>Download/DLL/UniTask.dll</HintPath>
    </Reference>
    <Reference Include="YooAsset" />
    <Reference Include="ZString">
      <HintPath>Download/DLL/ZString.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>