return {
  unitList = {
    {
      Rotate = 45.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = false,
      Camp = 4,
      UnitID = 20101501,
      InitPos = "M2",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_1015306_0",
      AutoLevel = 0,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = false,
      Camp = 4,
      UnitID = 20101501,
      InitPos = "M3",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_1015306_1",
      AutoLevel = 0,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 135.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = false,
      Camp = 4,
      UnitID = 20101501,
      InitPos = "M4",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_1015306_2",
      AutoLevel = 0,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = -45.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = false,
      Camp = 4,
      UnitID = 20101401,
      InitPos = "M5",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_1015306_3",
      AutoLevel = 0,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = false,
      Camp = 4,
      UnitID = 20101401,
      InitPos = "M6",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_1015306_4",
      AutoLevel = 0,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = false,
      Camp = 4,
      UnitID = 20101401,
      InitPos = "M7",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_1015306_5",
      AutoLevel = 0,
      Delay = 0.0,
      MagicId = 0
    }
  },
  Name = "",
  Id = 1015306,
  Type = 0
}
