return {
  unitList = {
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20102801,
      InitPos = "E1",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_2050504_0",
      AutoLevel = 2,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20102801,
      InitPos = "E2",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_2050504_1",
      AutoLevel = 2,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 0.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = true,
      Camp = 4,
      UnitID = 20101201,
      InitPos = "E3",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_2050504_2",
      AutoLevel = 2,
      Delay = 0.0,
      MagicId = 0
    }
  },
  Name = "",
  Id = 2050504,
  Type = 0
}
