return {
  unitList = {
    {
      Rotate = 180.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = false,
      Camp = 4,
      UnitID = 20103706,
      InitPos = "M2",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_29211_0",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 90.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = false,
      Camp = 4,
      UnitID = 20103706,
      InitPos = "M3",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_29211_1",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 0
    },
    {
      Rotate = 270.0,
      IsEdit = true,
      IsShow = false,
      IsNoUse = false,
      IsLookAtRole = false,
      Camp = 4,
      UnitID = 20103706,
      InitPos = "M4",
      OffSetX = 0.0,
      OffSetZ = 0.0,
      Level = 0,
      IsChange = false,
      UnitKey = "0_29211_2",
      AutoLevel = 1,
      Delay = 0.0,
      MagicId = 0
    }
  },
  Name = "",
  Id = 29211,
  Type = 0
}
