local config = {
  ui_story_31870401_1_dialog_content = "Ah, PlayerName, finalmente estás aquí.",
  ui_story_31870401_2_dialog_content = "Squawk ha estado muy preocupado desde que Jabber desapareció.",
  ui_story_31870401_3_dialog_content = "¡Graznido! ¡Más comida para mí!",
  ui_story_31870401_4_dialog_content = "Entiendo que el nombre de este estornino es ¿Graznido?",
  ui_story_31870401_5_dialog_content = "No parece especialmente preocupado...",
  ui_story_31870401_6_dialog_content = "Oh, Squawk solo está diciendo tonterías otra vez. No lo escuches.",
  ui_story_31870401_7_dialog_content = "No, ¡estás diciendo tonterías! ¡Graznido!",
  ui_story_31870401_8_dialog_content = "¡Silencio, tú! De todos modos, Jabber es mi otro estornino, uno que se parece a Squawk.",
  ui_story_31870401_9_dialog_content = "Entonces, ¿lo has visto por aquí?",
  ui_story_31870401_10_dialog_content = "Eh... no puedo recordar realmente.",
  ui_story_31870401_11_dialog_content = "Quizás podamos empezar recordando dónde lo perdiste.",
  ui_story_31870401_12_dialog_content = "¿Dónde has estado y qué has estado haciendo en los últimos dos días?",
  ui_story_31870401_13_dialog_content = "Bueno, ahora que lo mencionas, visité muchos lugares en ese período de tiempo.",
  ui_story_31870401_14_dialog_content = "Estoy en medio de un viaje por todo Astra, recolectando todo tipo de chismes e historias extrañas...",
  ui_story_31870401_15_dialog_content = "Y utilizándolos para completar el tercer capítulo del <color=#FFB400>\"Pergamino de la Ascensión Divina.\"</color>",
  ui_story_31870401_16_dialog_content = "¿El \"Pergamino de la Ascensión Divina\"? Suena bastante complicado.",
  ui_story_31870401_17_dialog_content = "Es natural, teniendo en cuenta que esta obra misteriosa me fue dada por una persona aún más misteriosa.",
  ui_story_31870401_18_dialog_content = "El primer capítulo está compuesto de <color=#FFB400>toda clase de extrañas y antiguas leyendas</color> de todo el mundo.",
  ui_story_31870401_19_dialog_content = "El segundo capítulo está lleno de <color=#FFB400>escrituras y símbolos misteriosos</color>, todos ellos completamente incomprensibles...",
  ui_story_31870401_20_dialog_content = "¡Eso suena genial! ¿Qué pasa con el tercer capítulo?",
  ui_story_31870401_21_dialog_content = "El tercer capítulo... es una colección de <color=#FFB400>historias extrañas y rumores</color> recopilados por un servidor!",
  ui_story_31870401_22_dialog_content = "Y me reservo todos los derechos para la explicación final de su contenido.",
  ui_story_31870401_23_dialog_content = "(De alguna manera siento que esto no le hace justicia al pergamino...)",
  ui_story_31870401_24_dialog_content = "Aun así, me gustaría que lo leyeras por ti mismo. Ver para creer, después de todo.",
  ui_story_31870401_25_dialog_content = "Solo hay una línea de texto en cada página del tercer capítulo, así que siéntete libre de echarle un vistazo.",
  ui_story_31870401_26_dialog_content = "Bien, veamos...",
  ui_story_31870401_27_dialog_content = "<size=50>\"¿Preparativos secretos para reemplazar al Gran Mariscal están en marcha?!\"</size>",
  ui_story_31870401_28_dialog_content = "Esta parte significa que cierta Comandante Illumina de cabello rosa ha estado imitando secretamente la escritura del Gran Mariscal, entre otras cosas.",
  ui_story_31870401_29_dialog_content = "Y... <size=50>¿\"Los asuntos secretos de la corte real de Northland son expuestos\"?</size>",
  ui_story_31870401_30_dialog_content = "Ah, sí, esta parte. Solo significa que la reina de Northland tiene tendencia a hablar dormida, entre otras cosas.",
  ui_story_31870401_31_dialog_content = "... ¡Nunca he oído hablar de ninguna de estas cosas! ¿Y por qué las haces sonar mucho más sensacionales de lo que realmente son?!",
  ui_story_31870401_32_dialog_content = "De todos modos, ya deberías estar bastante familiarizado con Astra después de haber visitado tantos lugares, ¿verdad?",
  ui_story_31870401_33_dialog_content = "Mis viajes son simplemente parte de mi trabajo. Mi conocimiento de esta tierra no se compara con el tuyo, estoy seguro.",
  ui_story_31870401_34_dialog_content = "En los últimos dos días, volví a visitar <color=#FFB400>Bahía Twin Pavilions</color>, el <color=#FFB400>Desierto de Rediesel</color> y <color=#FFB400>Umbraton</color> para escuchar los últimos chismes.",
  ui_story_31870401_35_dialog_content = "¿Conoces alguno de estos lugares?",
  ui_story_31870401_36_dialog_content = "Estoy seguro de que alguien como tú debe tener alguna técnica <color=#FFB400>especial</color> para encontrar pájaros, ¿verdad?",
  ui_story_31870401_37_dialog_content = "¿Cómo iba a saberlo? No estaba contigo cuando...",
  ui_story_31870401_38_dialog_content = "¡Espera, lo tengo!",
  ui_story_31870401_39_option_content = "Usa habilidades psíquicas",
  ui_story_31870401_40_dialog_content = "Puedo usar mis poderes para ver tus recuerdos basándome en el contenido de estas tres páginas.",
  ui_story_31870401_41_dialog_content = "Tal vez pueda encontrar algunas pistas que nos lleven a Jabber.",
  ui_story_31870401_42_option_content = "Ponte en contacto con las partes involucradas en los chismes",
  ui_story_31870401_43_dialog_content = "Eso no servirá, me temo. Como viajero recolector de rumores del mundo, siempre me lavo las manos de asuntos viejos cuando termino mi trabajo.",
  ui_story_31870401_44_dialog_content = "Ya estoy lo suficientemente agradecido de que las partes involucradas no hayan intentado perseguirme. ¿Cómo podría contactarlos?",
  ui_story_31870401_45_dialog_content = "Ya veo... Supongo que tendré que usar mis poderes psíquicos, ¿verdad?",
  ui_story_31870401_46_dialog_content = "Sabía que eras la persona adecuada para llamar.",
  ui_story_31870401_47_dialog_content = "Ahora bien, ¿podrías comenzar con mis recuerdos de Twin Pavilions Bay, por favor?",
  ui_story_31870401_48_dialog_content = "De acuerdo, la parte sobre Twin Pavilions Bay debería ser... <color=#FFB400>\"¿Las tendencias sospechosas del capitán del Shadowind?!\"</color>",
  ui_story_31870401_49_option_content = "¡Potencia de fuerza!",
  ui_story_31870401_50_dialog_content = "Oye, ¿soy yo o el Capitán Yuebai ha estado actuando raro últimamente?",
  ui_story_31870401_51_dialog_content = "Entiendo lo que dices. Estos últimos días se ha estado yendo sola y luego revisa su ropa cada vez que regresa a la nave.",
  ui_story_31870401_52_dialog_content = "Probablemente esté asegurándose de que no haya nada pegado a su ropa. Aprendí hace mucho tiempo que Umbraton está lleno de gente buena y mala...",
  ui_story_31870401_53_dialog_content = "Oye, ¿crees que es posible que la hayan comprado para ser informante de ese jefe de pandilla?",
  ui_story_31870401_54_dialog_content = "¡Shh! ¡Shh!",
  ui_story_31870401_55_dialog_content = "…",
  ui_story_31870401_56_dialog_content = "¡¡C-Capitán Yuebai!!",
  ui_story_31870401_57_dialog_content = "¿Oh? ¿Huelo algún chisme jugoso?",
  ui_story_31870401_58_dialog_content = "¡Yuebai se va!",
  ui_story_31870401_59_dialog_content = "¡Síguela! ¡Síguela!",
  ui_story_31870401_60_dialog_content = "Lo sé, lo sé! ¡Ahora cálmate!",
  ui_story_31870401_61_dialog_content = "<color=#e8d9bb>Bahía de Twin Pavilions</color>",
  ui_story_31870401_62_dialog_content = "…",
  ui_story_31870401_63_dialog_content = "Parece tener miedo de ser notada. ¿Qué diablos podría estar haciendo?",
  ui_story_31870401_64_dialog_content = "¡Ella está entrando a una tienda!",
  ui_story_31870401_65_dialog_content = "¡Es una taberna!",
  ui_story_31870401_66_dialog_content = "¿Es esta una de esas tabernas utilizadas para reuniones clandestinas...?",
  ui_story_31870401_67_dialog_content = "¡¿Urgh?!",
  ui_story_31870401_68_dialog_content = "Eww, ¡qué hedor tan horrible!",
  ui_story_31870401_69_dialog_content = "¡Vengan todos! Prueben nuestros deliciosos <color=#FFB400>fideos de caracol</color>, ¡nuestro nuevo producto directamente desde el este!",
  ui_story_31870401_70_dialog_content = "A pesar del olor, una delicia sabrosa; ¡un bocado te transportará de vuelta a Longzhou!",
  ui_story_31870401_71_dialog_content = "Lo de siempre, por favor.",
  ui_story_31870401_72_dialog_content = "¡Entendido! Un tazón de fideos de caracol extra picantes con el doble de caracoles y sin brotes de bambú encurtidos, ¡enseguida! ¡Ven a sentarte, amigo!",
  ui_story_31870401_73_dialog_content = "Ahhh, simplemente no se pueden olvidar los aromas de la cocina de nuestra tierra.",
  ui_story_31870401_74_dialog_content = "(Entonces el secreto de Yuebai es que le gusta salir a escondidas a comer fideos de caracol...)",
  ui_story_31870401_75_dialog_content = "(Espera, ¿qué estoy haciendo? ¡Se supone que debo buscar a Jabber!)",
  ui_story_31870401_76_dialog_content = "Aun así, Farfullar estuvo contigo en esta memoria de principio a fin.",
  ui_story_31870401_77_dialog_content = "Creo que es seguro decir que no lo perdiste en Twin Pavilions Bay.",
  ui_story_31870401_78_dialog_content = "Ya veo. No tenía idea de que tus poderes psíquicos te permitieran ver las cosas tan claramente.",
  ui_story_31870401_79_dialog_content = "Ahora, por favor pasa a la siguiente página y ayúdame a buscar de nuevo.",
  ui_story_31870401_80_dialog_content = "No hay problema. La siguiente página trata sobre... <color=#FFB400>\"El pasado y presente de la vida de Lepidoz\"?!</color>",
  ui_story_31870401_81_option_content = "¡Potencia de fuerza!",
  ui_story_31870401_82_dialog_content = "<color=#e8d9bb>Desierto de Rediesel</color>",
  ui_story_31870401_83_dialog_content = "¿Nunca te tomas un descanso?!",
  ui_story_31870401_84_dialog_content = "¡También necesitamos comida y descanso!",
  ui_story_31870401_85_dialog_content = "¡Muestren modales, ustedes dos! ¡Les he estado dando mucha fruta durante todo este viaje!",
  ui_story_31870401_86_dialog_content = "Ahora que tenemos un chisme jugoso sobre Yuebai, necesitamos maximizar su valor lo más pronto posible.",
  ui_story_31870401_87_dialog_content = "Siempre me han fascinado los Colosos de esta tierra.",
  ui_story_31870401_88_dialog_content = "Soroz—",
  ui_story_31870401_89_dialog_content = "Lepidoz—",
  ui_story_31870401_90_dialog_content = "Y el barco mercante sería—",
  ui_story_31870401_91_dialog_content = "¡Sombráz!",
  ui_story_31870401_92_dialog_content = "¿Barco mercante? ¿Qué barco mercante?",
  ui_story_31870401_93_dialog_content = "Ah sí, y a veces las respuestas que buscamos vienen caminando directamente hacia nosotros.",
  ui_story_31870401_94_dialog_content = "¿Eh? No tengo idea de lo que estás hablando, pero ¿estás aquí para unirte a Rediesel Wrench?",
  ui_story_31870401_95_dialog_content = "No, simplemente tengo el máximo respeto y admiración por el líder de Rediesel Wrench, por eso he venido aquí para informar sobre nueva información.",
  ui_story_31870401_96_dialog_content = "Hablas de manera graciosa, ¿lo sabes? Además, ¿qué tiene de especial Sinsa?",
  ui_story_31870401_97_dialog_content = "(Uh-oh, parece que estoy halagando a la persona equivocada...)",
  ui_story_31870401_98_dialog_content = "(¡Tendré que ajustar mi enfoque según lo que él dijo!)",
  ui_story_31870401_99_dialog_content = "Sabes, viendo lo grande y poderoso que pareces ser, estoy seguro de que tu líder confía en ti con muchos de sus secretos, ¿verdad?",
  ui_story_31870401_100_dialog_content = "¡Tienes buen ojo, amigo! ¡Resulta que soy el tipo más fuerte de todo Rediesel Wrench!",
  ui_story_31870401_101_dialog_content = "Pero, eh... ¿Qué tipo de secretos estás mencionando?",
  ui_story_31870401_102_dialog_content = "Actualmente tengo un chisme increíble relacionado con el capitán de un barco mercante de la familia Lin. ¿Estarías interesado en intercambiar detalles sobre la existencia de Lepidoz por eso?",
  ui_story_31870401_103_dialog_content = "Lepidoz, ¿eh? Sinsa simplemente lo encontró y luego lo modificó muchísimo.",
  ui_story_31870401_104_dialog_content = "No es realmente un secreto, teniendo en cuenta que a la gente aquí le encanta reutilizar objetos viejos como ese.",
  ui_story_31870401_105_dialog_content = "En cuanto a dónde encontramos Lepidoz, tampoco me importa decirte: ¡casi todo lo que recolectamos viene directamente de <color=#FFB400>la basura</color>! ¡Viva la Rediesel Wrench!",
  ui_story_31870401_106_dialog_content = "¿Basura?",
  ui_story_31870401_107_dialog_content = "¡Así es! Ya sea un gran Colossus al lado de la carretera o un coche destrozado... ¡Todo vale aquí!",
  ui_story_31870401_108_dialog_content = "Después de todo, ¡la libertad es de lo que se trata todo!",
  ui_story_31870401_109_dialog_content = "Eso me recuerda... ¿De qué barco mercante estabas hablando? ¿Es uno de los barcos atracados en el puerto continental?",
  ui_story_31870401_110_dialog_content = "¡Esto no es bueno!",
  ui_story_31870401_111_dialog_content = "¡Corre corre!",
  ui_story_31870401_112_dialog_content = "¡Jajaja! ¡Lo siento, pero debo irme ahora! ¡Hasta la próxima, hermano!",
  ui_story_31870401_113_dialog_content = "En ese momento, también fue un gran shock para mí.",
  ui_story_31870401_114_dialog_content = "(Entonces Sinsa fue quien modificó a Lepidoz...)",
  ui_story_31870401_115_dialog_content = "(¡Argh, concéntrate! ¡Se supone que debo buscar a Farfullar!)",
  ui_story_31870401_116_dialog_content = "Farfullar también estuvo presente en esta memoria todo el tiempo.",
  ui_story_31870401_117_dialog_content = "Su grito sonó igual de incómodo que el tuyo.",
  ui_story_31870401_118_dialog_content = "Me sorprende que tus poderes psíquicos también te permitan sentir los sentimientos de tu objetivo...",
  ui_story_31870401_119_dialog_content = "Sé lo que vas a decir. Pasar a la siguiente página, ¿verdad?",
  ui_story_31870401_120_dialog_content = "¡Sí, por favor! Eres un adivino en tu propio derecho, ¿sabes?",
  ui_story_31870401_121_dialog_content = "Está bien, ahora para la última página: <color=#FFB400>\"¿La gran revelación del cumpleaños de la princesa Zhuohua?\"</color>",
  ui_story_31870401_122_option_content = "¡Potencia de fuerza!",
  ui_story_31870401_123_dialog_content = "Parece que los rumores en torno a Yuebai han disminuido más o menos ahora.",
  ui_story_31870401_124_dialog_content = "Aunque he derramado mi sangre, sudor y lágrimas en esta tarea, no puedo evitar sentirme un poco aburrido por ella.",
  ui_story_31870401_125_dialog_content = "¡Presume de ello, por qué no lo haces?!",
  ui_story_31870401_126_dialog_content = "¡Vaya, qué humilde!",
  ui_story_31870401_127_dialog_content = "Ugh, todos sus graznidos incesantes realmente dificultan el poder calmarse.",
  ui_story_31870401_128_dialog_content = "... ¿Mmm? Espera, creo que escucho algo además de sus molestas voces—",
  ui_story_31870401_129_dialog_content = "Escuché que la razón por la que el capitán no hace negocios con Umbraton es porque ese lugar es como el infierno descrito en los mitos.",
  ui_story_31870401_130_dialog_content = "No solo eso, dicen que el Señor Sombrío parece tener cuernos de toro y cara de caballo, y que mantiene un perro negro y un perro blanco a su lado...",
  ui_story_31870401_131_dialog_content = "... ¿Y dónde escuchaste esas cosas?",
  ui_story_31870401_132_dialog_content = "Más cuentos del coco, ¿eh? Parece que estas personas simplemente están especulando sobre Umbraton, como antes.",
  ui_story_31870401_133_dialog_content = "Si no voy al infierno, ¿quién más irá?",
  ui_story_31870401_134_dialog_content = "<color=#e8d9bb>Umbraton</color>",
  ui_story_31870401_135_dialog_content = "¡Una calle normal!",
  ui_story_31870401_136_dialog_content = "¡Una tienda normal!",
  ui_story_31870401_137_dialog_content = "Parece que los cuentos de este \"infierno\" han sido muy exagerados.",
  ui_story_31870401_138_dialog_content = "... ¿Oh? ¿Es esa una cara familiar que veo?",
  ui_story_31870401_139_dialog_content = "Su Alteza, parece que este puesto vende artículos utilizados para el método de adivinación de Astra.",
  ui_story_31870401_140_dialog_content = "Estas cartas... creo que se llaman cartas del tarot, ¿no? Interesante.",
  ui_story_31870401_141_dialog_content = "Jiu, quiero intentarlo, que lean mi fortuna con ellos.",
  ui_story_31870401_142_dialog_content = "Pero Su Alteza...",
  ui_story_31870401_143_dialog_content = "Elijamos la que está junto a mi mano como primera carta.",
  ui_story_31870401_144_dialog_content = "¿Podrías explicarme el significado de esta tarjeta, por favor?",
  ui_story_31870401_145_dialog_content = "Oh... Esa es la Torre en posición vertical. No es una buena señal, amigo mío.",
  ui_story_31870401_146_dialog_content = "Su Alteza, estoy seguro de que esto es solo un juguete para pasar el tiempo, así que por favor no...",
  ui_story_31870401_147_dialog_content = "Por favor, no confíes en ello en absoluto.",
  ui_story_31870401_148_dialog_content = "Veo que las calles de Umbraton tampoco están a salvo de estafadores.",
  ui_story_31870401_149_dialog_content = "Pero ambos somos adivinos, princesa Zhuohua. ¿Por qué cuestionar mis habilidades y no las de este caballero?",
  ui_story_31870401_150_dialog_content = "Nunca he sido de los que creen en adivinos o sus predicciones sin fundamento. Te lo dije en el barco, ¿o lo has olvidado?",
  ui_story_31870401_151_dialog_content = "¡Las mandarinas que crecen en el sur son mandarinas!",
  ui_story_31870401_152_dialog_content = "¡Pero se convertirían en naranjas amargas en el norte!",
  ui_story_31870401_153_dialog_content = "Princesa Zhuohua, sería un honor leer su fortuna, si está dispuesta. Estoy seguro de que el método de adivinación de nuestra tierra natal producirá una predicción muy diferente.",
  ui_story_31870401_154_dialog_content = "Todo lo que necesito es tu cumpleaños y nada más.",
  ui_story_31870401_155_dialog_content = "…",
  ui_story_31870401_156_dialog_content = "Muy bien, tengo curiosidad por ver qué tipo de predicción a medias me darás.",
  ui_story_31870401_157_dialog_content = "El cuarto día del cuarto mes... Debo decir que son números bastante especiales para tu fecha de nacimiento.",
  ui_story_31870401_158_dialog_content = "Contempla los palos, toma el control del destino. Con yin y yang combinados, todas las cosas toman forma...",
  ui_story_31870401_159_dialog_content = "Vaya. Esta es la primera vez que veo un destino tan increíblemente extraño.",
  ui_story_31870401_160_dialog_content = "Ahórrenos el teatro y simplemente dime mi fortuna.",
  ui_story_31870401_161_dialog_content = "La Serpiente Yang y el Tigre Yin son una fortuna también conocida como \"cabeza de serpiente y cola de tigre\", donde la serpiente representa la luz y el tigre representa la oscuridad.",
  ui_story_31870401_162_dialog_content = "Por absurdo que parezca, esta fortuna en realidad contiene un significado profundo.",
  ui_story_31870401_163_dialog_content = "Por lo que puedo ver, tu destino está lleno de muchas luchas, pero al final de tu viaje hay una bifurcación en el camino y más allá de eso se encuentra la <color=#FFB400>buena fortuna</color>.",
  ui_story_31870401_164_dialog_content = "¡¿Qué?!",
  ui_story_31870401_165_dialog_content = "Pero cuando era niño, el adivino me dijo que estaba destinado a tener mala suerte...",
  ui_story_31870401_166_dialog_content = "El destino y la suerte son dos cosas muy diferentes. El destino es decidido por los cielos, mientras que la suerte puede ser cambiada por nuestras propias manos.",
  ui_story_31870401_167_dialog_content = "Si decides mantenerte en tu camino actual, la vida cambiará para mejor. Las cosas no serán tan malas como lo fueron antes, estoy seguro.",
  ui_story_31870401_168_dialog_content = "En cuanto a cuándo sucederá eso, no puedo decirlo. Después de todo, ciertas cosas deben permanecer en secreto.",
  ui_story_31870401_169_dialog_content = "Sin embargo, esto es simplemente mi propia predicción. Eres libre de creer en cualquiera de las predicciones que se te den, o en ninguna.",
  ui_story_31870401_170_dialog_content = "Ahora bien, debo irme. Hasta la próxima vez que nos encontremos, Su Alteza.",
  ui_story_31870401_171_dialog_content = "¡Adiós!",
  ui_story_31870401_172_dialog_content = "¡Hasta la próxima!",
  ui_story_31870401_173_dialog_content = "…",
  ui_story_31870401_174_dialog_content = "Su Alteza... ¿En qué está pensando?",
  ui_story_31870401_175_dialog_content = "... No es nada. Vamos Jiu, deberíamos regresar al barco ahora.",
  ui_story_31870401_176_dialog_content = "Ah, parece que el destino de la Princesa Zhuohua está lejos de ser ordinario. Los cielos han puesto una gran responsabilidad sobre sus hombros.",
  ui_story_31870401_177_dialog_content = "(Así que ese es el tipo de fortuna que Dantang recibió al nacer...)",
  ui_story_31870401_178_dialog_content = "(¡Oh, no otra vez! ¡Tengo que encontrar a Jabber!)",
  ui_story_31870401_179_dialog_content = "No hay pistas en esta página tampoco, así que supongo que tendré que intentar con la siguiente...",
  ui_story_31870401_180_dialog_content = "¡Detente! ¡No pases esa página!",
  ui_story_31870401_181_dialog_content = "¿Eh?",
  ui_story_31870401_182_dialog_content = "Te sugiero encarecidamente que no sigas leyendo, PlayerName. Como he dicho antes, ciertas cosas deben mantenerse en secreto.",
  ui_story_31870401_183_dialog_content = "Está bien, sé todo misterioso entonces...",
  ui_story_31870401_184_dialog_content = "Por favor, perdóname, especialmente cuando debería estar agradeciéndote por usar tus poderes psíquicos para ayudarme.",
  ui_story_31870401_185_dialog_content = "Creo que sé dónde encontrar Farfullar ahora.",
  ui_story_31870401_186_dialog_content = "¿Qué? ¡¿Tú haces?!",
  ui_story_31870401_187_dialog_content = "Pero no logré descubrir nada...",
  ui_story_31870401_188_dialog_content = "Aunque me gustaría despedirte, debo buscar a Jabber de inmediato. Me aseguraré de agradecerte apropiadamente en otra ocasión.",
  ui_story_31870401_189_dialog_content = "No te preocupes por eso. No es como si realmente hubiera hecho algo...",
  ui_story_31870401_190_dialog_content = "¡Adiós por ahora! ¡Hasta la próxima!",
  ui_story_31870401_191_dialog_content = "¡E-Entonces me iré!",
  ui_story_31870401_192_dialog_content = "<color=#e8d9bb>Algún tiempo después</color>",
  ui_story_31870401_193_dialog_content = "…",
  ui_story_31870401_194_dialog_content = "Muy bien, ustedes dos pueden salir ahora.",
  ui_story_31870401_195_dialog_content = "¡Una sola tabla no hace un barco!",
  ui_story_31870401_196_dialog_content = "¡Un solo actor no hace una obra!",
  ui_story_31870401_197_dialog_content = "¡Hicimos un gran trabajo juntos!",
  ui_story_31870401_198_dialog_content = "¡Y podemos comer fruta todo el día!",
  ui_story_31870401_199_dialog_content = "Sí, sí, y también estoy dispuesto a pasar por alto el error de Squawk, aunque casi arruinó todo.",
  ui_story_31870401_200_dialog_content = "Aquí está la fruta especial prometida. ¡Ahora, deja de interferir con mi trabajo!",
  ui_story_31870401_201_dialog_content = "¡Hora de comer! ¡Hora de comer!",
  ui_story_31870401_202_dialog_content = "(Uf, invitar a PlayerName también resultó ser bastante fructífero!)",
  ui_story_31870401_203_dialog_content = "(Parece que tengo otra entrada para agregar al \"Pergamino de Ascensión Divina\" ahora.)",
  ui_story_31870401_204_dialog_content = "<color=#e8d9bb>Whoosh</color>",
  ui_story_31870401_205_dialog_content = "\"Experimentando y observando las habilidades psíquicas de los Caelestites.\""
}
return config
