---
--- Generated by shentayibu
--- Created by shentayibu.
--- DateTime: 2023/9/7 14:59
---

local FishingUtils = import('Game.UI.Fishing.FishingUtils')
local fishingComponent = GameUtils.GetOrAddEntityCompByType(ECSComponentType.Constants.FishingComponent)
local FishingMgr = import('Game.UI.Fishing.FishingMgr')
local ConstantsFishing = import('Game.UI.Fishing.ConstantsFishing')
local cardComponent = GameUtils.GetEntityCompByType(ECSComponentType.Constants.CardComponent)
local KTool = CS.Engine.Lib.KTool

----------------------------------------------

---@class PlaceNameService
local PlaceNameService = Class("PlaceNameService")

function PlaceNameService.new(from)
    local obj = PlaceNameService.New()
    obj.luaDialog = from
    for k, v in pairs(from) do
        obj[k] = v
    end
    return obj
end

function PlaceNameService:UpdateInfo()
    local vo = FishingUtils.GetFishingPlaceVo(self.placeId)
    CfUtils.FillText(self.PlaceName, vo.name)
end

function PlaceNameService:ShowMe()
    self:UpdateInfo()
    KTool.SetActive(self.PlaceName, true)
end

function PlaceNameService:HideMe()
    KTool.SetActive(self.PlaceName, false)
end

function PlaceNameService:OnClick()

end

return PlaceNameService