---
--- Generated by suixin
--- Created by suixin.
--- DateTime: 2023/2/23 10:54
---
--- from: Assets/BundleResources/Prefabs/OverseaManage/OverseaManageCafeCattyDialog.prefab
---@class OverseaManageCafeCattyLevelUpNode
---@field Env                           	OverseaManageCafeCattyLevelUpNode       
---@field controller                    	Engine.Modules.LuaBehaviour             
---@field SlierNumber                   	UnityEngine.RectTransform               
---@field Slider                        	UnityEngine.UI.Slider                   
---@field StateDescNode                 	UnityEngine.RectTransform               
---@field Content                       	UnityEngine.RectTransform               
---@field ImgIcon                       	UnityEngine.RectTransform               
---@field CommonBtnConsumePop           	Engine.Modules.LuaBehaviour             
---@field FontStyleButton               	Game.Native.Common.FontStyleButton      
---@field Item2                         	Engine.Modules.LuaBehaviour             
---@field Item1                         	Engine.Modules.LuaBehaviour             
---@field NextLock                      	UnityEngine.UI.Text                     
---@field TxtLVNumber                   	TMPro.TextMeshProUGUI                   
local OverseaManageCafeCattyLevelUpNode = Class('OverseaManageCafeCattyLevelUpNode')
local MaidCoffeeUtils = import("Game.MaidCoffee.MaidCoffeeUtils")
local MaidCoffeeMgr = import('Game.MaidCoffee.MaidCoffeeMgr')
local ConditionPath = "Game.MaidCoffee.MaidCoffeeUIDialog.Cell.OverseaManageCafeCattyConditionCell"
local ConditionCount = 2
local lockCount = 6
local KTool = CS.Engine.Lib.KTool
local cs_coroutine = require 'XLua.cs_coroutine'
local UIModule = CS.Engine.UI.UIModule
local LockCellPath = "Game.MaidCoffee.MaidCoffeeUIDialog.Cell.OverseaManageCafeLockDesCell"



function OverseaManageCafeCattyLevelUpNode:__init()
    self.component = GameUtils.GetOrAddEntityCompByType(ECSComponentType.Constants.MaidCoffeeComponent)
    self.conditionEnv = {}
    self.lockEnv = {}
end

function OverseaManageCafeCattyLevelUpNode:__delete()
    self.conditionEnv = nil
    self.lockEnv = nil
    Events.RemoveListener(Constants.EventNames.QuitLevelUpFinishDialog, self.onLevelUpEvent)
    self.onLevelUpEvent = nil
end

function OverseaManageCafeCattyLevelUpNode:SetCallBack(callBack)
    self.callBack = callBack
end

function OverseaManageCafeCattyLevelUpNode:Awake()
    self:InitEnv()
    self:AddUIClick()
end

function OverseaManageCafeCattyLevelUpNode:AddUIClick()
    SetButtonAction(self.FontStyleButton.gameObject,Bind(self,self.OnCattyLevelUp))

    self.onLevelUpEvent = Bind(self,self.OnLevelUpSuccess)
    Events.AddListener(Constants.EventNames.QuitLevelUpFinishDialog, self.onLevelUpEvent)

end

function OverseaManageCafeCattyLevelUpNode:InitEnv()
    for i = 1, ConditionCount do
        local node = self["Item"..i]
        if node then
            local env = CfUtils.GetLuaScr(node,ConditionPath)
            if env then
                self.conditionEnv[i] = env
            end
        end
    end

    self.lockEnv = {}
    self.lockEnv[1] = CfUtils.GetLuaScr(self.StateDescNode,LockCellPath)

    for i = 2, lockCount do
        local go = CS.UnityEngine.GameObject.Instantiate(self.StateDescNode.gameObject)
        KTool.SetParent(go,self.Content.gameObject,false)
        self.lockEnv[i] = CfUtils.GetLuaScr(go,LockCellPath)
    end
end

function OverseaManageCafeCattyLevelUpNode:RefreshShow(callBack)
    local curLevel = self.component:GetMaidCoffeeLevel()
    local curStar = self.component:GetMaidCoffeeCattyStarLevel()  --初始为0级  要取下一等级的对应等级
    local starVo = MaidCoffeeUtils.GetMaidCoffeeStarUpVo(curStar + 1)

    local maxLevel = nil
    if starVo then
        maxLevel = starVo.rankid
    end
    if maxLevel then
        CfUtils.FillText(self.TxtLVNumber,string.format("%s<size=40><color=#9d9d9d>/%s",curLevel,maxLevel))
    end

    local vos = MaidCoffeeMgr:GetInstance():GetMaidCoffeeLevelUpVosByLevel(curLevel)
    self:SetLockDesc(curLevel)
    self:SetConditionShow(vos,callBack)
    self:SetButtonStatus(vos)
    self:SetSliderShow(curLevel)
    self:RefreshRewardShow(curLevel)
    CfUtils.FillCommonBtnConsumePopNode(self.CommonBtnConsumePop, vos[1].costId, vos[1].costNum)
end

function OverseaManageCafeCattyLevelUpNode:RefreshRewardShow(level)
    local vo = MaidCoffeeUtils.GetMaidCoffeeLevelExpVo(level)
    CfUtils.RefreshCommonGoodsListLight(self.CommonGoodsListLight, vo.rewards)
end

function OverseaManageCafeCattyLevelUpNode:SetSliderShow(level)
    ---@type MaidCoffeePlayerComponent
    local maidCoffeePlayerComponent = GameUtils.GetEntityCompByType(ECSComponentType.Constants.MaidCoffeePlayerComponent)
    local cafeExp = maidCoffeePlayerComponent:GetCafeExp()
    local vo = MaidCoffeeUtils.GetMaidCoffeeLevelExpVo(level)
    if not isNull(vo) then
        self.Slider.value = cafeExp/vo.exp
        local iconTrans = self.SlierNumber.transform:Find("ImgGoodsIcon")
        if iconTrans then
            local path = GoodsConfMgr:GetInstance():GetPhotoPathById(Constants.CoffeeShowItem.PraisePointId)
            if path then
                CfUtils.FillImage(iconTrans.gameObject, path)
            end
        end
        CfUtils.FillText(self.SlierNumber,string.format("%s<color=#9d9d9d>/%s",cafeExp,vo.exp))
    end
end

function OverseaManageCafeCattyLevelUpNode:SetLockDesc(curLevel)
    local lockVos = MaidCoffeeMgr:GetInstance():GetMaidCoffeeLockVosByLevel(curLevel)
    for i = 1, #self.lockEnv do
        if lockVos[i] then
            KTool.SetActive(self.lockEnv[i].controller.gameObject,true)
            self.lockEnv[i]:RefreshShow(lockVos[i])
        else
            KTool.SetActive(self.lockEnv[i].controller.gameObject,false)
        end
    end
end

function OverseaManageCafeCattyLevelUpNode:SetButtonStatus()
    local isCanLevelUp = self.component:IsCanLevelUp()
    local id = isCanLevelUp and "B6" or "B18"
    self.FontStyleButton:ResetFontStyle(id)
end

function OverseaManageCafeCattyLevelUpNode:SetConditionShow(vos,callBack)
    for i = 1, #self.conditionEnv do
        if vos[i] then
            KTool.SetActive(self.conditionEnv[i].controller.gameObject,true)
            self.conditionEnv[i]:SetConditionShow(vos[i],i,function()
                Events.Broadcast("MaidCoffee.RefreshCondition")
            end)
        else
            KTool.SetActive(self.conditionEnv[i].controller.gameObject,false)
        end
    end
end
function OverseaManageCafeCattyLevelUpNode:OnCattyLevelUp()
    local curLevel = self.component:GetMaidCoffeeLevel()
    local vos = MaidCoffeeMgr:GetInstance():GetMaidCoffeeLevelUpVosByLevel(curLevel)
    local isCompleteAll = self.component:IsCompleteAll(vos)
    if not isCompleteAll then
        return
    end
    local itemEnough = GoodsUtils.GetThingNo(vos[1].costId) >= vos[1].costNum
    if not itemEnough then
        return
    end
    local maidCoffeePlayerComponent = GameUtils.GetEntityCompByType(ECSComponentType.Constants.MaidCoffeePlayerComponent)
    local cafeExp = maidCoffeePlayerComponent:GetCafeExp()
    local vo = MaidCoffeeUtils.GetMaidCoffeeLevelExpVo(curLevel)

    local isExpEnough = cafeExp >= vo.exp
    if not isExpEnough then
        GameUtils.Toast(localize("餐厅经验不足，前往售卖套餐可获得餐厅经验"))
        return
    end

    GameUtils.Request(Interfaces.MaidCoffeeLevelUp,
            {},
            function(request,response)
                if checkInt(response.errCode) == 0 then
                    GoodsUtils.DrawRewards({ [1] = { goodsId = vos[1].costId, num = -vos[1].costNum} })
                    ---@type MaidCoffeePlayerComponent
                    local maidCoffeePlayerComponent = GameUtils.GetEntityCompByType(ECSComponentType.Constants.MaidCoffeePlayerComponent)
                    local curLevel = maidCoffeePlayerComponent:GetCafeLevel()
                    maidCoffeePlayerComponent:UpdateCafeLevel(curLevel + 1)

                    local maidCoffeeHomeDojo = self.component:GetMaidCoffeeHomeDoJo()
                    maidCoffeeHomeDojo:UpdateDarkMerchantInfo(response.data.darkMerchant)

                    --- 进入升级成功界面
                    UIModule.OpenDialog({ id = Constants.UITypeIds.CultivateLevelUpSecondConfirmPanel, parameters = {
                        levelUpType = Constants.UICultivateLevelUpFinishType.MaidCoffeeCattyLevelUp,closeCb = function()
                            if response.data.rewards and table.count(response.data.rewards) > 0 then
                                GoodsUtils.DrawRewards(response.data.rewards, true)
                                UIModule.OpenDialog({ id = Constants.UITypeIds.UICommonRewardPop, parameters = { rewards = response.data.rewards}})
                            end
                        end
                    } })
                end
            end)
end

function OverseaManageCafeCattyLevelUpNode:OnLevelUpSuccess(levelUpType)
    if levelUpType == Constants.UICultivateLevelUpFinishType.MaidCoffeeCattyLevelUp then
        GameUtils.Request(Interfaces.MaidCoffeeLevelTask,{},
                function(request,response)
                    if checkInt(response.errCode) == 0 then
                        local maidCoffeeHomeDojo = self.component:GetMaidCoffeeHomeDoJo()
                        maidCoffeeHomeDojo:UpdateLevelTaskProgress(response.data.levelTaskProgress)
                        if self.callBack then
                            self.callBack()
                        end
                    end
                end)
    end
end

function OverseaManageCafeCattyLevelUpNode:OnDestroy()
    self.controller = nil--luabehaviour 中CSharp对象
    self:Delete()
end

return OverseaManageCafeCattyLevelUpNode