---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuhao.zhao
--- DateTime: 2021/1/29 15:04
--- Project: cat-proj
---

local util = require 'XLua.util'
local cs_coroutine = require 'XLua.cs_coroutine'
local KTool = CS.Engine.Lib.KTool
local CSGameUtils = CS.GameUtils
local ButtonComp = CS.UnityEngine.UI.Button
local InputComp = CS.UnityEngine.UI.InputField
local TextComp = CS.UnityEngine.UI.Text
local ImageComp = CS.UnityEngine.UI.Image
local CanvasGroup = CS.UnityEngine.CanvasGroup
local Yielders = CS.Engine.Lib.Yielders
local SettingMgr = SettingMgr:GetInstance()
local PlayableDirector = CS.UnityEngine.Playables.PlayableDirector
local CriWareUtils = import('Game.Entry.CriWareUtilsFix')
local MonoHelper = CS.Engine.Lib.MonoHelper
local support = require 'Frame.support'
local AnimatorOverrideBinder = CS.AnimatorOverrideBinder
local ResourceModule = CS.Engine.Modules.ResourceModule
local Animator = CS.UnityEngine.Animator
local Unity_Quaternion = CS.UnityEngine.Quaternion
local DOTween = CS.DG.Tweening.DOTween
local DOVirtual = CS.DG.Tweening.DOVirtual
local UISwitchImage = CS.Game.Native.Common.UISwitchImage
local SpriteRenderer = CS.UnityEngine.SpriteRenderer
local CustomRoleLightDir = CS.CustomRoleLightDir
local UIRaycastBlocker = CS.Engine.UI.UIRaycastBlocker.Instance
local KCookie = CS.Engine.Lib.KCookie

local CustomMarkerTrack = CS.Markers.CustomMarkerTrack
local TimelineNotificationTrcak = CS.Game.Native.QTE.TimelineNotificationTrcak
local UIAutoContentMarker = CS.Markers.UIAutoContentMarker
local UIContentMarker = CS.Markers.UIContentMarker
local SkipPointMarker = CS.Markers.SkipPointMarker
local TimelineController = CS.Engine.TimeLine.TimelineController

local CriLipsDeformerForAtomSource = CS.CriWare.CriLipsDeformerForAtomSource
local SmallPackageDownloaded = "SmallPackageDownloaded"
local PlayerPrefsUtility = CS.Engine.Tools.PlayerPrefsUtility
local AppEngine = CS.Engine.Lib.AppEngine
local function IsSmallPackage()
    local isSmallPackage = checkNumber(AppEngine.GetConfig("Engine", "IsSmallPackage", false))
    local preVersion = PlayerPrefsUtility.GetEncryptedString(SmallPackageDownloaded, "")
    local isSmall = false
    if isSmallPackage == 1 and preVersion ~= CS.UnityEngine.Application.version then
        ---最新的分包的逻辑，要进行检测更新相关的逻辑
        isSmall = true
    end
    return isSmall
end
--- from: Assets/BundleResources/Prefabs/Chapter/ChapterNewUI.prefab
---@class ChapterNewUI
---@field Env                            ChapterNewUI
---@field controller                        Engine.Modules.LuaBehaviour | Engine.UI.UILuaDialog
---@field BtnSpeed                        UnityEngine.UI.Button
---@field BtnPlotReview                    UnityEngine.UI.Button
---@field DialogBtn                        UnityEngine.UI.Button
---@field ScreenBtn                        UnityEngine.UI.Button
---@field BtnSkip                        UnityEngine.UI.Button
---@field TgAuto                            UnityEngine.RectTransform
---@field BtnUIControl                    UnityEngine.UI.Button
---@field Control                        UnityEngine.RectTransform
---@field BtnConfirm                        UnityEngine.RectTransform
---@field BtnRandom                        UnityEngine.UI.Button
---@field InputField                        UnityEngine.UI.InputField
---@field CreateName                        UnityEngine.RectTransform
---@field Indicate                        UnityEngine.RectTransform
---@field IconHead                        Engine.UI.ImageAlterable
---@field TxtLeftName                    UnityEngine.UI.Text
---@field Titles                            UnityEngine.RectTransform
---@field TxtContent                        LetterTyperComp
---@field grid                            UnityEngine.RectTransform
---@field Dialog                            UnityEngine.RectTransform
local ChapterNewUI = Class('ChapterNewUI')

local ChapterUtils = import('Game.Chapter.ChapterUtils')

local ChapterConstants = import('Game.Chapter.ChapterConstants')

local NewChapterConstants = import('Game.Chapter.NewChapterConstants')

local NewChapterUtils = import('Game.Chapter.NewChapterUtils')

--"\u00A0"
local NonBreakingSpace = utf8.char(160)

function ChapterNewUI:__init()
    --
    self.IsAutoPlay = nil   -- 正在自动播放
    self.IsUIHide = nil
    self.CsEnv = nil        -- C#脚本ChapterProcessor
    self.DialogSetting = nil    -- 剧情配表信息
    self.BlockClick = nil
    self.Tween = nil
    self._preAuto = nil     -- 保存之前是否是自动状态
    self._waitCo = nil
    self._wait = nil
    self._cachedVo = nil
    self._cachedPath = nil
    self._lockName = nil
    self._isPause = nil
    self._isQTEChapter = nil
    ---@type NewChapterSummary
    self.summaryEnv = nil       -- 跳过时显示的概述界面
    self._modifyBs = nil
    self._lateUpdater = nil
    self._speakerMouseRigs = nil
    self._speakerMouseRigsDefaults = nil
end

function ChapterNewUI:__delete()
    --
    self.IsAutoPlay = nil
    self.IsUIHide = nil
    self.CsEnv = nil
    self.DialogSetting = nil
    self.BlockClick = nil
    self.Tween = nil
    self._preAuto = nil
    self._waitCo = nil
    self._wait = nil
    self._cachedVo = nil
    self._cachedPath = nil
    self._lockName = nil
    self._isPause = nil
    self._isQTEChapter = nil
    ---@type NewChapterSummary
    self.summaryEnv = nil
    self._modifyBs = nil
    self._lateUpdater = nil
    self._speakerMouseRigs = nil
    self._speakerMouseRigsDefaults = nil
end

function ChapterNewUI:Awake()
    self.IsAutoPlay = false
    self.IsUIHide = false
    self.visible = true
    KTool.SetActive(self.grid.gameObject, false)
    local pos = self.grid.anchoredPosition
    pos.y = 249
    self.grid.anchoredPosition = pos

    if IsSmallPackage() then
        KTool.SetActive(self.BtnUIControl.gameObject, false)
        KTool.SetActive(self.BtnPlotReview.gameObject, false)
    end
end

function ChapterNewUI:Start()
    self.timeScaleBeforeChapter = CS.UnityEngine.Time.timeScale     -- 记录进入剧情前的倍速

    SetButtonAction(self.BtnUIControl, function()
        self.IsUIHide = true;
        self:SetUIState(true);
        self:SetVisible(true)

        KTool.SetActive(self.ScreenBtn, true)
    end)

    --self.TgAuto.onValueChanged:AddListener(function(st)
    --    self.IsAutoPlay = st
    --    self:SetAutoPlay(st)
    --end)
    SetButtonAction(self.TgAuto, function()
        KTool.SetActive(self.BtnSpeed.gameObject, not self.IsAutoPlay)
        self.IsAutoPlay = not self.IsAutoPlay
        local state = self.IsAutoPlay and 2 or 1
        self.TgAuto.gameObject:GetComponent(typeof(UISwitchImage)).Status = state
        self._autoSpeed = 1
        CS.UnityEngine.Time.timeScale = NewChapterConstants.SpeedUp[self._autoSpeed]
        DOTween.timeScale = NewChapterConstants.SpeedUp[self._autoSpeed]
        CriWareUtils.SetAudioSpeed(NewChapterConstants.SpeedUp[self._autoSpeed])
        self:SetAutoPlay(self.IsAutoPlay)
        self.BtnSpeed.transform:Find("ImgSpeed").gameObject:GetComponent(typeof(UISwitchImage)).Status = self._autoSpeed
    end)

    SetButtonAction(self.BtnSpeed, function()
        self._autoSpeed = self._autoSpeed % #NewChapterConstants.SpeedUp + 1
        CS.UnityEngine.Time.timeScale = NewChapterConstants.SpeedUp[self._autoSpeed]
        DOTween.timeScale = NewChapterConstants.SpeedUp[self._autoSpeed]
        CriWareUtils.SetAudioSpeed(NewChapterConstants.SpeedUp[self._autoSpeed])
        self.BtnSpeed.transform:Find("ImgSpeed").gameObject:GetComponent(typeof(UISwitchImage)).Status = self._autoSpeed
    end)

    SetButtonAction(self.BtnSkip, function()
        --if self._isSkip then
        --    return
        --end

        if not isNull(self.CsEnv) then
            if not isNull(self.summaryEnv) and self.GeneralVo ~= nil then
                self.summaryEnv.Env:Show(self.GeneralVo, nil, function()

                    --if not isNull(self.CsEnv) then
                    --    self.CsEnv:ChapterFinish()
                    --end
                    CriWareUtils.SetAudioSpeed(1)
                    self:Pause()
                    self.CsEnv:StopAllCoroutines()
                    if self.CsEnv.OnChapterFinish ~= nil then
                        self.CsEnv.OnChapterFinish()
                    end

                    xRecord.record(ChapterConstants.EventId, string.format(ChapterConstants.EventContent, self.CsEnv.ChapterId))

                end)
            else
                self:Pause()
                self.CsEnv:StopAllCoroutines()
                if self.CsEnv.OnChapterFinish ~= nil then
                    self.CsEnv.OnChapterFinish()
                end

                xRecord.record(ChapterConstants.EventId, string.format(ChapterConstants.EventContent, self.CsEnv.ChapterId))
            end
            --self._isSkip = true
        end
        
    end)

    SetButtonAction(self.ScreenBtn, function()
        self.IsUIHide = false;
        self:SetUIState(false)
        self:SetVisible(false)
        self.TxtContent:ShowAll()

        KTool.SetActive(self.ScreenBtn, false)
    end)

    SetButtonAction(self.BtnPlotReview, function()
        if not isNull(self.reviewEnv) then
            self:FinishType()
            self.reviewEnv.Env:Show(self.record, function()
                if not isNull(self._dialogCo) then
                    cs_coroutine.stop(self._dialogCo)
                    self._dialogCo = nil
                end

                if not isNull(self.disableCo) then
                    cs_coroutine.stop(self.disableCo)
                    self.disableCo = nil
                end

                if self._sequenceNext == nil then
                    self:Pause()
                end

            end, function()

                if self.HasOption then
                    return
                end

                if self._sequenceNext == nil then
                    self:Resume()
                end
                
            end)
        end
    end)

    local type = ChapterUtils.GetChapterTypeById(self.CsEnv.ChapterId)
    if type ~= ChapterConstants.ChapterType.PrePlot then
        local popTrans = self.controller.transform.parent:Find("ChapterSummaryPopup")
        if not isNull(popTrans) then
            popTrans.localScale = Vector3(1, 1, 1)
            local vec = self.controller.transform.localPosition
            vec.z = 10
            self.controller.transform.localPosition = vec
            self.summaryEnv = GetLuaBehaviour(popTrans.gameObject, "Game.Chapter.NewChapterSummary")
            if isNull(self.summaryEnv.Env) then
                self.summaryEnv:Init()
            end
        end
        KTool.SetActive(popTrans, false)
    end

    if type ~= ChapterConstants.ChapterType.PrePlot then
        local popTrans = self.controller.transform.parent:Find("ChapterReviewPopup")
        if not isNull(popTrans) then
            popTrans.localScale = Vector3(1, 1, 1)
            local vec = self.controller.transform.localPosition
            vec.z = 10
            self.controller.transform.localPosition = vec
            -- 回看全部对话的界面
            self.reviewEnv = GetLuaBehaviour(popTrans.gameObject, "Game.Chapter.NewChapterReview")
            if isNull(self.reviewEnv.Env) then
                self.reviewEnv:Init()
            end
        end
        KTool.SetActive(popTrans, false)
    end

    self.OverlayBtn = self.controller.transform:Find("OverlayBtn")
    KTool.SetActive(self.OverlayBtn, false)
    self.cg = self.controller.transform:Find("cg")
    if not isNull(self.cg) then
        self.cg = self.cg.gameObject:GetComponent(typeof(CS.Engine.UI.RawImageAlterable))
    end
    self.bgMovie = self.controller.transform:Find("bgMovie")
    if not isNull(self.bgMovie) then
        self.bgMovie = self.bgMovie.gameObject:GetComponent(typeof(CS.CriWare.CriManaMovieControllerForUI))
        self.bgMovie.loop = true
    end

    local parent = self.controller.transform.parent
    self.BlockUI = parent:Find("Block")
    if not isNull(self.BlockUI) then
        KTool.SetActive(self.BlockUI:Find("Text"), false)
        self.BlockUI = self.BlockUI:Find("BlockScreen")
        self.BlockUI = self.BlockUI.gameObject:GetComponent(typeof(ImageComp))
    end

    self:InitLayout()
    self._lateUpdater = Bind(self, self.OnLateUpdate)
    MonoHelper.AddLateUpdateListener(self._lateUpdater)
end

function ChapterNewUI:OnDestroy()
    -- print("[声音] ChapterNewUI 退出前关闭声音")
    if not isNull(self.soundRecord) then
        if not isNull(self.soundRecord.loopSERecord) then
            for i, v in ipairs(self.soundRecord.loopSERecord) do
                CriWareUtils.StopById(v)
            end
        end
        if not isNull(self.soundRecord.SERecord) then
            for i, v in ipairs(self.soundRecord.SERecord) do
                CriWareUtils.StopById(v)
            end
        end
        if not isNull(self.soundRecord.bgmRecord) then
            for i, v in ipairs(self.soundRecord.bgmRecord) do
                CriWareUtils.StopById(v)
            end
        end
    end

    CS.UnityEngine.Time.timeScale = self.timeScaleBeforeChapter
    DOTween.timeScale = self.timeScaleBeforeChapter
    CriWareUtils.SetAudioSpeed(self.timeScaleBeforeChapter)
end

function ChapterNewUI:SetUIState(st)

    KTool.SetActive(self.TgAuto.gameObject, not st)

    if IsSmallPackage() then
        KTool.SetActive(self.BtnUIControl.gameObject, false)
    else
        KTool.SetActive(self.BtnUIControl.gameObject, not st)
    end

    KTool.SetActive(self.BtnSkip.gameObject, not st)

    if IsSmallPackage() then
        KTool.SetActive(self.BtnPlotReview.gameObject, false)
    else
        KTool.SetActive(self.BtnPlotReview.gameObject, not st)
    end

    KTool.SetActive(self.BtnSpeed.gameObject, not st)
    if not st then
        KTool.SetActive(self.BtnSpeed.gameObject, checkBool(self.IsAutoPlay))
    end
end

--ChapterProcessor 调用
function ChapterNewUI:Initialize(csEnv)
    self.CsEnv = csEnv
    local id = self.CsEnv.ChapterId
    xRecord.record(ChapterConstants.EventEnterId, string.format(ChapterConstants.EventEnterContent, id))
    self.visible = true
    printInfo("Initialize %d", id)
    self._chapterType = ChapterUtils.GetChapterTypeById(id)
    self._isQTEChapter = self.CsEnv.IsQTEChapter

    self._needHead = false

    -- 每个分段开始的时候，收集分段里的marks，重置markIndex
    self.CsEnv.OnSingleChapterStart = function(director)

        print("chapter start ", director.name)

        self:GetSkipConfigs(director)
        --for i = 1, #self.collectMarkers do
        --    local index = i
        --    printInfo(tostring(self.collectMarkers[index]:GetType()) .. " " .. tostring(self.collectMarkers[index].time) )
        --end
        --printInfo(table.dump(self.collectMarkers))
        self.markerIndex = 0
    end

    self.CsEnv.OnSingleChapterFinish = function(director)
        self.collectMarkers = nil
        self.currentDirector = nil
        self.skipPointMarkers = nil
        self.markerIndex = -1
        print("chapter finish ", director.name)

    end

    xTry(function()
        local vo = ChapterUtils.GetChapterGeneralVo(self.CsEnv.ChapterId)
        self.GeneralVo = vo
    end)

    xTry(function()

        self.DialogSetting = SettingMgr:GetSetting(ChapterUtils.GetSettingPathById(self.CsEnv.ChapterId), "NewChapter2DVo")

        self.initialized = true
    end, function()
        --printError("%s", debug.traceback())
        self.initialized = false
    end)
    --if checkNumber(self.CsEnv.ChapterId) == ChapterConstants.ChapterRename then
    --    ---@type GuideComponent
    --    --local GuideComponent = GameUtils.GetOrAddEntityCompByType(ECSComponentType.Constants.GuideComponent)
    --    --if GuideComponent.isInit == nil then
    --    --    local st = GuideComponent:CheckOneCondition(Constants.GuideConditionType.CompletePreModule, 2)
    --    --    KTool.SetActive(self.Control, st)
    --    --    self._lockName = st
    --    --
    --    --else
    --    --    KTool.SetActive(self.Control, false)
    --    --end
    --    ---@type PlayerComponent
    --    local playerComp = GameUtils.GetOrAddEntityCompByType(ECSComponentType.Constants.PlayerComponent)
    --    self._lockName = not string.startsWith(playerComp.playerDojo.playerName, "test")
    --    KTool.SetActive(self.Control, self._lockName)
    --end
    print(self.initialized)

    local needSkip = true
    KTool.SetActive(self.BtnSkip.gameObject, needSkip)

    --self.simpleController = {}
    --self.simpleController.loader = ResourceModule.LoadBundleSync("RuntimeController/Simple.controller", nil, true)
    --self.simpleController.obj = self.simpleController.loader.ResultObject
    --if not self.TxtContent.Inited then
    --    self.TxtContent:Init()
    --    self.TxtContent.Inited = true
    --end

    self:PreprocessSpeakerMouse()

end

function ChapterNewUI:Pause()
    self._isPause = true
    self.CsEnv:PauseDirector()
    if self.currentDirector ~= nil and self.currentDirector.director ~= nil then
        self.currentDirector.director:Evaluate()
    end
    printInfo("Pause")
end

function ChapterNewUI:Resume(st)
    if st == nil then
        st = false
    end
    self._isPause = false
    self.CsEnv:ResumeDirector(st)
    printInfo("Resume %s", tostring(st))
end

--function ChapterNewUI:IncreaseIndex()
--    if not isNull(self.markerIndex) then
--        self.markerIndex = self.markerIndex + 1
--    end
--end

function ChapterNewUI:CheckIndex()
    if isNull(self.markerIndex) or #self.collectMarkers == 0 then
        return -1
    end

    if self.markerIndex + 1 > #self.collectMarkers then
        return 1
    end

    return 0
end

function ChapterNewUI:GetIndex(time)
    local index
    for i = 1, #self.collectMarkers do
        if self.collectMarkers[i].time > time then
            index = i - 1
            break
        end
    end
    if index == nil then
        index = #self.collectMarkers
    end
    return index
end

function ChapterNewUI:IsInBlockTime(time)
    local r = false
    for i, v in ipairs(self.blockTime) do
        if v.startTime <= time and time <= v.endTime then
            r = true
            break
        end
    end

    return r
end

function ChapterNewUI:GetSkipMarker()
    if self.currentDirector == nil then
        return -1
    end

    if self.skipPointMarkers == nil then
        return -1
    end

    local marker = nil
    for i = 1, #self.skipPointMarkers do
        if self.skipPointMarkers[i].time > self.currentDirector.director.time then
            marker = self.skipPointMarkers[i]
            break
        end
    end

    if isNull(marker) then
        return 0
    else
        return marker
    end
end

-- 获取一个分段timeline里面所有的mark配置信息
function ChapterNewUI:GetSkipConfigs(director)
    -- 保存 UIContentMarker 和 UIAutoContentMarker
    self.collectMarkers = {}
    self.skipPointMarkers = {}
    self.blockMarkers = {}
    self.silenceDealMarkers = {}
    self.blockTime = {}

    self.currentDirector = {}
    self.currentDirector.director = director
    self.currentDirector.controller = director.gameObject:EnsureComponent(typeof(TimelineController))

    local track = self:GetTrackByType(director, typeof(CustomMarkerTrack))
    if not isNull(track) then
        local list = self:GetMarkers(track)
        for i = 1, list.Count do
            local index = i - 1
            local markerType = list[index]:GetType()
            if markerType == typeof(UIContentMarker) or markerType == typeof(UIAutoContentMarker) then
                table.insert(self.collectMarkers, list[index])
            elseif markerType == typeof(SkipPointMarker) then
                table.insert(self.skipPointMarkers, list[index])
            elseif markerType == typeof(CS.Game.Native.QTE.QTEFullScreenTouchMarker) then
                table.insert(self.blockMarkers, list[index])
            elseif markerType == typeof(CS.Markers.BlockSkipStartMarker) then
                table.insert(self.blockMarkers, list[index])
                local tb = {}
                tb.startTime = list[index].time
                tb.endTime = isNull(list[index].EndMarker) and self.currentDirector.director.duration or list[index].EndMarker.time
                table.insert(self.blockTime, tb)
            end
        end

    end

    track = self:GetTrackByType(director, typeof(TimelineNotificationTrcak))
    if not isNull(track) then
        local list = self:GetMarkers(track)
        for i = 1, list.Count do
            local index = i - 1
            local markerType = list[index]:GetType()
            if markerType == typeof(CS.Game.Native.QTE.QTEFullScreenTouchMarker) then
                table.insert(self.blockMarkers, list[index])
            elseif markerType == typeof(CS.Game.Native.QTE.QTEDragMarker) then
                table.insert(self.blockMarkers, list[index])
            elseif markerType == typeof(CS.Game.Native.QTE.QTEShowMainSceneMarker) then
                table.insert(self.silenceDealMarkers, list[index])
            elseif markerType == typeof(CS.Game.Native.QTE.QTERectTouchMarker) then
                table.insert(self.blockMarkers, list[index])
            elseif markerType == typeof(CS.Game.Native.QTE.QTELongTouchMarker) then
                table.insert(self.blockMarkers, list[index])
            elseif markerType == typeof(CS.Game.Native.QTE.QTESoundPlayMarker) then
                table.insert(self.silenceDealMarkers, list[index])
            elseif markerType == typeof(CS.Markers.GameObjectActiveMarker) then
                table.insert(self.silenceDealMarkers, list[index])
            end
        end
    end

    if #self.collectMarkers > 1 then
        table.sort(self.collectMarkers, function(a, b)
            return a.time < b.time
        end)
    end

    if #self.skipPointMarkers > 1 then
        table.sort(self.skipPointMarkers, function(a, b)
            return a.time < b.time
        end)
    end

    if #self.blockMarkers > 1 then
        table.sort(self.blockMarkers, function(a, b)
            return a.time < b.time
        end)
    end

    if #self.silenceDealMarkers > 1 then
        table.sort(self.silenceDealMarkers, function(a, b)
            return a.time < b.time
        end)
    end
end

function ChapterNewUI:GetBlockMarker(currentTime, destTime)
    local block
    for i = 1, #self.blockMarkers do
        local time = self.blockMarkers[i].time
        if currentTime <= time and destTime >= time then
            block = self.blockMarkers[i]
            break
        end
    end

    return block
end

function ChapterNewUI:GetBlockUI()
    if self.currentDirector == nil or self.currentDirector.director == nil then
        return 
    end
    local blockName = "heimu"
    local parent = self.currentDirector.director.transform
    local tmp = parent:Find(blockName)
    if not isNull(tmp) then
        return tmp
    end
    tmp = parent:Find("UI")
    if isNull(tmp) then
        tmp = parent:Find("Canvas")
    end

    if isNull(tmp) then
        return nil
    end
    
    return tmp:Find(blockName)
    
end

function ChapterNewUI:SilenceProcess(currentTime, destTime)
    for i = 1, #self.silenceDealMarkers do
        local time = self.silenceDealMarkers[i].time
        local markerType = self.silenceDealMarkers[i]:GetType()
        if currentTime <= time and destTime >= time then
            if markerType == typeof(CS.Game.Native.QTE.QTEShowMainSceneMarker) then
                --table.insert(self.silenceDealMarkers, list[index])
                self:OpenMain()
            elseif markerType == typeof(CS.Game.Native.QTE.QTESoundPlayMarker) then
                --table.insert(self.silenceDealMarkers, list[index])
                self:OnSound(self.silenceDealMarkers[i])
            elseif markerType == typeof(CS.Markers.GameObjectActiveMarker) then
                --table.insert(self.silenceDealMarkers, list[index])
                self:ActiveObj(self.silenceDealMarkers[i])
            end
        end
    end

end

function ChapterNewUI:ActiveObj(notification)
    local obj = notification.ControlObj:Resolve(self.currentDirector.director);
    if isNull(obj) then
        return
    end
    KTool.SetActive(obj, notification.State);
end

function ChapterNewUI:OnSound(notification)
    local soundId = notification.soundId
    if notification.isStop then
        CriWareUtils.StopById(soundId)
        return
    end
    if notification.isBGM
    or notification.alwaysPlay then
        CriWareUtils.PlayMusicById(soundId)
    end
end

function ChapterNewUI:OpenMain()
    local sceneManagement = SceneManagement:GetInstance()
    local sceneData = sceneManagement:GetScenePathInfo(self.OP1Env.sceneId)
    sceneManagement:SetActive(sceneData.id, true)
    CfUtils.ChangeMainCamDefalultBlend(0)
    KTool.SetRenderFeatureActiveByName(Constants.RenderFeatureNames.BLUR, false)

end

function ChapterNewUI:UIControl(luaFunc, parameters, csEnv)

    --self:IncreaseIndex()

    if luaFunc == "ShowText" then

        --printInfo(parameters)
        --local data = string.split(parameters, ";")
        self:Pause()

        KTool.SetActive(self.OverlayBtn, false)
        --KTool.SetActive(self.Dialog, true)
        ----KTool.SetActive(self.DialogBtn, true)
        --if not isNull(self.Tween) then
        --    self.Tween:Kill()
        --end
        --self.Tween = self.Dialog.gameObject:GetComponent(typeof(CanvasGroup)):DOFade(1, 0.25)
        --self.TxtContent:SetText("")
        if self.disableCo ~= nil then
            cs_coroutine.stop(self.disableCo)
            self.disableCo = nil
        end
        

        self._needHead = false
        self._teleportEffect = false
        print("ShowText showHead ", self._needHead, self._teleportEffect)

        self:OpenDialog()
        self._overrideNext = true
        self._convertAuto = parameters.AutoSkip
        self:Refresh(checkNumber(parameters.RowId))

        --elseif luaFunc == "Rename" then
        --
        --    if self._lockName then
        --        self.CsEnv:ResumeDirector()
        --        return
        --    end
        --    
        --    self.BlockClick = true
        --    
        --    KTool.SetActive(self.CreateName, true)
        --    
        --    --KTool.SetActive(self.DialogBtn, false)
        --
        --    local randomImage = self.BtnRandom.gameObject:GetComponent(typeof(ImageComp))
        --    randomImage.raycastTarget = true
        --    --btn.gameObject:GetComponent(typeof(CanvasGroup)).alpha = 1
        --    
        --    SetButtonAction(self.BtnRandom, function()
        --        --local id = math.random(1, self.RandomNameSetting:Count())
        --        --self.InputField.text = self.RandomNameSetting:Get(id).RoleName
        --        GameUtils.Request(Interfaces.PlayerRandomName, {}, function(request, response)
        --            if checkNumber(response.errCode) == 0 then
        --                self.InputField.text = response.data.playerName
        --               
        --            end
        --        end)
        --    end)
        --
        --    local btn = self.BtnConfirm:GetChild(0).gameObject:GetComponent(typeof(ButtonComp))
        --
        --    SetButtonAction(btn, function()
        --        
        --        local text = self.InputField.text
        --        if string.isEmpty(text) or text == nil then
        --            GameUtils.Toast(localize("请输入名字"), nil)
        --            return
        --        end
        --        --printInfo(text)
        --        --local length = utf8.len(text)
        --        --printInfo(length)
        --        -----@type BaseArgVo
        --        --local voMin = self.BaseArgSetting:Get(1)
        --        -----@type BaseArgVo
        --        --local voMax = self.BaseArgSetting:Get(2)
        --        --if length < checkNumber(voMin.num) or length > checkNumber(voMax.num) then
        --        --    GameUtils.Toast(localize("名字的长度应该在_num1_和_num2_之前", {_num1_ = voMin.num , _num2_ = voMax.num}), nil, self.CreateName.gameObject)
        --        --    return
        --        --end
        --        
        --        
        --        
        --        GameUtils.Request(Interfaces.PlayerRename, {playerName = text}, function(request, response)
        --            if checkNumber(response.errCode) == 0 then
        --                ---@type PlayerComponent
        --                local playerComp = GameUtils.GetEntityCompByType(ECSComponentType.Constants.PlayerComponent)
        --                playerComp.playerDojo.playerName = response.data.playerName
        --
        --                KTool.SetActive(self.CreateName, false)
        --
        --                self.BlockClick = false
        --
        --                self.CsEnv:ResumeDirector()
        --            end
        --        end )
        --    end)
    elseif luaFunc == "AutoShowText" then
        if parameters.PauseTimeline then
            self:Pause()
        end

        self._needHead = parameters.NeedHead
        self._teleportEffect = parameters.TeleportEffect

        print("AutoShowText showHead ", self._needHead, self._teleportEffect)

        KTool.SetActive(self.OverlayBtn, false)

        if self.disableCo ~= nil then
            cs_coroutine.stop(self.disableCo)
            self.disableCo = nil
        end
        

        self.disableCo = cs_coroutine.start(function()
            coroutine.yield(Yielders.GetWaitForSeconds(parameters.Duration))
            self:Refresh(0)
            --self:Pause()
            --local modelBinders = parameters.ModelBinders
            --if modelBinders.Count > 0 then
            --    for i = 1, modelBinders.Count do
            --        local binder = modelBinders[i - 1]
            --        self:SetCharacterLoop(binder)
            --    end
            --end
            self.disableCo = nil
        end)

        self:OpenDialog()
        self._overrideNext = true
        self:Refresh(checkNumber(parameters.RowId))

    elseif luaFunc == "SequenceText" then

        self:Pause()

        KTool.SetActive(self.OverlayBtn, false)

        self._needHead = true
        self._teleportEffect = false

        print("SequenceText showHead ", self._needHead, self._teleportEffect)

        self._overrideNext = false
        if self._sequenceNext == nil then
            self._sequenceNext = {}
        end
        local startId = parameters.StartRowId 
        local endId = parameters.EndRowId
        if endId - startId < 50 then
            for i = startId, endId do
                self._sequenceNext[i] = i + 1
            end
        end
        self._sequenceNext[endId] = 0

        self:FindStartBg(startId, endId)
        if self.startBg ~= nil then
            print("start bg ", table.dump(self.startBg))
            self:LoadBg(self.startBg)
        end

        self.Duration = 1
        self.seqCo = cs_coroutine.start(function()

            coroutine.yield(Yielders.GetWaitForSeconds(0.5))

            local current = self.CsEnv:GetCurrentDirector()
            self.timelineBlock = current.gameObject:GetComponentInChildren(typeof(ImageComp))
            KTool.SetActive(self.timelineBlock, false)
            self.BlockUI.color = Color.New(0, 0, 0, 1)
            self.BlockUI:DOColor(Color.New(0, 0, 0, 0), self.Duration)

            KTool.SetActive(self.BlockUI.transform.parent, true)
            coroutine.yield(Yielders.GetWaitForSeconds(self.Duration))
            KTool.SetActive(self.BlockUI.transform.parent, false)

            self:OpenDialog()
            self:Refresh(checkNumber(startId))
        end)
    end
end

function ChapterNewUI:InitLayout()
    KTool.SetActive(self.Dialog, false)
    KTool.SetActive(self.CreateName, false)

    if self._chapterType == ChapterConstants.ChapterType.PreDownload  then
        KTool.SetActive(self.TgAuto.transform.parent, false)
        KTool.SetActive(self.BtnUIControl, false)
        KTool.SetActive(self.BtnPlotReview, false)
    end

    self.Control.transform:SetAsLastSibling()
    KTool.SetActive(self.BtnSpeed.gameObject, false)
    self.DistortComp = self.IconHead.gameObject:GetComponent(typeof(CS.RandomDistortion))
end

function ChapterNewUI:OpenDialog()
    if not isNull(self.Tween) then
        self.Tween:Kill()
    end

    self.Tween = self.Dialog.gameObject:GetComponent(typeof(CanvasGroup)):DOFade(1, 0.25)
    if isNull(self.TxtContent:GetTextComp()) then
        return
    end
    self.TxtContent:SetText("")

    if not self.visible then
        return
    end

    --KTool.SetActive(self.DialogBtn, true)

    KTool.SetActive(self.Dialog, true)

end

function ChapterNewUI:FindStartBg(startRowId, endRowId)
    ---@type NewChapter2DVo
    local vo = self.DialogSetting:Get(startRowId)
    if vo == nil then
        return
    end

    if not string.isEmpty(vo.sceneId) and vo.type ~= NewChapterConstants.NewType.StartAnimation then
        self.startBg = {}
        self.startBg.sceneId = vo.sceneId
        self.startBg.sceneType = vo.sceneType
        return
    end
    if (vo.nextId ~= 0 or vo.nextId > endRowId) then
        self:FindStartBg(vo.nextId, endRowId)
    else
        printInfo("no start bg")
    end
end

--elseif notifyType == typeof(CS.Game.Native.QTE.QTEShowLetterMarker) then
--self:TypeLetter(notification)
--elseif notifyType == typeof(CS.Game.Native.QTE.QTESoundPlayMarker) then
--self:OnSound(notification)

function ChapterNewUI:SetAutoPlay(state)
    if state then
        if self._sequenceNext ~= nil then
            if not self.IsTyping and not self.HasOption then
                printInfo("Invoke")
                self.DialogBtn.onClick:Invoke()
            end
        end
    end
    self.AutoPlay = state
    printInfo("SetAutoPlay ")
    printInfo(state)
end

function ChapterNewUI:SetVisible(state)
    if state then
        self._preAuto = self.AutoPlay
        self.AutoPlay = false
    else
        self.AutoPlay = self._preAuto

    end
    self:FinishType()
    self.visible = not state
    KTool.SetActive(self.Dialog, not state)
    --KTool.SetActive(self.Option, not state)
    printInfo("SetVisible ")
    printInfo(state)
end

function ChapterNewUI:SetUIJumpCtrl(state)
    if not state then
        KTool.SetActive(self.DialogBtn, false)
    end
end

function ChapterNewUI:SmallSkip()

    if self._isQTEChapter then
        return false
    end

    if self._sequenceNext ~= nil then
        return false
    end

    if self.currentDirector == nil or self.currentDirector.director == nil then
        return false
    end
    
    local currentTime = self.currentDirector.director.time

    if self:IsInBlockTime(currentTime) then
        return false
    end

    local curIndex = self:GetIndex(currentTime)

    self.markerIndex = curIndex

    local checked = self:CheckIndex()
    if checked < 0 then
        return false
    end

    if self._dialogCo ~= nil then
        cs_coroutine.stop(self._dialogCo)
        self._dialogCo = nil
    end

    if self.disableCo ~= nil then
        cs_coroutine.stop(self.disableCo)
        self.disableCo = nil
    end

    if self._isPause then
        self:Resume(true)
    end

    --if checked == 1 then
    --    print("jumpEnd")
    --    self.currentDirector.controller:SetTime(self.currentDirector.director.duration - 0.02)
    --    return true
    --end

    --local index = self:GetIndex() + 1
    ----KTool.SetActive(self.DialogBtn, false)
    --local time = self.collectMarkers[index].time
    --print("jump ", time)
    --self.currentDirector.controller:SetTime(time - 0.01)
    --return true


    local index = curIndex + 1
    local destTime = checked == 1 and self.currentDirector.director.duration or self.collectMarkers[index].time

    local blockMarker = self:GetBlockMarker(currentTime, destTime)
    if not isNull(blockMarker) then
        destTime = blockMarker.time
        KTool.SetActive(self.DialogBtn, false)
    end
    local ui = self:GetBlockUI()
    if not isNull(ui) and checked ~= 1 then
        local img = ui.gameObject:GetComponent(typeof(ImageComp))
        local c = img.color
        c.a = 0
        img.color = c
    end
    self:SilenceProcess(currentTime, destTime)
    self:StopSE(self._cachedVo)
    self.currentDirector.controller:SetTime(destTime - 0.02)
    return true
end

function ChapterNewUI:Refresh(id)
    
    assert(type(id) == "number")
    if self._dialogCo ~= nil then
        cs_coroutine.stop(self._dialogCo)
        self._dialogCo = nil
    end
    
    self.DialogBtn.onClick:RemoveAllListeners()

    --printInfo("ChapterNewUI:Refresh %s %s" , tostring(id) , debug.traceback())
    if id == 0 or not self.initialized then
        --self.controller:Close()
        --Events.Broadcast(ChapterConstants.ChapterEvents.OnChapterEndDialog)

        --KTool.SetActive(self.Dialog, false)

        --KTool.SetActive(self.DialogBtn, false)

        self.Tween = self.Dialog.gameObject:GetComponent(typeof(CanvasGroup)):DOFade(0, 0.25)

        if self._isPause then
            self:Resume()
        end

        if self._teleportEffect and not isNull(self.DistortComp) then
            self.DistortComp.enabled = false
        end

        self._teleportEffect = false

        --阻挡了op7引导点击了
        KTool.SetActive(self.DialogBtn, false)
        KTool.SetActive(self.OverlayBtn, false)

        if self._sequenceNext ~= nil then
            self._sequenceNext = nil
            if self._slowClose ~= nil then
                cs_coroutine.stop(self._slowClose)
                self._slowClose = nil
            end
            self._slowClose = cs_coroutine.start(function()

                KTool.SetActive(self.BlockUI.transform.parent, true)

                self.BlockUI:DOColor(Color.New(0, 0, 0, 1), self.Duration)

                coroutine.yield(Yielders.GetWaitForSeconds(self.Duration))

                KTool.SetActive(self.BlockUI.transform.parent, false)

                local current = self.CsEnv:GetCurrentDirector()
                self.timelineBlock = current.gameObject:GetComponentInChildren(typeof(ImageComp))
                KTool.SetActive(self.timelineBlock, true)

                if KTool.IsActiveInHierarchy(self.cg.gameObject) then
                    KTool.SetActive(self.cg, false)
                end

                self._slowClose = nil

                if isNull(self.bgMovie) then
                    return
                end

                if not isNull(self.bgMovie.player) then
                    self.bgMovie:Stop()
                end

                --不能直接关 要等几帧彻底结束
                coroutine.yield()
                coroutine.yield()
                coroutine.yield()

                if KTool.IsActiveInHierarchy(self.bgMovie.gameObject) then
                    KTool.SetActive(self.bgMovie.gameObject, false)
                end
            end)
        end

        self._needHead = false

        self._afterOption = false

        self._cachedPath = nil

        self._cachedBgMovie = nil

        self._modifyModel = nil

        self._modifyBs = nil

        self._modifyRigSpeaker = nil

        return
    end

    if self.record == nil then
        self.record = {}
    end
    
    self._dialogCo = cs_coroutine.start(function()

        --携程没stop干净 临时保护 后期优化流程可去掉
        if self == nil or self.DialogSetting == nil then
            return
        end
        --coroutine.yield()
        ---@type NewChapter2DVo
        local currentDialog = self.DialogSetting:Get(id)

        if currentDialog == nil then
            printError("%d not found %d", self.CsEnv.ChapterId, id)
            return
        end

        if self._sequenceNext == nil then
            if self._afterOption == true and currentDialog.characterName ~= "我" then
                printInfo("??")
                self.Tween = self.Dialog.gameObject:GetComponent(typeof(CanvasGroup)):DOFade(0, 0.25)
                self:Refresh(0)
                return
            end
        else
            self._afterOption = nil
        end

        printInfo("refresh %d", id)

        print("dialog:", table.dump(currentDialog))

        self._cachedVo = currentDialog

        self.IsTyping = true

        self:LoadBg(currentDialog)

        self:ProcessSE(currentDialog)

        self:SetContentName(currentDialog.characterName)

        self:SetIconHead(currentDialog.avatar)

        local content = self:FillPlaceHold(currentDialog.desc, currentDialog.characterName)

        --if currentDialog.type ~= NewChapterConstants.NewType.ChapterOption  then
        if not NewChapterUtils.HasOption(currentDialog) then
            if not (self.recordCell ~= nil and self.recordCell.owner == currentDialog.characterName and self.recordCell.content == content) then
                self.recordCell = {}
                self.recordCell.owner = currentDialog.characterName
                printInfo("insert %s", table.dump(self.recordCell))
                table.insert(self.record, self.recordCell)
            end
            
        end

        if not string.isEmpty(content) then
            self.recordCell.content = content
        end

        --self.TxtContent.text = "invaild parameters " .. id
        KTool.SetActive(self.grid.gameObject, false)

        -- 点击屏幕可以立刻finish打字机的效果
        local dialogClick = function()
            if self.BlockClick then
                return
            end

            --if self:SmallSkip() then
            --    return
            --end

            if self._isQTEChapter then
                return
            end

            if not self.AutoPlay then
                self.DialogBtn.onClick:RemoveAllListeners()

                self:FinishType()

            end
            --printInfo("DialogBtn")
        end

        self:SetButtonClick(self.DialogBtn, dialogClick)

        KTool.SetActive(self.DialogBtn, true);

        self.HasOption = not string.isEmpty(currentDialog.option)


        --self:ProcessEvent(currentDialog.event, currentDialog.parameter)

        local txtContent = self.TxtContent
        txtContent.AppearDuration = 0.2
        txtContent.PendingTime = self:GetPendingTime()
        txtContent.TextWillFill = content
        txtContent.SplitlineEffect = false

        self._wait = true

        self._waitCo = cs_coroutine.start(function()

            coroutine.yield(txtContent:StartType())

            self._wait = false
        end)

        if self._blockWait ~= nil and self._blockWait > 0 then

            local cached = self.BlockClick == true
            self.BlockClick = true
            self._blockCo = cs_coroutine.start(function()

                printInfo("start " .. tostring(self.BlockClick))
                printInfo("wait " .. tostring(self._blockWait))

                coroutine.yield(Yielders.GetWaitForSeconds(self._blockWait))

                self.BlockClick = cached

                printInfo("end " .. tostring(self.BlockClick))
            end)


        end

        while self._wait do
            coroutine.yield()
        end

        if self._waitCo ~= nil then
            cs_coroutine.stop(self._waitCo)
        end
        self._waitCo = nil

        if isNull(txtContent:GetTextComp()) then
            return
        end

        txtContent:StopType()
        txtContent:ShowAll()

        printInfo("finish type")
        self.IsTyping = false
        if self.HasOption then

            --print_to_file(currentDialog.option)
            local split = currentDialog.option
            local len = #split
            local subsplit = currentDialog.jumpId

            --KTool.SetActive(self.grid.gameObject, true)
            if not isNull(self.recordCell) then
                self.recordCell.option = {}
            end
            for i = 1, self.grid.childCount do

                local btn = self.grid:GetChild(i - 1).gameObject:GetComponent(typeof(ButtonComp))
                KTool.SetActive(btn.gameObject, i <= len)
                if i <= len then
                    --printInfo(split[i + len - self.grid.childCount])
                    printInfo(split[i])
                    ---@type NewChapterOptionVo
                    --local vo = self.OptionSetting:Get(split[i])
                    local optionContent = self:FillPlaceHold(split[i])

                    if not isNull(self.recordCell) then

                        table.insert(self.recordCell.option, optionContent)
                    end
                    btn.transform:GetChild(0):Find("Text"):GetComponent(typeof(TextComp)).text = optionContent
                    self:SetButtonClick(btn, function()
                        --printInfo(subsplit[2])
                        if self.BlockClick then
                            return
                        end
                        --self.DialogBtn.onClick:RemoveAllListeners()

                        if not isNull(self.recordCell) then
                            self.recordCell.selectIndex = i
                        end
                        --cs_coroutine.stop(self._dialogCo)
                        printInfo(subsplit[i])

                        self._afterOption = true

                        self.HasOption = false
                        
                        self:Refresh(tonumber(subsplit[i]))
                    end)
                end

            end
            KTool.SetActive(self.grid.gameObject, true)
            self.DialogBtn.onClick:RemoveAllListeners()
            KTool.SetActive(self.DialogBtn, false)
        else
            --self.recordCell.content = content

            --self.HasOption = false
            printInfo("?！")
            KTool.SetActive(self.grid.gameObject, false)
            self:SetButtonClick(self.DialogBtn, function()
                if self.BlockClick then
                    return
                end

                if not self.AutoPlay then
                    if self._sequenceNext ~= nil then

                        if isSet(self._sequenceNext, currentDialog.id) then
                            self:Refresh(self._sequenceNext[currentDialog.id])
                        else
                            self:Refresh(currentDialog.nextId)
                        end
                        return
                    end

                    --if self._overrideNext then
                    --    self._overrideNext = false
                    --    self:Refresh(0)
                    --    printInfo("override")
                    --
                    --else
                    --    
                    --    self:Refresh(currentDialog.nextId)
                    --end

                    if self:SmallSkip() then
                        return
                    end


                end


            end)
        end

        --self._finishCall()
        --self._finishCall = nil
        --
        --self._dialogCo = nil

        self:ResetArgs()

        self._finishCall = nil


        if self._afterOption then
            self._afterOption = nil
            self._dialogCo = nil
            
            self.disableCo = cs_coroutine.start(function()
                KTool.SetActive(self.OverlayBtn, true)
                coroutine.yield(Yielders.GetWaitForSeconds(0.5))
                self:Refresh(0)
                self.disableCo = nil
            end)
        else
            if self.AutoPlay or self._convertAuto then
                if self.HasOption then
                    self._convertAuto = nil
                    return
                end

                local wait = nil
                if self._convertAuto then
                    self._convertAuto = nil
                    printInfo("AutoSkip Invoke")

                    wait = 0.5
                else
                    wait = 1
                    printInfo("AutoPlay Invoke")

                    while not self.voiceFinish do
                        coroutine.yield()
                    end
                end

                if not isNull(self.disableCo) then
                    coroutine.yield(self.disableCo)
                else
                    coroutine.yield(Yielders.GetWaitForSeconds(wait))

                    self._dialogCo = nil

                    if self._sequenceNext ~= nil then
                        if isSet(self._sequenceNext, currentDialog.id) then
                            self:Refresh(self._sequenceNext[currentDialog.id])
                        else
                            self:Refresh(currentDialog.nextId)
                        end
                    else
                        self:Refresh(0)
                    end
                end

            else
                self._dialogCo = nil
            end
        end

        

    end)

end

function ChapterNewUI:GetPendingTime()
    if GameUtils.IsEnglish() or GameUtils.IsTh() then
        return 0.01
    end
    return 0.05
end

---@param vo NewChapter2DVo
function ChapterNewUI:StartOption(vo)
    --printInfo(table.dump(vo.option))

    --self.recordCell.type = NewChapterConstants.RecordType.Option
    if not KTool.IsActiveInHierarchy(self.Dialog) then
        KTool.SetActive(self.Dialog, true)
    end
    self.recordCell.option = {}
    local len = #vo.option
    if #vo.option > 0 then
        self.HasOption = true;
        --printInfo(table.dump(vo.option))
        --print_to_file(currentDialog.option)
        --local split = string.split(currentDialog.option, "|")
        --local len = rawlen(split)
        --KTool.SetActive(self.grid.gameObject, true)
        --for i = 1, self.grid.childCount do
        --
        --    local btn = self.grid:GetChild(i - 1).gameObject:GetComponent(typeof(ButtonComp))
        --    KTool.SetActive(btn.gameObject, i > self.grid.childCount - len)
        --    if i > self.grid.childCount - len then
        --        --printInfo(split[i + len - self.grid.childCount])
        --        --printInfo("option %d", vo.option[i])
        --        ---@type NewChapterOptionVo
        --        local optionVo = self.OptionSetting:Get(vo.option[i + len - self.grid.childCount])
        --        
        --        btn.transform:GetChild(0).gameObject:GetComponent(typeof(TextComp)).text = optionVo.desc
        --        self:SetButtonClick(btn, function()
        --            --printInfo(subsplit[2])
        --            if self.BlockClick then
        --                return
        --            end
        --            self.DialogBtn.onClick:RemoveAllListeners()
        --
        --            self:Refresh(tonumber(vo.jumpId[i]))
        --        end)
        --    end
        --
        --end

        local wait = true

        for i = 1, self.grid.childCount do
            local btn = self.grid:GetChild(i - 1).gameObject:GetComponent(typeof(ButtonComp))
            KTool.SetActive(btn.gameObject, i <= len)
            if i <= len then

                --printInfo(vo.option[i])
                ---@type NewChapterOptionVo
                local optionVo = self.OptionSetting:Get(checkNumber(vo.option[i]))
                local content = self:FillPlaceHold(optionVo.desc)
                table.insert(self.recordCell.option, content)

                btn.transform:GetChild(0).gameObject:GetComponent(typeof(TextComp)).text = content
                self:SetButtonClick(btn, function()
                    --printInfo(subsplit[2])
                    if self.BlockClick then
                        return
                    end
                    self.DialogBtn.onClick:RemoveAllListeners()

                    --self:Refresh(tonumber(vo.jumpId[i]))
                    self.recordCell.selectIndex = i
                    self.GotoNext = checkNumber(vo.jumpId[i])
                    if self._endCo then
                        printInfo("%s", tostring(self._endCo))
                        self.HasOption = false

                        self:ClearOption()

                        if KTool.IsActiveInHierarchy(self.Dialog) then
                            self.Tween = self.Dialog.gameObject:GetComponent(typeof(CanvasGroup)):DOFade(0, 0.25)
                        end
                        
                        self:Refresh(tonumber(vo.jumpId[i]))
                    end

                    wait = false
                end)
            end
        end

        KTool.SetActive(self.grid.gameObject, true)
        self.DialogBtn.onClick:RemoveAllListeners()
        KTool.SetActive(self.DialogBtn.gameObject, false)

        while wait do
            coroutine.yield(Yielders.EndOfFrame)
        end

        
    end
end

---@param vo NewChapter2DVo
function ChapterNewUI:ProcessMusic(vo)
    -- print("[声音] ChapterNewUI ProcessMusic", table.dump(vo, nil, 3))
    if not string.isEmpty(vo.music) then
        --AudioManager:StopMusic()
        --AudioManager:PlayMusic(vo.music, NewChapterConstants.AudioMarker)
        --CriWareUtils.PlayMusic(vo.music[1], vo.music[2])
        if self.soundRecord == nil then
            self.soundRecord = {}
        end

        if vo.music == "-1" then
            if self.soundRecord.bgm ~= nil then
                CriWareUtils.StopById(self.soundRecord.bgm)
            end
            self.soundRecord.bgm = nil
        else
            CriWareUtils.PlayMusicById(vo.music)
            self.soundRecord.bgm = vo.music

            if self.soundRecord.bgmRecord == nil then
                self.soundRecord.bgmRecord = {}
            end
            table.insert(self.soundRecord.bgmRecord, vo.music)
        end
    end
end

---@param vo NewChapter2DVo
function ChapterNewUI:ProcessSE(vo)
    -- print("[声音] ChapterNewUI ProcessSE", table.dump(vo, nil, 3))
    --if not string.isEmpty(vo.music) then
    --    --AudioManager:StopMusic()
    --    --AudioManager:PlayMusic(vo.music, NewChapterConstants.AudioMarker)
    --    CriWareUtils.PlayMusic(vo.music[1], vo.music[2])
    --end
    if not self._isQTEChapter then
        self:ProcessMusic(vo)

        if not string.isEmpty(vo.sound) then
            --AudioManager:EnsurePlaySFX(vo.sound, NewChapterConstants.AudioMarker)
            CriWareUtils.PlaySeById(vo.sound)

            if self.soundRecord.SERecord == nil then
                self.soundRecord.SERecord = {}
            end
            table.insert(self.soundRecord.SERecord, vo.sound)
        end

        if not string.isEmpty(vo.loopSE) then
            --AudioManager:EnsurePlaySFX(vo.loopSE, NewChapterConstants.AudioMarker)
            CriWareUtils.PlaySeById(vo.loopSE)

            -- 把所有播放过的音效都记录下来，退出剧情的时候全都关掉
            if self.soundRecord.loopSERecord == nil then
                self.soundRecord.loopSERecord = {}
            end
            table.insert(self.soundRecord.loopSERecord, vo.loopSE)
        end
    end

    self.voiceFinish = false
    if not string.isEmpty(vo.voice) then
        --AudioManager:EnsurePlaySFX(vo.voice, NewChapterConstants.AudioMarker)
        local tmp = self:GetSpeaker(vo)
        printInfo("voice %s %s", vo.voice, tostring(tmp))

        local slice = CriWareUtils.PlaySeById(vo.voice, tmp)
        if not isNull(slice) then
            if not isNull(tmp) then
                local arr = tmp.gameObject:GetComponentsInChildren(typeof(CS.UnityEngine.SkinnedMeshRenderer), true)
                self._modifyModel = {}
                for i = 1, arr.Length do
                    local model = arr[i - 1]
                    local str = model.name
                    if str == "face" or str == "mouth" then
                        local t = {}
                        t.skinned = model
                        t.willModify = {}
                        for j = 1, model.sharedMesh.blendShapeCount do
                            if NewChapterUtils.NeedModify(model.sharedMesh:GetBlendShapeName(j - 1)) then
                                table.insert(t.willModify, j - 1)
                            end
                        end
                        table.insert(self._modifyModel, t)
                    end
                    self._modifyBs = true
                end
                self._modifyRigSpeaker = tmp.gameObject:GetInstanceID()
                -- printInfo("will modify %s %s %s", tostring(self._modifyBs), self._modifyRigSpeaker, tostring(table.dump(self._modifyModel)))

            else
                self._modifyBs = false
                self._modifyModel = nil
                self._modifyRigSpeaker = nil
            end

            slice.onFinish = function()
                self.voiceFinish = true
                printInfo("voice finish %s", vo.voice)
            end
        else
            self._modifyBs = false
            self._modifyModel = nil
            self._modifyRigSpeaker = nil
            self.voiceFinish = true
        end

    else
        self.voiceFinish = true
    end
end

function ChapterNewUI:StopSE(vo)
    if not self._isQTEChapter then
        --self:ProcessMusic(vo)

        if not string.isEmpty(vo.sound) then
            --AudioManager:EnsurePlaySFX(vo.sound, NewChapterConstants.AudioMarker)
            CriWareUtils.StopById(vo.sound)
        end

        if not string.isEmpty(vo.loopSE) then
            --AudioManager:EnsurePlaySFX(vo.loopSE, NewChapterConstants.AudioMarker)
            CriWareUtils.StopById(vo.loopSE)
        end

        if not string.isEmpty(vo.voice) then
            CriWareUtils.StopById(vo.voice)
        end
    end
end

--- 预处理收集嘴巴的骨骼和初始位置信息
function ChapterNewUI:PreprocessSpeakerMouse()
    self._speakerMouseRigs = {}
    self._speakerMouseRigsDefaults = {}

    local current = self.CsEnv.transform.parent

    local lips = current.gameObject:GetComponentsInChildren(typeof(CS.CriWare.CriLipsDeformerForAtomSource), true)
    for i = 1, lips.Length do
        local tmp = lips[i - 1].gameObject
        local rigs = ChapterUtils.CollectMouseRig(tmp.transform)
        if table.count(rigs) > 0 then
            self._speakerMouseRigs[tmp:GetInstanceID()] = rigs

            local rigDefaults = {}
            for i, rig in ipairs(rigs) do
                local defaultValue = {}
                defaultValue.pos = rig.localPosition
                defaultValue.rot = rig.localRotation
                defaultValue.scl = rig.localScale

                table.insert(rigDefaults, defaultValue)
            end
            self._speakerMouseRigsDefaults[tmp:GetInstanceID()] = rigDefaults
        end
    end

    -- print("[嘴型] 预处理", table.dump(self._speakerMouseRigs, nil, 3), table.dump(self._speakerMouseRigsDefaults, nil ,3))
end

---@param vo ChapterDialogVo
function ChapterNewUI:GetSpeaker(vo)
    if vo.speaker == 0 then
        return nil
    end

    --local current = self.CsEnv:GetCurrentDirector()
    --if isNull(current) then
    --    return nil
    --end
    local current = self.CsEnv.transform.parent

    if self._speakers == nil then
        self._speakers = {}
    end

    if isSet(self._speakers, vo.speaker) then
        if KTool.IsActiveInHierarchy(self._speakers[vo.speaker]) then
            return self._speakers[vo.speaker]
        end
    end

    local lips = current.gameObject:GetComponentsInChildren(typeof(CS.CriWare.CriLipsDeformerForAtomSource))
    for i = 1, lips.Length do
        local tmp = lips[i - 1].gameObject.name
        printInfo("%s %d", tmp, tostring(vo.speaker))
        if string.contains(tmp, tostring(vo.speaker)) or string.contains(tostring(vo.speaker), tmp) then
            self._speakers[vo.speaker] = lips[i - 1].gameObject
            printInfo("found %s %s ", tostring(vo.speaker), tostring(lips[i - 1].gameObject))
            break
        end
    end

    if self._speakers[vo.speaker] == nil and self.CsEnv.IsQTEChapter then
        local roleRoot = CS.UnityEngine.GameObject.Find("Role")
        if not isNull(roleRoot) then
            local tlLip = roleRoot:GetComponentsInChildren(typeof(CS.CriWare.CriLipsDeformerForAtomSource))
            for i = 1, tlLip.Length do
                local tmp = tostring(vo.speaker)
                --vo.speaker 108008
                --tltip 主界面上的人 108
                if string.contains(tmp, tlLip[i - 1].gameObject.name) then
                    self._speakers[vo.speaker] = tlLip[i - 1].gameObject
                    break
                end
            end
        end

    end

    return self._speakers[vo.speaker]
end

function ChapterNewUI:GetCharacter(characterId)
    local dirTrans = self.currentDirector.director.transform
    local charParentName = characterId .. "_loc"
    local tmpTrans = dirTrans:Find("allposition")
    if isNull(tmpTrans) then
        tmpTrans = dirTrans:Find(charParentName)
    end
    if isNull(tmpTrans) then
        return nil
    end

    local r = tmpTrans:Find(characterId)
    if not isNull(r) then
        r = r.gameObject
    end
    return r
end

function ChapterNewUI:SetCharacterLoop(modelBinder)
    local characterId = modelBinder.ModelName
    if string.isEmpty(characterId) then
        return
    end
    local model = self:GetCharacter(characterId)
    if isNull(model) then
        return
    end
    local overrideBinder = model:EnsureComponent(typeof(AnimatorOverrideBinder))
    --if not overrideBinder:HasInsController() then
    --    overrideBinder:SetRuntimeController(self.simpleController.obj)
    --end
    --overrideBinder:SetOverrideClip("SimpleFirst", modelBinder.LoopClip)
    --overrideBinder:SetOverrideClip("FaceFirst", modelBinder.FaceLoop)
    --overrideBinder:ApplyOverride()
    local trackName = characterId .. "_ani"
    local track = self:GetTrackByName(self.currentDirector.director, trackName)
    if isNull(track) then
        track = self:GetTrackByName(self.currentDirector.director, characterId)
    end
    --printInfo(track:GetType())
    --self.currentDirector:ClearGenericBinding(track)
    --overrideBinder:PlayClipOnGraph(modelBinder.LoopClip)
    overrideBinder:PlayMixerGraph()
end

function ChapterNewUI:FillPlaceHold(origin, ownerId)
    local playerComp = ChapterUtils.GetPlayerComp()
    local result = origin
    result = ChapterUtils.ReplaceStr(result, "#playerName", playerComp.playerDojo.playerName)
    result = ChapterUtils.ReplaceStr(result, "#playerId", playerComp.playerDojo.playerId)
    result = ChapterUtils.ReplaceStr(result, "/n", "\n")
   -- result = ChapterUtils.ReplaceStr(result, " ", NonBreakingSpace)

    --if isSet(ChapterConstants.ChapterScheme, ownerId) then
    --    result = string.format(ChapterConstants.ChapterScheme[ownerId].scheme, result)
    --end

    if self.CsEnv.ChapterId == 1000002 then
        -- local day = math.ceil((ChapterConstants.PreDownloadDestTime - os.time()) / 86400)
        -- local str = localize("_days_天", { _days_ = day })
        local str = CfUtils.GetTimeHumanize(ChapterConstants.PreDownloadDestTime - os.time())
        result = ChapterUtils.ReplaceStr(result, "#timeStr", str)
    end

    return result
end

function ChapterNewUI:ProcessEvent(event, param)
    --assert(type(event) == "string")

    --todo [string "Game.Chapter.ChapterNewUI"]:473: attempt to concatenate a nil value
    --print("event" .. table.dump(event))
    for i = 1, #event do
        if event[i] == "Resume" then
            --self.Processor.DirectorControl:ResumeCurrent()
            --self._processor:ResumeDirector()
            self.CsEnv:ResumeDirector()
        elseif event[i] == "SplitlineEffect" then
            self._splitlineEffect = true
        elseif event[i] == "Wait" then
            self._blockWait = checkNumber(param[i])
        end
    end

end

function ChapterNewUI:ResetArgs()
    self._splitlineEffect = false
    self._blockWait = 0
end

function ChapterNewUI:SetIconHead(icon)

    if not isNull(self.DistortComp) then
        self.DistortComp.enabled = self._teleportEffect
    end

    if self._cachedPath ~= icon then


        self._cachedPath = icon

        if not self._needHead then
            KTool.SetActive(self.IconHead.gameObject, false)
            KTool.SetActive(self.IconHead.transform.parent, false)
            return
        end

        if string.isEmpty(icon) then
            KTool.SetActive(self.IconHead.gameObject, false)
            KTool.SetActive(self.IconHead.transform.parent, false)
            return
        end

        if not KTool.IsActiveInHierarchy(self.IconHead.transform.parent) then
            KTool.SetActive(self.IconHead.transform.parent, true)
        end

        if not KTool.IsActiveInHierarchy(self.IconHead.gameObject) then
            KTool.SetActive(self.IconHead.gameObject, true)
        end

        printInfo("head %s", icon)

        self.IconHead.isNativeSize = false
        self.IconHead:LoadSprite(icon, ChapterConstants.ChapterPool)
    end

    --if self._teleportEffect then
    --    local dis = self.IconHead.gameObject:GetComponent(typeof(CS.RandomDistortion))
    --    dis.enabled = true
    --end
end

function ChapterNewUI:LoadBg(vo)
    if isNull(self.cg) then
        return
    end

    if self._sequenceNext == nil then
        return
    end

    if string.isEmpty(vo.sceneId) then
        --KTool.SetActive(self.cg.gameObject, false)
        return
    end

    if self._slowClose ~= nil then
        cs_coroutine.stop(self._slowClose)
        self._slowClose = nil
    end

    if vo.sceneType == NewChapterConstants.BgType.BgMovie then

        if isNull(self.bgMovie) then
            return
        end

        if not KTool.IsActiveInHierarchy(self.bgMovie.gameObject) then
            KTool.SetActive(self.bgMovie.gameObject, true)
        end

        if self._cachedBgMovie == vo.sceneId then
            return
        end

        self._cachedBgMovie = vo.sceneId

        if self._cachedBgCo ~= nil then
            cs_coroutine.stop(self._cachedBgCo)
            self._cachedBgCo = nil
        end

        printInfo("status %s", tostring(self.bgMovie.player.status))
        if self.bgMovie.player.status ~= CS.CriWare.CriMana.Player.Status.Playing then
            self.bgMovie.player:SetFile(nil, GameUtils.GetManaPath(vo.sceneId))
            self.bgMovie:Play()

            printInfo("play %s", vo.sceneId)

        else

            self._cachedBgCo = cs_coroutine.start(function()
                local wait = true
                self.bgMovie.player.statusChangeCallback = function(status)
                    printInfo("status %s", tostring(status))
                    if status == CS.CriWare.CriMana.Player.Status.Stop then
                        wait = false
                    end
                end

                self.bgMovie:Stop()

                while wait do
                    coroutine.yield()
                end

                self.bgMovie.player.statusChangeCallback = nil

                printInfo("play %s", vo.sceneId)

                self.bgMovie.player:SetFile(nil, GameUtils.GetManaPath(vo.sceneId))
                self.bgMovie:Play()

                self._cachedBgCo = nil
            end)
        end

    else

        if not isNull(self.bgMovie) then
            if not isNull(self.bgMovie.player) then
                self.bgMovie:Stop()
            else

            end
            if KTool.IsActiveInHierarchy(self.bgMovie.gameObject) then
                KTool.SetActive(self.bgMovie.gameObject, false)
            end
        end

        if vo.type == NewChapterConstants.NewType.StartCgPlay then

            if not KTool.IsActiveInHierarchy(self.cg.gameObject) then
                KTool.SetActive(self.cg.gameObject, true)
            end

            --NewChapterShared:LoadSprite(self.cg, vo.sceneId)
            printInfo("LoadBg %s", vo.sceneId)

            self.cg:LoadSprite(vo.sceneId)
        elseif vo.type == NewChapterConstants.NewType.EndCgPlay then

            if KTool.IsActiveInHierarchy(self.cg.gameObject) then
                KTool.SetActive(self.cg.gameObject, false)
            end

        elseif vo.type == NewChapterConstants.NewType.KeepCgPlay then

        else
            if not KTool.IsActiveInHierarchy(self.cg.gameObject) then
                KTool.SetActive(self.cg.gameObject, true)
            end

            printInfo("LoadBg %s", vo.sceneId)
            self.cg:LoadSprite(vo.sceneId)
        end
    end

    --if not KTool.IsActiveInHierarchy(self.cg.gameObject) then
    --    KTool.SetActive(self.cg.gameObject, true)
    --end
    --
    --printInfo("LoadBg %s", vo.sceneId)
    --self.cg:LoadSprite(vo.sceneId)
end

function ChapterNewUI:SetContentName(owner)
    assert(type(owner) == "string")
    --self.TxtLeftName.text = owner
    --KTool.SetActive(self.LeftTitle.gameObject, not string.isEmpty(owner))
    local st = not string.isEmpty(owner)
    KTool.SetActive(self.Titles, st)
    if st then
        local playerComp = ChapterUtils.GetPlayerComp()
        local str = ChapterUtils.ReplaceStr(owner, "#playerName", playerComp.playerDojo.playerName)
        self.TxtLeftName.text = str
    end
end

function ChapterNewUI:SetButtonClick(button, callback)
    if button and button.onClick then
        button.onClick:RemoveAllListeners()
        button.onClick:AddListener(callback)
    else
        print("set click event failed ,type not button")
    end
end

function ChapterNewUI:FinishType()
    if self.IsTyping then
        --if self._dialogCo ~= nil then
        --    cs_coroutine.stop(self._dialogCo)
        --    self._dialogCo = nil
        --end
        --local txtContent = self.TxtContent
        --txtContent:StopType()
        --txtContent:ShowAll()
        --if self._finishCall ~= nil then
        --    self._finishCall()
        --    self._finishCall = nil
        --end
        --self.TxtContent:InvokeEndCall()
        self._wait = false
    end
end

function ChapterNewUI:OnLateUpdate()
    self:ModifyMouseBlendShapeWeight()
    self:ModifyMouseRig()
end

function ChapterNewUI:ModifyMouseBlendShapeWeight()
    if not self._modifyBs or isNull(self._modifyModel) then
        return
    end

    --printInfo("will modify %s %s", tostring(self._modifyBs), tostring(table.dump(self._modifyModel)))

--[[    for i, v in pairs(self._modifyModel) do

        --printInfo(table.dump(v.willModify))
        
        for ii, vv in pairs(v.willModify) do
            v.skinned:SetBlendShapeWeight(vv, 0)
        end

    end]]
    --printInfo("modify ")
end

function ChapterNewUI:ModifyMouseRig()
    if isNull(self._modifyRigSpeaker) then return end

    local rigs = self._speakerMouseRigs[self._modifyRigSpeaker]
    local rigDefaults = self._speakerMouseRigsDefaults[self._modifyRigSpeaker]

    if isNull(rigs) or isNull(rigDefaults) then
        return
    end

    -- for i, rig in ipairs(rigs) do
    --     local defaults = rigDefaults[i]
    --     rig.localPosition = Vector3.zero
    --     rig.localRotation = Quaternion.identity
    --     rig.localScale = Vector3.one
    -- end

    for i, rig in ipairs(rigs) do
        local defaults = rigDefaults[i]
        rig.localPosition = defaults.pos
        rig.localRotation = defaults.rot
        rig.localScale = defaults.scl
    end
end

function ChapterNewUI:OnDestroy()
    --self.TxtContent:StopType()
    if self.disableCo ~= nil then
        cs_coroutine.stop(self.disableCo)
        self.disableCo = nil
    end
    if self._waitCo ~= nil then
        cs_coroutine.stop(self._waitCo)
        self._waitCo = nil
    end
    if self._dialogCo ~= nil then
        cs_coroutine.stop(self._dialogCo)
        self._dialogCo = nil
    end

    if self._slowClose ~= nil then
        cs_coroutine.stop(self._slowClose)
        self._slowClose = nil
    end

    if self._cachedBgCo ~= nil then
        cs_coroutine.stop(self._cachedBgCo)
        self._cachedBgCo = nil
    end

    if self.seqCo ~= nil then
        cs_coroutine.stop(self.seqCo)
        self.seqCo = nil
    end

    if self._lateUpdater ~= nil then
        MonoHelper.RemoveLateUpdateListener(self._lateUpdater)
    end

    if not isNull(self.CsEnv) then
        local lips = self.CsEnv.transform.parent.gameObject:GetComponentsInChildren(typeof(CriLipsDeformerForAtomSource), true)
        if not isNull(lips) then
            for i = 1, lips.Length do
                local tmp = lips[i - 1]
                if not isNull(tmp.atomAnalyzer) then
                    tmp.atomAnalyzer:Dispose()
                end
            end
        end
    end

    self.controller = nil--luabehaviour 中CSharp对象
    self:Delete()
    self = nil
end

function ChapterNewUI:GetTrackByType(director, trackType)
    local list = support.new_list(typeof(CS.UnityEngine.Timeline.TrackAsset))
    list:AddRange(director.playableAsset:GetOutputTracks())

    local track = nil
    --printInfo(trackName)
    for i = 0, list.Count - 1 do
        if list[i]:GetType() == trackType then
            --printInfo(mute)
            track = list[i]
            break
        end
    end

    return track
end

function ChapterNewUI:GetTrackByName(director, name)
    local list = support.new_list(typeof(CS.UnityEngine.Timeline.TrackAsset))
    list:AddRange(director.playableAsset:GetOutputTracks())

    local track = nil
    --printInfo(trackName)
    for i = 0, list.Count - 1 do
        if list[i].name == name then
            --printInfo(mute)
            track = list[i]
            break
        end
    end

    return track
end

function ChapterNewUI:GetMarkers(track)
    if isNull(track) then
        return
    end
    local list = support.new_list(typeof(CS.UnityEngine.Timeline.IMarker))
    list:AddRange(track:GetMarkers())

    --for i = 1, list.Count do
    --    local index = i - 1
    --    printInfo(tostring(list[index]:GetType()) .. " " .. tostring(list[index].time) )
    --end
    --

    return list
end

return ChapterNewUI