---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by win 10.
--- DateTime: 2019/4/15 11:40
---

local UICardIntens = {
    Name = UIWindowNames.UICardIntens,
    Layer = UILayers.BackgroudLayer,
    Model = require "UI.UIIntens.UICardIntens.UICardIntensModel",
    Ctrl = require "UI.UIIntens.UICardIntens.UICardIntensCtrl",
    View = require "UI.UIIntens.UICardIntens.UICardIntensView",
    PrefabPath = "UI/Prefabs/UI/Intens/UICardIntens.prefab",
}


return {UICardIntens = UICardIntens}