---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gaole.
--- DateTime: 2021-09-29 16:43:59
---
local CoWait = CS.Engine.Lib.CoWait
local util = require 'XLua.util'
local KTool = CS.Engine.Lib.KTool
local UIModule = CS.Engine.UI.UIModule
local CookingFoodVo = import("Game.Setting.Vo.CookingFoodVo")
local UIMainInteractionCookingMenuFoodNode = "Game.UI.Phone.Cooking.MainInteractionCooking.MainInteractionCookingMenu.UIMainInteractionCookingMenuFoodNode"
local PageFoodCount = 9
local comp = GameUtils.GetEntityCompByType(ECSComponentType.Constants.CookingComponent)
local CookingUtils = import('Game.UI.Phone.Cooking.CookingUtils')
local Yielders = CS.Engine.Lib.Yielders
local RolesShowMgr = import('Game.Robot.RolesShowMgr')
local cs_coroutine = import('XLua.cs_coroutine')
local WaitForSeconds = CS.UnityEngine.WaitForSeconds

---@class UIMainInteractionCookingMenuDialog
---@field TxtTitle                      	UnityEngine.RectTransform               
---@field BtnLeft                       	UnityEngine.RectTransform               
---@field BtnRight                      	UnityEngine.RectTransform               
---@field LoopGridView                  	SuperScrollView.LoopGridView            
---@field Text                          	UnityEngine.RectTransform               
---@field AnimRoot                      	UnityEngine.RectTransform               
---@field Root                          	UnityEngine.RectTransform               
local UIMainInteractionCookingMenuDialog = Class("UIMainInteractionCookingMenuDialog")
             
function UIMainInteractionCookingMenuDialog:__init() 
    self._allBattleFoodData = {}            --所有的战斗料理
    self._curPageInd = 1                    --当前的下标
    self._curPageFoodData = {}              --当前页面食物数据
end

function UIMainInteractionCookingMenuDialog:__delete()
    self._allBattleFoodData = {}            --所有的战斗料理
    self._curPageInd = 1                    --当前的下标
    self._curPageFoodData = {}              --当前页面食物数据
end

function UIMainInteractionCookingMenuDialog:Awake()
    self.EventBattleFoodCollectChange = Events.AddListener(Constants.EventNames.BattleFoodCollectChange, Bind(self, self.OnBattleFoodCollectChange))

    SetButtonAction(self.BtnLeft, Bind(self, self.OnBtnLeft))
    SetButtonAction(self.BtnRight, Bind(self, self.OnBtnRight))
    SetButtonAction(self.BtnLunchBox, Bind(self, self.OnBtnBackPack))

    self:InitData()
    self:RefreshFoodView()

    self:RefreshArrow()
    self:RefreshPagePoints()
end

function UIMainInteractionCookingMenuDialog:OnBattleFoodCollectChange()
    self:RefreshFoodView()
end

--背包
function UIMainInteractionCookingMenuDialog:OnBtnBackPack()
    UIModule.OpenDialog({ id = Constants.UITypeIds.Backpack, parameters = {type = 4}}, { { id = Constants.UITypeIds.UIMainInteractionCookingMenuDialog } })
end

--
function UIMainInteractionCookingMenuDialog:InitData()
    self._allBattleFoodData = {}

    local t = self:GetAllBattleFoodData()
    local _t = {}
    for k, v in pairs(t) do
        table.insert(_t, v)

        if table.count(_t) == PageFoodCount then
            table.insert(self._allBattleFoodData, _t)
            _t = {}
        elseif k == table.count(t) then 
            table.insert(self._allBattleFoodData, _t)
            _t = {}
        end
    end
end

--所有的套餐食品
function UIMainInteractionCookingMenuDialog:GetAllBattleFoodData()
    local t = CfUtils.GetCfTable(AutoIds.IdSetting2017)
    if not t then
        return {}
    end
    local _t = {}
    local useVo 
    for k, v in pairs(t) do
        local vo = CookingFoodVo.New()
        vo:FillVo(v)

        local isCurUse, num = CookingUtils.IsUseBattleFood(vo.id)
        if isCurUse then
            useVo = vo
        else
            table.insert(_t, vo)
        end
    end 

    for i = 1, #_t - 1 do
        for j = i + 1, #_t do
            local vo1 = _t[i]
            local vo2 = _t[j]
            local isChange = false
            if CookingUtils.IsUnlockFood(vo2.id) and not CookingUtils.IsUnlockFood(vo1.id) then
                isChange = true
            elseif CookingUtils.IsUnlockFood(vo2.id) and CookingUtils.IsUnlockFood(vo1.id) then
                if CookingUtils.IsCollectFood(vo2.id) and not CookingUtils.IsCollectFood(vo1.id) then
                    isChange = true
                else
                    isChange = checkNumber(vo2.id) < checkNumber(vo1.id)
                end
            else
                isChange = checkNumber(vo2.id) < checkNumber(vo1.id)
            end
            if isChange then
                local buffer = _t[i]
                _t[i] = _t[j]
                _t[j] = buffer
            end
        end
    end
    if useVo then
        table.insert(_t, 1, useVo)
    end
    --[[
    table.sort(_t, function(a, b)
        if (CookingUtils.IsUnlockFood(b.id) and CookingUtils.IsUnlockFood(a.id)) or ((not CookingUtils.IsUnlockFood(b.id)) and (not CookingUtils.IsUnlockFood(a.id))) then
            if not CookingUtils.IsCollectFood(b.id) and CookingUtils.IsCollectFood(a.id) then
                return true
            else
                return checkNumber(a.id) < checkNumber(b.id)
            end
        elseif not CookingUtils.IsUnlockFood(b.id) and CookingUtils.IsUnlockFood(a.id) then
            return false
        else
            return checkNumber(a.id) < checkNumber(b.id)
        end
        return false
    end)
    ]]
    return _t
end

--绘制
function UIMainInteractionCookingMenuDialog:RefreshFoodView()
    self._curPageFoodData = self:GetCurPageFoodData()
    if not self._isInitRoleView then
        self.LoopGridView:InitListView(#self._curPageFoodData, Bind(self, self.OnGetFoodCellByIndex))
        self.LoopGridView.mOnSnapNearestChanged = Bind(self, self.OnSnapNearestChanged)
        self._isInitRoleView = true
    else
        --GameUtils.ReloadData(self.LoopGridView, 0)
        GameUtils.ReloadData(self.LoopGridView, #self._curPageFoodData)
        self.LoopGridView:MovePanelToItemIndex(0)
    end
end

function UIMainInteractionCookingMenuDialog:OnSnapNearestChanged(listView, item)
    local ind = self.LoopGridView.CurSnapNearestItemIndex

    self._curPageInd = ind + 1
    --self:RefreshFoodView()
    self:RefreshArrow()
    self:RefreshPagePoints()
end

function UIMainInteractionCookingMenuDialog:OnGetFoodCellByIndex(listView, index)
    if index < 0 then
        return nil
    end

    local data = self._curPageFoodData[index + 1]
    local pageGo = listView:NewListViewItem("Page")

    local goPar = pageGo.gameObject.transform:Find("ButtonLayout")
    local goInstantiate = goPar.transform:Find("Cell")

    for i = 1, goPar.transform.childCount do
        local go = goPar.transform:GetChild(i - 1)
        if go then
            KTool.SetActive(go, false)
        end
    end

    for k, v in pairs(data) do
        local go = goPar.transform:Find("cell"..k)
        if not go then
            go = CfUtils.InstantiateGo(goInstantiate, goPar)
            go.name = "cell"..k
        end
        KTool.SetActive(go, true)

        local scr = CfUtils.GetLuaScr(go, UIMainInteractionCookingMenuFoodNode)
        if scr then
            scr:Refresh(v, function()
                local t = {
                    goodsId = v.id,
                    consumeGoodsId = v.goodsConsum,
                    remainTime = 0,
                    consumeNum = v.goodsConsumNum,
                    maxBuyNum = 99,
                    buyCb = function(num)
                        comp:CookingBuyBattleCookingReq(v.id, num, function()
                            self:RefreshFoodView()
                            UIModule.OpenDialog({ id = Constants.UITypeIds.UICultivateLevelUpFinishDialog, parameters = {
                                foodId = v.id,
                                levelUpType = Constants.UICultivateLevelUpFinishType.CookingFood
                            }})
                        end)
                    end,
                }
                UIModule.OpenDialog({ id = Constants.UITypeIds.UICommonBuyItemDialog, parameters = t}, {
                })
            end)
        end
    end

    return pageGo
end

--当前页面的数据
function UIMainInteractionCookingMenuDialog:GetCurPageFoodData()
    --[[
    local ind = checkNumber(self._curPageInd)
    if ind <= 0 then
        return {}
    end
    ]]
    local t = self._allBattleFoodData
    --[[
    if ind > table.count(t) then
        return {}
    end

    return t[ind]
    ]]
    return t
end

--左
function UIMainInteractionCookingMenuDialog:OnBtnLeft()  
    if self._curPageInd <= 1 then
        return
    end
    self._curPageInd = self._curPageInd - 1
    self.LoopGridView:MovePanelToItemIndex(self._curPageInd - 1)

    --self:RefreshFoodView()
    self:RefreshArrow()
    self:RefreshPagePoints()
end

--右
function UIMainInteractionCookingMenuDialog:OnBtnRight()
    local maxNum = table.count(self._allBattleFoodData)
    if self._curPageInd >= maxNum then
        return
    end
    self._curPageInd = self._curPageInd + 1
    print(self._curPageInd)
    self.LoopGridView:MovePanelToItemIndex(self._curPageInd - 1)

    --self:RefreshFoodView()
    self:RefreshArrow()
    self:RefreshPagePoints()
end

function UIMainInteractionCookingMenuDialog:RefreshArrow()
    local lStatus, rStatus = 1, 1
    if self._curPageInd <= 1 then
        lStatus = 2
    end
    local maxNum = table.count(self._allBattleFoodData)
    if self._curPageInd >= maxNum then
        rStatus = 2
    end
    CfUtils.SetUISwitchImage(self.BtnLeft.transform:Find("ImgArrow"), lStatus)
    CfUtils.SetUISwitchImage(self.BtnRight.transform:Find("ImgArrow"), rStatus)

    local lRedPoint = false
    local rRedPoint = false
    local t
    if self._curPageInd > 1 then
        t = self._allBattleFoodData[self._curPageInd - 1]
        lRedPoint = self:IsMapHasNew(t)
    end

    if self._curPageInd < maxNum then
        t = self._allBattleFoodData[self._curPageInd + 1]
        rRedPoint = self:IsMapHasNew(t)
    end
    KTool.SetActive(self.BtnLeft.transform:Find("CommonRedPoint"), lRedPoint)
    KTool.SetActive(self.BtnRight.transform:Find("CommonRedPoint"), rRedPoint)
end

function UIMainInteractionCookingMenuDialog:RefreshPagePoints()
    local count = table.count(self._allBattleFoodData)
    if count <= 1 then
        KTool.SetActive(self.Page, false)
        return
    end
    for i = 1, count do
        local go = self.Page.transform:Find("point"..i)
        if not go then
            go = CfUtils.InstantiateGo(self.ImgSquare, self.Page)
            go.name = "point"..i
            KTool.SetActive(go, true)
        end
        local status = (checkNumber(self._curPageInd) == i) and 1 or 2
        CfUtils.SetUISwitchImage(go, status)
    end
end

--是否有新的数据
function UIMainInteractionCookingMenuDialog:IsMapHasNew(t)
    if not t then
        return false
    end
    for k, v in pairs(t) do
        if CookingUtils.IsNewRecipe(v.menu) then
            return true
        end
    end
    return false
end

function UIMainInteractionCookingMenuDialog:OnShow()
    ---@type Engine.Lib.CoWait
    local coWait = CoWait.Start():Coroutine(util.cs_generator(function()
        CS.Engine.UI.UIRaycastBlocker.Instance:AddCondition("UIMainInteractionCookingMenuDialog")

        self._co = cs_coroutine.start(function()
            coroutine.yield(Yielders.GetWaitForSeconds(1))
            CS.Engine.UI.UIRaycastBlocker.Instance:RemoveCondition("UIMainInteractionCookingMenuDialog")
        end)
    end))
    return coWait
end

function UIMainInteractionCookingMenuDialog:OnFocus(focus)
    local coWait = CoWait.Start():Coroutine(util.cs_generator(function()
        if focus then
            Events.Broadcast(Constants.EventNames.UIMainHomeSceneFocusShowEventName, true)
            Events.Broadcast(Constants.EventNames.MainHomeRoleActive, { isShow = true, roleId = 108})


        end
    end))
    return coWait
end

function UIMainInteractionCookingMenuDialog:OnHide()
    ---@type Engine.Lib.CoWait
    local coWait = CoWait.Start():Coroutine(util.cs_generator(function()
    end))
    return coWait
end

function UIMainInteractionCookingMenuDialog:OnInitialize()
    local coWait = CoWait.Start():Coroutine(util.cs_generator(function()
        CfUtils.RefreshTopGoods({Constants.Currency.GoldId})
    end))
    return coWait
end

function UIMainInteractionCookingMenuDialog:OnFinalize()
    local coWait = CoWait.Start():Coroutine(util.cs_generator(function()
        Events.RemoveListener(Constants.EventNames.BattleFoodCollectChange, self.EventBattleFoodCollectChange)
        self.controller = nil --删除lua层引用到的c#对象 否则不会产生c# gc回收到对象
        self:Delete()
        self = nil --lua层的gc需要
    end))
    return coWait
end

return UIMainInteractionCookingMenuDialog
