---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gaole.
--- DateTime: 2023-07-12 15:07:39
---

local SettingRefBase = require('Game.Setting.SettingRefBase')
local base = SettingRefBase
local ParseUtils = CS.ParseUtils

---@class MaidCoffeeRenovateInfoVo
local MaidCoffeeRenovateInfoVo = Class("MaidCoffeeRenovateInfoVo", SettingRefBase)

---__int
function MaidCoffeeRenovateInfoVo:__init()
    self.furnitureId = nil              --道具编号
    self.type = nil              --道具类型
    self.furnitureType = nil              --家具类型
    self.name = nil              --名字
    self.fullName = nil          --全名
    self.description = nil              --文案包装（暂时不填）
    self.photoPath = nil              --家具图标
    self.quality = nil              --品质，1,白;2,绿;3,蓝;4,紫;5,橙;6,彩色
    self.prefab = nil              --3D模型
    self.decorationValue = nil              --美观度
    self.source = nil              --来源：0,其他；1,换装模式购买
    self.goodsId = nil              --购买所需货币类型
    self.originalNum = nil              --原价
    self.isLoad = nil          --是否在吧台界面加载
    self.goodsNum = nil              --折扣价
    self.showType = nil         --显示类型
    self.suitId = nil           --所属套装
    self.hot = nil              --是否推荐（1，推荐）
    self.status = nil              --1，正常；0，禁用
end

---FillVo
---@param row TableML.TableFileRow
function MaidCoffeeRenovateInfoVo:FillVo(row)
    base.FillVo(self,row)
    self.furnitureId = parse_number(row, "furnitureId")
    self.id = self.furnitureId
    self.type = parse_number(row, "type")
    self.furnitureType = parse_number(row, "furnitureType")
    self.name = ParseUtils.ParseLocalizeText(row, "name")
    self.fullName = ParseUtils.ParseLocalizeText(row, "fullName")

    self.showType = parse_number(row, "showType", 0)
    ---和道具表同步 2个字段反着解析
    self.description = ParseUtils.ParseLocalizeText(row, "desc")
    self.desc = ParseUtils.ParseLocalizeText(row, "description")
    self.photoPath = ParseUtils.ParsePathName(row,"photoId")              --图片
    self.quality = parse_number(row, "quality")
    self.prefab = ParseUtils.ParsePathName(row,"prefab",".prefab")              --3D模型
    self.decorationValue = parse_number(row, "decorationValue")
    self.source = parse_number(row, "source")              --来源：0,其他；1,换装模式购买
    self.goodsId = parse_number(row, "goodsId")
    self.originalNum = parse_number(row, "originalNum")
    self.isLoad = parse_number(row, "isLoad",0)  == 1         --是否在吧台界面加载
    self.goodsNum = parse_number(row, "goodsNum")
    self.hot = parse_number(row, "hot")
    self.suitId = parse_number(row,"suitId")
    self.status = parse_number(row, "status")
end

function MaidCoffeeRenovateInfoVo:__delete()
    self.furnitureId = nil
    self.type = nil
    self.furnitureType = nil
    self.name = nil
    self.showType = nil
    self.fullName = nil
    self.description = nil
    self.photoPath = nil
    self.quality = nil
    self.prefab = nil
    self.decorationValue = nil
    self.source = nil
    self.goodsId = nil
    self.originalNum = nil
    self.goodsNum = nil
    self.isLoad = nil
    self.hot = nil
    self.suitId = nil
    self.status = nil
end

return MaidCoffeeRenovateInfoVo
