---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gaole.
--- DateTime: 2022-03-28 14:02:22
--- 地图索引表

local SettingRefBase = require('Game.Setting.SettingRefBase')
local base = SettingRefBase
local ParseUtils = CS.ParseUtils

---@class MainQuestMapVo
local MainQuestMapVo = Class("MainQuestMapVo", SettingRefBase)

---__int
function MainQuestMapVo:__init()
    self.id = nil              --地图ID
    self.name = nil              --名称
    self.image = nil              --地图图片资源索引
    self.status = nil              --状态
end

---FillVo
---@param row TableML.TableFileRow
function MainQuestMapVo:FillVo(row)
    base.FillVo(self,row)
    self.id = parse_number(row, "id")
    self.name = ParseUtils.ParseLocalizeText(row, "name")
    self.image = ParseUtils.ParsePathName(row, "image")
    self.status = parse_number(row, "status")
end

function MainQuestMapVo:__delete()
    self.id = nil
    self.name = nil
    self.image = nil
    self.status = nil
end

return MainQuestMapVo
