---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gaole.
--- DateTime: 2021-12-20 14:37:25
---

local SettingRefBase = require('Game.Setting.SettingRefBase')
local base = SettingRefBase
local ParseUtils = CS.ParseUtils

---@class MainTaskVo
local MainTaskVo = Class("MainTaskVo", SettingRefBase)

---__int
function MainTaskVo:__init()
    self.taskAchId = nil              --任务的ID
    self.taskTitle = nil              --任务标题
    self.desc = nil              --任务说明
    --self.Numtype = nil              --计数类型
    self.before = nil              --前置任务
    self.exp = nil              --经验
    self.taskContentType = nil              --任务目标类型
    self.taskContentId = nil              --任务目标
    self.taskContenNum = nil              --任务值
    self.taskGroup = nil              --任务组分类（1为主线，其他均为支线）
    self.rewardId = nil              --任务奖励
    self.rewardNum = nil              --任务奖励数量
    self.openType = nil              --跳转目标
    self.background = nil              --任务背景图
    self.isLastTask = nil              --1是0不是
    self.status = nil              --状态
end

---FillVo
---@param row TableML.TableFileRow
function MainTaskVo:FillVo(row)
    base.FillVo(self,row)
    self.taskAchId = parse_number(row, "taskAchId")
    self.taskTitle = ParseUtils.ParseLocalizeText(row, "taskTitle")
    self.desc = ParseUtils.ParseLocalizeText(row, "desc")
    --self.Numtype = parse_number(row, "Numtype")
    self.before = parse_string(row, "before")
    self.exp = parse_number(row, "exp")
    self.taskContentType = parse_number(row, "taskContentType")
    self.taskContentId = parse_number(row, "taskContentId")
    self.taskContenNum = parse_number(row, "taskContenNum")
    self.taskGroup = parse_number(row, "taskGroup")
    self.rewardId = parse_string(row, "rewardId")
    self.rewardNum = parse_string(row, "rewardNum")
    self.openType = parse_string(row, "openType")
    self.background = ParseUtils.ParsePathName(row, "Background")
    self.isLastTask = parse_number(row, "isLastTask")
    self.status = parse_number(row, "status")
end

function MainTaskVo:__delete()
    self.taskAchId = nil
    self.taskTitle = nil
    self.desc = nil
    --self.Numtype = nil
    self.before = nil
    self.exp = nil
    self.taskContentType = nil
    self.taskContentId = nil
    self.taskContenNum = nil
    self.taskGroup = nil
    self.rewardId = nil
    self.rewardNum = nil
    self.openType = nil
    self.background = nil
    self.isLastTask = nil
    self.status = nil
end

return MainTaskVo
