---
--- Generated by 
--- Created by zxr.
--- DateTime: 2021/3/8 2:45 下午
---

local SettingRefBase = require('Game.Setting.SettingRefBase')
---@class PVPArenaRankRewardVo
local PVPArenaRankRewardVo = Class("PVPArenaRankRewardVo", SettingRefBase)

local base          = SettingRefBase
local parse_number  = parse_number
local parse_string  = parse_string
local parse_rewards = parse_rewards

function PVPArenaRankRewardVo:__init()
    self.PrizeId = nil
    self.PrizeNum = nil
    self.limitNum = nil
end

function PVPArenaRankRewardVo:__delete()
    self.PrizeId = nil
    self.PrizeNum = nil
    self.limitNum = nil
end

---FillVo
---@param row TableML.TableFileRow
function PVPArenaRankRewardVo:FillVo(row)
    base.FillVo(self, row)

    local PrizeId = parse_string(row, "PrizeId")
    local PrizeNum = parse_string(row, "PrizeNum")
    self.rewards  = parse_rewards(PrizeId, PrizeNum)
    self.limitNum = parse_number(row, "limitNum")

    self.grades = parse_strings(parse_string(row, "Grade"))
end

return PVPArenaRankRewardVo