---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gaole.
--- DateTime: 2023-04-11 20:25:58
--- 区域好感度升级解锁弹窗表

local SettingRefBase = require('Game.Setting.SettingRefBase')
local base = SettingRefBase
local ParseUtils = CS.ParseUtils

---@class RegionLikabilityUpRewardVo
local RegionLikabilityUpRewardVo = Class("RegionLikabilityUpRewardVo", SettingRefBase)

---__int
function RegionLikabilityUpRewardVo:__init()
    self.id = nil              --编号
    self.lable = nil              --标题
    self.describe = nil              --描述
    self.icon = nil              --图标
    self.status = nil              --状态
end

---FillVo
---@param row TableML.TableFileRow
function RegionLikabilityUpRewardVo:FillVo(row)
    base.FillVo(self,row)
    self.id = parse_number(row, "id")
    self.lable = ParseUtils.ParseLocalizeText(row, "lable")
    self.describe = ParseUtils.ParseLocalizeText(row, "describe")
    self.icon = ParseUtils.ParsePathName(row, "icon")
    self.status = parse_number(row, "status")
end

function RegionLikabilityUpRewardVo:__delete()
    self.id = nil
    self.lable = nil
    self.describe = nil
    self.icon = nil
    self.status = nil
end

return RegionLikabilityUpRewardVo
