---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gaole.
--- DateTime: 2023-02-18 14:25:24
--- 歼灭战关卡表

local SettingRefBase = require('Game.Setting.SettingRefBase')
local base = SettingRefBase
local ParseUtils = CS.ParseUtils

---@class RegionAnnihilationQuestVo
local RegionAnnihilationQuestVo = Class("RegionAnnihilationQuestVo", SettingRefBase)

---__int
function RegionAnnihilationQuestVo:__init()
    self.id = nil              --关卡ID
    self.label = nil              --标题
    self.name = nil              --名称
    self.task = nil              --任务id
    self.monsteType = nil              --怪物类型
    self.monsterShow = nil              --怪物显示（皮肤表ID）
    self.level = nil              --进入等级
    self.teamlevel = nil              --进入小队评级
    self.exp = nil              --主角经验
    self.cardExp = nil              --卡牌经验
    self.battleRules = nil              --战斗规则字段
    self.proposalLevel = nil              --推荐战斗力
    self.costItem = nil              --消耗道具ID
    self.costNum = nil              --成功时消耗的数量
    self.costNumLose = nil              --进入时扣除的数量
    self.SceneId = nil              --场景ID
    self.rounds = nil              --回合限制(超出后直接失败)
    self.roleNun = nil              --最多上阵人数（1为下限 4为上限）
    self.unlockNum = nil              --解锁条件值（填充为0，固定为前置关卡解锁）
    self.isMultiStage = nil         -- 多阶段boss关卡
    self.status = nil              --状态
end

---FillVo
---@param row TableML.TableFileRow
function RegionAnnihilationQuestVo:FillVo(row)
    base.FillVo(self,row)
    self.id = parse_number(row, "id")
    self.label = ParseUtils.ParseLocalizeText(row, "label")
    self.name = ParseUtils.ParseLocalizeText(row, "name")
    self.monsterType = parse_number(row, "monsterType")
    self.exp = parse_number(row, "exp")
    self.cardExp = parse_number(row, "cardExp")
    self.battleRules = parse_string(row, "battleRules")
    self.proposalLevel = parse_number(row, "proposalLevel")
    self.costItem = parse_number(row, "costItem")
    self.costNum = parse_number(row, "costNum")
    self.costNumLose = parse_number(row, "costNumLose")
    self.SceneId = parse_number(row, "SceneId")
    self.rounds = parse_number(row, "rounds")
    self.roleNum = parse_string(row, "roleNum")
    self.unlockNum = parse_string(row, "unlockNum")
    self.bgPath = parse_pathName(row, "bgPath")
    self.isMultiStage = parse_number(row, "super", 0)
    self.status = parse_number(row, "status")
end

function RegionAnnihilationQuestVo:__delete()
    self.id = nil
    self.label = nil
    self.name = nil
    self.task = nil
    self.monsteType = nil
    self.monsterShow = nil
    self.level = nil
    self.teamlevel = nil
    self.exp = nil
    self.cardExp = nil
    self.battleRules = nil
    self.proposalLevel = nil
    self.costItem = nil
    self.costNum = nil
    self.costNumLose = nil
    self.SceneId = nil
    self.rounds = nil
    self.roleNun = nil
    self.unlockNum = nil
    self.isMultiStage = nil
    self.status = nil
end

return RegionAnnihilationQuestVo
