---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gaole.
--- DateTime: 2023-09-12 14:16:58
--- 皮肤属性表
---

local parse_number = parse_number
local parse_string = parse_string

local SettingRefBase = require('Game.Setting.SettingRefBase')
local base = SettingRefBase
local ParseUtils = CS.ParseUtils

---@class SkinAttributeVo
local SkinAttributeVo = Class("SkinAttributeVo", SettingRefBase)

---__int
function SkinAttributeVo:__init()
    self.ID = nil              --ID=皮肤id&等级（三位数）
    self.skinID = nil              --皮肤id
    self.levelID = nil              --时装等级
    self.upProperty = nil              --升级属性（增加值，总属性需累加）
    self.upqualityItem = nil              --每级消耗道具id
    self.upqualityItemNum = nil              --消耗道具数量
end

---FillVo
---@param row TableML.TableFileRow
function SkinAttributeVo:FillVo(row)
    base.FillVo(self,row)
    self.ID               = parse_number(row, "ID")
    self.skinID           = parse_number(row, "skinID")
    self.levelID          = parse_number(row, "levelID")
    -- self.upProperty       = parse_string(row, "upProperty")
    self.totalUpProperty  = parse_string(row, "totalUpProperty") --- 反解出来的字段
    self.upqualityItem    = parse_string(row, "upqualityItem")
    self.upqualityItemNum = parse_string(row, "upqualityItemNum")
end

function SkinAttributeVo:__delete()
    self.ID = nil
    self.skinID = nil
    self.levelID = nil
    self.upProperty = nil
    self.upqualityItem = nil
    self.upqualityItemNum = nil
end

function SkinAttributeVo:GetAttributes()
    if self.attributes == nil then
        self.attributes = parseTwoDelimiterStr2Dict(self.totalUpProperty, nil, "@")
    end
    return self.attributes
end

function SkinAttributeVo:GetConsumes()
    if self.consumes == nil then
        self.consumes = parse_rewards(self.upqualityItem, self.upqualityItemNum)
    end
    return self.consumes
end

return SkinAttributeVo
