---
--- Generated by
--- Created by xingweihao.
--- DateTime: 2022/11/7 10:36
---
local CommonGoodsList = "Game.Behaviours.CommonGoodsList"
local Yielders = CS.Engine.Lib.Yielders
local cs_coroutine = import('XLua.cs_coroutine')

---@class CompeteRankingEndRewardNode
---@field ImgDebris                     	UnityEngine.RectTransform               
---@field PointGroup                    	UnityEngine.RectTransform               
---@field ImgIcon                       	UnityEngine.RectTransform                                 
local CompeteRankingEndRewardNode = Class("CompeteRankingEndRewardNode")
function CompeteRankingEndRewardNode:__init()
    self.delayCo = nil
end

function CompeteRankingEndRewardNode:__delete()
    if self.delayCo then
        cs_coroutine.stop(self.delayCo)
    end
    self.delayCo = nil
end
---@return CompeteComponent
function CompeteRankingEndRewardNode:GetComponent()
    ---@type CompeteComponent
    local comp = GameUtils.GetEntityCompByType(ECSComponentType.Constants.CompeteComponent)
    return comp
end

function CompeteRankingEndRewardNode:Awake()
    self:FillSelf()
end

function CompeteRankingEndRewardNode:Start()

end

function CompeteRankingEndRewardNode:FillSelf()
    local comp = self:GetComponent()
    local activityConf = comp:GetActivityConf()
    local scr = CfUtils.GetLuaScr(self.CommonGoodsList, CommonGoodsList)
    local people = activityConf.people
    local peopleId = comp:GetPlayerPeopleId()
    local index = 1
    for i, v in pairs(people) do
        if checkInt(v) == peopleId then
            index = i
            break
        end
    end

    if scr then
        scr:FreshBaseUI({activityConf.winReward[index]})
    end
    self:PlayAni("Go")
end

function CompeteRankingEndRewardNode:PlayAni(name)
    self.delayCo = cs_coroutine.start(function()
        cs_coroutine.yield_return(Yielders.GetWaitForSeconds(0.1))
        CfUtils.PlayAnimator(self.controller.gameObject, name)
    end)

end

function CompeteRankingEndRewardNode:OnDestroy()
    self.controller = nil--luabehaviour 中CSharp对象
    self:Delete()
    self = nil
end

return CompeteRankingEndRewardNode
