---
--- Generated by suixin
--- Created by suixin.
--- DateTime: 2024/9/9 16:31
---

--region import
---@type CommonTabToggleLeftCell
local CommonTabToggleLeftCell = import("Game.Behaviours.CommonTabToggleLeftCell")
local XLuaUtils = CS.Engine.Lib.XLuaUtils
---@class RegressionTabToggleLeftCell
local RegressionTabToggleLeftCell = Class('RegressionTabToggleLeftCell', CommonTabToggleLeftCell)
local SwitchTextStatusEnum = {
	DEFAULT = 1,
	SELECTED = 2,
}

function RegressionTabToggleLeftCell:Awake()
	self.super.Awake(self)
end

---@override
function RegressionTabToggleLeftCell:FreshSelectStatus(isSelected)
	CfUtils.SetActive(self.Image, isSelected)
	CfUtils.SetUISwitchText(self.Text.transform, isSelected and SwitchTextStatusEnum.SELECTED or SwitchTextStatusEnum.DEFAULT)
	
	if isSelected then
		CfUtils.SetColor(self.ImgIcon, XLuaUtils.HexToColor("#4A4A4A"))
		CfUtils.SetScale(self.ImgIcon, Vector3(0.5, 0.5, 1))
	else
		CfUtils.SetColor(self.ImgIcon, XLuaUtils.HexToColor("#a3a3a3"))
		CfUtils.SetScale(self.ImgIcon, Vector3(0.4, 0.4, 1))
	end
	CfUtils.PlayAnimation(self.AnimRoot, isSelected and "CommonTabToggleLeftGo" or "CommonTabToggleLeftDefault")
end

function RegressionTabToggleLeftCell:OnDestroy()
	self.controller = nil--luabehaviour 中CSharp对象
	self:Delete()
end

return RegressionTabToggleLeftCell