---
--- Generated by zou hanjie
--- DateTime: 2023/11/24 09:28
---


-- 个人信息页面2D版 - 主界面右下角一组按钮的管理

---@class Player2DOptionBtns
local Player2DOptionBtns = Class('Player2DOptionBtns')
-- 外部调用时使用:
-- local Player2DOptionBtns = import('Game.UI.Player.Player2DOptionBtns')


-- ========================================================

--- lua:
local cs_coroutine = require 'XLua.cs_coroutine' -- 协程
local Yielders = CS.Engine.Lib.Yielders -- 协程

---:
local Object = CS.UnityEngine.Object
local GameObject = CS.UnityEngine.GameObject
local Vector3 = CS.UnityEngine.Vector3

--- funtoy:
local BehaviourAction = CS.Engine.Lib.BehaviourAction
local KTool = CS.Engine.Lib.KTool
local UIModule = CS.Engine.UI.UIModule

---@type FriendComponent
local friendComp = GameUtils.GetEntityCompByType(ECSComponentType.Constants.FriendComponent)


-- ========================================================

local FriendState = 
{
    NotFriend = 11,
    Added = 22,
    IsFriend = 33,
}

-- ========================================================

function Player2DOptionBtns:__init( main_, btnParent_ )

    self.main = main_
    self.btnParent = btnParent_

    self.baseBtnTF = self.btnParent:Find("FontStyleButton")    
    KTool.SetActive(self.baseBtnTF.gameObject, false)

    self.exParameter = main_.exParameter
    self.isShowMySelf = self.main:IsShowMySelf()
end


function Player2DOptionBtns:__delete( )
end



-- =============================================================


function Player2DOptionBtns:Refresh()
    if self.isShowMySelf then 
        return
    end

    local selfPlayerId = checkInt(GameUtils.GetPlayerId())
    local othPlayerId = self.main:GetPlayerData().playerId

    if selfPlayerId == othPlayerId then 
        print("koko - 自己看了自己的 个人信息页面")
        return
    end 

    -- ===== 删除所有按钮: ===== 
    local currentRoleTF = nil
    for i=self.btnParent.childCount-1, 0, -1 do   -- 非递归
        local childTF = self.btnParent:GetChild(i)
        if childTF.name ~= "FontStyleButton" then 
            --print("删除按钮 - " .. tostring(childTF.name) )
            Object.Destroy(childTF.gameObject)
        end 
    end

    self:InitPlayerBtn(self.btnParent, self.baseBtnTF, "btnReport", localize("举报"), function()
        self:_OnClickBtn_Accusation()
    end)

    --- ===== 好友 相关按钮: =====
    if not self.main:GetExParameter().hideFriendBtn then
        if friendComp:GetFriendInfo(othPlayerId) ~= nil then
            self.friendState = FriendState.IsFriend
        else
            self.friendState = friendComp:IsSendAddReq(othPlayerId) and FriendState.Added or FriendState.NotFriend
        end
        ---
        if self.friendState == FriendState.IsFriend then
            self:InitPlayerBtn( self.btnParent, self.baseBtnTF, "StartChatBtn", localize("发起私聊"), function()
                self:_OnClickBtn_StartChat()
            end  )

            self:InitPlayerBtn( self.btnParent, self.baseBtnTF, "RemoveFriendBtn", localize("移除好友"), function()
                self:_OnClickBtn_RemoveFriend()
            end  )
        elseif self.friendState == FriendState.NotFriend then

            self:InitPlayerBtn( self.btnParent, self.baseBtnTF, "AddFriend", localize("添加好友"), function()
                self:_OnClickBtn_AddFriend()
            end  )
        else
            -- 添加好友后 按钮变灰
            local btnTF = self:InitPlayerBtn( self.btnParent, self.baseBtnTF, "AddFriend", localize("添加好友"), function()
                self:_OnClickBtn_AlreadyAddedFriend()
            end  )
            CfUtils.SetCanvasGroupAlpha( btnTF, 0.6 )
        end
    end


    --- ===== 社团相关按钮: ===== 
    if self:IsFromClub() then 

        local myMemberDojo = ClubUtils.GetClubComp():GetHomeDojo().myselfDojo
        local othMemberDojo = ClubUtils.GetClubComp():ClubMemberFind(othPlayerId)

        -- 为 nil 就说明这个 othPlayer 刚刚被我们踢出了群, 刷新界面的时候执行到此
        if isNotNull(othMemberDojo) then

            local myClubJob = checkInt(myMemberDojo.job)
            local othClubJob = checkInt(othMemberDojo.job)

            if ClubUtils.HasJobFunc(myClubJob, ClubUtils.JobFuncId.KICKOUT_MEMBER) then
                self:InitPlayerBtn( self.btnParent, self.baseBtnTF, "clubKickout", localize("踢出社团"), function()
                    self:_OnClickBtn_ClubKickout()
                end)
            end

            if ClubUtils.HasJobFunc(myClubJob, ClubUtils.JobFuncId.JOB_MANAGER) then
                -- 只可以任命比自己底的职位，并且排除他当前的职位
                for _, jobType in pairs(ClubUtils.JobType) do
                    if myClubJob < jobType and othClubJob ~= jobType then

                        local nameCH,nameEn = self:JobTypeToName(jobType)
                        self:InitPlayerBtn( self.btnParent, self.baseBtnTF, "To".. tostring(nameEn), localize("任命_Name_",{_Name_=nameCH}), function()
                            self:_OnClickBtn_ClubAssignJob(  jobType )
                        end)
                    end
                end
                -- 如果是社长，额外多一条 "转让社长"
                if myClubJob == ClubUtils.JobType.CHAIRMAN then
                    self:InitPlayerBtn( self.btnParent, self.baseBtnTF, "ToChairman", localize("转让社长"), function()
                        self:_OnClickBtn_ClubAssignJob(  ClubUtils.JobType.CHAIRMAN )
                    end)
                end 
            end
        end
    end

end


---@return string,string
function Player2DOptionBtns:JobTypeToName( type_ )
    local jobName = ClubUtils.GetJobVo(type_).jobName
    if type_ == ClubUtils.JobType.CHAIRMAN then
        return jobName,"Chairman"

    elseif type_ == ClubUtils.JobType.SUBCHAIRMAN then
        return jobName,"SubChairman"
        
    else
        return jobName,"Member"
    end
end




function Player2DOptionBtns:_OnClickBtn_ClubKickout()
    print("koko - 踢出社团")
    local othPlayerId = self.main:GetPlayerData().playerId
    local clubMemberDojo = ClubUtils.GetClubComp():ClubMemberFind(othPlayerId)
    local memberName = clubMemberDojo and clubMemberDojo.playerName or ''
    local requestData = {memberId = othPlayerId }
    GameUtils.SecondConfirm(localize('确认将【_name_】请离社团吗？', {_name_ = memberName}), function()
        GameUtils.Request(Interfaces.OverseaClubKickout, requestData, function(request, response)
            if checkInt(response.errCode) == 0 then
                local responseData = checkTable(response.data)
                ClubUtils.GetClubComp():ClubMemberRemove(othPlayerId)
                GameUtils.Toast(localize('已将【_name_】踢出社团', {_name_ = memberName}))
                --
                self:Refresh()
            end
        end)
    end)
end


function Player2DOptionBtns:_OnClickBtn_ClubAssignJob( newJobType_ )
    print("koko - 社团任命")

    local selfPlayerId = checkInt(GameUtils.GetPlayerId())
    local othPlayerId    = self.main:GetPlayerData().playerId

    local myMemberDojo = ClubUtils.GetClubComp():GetHomeDojo().myselfDojo
    local othMemberDojo = ClubUtils.GetClubComp():ClubMemberFind(othPlayerId)

    local newClubJobId   = checkInt(newJobType_)   
    local newClubJobVo   = ClubUtils.GetJobVo(newClubJobId)
    local newClubJobName = tostring(newClubJobVo.jobName)
    local othMemberName  = othMemberDojo and othMemberDojo.playerName or ''

    local toAssignJob = function()
        local requestData = {memberId = othPlayerId, job = newClubJobId}
        GameUtils.Request(Interfaces.OverseaClubAssignJob, requestData, function(request, response)
            if checkInt(response.errCode) == 0 then
                local responseData = checkTable(response.data)
                if newClubJobId == ClubUtils.JobType.CHAIRMAN then
                    -- 转让会长
                    ClubUtils.GetClubComp():ClubMemberChangeJob(selfPlayerId, ClubUtils.JobType.MEMBER)
                end
                ClubUtils.GetClubComp():ClubMemberChangeJob(othPlayerId, newClubJobId)
                GameUtils.Toast(localize('已将【_name_】任命为【_job_】', {_name_ = othMemberName, _job_ = newClubJobName}))
                ---
                self:Refresh()
            end
        end)
    end

    if newClubJobId == ClubUtils.JobType.CHAIRMAN then
        local secondTips = localize('是否将_job_转让给【_name_】', {_name_ = othMemberName, _job_ = newClubJobName})
        GameUtils.SecondConfirm(secondTips, function() 
            toAssignJob()
        end)

    elseif newClubJobId ~= ClubUtils.JobType.MEMBER then
        local clubJobMemberMax = checkInt(newClubJobVo.jobMember)
        local clubJomMemberNow = ClubUtils.GetClubComp():ClubMembersJobFind(newClubJobId)
        if clubJomMemberNow >= clubJobMemberMax then
            GameUtils.Toast(localize('_job_职位已满员', {_job_ = newClubJobName}))
        else
            toAssignJob()
        end
    else
        toAssignJob()
    end    
end





function Player2DOptionBtns:InitPlayerBtn( parentTF_, baseBtn_, btnName_, name_, func_  )
    local newgo = CfUtils.InstantiateGo(baseBtn_.gameObject, parentTF_)
    newgo.name = btnName_
    KTool.SetActive(newgo, true)
    local textComp = newgo.transform:Find("Text")
    CfUtils.FillCfText( textComp, name_ )
    SetButtonAction(newgo, func_)
    return newgo.transform
end


function Player2DOptionBtns:_OnClickBtn_StartChat()
    print("koko - 发起私聊")
    local othPlayerId = self.main:GetPlayerData().playerId
    local friendData    = friendComp:GetFriendInfo(othPlayerId)
    local ChatConstants = import('Game.OverseaChat.ChatConstants')

    -- todo 临时的方案: 打开聊天前先主动关闭 本页面, 以此来规避层级问题
    if self.co_3 ~= nil then
        cs_coroutine.stop(self.co_3)
    end
    self.co_3 = cs_coroutine.start(function()
        cs_coroutine.yield_return(UIModule.BackDialog())
        if self:IsFromFriendChat() then
            Events.Broadcast(ChatConstants.EventNames.CHAT_TAB_SWITCH, {type = ChatConstants.Channels.Single, friendData = friendData})
        else
            UIModule.OpenDialog( UIArgs(Constants.UITypeIds.OverseaChatMainDialog, {type = ChatConstants.Channels.Single, data = friendData}))
        end
    end) 
end



function Player2DOptionBtns:_OnClickBtn_AddFriend()
    print("koko - 添加好友")
    -- 添加好友
    local playerId = self.main:GetPlayerData().playerId
    friendComp:AddFriend(playerId, function()     
        self:Refresh()
    end) 
end


function Player2DOptionBtns:_OnClickBtn_AlreadyAddedFriend()
    GameUtils.Toast(localize("好友申请已发送"))
end


function Player2DOptionBtns:_OnClickBtn_RemoveFriend()
    print("koko - 移除好友")
    -- 移除好友
    local playerId = self.main:GetPlayerData().playerId
    friendComp:DelFriend(playerId, function() 
        Events.Broadcast("CommonPlayerHead_DelFriend") 
        ---
        self:Refresh()
    end)
end

function Player2DOptionBtns:_OnClickBtn_Accusation()
    local targetPlayer = self.main:GetPlayerData()
    local targetMessage = self.main:GetExParameter().message
    UIModule.OpenDialog({id = Constants.UITypeIds.UIAccusationMainDialog, parameters = {player = targetPlayer, message = targetMessage, chatEnter = self:IsFromFriendChat()}}, {
        --{id = Constants.UITypeIds.Player2DMainDialog}
    })
end

-- function Player2DOptionBtns:_HidePlayerLayoutBtn( name_ )
--     local tf = self.btnParent.transform:Find(name_)
--     if tf then 
--         KTool.SetActive( tf.gameObject, false )
--     end 
-- end


-- 本界面 是否从 好友聊天系统而来
function Player2DOptionBtns:IsFromFriendChat()
    return isNotNull(self.exParameter) and self.exParameter.chatEnter == true
end



function Player2DOptionBtns:IsFromClub()
    return isNotNull(self.exParameter) and self.exParameter.enterType == "Club"
end



return Player2DOptionBtns
