local READONLY = 1
local REACTIVE = 2
local SHALLOW = 4
local MODELSTATE = 8
local ReactiveTypes = {
  TYPE_READONLY = READONLY,
  TYPE_REACTIVE = REACTIVE,
  TYPE_SHALLOW = SHALLOW,
  TYPE_SHALLOW_READONLY = SHALLOW | READONLY,
  TYPE_MODELSTATE = MODELSTATE
}
return ReactiveTypes
