---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuguoqing.
--- DateTime: 2020/4/7 18:53
--- 主线章节选择——Item

------------ import ------------
local UIModule = CS.Engine.UI.UIModule
local DreamlandUtils = import('Game.UI.FightReady.UIDreamland.DreamlandUtils')
local CountDownTime = 2592000 --30 * 86400 30天的秒数
local CDTimerModule = CS.Engine.Modules.CDTimerModule
------------ import ------------

---@class UIActionDreamlandEntryNode
---@field BtnSecondTabel                	UnityEngine.RectTransform               
---@field BgContainer                   	UnityEngine.RectTransform               
---@field ImgMobile                     	UnityEngine.RectTransform               
---@field ImgBg                         	UnityEngine.RectTransform               
---@field ChallengeText                 	UnityEngine.RectTransform               
---@field StoryText                     	UnityEngine.RectTransform               
---@field BtnChallenge                  	UnityEngine.RectTransform               
---@field BtnStory                      	UnityEngine.RectTransform               
---@field BtnChapterList                	FancyScrollView.FancyScrollView         
---@field Content                       	UnityEngine.RectTransform               
---@field Cell                          	UnityEngine.RectTransform               
---@field MessageList                   	UnityEngine.RectTransform               
---@field Challenge                     	UnityEngine.RectTransform               
---@field Story                         	UnityEngine.RectTransform               
---@field MusicPlayer                   	UnityEngine.RectTransform                         
local UIActionDreamlandEntryNode = Class("UIActionDreamlandEntryNode")
function UIActionDreamlandEntryNode:__init()
    self._data = nil
    self._cb = nil
    self._timeDown = nil
end

function UIActionDreamlandEntryNode:__delete()
    self._data = nil
    self._cb = nil
    self._timeDown = nil
end

function UIActionDreamlandEntryNode:Awake()
end

function UIActionDreamlandEntryNode:Start()
    SetButtonAction(self.controller.gameObject, Bind(self, self.OnBtnClick))
end

function UIActionDreamlandEntryNode:Refresh(data, ind, cb)
    if not data then
        return
    end
    self._ind = checkNumber(ind)
    self._cb = cb
    self._data = data

    self:FillSelf()
end

function UIActionDreamlandEntryNode:FillSelf()
    self:FillSelect(false)
    CfUtils.FillImage(self.ImgEnter, self._data.iconID)
    CfUtils.FillText(self.TxtSerialNum, self._ind..".")

    local isUnlock, err = DreamlandUtils.IsUnlock(self._data.id)
    CfUtils.SetActive(self.NormalGroup, isUnlock)
    CfUtils.SetActive(self.LockGroup, not isUnlock)
    CfUtils.SetActive(self.SelectGroup.transform:Find("ImgIcon"), isUnlock)

    if isUnlock then
        --local count = DreamlandUtils.GetAllCollectionCount(self._data.id)
        local count = DreamlandUtils.GetAllPiecesNumByQuestId(self._data.id)
        local t = DreamlandUtils.GetHomeDojoPieces(self._data.id)
        CfUtils.FillText(self.TxtNumber, table.count(t).."/"..count)
    else
        CfUtils.FillText(self.TxtCondition, err)
    end
end

function UIActionDreamlandEntryNode:FillSelect(isTrue)
    CfUtils.SetActive(self.SelectGroup, isTrue)
    CfUtils.SetUISwitchImage(self.ImgBg, isTrue and 1 or 2)
end

function UIActionDreamlandEntryNode:PlayAnimation(name)
    CfUtils.PlayAnimation(self.AnimRoot, name)
end


function UIActionDreamlandEntryNode:OnBtnClick()
    if not isNull(self._cb) then
        self._cb()
    end
end

function UIActionDreamlandEntryNode:OnDestroy()
    self.controller = nil--luabehaviour 中CSharp对象
    self:Delete()
    self = nil
end

return UIActionDreamlandEntryNode