namespace RogueCard;

public enum ActionType
{
	ChangeGlobalData = 1,
	AddEnhance,
	AddEffect,
	ChangeValue,
	AddJoker,
	ChangeSuit,
	AddRank,
	ChangeRank,
	DeleteCard,
	AddUseHandTypeLevel,
	CopyCard,
	RandomCopyCard,
	AllSuit,
	MutliTrigger,
	OtherSuit,
	BetterStraight,
	BetterHand,
	DeleteSelf,
	ChangeAtPlay,
	AlwaysWuChang,
	IgnoreBossEffect,
	CopyJokerEffect,
	RandomJoker,
	AddByRank,
	RandomVersion,
	GetGoldByPoint,
	AddByDeckNum,
	AddByDeckEnhance,
	AddByCardNum,
	ForceSelect,
	NoRepeat,
	OnlyOne,
	CardFail,
	RandomDiscard,
	AddTargetHandTypeLevel,
	DrawSameRankCard,
	RandomRank,
	AddRandomEnhance,
	OddEven,
	TargetScore,
	ChangeValueByJokerSlot,
	ComboCard,
	MoreScore
}
