---
--- Generated by suixin
--- Created by suixin.
--- DateTime: 2023/12/7 10:26
---
local KTool = CS.Engine.Lib.KTool
local ActionDarkDreamStarRootCell = Class('ActionDarkDreamStarRootCell')
function ActionDarkDreamStarRootCell:__init()

end

function ActionDarkDreamStarRootCell:__delete()

end

function ActionDarkDreamStarRootCell:Awake()

end

function ActionDarkDreamStarRootCell:RefreshStarStatus(status)
    KTool.SetActive(self.ImgLight.gameObject,status)
end

function ActionDarkDreamStarRootCell:OnDestroy()
    self.controller = nil--luabehaviour 中CSharp对象
    self:Delete()
end

return ActionDarkDreamStarRootCell