---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by win 10.
--- DateTime: 2019/4/2 14:31
---

local UIHomeView = BaseClass("UIHomeView",UIBaseView);
local base = UIBaseView;

local launchAtk_btn_path = "Right/LaunchAtkButton";
local format_btn_path = "Right/BtnCtrl/FormatButton";
local empire_btn_path = "Right/BtnCtrl/EmpireButton";
local intens_btn_path = "Right/BtnCtrl/IntensButton";
local drawCard_btn_path = "Right/BtnCtrl/DrawCardButton";
local bottom_scroll_path = "Right/BottomScroll View";
local top_scroll_path = "Right/TopScroll View";
local menu_btn_path = "MenuButton";
local menuCtrl_path = "MenuCtrl";
local menu_start_path = "StartIndex";
local menu_end_path = "EndIndex";


local delay = 0.5;

local function CloseMenu(self)
   DoTweenManager.DOAnchorPos3D(self.menuCtrl,self.startIndex,delay,nil);
   self.isMenu = false;
end

local function OpenMenu(self)
   DoTweenManager.DOAnchorPos3D(self.menuCtrl,self.endIndex,delay,nil);
   self.isMenu = true;
end

local function OnMenuBtn(self)
   if(self.isMenu) then
      CloseMenu(self)
   else
      OpenMenu(self)
   end
end

local function OnCreate(self) --界面被创建 获取组件
   base.OnCreate(self); 
   
   local rc = self.rc
   
   
   
   self.isMenu = false;
   self.launchAtk_btn = self:AddComponent(UIButton,launchAtk_btn_path);
   self.format_btn = self:AddComponent(UIButton,format_btn_path);
   self.empire_btn = self:AddComponent(UIButton,empire_btn_path);
   self.intens_btn = self:AddComponent(UIButton,intens_btn_path);
   self.drawCard_btn = self:AddComponent(UIButton,drawCard_btn_path);
   self.bottom_scroll = self:AddComponent(UIButton,bottom_scroll_path);
   self.top_scroll = self:AddComponent(UIButton,top_scroll_path);
   self.menu_btn = self:AddComponent(UIButton,menu_btn_path);
   
   self.menuCtrl = rc:GetObject(menuCtrl_path):GetComponent("RectTransform");
   self.startIndex = rc:GetObject(menu_start_path):GetComponent("RectTransform").anchoredPosition3D; --锚点移动的方式
   self.endIndex = rc:GetObject(menu_end_path):GetComponent("RectTransform").anchoredPosition3D;
   
   Logger.Log(self.startIndex);
   Logger.Log(self.endIndex);
   Logger.Log(self.menuCtrl.rect.position);
   
   self.launchAtk_btn:SetOnClick(self.ctrl.OpenLaunchAtkWindow);
   self.format_btn:SetOnClick(self.ctrl.OpenForMatWindow);
   self.empire_btn:SetOnClick(self.ctrl.OpenEmpireWindow);
   self.intens_btn:SetOnClick(self.ctrl.OpenIntensWindow);
   self.drawCard_btn:SetOnClick(self.ctrl.OpenDrawCardWindow);
   self.menu_btn:SetOnClick(OnMenuBtn);

  
   
end


local function OnEnable(self) --界面被激活 刷新界面
   base.OnEnable(self);
   self:OnRefresh();
end

local function OnRefresh(self)
   --self.isMenu = false;
  -- DoTweenManager.DOAnchorPos3D(self.menuCtrl,self.endIndex,0,nil);
end

--local function OnAddListener(self) -- 监听事件
  -- base.AddUIListener(self);
--end

--local function OnRemoveListener(self) --删除事件
  -- base.OnRemoveListener(self);
--end

local function OnDestroy(self) --销毁界面
   self.isMenu = nil;
   self.launchAtk_btn = nil;
   self.format_btn = nil;
   self.empire_btn = nil;
   self.intens_btn = nil;
   self.drawCard_btn = nil;
   self.bottom_scroll = nil;
   self.top_scroll =nil;
   self.menu_btn = nil;
   self.menuCtrl = nil;
   self.startIndex = nil;
   self.endIndex = nil;
   base.OnDestroy(self);
   
end

UIHomeView.OnCreate = OnCreate
UIHomeView.OnEnable = OnEnable
UIHomeView.OnRefresh = OnRefresh
--UIHomeView.OnAddListener = OnAddListener
--UIHomeView.OnRemoveListener = OnRemoveListener
UIHomeView.OnDestroy = OnDestroy

return UIHomeView