---
--- Generated by zxr
--- Created by zxr.
--- DateTime: 2020/7/9 1:53 下午
---

---@class UICultivateEquipMaterialSelectTipNode
---@field GoodsIcon                     	UnityEngine.RectTransform
---@field CostNumText                   	UnityEngine.UI.Text
---@field TipText                       	UnityEngine.RectTransform
local UICultivateEquipMaterialSelectTipNode = Class('UICultivateEquipMaterialSelectTipNode')

------------ define ------------

------------ define ------------

------------ import ------------
local XLuaUtils        = CS.Engine.Lib.XLuaUtils
------------ import ------------

function UICultivateEquipMaterialSelectTipNode:__init()
end

function UICultivateEquipMaterialSelectTipNode:__delete()
end

function UICultivateEquipMaterialSelectTipNode:Awake()
end

function UICultivateEquipMaterialSelectTipNode:Start()
end

function UICultivateEquipMaterialSelectTipNode:OnDestroy()
    self.controller = nil--luabehaviour 中CSharp对象 self:Delete()
    self:Delete()
    self = nil
end


---------------------------------------------------
--- ui logic begin --
---------------------------------------------------

function UICultivateEquipMaterialSelectTipNode:RefreshCostNumText(costNumText, colorString)
    self.CostNumText.text = costNumText
    if colorString then
        self.CostNumText.color = XLuaUtils.HexToColor(colorString)
    end
end

---------------------------------------------------
--- ui logic end --
---------------------------------------------------

---------------------------------------------------
--- get/set begin --
---------------------------------------------------

---------------------------------------------------
--- get/set end --
---------------------------------------------------

---------------------------------------------------
--- click handler begin --
---------------------------------------------------


---------------------------------------------------
--- click handler end --
---------------------------------------------------

return UICultivateEquipMaterialSelectTipNode