-- chunkname: @/Users/baioo/builds/866EVqtU/3/spacex/spacex-client/UnityProj/Assets/Scripts/Lua/logic/config/leveleditor/t_level_config_900005.lua

module("logic.config.leveleditor.t_level_config_900005", package.seeall)

local configData = {
	battleMusicName = "",
	remarks = "",
	levelId = "900005",
	plotEventGroup = 0,
	maxPerson = 3,
	initRotationOffSet = 90,
	maxRound = 99,
	levelName = "全怪物展示2",
	lossConditionDesc = "",
	sceneId = "111002",
	winConditionDesc = "",
	forbidAction = {
		auto = false,
		move = false,
		strengthenSkill = false,
		useSpecifyTypeSkill = {},
		useSpecifyPurposeSkill = {}
	},
	bornPosList = {
		{
			direction = 1,
			x = 5,
			y = 2
		},
		{
			direction = 1,
			x = 6,
			y = 2
		},
		{
			direction = 1,
			x = 7,
			y = 2
		}
	},
	additionalTerrainList = {},
	winConditionGroupList = {
		{
			tag = "",
			isBackup = false,
			hasTag = false,
			winConditionList = {
				{
					round = 10,
					heroId = 0,
					count = 0,
					monsterTag = "",
					DIYName = "",
					condition = 1,
					monsterIds = {}
				}
			}
		}
	},
	lossConditionList = {
		{
			condition = 1,
			maxDeadCount = 0,
			count = 0,
			hasTag = false,
			DIYName = "",
			isBackup = false,
			tag = "",
			targetId = 0,
			monsterIds = {}
		}
	},
	globalSkillCodeList = {},
	monsterGroupList = {
		{
			symbolStr = "",
			refreshType = 1,
			form = 2,
			plotStr = "",
			round = 1,
			hasSymbol = false,
			groupName = "怪物组1",
			color = 1,
			enemyCountY = 0,
			enemyCountX = 0,
			monsterList = {
				{
					isInitialStatus = false,
					direction = 4,
					y = 14,
					tag = "",
					monsterId = 90000501,
					x = 3,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				},
				{
					isInitialStatus = false,
					direction = 4,
					y = 14,
					tag = "",
					monsterId = 90000502,
					x = 5,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				},
				{
					isInitialStatus = false,
					direction = 4,
					y = 14,
					tag = "",
					monsterId = 90000503,
					x = 7,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				},
				{
					isInitialStatus = false,
					direction = 4,
					y = 14,
					tag = "",
					monsterId = 90000504,
					x = 9,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				},
				{
					isInitialStatus = false,
					direction = 4,
					y = 13,
					tag = "",
					monsterId = 90000505,
					x = 2,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				},
				{
					isInitialStatus = false,
					direction = 4,
					y = 12,
					tag = "",
					monsterId = 90000506,
					x = 3,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				},
				{
					isInitialStatus = false,
					direction = 4,
					y = 12,
					tag = "",
					monsterId = 90000507,
					x = 5,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				},
				{
					isInitialStatus = false,
					direction = 4,
					y = 12,
					tag = "",
					monsterId = 90000508,
					x = 7,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				},
				{
					isInitialStatus = false,
					direction = 4,
					y = 12,
					tag = "",
					monsterId = 90000509,
					x = 9,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				},
				{
					isInitialStatus = false,
					direction = 4,
					y = 12,
					tag = "",
					monsterId = 90000510,
					x = 11,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				},
				{
					isInitialStatus = false,
					direction = 4,
					y = 5,
					tag = "",
					monsterId = 90000511,
					x = 6,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				},
				{
					isInitialStatus = false,
					direction = 4,
					y = 10,
					tag = "",
					monsterId = 90000512,
					x = 2,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				},
				{
					isInitialStatus = false,
					direction = 4,
					y = 10,
					tag = "",
					monsterId = 90000513,
					x = 4,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				},
				{
					isInitialStatus = false,
					direction = 4,
					y = 10,
					tag = "",
					monsterId = 90000514,
					x = 6,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				},
				{
					isInitialStatus = false,
					direction = 4,
					y = 10,
					tag = "",
					monsterId = 90000515,
					x = 8,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				},
				{
					isInitialStatus = false,
					direction = 4,
					y = 10,
					tag = "",
					monsterId = 90000516,
					x = 10,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				},
				{
					isInitialStatus = false,
					direction = 4,
					y = 14,
					tag = "",
					monsterId = 90000517,
					x = 11,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				},
				{
					isInitialStatus = false,
					direction = 4,
					y = 8,
					tag = "",
					monsterId = 90000518,
					x = 2,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				},
				{
					isInitialStatus = false,
					direction = 4,
					y = 8,
					tag = "",
					monsterId = 90000519,
					x = 4,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				},
				{
					isInitialStatus = false,
					direction = 4,
					y = 8,
					tag = "",
					monsterId = 90000520,
					x = 9,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				},
				{
					isInitialStatus = false,
					direction = 4,
					y = 8,
					tag = "",
					monsterId = 90000521,
					x = 11,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				},
				{
					isInitialStatus = false,
					direction = 4,
					y = 6,
					tag = "",
					monsterId = 90000522,
					x = 4,
					initialStatus = {
						hpPercent = 0,
						buffList = {}
					}
				}
			}
		}
	},
	cameraWalkCells = {},
	lockHeroList = {},
	monsters = {
		[90000501] = {
			normalSkill = 1204901,
			name = "水滴执行者",
			pre_magicAtk = 0,
			maxHp = 0,
			aiName = "",
			battleCamp = 1,
			career = 5,
			magicAtk = 0,
			pre_meleeDef = 0,
			sanity = 0,
			remark = "",
			giftSkill = 0,
			weakPointHpRate = 0,
			meleeDef = 0,
			level = 10,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 0,
			pre_meleeAtk = 0,
			pre_maxHp = 0,
			colorType = 4,
			monsterType = 0,
			id = 90000501,
			mobility = 1,
			pre_magicDef = 0,
			aiStepOrder = 3,
			trumpSkill = 0,
			isFuzzy = false,
			inspire = 0,
			camp = 7,
			hasSanity = true,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 0,
			modelId = 120049,
			magicDef = 0,
			specialSkill = 0,
			extraSkills = {},
			attributeGrade = {
				"A",
				"B",
				"B",
				"C",
				"C"
			},
			tags = {}
		},
		[90000502] = {
			normalSkill = 1205001,
			name = "水滴执行者",
			pre_magicAtk = 0,
			maxHp = 0,
			aiName = "",
			battleCamp = 1,
			career = 4,
			magicAtk = 0,
			pre_meleeDef = 0,
			sanity = 0,
			remark = "",
			giftSkill = 0,
			weakPointHpRate = 0,
			meleeDef = 0,
			level = 10,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 0,
			pre_meleeAtk = 0,
			pre_maxHp = 0,
			colorType = 1,
			monsterType = 0,
			id = 90000502,
			mobility = 2,
			pre_magicDef = 0,
			aiStepOrder = 3,
			trumpSkill = 0,
			isFuzzy = false,
			inspire = 0,
			camp = 7,
			hasSanity = true,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 0,
			modelId = 120050,
			magicDef = 0,
			specialSkill = 0,
			extraSkills = {},
			attributeGrade = {
				"S",
				"C",
				"C",
				"S",
				"A"
			},
			tags = {}
		},
		[90000503] = {
			normalSkill = 1204501,
			name = "水滴执行者",
			pre_magicAtk = 63.6,
			maxHp = 148.9,
			aiName = "",
			battleCamp = 1,
			career = 1,
			magicAtk = 63.6,
			pre_meleeDef = 41,
			sanity = 0,
			remark = "",
			giftSkill = 0,
			weakPointHpRate = 0,
			meleeDef = 41,
			level = 10,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 161.2,
			pre_meleeAtk = 161.2,
			pre_maxHp = 148.9,
			colorType = 1,
			monsterType = 0,
			id = 90000503,
			mobility = 3,
			pre_magicDef = 37.8,
			aiStepOrder = 0,
			trumpSkill = 0,
			isFuzzy = false,
			inspire = 22.4,
			camp = 7,
			hasSanity = true,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 22.4,
			modelId = 120045,
			magicDef = 37.8,
			specialSkill = 0,
			extraSkills = {},
			attributeGrade = {
				"A",
				"B",
				"B",
				"C",
				"C"
			},
			tags = {}
		},
		[90000504] = {
			normalSkill = 1204601,
			name = "水滴执行者",
			pre_magicAtk = 58.5,
			maxHp = 180.2,
			aiName = "",
			battleCamp = 1,
			career = 2,
			magicAtk = 58.5,
			pre_meleeDef = 74.9,
			sanity = 0,
			remark = "",
			giftSkill = 0,
			weakPointHpRate = 0,
			meleeDef = 74.9,
			level = 10,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 145.5,
			pre_meleeAtk = 145.5,
			pre_maxHp = 180.2,
			colorType = 2,
			monsterType = 0,
			id = 90000504,
			mobility = 2,
			pre_magicDef = 32.1,
			aiStepOrder = 0,
			trumpSkill = 0,
			isFuzzy = false,
			inspire = 17.9,
			camp = 7,
			hasSanity = true,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 17.9,
			modelId = 120046,
			magicDef = 32.1,
			specialSkill = 0,
			extraSkills = {},
			attributeGrade = {
				"B",
				"B",
				"A",
				"C",
				"C"
			},
			tags = {}
		},
		[90000505] = {
			normalSkill = 1204701,
			name = "水滴执行者",
			pre_magicAtk = 70.2,
			maxHp = 112.8,
			aiName = "",
			battleCamp = 1,
			career = 3,
			magicAtk = 70.2,
			pre_meleeDef = 43,
			sanity = 0,
			remark = "",
			giftSkill = 0,
			weakPointHpRate = 0,
			meleeDef = 43,
			level = 10,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 175.4,
			pre_meleeAtk = 175.4,
			pre_maxHp = 112.8,
			colorType = 3,
			monsterType = 0,
			id = 90000505,
			mobility = 2,
			pre_magicDef = 32.5,
			aiStepOrder = 0,
			trumpSkill = 0,
			isFuzzy = false,
			inspire = 26.9,
			camp = 7,
			hasSanity = true,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 26.9,
			modelId = 120047,
			magicDef = 32.5,
			specialSkill = 0,
			extraSkills = {},
			attributeGrade = {
				"S",
				"A",
				"B",
				"C",
				"C"
			},
			tags = {}
		},
		[90000506] = {
			normalSkill = 1209801,
			name = "徘徊雨具",
			pre_magicAtk = 145.5,
			maxHp = 135.2,
			aiName = "",
			battleCamp = 1,
			career = 4,
			magicAtk = 145.5,
			pre_meleeDef = 37.8,
			sanity = 0,
			remark = "特异小怪模板",
			giftSkill = 0,
			weakPointHpRate = 0,
			meleeDef = 37.8,
			level = 10,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 70.2,
			pre_meleeAtk = 70.2,
			pre_maxHp = 135.2,
			colorType = 1,
			monsterType = 0,
			id = 90000506,
			mobility = 1,
			pre_magicDef = 49.5,
			aiStepOrder = 2,
			trumpSkill = 0,
			isFuzzy = false,
			inspire = 17.9,
			camp = 9,
			hasSanity = false,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 17.9,
			modelId = 120098,
			magicDef = 49.5,
			specialSkill = 0,
			extraSkills = {},
			attributeGrade = {
				"S",
				"C",
				"C",
				"S",
				"A"
			},
			tags = {}
		},
		[90000507] = {
			normalSkill = 1209701,
			name = "徘徊者",
			pre_magicAtk = 63.6,
			maxHp = 148.9,
			aiName = "",
			battleCamp = 1,
			career = 1,
			magicAtk = 63.6,
			pre_meleeDef = 41,
			sanity = 0,
			remark = "随意近战（记得改职业）",
			giftSkill = 0,
			weakPointHpRate = 0,
			meleeDef = 41,
			level = 10,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 161.2,
			pre_meleeAtk = 161.2,
			pre_maxHp = 148.9,
			colorType = 2,
			monsterType = 0,
			id = 90000507,
			mobility = 1,
			pre_magicDef = 37.8,
			aiStepOrder = 3,
			trumpSkill = 0,
			isFuzzy = false,
			inspire = 22.4,
			camp = 9,
			hasSanity = false,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 22.4,
			modelId = 120097,
			magicDef = 37.8,
			specialSkill = 0,
			extraSkills = {},
			attributeGrade = {
				"A",
				"B",
				"B",
				"C",
				"C"
			},
			tags = {}
		},
		[90000508] = {
			normalSkill = 1209001,
			name = "路障角兽",
			pre_magicAtk = 58.5,
			maxHp = 180.2,
			aiName = "",
			battleCamp = 1,
			career = 2,
			magicAtk = 58.5,
			pre_meleeDef = 74.9,
			sanity = 0,
			remark = "守卫小怪（反击后触发振荡）",
			giftSkill = 1209002,
			weakPointHpRate = 0,
			meleeDef = 74.9,
			level = 10,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 145.5,
			pre_meleeAtk = 145.5,
			pre_maxHp = 180.2,
			colorType = 2,
			monsterType = 0,
			id = 90000508,
			mobility = 2,
			pre_magicDef = 32.1,
			aiStepOrder = 2,
			trumpSkill = 0,
			isFuzzy = false,
			inspire = 17.9,
			camp = 9,
			hasSanity = false,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 17.9,
			modelId = 120090,
			magicDef = 32.1,
			specialSkill = 0,
			extraSkills = {},
			attributeGrade = {
				"B",
				"B",
				"A",
				"C",
				"C"
			},
			tags = {}
		},
		[90000509] = {
			normalSkill = 1208901,
			name = "花剑雨伞",
			pre_magicAtk = 70.2,
			maxHp = 112.8,
			aiName = "",
			battleCamp = 1,
			career = 1,
			magicAtk = 70.2,
			pre_meleeDef = 43,
			sanity = 0,
			remark = "幻影小怪（主动攻击时追击）",
			giftSkill = 1208903,
			weakPointHpRate = 0,
			meleeDef = 43,
			level = 10,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 175.4,
			pre_meleeAtk = 175.4,
			pre_maxHp = 112.8,
			colorType = 1,
			monsterType = 0,
			id = 90000509,
			mobility = 4,
			pre_magicDef = 32.5,
			aiStepOrder = 3,
			trumpSkill = 0,
			isFuzzy = false,
			inspire = 26.9,
			camp = 9,
			hasSanity = false,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 26.9,
			modelId = 120089,
			magicDef = 32.5,
			specialSkill = 1208902,
			extraSkills = {},
			attributeGrade = {
				"A",
				"B",
				"B",
				"C",
				"C"
			},
			tags = {}
		},
		[90000510] = {
			normalSkill = 1208801,
			name = "狂欢路灯",
			pre_magicAtk = 145.5,
			maxHp = 135.2,
			aiName = "",
			battleCamp = 1,
			career = 3,
			magicAtk = 145.5,
			pre_meleeDef = 37.8,
			sanity = 0,
			remark = "狙击小怪（主动攻击后发动弧光）",
			giftSkill = 1208803,
			weakPointHpRate = 0,
			meleeDef = 37.8,
			level = 10,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 70.2,
			pre_meleeAtk = 70.2,
			pre_maxHp = 135.2,
			colorType = 3,
			monsterType = 0,
			id = 90000510,
			mobility = 2,
			pre_magicDef = 49.5,
			aiStepOrder = 0,
			trumpSkill = 0,
			isFuzzy = false,
			inspire = 17.9,
			camp = 9,
			hasSanity = false,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 17.9,
			modelId = 120088,
			magicDef = 49.5,
			specialSkill = 0,
			extraSkills = {},
			attributeGrade = {
				"S",
				"A",
				"B",
				"C",
				"C"
			},
			tags = {}
		},
		[90000511] = {
			normalSkill = 1208201,
			name = "拟态/蚺",
			pre_magicAtk = 82.6,
			maxHp = 123.8,
			aiName = "",
			battleCamp = 1,
			career = 4,
			magicAtk = 82.6,
			pre_meleeDef = 48.2,
			sanity = 0,
			remark = "特异模板（没移动力；要注意）",
			giftSkill = 0,
			weakPointHpRate = 0,
			meleeDef = 48.2,
			level = 10,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 206.4,
			pre_meleeAtk = 206.4,
			pre_maxHp = 123.8,
			colorType = 2,
			monsterType = 0,
			id = 90000511,
			mobility = 1,
			pre_magicDef = 48.2,
			aiStepOrder = 2,
			trumpSkill = 0,
			isFuzzy = false,
			inspire = 22.4,
			camp = 9,
			hasSanity = false,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 22.4,
			modelId = 120082,
			magicDef = 48.2,
			specialSkill = 0,
			extraSkills = {},
			attributeGrade = {
				"S",
				"C",
				"C",
				"S",
				"A"
			},
			tags = {}
		},
		[90000512] = {
			normalSkill = 1208101,
			name = "拟态/葵",
			pre_magicAtk = 206.4,
			maxHp = 112.8,
			aiName = "",
			battleCamp = 1,
			career = 5,
			magicAtk = 206.4,
			pre_meleeDef = 32.5,
			sanity = 0,
			remark = "陨灭模板（没移动力；要注意）",
			giftSkill = 0,
			weakPointHpRate = 0,
			meleeDef = 32.5,
			level = 10,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 82.6,
			pre_meleeAtk = 82.6,
			pre_maxHp = 112.8,
			colorType = 4,
			monsterType = 0,
			id = 90000512,
			mobility = 1,
			pre_magicDef = 49.5,
			aiStepOrder = 3,
			trumpSkill = 0,
			isFuzzy = false,
			inspire = 26.9,
			camp = 9,
			hasSanity = false,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 26.9,
			modelId = 120081,
			magicDef = 49.5,
			specialSkill = 1208102,
			extraSkills = {},
			attributeGrade = {
				"A",
				"B",
				"B",
				"C",
				"C"
			},
			tags = {}
		},
		[90000513] = {
			normalSkill = 1207001,
			name = "彩绘积木",
			pre_magicAtk = 206.4,
			maxHp = 112.8,
			aiName = "",
			battleCamp = 1,
			career = 3,
			magicAtk = 206.4,
			pre_meleeDef = 32.5,
			sanity = 0,
			remark = "狙击小怪（没移动力；要注意）",
			giftSkill = 0,
			weakPointHpRate = 0,
			meleeDef = 32.5,
			level = 10,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 82.6,
			pre_meleeAtk = 82.6,
			pre_maxHp = 112.8,
			colorType = 3,
			monsterType = 0,
			id = 90000513,
			mobility = 1,
			pre_magicDef = 49.5,
			aiStepOrder = 0,
			trumpSkill = 0,
			isFuzzy = false,
			inspire = 26.9,
			camp = 8,
			hasSanity = false,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 26.9,
			modelId = 120070,
			magicDef = 49.5,
			specialSkill = 0,
			extraSkills = {},
			attributeGrade = {
				"S",
				"A",
				"B",
				"C",
				"C"
			},
			tags = {}
		},
		[90000514] = {
			normalSkill = 1206901,
			name = "疯狂车轴",
			pre_magicAtk = 206.4,
			maxHp = 112.8,
			aiName = "",
			battleCamp = 1,
			career = 5,
			magicAtk = 206.4,
			pre_meleeDef = 32.5,
			sanity = 0,
			remark = "陨灭小怪（具有3层及以上的轰鸣时；主动攻击必定暴击）",
			giftSkill = 1206903,
			weakPointHpRate = 0,
			meleeDef = 32.5,
			level = 10,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 82.6,
			pre_meleeAtk = 82.6,
			pre_maxHp = 112.8,
			colorType = 4,
			monsterType = 0,
			id = 90000514,
			mobility = 1,
			pre_magicDef = 49.5,
			aiStepOrder = 1,
			trumpSkill = 0,
			isFuzzy = false,
			inspire = 26.9,
			camp = 8,
			hasSanity = false,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 26.9,
			modelId = 120069,
			magicDef = 49.5,
			specialSkill = 1206902,
			extraSkills = {},
			attributeGrade = {
				"A",
				"B",
				"B",
				"C",
				"C"
			},
			tags = {}
		},
		[90000515] = {
			normalSkill = 1206801,
			name = "噩梦圆规",
			pre_magicAtk = 60.3,
			maxHp = 192.2,
			aiName = "",
			battleCamp = 1,
			career = 4,
			magicAtk = 60.3,
			pre_meleeDef = 52.9,
			sanity = 0,
			remark = "红特异小怪（主动攻击触发超感）",
			giftSkill = 1206802,
			weakPointHpRate = 0,
			meleeDef = 52.9,
			level = 15,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 153,
			pre_meleeAtk = 153,
			pre_maxHp = 192.2,
			colorType = 1,
			monsterType = 0,
			id = 90000515,
			mobility = 2,
			pre_magicDef = 48.8,
			aiStepOrder = 0,
			trumpSkill = 0,
			isFuzzy = false,
			inspire = 24.4,
			camp = 8,
			hasSanity = false,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 24.4,
			modelId = 120068,
			magicDef = 48.8,
			specialSkill = 0,
			extraSkills = {},
			attributeGrade = {
				"S",
				"C",
				"C",
				"S",
				"A"
			},
			tags = {}
		},
		[90000516] = {
			normalSkill = 1206701,
			name = "冲锋路桩",
			pre_magicAtk = 66.6,
			maxHp = 145.5,
			aiName = "",
			battleCamp = 1,
			career = 2,
			magicAtk = 66.6,
			pre_meleeDef = 55.5,
			sanity = 0,
			remark = "守卫小怪（主动攻击触发2次锥刺）",
			giftSkill = 1206702,
			weakPointHpRate = 0,
			meleeDef = 55.5,
			level = 15,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 166.5,
			pre_meleeAtk = 166.5,
			pre_maxHp = 145.5,
			colorType = 2,
			monsterType = 0,
			id = 90000516,
			mobility = 2,
			pre_magicDef = 42,
			aiStepOrder = 1,
			trumpSkill = 0,
			isFuzzy = false,
			inspire = 29.4,
			camp = 8,
			hasSanity = false,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 29.4,
			modelId = 120067,
			magicDef = 42,
			specialSkill = 0,
			extraSkills = {},
			attributeGrade = {
				"B",
				"B",
				"A",
				"C",
				"C"
			},
			tags = {}
		},
		[90000517] = {
			normalSkill = 1203301,
			name = "量子保险箱",
			pre_magicAtk = 66.6,
			maxHp = 145.5,
			aiName = "",
			battleCamp = 1,
			career = 6,
			magicAtk = 66.6,
			pre_meleeDef = 55.5,
			sanity = 0,
			remark = "金币本小怪",
			giftSkill = 1203302,
			weakPointHpRate = 0,
			meleeDef = 55.5,
			level = 15,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 166.5,
			pre_meleeAtk = 166.5,
			pre_maxHp = 145.5,
			colorType = 4,
			monsterType = 0,
			id = 90000517,
			mobility = 2,
			pre_magicDef = 42,
			aiStepOrder = 1,
			trumpSkill = 0,
			isFuzzy = false,
			inspire = 29.4,
			camp = 8,
			hasSanity = false,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 29.4,
			modelId = 120033,
			magicDef = 42,
			specialSkill = 0,
			extraSkills = {},
			attributeGrade = {
				"B",
				"C",
				"C",
				"A",
				"A"
			},
			tags = {}
		},
		[90000518] = {
			normalSkill = 1203101,
			name = "枯荣/维生",
			pre_magicAtk = 66.6,
			maxHp = 145.5,
			aiName = "",
			battleCamp = 1,
			career = 6,
			magicAtk = 66.6,
			pre_meleeDef = 55.5,
			sanity = 0,
			remark = "支援小怪（行动结束时援护；援护群体加攻）",
			giftSkill = 1203103,
			weakPointHpRate = 0,
			meleeDef = 55.5,
			level = 15,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 166.5,
			pre_meleeAtk = 166.5,
			pre_maxHp = 145.5,
			colorType = 4,
			monsterType = 0,
			id = 90000518,
			mobility = 2,
			pre_magicDef = 42,
			aiStepOrder = 0,
			trumpSkill = 1203102,
			isFuzzy = false,
			inspire = 29.4,
			camp = 9,
			hasSanity = false,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 29.4,
			modelId = 120031,
			magicDef = 42,
			specialSkill = 0,
			extraSkills = {},
			attributeGrade = {
				"B",
				"C",
				"C",
				"A",
				"A"
			},
			tags = {}
		},
		[90000519] = {
			normalSkill = 1203001,
			name = "惑形/毒蛞",
			pre_magicAtk = 66.6,
			maxHp = 145.5,
			aiName = "",
			battleCamp = 1,
			career = 3,
			magicAtk = 66.6,
			pre_meleeDef = 55.5,
			sanity = 0,
			remark = "狙击小怪（弧光；弧光可弹射重复目标且施加1层[衰退）",
			giftSkill = 1203002,
			weakPointHpRate = 0,
			meleeDef = 55.5,
			level = 15,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 166.5,
			pre_meleeAtk = 166.5,
			pre_maxHp = 145.5,
			colorType = 3,
			monsterType = 0,
			id = 90000519,
			mobility = 2,
			pre_magicDef = 42,
			aiStepOrder = 0,
			trumpSkill = 0,
			isFuzzy = false,
			inspire = 29.4,
			camp = 9,
			hasSanity = false,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 29.4,
			modelId = 120030,
			magicDef = 42,
			specialSkill = 0,
			extraSkills = {},
			attributeGrade = {
				"S",
				"A",
				"B",
				"C",
				"C"
			},
			tags = {}
		},
		[90000520] = {
			normalSkill = 1202901,
			name = "惑形/蜉蝣",
			pre_magicAtk = 66.6,
			maxHp = 145.5,
			aiName = "",
			battleCamp = 1,
			career = 4,
			magicAtk = 66.6,
			pre_meleeDef = 55.5,
			sanity = 0,
			remark = "红特异小怪（主动攻击时触发超感；超感范围+1）",
			giftSkill = 1202902,
			weakPointHpRate = 0,
			meleeDef = 55.5,
			level = 15,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 166.5,
			pre_meleeAtk = 166.5,
			pre_maxHp = 145.5,
			colorType = 1,
			monsterType = 0,
			id = 90000520,
			mobility = 2,
			pre_magicDef = 42,
			aiStepOrder = 0,
			trumpSkill = 0,
			isFuzzy = false,
			inspire = 29.4,
			camp = 9,
			hasSanity = false,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 29.4,
			modelId = 120029,
			magicDef = 42,
			specialSkill = 0,
			extraSkills = {},
			attributeGrade = {
				"S",
				"C",
				"C",
				"S",
				"A"
			},
			tags = {}
		},
		[90000521] = {
			normalSkill = 1202801,
			name = "枯荣/孵化",
			pre_magicAtk = 66.6,
			maxHp = 145.5,
			aiName = "",
			battleCamp = 1,
			career = 2,
			magicAtk = 66.6,
			pre_meleeDef = 55.5,
			sanity = 0,
			remark = "守卫小怪（受到攻击后触发振荡；振荡附带群体衰退）",
			giftSkill = 1202802,
			weakPointHpRate = 0,
			meleeDef = 55.5,
			level = 15,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 166.5,
			pre_meleeAtk = 166.5,
			pre_maxHp = 145.5,
			colorType = 2,
			monsterType = 0,
			id = 90000521,
			mobility = 2,
			pre_magicDef = 42,
			aiStepOrder = 0,
			trumpSkill = 0,
			isFuzzy = false,
			inspire = 29.4,
			camp = 9,
			hasSanity = false,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 29.4,
			modelId = 120028,
			magicDef = 42,
			specialSkill = 0,
			extraSkills = {},
			attributeGrade = {
				"B",
				"B",
				"A",
				"C",
				"C"
			},
			tags = {}
		},
		[90000522] = {
			normalSkill = 1201401,
			name = "禁行隔离墩",
			pre_magicAtk = 66.6,
			maxHp = 145.5,
			aiName = "",
			battleCamp = 1,
			career = 2,
			magicAtk = 66.6,
			pre_meleeDef = 55.5,
			sanity = 0,
			remark = "守卫小怪（受到攻击后锥刺）",
			giftSkill = 1201402,
			weakPointHpRate = 0,
			meleeDef = 55.5,
			level = 15,
			monsterGroup = "通用关卡",
			skipStep = false,
			hasGodlike = false,
			meleeAtk = 166.5,
			pre_meleeAtk = 166.5,
			pre_maxHp = 145.5,
			colorType = 2,
			monsterType = 0,
			id = 90000522,
			mobility = 2,
			pre_magicDef = 42,
			aiStepOrder = 1,
			trumpSkill = 0,
			isFuzzy = false,
			inspire = 29.4,
			camp = 8,
			hasSanity = false,
			bodyEffect = "",
			weakPointColor = -1,
			monsterGroupEnum = 1,
			pre_inspire = 29.4,
			modelId = 120014,
			magicDef = 42,
			specialSkill = 0,
			extraSkills = {},
			attributeGrade = {
				"B",
				"B",
				"A",
				"C",
				"C"
			},
			tags = {}
		}
	}
}

return configData
