local L0_1, L1_1, L2_1, L3_1
L0_1 = {}
L1_1 = {}
L1_1.m_CutScenProcessKey = 1
L1_1.m_CutScenID = 10070002
L1_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_C_ALT_KIM_SOBIN"
L1_1.m_bWaitClick = false
L1_1.m_fWaitTime = 0
L1_1.m_BGFileName = "LIFETIME"
L1_1.m_StartBGMFileName = "CUTSCENE_HOPE"
L2_1 = {}
L2_1.m_CutScenKey_Talk = "LIFETIME_END_NKM_UNIT_C_ALT_KIM_SOBIN@2#Talk"
L2_1.m_CutScenProcessKey = 2
L2_1.m_CutScenID = 10070002
L2_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_C_ALT_KIM_SOBIN"
L2_1.m_bWaitClick = true
L2_1.m_fWaitTime = 0
L2_1.m_Face = "UNIT_LAUGH"
L2_1.m_CharStrID = "KIMSOBIN_ALT_NULL_NULL"
L2_1.m_Pos = "C"
L2_1.m_Talk_KOREA = "저...... 항상 고마웠어요, 사장님. 아, 앞으로 더 노력할 테니까...... 꼭, 지켜봐 주셨으면 좋겠어요......!"
L2_1.m_fTalkTime = 0.03
L2_1.m_Talk_JPN = "えっと……これまでありがとうございました、社長。こ、これからもっと頑張りますから……ずっと、見守っていてください……！"
L2_1.m_Talk_ENG = "Erm, thank you for everything, Boss. A-and I'll continue to do my best. I promise."
L2_1.m_Talk_TWN = "那個……一直以來都很感謝您，老闆。我、我以後也會更加努力的……請、請您拭目以待吧！"
L2_1.m_Talk_THA = "เอิ่ม ขอบคุณสำหรับทุกอย่างค่ะบอส ละ-และฉันก็จะพยายามอย่างเต็มที่ต่อไปค่ะ ฉันสัญญา"
L2_1.m_Talk_VTN = "Ờm, cảm ơn vì mọi thứ, Ông Chủ. V-và tôi sẽ tiếp tục cố gắng hết sức. Tôi hứa đấy."
L2_1.m_Talk_SCN = "那个……一直以来谢谢您了，老板。以，以后我会更加努力的……请您拭目以待！"
L2_1.m_Talk_DEU = "Ähm, danke für alles, Boss. I-i-ich werde weiter mein B-Bestes geben. Versprochen."
L2_1.m_Talk_FRA = "Hum, merci pour tout, monsieur. E-Et je vais continuer à faire de mon mieux, je le promets !"
L3_1 = {}
L3_1.m_CutScenProcessKey = 3
L3_1.m_CutScenID = 10070002
L3_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_C_ALT_KIM_SOBIN"
L3_1.m_bWaitClick = false
L3_1.m_fWaitTime = 0
L3_1.m_bFadeIn = false
L3_1.m_fFadeTime = 3
L3_1.m_bFadeWhite = true
L0_1[1] = L1_1
L0_1[2] = L2_1
L0_1[3] = L3_1
m_dicNKCCutScenTempletByID = L0_1
