local L0_1, L1_1, L2_1, L3_1
L0_1 = {}
L1_1 = {}
L1_1.m_CutScenProcessKey = 1
L1_1.m_CutScenID = 11352802
L1_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_C_YG_HARIM_CLB_003"
L1_1.m_bWaitClick = false
L1_1.m_fWaitTime = 0
L1_1.m_StartBGMFileName = "COLLABO_2022_02"
L2_1 = {}
L2_1.m_CutScenKey_Talk = "LIFETIME_END_NKM_UNIT_C_YG_HARIM_CLB_003@2#Talk"
L2_1.m_CutScenProcessKey = 2
L2_1.m_CutScenID = 11352802
L2_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_C_YG_HARIM_CLB_003"
L2_1.m_bWaitClick = true
L2_1.m_fWaitTime = 0
L2_1.m_BGFileName = "CLB_003"
L2_1.m_Face = "UNIT_IDLE"
L2_1.m_CharStrID = "HARIM_REBBIT_CLB_003"
L2_1.m_Pos = "C"
L2_1.m_Talk_KOREA = "항상 열정과 지지를 담아 응원해 줘서 고마워! 티메이츠, 네가 항상 웃을 수 있도록 열심히 할 거니까 지켜봐 줘. 사랑을 담아서 내가 네게 주는 의뢰야."
L2_1.m_fTalkTime = 0.03
L2_1.m_Talk_JPN = "いつもアタシを熱烈に支えてくれてありがとう！　Teammatesたちがいつも笑顔でいられるように頑張るから見守ってね！　アタシからの愛を込めた依頼だよ。"
L2_1.m_Talk_ENG = "Thanks for all the passion and always supporting and cheering me up! Teamates, I will always keep working hard to put a smile on your faces, so just watch me. It is a quest to you guys with love from me."
L2_1.m_Talk_TWN = "Thanks for all the passion and always supporting and cheering me up! Teamates, I will always keep working hard to put a smile on your faces, so just watch me. It is a quest to you guys with love from me."
L2_1.m_Talk_DEU = "Danke für all die Leidenschaft und dafür, dass ihr mich immer unterstützt und aufmuntert, Teamates! Ich werde immer hart daran arbeiten, euch ein Lächeln ins Gesicht zu zaubern, also schaut mir weiter zu. Dies ist meine Mission an euch, mit Liebe von mir."
L2_1.m_Talk_FRA = "Merci pour votre soutien et vos encouragements ! Je vais continuer à travailler dur pour que vous gardiez le sourire, alors restez avec moi ! C'est votre quête, une quête remplie d'amour."
L3_1 = {}
L3_1.m_CutScenProcessKey = 3
L3_1.m_CutScenID = 11352802
L3_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_C_YG_HARIM_CLB_003"
L3_1.m_bWaitClick = false
L3_1.m_fWaitTime = 0
L3_1.m_bFadeIn = false
L3_1.m_fFadeTime = 3
L3_1.m_bFadeWhite = true
L0_1[1] = L1_1
L0_1[2] = L2_1
L0_1[3] = L3_1
m_dicNKCCutScenTempletByID = L0_1
