local L0_1, L1_1, L2_1, L3_1
L0_1 = {}
L1_1 = {}
L1_1.m_CutScenProcessKey = 1
L1_1.m_CutScenID = 11661902
L1_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_ALT_CA_SEO_YOON_RECITAL"
L1_1.m_bWaitClick = false
L1_1.m_fWaitTime = 0
L1_1.m_StartBGMFileName = "CUTSCENE_HOPE"
L2_1 = {}
L2_1.m_CutScenKey_Talk = "LIFETIME_END_NKM_UNIT_ALT_CA_SEO_YOON_RECITAL@2#Talk"
L2_1.m_CutScenProcessKey = 2
L2_1.m_CutScenID = 11661902
L2_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_ALT_CA_SEO_YOON_RECITAL"
L2_1.m_bWaitClick = true
L2_1.m_fWaitTime = 0
L2_1.m_BGFileName = "LIFETIME"
L2_1.m_Face = "UNIT_LAUGH"
L2_1.m_CharStrID = "SEO_YOON_ALT_CA_RECITAL"
L2_1.m_Pos = "C"
L2_1.m_Talk_KOREA = "저희들의 미래는 사장님과 함께 찾고 싶어요. 그러니까...... 앞으로도 믿어 주실 거죠? 지금까지 그래 주셨던 것처럼."
L2_1.m_fTalkTime = 0.03
L2_1.m_Talk_JPN = "私たちの未来は、社長と一緒に探したいんです。だから……今までのように、これからも信じてくれますよね？"
L2_1.m_Talk_ENG = "I want to find our future with you, Boss. So... I'd like you to keep your faith in me, as you've always done."
L2_1.m_Talk_TWN = "我想和老闆一起尋找我們的未來。老闆……不管是過去或未來，都會相信我的吧？"
L2_1.m_Talk_THA = "ฉันอยากตามหาอนาคตกับคุณนะคะ บอส ดังนั้น... ฉันอยากให้คุณเชื่อในตัวฉัน อย่างที่เป็นมาเสมอ"
L2_1.m_Talk_VTN = "Tôi muốn tìm thấy một tương lai của chúng tôi với ngài, Ông Chủ. Vì vậy,... tôi muốn ngài tin vào tôi, giống như ngài đã luôn như vậy."
L2_1.m_Talk_SCN = "我想跟老板一起探索我们的未来，所以……以后也会一如既往地继续相信我吧？"
L2_1.m_Talk_DEU = "Ich will mit Ihnen zusammen unsere Zukunft herausfinden, Boss … Ich möchte, dass Sie an mich glauben, so wie Sie es immer getan haben."
L2_1.m_Talk_FRA = "Je veux explorer l'avenir avec vous, Boss. Alors… faites-moi confiance, comme vous l'avez toujours fait."
L3_1 = {}
L3_1.m_CutScenProcessKey = 3
L3_1.m_CutScenID = 11661902
L3_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_ALT_CA_SEO_YOON_RECITAL"
L3_1.m_bWaitClick = false
L3_1.m_fWaitTime = 0
L3_1.m_bFadeIn = false
L3_1.m_fFadeTime = 3
L3_1.m_bFadeWhite = true
L0_1[1] = L1_1
L0_1[2] = L2_1
L0_1[3] = L3_1
m_dicNKCCutScenTempletByID = L0_1
