local L0_1, L1_1, L2_1, L3_1, L4_1, L5_1, L6_1, L7_1, L8_1, L9_1, L10_1, L11_1, L12_1, L13_1, L14_1, L15_1, L16_1, L17_1, L18_1, L19_1, L20_1, L21_1, L22_1, L23_1, L24_1, L25_1, L26_1, L27_1, L28_1, L29_1, L30_1, L31_1, L32_1
L0_1 = {}
L1_1 = {}
L1_1.m_CutScenProcessKey = 1
L1_1.m_CutScenID = 11630901
L1_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L1_1.m_bWaitClick = false
L1_1.m_fWaitTime = 0
L1_1.m_BGFileName = "BLACK"
L1_1.m_bFadeIn = true
L1_1.m_fFadeTime = 1.5
L1_1.m_StartBGMFileName = "CUTSCENE_SILENCE"
L2_1 = {}
L2_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@29#Talk"
L2_1.m_CutScenProcessKey = 2
L2_1.m_CutScenID = 11630901
L2_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L2_1.m_bWaitClick = true
L2_1.m_fWaitTime = 0
L2_1.m_Talk_KOREA = "오랜 고민 끝에, 당신은 한 가지 중요한 사실을 깨달았다."
L2_1.m_fTalkTime = 0.03
L2_1.m_Talk_JPN = "長い間悩んだ結果、あなたは一つ大事なことに気づいた。"
L2_1.m_Talk_ENG = "After much debate, you came to the conclusion"
L2_1.m_Talk_TWN = "苦惱許久後，你意識到一件重要的事實。"
L2_1.m_Talk_THA = "หลังจากหารือถกเถียงกันอย่างหนักหน่วง คุณก็ได้ข้อสรุป"
L2_1.m_Talk_VTN = "Sau nhiều cuộc tranh luận, ngài đã đi đến kết luận,"
L2_1.m_Talk_SCN = "苦恼许久后，你意识到一件重要的事实。"
L2_1.m_Talk_DEU = "Nach langen Überlegungen bist du zum Schluss gekommen,"
L2_1.m_Talk_FRA = "Après un long moment de réflexion et de nombreuses délibérations,"
L3_1 = {}
L3_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@30#Talk"
L3_1.m_CutScenProcessKey = 3
L3_1.m_CutScenID = 11630901
L3_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L3_1.m_bWaitClick = true
L3_1.m_fWaitTime = 0
L3_1.m_Talk_KOREA = "줄곧 생각해 온 그녀야말로, 앞으로 마주할 운명에서 꼭 필요한 존재라는 것을."
L3_1.m_fTalkTime = 0.03
L3_1.m_Talk_JPN = "ずっと考えてきた彼女だからこそ、これから向き合う運命に必ず必要な存在であることを。"
L3_1.m_Talk_ENG = "that this employee, whom you'd been giving a lot of thought to, was absolutely necessary for the future ahead."
L3_1.m_Talk_TWN = "經過長久的思考，你明白在今後即將面對的命運中，她是不可缺少的存在。"
L3_1.m_Talk_THA = "ว่าพนักงานคนนี้ ซึ่งเป็นคนที่คุณพิจารณาอย่างละเอียดถี่ถ้วน เป็นบุคลากรที่มีความสำคัญอย่างยิ่งกับอนาคตภายภาคหน้า"
L3_1.m_Talk_VTN = "với sự suy xét kỹ càng, người nhân viên này là hoàn toàn cần thiết cho tương lai phía trước của ngài."
L3_1.m_Talk_SCN = "经过长久的思考，你明白在今后即将面对的命运中，她是必不可少的存在。"
L3_1.m_Talk_DEU = "dass diese Mitarbeiterin, über die du so viel nachgedacht hast, absolut unverzichtbar für die Zukunft des Unternehmens ist."
L3_1.m_Talk_FRA = "vous êtes arrivé à la conclusion que cette employée était un élément vital pour votre entreprise et son futur."
L4_1 = {}
L4_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@31#Talk"
L4_1.m_CutScenProcessKey = 4
L4_1.m_CutScenID = 11630901
L4_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L4_1.m_bWaitClick = true
L4_1.m_fWaitTime = 0
L4_1.m_Talk_KOREA = "그리하여 당신은 결심했다."
L4_1.m_fTalkTime = 0.03
L4_1.m_Talk_JPN = "そして、あなたは決心した。"
L4_1.m_Talk_ENG = "So, you've decided"
L4_1.m_Talk_TWN = "所以你下定決心。"
L4_1.m_Talk_THA = "ดังนั้น คุณจึงตัดสินใจ"
L4_1.m_Talk_VTN = "Vậy nên ngài đã quyết định"
L4_1.m_Talk_SCN = "所以你下定决心。"
L4_1.m_Talk_DEU = "Daher hast du beschlossen,"
L4_1.m_Talk_FRA = "Vous avez donc décidé"
L5_1 = {}
L5_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@1#Talk"
L5_1.m_CutScenProcessKey = 5
L5_1.m_CutScenID = 11630901
L5_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L5_1.m_bWaitClick = true
L5_1.m_fWaitTime = 0
L5_1.m_Talk_KOREA = "이 세계에서 어떤 결말을 마주하더라도, 마지막까지 그녀와 함께하기로."
L5_1.m_fTalkTime = 0.03
L5_1.m_Talk_JPN = "この世界でどのような結末を迎えるとしても、最後まで彼女とともにいることを。"
L5_1.m_Talk_ENG = "that you'll be with her, no matter the consequences."
L5_1.m_Talk_TWN = "不管這個世界會迎來怎樣的結局，你都要和她一起走到最後。"
L5_1.m_Talk_THA = "ว่าจะอยู่เคียงข้างเธอ ไม่ว่าจะเกิดอะไรขึ้นต่อจากนี้ก็ตาม"
L5_1.m_Talk_VTN = "rằng ngài sẽ chọn cô ấy, bất chấp hậu quả ra sao."
L5_1.m_Talk_SCN = "不管这个世界会迎来怎样的结局，你都要和她一起走到最后。"
L5_1.m_Talk_DEU = "sie an dich zu binden, egal was auch geschieht."
L5_1.m_Talk_FRA = "de rester à ses côtés et la soutenir, peu importe les conséquences."
L6_1 = {}
L6_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@2#Talk"
L6_1.m_CutScenProcessKey = 6
L6_1.m_CutScenID = 11630901
L6_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L6_1.m_bWaitClick = true
L6_1.m_fWaitTime = 0
L6_1.m_Talk_KOREA = "마음의 준비를 마치고 사장실로 호출하자, 곧 도착한다는 응답이 돌아왔다."
L6_1.m_fTalkTime = 0.03
L6_1.m_Talk_JPN = "意を決して社長室へ呼び出すと、もうすぐ着くとの応答が返ってきた。"
L6_1.m_Talk_ENG = "Having decided that, you called her to your office. She said she'd be here soon."
L6_1.m_Talk_TWN = "做好心理準備後，你將她傳喚到老闆辦公室，她說馬上就會過來。"
L6_1.m_Talk_THA = "เมื่อตัดสินใจเช่นนั้นแล้ว คุณจึงเชิญเธอมาที่ห้องทำงาน และเธอก็บอกว่าจะมาหาในไม่ช้า"
L6_1.m_Talk_VTN = "Sau khi quyết định, ngài đã gọi cô ấy đến văn phòng. Cô ấy cho biết mình sẽ sớm có mặt tại đây."
L6_1.m_Talk_SCN = "做好心理准备后，你将她传唤到老板办公室，得到回应说她马上就到。"
L6_1.m_Talk_DEU = "Also hast du sie in dein Büro gerufen. Sie sagte, sie wolle bald da sein."
L6_1.m_Talk_FRA = "Fort de cette décision, vous l'avez convoquée dans votre bureau. Elle ne devrait pas tarder."
L7_1 = {}
L7_1.m_CutScenProcessKey = 7
L7_1.m_CutScenID = 11630901
L7_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L7_1.m_bWaitClick = false
L7_1.m_fWaitTime = 0.4
L7_1.m_fFlashBangTime = 0.25
L7_1.m_StartFXSoundName = "FX_CUTSCEN_KNOCK_WOOD"
L8_1 = {}
L8_1.m_CutScenProcessKey = 8
L8_1.m_CutScenID = 11630901
L8_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L8_1.m_bWaitClick = false
L8_1.m_fWaitTime = 0.4
L8_1.m_fFlashBangTime = 0.25
L9_1 = {}
L9_1.m_CutScenProcessKey = 9
L9_1.m_CutScenID = 11630901
L9_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L9_1.m_bWaitClick = false
L9_1.m_fWaitTime = 1.5
L9_1.m_fFlashBangTime = 0.25
L10_1 = {}
L10_1.m_CutScenProcessKey = 10
L10_1.m_CutScenID = 11630901
L10_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L10_1.m_bWaitClick = false
L10_1.m_fWaitTime = 0
L10_1.m_bFadeIn = false
L10_1.m_fFadeTime = 2
L11_1 = {}
L11_1.m_CutScenProcessKey = 11
L11_1.m_CutScenID = 11630901
L11_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L11_1.m_bWaitClick = false
L11_1.m_fWaitTime = 1
L11_1.m_BGFileName = "LIFETIME"
L11_1.m_Face = "UNIT_HATE"
L11_1.m_bFadeIn = true
L11_1.m_fFadeTime = 3
L11_1.m_StartBGMFileName = "CUTSCENE_HOPE"
L11_1.m_StartFXSoundName = "FX_CUTSCEN_DOOR_WOOD"
L11_1.m_CharStrID = "SPEAR_FLORA_SUMMER_NULL"
L11_1.m_Pos = "C_D"
L12_1 = {}
L12_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@8#Talk"
L12_1.m_CutScenProcessKey = 12
L12_1.m_CutScenID = 11630901
L12_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L12_1.m_bWaitClick = true
L12_1.m_fWaitTime = 0
L12_1.m_CharStrID = "SPEAR_FLORA_SUMMER_NULL"
L12_1.m_Pos = "C"
L12_1.m_Talk_KOREA = "그래서, 이번엔 무슨 일인데? 미리 말해 두지만 주인님이란 호칭은 절-대 안 쓸 거니까."
L12_1.m_fTalkTime = 0.03
L12_1.m_Talk_JPN = "それで、今度は何の用？言っとくけど、ご主人様なんて、ぜーったいに呼ばないんだから。"
L12_1.m_Talk_ENG = "So, what is it this time? If it's about calling you Master, forget it; it's never going to happen."
L12_1.m_Talk_TWN = "所以，這次又是什麼事？先說好了，我不會使用主人這個稱呼。"
L12_1.m_Talk_THA = "คราวนี้อะไรอีกล่ะ? ถ้าเป็นเรื่องที่จะให้เรียกคุณว่ามาสเตอร์ละก็ ลืมไปได้เลย ไม่มีทางเกิดขึ้นแน่"
L12_1.m_Talk_VTN = " Vậy, lần này là gì? Nếu đó là việc gọi ngài là Sếp, hãy quên nó đi; điều đó sẽ không bao giờ xảy ra.  "
L12_1.m_Talk_SCN = "所以，这次又是什么事？先说好了，我不会使用主人这个称呼。"
L12_1.m_Talk_DEU = "Also, was gibt es diesmal? Wenn es darum geht, Sie als Meister zu bezeichnen, vergessen Sie es. Das wird nie passieren."
L12_1.m_Talk_FRA = "C'est pour quoi, cette fois ? Si c'est pour que je vous appelle maître, laissez tomber. Ça n'arrivera jamais."
L13_1 = {}
L13_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@9#Talk"
L13_1.m_CutScenProcessKey = 13
L13_1.m_CutScenID = 11630901
L13_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L13_1.m_bWaitClick = true
L13_1.m_fWaitTime = 0
L13_1.m_Face = "UNIT_IDLE"
L13_1.m_CharStrID = "SPEAR_FLORA_SUMMER_NULL"
L13_1.m_Pos = "C"
L13_1.m_Talk_KOREA = "응? 내 손가락?"
L13_1.m_fTalkTime = 0.03
L13_1.m_Talk_JPN = "え？私の指？"
L13_1.m_Talk_ENG = "Huh? My finger?"
L13_1.m_Talk_TWN = "嗯？我的手指？"
L13_1.m_Talk_THA = "หืม? นิ้วฉันเหรอ?"
L13_1.m_Talk_VTN = "Gì? Ngón tay của tôi á?"
L13_1.m_Talk_SCN = "嗯？我的手指？"
L13_1.m_Talk_DEU = "Hm? Mein Finger?"
L13_1.m_Talk_FRA = "Quoi ? Mon doigt ?"
L14_1 = {}
L14_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@10#Talk"
L14_1.m_CutScenProcessKey = 14
L14_1.m_CutScenID = 11630901
L14_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L14_1.m_bWaitClick = true
L14_1.m_fWaitTime = 0
L14_1.m_Face = "UNIT_DESPAIR"
L14_1.m_CharStrID = "SPEAR_FLORA_SUMMER_NULL"
L14_1.m_Pos = "C"
L14_1.m_Talk_KOREA = "그, 그냥 식칼에 살짝 긁힌 것뿐이야. 쓸데없이 치료하지 않아도 돼."
L14_1.m_fTalkTime = 0.03
L14_1.m_Talk_JPN = "ちょ、ちょっと包丁で切っただけよ。手当とかしなくていいから。"
L14_1.m_Talk_ENG = "I-it's just a scratch from a kitchen knife. It doesn't need any treatment."
L14_1.m_Talk_TWN = "沒、沒什麼。只是被菜刀割了一下，不需要治療的。"
L14_1.m_Talk_THA = "มะ-มันก็แค่รอยมีดทำครัวบาดนิดหน่อยน่ะ ไม่ต้องรักษาอะไรหรอก"
L14_1.m_Talk_VTN = "Nó chỉ là vết xước do con dao trong bếp thôi. Nó không cần chữa trị gì đâu."
L14_1.m_Talk_SCN = "没，没什么。只是被菜刀划了一下，不需要治疗的。"
L14_1.m_Talk_DEU = "E-Es ist nur ein Kratzer von einem Küchenmesser. Das muss nicht behandelt werden."
L14_1.m_Talk_FRA = "C-C'est juste une égratignure que je me suis faite en cuisinant. Ça va aller."
L15_1 = {}
L15_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@11#Talk"
L15_1.m_CutScenProcessKey = 15
L15_1.m_CutScenID = 11630901
L15_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L15_1.m_bWaitClick = true
L15_1.m_fWaitTime = 0
L15_1.m_CharStrID = "SPEAR_FLORA_SUMMER_NULL"
L15_1.m_Pos = "C"
L15_1.m_Talk_KOREA = "......"
L15_1.m_fTalkTime = 0.09
L15_1.m_Talk_JPN = "……"
L15_1.m_Talk_ENG = "......"
L15_1.m_Talk_TWN = "……"
L15_1.m_Talk_THA = "......"
L15_1.m_Talk_VTN = "......"
L15_1.m_Talk_SCN = "……"
L15_1.m_Talk_DEU = "……"
L15_1.m_Talk_FRA = "......"
L16_1 = {}
L16_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@12#Talk"
L16_1.m_CutScenProcessKey = 16
L16_1.m_CutScenID = 11630901
L16_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L16_1.m_bWaitClick = true
L16_1.m_fWaitTime = 0
L16_1.m_Face = "UNIT_HATE"
L16_1.m_CharStrID = "SPEAR_FLORA_SUMMER_NULL"
L16_1.m_Pos = "C"
L16_1.m_Talk_KOREA = "뭐, 그렇게 안달하면 반창고 붙이는 것 정돈 허락해 줄까......"
L16_1.m_fTalkTime = 0.03
L16_1.m_Talk_JPN = "まあ、そこまで言うなら\n絆創膏ぐらいは貼ってくれてもいいけど……"
L16_1.m_Talk_ENG = "Well, if you're so worried, I guess I can let you put a bandage on it."
L16_1.m_Talk_TWN = "嗯，既然你這麼擔心，那我就允許你給我貼個OK繃之類的。"
L16_1.m_Talk_THA = "ถ้าคุณกังวลขนาดนั้น ฉันจะยอมให้คุณติดผ้าพันแผลให้ฉันก็ได้มั้ง"
L16_1.m_Talk_VTN = "Chà, nếu ngài quá lo lắng, tôi đoán tôi có thể để ngài băng bó nó. "
L16_1.m_Talk_SCN = "嗯，既然你这么担心，那我就允许你给我贴个创可贴之类的。"
L16_1.m_Talk_DEU = "Nun, wenn Sie so besorgt sind, können Sie mir wohl einen Verband anlegen."
L16_1.m_Talk_FRA = "Bon, si vous vous inquiétez tant que ça, vous pouvez me mettre un pansement."
L17_1 = {}
L17_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@13#Talk"
L17_1.m_CutScenProcessKey = 17
L17_1.m_CutScenID = 11630901
L17_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L17_1.m_bWaitClick = true
L17_1.m_fWaitTime = 0
L17_1.m_Face = "UNIT_PRIDE"
L17_1.m_CharStrID = "SPEAR_FLORA_SUMMER_NULL"
L17_1.m_Pos = "C"
L17_1.m_Talk_KOREA = "크흠, 흠. 고마워. 이런 거 안 붙여도 금방 나았겠지만."
L17_1.m_fTalkTime = 0.03
L17_1.m_Talk_JPN = "こほん、ふん。ありがとう。\nこんなの貼らなくても、すぐ治るとは思うけど。"
L17_1.m_Talk_ENG = "*Kahem, hem* Thank you... although this wasn't necessary."
L17_1.m_Talk_TWN = "咳嗯，謝謝。其實不用貼這些也會馬上恢復。"
L17_1.m_Talk_THA = "*อะแฮ่ม* ขอบคุณ... ถึงแม้มันจะไม่จำเป็นก็เถอะ"
L17_1.m_Talk_VTN = "*Kahem, hem* Cảm ơn ngài... mặc dù điều này không cần thiết. "
L17_1.m_Talk_SCN = "咳咳，谢谢。其实不用贴这些也会马上恢复。"
L17_1.m_Talk_DEU = "*Hüstel* Danke … auch wenn es nicht nötig gewesen wäre."
L17_1.m_Talk_FRA = "Hum, humm. Merci... même si ce n'était pas nécessaire."
L18_1 = {}
L18_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@14#Talk"
L18_1.m_CutScenProcessKey = 18
L18_1.m_CutScenID = 11630901
L18_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L18_1.m_bWaitClick = true
L18_1.m_fWaitTime = 0
L18_1.m_Face = "UNIT_IDLE"
L18_1.m_CharStrID = "SPEAR_FLORA_SUMMER_NULL"
L18_1.m_Pos = "C"
L18_1.m_Talk_KOREA = "......그런데 너, 배는 안 고파? 늘 이 시간에 밥해 달라고 했잖아."
L18_1.m_fTalkTime = 0.03
L18_1.m_Talk_JPN = "…で、あんた、お腹は空いてないの？いつもこの時間にご飯作ってって言うじゃない。"
L18_1.m_Talk_ENG = "By the way, aren't you hungry yet? You usually ask me for food around this time."
L18_1.m_Talk_TWN = "……不過你，你不餓嗎？你不是每到這個時候都會喊著要吃飯嗎。"
L18_1.m_Talk_THA = "ว่าแต่คุณหิวรึยังคะ? ปกติคุณมักถามถึงอาหารเวลานี้นี่"
L18_1.m_Talk_VTN = "Nhân tiện, ngài vẫn chưa đói sao? ngài thường yêu cầu tôi mang thức ăn vào khoảng thời gian này.  "
L18_1.m_Talk_SCN = "……不过你，你不饿吗？你不是每到这个点都会喊着要吃饭吗。"
L18_1.m_Talk_DEU = "Haben Sie eigentlich noch keinen Hunger? Normalerweise fragen Sie mich um diese Zeit nach Essen."
L18_1.m_Talk_FRA = "Au fait, est-ce que vous avez faim ? D'habitude, vous demandez de manger à cette heure-ci."
L19_1 = {}
L19_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@15#Talk"
L19_1.m_CutScenProcessKey = 19
L19_1.m_CutScenID = 11630901
L19_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L19_1.m_bWaitClick = false
L19_1.m_fWaitTime = 0
L19_1.m_Face = "UNIT_LAUGH"
L19_1.m_CharStrID = "SPEAR_FLORA_SUMMER_NULL"
L19_1.m_Pos = "C"
L19_1.m_Talk_KOREA = "좋아. 그럼 여기서......"
L19_1.m_fTalkTime = 0.03
L19_1.m_Talk_JPN = "よし、じゃあここで……"
L19_1.m_Talk_ENG = "Okay, then here..."
L19_1.m_Talk_TWN = "好，那就……"
L19_1.m_Talk_THA = "โอเค งั้นก็นี่..."
L19_1.m_Talk_VTN = "Được rồi, vậy chỗ này..."
L19_1.m_Talk_SCN = "好，那就……"
L19_1.m_Talk_DEU = "Okay, dann hier …"
L19_1.m_Talk_FRA = "D'accord, alors, voilà pour vous..."
L20_1 = {}
L20_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@16#Talk"
L20_1.m_CutScenProcessKey = 20
L20_1.m_CutScenID = 11630901
L20_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L20_1.m_bWaitClick = true
L20_1.m_fWaitTime = 0
L20_1.m_Face = "UNIT_SURPRISE"
L20_1.m_CharStrID = "SPEAR_FLORA_SUMMER_NULL"
L20_1.m_Pos = "C"
L20_1.m_Crash = 30
L20_1.m_Talk_KOREA = "응? 같이 먹자고?"
L20_1.m_fTalkTime = 0.03
L20_1.m_bTalkAppend = true
L20_1.m_Talk_JPN = "うん？一緒に食べようって？"
L20_1.m_Talk_ENG = " Huh? You want to eat with me?"
L20_1.m_Talk_TWN = " 嗯？一起吃？"
L20_1.m_Talk_THA = "หืม? คุณอยากกินกับฉันงั้นเหรอ?"
L20_1.m_Talk_VTN = " Hử? ngài muốn ăn với tôi sao?"
L20_1.m_Talk_SCN = " 嗯？一起吃？"
L20_1.m_Talk_DEU = " Hm? Sie wollen mit mir essen?"
L20_1.m_Talk_FRA = " Hein ? Vous voulez que je mange avec vous ?"
L21_1 = {}
L21_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@17#Talk"
L21_1.m_CutScenProcessKey = 21
L21_1.m_CutScenID = 11630901
L21_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L21_1.m_bWaitClick = true
L21_1.m_fWaitTime = 0
L21_1.m_Face = "UNIT_SERIOUS"
L21_1.m_CharStrID = "SPEAR_FLORA_SUMMER_NULL"
L21_1.m_Pos = "C"
L21_1.m_Talk_KOREA = "주, 주인 주제에 그게 메이드한테 할 소리야? 우리가 무슨 커플인 줄 착각하나 본데 절대 아니거든?!"
L21_1.m_fTalkTime = 0.03
L21_1.m_Talk_JPN = "しゅ、主人のくせにメイドに何言ってるの？私たちがカップルか何かと勘違いしているようだけど、全然違うからね？"
L21_1.m_Talk_ENG = "A-are you out of your mind? I'm not your girlfriend—I'm your maid!"
L21_1.m_Talk_TWN = "主、主人怎麼能和女僕說這些話？你以為我們是情侶關係嗎？絕對不是！"
L21_1.m_Talk_THA = "บะ-บ้าไปแล้วเหรอไง? ฉันไม่ใช่แฟนคุณนะคะ... ฉันเป็นเมด!"
L21_1.m_Talk_VTN = "ngài mất trí rồi à? Tôi không phải là ngài gái của ngài - Tôi là người hầu!"
L21_1.m_Talk_SCN = "主，主人怎么能和女仆说这些话？你以为我们是情侣关系吗？绝对不是！"
L21_1.m_Talk_DEU = "H-Haben Sie den Verstand verloren? Ich bin nicht Ihre Freundin, ich bin Ihr Hausmädchen!"
L21_1.m_Talk_FRA = "V-Vous avez perdu la tête ? Je suis votre domestique, pas votre petite-amie !"
L22_1 = {}
L22_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@18#Talk"
L22_1.m_CutScenProcessKey = 22
L22_1.m_CutScenID = 11630901
L22_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L22_1.m_bWaitClick = true
L22_1.m_fWaitTime = 0
L22_1.m_Face = "UNIT_IDLE"
L22_1.m_CharStrID = "SPEAR_FLORA_SUMMER_NULL"
L22_1.m_Pos = "C"
L22_1.m_Talk_KOREA = "물론 네가 상냥하게 대해 주는 건 고맙고, 허구한 날 봐서 낯가림도 없고, 챙겨 주는 대로 잘 먹으니까......"
L22_1.m_fTalkTime = 0.03
L22_1.m_Talk_JPN = "もちろん、あんたが優しくしてくれるのはありがたいし、いつも会ってるから慣れてるし、ご飯作るとちゃんと食べてくれるから……"
L22_1.m_Talk_ENG = "Of course, I'm grateful for your kindness. I don't feel uncomfortable around you either; I've been seeing you so often. You also like everything I cook, so..."
L22_1.m_Talk_TWN = "你對我很溫柔，我很感謝，我做的東西你也都愛吃……"
L22_1.m_Talk_THA = "แน่นอนว่าฉันซาบซึ้งในความใจดีของคุณ เวลาอยู่กับคุณแล้วฉันก็ไม่รู้สึกอึดอัดด้วย ฉันเห็นคุณบ่อยแล้วนะ คุณชอบอาหารทุกอย่างที่ฉันทำ ดังนั้น..."
L22_1.m_Talk_VTN = "Tất nhiên, tôi biết ơn vì lòng tốt của ngài. Tôi cũng không cảm thấy khó chịu khi ở bên ngài; Tôi đã gặp ngài rất thường xuyên. ngài cũng thích mọi thứ tôi nấu, vì vậy...  "
L22_1.m_Talk_SCN = "你对我很温柔，我很感谢，我做的东西你也都爱吃……"
L22_1.m_Talk_DEU = "Natürlich bin ich Ihnen für Ihre Freundlichkeit dankbar. Ich fühle mich auch nicht unwohl in Ihrer Nähe, ich habe Sie so oft gesehen. Sie mögen auch alles, was ich koche, also …"
L22_1.m_Talk_FRA = "Bien sûr, j'apprécie votre gentillesse... Je suis plutôt à l'aise avec vous, depuis que je vous vois régulièrement. Et en plus, vous aimez ma cuisine..."
L23_1 = {}
L23_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@19#Talk"
L23_1.m_CutScenProcessKey = 23
L23_1.m_CutScenID = 11630901
L23_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L23_1.m_bWaitClick = true
L23_1.m_fWaitTime = 0
L23_1.m_Face = "UNIT_DESPAIR"
L23_1.m_CharStrID = "SPEAR_FLORA_SUMMER_NULL"
L23_1.m_Pos = "C"
L23_1.m_Talk_KOREA = "나도...... 뿌듯하긴 하지만......"
L23_1.m_fTalkTime = 0.03
L23_1.m_Talk_JPN = "私も……嬉しいけど……"
L23_1.m_Talk_ENG = "I'm happy, but..."
L23_1.m_Talk_TWN = "我……我也很高興……"
L23_1.m_Talk_THA = "ฉันดีใจนะ แต่ว่า..."
L23_1.m_Talk_VTN = "Tôi rất vui, nhưng..."
L23_1.m_Talk_SCN = "我……我也很高兴……"
L23_1.m_Talk_DEU = "Ich bin glücklich, aber …"
L23_1.m_Talk_FRA = "Ça me fait plaisir, mais..."
L24_1 = {}
L24_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@20#Talk"
L24_1.m_CutScenProcessKey = 24
L24_1.m_CutScenID = 11630901
L24_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L24_1.m_bWaitClick = true
L24_1.m_fWaitTime = 0
L24_1.m_CharStrID = "SPEAR_FLORA_SUMMER_NULL"
L24_1.m_Pos = "C"
L24_1.m_Crash = 20
L24_1.m_Talk_KOREA = "아, 아차~ 벌써 간식시간이네~ 모네 굶어 죽기 전에 얼른 가봐야겠다~"
L24_1.m_fTalkTime = 0.03
L24_1.m_Talk_JPN = "あ、し、しまった～もうおやつの時間か。モネが飢え死にする前に早く行かないと～。"
L24_1.m_Talk_ENG = "Uh-oh, is it already snack time? I'd better go to Mone before she passes out from hunger!"
L24_1.m_Talk_TWN = "啊，哎呀~ 該吃零食了~ 我得趕緊去看看莫妮~"
L24_1.m_Talk_THA = "เอ๊ะ ถึงเวลาของว่างแล้วเหรอ? ฉันไปหาโมเนต์ก่อนที่เธอจะหิวจนเป็นลมดีกว่า!"
L24_1.m_Talk_VTN = "Uh-oh, đã đến giờ ăn nhẹ chưa? Tốt hơn là tôi nên đến gặp Mone trước khi cô ấy ngất đi vì đói!"
L24_1.m_Talk_SCN = "啊，哎呀~该吃零食了~我得赶紧去看看摩尼~"
L24_1.m_Talk_DEU = "Oh-oh, ist es schon Zeit für einen Snack? Ich gehe besser zu Mone, bevor sie vor Hunger in Ohnmacht fällt!"
L24_1.m_Talk_FRA = "Oh, non, c'est déjà l'heure du goûter de Mone ? Il faut que j'aille la voir avant qu'elle s'évanouisse à cause de la faim !"
L25_1 = {}
L25_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@21#Talk"
L25_1.m_CutScenProcessKey = 25
L25_1.m_CutScenID = 11630901
L25_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L25_1.m_bWaitClick = true
L25_1.m_fWaitTime = 0
L25_1.m_Face = "UNIT_SURPRISE"
L25_1.m_CharStrID = "SPEAR_FLORA_SUMMER_NULL"
L25_1.m_Pos = "C"
L25_1.m_Talk_KOREA = "어? 나한테 용건? 그 계약서 때문에 그래?"
L25_1.m_fTalkTime = 0.03
L25_1.m_Talk_JPN = "え？私に用事？その契約書の話なの？"
L25_1.m_Talk_ENG = "Huh, a talk? For what, that contract?"
L25_1.m_Talk_TWN = "嗯？找我有事？是因為那個合約嗎？"
L25_1.m_Talk_THA = "หืม คุยเหรอคะ? เรื่องอะไร สัญญาเหรอ?"
L26_1 = "Hử, một cuộc nói chuyện ư? Để làm gì, hợp đồng đó sao?"
L25_1.m_Talk_VTN = L26_1
L26_1 = "嗯？找我有事？是因为那个合同吗？"
L25_1.m_Talk_SCN = L26_1
L26_1 = "Hm, ein Gespräch? Weswegen, geht es um diesen Vertrag?"
L25_1.m_Talk_DEU = L26_1
L26_1 = "Hein ? Vous vouliez me parler d'un contrat ?"
L25_1.m_Talk_FRA = L26_1
L26_1 = {}
L27_1 = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@22#Talk"
L26_1.m_CutScenKey_Talk = L27_1
L27_1 = 26
L26_1.m_CutScenProcessKey = L27_1
L26_1.m_CutScenID = 11630901
L26_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L26_1.m_bWaitClick = true
L26_1.m_fWaitTime = 0
L26_1.m_Face = "UNIT_LAUGH"
L26_1.m_CharStrID = "SPEAR_FLORA_SUMMER_NULL"
L26_1.m_Pos = "C"
L27_1 = "자, 사인! 됐지? 보나마나 뭐 근로보험이나 계약연장 같은 거잖아?"
L26_1.m_Talk_KOREA = L27_1
L26_1.m_fTalkTime = 0.03
L27_1 = "はい、サイン！これでいい？どうせ勤労保険とか、契約延長みたいなもんでしょ？"
L26_1.m_Talk_JPN = L27_1
L27_1 = "There, I signed it. It's just about my unemployment insurance or employment contract extension, right?"
L26_1.m_Talk_ENG = L27_1
L27_1 = "好，簽名！可以了吧？想來又是勞動保險或延長期限之類的吧？"
L26_1.m_Talk_TWN = L27_1
L27_1 = "เรียบร้อย ฉันเซ็นแล้ว นี่แค่เรื่องประกันคนว่างงานหรือการต่อสัญญาณว่าจ้างของฉันใช่มั้ยคะ?"
L26_1.m_Talk_THA = L27_1
L27_1 = "Đó, tôi đã ký nó. Đó chỉ là về bảo hiểm thất nghiệp hoặc gia hạn hợp đồng lao động của tôi, phải không?"
L26_1.m_Talk_VTN = L27_1
L27_1 = "好，签名！可以了吧？想来又是劳动保险或延长期限之类的吧？"
L26_1.m_Talk_SCN = L27_1
L27_1 = "Hier, ich habe ihn unterschrieben. Es geht nur um meine Arbeitslosenversicherung oder die Verlängerung meines Arbeitsvertrags, richtig?"
L26_1.m_Talk_DEU = L27_1
L27_1 = "Voilà, j'ai signé. À part l'extension de mon contrat et mon assurance chômage, ça ne change pas grand-chose, si ?"
L26_1.m_Talk_FRA = L27_1
L27_1 = {}
L28_1 = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@23#Talk"
L27_1.m_CutScenKey_Talk = L28_1
L28_1 = 27
L27_1.m_CutScenProcessKey = L28_1
L27_1.m_CutScenID = 11630901
L27_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L27_1.m_bWaitClick = true
L27_1.m_fWaitTime = 0
L27_1.m_Face = "UNIT_SURPRISE"
L27_1.m_CharStrID = "SPEAR_FLORA_SUMMER_NULL"
L27_1.m_Pos = "C"
L28_1 = "종신계약? ......뭐어어어어?!!"
L27_1.m_Talk_KOREA = L28_1
L27_1.m_fTalkTime = 0.03
L28_1 = "終身契約？……はああああ！！？"
L27_1.m_Talk_JPN = L28_1
L28_1 = "WHAT? A LIFETIME CONTRACT?!"
L27_1.m_Talk_ENG = L28_1
L28_1 = "終身雇傭？……什麼啊啊啊啊？！！"
L27_1.m_Talk_TWN = L28_1
L28_1 = "หา? สัญญาตลอดชีพงั้นเหรอ?!"
L27_1.m_Talk_THA = L28_1
L28_1 = "GÌ CƠ? HỢP ĐỒNG TRỌN ĐỜI?!"
L27_1.m_Talk_VTN = L28_1
L28_1 = "终身雇佣？……什么啊啊啊啊？！！"
L27_1.m_Talk_SCN = L28_1
L28_1 = "WAS? EIN … LEBENSLANGER … VERTRAG?!"
L27_1.m_Talk_DEU = L28_1
L28_1 = "PARDON ? C'EST UN CONTRAT À VIE ?!"
L27_1.m_Talk_FRA = L28_1
L28_1 = {}
L29_1 = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@24#Talk"
L28_1.m_CutScenKey_Talk = L29_1
L29_1 = 28
L28_1.m_CutScenProcessKey = L29_1
L28_1.m_CutScenID = 11630901
L28_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L28_1.m_bWaitClick = true
L28_1.m_fWaitTime = 0
L28_1.m_Face = "UNIT_DESPAIR"
L28_1.m_CharStrID = "SPEAR_FLORA_SUMMER_NULL"
L28_1.m_Pos = "C"
L28_1.m_Talk_KOREA = "......"
L28_1.m_fTalkTime = 0.09
L28_1.m_Talk_JPN = "……"
L28_1.m_Talk_ENG = "......"
L28_1.m_Talk_TWN = "……"
L28_1.m_Talk_THA = "......"
L28_1.m_Talk_VTN = "......"
L28_1.m_Talk_SCN = "……"
L28_1.m_Talk_DEU = "……"
L28_1.m_Talk_FRA = "......"
L29_1 = {}
L30_1 = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@25#Talk"
L29_1.m_CutScenKey_Talk = L30_1
L30_1 = 29
L29_1.m_CutScenProcessKey = L30_1
L29_1.m_CutScenID = 11630901
L29_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L29_1.m_bWaitClick = true
L29_1.m_fWaitTime = 0
L29_1.m_CharStrID = "SPEAR_FLORA_SUMMER_NULL"
L29_1.m_Pos = "C"
L30_1 = "저기, 무르기...... 안되겠지?"
L29_1.m_Talk_KOREA = L30_1
L29_1.m_fTalkTime = 0.03
L30_1 = "あの、取消……ってわけにはいかないわよね？"
L29_1.m_Talk_JPN = L30_1
L30_1 = "Hey, erm... Can I back out?"
L29_1.m_Talk_ENG = L30_1
L30_1 = "那個，能不能……反悔？"
L29_1.m_Talk_TWN = L30_1
L30_1 = "เฮ้ เอ่อ... ฉันขอถอนตัวได้มั้ย?"
L29_1.m_Talk_THA = L30_1
L30_1 = "Này, ừm... Tôi có thể quay lại không?"
L29_1.m_Talk_VTN = L30_1
L30_1 = "那个，能不能……反悔？"
L29_1.m_Talk_SCN = L30_1
L30_1 = "Hey, ähm … Kann ich einen Rückzieher machen?"
L29_1.m_Talk_DEU = L30_1
L30_1 = "Euh... J'ai le droit de me rétracter ?"
L29_1.m_Talk_FRA = L30_1
L30_1 = {}
L31_1 = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@26#Talk"
L30_1.m_CutScenKey_Talk = L31_1
L30_1.m_CutScenProcessKey = 30
L30_1.m_CutScenID = 11630901
L30_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L30_1.m_bWaitClick = true
L30_1.m_fWaitTime = 0
L30_1.m_Face = "UNIT_SERIOUS"
L30_1.m_CharStrID = "SPEAR_FLORA_SUMMER_NULL"
L30_1.m_Pos = "C"
L31_1 = "크읏....... 됐어! 까짓 거 하면 될 거 아냐! 계약은 계약이니까!"
L30_1.m_Talk_KOREA = L31_1
L30_1.m_fTalkTime = 0.03
L31_1 = "くうっ……もういい！やればいいんでしょ？契約は契約なんだから！"
L30_1.m_Talk_JPN = L31_1
L31_1 = "Hmpf, fine! I'll do it! A contract is a contract."
L30_1.m_Talk_ENG = L31_1
L31_1 = "切……算了！不就是終身雇傭嗎！合約就是合約，沒什麼的！"
L30_1.m_Talk_TWN = L31_1
L31_1 = "ฮึ่ม ก็ได้! ฉันจะทำ! สัญญาก็คือสัญญา"
L30_1.m_Talk_THA = L31_1
L31_1 = "Hmpf, được thôi! Tôi sẽ làm việc đó! Hợp đồng dù sao cũng là hợp đồng."
L30_1.m_Talk_VTN = L31_1
L31_1 = "切……算了！不就是终身雇佣吗！有什么的！"
L30_1.m_Talk_SCN = L31_1
L31_1 = "Hmpf, gut! Ich machs. Vertrag ist Vertrag."
L30_1.m_Talk_DEU = L31_1
L31_1 = "Pff, d'accord ! Un contrat est un contrat."
L30_1.m_Talk_FRA = L31_1
L31_1 = {}
L32_1 = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER@27#Talk"
L31_1.m_CutScenKey_Talk = L32_1
L32_1 = 31
L31_1.m_CutScenProcessKey = L32_1
L31_1.m_CutScenID = 11630901
L31_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_MAID_C_SPEAR_SUMMER"
L31_1.m_bWaitClick = true
L31_1.m_fWaitTime = 0
L31_1.m_Face = "UNIT_HATE"
L31_1.m_CharStrID = "SPEAR_FLORA_SUMMER_NULL"
L31_1.m_Pos = "C"
L32_1 = "이렇게 된 이상, 전속 메이드로서 평생 먹여주고 돌봐줄 테니까 각오하라고. 흥!"
L31_1.m_Talk_KOREA = L32_1
L31_1.m_fTalkTime = 0.03
L32_1 = "こうなった以上、専属メイドとして一生面倒を見るから覚悟しなさい。ふん！"
L31_1.m_Talk_JPN = L32_1
L32_1 = "As your maid, I'll take care of you for the rest of your life. You'd better not regret this. Hmpf!"
L31_1.m_Talk_ENG = L32_1
L32_1 = "既然這樣，那我就作為你的專屬女僕照顧你一輩子，等著瞧，哼！"
L31_1.m_Talk_TWN = L32_1
L32_1 = "ในฐานะเมดของคุณ ฉันจะดูแลคุณไปตลอดชีวิต อย่าเสียใจทีหลังก็แล้วกัน ฮึ่ม!"
L31_1.m_Talk_THA = L32_1
L32_1 = "Là người hầu của ngài, tôi sẽ chăm sóc ngài đến hết đời. Ngài đừng có hối tiếc về điều này nhé. Hừ hừ! "
L31_1.m_Talk_VTN = L32_1
L32_1 = "既然这样，那我就作为你的专属女仆照顾你一辈子，等着瞧，哼！"
L31_1.m_Talk_SCN = L32_1
L32_1 = "Als Ihr Hausmädchen werde ich mich für den Rest Ihres Lebens um Sie kümmern. Ich hoffe, Sie bereuen das nicht. Hmpf!"
L31_1.m_Talk_DEU = L32_1
L32_1 = "Je prendrai soin de vous pour le restant de vos jours. Vous n'avez pas intérêt à le regretter. Pff !"
L31_1.m_Talk_FRA = L32_1
L0_1[1] = L1_1
L0_1[2] = L2_1
L0_1[3] = L3_1
L0_1[4] = L4_1
L0_1[5] = L5_1
L0_1[6] = L6_1
L0_1[7] = L7_1
L0_1[8] = L8_1
L0_1[9] = L9_1
L0_1[10] = L10_1
L0_1[11] = L11_1
L0_1[12] = L12_1
L0_1[13] = L13_1
L0_1[14] = L14_1
L0_1[15] = L15_1
L0_1[16] = L16_1
L0_1[17] = L17_1
L0_1[18] = L18_1
L0_1[19] = L19_1
L0_1[20] = L20_1
L0_1[21] = L21_1
L0_1[22] = L22_1
L0_1[23] = L23_1
L0_1[24] = L24_1
L0_1[25] = L25_1
L0_1[26] = L26_1
L0_1[27] = L27_1
L0_1[28] = L28_1
L0_1[29] = L29_1
L0_1[30] = L30_1
L0_1[31] = L31_1
m_dicNKCCutScenTempletByID = L0_1
