local L0_1, L1_1, L2_1, L3_1
L0_1 = {}
L1_1 = {}
L1_1.m_CutScenProcessKey = 1
L1_1.m_CutScenID = 13200002
L1_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_C_CIVIL_ZENA"
L1_1.m_bWaitClick = false
L1_1.m_fWaitTime = 0
L1_1.m_BGFileName = "LIFETIME"
L1_1.m_StartBGMFileName = "CUTSCENE_HOPE"
L2_1 = {}
L2_1.m_CutScenKey_Talk = "LIFETIME_END_NKM_UNIT_C_CIVIL_ZENA@2#Talk"
L2_1.m_CutScenProcessKey = 2
L2_1.m_CutScenID = 13200002
L2_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_C_CIVIL_ZENA"
L2_1.m_bWaitClick = true
L2_1.m_fWaitTime = 0
L2_1.m_CharStrID = "ZENA_CIVIL_NULL_NULL"
L2_1.m_Pos = "C"
L2_1.m_Talk_KOREA = "하루 빨리 사장님께 어울리는 어엿한 소대장이 되겠어요. 그럼, 앞으로도 많은 지도 부탁드리겠습니다!"
L2_1.m_fTalkTime = 0.03
L2_1.m_Talk_JPN = "1日でも早く社長に似合う一人前の小隊長になりたいです。それでは、これからもたくさんのご指導をよろしくお願いします！"
L2_1.m_Talk_ENG = "I'll grow into a great commander as quickly as I can, to live up to your expectations. Thank you for choosing me!"
L2_1.m_Talk_TWN = "我會儘快成為和您相稱優秀的小隊長。那麼，以後也請多多指教！"
L2_1.m_Talk_THA = "ฉันจะพัฒนาตัวเองให้เร็วที่สุดเพื่อมุ่งสู่การเป็นผู้บัญชาการที่ดีให้สมกับที่คุณคาดหวัง ขอบคุณที่เลือกฉันค่ะ!"
L2_1.m_Talk_VTN = "Tôi sẽ trở thành một chỉ huy tài ba nhanh nhất có thể, để đáp ứng kỳ vọng của ngài. Cảm ơn vì đã chọn tôi!"
L2_1.m_Talk_SCN = "我会尽快成为可以与您相称的小队长。那么，以后也请多多指教！"
L2_1.m_Talk_DEU = "Ich werde so schnell ich kann eine starke Kommandantin werden, damit ich Ihre Erwartungen erfüllen kann. Danke, dass Sie sich für mich entschieden haben."
L2_1.m_Talk_FRA = "Je deviendrai une bonne commandante, je ne vous décevrai pas. Merci de me donner ma chance, merci !"
L3_1 = {}
L3_1.m_CutScenProcessKey = 3
L3_1.m_CutScenID = 13200002
L3_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_C_CIVIL_ZENA"
L3_1.m_bWaitClick = false
L3_1.m_fWaitTime = 0
L3_1.m_bFadeIn = false
L3_1.m_fFadeTime = 3
L3_1.m_bFadeWhite = true
L0_1[1] = L1_1
L0_1[2] = L2_1
L0_1[3] = L3_1
m_dicNKCCutScenTempletByID = L0_1
