local L0_1, L1_1, L2_1, L3_1
L0_1 = {}
L1_1 = {}
L1_1.m_CutScenProcessKey = 1
L1_1.m_CutScenID = 12190002
L1_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_REAPER_M_RAILGUN"
L1_1.m_bWaitClick = false
L1_1.m_fWaitTime = 0
L1_1.m_StartBGMFileName = "CUTSCENE_HOPE"
L2_1 = {}
L2_1.m_CutScenKey_Talk = "LIFETIME_END_NKM_UNIT_REAPER_M_RAILGUN@2#Talk"
L2_1.m_CutScenProcessKey = 2
L2_1.m_CutScenID = 12190002
L2_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_REAPER_M_RAILGUN"
L2_1.m_bWaitClick = true
L2_1.m_fWaitTime = 0
L2_1.m_BGFileName = "LIFETIME"
L2_1.m_CharStrID = "RAILGUN_NPC_ALPHA_NULL"
L2_1.m_Pos = "C"
L2_1.m_Talk_KOREA = "귀관은 적들을 심판할 준비가 되었는가? 그렇다면 좋다."
L2_1.m_fTalkTime = 0.03
L2_1.m_Talk_JPN = "貴官は敵を裁く準備はできているか？　ならばよい。"
L2_1.m_Talk_ENG = "Are you prepared to pass judgment to our enemies? If so, good."
L2_1.m_Talk_TWN = "閣下已經準備好要審判敵人嗎？非常好。"
L2_1.m_Talk_THA = "พร้อมจะมอบคำพิพากษาให้ศัตรูของเราแล้วหรือยัง? ถ้าพร้อมแล้วก็เยี่ยมมาก\n"
L2_1.m_Talk_VTN = "Ngài đã sẵn sàng để phán xét kẻ thù của chúng ta chưa? Nếu vậy thì tốt."
L2_1.m_Talk_SCN = "你准备好审判敌人了吗？如果是这样，那很好。"
L2_1.m_Talk_DEU = "Sind Sie bereit, die Feinde zu verurteilen? Wenn ja, gut."
L2_1.m_Talk_FRA = "Es-tu prêt à abattre ton jugement sur tes ennemis ? Si oui, tant mieux."
L3_1 = {}
L3_1.m_CutScenProcessKey = 3
L3_1.m_CutScenID = 12190002
L3_1.m_CutScenStrID = "LIFETIME_END_NKM_UNIT_REAPER_M_RAILGUN"
L3_1.m_bWaitClick = false
L3_1.m_fWaitTime = 0
L3_1.m_bFadeIn = false
L3_1.m_fFadeTime = 3
L3_1.m_bFadeWhite = true
L0_1[1] = L1_1
L0_1[2] = L2_1
L0_1[3] = L3_1
m_dicNKCCutScenTempletByID = L0_1
