local L0_1, L1_1, L2_1, L3_1, L4_1, L5_1, L6_1, L7_1, L8_1, L9_1, L10_1, L11_1, L12_1, L13_1, L14_1, L15_1, L16_1, L17_1, L18_1, L19_1, L20_1, L21_1, L22_1, L23_1, L24_1, L25_1, L26_1, L27_1, L28_1, L29_1, L30_1, L31_1, L32_1
L0_1 = {}
L1_1 = {}
L1_1.m_CutScenProcessKey = 1
L1_1.m_CutScenID = 11110001
L1_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L1_1.m_bWaitClick = false
L1_1.m_fWaitTime = 0
L1_1.m_BGFileName = "BLACK"
L1_1.m_bFadeIn = true
L1_1.m_fFadeTime = 1.5
L1_1.m_StartBGMFileName = "CUTSCENE_SILENCE"
L2_1 = {}
L2_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@2#Talk"
L2_1.m_CutScenProcessKey = 2
L2_1.m_CutScenID = 11110001
L2_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L2_1.m_bWaitClick = true
L2_1.m_fWaitTime = 0
L2_1.m_Talk_KOREA = "오랜 고민 끝에, 당신은 한 가지 중요한 사실을 깨달았다."
L2_1.m_fTalkTime = 0.03
L2_1.m_Talk_JPN = "長い間悩んだ結果、あなたは一つ大事なことに気づいた。"
L2_1.m_Talk_ENG = "After much debate, you came to the conclusion"
L2_1.m_Talk_TWN = "苦惱許久後，你意識到一件重要的事實。"
L2_1.m_Talk_THA = "หลังจากหารือถกเถียงกันอย่างหนักหน่วง คุณก็ได้ข้อสรุป"
L2_1.m_Talk_VTN = "Sau nhiều cuộc tranh luận, ngài đã đi đến kết luận,"
L2_1.m_Talk_SCN = "苦恼许久后，你意识到一件重要的事实。"
L2_1.m_Talk_DEU = "Nach langen Überlegungen bist du zum Schluss gekommen,"
L2_1.m_Talk_FRA = "Après un long moment de réflexion et de nombreuses délibérations,"
L3_1 = {}
L3_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@3#Talk"
L3_1.m_CutScenProcessKey = 3
L3_1.m_CutScenID = 11110001
L3_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L3_1.m_bWaitClick = true
L3_1.m_fWaitTime = 0
L3_1.m_Talk_KOREA = "줄곧 생각해 온 그녀야말로, 앞으로 마주할 운명에서 꼭 필요한 존재라는 것을."
L3_1.m_fTalkTime = 0.03
L3_1.m_Talk_JPN = "ずっと考えてきた彼女だからこそ、これから向き合う運命に必ず必要な存在であることを。"
L3_1.m_Talk_ENG = "that this employee, whom you'd been giving a lot of thought to, was absolutely necessary for the future ahead."
L3_1.m_Talk_TWN = "經過長久的思考，你明白在今後即將面對的命運中，她是不可缺少的存在。"
L3_1.m_Talk_THA = "ว่าพนักงานคนนี้ ซึ่งเป็นคนที่คุณพิจารณาอย่างละเอียดถี่ถ้วน เป็นบุคลากรที่มีความสำคัญอย่างยิ่งกับอนาคตภายภาคหน้า"
L3_1.m_Talk_VTN = "với sự suy xét kỹ càng, người nhân viên này là hoàn toàn cần thiết cho tương lai phía trước của ngài."
L3_1.m_Talk_SCN = "经过长久的思考，你明白在今后即将面对的命运中，她是必不可少的存在。"
L3_1.m_Talk_DEU = "dass diese Mitarbeiterin, über die du so viel nachgedacht hast, absolut unverzichtbar für die Zukunft des Unternehmens ist."
L3_1.m_Talk_FRA = "vous êtes arrivé à la conclusion que cette employée était un élément vital pour votre entreprise et son futur."
L4_1 = {}
L4_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@4#Talk"
L4_1.m_CutScenProcessKey = 4
L4_1.m_CutScenID = 11110001
L4_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L4_1.m_bWaitClick = true
L4_1.m_fWaitTime = 0
L4_1.m_Talk_KOREA = "그리하여 당신은 결심했다."
L4_1.m_fTalkTime = 0.03
L4_1.m_Talk_JPN = "そして、あなたは決心した。"
L4_1.m_Talk_ENG = "So, you've decided"
L4_1.m_Talk_TWN = "所以你下定決心。"
L4_1.m_Talk_THA = "ดังนั้น คุณจึงตัดสินใจ"
L4_1.m_Talk_VTN = "Vậy nên ngài đã quyết định"
L4_1.m_Talk_SCN = "所以你下定决心。"
L4_1.m_Talk_DEU = "Daher hast du beschlossen,"
L4_1.m_Talk_FRA = "Vous avez donc décidé"
L5_1 = {}
L5_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@5#Talk"
L5_1.m_CutScenProcessKey = 5
L5_1.m_CutScenID = 11110001
L5_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L5_1.m_bWaitClick = true
L5_1.m_fWaitTime = 0
L5_1.m_Talk_KOREA = "이 세계에서 어떤 결말을 마주하더라도, 마지막까지 그녀와 함께하기로."
L5_1.m_fTalkTime = 0.03
L5_1.m_Talk_JPN = "この世界でどのような結末を迎えるとしても、最後まで彼女とともにいることを。"
L5_1.m_Talk_ENG = "that you'll be with her, no matter the consequences."
L5_1.m_Talk_TWN = "不管這個世界會迎來怎樣的結局，你都要和她一起走到最後。"
L5_1.m_Talk_THA = "ว่าจะอยู่เคียงข้างเธอ ไม่ว่าจะเกิดอะไรขึ้นต่อจากนี้ก็ตาม"
L5_1.m_Talk_VTN = "rằng ngài sẽ chọn cô ấy, bất chấp hậu quả ra sao."
L5_1.m_Talk_SCN = "不管这个世界会迎来怎样的结局，你都要和她一起走到最后。"
L5_1.m_Talk_DEU = "sie an dich zu binden, egal was auch geschieht."
L5_1.m_Talk_FRA = "de rester à ses côtés et la soutenir, peu importe les conséquences."
L6_1 = {}
L6_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@6#Talk"
L6_1.m_CutScenProcessKey = 6
L6_1.m_CutScenID = 11110001
L6_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L6_1.m_bWaitClick = true
L6_1.m_fWaitTime = 0
L6_1.m_Talk_KOREA = "마음의 준비를 마치고 사장실로 호출하자, 곧 도착한다는 응답이 돌아왔다."
L6_1.m_fTalkTime = 0.03
L6_1.m_Talk_JPN = "意を決して社長室へ呼び出すと、もうすぐ着くとの応答が返ってきた。"
L6_1.m_Talk_ENG = "Having decided that, you called her to your office. She said she'd be here soon."
L6_1.m_Talk_TWN = "做好心理準備後，你將她傳喚到老闆辦公室，她說馬上就會過來。"
L6_1.m_Talk_THA = "เมื่อตัดสินใจเช่นนั้นแล้ว คุณจึงเชิญเธอมาที่ห้องทำงาน และเธอก็บอกว่าจะมาหาในไม่ช้า"
L6_1.m_Talk_VTN = "Sau khi quyết định, ngài đã gọi cô ấy đến văn phòng. Cô ấy cho biết mình sẽ sớm có mặt tại đây."
L6_1.m_Talk_SCN = "做好心理准备后，你将她传唤到老板办公室，得到回应说她马上就到。"
L6_1.m_Talk_DEU = "Also hast du sie in dein Büro gerufen. Sie sagte, sie wolle bald da sein."
L6_1.m_Talk_FRA = "Fort de cette décision, vous l'avez convoquée dans votre bureau. Elle ne devrait pas tarder."
L7_1 = {}
L7_1.m_CutScenProcessKey = 7
L7_1.m_CutScenID = 11110001
L7_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L7_1.m_bWaitClick = false
L7_1.m_fWaitTime = 0.4
L7_1.m_fFlashBangTime = 0.25
L7_1.m_StartFXSoundName = "FX_CUTSCEN_KNOCK_WOOD"
L8_1 = {}
L8_1.m_CutScenProcessKey = 8
L8_1.m_CutScenID = 11110001
L8_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L8_1.m_bWaitClick = false
L8_1.m_fWaitTime = 0.4
L8_1.m_fFlashBangTime = 0.25
L9_1 = {}
L9_1.m_CutScenProcessKey = 9
L9_1.m_CutScenID = 11110001
L9_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L9_1.m_bWaitClick = false
L9_1.m_fWaitTime = 1.5
L9_1.m_fFlashBangTime = 0.25
L10_1 = {}
L10_1.m_CutScenProcessKey = 10
L10_1.m_CutScenID = 11110001
L10_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L10_1.m_bWaitClick = false
L10_1.m_fWaitTime = 0
L10_1.m_bFadeIn = false
L10_1.m_fFadeTime = 2
L11_1 = {}
L11_1.m_CutScenProcessKey = 11
L11_1.m_CutScenID = 11110001
L11_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L11_1.m_bWaitClick = false
L11_1.m_fWaitTime = 1
L11_1.m_BGFileName = "LIFETIME"
L11_1.m_bFadeIn = true
L11_1.m_fFadeTime = 3
L11_1.m_StartBGMFileName = "CUTSCENE_HOPE"
L11_1.m_StartFXSoundName = "FX_CUTSCEN_DOOR_WOOD"
L11_1.m_CharStrID = "YUMA_FALLEN_NULL_NULL"
L11_1.m_Pos = "C_D"
L12_1 = {}
L12_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@12#Talk"
L12_1.m_CutScenProcessKey = 12
L12_1.m_CutScenID = 11110001
L12_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L12_1.m_bWaitClick = true
L12_1.m_fWaitTime = 0
L12_1.m_CharStrID = "YUMA_FALLEN_NULL_NULL"
L12_1.m_Pos = "C"
L12_1.m_Talk_KOREA = "난 복잡한 얘기는 별로 관심없어."
L12_1.m_fTalkTime = 0.03
L12_1.m_Talk_JPN = "こっちは難しい話には興味ねえんだ。"
L12_1.m_Talk_ENG = "I'm not interested in complicated things."
L12_1.m_Talk_TWN = "我對複雜的事情沒什麼興趣。"
L12_1.m_Talk_THA = "ฉันไม่สนใจสิ่งที่ซับซ้อน"
L12_1.m_Talk_VTN = "Tôi không quan tâm đến những chuyện phức tạp."
L12_1.m_Talk_SCN = "我对复杂的事情没什么兴趣。"
L12_1.m_Talk_DEU = "Ich bin nicht an komplizierten Dingen interessiert."
L12_1.m_Talk_FRA = "Ces trucs compliqués, ça m'intéresse pas."
L13_1 = {}
L13_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@13#Talk"
L13_1.m_CutScenProcessKey = 13
L13_1.m_CutScenID = 11110001
L13_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L13_1.m_bWaitClick = true
L13_1.m_fWaitTime = 0
L13_1.m_Face = "UNIT_LAUGH"
L13_1.m_CharStrID = "YUMA_FALLEN_NULL_NULL"
L13_1.m_Pos = "C"
L13_1.m_Crash = 30
L13_1.m_Talk_KOREA = "역시 싸움이 최고지! 한 방에 한 놈씩 땅바닥에 꽂아 버릴 때마다 기분 째지거든!"
L13_1.m_fTalkTime = 0.03
L13_1.m_Talk_JPN = "アタシはとにかく喧嘩がしてえ！喧嘩はいいぜ。一人一発ずつぶん殴って地面に叩きつけてやりゃ、スカッとできるしな！"
L13_1.m_Talk_ENG = "All I know is fighting. It feels awesome when I knock my enemies down, one by one."
L13_1.m_Talk_TWN = "果然打架才是王道！一拳把一個傢伙打倒在地，這感覺真是爽呆了！"
L13_1.m_Talk_THA = "ฉันรู้จักแค่การต่อสู้ ฉันรู้สึกดีที่ได้โค่นศัตรูทีละตัว"
L13_1.m_Talk_VTN = "Tất cả những gì tôi biết là chiến đấu. Cảm giác thật tuyệt khi hạ gục kẻ thù của mình, từng người một."
L13_1.m_Talk_SCN = "果然打架才是王道！一拳把一个家伙锤到地里，别提有多爽了！"
L13_1.m_Talk_DEU = "Ich kann nur kämpfen. Es ist ein großartiges Gefühl, wenn ich meine Feinde einen nach dem anderen niederschlage."
L13_1.m_Talk_FRA = "Tout ce que j'sais faire, c'est me battre. Et quand je descends mes ennemis les uns après les autres, c'est le pied."
L14_1 = {}
L14_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@14#Talk"
L14_1.m_CutScenProcessKey = 14
L14_1.m_CutScenID = 11110001
L14_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L14_1.m_bWaitClick = true
L14_1.m_fWaitTime = 0
L14_1.m_Face = "UNIT_DESPAIR"
L14_1.m_CharStrID = "YUMA_FALLEN_NULL_NULL"
L14_1.m_Pos = "C"
L14_1.m_Talk_KOREA = "하아...... 근데 요샌 내 소문이 이 근처까지 쫙 퍼진 것 같단 말이야......"
L14_1.m_fTalkTime = 0.03
L14_1.m_Talk_JPN = "ふぅ……だというのに、近頃はこの辺りにまでアタシの噂が広まっちまったみたいでな……"
L14_1.m_Talk_ENG = "*Sigh* But it seems that the word has gotten out about me."
L14_1.m_Talk_TWN = "唉……但是最近，關於我的傳聞好像傳到這裡來了……"
L14_1.m_Talk_THA = "*เฮ้อ* แต่ดูเหมือนว่าคนจะพากันพูดถึงฉัน"
L14_1.m_Talk_VTN = "*Thở dài* Nhưng có vẻ như cảm giác đó đã rời bỏ tôi rồi."
L14_1.m_Talk_SCN = "哈啊...但最近关于我的传闻好像都传到这儿来了......"
L14_1.m_Talk_DEU = "*Seufz* Aber es scheint, dass mein Ruf sich herumgesprochen hat."
L14_1.m_Talk_FRA = "*Soupir* Mais apparemment, je commence à me faire une sacrée réputation."
L15_1 = {}
L15_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@15#Talk"
L15_1.m_CutScenProcessKey = 15
L15_1.m_CutScenID = 11110001
L15_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L15_1.m_bWaitClick = true
L15_1.m_fWaitTime = 0
L15_1.m_CharStrID = "YUMA_FALLEN_NULL_NULL"
L15_1.m_Pos = "C"
L15_1.m_Talk_KOREA = "어떻게 된 게 하루 종일 싸돌아다녀도 시비 거는 놈이 한 놈도 없을 수 있어?"
L15_1.m_fTalkTime = 0.03
L15_1.m_Talk_JPN = "一日中歩き回ったってのに、喧嘩を吹っかけてくる奴が一人もいやしねえ。あり得ないだろ？"
L15_1.m_Talk_ENG = "No one seems to want to pick a fight with me, no matter how long I roam the streets."
L15_1.m_Talk_TWN = "不然怎麼可能我溜達了一天，也沒人上來挑釁？"
L15_1.m_Talk_THA = "ไม่มีใครอยากหาเรื่องฉันเลย ไม่ว่าฉันจะเตร็ดเตร่อยู่บนถนนนานแค่ไหน"
L15_1.m_Talk_VTN = "Không ai muốn gây gổ với tôi, bất kể tôi lang thang trên đường bao lâu đi chăng nữa."
L15_1.m_Talk_SCN = "不然怎么可能我溜达了一天也没人上来挑衅？"
L15_1.m_Talk_DEU = "Niemand scheint sich mit mir prügeln zu wollen, egal wie lange ich durch die Straßen ziehe."
L15_1.m_Talk_FRA = "Je passe mon temps à traîner dans les rues à la recherche d'adversaires, mais plus personne veut se battre contre moi."
L16_1 = {}
L16_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@16#Talk"
L16_1.m_CutScenProcessKey = 16
L16_1.m_CutScenID = 11110001
L16_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L16_1.m_bWaitClick = true
L16_1.m_fWaitTime = 0
L16_1.m_Face = "UNIT_HATE"
L16_1.m_CharStrID = "YUMA_FALLEN_NULL_NULL"
L16_1.m_Pos = "C"
L16_1.m_Crash = 40
L16_1.m_Talk_KOREA = "아, 진짜! 생각하니까 또 주먹 근질거려서 미치겠네!"
L16_1.m_fTalkTime = 0.03
L16_1.m_Talk_JPN = "ああ、もう！思い出したら、また拳がうずいてきたじゃねえか！"
L16_1.m_Talk_ENG = "Darn it! Thinking about that makes my fists itch again!"
L16_1.m_Talk_TWN = "啊，真是的！一想到這裡，我的拳頭就癢到快要瘋了！"
L16_1.m_Talk_THA = "ให้ตายสิ! พอคิดแล้วก็คันหมัดอีกแล้ว!"
L16_1.m_Talk_VTN = "Khỉ thật! Nghĩ đến chuyện đó lại khiến tay tôi ngứa ngáy!"
L16_1.m_Talk_SCN = "啊，真是的！一想到这儿拳头又发痒了！"
L16_1.m_Talk_DEU = "Verdammt! Schon beim Gedanken daran fangen meine Fäuste wieder an zu jucken!"
L16_1.m_Talk_FRA = "Mince ! Quand j'y pense, j'ai les poings qui me démangent !"
L17_1 = {}
L17_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@17#Talk"
L17_1.m_CutScenProcessKey = 17
L17_1.m_CutScenID = 11110001
L17_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L17_1.m_bWaitClick = true
L17_1.m_fWaitTime = 0
L17_1.m_Face = "UNIT_IDLE"
L17_1.m_CharStrID = "YUMA_FALLEN_NULL_NULL"
L17_1.m_Pos = "C"
L17_1.m_Talk_KOREA = "그러니까 종신...... 그 종신 뭔가인가 하여튼 그거, 꼭 내 입으로 말해 줘야 돼?"
L17_1.m_fTalkTime = 0.03
L17_1.m_Talk_JPN = "つまり、その……あれだよあれ、終身なんちゃらってヤツ。アタシの口から言わなきゃなんないのか？"
L17_1.m_Talk_ENG = "So that lifetime whatever that you're talking about... Do I really have to say it in words?"
L17_1.m_Talk_TWN = "所以，終身……那個終身什麼來著，還要我親口告訴你嗎？"
L17_1.m_Talk_THA = "ไอ้ชั่วชีวิตหรืออะไรที่คุณพูดถึงน่ะ… ฉันต้องบอกออกมาเป็นคำพูดจริงๆ เหรอ?"
L17_1.m_Talk_VTN = "Vậy nên dù cuộc đời đó là gì đi chăng nữa… Tôi thực sự phải nói thẳng ra à?"
L17_1.m_Talk_SCN = "所以，终身......那个终身啥的，反正是那个东西。"
L17_1.m_Talk_DEU = "Dieses „lebenslang“, von dem Sie sprechen, ist also … Muss ich das wirklich mit Worten sagen?"
L17_1.m_Talk_FRA = "Bon, ce machin à vie dont tu me parles, là... Rah, comment t'expliquer ça..."
L18_1 = {}
L18_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@18#Talk"
L18_1.m_CutScenProcessKey = 18
L18_1.m_CutScenID = 11110001
L18_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L18_1.m_bWaitClick = true
L18_1.m_fWaitTime = 0
L18_1.m_CharStrID = "YUMA_FALLEN_NULL_NULL"
L18_1.m_Pos = "C"
L18_1.m_Talk_KOREA = "알잖아. 딴 녀석들이 하란 대로 하는 건 내 방식에 안 맞는다고."
L18_1.m_fTalkTime = 0.03
L18_1.m_Talk_JPN = "知ってんだろ？他の奴らのやり方はアタシの性に合わねえんだよ。"
L18_1.m_Talk_ENG = "You know how I feel about people ordering me around."
L18_1.m_Talk_TWN = "你知道的嘛。別人說什麼就做什麼，這可不是我的風格。"
L18_1.m_Talk_THA = "คุณก็รู้ว่าฉันรู้สึกยังไงเวลามีคนมาออกคำสั่งฉัน"
L18_1.m_Talk_VTN = "Ngài biết tôi cảm thấy thế nào khi mọi người ra lệnh cho tôi rồi đấy."
L18_1.m_Talk_SCN = "你不是知道嘛。听别人的命令可不是我的性格。"
L18_1.m_Talk_DEU = "Sie wissen, was ich von Leuten halte, die mich herumkommandieren."
L18_1.m_Talk_FRA = "Tu sais que j'aime pas qu'on me donne des ordres."
L19_1 = {}
L19_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@19#Talk"
L19_1.m_CutScenProcessKey = 19
L19_1.m_CutScenID = 11110001
L19_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L19_1.m_bWaitClick = true
L19_1.m_fWaitTime = 0
L19_1.m_Face = "UNIT_SERIOUS"
L19_1.m_CharStrID = "YUMA_FALLEN_NULL_NULL"
L19_1.m_Pos = "C"
L19_1.m_Talk_KOREA = "근데 그걸 알면서도 이런 종이를 들이밀어? 혹시 나랑 한 판 붙어 보잔 거야, 응?"
L19_1.m_fTalkTime = 0.03
L19_1.m_Talk_JPN = "知ってるくせして、そんな紙切れをアタシに突きつけてきやがって。ひょっとして喧嘩売ってんのか？あぁ？"
L19_1.m_Talk_ENG = "And you still had the nerve to shove this stupid paper in my face? Are you provoking me into a fight? Huh? Is that what you're doing?"
L19_1.m_Talk_TWN = "你都知道這種事了，還把這張紙推給我？你是想和我打一架嗎，啊？"
L19_1.m_Talk_THA = "แล้วนี่คุณยังกล้ายัดกระดาษโง่ๆ นี่ใส่หน้าฉันอีกเหรอ? นี่จะยั่วโมโหฉันรึไง? หืม? พยายามจะทำแบบนั้นอยู่ใช่มั้ย?"
L19_1.m_Talk_VTN = "Và ngài vẫn can đảm ném tờ giấy ngu ngốc này vào mặt tôi sao? Ngài đang khiêu khích tôi đánh nhau với ngài đấy à? Hả? Đó là chuyện ngài đang làm sao?"
L19_1.m_Talk_SCN = "你都知道还把这种东西推给我？是不是想和我打一架啊，嗯？"
L19_1.m_Talk_DEU = "Und Sie wagen es trotzdem, mir dieses dumme Papier unter die Nase zu halten? Wollen Sie mich zu einem Kampf herausfordern? Hm? Ist es das, was Sie vorhaben?"
L19_1.m_Talk_FRA = "Et toi, t'as les nerfs de me convoquer pour un papelard à la noix ? C'est une provocation ? Hein ? Tu veux te battre ?"
L20_1 = {}
L20_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@20#Talk"
L20_1.m_CutScenProcessKey = 20
L20_1.m_CutScenID = 11110001
L20_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L20_1.m_bWaitClick = true
L20_1.m_fWaitTime = 0
L20_1.m_Face = "UNIT_LAUGH"
L20_1.m_CharStrID = "YUMA_FALLEN_NULL_NULL"
L20_1.m_Pos = "C"
L20_1.m_Talk_KOREA = "......킥킥, 눈도 깜짝 안 하네. 주먹질 한 번 안 해 본 것처럼 생겨선 배짱만 좋아 가지곤."
L20_1.m_fTalkTime = 0.03
L20_1.m_Talk_JPN = "……ククッ、眉一つ動かさねえと来た。大人しそうなナリして、肝っ玉の太い野郎だぜ。"
L20_1.m_Talk_ENG = "*Giggle* You didn't even blink. You have guts for someone who looks so meek."
L20_1.m_Talk_TWN = "……嘻嘻，眼睛眨都不眨一下。看起來弱不禁風的，膽子倒是不小嘛。"
L20_1.m_Talk_THA = "*คิกคัก* คุณไม่กระพริบด้วยซ้ำ คุณนี่กล้านะสำหรับคนที่ดูติ๋มขนาดนี้"
L20_1.m_Talk_VTN = "*Khúc khích* Ngài thậm chí còn không thèm chớp mắt. Lá gan khá to đối với một kẻ có vẻ ngoài nhu mì đấy."
L20_1.m_Talk_SCN = "......嘻嘻，眼睛都不眨一下啊。看起来弱不禁风的，胆子倒不小嘛。"
L20_1.m_Talk_DEU = "*Kicher* Sie haben nicht einmal geblinzelt. Für jemanden, der so sanftmütig aussieht, haben Sie Mut."
L20_1.m_Talk_FRA = "Ha ha ha, t'as même pas cligné des yeux. T'as du cran, pour un gringalet."
L21_1 = {}
L21_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@21#Talk"
L21_1.m_CutScenProcessKey = 21
L21_1.m_CutScenID = 11110001
L21_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L21_1.m_bWaitClick = true
L21_1.m_fWaitTime = 0
L21_1.m_CharStrID = "YUMA_FALLEN_NULL_NULL"
L21_1.m_Pos = "C"
L21_1.m_Talk_KOREA = "뭐, 부탁하는 게 영 심심하긴 한데~"
L21_1.m_fTalkTime = 0.03
L21_1.m_Talk_JPN = "まあ、どうせならもっと闘志に火がつくような頼み方をしてほしかったな。"
L21_1.m_Talk_ENG = "Well, I don't like the way you're asking me..."
L21_1.m_Talk_TWN = "不過，這請求是很無聊沒錯啦～"
L21_1.m_Talk_THA = "อืม ฉันไม่ชอบวิธีที่คุณถามฉันเลย…"
L21_1.m_Talk_VTN = "Chà, tôi không thích cách ngài đang hỏi tôi đâu…"
L21_1.m_Talk_SCN = "虽然这请求确实很无聊~"
L21_1.m_Talk_DEU = "Die Art und Weise, wie Sie mich fragen, gefällt mir nicht …"
L21_1.m_Talk_FRA = "C'est vrai que j'aime pas la façon dont tu me demandes ça..."
L22_1 = {}
L22_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@22#Talk"
L22_1.m_CutScenProcessKey = 22
L22_1.m_CutScenID = 11110001
L22_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L22_1.m_bWaitClick = true
L22_1.m_fWaitTime = 0
L22_1.m_Face = "UNIT_IDLE"
L22_1.m_CharStrID = "YUMA_FALLEN_NULL_NULL"
L22_1.m_Pos = "C"
L22_1.m_Talk_KOREA = "주인님은 내가 싸우는 걸 마음에 들어하시거든. 그때 뭐랬더라......"
L22_1.m_fTalkTime = 0.03
L22_1.m_Talk_JPN = "主様はアタシが喧嘩すると喜んでくれるのさ。えーと、何つってたかな……"
L22_1.m_Talk_ENG = "But Mistress likes it when I fight. What was the word that she used the other day?"
L22_1.m_Talk_TWN = "但主人非常喜歡我打架。那時候說什麼來著……"
L22_1.m_Talk_THA = "แต่อาจารย์ชอบเวลาที่ฉันสู้ วันก่อนเธอใช้คำว่าอะไรนะ?"
L22_1.m_Talk_VTN = "Nhưng Sếp thích nhìn tôi chiến đấu. Từ mà ngài ấy đã sử dụng ngày hôm trước là gì nhỉ?"
L22_1.m_Talk_SCN = "不过主人非常喜欢我打架来着。那时候说什么来着......"
L22_1.m_Talk_DEU = "Aber die Meisterin mag es, wenn ich kämpfe. Wie war das Wort, das sie neulich benutzt hat?"
L22_1.m_Talk_FRA = "Mais mon maître aime me voir me battre. Comment elle a dit, déjà, l'autre jour ?"
L23_1 = {}
L23_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@23#Talk"
L23_1.m_CutScenProcessKey = 23
L23_1.m_CutScenID = 11110001
L23_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L23_1.m_bWaitClick = true
L23_1.m_fWaitTime = 0
L23_1.m_Face = "UNIT_LAUGH"
L23_1.m_CharStrID = "YUMA_FALLEN_NULL_NULL"
L23_1.m_Pos = "C"
L23_1.m_Talk_KOREA = "아, 그래! 꼴사납다더라고!"
L23_1.m_fTalkTime = 0.03
L23_1.m_Talk_JPN = "あっ、そうそう！とんだ暴れ馬だって言ってたな！"
L23_1.m_Talk_ENG = "Oh, yeah! Unsightly!"
L23_1.m_Talk_TWN = " 啊，對了！真讓人討厭！"
L23_1.m_Talk_THA = "อ๋อ ใช่แล้ว! ไม่น่าดู!"
L23_1.m_Talk_VTN = "Ồ, đúng rồi! Khó coi!"
L23_1.m_Talk_SCN = "啊，对！说我丑凶丑凶的！"
L23_1.m_Talk_DEU = "Oh, ja! Unansehnlich!"
L23_1.m_Talk_FRA = "Ah, ouais ! C'est « disgracieux » !"
L24_1 = {}
L24_1.m_CutScenKey_Talk = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@24#Talk"
L24_1.m_CutScenProcessKey = 24
L24_1.m_CutScenID = 11110001
L24_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L24_1.m_bWaitClick = true
L24_1.m_fWaitTime = 0
L24_1.m_CharStrID = "YUMA_FALLEN_NULL_NULL"
L24_1.m_Pos = "C"
L24_1.m_Talk_KOREA = "뭔 뜻인지 몰라도 사납다고 하니까 좋은 말이겠지? 안 그래?"
L24_1.m_fTalkTime = 0.03
L24_1.m_Talk_JPN = "どういう意味だか知らねえけど、誉め言葉なんだよな？だって暴れると気持ちイイしな！"
L24_1.m_Talk_ENG = "I don't know what it means exactly, but I bet it's a compliment, because it has the word sight in it. So basically,"
L24_1.m_Talk_TWN = "雖然不知道這是什麼意思，但既然說我討厭，就是在誇我，對吧？"
L24_1.m_Talk_THA = "ฉันไม่รู้หรอกว่ามันหมายความว่าไง แต่ฉันพนันได้เลยว่ามันเป็นคำชม เพราะมันมีคำว่าดูอยู่ด้วย ดังนั้น ง่ายๆ เลยนะ"
L24_1.m_Talk_VTN = "Tôi không biết chính xác nghĩa, nhưng tôi dám cá đó là một lời khen, bởi vì nó có từ \"coi\" ở trong đó. Nên về cơ bản,"
L24_1.m_Talk_SCN = "虽然不知道啥意思，但既然说我很凶，应该是在夸我吧？不是吗？"
L24_1.m_Talk_DEU = "Ich weiß nicht, was es genau bedeutet, aber ich wette, es ist ein Kompliment, weil es das Wort „sehen“ enthält. Also grundsätzlich"
L24_1.m_Talk_FRA = "J'sais pas ce que ça veut dire exactement, mais ça doit être un compliment, vu qu'il y a « grâce » dedans."
L25_1 = {}
L26_1 = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@25#Talk"
L25_1.m_CutScenKey_Talk = L26_1
L26_1 = 25
L25_1.m_CutScenProcessKey = L26_1
L25_1.m_CutScenID = 11110001
L25_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L25_1.m_bWaitClick = true
L25_1.m_fWaitTime = 0
L25_1.m_CharStrID = "YUMA_FALLEN_NULL_NULL"
L25_1.m_Pos = "C"
L26_1 = "어쨌든 그럼 내가 자꾸 싸우고 다녀야 주인님도 좋아하시지 않겠냐, 이 말이야."
L25_1.m_Talk_KOREA = L26_1
L25_1.m_fTalkTime = 0.03
L26_1 = "まあ、そんなわけで、アタシはもっともっと暴れまくって、主様に喜んでもらいてえ。"
L25_1.m_Talk_JPN = L26_1
L26_1 = "I think the more I go around, the happier Mistress will be."
L25_1.m_Talk_ENG = L26_1
L26_1 = "反正就是說，只要我一直打架，主人就會高興吧。"
L25_1.m_Talk_TWN = L26_1
L26_1 = "ฉันว่ายิ่งฉันออกไปมีเรื่องบ่อย อาจารย์ก็จะยิ่งพอใจ"
L25_1.m_Talk_THA = L26_1
L26_1 = "tôi nghĩ là tôi chiến đấu càng nhiều, Sếp sẽ càng vui."
L25_1.m_Talk_VTN = L26_1
L26_1 = "反正就是说，我一直打架，主人也会开心。"
L25_1.m_Talk_SCN = L26_1
L26_1 = "denke ich, je mehr ich herumkomme, desto glücklicher wird die Meisterin sein."
L25_1.m_Talk_DEU = L26_1
L26_1 = "Donc, en gros, plus je me bats, plus ça fait plaisir à mon maître."
L25_1.m_Talk_FRA = L26_1
L26_1 = {}
L27_1 = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@26#Talk"
L26_1.m_CutScenKey_Talk = L27_1
L27_1 = 26
L26_1.m_CutScenProcessKey = L27_1
L26_1.m_CutScenID = 11110001
L26_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L26_1.m_bWaitClick = true
L26_1.m_fWaitTime = 0
L26_1.m_Face = "UNIT_IDLE"
L26_1.m_CharStrID = "YUMA_FALLEN_NULL_NULL"
L26_1.m_Pos = "C"
L27_1 = "근데 사장님은 박 터지게 싸울 놈들만 찾아다니잖아?"
L26_1.m_Talk_KOREA = L27_1
L26_1.m_fTalkTime = 0.03
L27_1 = "そこでだ。あんたは次から次に喧嘩相手を見つけてくれるだろ？"
L26_1.m_Talk_JPN = L27_1
L27_1 = "And all you do, Boss, is to look around for fights."
L26_1.m_Talk_ENG = L27_1
L27_1 = "而且老闆不是只找那些打架很火爆的傢伙嗎？"
L26_1.m_Talk_TWN = L27_1
L27_1 = "และสิ่งที่คุณต้องทำนะบอส ก็คือการมองหาการต่อสู้"
L26_1.m_Talk_THA = L27_1
L27_1 = "Và tất cả những chuyện ngài làm, ông chủ, là tìm người chiến đấu."
L26_1.m_Talk_VTN = L27_1
L27_1 = "而且老板不是只找那些打架很厉害的家伙的麻烦吗？"
L26_1.m_Talk_SCN = L27_1
L27_1 = "Und alles, was Sie tun, Boss, ist, sich nach Kämpfen umzusehen."
L26_1.m_Talk_DEU = L27_1
L27_1 = "Et toi, boss, t'as un don pour chercher la bagarre."
L26_1.m_Talk_FRA = L27_1
L27_1 = {}
L28_1 = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@27#Talk"
L27_1.m_CutScenKey_Talk = L28_1
L28_1 = 27
L27_1.m_CutScenProcessKey = L28_1
L27_1.m_CutScenID = 11110001
L27_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L27_1.m_bWaitClick = true
L27_1.m_fWaitTime = 0
L27_1.m_CharStrID = "YUMA_FALLEN_NULL_NULL"
L27_1.m_Pos = "C"
L28_1 = "사장님은 찾고 패는 건 내가 하는 거야! 이거 진짜 끝내 주는 콤보 아냐?"
L27_1.m_Talk_KOREA = L28_1
L27_1.m_fTalkTime = 0.03
L28_1 = "あんたが相手を見つけて、それをアタシがぶん殴る！どうよ、見事なワンツーコンボだろ？"
L27_1.m_Talk_JPN = L28_1
L28_1 = "You do the looking, and I do the fighting! How awesome is that?"
L27_1.m_Talk_ENG = L28_1
L28_1 = "老闆找人，我來幹架！這根本是最佳拍檔吧？"
L27_1.m_Talk_TWN = L28_1
L28_1 = "คุณเป็นคนหา ส่วนฉันเป็นคนสู้! เจ๋งเลยใช่มั้ยล่ะ?"
L27_1.m_Talk_THA = L28_1
L28_1 = "Ngài tìm, và tôi chiến đấu! Còn gì tuyệt hơn thế nữa cơ chứ?"
L27_1.m_Talk_VTN = L28_1
L28_1 = "老板来找人，我来干架！这完全是最棒的组合对吧？"
L27_1.m_Talk_SCN = L28_1
L28_1 = "Sie suchen und ich kämpfe! Ist das nicht toll?"
L27_1.m_Talk_DEU = L28_1
L28_1 = "Toi, tu cherches, et moi, je tape ! C'est pas génial ?"
L27_1.m_Talk_FRA = L28_1
L28_1 = {}
L29_1 = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@28#Talk"
L28_1.m_CutScenKey_Talk = L29_1
L29_1 = 28
L28_1.m_CutScenProcessKey = L29_1
L28_1.m_CutScenID = 11110001
L28_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L28_1.m_bWaitClick = true
L28_1.m_fWaitTime = 0
L28_1.m_CharStrID = "YUMA_FALLEN_NULL_NULL"
L28_1.m_Pos = "C"
L28_1.m_Crash = 30
L29_1 = "오빠도 내가 여기 있는 게 주인님을 돕는 거라고 그랬고!"
L28_1.m_Talk_KOREA = L29_1
L28_1.m_fTalkTime = 0.03
L29_1 = "兄さんだって、アタシはここにいた方が主様を助けることになるって言ってたからな！"
L28_1.m_Talk_JPN = L29_1
L29_1 = "And Doma also said I'm helping Mistress by staying here with you."
L28_1.m_Talk_ENG = L29_1
L29_1 = "哥哥也說過，我在這裡是在幫助主人！"
L28_1.m_Talk_TWN = L29_1
L29_1 = "และโดมะยังบอกด้วยว่าฉันจะทำประโยชน์ให้อาจารย์จากการอยู่ที่นี่กับคุณ"
L28_1.m_Talk_THA = L29_1
L29_1 = "Và Doma cũng nói là tôi sẽ hỗ trợ cho Sếp nếu ở lại đây với ngài."
L28_1.m_Talk_VTN = L29_1
L29_1 = "哥哥也说过，我在这里也是对主人的帮助！"
L28_1.m_Talk_SCN = L29_1
L29_1 = "Und Doma hat auch gesagt, dass ich der Meisterin helfe, indem ich hier bei Ihnen bleibe."
L28_1.m_Talk_DEU = L29_1
L29_1 = "En plus, Doma m'a dit que je rendais service à notre maître en restant avec toi."
L28_1.m_Talk_FRA = L29_1
L29_1 = {}
L30_1 = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@29#Talk"
L29_1.m_CutScenKey_Talk = L30_1
L30_1 = 29
L29_1.m_CutScenProcessKey = L30_1
L29_1.m_CutScenID = 11110001
L29_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L29_1.m_bWaitClick = true
L29_1.m_fWaitTime = 0
L29_1.m_Face = "UNIT_LAUGH"
L29_1.m_CharStrID = "YUMA_FALLEN_NULL_NULL"
L29_1.m_Pos = "C"
L30_1 = 50
L29_1.m_Crash = L30_1
L30_1 = "으하하하하!"
L29_1.m_Talk_KOREA = L30_1
L29_1.m_fTalkTime = 0.03
L30_1 = "アーッハハハハッ！"
L29_1.m_Talk_JPN = L30_1
L30_1 = "Mwa hah hah!"
L29_1.m_Talk_ENG = L30_1
L30_1 = "哇哈哈哈哈！"
L29_1.m_Talk_TWN = L30_1
L30_1 = "วะ ฮ่า ฮ่า!"
L29_1.m_Talk_THA = L30_1
L30_1 = "Moa ha ha!"
L29_1.m_Talk_VTN = L30_1
L30_1 = "哈哈哈哈！"
L29_1.m_Talk_SCN = L30_1
L30_1 = "Muahaha!"
L29_1.m_Talk_DEU = L30_1
L30_1 = "Mouah ha ha !"
L29_1.m_Talk_FRA = L30_1
L30_1 = {}
L31_1 = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@30#Talk"
L30_1.m_CutScenKey_Talk = L31_1
L30_1.m_CutScenProcessKey = 30
L30_1.m_CutScenID = 11110001
L30_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L30_1.m_bWaitClick = true
L30_1.m_fWaitTime = 0
L30_1.m_CharStrID = "YUMA_FALLEN_NULL_NULL"
L30_1.m_Pos = "C"
L30_1.m_Crash = 20
L31_1 = "하하...... 하......."
L30_1.m_Talk_KOREA = L31_1
L30_1.m_fTalkTime = 0.03
L31_1 = "ハハ……ハ……"
L30_1.m_Talk_JPN = L31_1
L31_1 = "Hah hah... Hah..."
L30_1.m_Talk_ENG = L31_1
L31_1 = "哈哈……哈……"
L30_1.m_Talk_TWN = L31_1
L31_1 = "ฮะฮะ… ฮะ…"
L30_1.m_Talk_THA = L31_1
L31_1 = "Hah hah… Hah…"
L30_1.m_Talk_VTN = L31_1
L31_1 = "哈哈......哈......"
L30_1.m_Talk_SCN = L31_1
L31_1 = "Haha … ha …"
L30_1.m_Talk_DEU = L31_1
L31_1 = "Ha ha... ha..."
L30_1.m_Talk_FRA = L31_1
L31_1 = {}
L32_1 = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA@31#Talk"
L31_1.m_CutScenKey_Talk = L32_1
L32_1 = 31
L31_1.m_CutScenProcessKey = L32_1
L31_1.m_CutScenID = 11110001
L31_1.m_CutScenStrID = "LIFETIME_START_NKM_UNIT_C_FALLEN_YUMA"
L31_1.m_bWaitClick = true
L31_1.m_fWaitTime = 0
L31_1.m_Face = "UNIT_DESPAIR"
L31_1.m_CharStrID = "YUMA_FALLEN_NULL_NULL"
L31_1.m_Pos = "C"
L32_1 = "......아, 씨. 이건 말하지 말랬는데. 방금 얘긴 못 들은 거다?"
L31_1.m_Talk_KOREA = L32_1
L31_1.m_fTalkTime = 0.03
L32_1 = "……クッ、まずったぜ。今のは内緒だって言われてるんだった。なぁ、聞かなかったことにしてくれるか？"
L31_1.m_Talk_JPN = L32_1
L32_1 = "Oh, crap. I just remembered. I wasn't supposed to tell you that. Just pretend you never heard that, okay?"
L31_1.m_Talk_ENG = L32_1
L32_1 = "……啊，糟糕。他要我別說出去的。剛才那句話你就當沒聽到吧。"
L31_1.m_Talk_TWN = L32_1
L32_1 = "ตายจริง ฉันเพิ่งนึกขึ้นได้ ฉันไม่ควรจะบอกคุณเลย แค่แกล้งทำเป็นไม่ได้ยินแล้วกันนะ โอเคมั้ย?"
L31_1.m_Talk_THA = L32_1
L32_1 = "Chết tiệt. Tôi vừa mới nhớ ra. Tôi không được nói chuyện đó cho ngài. Cứ giả vờ là ngài chưa bao giờ nghe thấy vụ đó, được chứ?"
L31_1.m_Talk_VTN = L32_1
L32_1 = "......啊，糟糕。他说让我别说出去的。刚才那句话你就当没听到哦？"
L31_1.m_Talk_SCN = L32_1
L32_1 = "Oh, Mist. Mir fällt gerade ein … Das hätte ich Ihnen nicht sagen sollen. Tun Sie einfach so, als hätten Sie das nie gehört, okay?"
L31_1.m_Talk_DEU = L32_1
L32_1 = "Oh, non. J'crois que j'étais pas censée te dire ça. T'as qu'à faire comme si t'avais rien entendu, d'ac' ?"
L31_1.m_Talk_FRA = L32_1
L0_1[1] = L1_1
L0_1[2] = L2_1
L0_1[3] = L3_1
L0_1[4] = L4_1
L0_1[5] = L5_1
L0_1[6] = L6_1
L0_1[7] = L7_1
L0_1[8] = L8_1
L0_1[9] = L9_1
L0_1[10] = L10_1
L0_1[11] = L11_1
L0_1[12] = L12_1
L0_1[13] = L13_1
L0_1[14] = L14_1
L0_1[15] = L15_1
L0_1[16] = L16_1
L0_1[17] = L17_1
L0_1[18] = L18_1
L0_1[19] = L19_1
L0_1[20] = L20_1
L0_1[21] = L21_1
L0_1[22] = L22_1
L0_1[23] = L23_1
L0_1[24] = L24_1
L0_1[25] = L25_1
L0_1[26] = L26_1
L0_1[27] = L27_1
L0_1[28] = L28_1
L0_1[29] = L29_1
L0_1[30] = L30_1
L0_1[31] = L31_1
m_dicNKCCutScenTempletByID = L0_1
