---
--- Generated by suixin
--- Created by suixin.
--- DateTime: 2024/3/14 16:40
---
local util = require 'XLua.util'
local CoWait = CS.Engine.Lib.CoWait
local KTool = CS.Engine.Lib.KTool
local cs_coroutine     = require "XLua.cs_coroutine"
--- from: Assets/BundleResources/Prefabs/ActivityMountain/11300302/ActivityMountainOptionEntryDialog.prefab > name: ActivityMountainOptionEntryDialog
---@class ActivityMountainOptionEntryDialog
---@field Env                           	ActivityMountainOptionEntryDialog       
---@field controller                    	Engine.UI.UILuaDialog                   
---@field BtnExchange                   	UnityEngine.RectTransform               
---@field TextTime                      	TMPro.TextMeshProUGUI                   
---@field BtnDraw                       	UnityEngine.RectTransform               
---@field BtnManage                     	UnityEngine.RectTransform               
---@field BtnMake                       	UnityEngine.RectTransform               
---@field BtnProtect                    	UnityEngine.RectTransform               
---@field BtnStory                      	UnityEngine.RectTransform               
---@field BtnManageRed                  	UnityEngine.RectTransform               
---@field BtnProtectRed                 	UnityEngine.RectTransform               
---@field BtnExchangeRed                	UnityEngine.RectTransform               
---@field ImgTitle                      	UnityEngine.RectTransform               
local ActivityMountainOptionEntryDialog = Class("ActivityMountainOptionEntryDialog")
local ActivityCakeUtils = import('Game.UI.ActivityCakeShopDialog.ActivityCakeUtils')
function ActivityMountainOptionEntryDialog:__init()
	self.requestSuccess = false
end

function ActivityMountainOptionEntryDialog:__delete()
	self.requestSuccess = false
	self.controller = nil
end

function ActivityMountainOptionEntryDialog:Awake()
	self:AddUIClick()
end

function ActivityMountainOptionEntryDialog:RefreshBtnName(data)
	local name = self:GetNameByIndex(data,1)
	self:RefreshNameShow(self.BtnStory,name,false)
	
	local name = self:GetNameByIndex(data,2)
	self:RefreshNameShow(self.BtnMake,name,true)
	
	local name = self:GetNameByIndex(data,3)
	self:RefreshNameShow(self.BtnProtect,name,true)
	
	local name = self:GetNameByIndex(data,4)
	self:RefreshNameShow(self.BtnExchange,name,true)
	
	local name = self:GetNameByIndex(data,5)
	self:RefreshNameShow(self.BtnManage,name,true)
end

function ActivityMountainOptionEntryDialog:GetNameByIndex(data, index)
	if data.entranceConf[index] then
		return data.entranceConf[index].name
	end
	return ""
end

function ActivityMountainOptionEntryDialog:RefreshNameShow(go,name,isShowName2)
	local name1 = go.transform:Find("Root/Title/TextDesc").gameObject
	if isShowName2 then
		local name2 = go.transform:Find("RootLock/Title/TextDesc").gameObject
		if isNotNull(name2) then
			CfUtils.FillText(name2,name)
		end
	end
	
	if isNotNull(name1) then
		CfUtils.FillText(name1,name)
	end
end

function ActivityMountainOptionEntryDialog:RefreshBtnUnLockStatus(go,status)
	local unLockRoot = go.transform:Find("RootLock").gameObject
	local lockRoot = go.transform:Find("Root").gameObject
	if not isNull(unLockRoot) then
		KTool.SetActive(unLockRoot.gameObject,not status)
	end
	
	if not isNull(lockRoot) then
		KTool.SetActive(lockRoot.gameObject, status)
	end
end

function ActivityMountainOptionEntryDialog:AddUIClick()
	SetButtonAction(self.BtnExchange.gameObject,Bind(self,self.OnBtnExchangeClick))
	SetButtonAction(self.BtnDraw.gameObject,Bind(self,self.OnBtnDrawClick))
	SetButtonAction(self.BtnManage.gameObject,Bind(self,self.OnBtnManageClick))
	SetButtonAction(self.BtnMake.gameObject,Bind(self,self.OnBtnMakeClick))
	SetButtonAction(self.BtnProtect.gameObject,Bind(self,self.OnBtnProtectClick))
	SetButtonAction(self.BtnStory.gameObject,Bind(self,self.OnBtnStoryClick))
	SetButtonAction(self.ImgTitle.gameObject,Bind(self,self.OnImgTitleClick))
end

function ActivityMountainOptionEntryDialog:OnFocus(focus)
	if focus then
		if self.requestSuccess then
			self:RefreshTopGoods()
		end
	end
end

function ActivityMountainOptionEntryDialog:OnShow()
	---@type Engine.Lib.CoWait
	local coWait = CoWait.Start():Coroutine(util.cs_generator(function()
		xTry(function()
		
		end)
	end))
	return coWait
end

function ActivityMountainOptionEntryDialog:OnInitialize()
	---@type Engine.Lib.CoWait
	local coWait = CoWait.Start():Coroutine(util.cs_generator(function()
		xTry(function()
			if not isNull(self.controller.Argument.extra) then
				self.isPlay = checkNumber(self.controller.Argument.extra) == 1
			else
				self.isPlay = false
			end
			if not self.isPlay then
				CfUtils.RefreshTopGoods({ })
				self.controller:SetExtraArgument(1)
			end
			local aniName = self.isPlay and "ActivityMountainOptionEntryDialog_Entry" or "ActivityMountainOptionEntryDialog_LoadEntry"
			CfUtils.PlayAnimation(self.controller, aniName)
			self.parameters = self.controller.Argument.parameters
			self.activityData = self.parameters.activityData
			self.co = cs_coroutine.start(function()
				local time = CfUtils.GetAnimationTime(self.controller,aniName)
				cs_coroutine.yield_return(CS.UnityEngine.WaitForSeconds(time - 1))
				self:RequestShow()
			end)
		end)
	end))
	return coWait
end

function ActivityMountainOptionEntryDialog:OnFinalize()
	local coWait = CoWait.Start():Coroutine(util.cs_generator(function()
		xTry(function()
			self.controller = nil --删除lua层引⽤到的c#对象否则不会产⽣c# gc回收到对象
			if isNotNull(self.co) then
				cs_coroutine.stop(self.co)
				self.co = nil
			end
			self:Delete()
			self = nil --lua层的gc需要    
		end)
	end))
	return coWait
end

function ActivityMountainOptionEntryDialog:Refresh(data)
	self:SetTimeShow()
	self:RefreshRedPoint(data)
	self:RefreshBtnStatus()
	self:RefreshBtnName(data)
	self:PlayBgm(data)
	self:RefreshTopGoods()
end

function ActivityMountainOptionEntryDialog:RefreshTopGoods()
	local topGoods = ActivityCakeUtils.GetActivityCakeMgr():GetTopGoods()
	CfUtils.RefreshTopGoods(topGoods)
end

function ActivityMountainOptionEntryDialog:RefreshBtnStatus()
	local id = self:GetIdByIndex(4)
	local isUnLock = self:IsUnLockFuncById(id)
	self:RefreshBtnUnLockStatus(self.BtnExchange,isUnLock)
	
	local id = self:GetIdByIndex(5)
	local isUnLock = self:IsUnLockFuncById(id)
	self:RefreshBtnUnLockStatus(self.BtnManage,isUnLock)
	
	local id = self:GetIdByIndex(2)
	local isUnLock = self:IsUnLockFuncById(id)
	self:RefreshBtnUnLockStatus(self.BtnMake,isUnLock)
	
	local id = self:GetIdByIndex(3)
	local isUnLock = self:IsUnLockFuncById(id)
	self:RefreshBtnUnLockStatus(self.BtnProtect,isUnLock)
end

function ActivityMountainOptionEntryDialog:PlayBgm(data)
	ActivityCakeUtils.PlayBgm()
end

function ActivityMountainOptionEntryDialog:RefreshRedPoint(data)
	CfUtils.SetActive(self.BtnManageRed,data.taskTips == 0)
	CfUtils.SetActive(self.BtnProtectRed,data.bossTips == 0)
	CfUtils.SetActive(self.BtnExchangeRed,data.luckyDrawTips == 0)
end

function ActivityMountainOptionEntryDialog:SetTimeShow()
	--region 时间
	local startTime =  self.activityData.startTime
	local closeTime =  self.activityData.closeTime
	local ActivityUtils         = import("Game.Activity.ActivityUtils")
	CfUtils.FillText(self.TextTime, ActivityUtils.ConventActivityDurationTime(startTime, closeTime))
	-- CfUtils.FillText(self.TextTime, os.date("%Y.%m.%d", startTime).."-"..os.date("%Y.%m.%d  %H:%M", closeTime))
end

function ActivityMountainOptionEntryDialog:RequestShow()
	GameUtils.Request(Interfaces.OverseaActivityCatParadiseHome,{ activityUuid = self.activityData.id},function(request,response)
		if response.errCode == 0 then
			ActivityCakeUtils.GetActivityCakeMgr():InitialDojo(response.data)
			self.requestSuccess = true
			local isPlayChapter = checkNumber(CfUtils.GetLocalData(self:GetLocalDataKey(),0)) == 1
			if not isPlayChapter then
				self:OnBtnPlayClick()
			end
			self:Refresh(response.data)
		end
	end)
end

function ActivityMountainOptionEntryDialog:GetLocalDataKey()
	if isNull(self.localDataKey) then
		self.localDataKey = string.format("ActivityMountainOptionEntryDialog_%s",self.activityData.id)
	end
	return self.localDataKey
end

function ActivityMountainOptionEntryDialog:OnBtnExchangeClick()
	local id = self:GetIdByIndex(4)
	local isUnLock = self:IsUnLockFuncById(id)
	if isUnLock then
		CS.Engine.UI.UIModule.OpenDialog({ id = self:GetModuleId(id)},{{id = self.controller.Argument.id }})
	else
		local des = self:GetUnLockDes(id)
		GameUtils.Toast(des)
	end
end

function ActivityMountainOptionEntryDialog:IsActivityClose()
	---@type PlayerComponent
	local comp = GameUtils.GetOrAddEntityCompByType(ECSComponentType.Constants.PlayerComponent)
	if not comp then
		return
	end
	local curTime = comp:GetPlayerDojo():GetServerTime()
	curTime = curTime or os.time()
	return curTime > self.activityData.endTime
end

function ActivityMountainOptionEntryDialog:OnBtnDrawClick()
	local GachaponUtils = import('Game.Gachapon.GachaponUtils')
	GachaponUtils.OpenGachapon(nil, { { id = self.controller.Argument.id } })
end

function ActivityMountainOptionEntryDialog:OnBtnManageClick()
	local isActivityClose = self:IsActivityClose()
	if isActivityClose then
		GameUtils.Toast(localize("活动已经结束"))
		return
	end
	local id = self:GetIdByIndex(5)
	local isUnLock = self:IsUnLockFuncById(id)
	if isUnLock then
		CS.Engine.UI.UIModule.OpenDialog({ id = self:GetModuleId(id)},{{id = self.controller.Argument.id}})
	else
		local des = self:GetUnLockDes(id)
		GameUtils.Toast(des)
	end
end

function ActivityMountainOptionEntryDialog:OnBtnMakeClick()
	local isActivityClose = self:IsActivityClose()
	if isActivityClose then
		GameUtils.Toast(localize("活动已经结束"))
		return
	end
	local id = self:GetIdByIndex(2)
	local isUnLock = self:IsUnLockFuncById(id)
	if isUnLock then
		---@type ActivityCookingComponent
		local ActivityCookingComponent = GameUtils.GetOrAddEntityCompByType(ECSComponentType.Constants.ActivityCookingComponent)
		ActivityCookingComponent:CookingHome({{id=self.controller.Argument.id}})
	else
		local des = self:GetUnLockDes(id)
		GameUtils.Toast(des)
	end
end

function ActivityMountainOptionEntryDialog:OnBtnProtectClick()
	local isActivityClose = self:IsActivityClose()
	if isActivityClose then
		GameUtils.Toast(localize("活动已经结束"))
		return
	end
	local id = self:GetIdByIndex(3)
	local isUnLock = self:IsUnLockFuncById(id)
	if isUnLock then
		CS.Engine.UI.UIModule.OpenDialog({ id = self:GetModuleId(id), parameters = { entryMgr = ActivityCakeUtils.GetActivityCakeMgr() }},{{id = self.controller.Argument.id}})
	else
		local des = self:GetUnLockDes(id)
		GameUtils.Toast(des)
	end
end

function ActivityMountainOptionEntryDialog:OnBtnStoryClick()
	local isActivityClose = self:IsActivityClose()
	if isActivityClose then
		GameUtils.Toast(localize("活动已经结束"))
		return
	end
	local id = self:GetIdByIndex(1)
	CS.Engine.UI.UIModule.OpenDialog({ id = self:GetModuleId(id)}, {{id = self.controller.Argument.id}})
	--CS.Engine.UI.UIModule.OpenDialog({ id = Constants.UITypeIds.ActivityCakeShopMainLineDialog }, {{id = self.controller.Argument.id}})
end

function ActivityMountainOptionEntryDialog:OnImgTitleClick()
	self:OnBtnPlayClick()
end

function ActivityMountainOptionEntryDialog:IsUnLockFuncById(id)
	local homeDojo = ActivityCakeUtils.GetActivityCakeMgr():GetActivityDojo()
	return homeDojo:IsBtnUnLock(id)
end

function ActivityMountainOptionEntryDialog:GetModuleId(id)
	local homeDojo = ActivityCakeUtils.GetActivityCakeMgr():GetActivityDojo()
	return homeDojo:GetModuleId(id)
end

function ActivityMountainOptionEntryDialog:GetUnLockDes(id)
	local homeDojo = ActivityCakeUtils.GetActivityCakeMgr():GetActivityDojo()
	local chapterId = homeDojo:GetUnLockChapterId(id)
	local vo = CfUtils.GetCfVo(AutoIds.IdSetting6240, "ActivityCakeMainLineLevelVo", chapterId)
	if not isNull(vo) then
		return localize("通关故事模式_levelName_后解锁",{_levelName_ = vo.levelName})
	end
	return ""
end

function ActivityMountainOptionEntryDialog:OnBtnPlayClick()
	local homeDojo = ActivityCakeUtils.GetActivityCakeMgr():GetActivityDojo()
	local scheduleVo = homeDojo.scheduleConf
	local ChapterUtils = import('Game.Chapter.ChapterUtils')
	local URPCameraController =  CS.Game.Native.URP.URPCameraController.Instance
	ChapterUtils.ProcessChapter(checkNumber(scheduleVo.storyId), function(go)
		self.controller.gameObject.transform.localPosition = Vector3(9999, 9999, 9999)
		URPCameraController:SetMainCameraActive(false)
		self._plotGo = go
	end, function()
		self.controller.gameObject.transform.localPosition = Vector3(0, 0, 0)
		URPCameraController:SetMainCameraActive(true)
		CfUtils.WriteLocalData(self:GetLocalDataKey(),1)
		ActivityCakeUtils.PlayBgm()
		CfUtils.SafeDelete(self._plotGo)
	end)
end

function ActivityMountainOptionEntryDialog:GetIdByIndex(index)
	return self.activityData.activityContentId * 100 + index
end

return ActivityMountainOptionEntryDialog