---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/4/20 21:19
---  
---
------------ import ------------
local CoWait = CS.Engine.Lib.CoWait
local cardConfMgr = CardConfMgr:GetInstance()
local KTool = CS.Engine.Lib.KTool
local Text = CS.UnityEngine.UI.Text
local Button = CS.UnityEngine.UI.Button
local KCookie = CS.Engine.Lib.KCookie
local UIModule = CS.Engine.UI.UIModule
------------ import ------------
local UIFightChooseCardsAttrNode =  "Game.UI.FightTeam.UIFightChooseCardsDialog.UIFightChooseCardsAttrNode"

---@class UIFightChooseCardsAttrsNode                         
local UIFightChooseCardsAttrsNode = Class("UIFightChooseCardsAttrsNode")

local STATUS = {
    HIDE = 1, 
    SHOW = 2,
}
function UIFightChooseCardsAttrsNode:__init()
    self.status = nil               --当前状态
    self._data = {}
    self._cardData = nil    
    self._isNeedRefresh = true      --是否需要刷新数据        
end

function UIFightChooseCardsAttrsNode:__delete()
    self.status = nil
    self._data = nil
    self._cardData = nil 
    self._isNeedRefresh = nil                   
end

function UIFightChooseCardsAttrsNode:Awake()
    self.status = STATUS.HIDE             --默认隐藏
    SetButtonAction(self.BtnAttr, Bind(self, self.OnBtnShowAttrs))
    CfUtils.FillText(self.TxtDetail, localize("属性详情"))
end

--卡牌数据
function UIFightChooseCardsAttrsNode:Refresh(cardData)
    if not cardData then
        return
    end
    self._cardData = cardData
    self._data = {}
    self._isNeedRefresh = true
end

function UIFightChooseCardsAttrsNode:InitData()
    self._data = {}
    if not self._cardData then
        return
    end

    table.insert(self._data, {
        type = 1,    
        name = localize("主属性")
    })

    FormulaUtils.HandleBasicAttrs(self._cardData, function (basicVo, num, index)
        num = attribute_format(basicVo.isConversion, checkNumber(num))
        table.insert(self._data, {
            type = 2,    
            name = basicVo.name,
            num = num,
        })

        if index == 4 then
            table.insert(self._data, {
                type = 1,    
                name = localize("副属性")
            })
        end
    end)
    
end

function UIFightChooseCardsAttrsNode:OnBtnShowAttrs()
    --打开
    if self.status == STATUS.HIDE then
        if self._isNeedRefresh then
            self:InitData()
            self._isNeedRefresh = false

            if not self._isInitView then
                self.LoopListView:InitListView(#self._data, Bind(self, self.OnGetCellByIndex))
                self._isInitView = true    
            else
                GameUtils.ReloadData(self.LoopListView, #self._data)        
            end
        end

        KTool.SetActive(self.LoopListView, true)
        local rotation = Quaternion.New()
        rotation.eulerAngles = Vector3.New(0, 0, 0)
        self.area.transform.localRotation = rotation
        self.status = STATUS.SHOW
    else
        KTool.SetActive(self.LoopListView, false)
        local rotation = Quaternion.New()
        rotation.eulerAngles = Vector3.New(0, 0, -180)
        self.area.transform.localRotation = rotation
        self.status = STATUS.HIDE
    end
end

function UIFightChooseCardsAttrsNode:OnGetCellByIndex(listView, index)
    if index < 0 then
        return nil
    end

    local data = self._data[index + 1]
    local cell
    if data.type == 1 then
        cell = listView:NewListViewItem("Cell1") 
    else
        cell = listView:NewListViewItem("Cell2") 
    end

    local scr = CfUtils.GetLuaScr(cell, UIFightChooseCardsAttrNode)
    if scr then
        scr:Refresh(data)
    end

    return cell
end

function UIFightChooseCardsAttrsNode:OnDestroy()
    self.controller = nil--luabehaviour 中CSharp对象
    self:Delete()
    self = nil
end

return UIFightChooseCardsAttrsNode





